### ISSUE TITLE
Last edit date returns invalid results

### ISSUE THREAD

**Issue by TaciteOFF** [openfoodfacts/openfoodfacts-server#100]
When I filter my products with "last edit date : 2012" I also get products I have edited in 2015.

http://fr.openfoodfacts.org/contributeur/tacite/date-de-derniere-modification/2012

For instance, "Caramel à tartiner - Pur Bonheur - 200 g" which appears in these results has been edited on 20/04/15.

**Comment by hangy** [comment]
The list is empty now. I suppose this is fixed.
