### ISSUE TITLE
In India, make the default unit for sodium mg instead of g on product edit form on web and mobile app

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#10038]
[Reported by krishanti on Slack](https://openfoodfacts.slack.com/archives/CDX0VQ0TS/p1711414340376119): "Please consider setting the default unit for Sodium as mg instead of grams as that is the unit commonly seen on nutrition labels. While editing products I've seen that sometimes the unit is mistakenly ignored and the nutriscore becomes inaccurate"

in the taxonomies/nutrients.txt, we can define default units for ingredients for a specific country. e.g. this states that for energy, the default unit is kj in all countries except Canada and the US:

unit:en: kj
unit_ca:en: kcal
unit_us:en: kcal

There is some code in product_multilingual.pl that then uses it to display the right unit on the product edit form on the web site:

```
		if (exists_taxonomy_tag("nutrients", "zz:$nid")) {
			$nutriment_ref->{name} = display_taxonomy_tag($lc, "nutrients", "zz:$nid");
			# We may have a unit specific to the country (e.g. US nutrition facts table using the International Unit for this nutrient, and Europe using mg)
			$unit = get_property("nutrients", "zz:$nid", "unit_$cc:en")
				// get_property("nutrients", "zz:$nid", "unit:en") // 'g';
		}
```

This code should be moved to a function in Food.pm, and it should also be called in cgi/nutrients.pl so that we get the right unit for countries. /cgi/nutrients.pl is used by the OFF mobile app.

### Part of
- #6540

**Comment by himanshisrestha** [comment]
I'll start working on this
