### ISSUE TITLE
Code crash for EMB suggestions

### ISSUE THREAD

**Issue by monsieurtanuki** [openfoodfacts/openfoodfacts-server#10049]
### What
- The problem started a few days ago, perhaps from @damil's https://github.com/openfoodfacts/openfoodfacts-server/commit/bf084bbe8ce263cea2eee7f53dcae634fcf1f2eb?
- Don't know if it's a problem of data (not supposed to have quotes in the results), code or settings.

### Steps to reproduce the behavior
https://world.openfoodfacts.org/api/v3/taxonomy_suggestions?tagtype=emb_codes&lc=fr&string=fR&limit=25

```
Software error:
Can't use string ("FR 01.004.002 EC") as a HASH ref while "strict refs" in use at /srv/off/lib/ProductOpener/APITaxonomySuggestions.pm line 133.
For help, please send mail to the webmaster ([contact@openfoodfacts.org](mailto:contact@openfoodfacts.org)), giving this error message and the time and date of the error.
```

**Comment by hangy** [comment]
Not bf084bbe8ce263cea2eee7f53dcae634fcf1f2eb. I can also reproduce the bug in the parent commit 0627780c26912223698ad191eb9dbd34a1515ce8.

**Comment by stephanegigandet** [comment]
The bug was probably introduced by https://github.com/openfoodfacts/openfoodfacts-server/pull/9395/files , I will fix it
