### ISSUE TITLE
Make Button Texts Visible on Edit Organization Profile Page

### ISSUE THREAD

**Issue by TheSussex** [openfoodfacts/openfoodfacts-server#10057]
### What
- In the 'Edit your organization profile' of the producer platform, the action buttons of the forms do not have a visible value/text.

### Steps to reproduce the behavior

1. Go to 'https://world.pro.openfoodfacts.org/'
2. Log in to with you producer details
3. Click on the dropdown beside the User's name in the far right and select 'Edit your organization profile'
4. You will see that the buttons on that page have no text.

Here is [a link to the conversation on Slack](https://openfoodfacts.slack.com/archives/C02LDQDDD/p1711439491211779).

### Screenshot
![Screenshot 2024-03-25 at 12 46 31 PM](https://github.com/openfoodfacts/openfoodfacts-server/assets/64183728/efc033cf-43c8-4253-957e-b1fb7dbf0aae)

### Type of device
- Browser: Google Chrome (Version 123.0.6312.87)

**Comment by TheSussex** [comment]
I'm curious to know long it typically take for updates to go live/get deployed? @alexgarel 

This was merged about an hour ago but the issue still persists on the page in production.

**Comment by manon-corneille** [comment]
Hi all,
 
Thank you @TheSussex for having fixed it :) 

Just fyi, the issue still persists in prod as of today.

**Comment by TheSussex** [comment]
Hi @manon-corneille, I just checked prod a minute ago and the issue has been fixed. Maybe try to refresh the page.

<img width="1434" alt="Screenshot 2024-04-15 at 9 14 14 AM" src="https://github.com/openfoodfacts/openfoodfacts-server/assets/64183728/404b447c-11cb-4bea-b05b-d688827aeb66">

**Comment by alexgarel** [comment]
It's on producers platform that it persists, I think @stephanegigandet did not deploy the new version on the producer platform last week.
