### ISSUE TITLE
"https" NET::ERR_CERT_DATE_INVALID

### ISSUE THREAD

**Issue by monsieurtanuki** [openfoodfacts/openfoodfacts-server#10056]
### What
https://world.openfoodfacts.org/api/v3/product/0030000010204/?lc=en%2Cfr&tags_lc=en&app_name=off-dart+integration+tests
![Capture d’écran 2024-03-30 à 09 39 45](https://github.com/openfoodfacts/openfoodfacts-server/assets/11576431/5ba76df1-fc88-4f24-a95a-cee7c762293b)
![Capture d’écran 2024-03-30 à 09 39 27](https://github.com/openfoodfacts/openfoodfacts-server/assets/11576431/d5b3ae73-37a8-4a59-ae9d-2375ff7b7f59)

**Comment by teolemon** [comment]
We're on it. Normally renewal is automated.

**Comment by teolemon** [comment]
fixed @monsieurtanuki

**Comment by teolemon** [comment]
- https://github.com/openfoodfacts/openfoodfacts-infrastructure/issues/330
