### ISSUE TITLE
Text on buttons has disappeared on the “Edit the profile of your org” page on the Pro platform

### ISSUE THREAD

**Issue by manon-corneille** [openfoodfacts/openfoodfacts-server#10071]
The text on **all buttons**on the “Edit the profile of your org” page is missing. 

![Image](https://github.com/openfoodfacts/openfoodfacts-server/assets/104015489/c44b32bb-eaee-4da5-b6e1-d9ca4c54a2f0)

**Comment by TheSussex** [comment]
I believe this is the same issue I reported at https://github.com/openfoodfacts/openfoodfacts-server/issues/10057

I have created a PR that should fix it.

**Comment by alexgarel** [comment]
@stephanegigandet we still need a deploy on pro platform to fix this !

**Comment by stephanegigandet** [comment]
The fix has been deployed in production, closing the issue.
