### ISSUE TITLE
Delete the button "Join the next Pro meetup" on the Pro platform

### ISSUE THREAD

**Issue by manon-corneille** [openfoodfacts/openfoodfacts-server#10070]
Delete the button "Join the next Pro meetup" on the Pro platform in the hamburger menu. 
After being tested several times, it turns out this format of support sessions doesn't really work for producers so we don't need the button anymore. 

![Image](https://github.com/openfoodfacts/openfoodfacts-server/assets/104015489/555a183d-7adc-49f5-bd77-0c0cdc5805b6)

**Comment by himanshisrestha** [comment]
I would like to work on this issue
