### ISSUE TITLE
Contribution tab link is going to empty when you are not logged in (I think it's meant to jump on the Data Quality panel)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#10109]
Contribution tab link is going to empty when you are not logged in (I think it's meant to jump on the Data Quality panel)

_Originally posted by @teolemon in https://github.com/openfoodfacts/openfoodfacts-server/pull/10106#issuecomment-2043140991_

**Comment by alexgarel** [comment]
Normally it was meant to be like it because you can see data source and authors (which is part of contribution)

![image](https://github.com/openfoodfacts/openfoodfacts-server/assets/144788/c37a154f-7519-46e8-bfad-48c97fee1849)
