### ISSUE TITLE
Add candy category

### ISSUE THREAD

**Issue by odin-h** [openfoodfacts/openfoodfacts-server#10139]
### Problem
Many stores have a pick and mix candy section where you can buy candy in bulk in a designated paper bag or cardboard container and pay per kg or full container. There does not currently seem to be a category for this.

### Proposed solution
Add a "Candy" category or something to allow for tracking the price.

**Comment by odin-h** [comment]
This issue for intended for [openfoodfacts/open-prices-frontend](https://github.com/openfoodfacts/open-prices-frontend). Clicked the wrong tab. Sorry about that!

**Comment by aleene** [comment]
You were in the right place, as prices uses the off taxonomies.

**Comment by odin-h** [comment]
But, there is already a taxonomy for the `en:candies` category. I only wanted that category to be part of the final "raw categories" list, over on [Open Prices](https://prices.openfoodfacts.org/app/add/single), after it's been filtered. Unless we're going to make a new category  for "_candies from pick and mix section_" and not just use `en:candies` for that purpose, this probably was the wrong place to open this issue?

**Comment by teolemon** [comment]
Sorry, I moved it because I thought a "Candy assortment" category could do the trick
