### ISSUE TITLE
Check for spaces in nutrition fields

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#1018]
Remove any spaces in nutrition fields.

**Comment by hangy** [comment]
Like leading and trailing spaces for the nutrient text? I thought the calculated `$nid` should not contain any spaces by definition ... do you have any example product? 😄

**Comment by aleene** [comment]
I do not quite remember what was the issue. I guess it is about the value fields in the json, which are exprssed as strings. I guess there are indeed some leading and or trailings spaces. I assume I had to remove those before I could use them, so it is better that off does provide nice strings in the first place.

Alas no example.

**Comment by hangy** [comment]
> so it is better that off does provide nice strings in the first place.

It should. 👍 

> Alas no example.

No worries. Thanks for looking into it! I'll see if we need to trim some leading/trailing spaces for the nutrition ids. 😃

**Comment by hangy** [comment]
So, it's definitely possible to create a custom nutrient label with leading and trailing whitespace. The whitespace is removed for the JSON key, but it's preserved in the label and value. 

```
"nutriments":{"asdffu-asdfu_serving":"","tab_serving":"","asdffu-asdfu_value":"  asdklasjd 390 löasd","tab_100g":"10","asdffu-asdfu":0,"asdffu-asdfu_unit":"g","asdffu-asdfu_100g":"0","tab_label":"\ttab\t","tab_unit":"g","asdffu-asdfu_label":"  asdffu asdfu","tab_value":"\t10 g\t","tab":10}
```

**Comment by aleene** [comment]
I remember now what the issue was. I encountered value fields that were not empty, but contained a space. It seemed like the user entered just a space to indicate that there was no value. I guess that off can clear those ‘empty’ fields.
