### ISSUE TITLE
Add an issue field to a product

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#1019]
### What
- Add a field to report an issue with a product. This can have a few presets to signal noteworthy product (delete, etc) and a field the user can fill.

### Part of
- #5538

**Comment by hangy** [comment]
Just an idea: We could store issues in a different MongoDB collection and not as normal fields. They might not be of much value to API consumers.

**Comment by aleene** [comment]
Indeed this is not about the product, but about the quality of the data. It should be easier to track down errors and be able to repair them. Adding the issues to a wiki page is to cumbersome.

**Comment by aleene** [comment]
too old
