### ISSUE TITLE
Folksonomy engine does not get barcode on some products and can't add properties

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-server#10220]
Alizarine spotted a bug: 

> I can't add this property to this product: https://world.openfoodfacts.org/product/2000000218021/12-macarons-plaisir-patissier#
> I hit "submit" nothing happens :(

It's the json that is sent that is wrong so it's an issue with the JS 
```json
{"product": "undefined", "k": "ingredient_list:multiple", "v": "6", "owner": ""}
```

`"product"` is wrong

In folksonomy.js, code is retrieved with `code = $("#barcode").html();`, maybe this value is not available ?

**Comment by teolemon** [comment]
- Please see: https://github.com/openfoodfacts/openfoodfacts-server/issues/7267 @alexgarel

**Comment by alexgarel** [comment]
duplicate of https://github.com/openfoodfacts/openfoodfacts-server/issues/7267
