### ISSUE TITLE
Store org data in MongoDB to ease pro platform dashboard

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#10245]
We currently store organization objects in .sto files in the orgs directory.
In addition, we should also store this data in a new "orgs" collection of the "off" database in MongoDB.

This will be useful in particular to create a dashboard for the administrators of the pro platform, with a table that lists all organizations (https://github.com/openfoodfacts/openfoodfacts-server/issues/9737)

Related code is in lib/ProductOpener/Orgs.pm (see also data.pm and Products.pm at the end of store_product() to see how we store product data in MongoDB).

**Comment by john-gom** [comment]
Do we need to replicate in MongoDB if we are also going to replicate in off-query too? If we can create redis events with all of the needed data we can hydrate this directly in off-query without the need for MongoDB
