### ISSUE TITLE
[a11y] Footer - Image elements don't have a alt attribute

### ISSUE THREAD

**Issue by g123k** [openfoodfacts/openfoodfacts-server#10286]
Hi everyone,

To improve accessibility on the website, we have some "simple" fixes to implement.
Here, we have a ton of `img` tags without the `alt` attribute:

- [ ] The "Download on the App Store" banner
- [ ] The "Get it on Google Play" banner
- [ ] The "Get it from Microsoft" banner
- [ ] The "Android apk" banner

**Comment by Valimp** [comment]
I have the impression that the alts on the images concerned are present

<img width="752" alt="Capture d’écran 2024-05-16 à 10 02 09" src="https://github.com/openfoodfacts/openfoodfacts-server/assets/112864841/ff0f7c07-0f46-4f08-8692-5223b336b412">

**Comment by g123k** [comment]
> I have the impression that the alts on the images concerned are present
> 
> <img alt="Capture d’écran 2024-05-16 à 10 02 09" width="752" src="https://private-user-images.githubusercontent.com/112864841/331107536-ff0f7c07-0f46-4f08-8692-5223b336b412.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NDY5MjgsIm5iZiI6MTcxNTg0NjYyOCwicGF0aCI6Ii8xMTI4NjQ4NDEvMzMxMTA3NTM2LWZmMGY3YzA3LTBmNDYtNGYwOC04NjkyLTUyMjNiMzM2YjQxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQwODAzNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YTEwMzFlMjYxMjZmYzUzMGEwODZjMTRjYTlhMTJjZDUwNTUzMmQxODIzMGUyOTYwNTdiYTJiZjRmYTU5YTJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9z_pEq-oJ5JECRWXldyQffk_l3dDPTSjCLqD_c8j7CU">

Yes, exactly.
I don't know why, but I'm pretty sure the other day it was not the case.
