### ISSUE TITLE
Add middleware to add images to a Pastec.io index for magic image recognition

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1031]
http://pastec.io/doc/api/
This is fully open source "magic" image recognition, without barcode.

We send an image through the backend to a separate, dedicated server for image recognition.

```
Adding an image to the index
This call allows to add the signature of an image in the index to make it available for searching. You need to provide the compressed binary data of the image and an id to identify it.

URL: https://api.pastec.io/indexes/<your index id>/images/<image id>
HTTP method: PUT
Data: the binary data of the image to add compressed in JPEG
Answer type: "IMAGE_ADDED"
Possible error types: "IMAGE_NOT_DECODED", "IMAGE_SIZE_TOO_BIG", "IMAGE_SIZE_TOO_SMALL"
Example:
Command line:
curl --header "AuthKey: dummy_auth_key" -X PUT --data-binary @/home/test/img/1.jpg https://api.pastec.io/indexes/dummy_index/images/23
Answer:
{
   "image_id" : 23,
   "type" : "IMAGE_ADDED"
}

```

**Comment by hangy** [comment]
The hosted version at http://api.pastec.io seems to be dead, and the project's GitHub page has not been updated in a while. We'd have to host it on our own. From what I've read, it could be used to find part of the image in a search request in the index … but what's the use case for OFF?

**Comment by stephanegigandet** [comment]
The pastec.io project and web site look dead. Closing.
