### ISSUE TITLE
Footer placeholder broken for Pro Platform

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#10349]
### Problem
- Footer placeholder broken for Pro Platform
- https://world.pro.openfoodfacts.org/

### Screenshot
![image](https://github.com/openfoodfacts/openfoodfacts-server/assets/1689815/faf5c97d-6a3a-4485-b18c-3de6b0ed7234)

**Comment by 4nt0ineB** [comment]
Seems fixed
<img width="55%" src="https://github.com/openfoodfacts/openfoodfacts-server/assets/56827368/1b84f278-7381-4241-bf82-e2da04c41ecf">
