### ISSUE TITLE
Lazy loading for images on lists

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#10342]
The home page and all other pages listings products (100 by default) are making more than 190 http requests: 100 of them are for images, and many of them are never seen by the users because the latter don't scroll down.

I'm not an expert of it, but lazy loading seems nowadays easy to implement: just adding `loading="lazy"` to each image?

**Comment by stephanegigandet** [comment]
Fixed by https://github.com/openfoodfacts/openfoodfacts-server/pull/10343
