### ISSUE TITLE
Remove "report a problem" entry in product navigation for producers platform

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-server#10359]
### Problem

On producer platform, we display the "report a problem" entry in product nav bar, while there is no corresponding knowledge panel, as it makes no sense (this is not public data).

### Proposed solution

Remove the entry in the menu if the knowledge panel is not there.

**Comment by subi9** [comment]
@alexgarel Can you please suggest some products/links where "report a problem" knowledge panel is not present. I have checked some products where knowledge panel as well as the menu is present.

**Comment by stephanegigandet** [comment]
@subi9 This is on the producers platform (pro platform).  https://github.com/openfoodfacts/openfoodfacts-server/blob/main/docs/dev/how-to-develop-producer-platform.md

**Comment by teolemon** [comment]
It happens for 100% of products, it's a partly implemented feature, we should have removed the top button when we removed the panel.
The location is here @subi9 : https://github.com/openfoodfacts/openfoodfacts-server/blob/main/templates/web/pages/product/product_page.tt.html#L93
