### ISSUE TITLE
Expose product recalls warnings in the API

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1035]
### What
- expose product warnings in the API so that the native apps can use them as well.
- Those messages we display for Salmonella products: https://github.com/openfoodfacts/openfoodfacts-server/commit/c2af92abb9f9376ebe4d56fe1290323c929217b5
- from dwarfex There is an EU provided Website (RASFF Portal), which lists urgent product recalls:
webgate.ec.europa.eu/rasff-window/consumers/?event=home
- https://wiki.openfoodfacts.org/Product_Recalls

### Part of
- #5493

**Comment by hangy** [comment]
Which warnings?

**Comment by teolemon** [comment]
https://github.com/openfoodfacts/openfoodfacts-server/commit/c2af92abb9f9376ebe4d56fe1290323c929217b5

**Comment by teolemon** [comment]
@hangy @stephanegigandet I've created a label for those (infoboxes).

**Comment by teolemon** [comment]
- closing in favor of : https://github.com/openfoodfacts/openfoodfacts-server/issues/56
