### ISSUE TITLE
Add quality facets based on the opposite: property, and on mutually-exclusive tag values

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#10372]
### What
- Add quality facets based on the opposite: property, and on mutually-exclusive tag values
- I have started listing intersections that should be empty or emptier (category X category, category X label, label X origin…): https://wiki.openfoodfacts.org/Data_quality_missions#Intersections_to_check_regularly
- We (mostly @aleene and @stephanegigandet) have in the past added `opposite:` properties to taxonomy but never leveraged them
- We could start generating additional quality facets based on those, that would be helpful for the Real-time Data Quality API, to prevent such logic bombs before they happen

**Comment by benbenben2** [comment]
Interesting. That would be warnings or errors? I guess, we can start with warnings, no?

Looking at the taxonomy, there are indeed such properties in labels.
They are used in Import.pm.

**Comment by teolemon** [comment]
Yes, warnings are good enough. Ideally, some of those we could almost autofix based on other fields like ingredients.
Some brands belong to some countries, I just spotted a French retailer brand (Auchan) as sold in the US.
Hopefully, we'll add more constraints in various taxonomies, and we'll spot more of those. But I'm very seduced by the notion of "suggested fix"
