### ISSUE TITLE
Better computation of NOVA 4 in German

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-server#10415]
[From the forum](https://forum.openfoodfacts.org/t/please-add-to-the-nova-4-list/579):

> At least for German products many which belong to the NOVA group 4 are missed and are only NOVA 3.

> * “modifizierte Stärke” = “modified starch” = chemically or physically treated plant (wheat, corn) starch to modify its properties
> * “Glukosesirup” = “glucose syrup” = plant (wheat, corn) starch treated with enzymes (amylases and amyloclucosidases) to split it in shorter chains up to glucose
> * “Glucose-Fructose-Sirup” = “glucose-fructose-syrup”, also known as “high fructose corn syrup” (HFCS), from enzyme treated starch as before, “Glukose” (glucose) and “Fruktose” (fuctose) in products are in many cases produced in this way, and should be also added
> * “*extrakt” e.g “Gewürzextrakt” = “*extract” e.g. “spice extract” = “100% natural” raw materials, from whatever sources, which has been fractional extracted and optionally mixed to form the declared extract, used as “natural” aroma in most cases
> * “*erzeugnis” e.g. “Milcheiweißerzeugnis” = catch-all declaration for all kinds or industrial proccessed “100% natural” raw substances
> * “whey protein concentrate” or “WPC” = size-fractionated whey protein as waste from cheese production, filtered by size by pressing it through menbranes

**Comment by aleene** [comment]
Where are the nova levels defined? Shouldn't that be in taxonomy?

**Comment by stephanegigandet** [comment]
@aleene From the nova:en: property in ingredients and categories taxonomies.

**Comment by aleene** [comment]
I did not add extract as that is very broad, we could add it to several children, which?

**Comment by aleene** [comment]
WPC is created by filtering? When is this acceptable and when not?

**Comment by stephanegigandet** [comment]
> I did not add extract as that is very broad, we could add it to several children, which?

I'll ask the team of Carlos Monteiro
