### ISSUE TITLE
API not working because of internal server error

### ISSUE THREAD

**Issue by alexk1923** [openfoodfacts/openfoodfacts-server#10416]
### What
API does not work for either web interface or axios request. Inte

### Steps to reproduce the behavior

1. Go to [ openfoodfacts.github.io/](https://openfoodfacts.github.io/openfoodfacts-server/api/ref-v2/#get-/api/v2/product/-barcode-)
2. Search a product by barcode or try the default value
3. A server error will be returned.

Software error:
Cannot write to '/mnt/podata/logs/ratelimiter_log4perl.log':  at /usr/share/perl5/Log/Log4perl/Appender/File.pm line 313.
For help, please send mail to the webmaster ([contact@openfoodfacts.net](mailto:contact@openfoodfacts.net)), giving this error message and the time and date of the error.

### Expected behavior
- A product data should be returned, either it does exist or not

### Why
- the API does not work

### Type of device
 
<!-- 
- Browser: Google Chrome Version 125.0.6422.142 (Official Build) (64-bit)
- REST-API

### Number of products impacted
- all

### Time per product
- cannot use the api

**Comment by stephanegigandet** [comment]
It is working for me currently.

![image](https://github.com/openfoodfacts/openfoodfacts-server/assets/8158668/d82fec70-7127-42e5-9683-70a8b6782fbf)
