### ISSUE TITLE
Nouvelle facette : picture_upload_date

### ISSUE THREAD

**Issue by TaciteOFF** [openfoodfacts/openfoodfacts-server#1045]
Sur le même modèle que last_edit_date, on pourrait imaginer une facette permettant de lister les produits sur lesquelles aucune photo n'a été uploadée depuis un certain temps.
Ca permettrait de mettre à jour les emballages des produits que nous avons depuis 2013 par exemple.
A l'heure actuelle le last_edit_date ne le permet pas car un produit de 2013 dont on corrige le nom en 2018 devient un produit de 2018.

**Comment by stephanegigandet** [comment]
I had forgotten about it, but we have already done that: https://world.openfoodfacts.org/last-image-dates
