### ISSUE TITLE
Reference to Interesting Views to delte

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1046]
b/lang/es/texts/conditions-d-utilisation.html
Reference to interestingviews

**Comment by teolemon** [comment]
lang/en/texts/mode-d-emploi.html
Reference to interestingviews

**Comment by teolemon** [comment]
lang/ar/texts/contact.html
Reference to interestingviews

**Comment by teolemon** [comment]
lang/ar/texts/mode-d-emploi.html
IV

**Comment by teolemon** [comment]
lang/ar/texts/conditions-d-utilisation.html

**Comment by CloCkWeRX** [comment]
I can only find https://github.com/openfoodfacts/openfoodfacts-server/blob/31bea82fb255011bc2055742c99cecd3c1f6ccc6/lang/ar/texts/conditions-d-utilisation.html now - is this issue still relevant? (Should that be removed?)
