### ISSUE TITLE
Ask to confirm a detected category

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1048]
![image](https://user-images.githubusercontent.com/1689815/35644196-a120a1fc-06c8-11e8-816d-64fef9fc9aa1.png)
Try to detect category from product name, and ask logged in users to validate it .

**Comment by teolemon** [comment]
Reusing the same logic for the Hercberg matching script

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/38606609-d0aaa0be-3d76-11e8-9d45-41a1b944672a.png)

**Comment by teolemon** [comment]
Categories suggestion by attempting to parse the product name with the Categories taxonomy

**Comment by raphael0202** [comment]
Closing, as it is provided by Robotoff
