### ISSUE TITLE
Missions pages have disappeared

### ISSUE THREAD

**Issue by nicolasleger** [openfoodfacts/openfoodfacts-server#1049]
## Empty Missions list (from homepage link)
- https://fr.openfoodfacts.org/missions
- https://world.openfoodfacts.org/missions

## Empty Mission page (from contributor link)
- https://fr.openfoodfacts.org/mission/informateur-100-produits
- https://world.openfoodfacts.org/mission/armoire-a-glaces

## But Missions list is well displayed on Contributor page
- https://fr.openfoodfacts.org/contributeur/tacite
- https://world.openfoodfacts.org/contributor/tacite

**Comment by hangy** [comment]
As far as I know, the old missions have been deprecated.
