### ISSUE TITLE
[FOUNDATION] [CORDOVA] Images shown twice in product page in Cordova app

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#105]
Bug introduced by the Foundation redesign.

**Comment by teolemon** [comment]
![screenshot_2015-05-11-11-14-25](https://cloud.githubusercontent.com/assets/1689815/7561852/a592d896-f7cf-11e4-92b3-06cdb2379f67.png)

**Comment by teolemon** [comment]
Is that related to the HTTP header you're sending for licence ?

**Comment by stephanegigandet** [comment]
No, it's because I use the same function than the one I use for the website which now uses the Foundation classes:

````
<img class="hide-for-xlarge-up" src="/images/products/$path/$id.$rev.$size.jpg" width="$product_ref->{images}{$id}{sizes}{$size}{w}" height="$product_ref->{images}{$id}{sizes}{$size}{h}" alt="$alt" />
<img class="show-for-xlarge-up" src="/images/products/$path/$id.$rev.$display_size.jpg" width="$product_ref->{images}{$id}{sizes}{$display_size}{w}" height="$product_ref->{images}{$id}{sizes}{$display_size}{h}" alt="$alt" />
````

But the app knows nothing about those classes, so it shows both the small and the large images.

**Comment by stephanegigandet** [comment]
Fixed.
