### ISSUE TITLE
Add a user related events Redis queue

### ISSUE THREAD

**Issue by 4nt0ineB** [openfoodfacts/openfoodfacts-server#10528]
To be able to track user related events we must add a Redis queue.

We want to record these data for a **login**, a **creation**, and **deletion** : 
timestamp / userid / organization / country (ip)

We must await for Keycloak integration in Product Opener

**Comment by hangy** [comment]
Maybe https://skycloak.io/auditing-in-keycloak-how-to-catch-them-all/? ProductOpener isnt's supposed to be responsible for user management for too long, any more

**Comment by 4nt0ineB** [comment]
Ah yes, I forgot for a moment
