### ISSUE TITLE
Add Vegan/Non Vegan detection

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1052]
- A list of 600 non vegan ingredients: https://github.com/hmontazeri/is-vegan 
Let's start by flagging clearly non-vegan products
```
Vegan: This product is not vegan
Vegan: We could not determine the status of this product with certainty.
```

**Comment by policorn** [comment]
I'd like to work in this one : )

**Comment by teolemon** [comment]
You can go ahead :-D

**Comment by sandy9999** [comment]
Would a vegan/non-vegan detection be enough? I think a better classification would be:
1) Vegan
2) Vegetarian
3) Eggetarian
4) Non-vegetarian

In my country, most people belong predominantly to 2, 3 and 4. Also, this could help with respect to Indian and Srilankan products.

<a>https://en.wikipedia.org/wiki/Vegetarian_and_non-vegetarian_marks</a>

**Comment by teolemon** [comment]
Fixed apart from the Eggetarian thing.

**Comment by aleksejrs** [comment]
The "Non-vegan" sign contains a leaf and is red. I guess that might look just like "contains a leaf and is green" to [many people](https://en.wikipedia.org/wiki/Color_blindness#Epidemiology) (fortunately the text helps).

**Comment by jolesh** [comment]
> The "Non-vegan" sign contains a leaf and is red. I guess that might look just like "contains a leaf and is green" to [many people](https://en.wikipedia.org/wiki/Color_blindness#Epidemiology) (fortunately the text helps).

@aleksejrs you might want to create a new issue for it.

**Comment by jolesh** [comment]
@teolemon Can we close the issue or should we also fix the Eggetarian thing?

**Comment by stephanegigandet** [comment]
Vegan and vegetarian detection has been implemented, closing this.
