### ISSUE TITLE
Expose the GeoIP API for the mobile app

### ISSUE THREAD

**Issue by g123k** [openfoodfacts/openfoodfacts-server#10594]
Hi everyone,

In the OFF mobile application, we’d like to identify the user’s country based on the IP (it’s not perfect, but it’s good enough).
I know a GeoIP implementation is used on the server.

Would it be possible to expose it as an API?

**Comment by stephanegigandet** [comment]
@4nt0ineB maybe add a few tests for the new API, to make sure we don't break it in the future

**Comment by g123k** [comment]
Thanks for the PR.

However, getting the public IP from Dart is impossible without an external service (ex : IPify).
Would it be possible to change the endpoint from:
`https://world.openfoodfacts.net/api/v3/geoip/85.214.132.117`
to
`https://world.openfoodfacts.net/api/v3/geoip/`

Basically, if the IP is missing, use the one from the request?
