### ISSUE TITLE
Synonyms in taxonomized suggestions are broken

### ISSUE THREAD

**Issue by October-Food-Facts** [openfoodfacts/openfoodfacts-server#10632]
### What
- Synonyms are no longer suggested in tag fields.
- This feature stopped working: [feat: Synonyms in taxonomized suggestions #9395](https://github.com/openfoodfacts/openfoodfacts-server/pull/9395)

How it used to be:
![Past](https://github.com/user-attachments/assets/a148e59c-3c2a-42bb-8f6b-a841fa7af10c)

How it is now:
![Present](https://github.com/user-attachments/assets/a9c8eb54-b09a-4849-81af-a211f7b005b3)

**Comment by Naruyoko** [comment]
This line is the culprit.
https://github.com/openfoodfacts/openfoodfacts-server/blob/c6a0564dcb3933908b64fb52cd1b79db29de6c40/html/js/product-multilingual.js#L592

Compare:
https://github.com/openfoodfacts/openfoodfacts-server/blob/908603ab4eeff16e55b9a68873379db50a9e19cb/html/js/product-multilingual.js#L582

**Comment by October-Food-Facts** [comment]
If this can be fixed, it would be great, because the taxonomies are really, really difficult to fill-in and end up taking hours of work to figure out. Without the synonyms, it's only so much harder.
