### ISSUE TITLE
"Evolution of the number of products" chart not showing for world

### ISSUE THREAD

**Issue by 4nt0ineB** [openfoodfacts/openfoodfacts-server#10645]
### What

The chart "Evolution of the number of products on Open Food Facts" is not showing at [world.openfoodfacts.org/products](https://world.openfoodfacts.org/products).
but [fr.openfoodfacts.org/produits](https://fr.openfoodfacts.org/produits) does.

**Comment by teolemon** [comment]
world.openfoodfacts.org/product-count @4nt0ineB we moved it there because it was creating conflicts with another URL

**Comment by 4nt0ineB** [comment]
> world.openfoodfacts.org/product-count @4nt0ineB we moved it there because it was creating conflicts with another URL 
Oh ok
