### ISSUE TITLE
Broken links to /data /terms-of-use /legal in footer (translated without corresponding text)

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#1068]
The footer contains those links:
 <li><a href="$Lang{footer_legal_link}{$lc}">$Lang{footer_legal}{$lc}</a></li>
 <li><a href="$Lang{footer_terms_link}{$lc}">$Lang{footer_terms}{$lc}</a></li>
 <li><a href="$Lang{footer_data_link}{$lc}">$Lang{footer_data}{$lc}</a></li>

if the footer_[..]_link are translated in the po files, then a corresponding file needs to exist in /lang/[lc]/[text id].html

e.g. on production, https://fr.openfoodfacts.org links to https://fr.openfoodfacts.org/donn%C3%A9es which does not exist.

I'm going to add test so that the build fails when those links are broken.

**Comment by teolemon** [comment]
@stephanegigandet I think we can close this one
