### ISSUE TITLE
Totals incorrect

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#10719]
### What
When doing a facet search the totals do not correspond to number of products shown.

### Steps to reproduce the behavior
1. \\see https://nl.openfoodfacts.org/status/ingredienten-invullen/status/foto-van-de-ingredienten-geselecteerd

### Expected behaviour
Correct totals

### Screenshot/Mockup/Before-After
<img width="1103" alt="Screenshot 2024-08-21 at 08 55 44" src="https://github.com/user-attachments/assets/f770dc20-e795-4784-b682-a5d8deb82f1b">

**Comment by October-Food-Facts** [comment]
This made me recall the super-useful advice that you gave me when I presented this exact same issue:
> Adding &nocache=1 will solve this. The cache is not working well.
https://openfoodfacts.slack.com/archives/C02KVRT2C/p1710188059833059?thread_ts=1710149137.656589&cid=C02KVRT2C

**Comment by aleene** [comment]
You are right. I forgot about that. It makes the totals correct.
