### ISSUE TITLE
Product code stored as number in MongoDB

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#1077]
At least one product has its code stored as a number instead of a string in mongodb:

db.products.find({_id: "0048151623426"})
{ "_id" : "0048151623426", "generic_name_en" : "DO NOT DELETE", "rev" : 35, "nutrient_levels_tags" : [ ], "ingredients_ids_debug" : [ "api-tests-should-be-done-on-the-net-domain", "not-here" ], "categories_prev_tags" : [ ], "creator" : "tacite", "generic_name" : "DO NOT DELETE", "categories_hierarchy" : [ ], "traces" : "", "ingredients_text_with_allergens_en" : "API Tests should be done on the .net domain, not here.", "emb_codes_tags" : [ ], "additives_prev_original_tags" : [ ], "nutrition_data_per_debug_tags" : [ ], "origins" : "", "code" : NumberLong("48151623426"),

The .sto file has the code stored as a string: 35.sto
0048151623426^@^D^@^@^@code^

There is some code in Products.pm to prevent that from happening, I do not know what happened here.

Need to check if other products are affected.

**Comment by stephanegigandet** [comment]
Lots of products have code stored as a number in the db:

> db.products.count ( {"code" : { $type: "long"} })
192962
> db.products.count ( {"code" : { $type: "string"} })
229387

**Comment by stephanegigandet** [comment]
culprit is the update_all_products.pl script

fixing it and re-running it.

**Comment by stephanegigandet** [comment]
Still affecting some products.

> db.products.count ( {"code" : { $type: "long"} })
71486

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/36356802-8002a87a-14f7-11e8-977d-099d64d57f05.png)

**Comment by stephanegigandet** [comment]
I thought re-running the update_all_products.pl script after fixing it would fix the issue, but it only fixed it for products without leading 0 in the code. I'm running a new fix.

> db.products.count ( {"code" : { $type: "long"} })
71418
> db.products.count ( {"code" : { $type: "long"} })
67683

**Comment by stephanegigandet** [comment]
There might be issues for products with leading 0s that have been edited in the last few days, not sure.

**Comment by stephanegigandet** [comment]
The script finished, all codes are now strings:
> db.products.count ( {"code" : { $type: "long"} })
0

**Comment by stephanegigandet** [comment]
US front page looks good: 

![image](https://user-images.githubusercontent.com/8158668/36373161-8867bf30-1567-11e8-9ab9-2d2ba15ff77e.png)

**Comment by hangy** [comment]
I think we should consider moving to using an `ObjectId` as the primary key of the products collection. Right now, we store the code in `_id` and in the `_code` field. Apparently, we also have products where both fields do not match

```
> db.products.find({ $where : "this._id !== this.code" }).count()
3349
```

Selected examples
```
{ "_id" : "2000000001702", "code" : "203474683" }
{ "_id" : ObjectId("57d139e83296350bfc5a9271") }
{ "_id" : "00574082", "code" : 574082 }
```

That would also be a better base for #637 and unique product ids (that could be useful for #677)

**Comment by OpenChris** [comment]
Still seeing the "code" stored as Int32 issue, for example, product 00735346.

**Comment by stephanegigandet** [comment]
db.products.count ( {"code" : { $type: "long"} })
0

**Comment by stephanegigandet** [comment]
> db.products.count ( {"code" : { $type: "int"} })
3137

**Comment by hangy** [comment]
> db.products.count ( {"code" : { $type: "long"} })
0
> db.products.count ( {"code" : { $type: "int"} })
0
