### ISSUE TITLE
Create a "Data Donation" page for manufacturers

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1078]
Create a "Data Donation" page for manufacturers to explain them:
- the advantages of getting their data into OFF
- what they are signing up for
- the technical details
- the rules for corporate accounts

**Comment by CloCkWeRX** [comment]
Oh, I was just about to raise a similar one and hunted down https://en.wiki.openfoodfacts.org/Data_imports

A really good example of this working is https://opencouncildata.org - a clean, clear set of schemas for CSV, JSON, etc for some common datasets at the local government level.
This has a few passionate stakeholders behind it and resulted in a large number of Australian councils publishing fairly clean, well structured data on hubs like data.gov.au with versioned schema; etc.

Starting with the schema first; then some generic input tools would probably be a good step; and later on things could be a little fancier with OpenRefine.

**Comment by CloCkWeRX** [comment]
Suggestions:
 * Extend http://schema.org/Product with the openfoodfacts attributes as optional (https://en.wiki.openfoodfacts.org/Data_imports) 
 * Reconcile with https://github.com/FoodOntology/foodon topics where sensible

**Comment by CloCkWeRX** [comment]
I started chipping away at a static open-your-data and here-is-schema site on https://clockwerx.github.io/openfoodfacts-standards/

**Comment by teolemon** [comment]
@stephanegigandet is working on this
