### ISSUE TITLE
Create a "Developer" page for developers

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1079]
- Link to the various Github Projects
- Link to the API
- Explanation about how to communicate via Slack
- Contribution charter

**Comment by Jigar3** [comment]
I want to take this issue.
Can you give me further details.
Any help is appreciated

**Comment by ashishkumar1550** [comment]
If anyone has not taken this issue, can you please elaborate a bit so I can work on it?

**Comment by teolemon** [comment]
fixed https://world.openfoodfacts.org/development

**Comment by teolemon** [comment]
Needs to be linked from the website.

**Comment by VaiTon** [comment]
Closing in favour of #4406
