### ISSUE TITLE
[FOUNDATION] Disable "Move" mode in image cropper

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#108]
I'd like to disable the double click in the cropper  (so that it stays in crop mode, and does not go in move mode). Is there a way to do that without changing the cropper code? e.g. by overriding this function somehow?

https://github.com/fengyuanchen/cropper/blob/master/src/js/handlers.js#L29

see also https://github.com/fengyuanchen/cropper/blob/master/src/js/listen.js#L5

**Comment by stephanegigandet** [comment]
Filed https://github.com/fengyuanchen/cropper/issues/299
and https://github.com/fengyuanchen/cropper/issues/300

**Comment by hangy** [comment]
Fixed with e086cad649b57bc39475e57a947ef84a33365686
