### ISSUE TITLE
Disable the "Open Food Facts Days 2024" banner

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#10823]
### Problem
- Disable the "Open Food Facts Days 2024" banner

**Comment by teolemon** [comment]
@hangy it's over ? I was thinking it would give more visibility to the donation campaign. We can keep it a little more :-)

**Comment by hangy** [comment]
> @hangy it's over ? I was thinking it would give more visibility to the donation campaign. We can keep it a little more :-) 

Yeah unfortunately it's over 😆

**Comment by tradmangh** [comment]
> [@hangy](https://github.com/hangy) it's over ? I was thinking it would give more visibility to the donation campaign. We can keep it a little more :-)

How about making it persistently removable for authenticated contributors?
