### ISSUE TITLE
No thumbnails on web-page

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#1083]
I see no thumbnails on the search result page ("strawberry preserve champagne"). Clicking to a product does show them.

![screen shot 2018-02-16 at 17 24 03](https://user-images.githubusercontent.com/1329905/36317972-c92bc208-133e-11e8-9924-2189c9eb0f32.png)

**Comment by hangy** [comment]
Apparently, this has been fixed: [![image](https://user-images.githubusercontent.com/87124/52902131-da998000-320c-11e9-94cd-cbf3beb1b6a6.png)](https://world.openfoodfacts.org/cgi/search.pl?action=process&search_terms=strawberry%20preserve%20champagne&sort_by=unique_scans_n&page_size=20&action=display)
