### ISSUE TITLE
Image urls wrong

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#1084]
In the search result jsons the image urls are wrong
They are encoded as:
`https://static.openfoodfacts.org/images/products/637/793/000/902/front_en.6.200.jpg`

But should be:
`https://static.openfoodfacts.org/images/products/063/779/300/0902/front_en.6.200.jpg`

**Comment by stephanegigandet** [comment]
It's because of bug #1077

**Comment by aleene** [comment]
Something changed then, it was ok.

**Comment by stephanegigandet** [comment]
Fixed by fixing #1077 : https://world.openfoodfacts.org/api/v0/product/0637793000902/seville-orange-marmalade-mackays has /063/ urls for images
