### ISSUE TITLE
Expose recalled products through the API

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1087]
### What

- [ ] Expose recalled products through the API 
- [ ] Design doc

**Comment by teolemon** [comment]
Blocks https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/349

**Comment by Dwarfex** [comment]
There is an EU provide Website, which lists urgent product recalls: 
webgate.ec.europa.eu/rasff-window/consumers/?event=home

**Comment by teolemon** [comment]
- dupe of #1035
