### ISSUE TITLE
[FOUNDATION] Nutrition facts table is too wide

### ISSUE THREAD

**Issue by TaciteOFF** [openfoodfacts/openfoodfacts-server#109]
On mobile, the nutrition facts table is too wide.
Can't scroll to the right either.

Tested on iPhone 6 and Galaxy S5.

![slack_for_ios_upload](https://cloud.githubusercontent.com/assets/11161632/7563521/44bcb78a-f7de-11e4-965a-2cca853c7a0a.png)

**Comment by teolemon** [comment]
Closing. Please see #226, which is a "very high impact" bug
