### ISSUE TITLE
Create an admin button to wipe all nutrition facts

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1090]
Create an admin button to wipe all nutrition facts. For the 0 eveywhere issue.

**Comment by stephanegigandet** [comment]
Wouldn't it be simpler to automatically delete nutrition facts that have 0 everywhere? (unless there are actual products with nutrition facts tables with all 0s ?)

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/46919070-d39dff00-cfd9-11e8-9f6c-7d67e1023a60.png)
