### ISSUE TITLE
When deleting all nutrients, some computed values are kept in DB

### ISSUE THREAD

**Issue by raphael0202** [openfoodfacts/openfoodfacts-server#10933]
When we remove all nutrients from a product using the web version, we still have the following (computed values) in the `nutriments` field:

```json
{
    "nutriments": {
        "carbon-footprint-from-known-ingredients_100g": 50.336,
        "carbon-footprint-from-known-ingredients_product": 252,
        "carbon-footprint-from-known-ingredients_serving": 27.2,
        "fruits-vegetables-legumes-estimate-from-ingredients_100g": 0,
        "fruits-vegetables-legumes-estimate-from-ingredients_serving": 0,
        "fruits-vegetables-nuts-estimate-from-ingredients_100g": 0,
        "fruits-vegetables-nuts-estimate-from-ingredients_serving": 0,
        "nova-group": 1,
        "nova-group_100g": 1,
        "nova-group_serving": 1,
        "nutrition-score-fr": -7,
        "nutrition-score-fr_100g": -7
    }
}
```

In Robotoff, I added a special case to consider the product nutrients as missing if there are only these keys: https://github.com/openfoodfacts/robotoff/commit/0e4aff3bb83807194ab163334ced75d4d72fe5dd.

**Comment by raphael0202** [comment]
> @raphael0202 We chose to have some computed values in the nutriments field, so this behaviour is normal. It is useful in particular for easing the creation of graphs and search filters. We could decide to do it differently in the future.

But as all nutrient values were deleted, I was expected the computed values to be deleted as well. But it's definitely not a major issue.

**Comment by stephanegigandet** [comment]
nutrition-score-fr and nutrition-score-fr_100g should definitely be removed, but the other ones are computed from ingredients, so they should stay

**Comment by stephanegigandet** [comment]
ah in fact it's probably a product where nutriments are estimated, that's why we get nutriscore-score-fr

so everything looks normal in this case
