### ISSUE TITLE
404 on MadeNearMe Picture

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1095]
http://madenear.me/images/misc/madenearme-map.620x465.png

Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by teolemon** [comment]
We have : https://github.com/openfoodfacts/openfoodfacts-server/blob/master/html/images/misc/madenearme-uk-map.620x465.png

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/36345160-1ff0e2c0-1426-11e8-9280-033a221e4c04.png)

**Comment by tonyb7** [comment]
You forgot "uk" in the URL. The correct URL is http://madenear.me/images/misc/madenearme-uk-map.620x465.png

**Comment by hangy** [comment]
> You forgot "uk" in the URL. The correct URL is http://madenear.me/images/misc/madenearme-uk-map.620x465.png

That's for http://madenear.me.uk/. This is a bit of a mess to fix, though, because the source of https://madenear.me/ does not seem to be on Git: https://github.com/openfoodfacts/openfoodfacts-server/tree/master/madenearme

**Comment by stephanegigandet** [comment]
> That's for http://madenear.me.uk/. This is a bit of a mess to fix, though, because the source of https://madenear.me/ does not seem to be on Git: https://github.com/openfoodfacts/openfoodfacts-server/tree/master/madenearme

The source for madenear.me is https://github.com/openfoodfacts/openfoodfacts-server/blob/master/cgi/madenearme.pl

There's a cron job that makes a static copy:

#*/45 * * * * wget -q -O /srv/off/html/cestemballepresdechezvous.html http://fr.openfoodfacts.org:8001/cgi/madenearyou.pl
#*/50 * * * * wget -q -O /srv/off/html/madenearme-uk.html http://uk.openfoodfacts.org:8001/cgi/madenearme.pl
#*/55 * * * * wget -q -O /srv/off/html/madenearme.html http://world.openfoodfacts.org:8001/cgi/madenearme.pl

**Comment by hangy** [comment]
Oh, ok, I get where I was wrong. [madenearme-world.html](https://github.com/openfoodfacts/openfoodfacts-server/blob/b5d4d3e88e15bfe83a8f8b54abd52d7834a5ebeb/madenearme/madenearme-world.html) actually has the title `Made Near Me - Europe`. 🙂
