### ISSUE TITLE
Quality tag if "ingrédients issus de l'Agriculture Biologique" is in ingredients, but no organic label

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1096]
Quality tag if "ingrédients issus de l'Agriculture Biologique" is in ingredients, but no organic label

**Comment by hangy** [comment]
German examples

- [aus biologischer Landwirtschaft](https://world.openfoodfacts.org/product/4010355130082)
- [aus kontrolliert ökologischer Landwirtschaft](https://world.openfoodfacts.org/product/4311501370933)
- [Zutaten aus ökol. Landwirtschaft](https://world.openfoodfacts.org/product/4005967585689)
