### ISSUE TITLE
Big: Serving size is missing digits to strict

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#10961]
### What
When I want to specify that a product does not mention a portion/serving size, I would like to enter a dash (`-`). Thius now results in an error.

### Steps to reproduce the behaviour
Just enter a dash ("-") in the field and save

### Expected behavior
No error

### Why
Entering missing data is also data

### Type of device
- Browser: Safari

### Number of products impacted
Many

**Comment by jusdekiwi** [comment]
That would be a cool feature! Same as for the fibers in the NT.

**Comment by CharlesNepote** [comment]
In the `serving size` isn't it? Seems to be quite rare for me. Can you give few examples to be sure?

In the meantime, you can use Folksonomy Engine to do so, but I guess it would be better to allow dash in the `Serving size` field.

**Comment by jusdekiwi** [comment]
> In the `serving size` isn't it? Seems to be quite rare for me. Can you give few examples to be sure?
> 
> In the meantime, you can use Folksonomy Engine to do so, but I guess it would be better to allow dash in the `Serving size` field.

You mean you don't often see products without a serving size? seems to happen >50% of the time for me

**Comment by aleene** [comment]
Example: https://world.openfoodfacts.org/product/20615079/hazelnut-cinnamon-biscuits-favorina
