### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#11043]
### What
Issue with build that can not finish!
![Image](https://github.com/user-attachments/assets/3318c60a-6ad6-42c2-a801-24d5719eada3)

**Comment by hangy** [comment]
Yep [I noticed this](https://github.com/openfoodfacts/openfoodfacts-server/issues/11013) on another branch last week, as well. I think the random product/image sample is now too large (>1 GiB) for a simple CI check.

**Comment by stephanegigandet** [comment]
Fixed by https://github.com/openfoodfacts/openfoodfacts-server/pull/11070
