### ISSUE TITLE
Do not take into account values less than

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#11075]
### What
Error is: `Nutrition-soluble-fiber-plus-insoluble-fiber-greater-than-fiber`

### Steps to reproduce the behaviour
see: https://world.openfoodfacts.org/product/0856651002104/chili-lime-chickpeas-the-good-bean

### Expected behaviour
no error. the algorithm should ignore values with a < sign

**Comment by CharlesNepote** [comment]
Should it ignore values or should it take into account value with "<" minus 1?

**Comment by aleene** [comment]
I think we should ignore the values

**Comment by jusdekiwi** [comment]
I agree with Aleene!
