### ISSUE TITLE
Change default language from Hindi to English on in.openfoodfacts.org (Open Food Facts India)

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#1109]
Hindi is currently the default language on in.openfoodfacts.org, and other languages are available from the dropdown. It seems that the most available language on food products sold in India is English. So it probably makes sense to change the default language to English on in.openfoodfacts.org , and have Hindi and other languages used in India as options.

Feedback from the #in channel on the OFF Slack:

"I guess people hardly use mobile apps in Hindi. They prefer English."

"Most people who will use an Android/iOS device prefer English language in apps."

"In my opinion we can have english as the main language and have an option to switch to hindi

Even "https://www.google.co.in/" has the main language as english and we have options below the search button to change the languages
And if I personally tell I will have more difficulty in typing on a Hindi keyboard than English keyboard while using the app"

"Hi., I agree English should be the main language and there should be a option to switch to Hindi or other languages"

"When it comes to food products in India, English is the most widely used language on any packaging.
There is easily around 125 million Indian's who do speak English. 
Hindi on the other hand is the most widely spoken language in India & hence it would be great to have support for Hindi and other regional languages."

**Comment by shivanshsoni** [comment]
Ya.. I am Indian and I agree that people in India use apps in English. So I also think that we can keep hindi as an optional language and we should keep english as a default language. I would say that a person who will use app, he knows english. I am an indian and I know mentality of indian people. No ordinary person not having knowledge of english will use this app. So,default language must be english. I think 😅

**Comment by muskangarg21** [comment]
@stephanegigandet May i work on this as my first issue ?
I think by changing the $country_languages of India to have english at first index and then hindi would work.
Which files should I look in for this issue ?
Thanks

**Comment by stephanegigandet** [comment]
Hi @muskangarg21 ! Sure, thank you!
We have a taxonomy which lists all countries and the associated languages:
https://github.com/openfoodfacts/openfoodfacts-server/blob/master/taxonomies/countries.txt

for the "en:India" entry, we have:

country_code_2:en:IN
country_code_3:en:IND
languages:en:hi,en

Just putting en first should work. We may want to add more optional languages if it's common for food products in India to have ingrédients lists etc. written in other languages used in India.

**Comment by stephanegigandet** [comment]
The corresponding Perl code is there: https://github.com/openfoodfacts/openfoodfacts-server/blob/master/lib/ProductOpener/Display.pm#L302

But it doesn't need to be changed, just updating the taxonomy should work.

To test, you can update the countries.txt file, and then build the taxonomy:

cd scripts
export PERL5LIB=.
./build_tags_taxonomy countries publish

Then stopping and starting Apache/mod_perl should load the new taxonomy.

**Comment by muskangarg21** [comment]
on running `./build_tags_taxonomy.pl countires publish` I am getting
<pre>
Status: 500
Content-type: text/html

<h1>Software error:</h1>
<pre>ProductOpener/Config.pm did not return a true value at ./build_tags_taxonomy.pl line 28.
BEGIN failed--compilation aborted at ./build_tags_taxonomy.pl line 28.
</pre>
<p>
For help, please send mail to this site's webmaster, giving this error message 
and the time and date of the error.

</p>
[Wed Mar 11 23:30:38 2020] build_tags_taxonomy.pl: ProductOpener/Config.pm did not return a true value at ./build_tags_taxonomy.pl line 28.
[Wed Mar 11 23:30:38 2020] build_tags_taxonomy.pl: BEGIN failed--compilation aborted at ./build_tags_taxonomy.pl line 28.
</pre>
which lead to the lines `use ProductOpener::Config qw/:all/;` in the code.
