### ISSUE TITLE
Changing Barcodes is Broken

### ISSUE THREAD

**Issue by October-Food-Facts** [openfoodfacts/openfoodfacts-server#11090]
Pictures are uploaded to wrong barcodes every day, so this is a significant halt to work on the site.

![Image](https://github.com/user-attachments/assets/f8ada952-7e76-4eaf-9d27-197e6570c2a1)

See also: https://github.com/openfoodfacts/openfoodfacts-server/issues/11067

**Comment by stephanegigandet** [comment]
This is because this specific product already existed, and was marked as deleted earlier: https://world.openfoodfacts.org/product/8430094327561?rev=3

We currently do not support moving products if we have existing data (even if that data was deleted). You can move the images instead.
