### ISSUE TITLE
Product Count is broken from November 5th on 3 flavors (OFF works fine)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#11114]
### What
- Product Count is broken from November 5th on all flavors but Open Food Facts
- https://world.openfoodfacts.org/product-count
- https://world.openpetfoodfacts.org/product-count
- https://world.openbeautyfacts.org/product-count

![Image](https://github.com/user-attachments/assets/03e4f2f6-2913-4aee-b48a-f2b1c1c798f8)

**Comment by alexgarel** [comment]
This was the same cause as #11118 and it's now up to date.
