### ISSUE TITLE
There is a line present due to merge conflicts can be resolved easily

### ISSUE THREAD

**Issue by ms10398** [openfoodfacts/openfoodfacts-server#1114]
https://github.com/openfoodfacts/openfoodfacts-server/blob/e5dbf9d4df2fe939da183a24325998a199870527/po/openfoodfacts/en.po#L10

@hangy Its a small fix maybe you can commit it directly instead of I make a PR for it

I am going through all the code so that I can refactor and work on the server.

Thats why while going through all the code I found it.

**Comment by hangy** [comment]
Changed this in the translations/Crowdin l10n_master branch. Thanks for the hint! The issue will be closed with the next translations update.

**Comment by ms10398** [comment]
Thats great! :tada:
