### ISSUE TITLE
Can't add any product from barcode

### ISSUE THREAD

**Issue by TaciteOFF** [openfoodfacts/openfoodfacts-server#112]
Whenever I write down a barcode in the input field then press "Add", nothing happens.
I think I'm redirected to the same page with an extra "#" at the end of the URL.
Also, in the previous version, it was easier to find a problem with a barcode because the input field was exactly 13 characters long, it's no longer the case :(

**Comment by stephanegigandet** [comment]
Fixed, thank you!

Regarding the barcode width,it's now changing as the site is responsive... I guess we could try to do something in Javascript to put the 14th character in another color or something.
