### ISSUE TITLE
Cache categories.json and labels.json for consumption in the mobile app

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1122]
Cache categories.json and labels.json for consumption in the mobile app

We don't need product count, we just need the names in all possible languages, the ids, and possibly the linked_data.
It should be cached, we'll provide in app mechanisms to refresh it.

**Comment by hangy** [comment]
> It should be cached, we'll provide in app mechanisms to refresh it.

What do you mean by that? If the list was ie. generated nightly as a static file by a cronjob, an app could not be able to invalidate the cache.

**Comment by teolemon** [comment]
@stephanegigandet  has produced static versions of the taxonomies. So this bug is obsolete.

**Comment by vogloblinsky** [comment]
@teolemon What is the API url for getting this list of taxonomies, for examples list of categories in french ?
Thanks
