### ISSUE TITLE
Export taxonomies definitions including translations in JSON format

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#1126]
Taxonomies are currently defined on the wiki in text format : https://en.wiki.openfoodfacts.org/Global_taxonomies

The text format is then processed to create a Perl representation of the taxonomy in Perl data structures that contains synonyms, translations, children and parents. Those data structures are used by Product Opener for data processing and data display, but are not directly available to apps.

This feature is to introduce JSON exports for each taxonomy so that apps can easily translate tags, and navigate the taxonomy (direct parents and children).

JSON exports will be updated whenever taxonomies are updated. Apps can include a version of those exports, and periodically check for newer versions.

**Comment by teolemon** [comment]
@stephanegigandet Fixed
