### ISSUE TITLE
Hong kong style nutrition list

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#1132]
I noticed that the nutrition lists used in Hong kong are a bit different. They are similar to the EU version, but:
- energy is in kcal
- protein is on the second place
- transfat is added below saturated fat
- no fiber
- sodium

Maybe this can be supported in some way. It seems that imported products (a lot) are required to add a label in the above format.

**Comment by teolemon** [comment]
It can be customized, just like for us products

**Comment by hangy** [comment]
- [ ] Add new nutritent list to https://github.com/openfoodfacts/openfoodfacts-server/blob/d602fffddabae21e0dbd5d2272e9dc1db59f349d/lib/ProductOpener/Food.pm#L214-L772
- [ ] Add this table with the `hk` country code to https://github.com/openfoodfacts/openfoodfacts-server/blob/d602fffddabae21e0dbd5d2272e9dc1db59f349d/lib/ProductOpener/Food.pm#L205-L210

**Comment by aleene** [comment]
I have the impression that this setup also holds for China. Products that are produced in China have this as standard and also include chinese daily values.

**Comment by aleene** [comment]
https://gain.fas.usda.gov/Recent%20GAIN%20Publications/General%20Rules%20for%20Nutrition%20Labeling%20of%20Prepackaged%20Foods%20_Beijing_China%20-%20Peoples%20Republic%20of_1-9-2013.pdf

**Comment by aleene** [comment]
I wonder if there shouldn’t be field to indicate the nutrition facts table style. This can usually default to the location of the user. But for a place like hong kong where food comes from the whole world you need to specify it.

**Comment by CloCkWeRX** [comment]
Oh, Australian labels are similar (protein is featured fairly high up); its been bugging me for a while.

HK: https://www.cfs.gov.hk/english/food_leg/files/nl_technical_guidance_e.pdf
AU: https://www.foodstandards.gov.au/consumer/labelling/panels/Pages/default.aspx / http://media.healthdirect.org.au/publications/Nutrition-Information-Panel.pdf

Its a tiny usability annoyance in the web UI when punching in data. Potentially useful for training nutrition table extraction models though?

**Comment by muskangarg21** [comment]
@teolemon may I work on this ?

**Comment by stephanegigandet** [comment]
@muskangarg21 : sure, please do :) As @hangy commented, the related code is in Food.pm

**Comment by muskangarg21** [comment]
@hangy @stephanegigandet what all should the list of Nutrients contain for Hong Kong ?
The pdf ` https://www.cfs.gov.hk/english/food_leg/files/nl_technical_guidance_e.pdf` as mentioned by @CloCkWeRX has a list.

**Comment by stephanegigandet** [comment]
I don't know, the best thing would be to look at pictures of nutrition facts labels that we already have on https://hk-en.openfoodfacts.org/ (looking for local products instead of imported products) to check what the most common format is.

**Comment by muskangarg21** [comment]
I am seeing a pattern in the products, I ll open a PR tomorrow for this issue.

**Comment by VaiTon** [comment]
Closed with #3042
