### ISSUE TITLE
Additives detection of E Numbers without E or with another prefix: INS, SIN etc. (Hong kong, India, Arabic)

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#1133]
They seem to the european e-numbers in the ingredients  lists, but they leave out the “E”. These are now not detected by OFF.

**Comment by stephanegigandet** [comment]
example product:
https://hk.openfoodfacts.org/product/4891028164456/vlt-vita
"water, sugar, tea, lemon juice, flavouring, acidity regulator (330, 331), vitamin C, antioxidant (304)"

**Comment by stephanegigandet** [comment]
related to that, India seems to prefix the e-numbers with INS : https://in.openfoodfacts.org/product/8908009670014/omg-oh-my-ganna-nutricane

"REAL SUGARCANE, SALT, ANTIOXIDANT (INS 300), ACIDITY REGULATOR (INS 334), STABILIZER (INS 440, INS 337), WATER (FOR MAINTAINING DESIRED BRIX), CONTAINS PERMITTED NATURAL FLAVOUR & NATURAL IDENTICAL COLOURING SUBSTANCES (INS 141[i])"

**Comment by stephanegigandet** [comment]
https://fr.openfoodfacts.org/produit/3379670008324/chicken-luncheon-meat-covi

Stabilisants: (SIN450i, SIN450iii), antioxydant (SIN316), Agent de conservation: (SIN250).

SIN = Système International de Numération.

There might be other prefixes in use in other countries.

**Comment by stephanegigandet** [comment]
Additives detection for those cases now work. Added tests for them.
