### ISSUE TITLE
Recent changes is missing pagination links

### ISSUE THREAD

**Issue by hangy** [openfoodfacts/openfoodfacts-server#1139]
Pagination is supported by https://world.openfoodfacts.org/cgi/recent_changes.pl, but currently, there are no links on the rendered HTML.

**Comment by justaname123** [comment]
I would like to try this

**Comment by hangy** [comment]
> I would like to try this

Please, go ahead! 👍 I can't assign you to the issue, but I'll gladly take a pull request. 🙂

**Comment by VaiTon** [comment]
I started working on this :)
