### ISSUE TITLE
Add checkbox for products with multiple nutrition facts values / tables (dehydrated etc.)

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#1145]
Some products have multiple nutrition facts values or tables, in particular for products that are dehydrated and need to be prepared with added water and/or milk, or products that are typically eaten with something else (e.g. milk in breakfast cereals). It is also the case for products that contain multiple different sub products. (e.g. something + some sauce to go with it)

OFF does not support multiple nutrition facts values and tables, and it would be difficult to add.

This checkbox is to identify such products, and to make them ineligible for product comparisons, graphs, computing nutrition grades like Nutriscore etc.

When checked in the product edit form, a message will appear to state that nutritional values entered for the product need to be the raw product values (without added water, milk etc.)

**Comment by teolemon** [comment]
Perfect

**Comment by stephanegigandet** [comment]
As @teolemon suggested, I will also introduce a quality:multiple-nutrition-data tag (when the checkbox is checked).

And also a new quality:not-comparable-nutrition-data (or maybe a shorter version) + a not_comparable_nutrition_data property for the product. This tag means that the product will be excluded from nutrition grade computation, nutrition statistics, and nutrition graphs.

The difference is for some products that have multiple nutrition facts tables, but that we still want to compare to other products. One example is products from the breakfast cereals category, but there may be others.

**Comment by stephanegigandet** [comment]
Live in production.

**Comment by SantosSi** [comment]
Sorry, cannot find the checkbox to enter a product mix box (e.g. 4007552305429).

**Comment by stephanegigandet** [comment]
OFF now has support for a prepared product nutrition table in addition to the product as sold nutrition table.
