### ISSUE TITLE
invalid CSRF token on account creation from an iphone

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#1147]
reported by an user: "Bonjour, j’essaye de créer un compte open food facts à partir de mon iphone. Mais j’ai toujours un message d’erreur : invalid CSRF token."

**Comment by hangy** [comment]
On the website? Does anyone have an iDevice to check that? The CSRF token should be sent as part of the HTML form, so that should work on any browser. Could the 'b' cookie be blocked?

**Comment by hangy** [comment]
Upon registration, the CSRF system uses the `b` cookie to verify the POSTed CSRF token. Can you test whether the correct cookie is sent to the server?

**Comment by teolemon** [comment]
https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/1862

**Comment by teolemon** [comment]
This is impacting the official android client

**Comment by hangy** [comment]
Accidentally closed by mis-click. But honestly: The most probbale cause is that the `b` cookie is not sent when POSTing the form, which correctly causes a CFRF validation error. Can anyone check that?
