### ISSUE TITLE
[FOUNDATION] Adding nutrition elements can make the Validate button disappear

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#115]
In the product edit form, if a lot of nutrition elements are added, then the Validate button below can disappear.

This is probably due to the Foundation "Equalizer" that makes the sidebar and the main column the same height.

![screenshot-modifier un produit - mozilla firefox](https://cloud.githubusercontent.com/assets/8158668/7582908/ede62d6a-f891-11e4-80c2-99071267fcba.png)

**Comment by aleksejrs** [comment]
It affects the Save button, too.

**Comment by stephanegigandet** [comment]
I cannot reproduce this bug, the column now extends when new nutrition elements are added.
