### ISSUE TITLE
Support for additional nutrition data for prepared product

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#1151]
Most products have nutrition facts for product as it is sold, but some also have nutrition facts for the prepared product (e.g. powder milk, dehydrated soup etc.)

**Comment by hangy** [comment]
Similar to #947 and #1073

**Comment by stephanegigandet** [comment]
I'm in process of adding in on .net, it's slightly working for now. Some CSS issues, a few bugs etc.

**Comment by stephanegigandet** [comment]
So in practice we have different cases in the products in our database:

Products that need to be prepared before being eaten and that have nutrition data values:
- only for the unprepared product
- only for the prepared product
- both (most common)

There are also products that can be eaten with added milk (e.g. breakfast cereals), in which case there can be additional values (sometimes more than one, e.g. with skim milk or whole milk).
-> we don't care about those, we should explicitly states that we only want data for prepared product if they cannot be eaten unprepared

Proposed solution:
- 2 check boxes, to indicate if the product has nutrition data for the product as sold (checked by default) and for the prepared product (unchecked by default)
- dynamically add columns in the nutrition facts entry form, based on the checkboxes

For Nutriscore: follow the guidelines (use prepared values for food that cannot be eaten unprepared, use unprepared values for breakfast cereals, dough and dry pasta (try to eat them raw, they are crunchy ;) )

**Comment by stephanegigandet** [comment]
Deployed in 2018.
