### ISSUE TITLE
[FOUNDATION] Can't scroll down when editing product page

### ISSUE THREAD

**Issue by TaciteOFF** [openfoodfacts/openfoodfacts-server#116]
This issue might be related to the fact that a product page has many pictures and is displayed on a small screen.
I can't scroll down to complete it.
Product page : http://fr.openfoodfacts.org/produit/3538280837254/la-vosgienne-parfums-framboise-citron-orange-cadbury

![capture d ecran 2015-05-12 a 14 30 03](https://cloud.githubusercontent.com/assets/11161632/7587061/9511ac56-f8b3-11e4-93c9-a6a2ab5764f4.png)

**Comment by TaciteOFF** [comment]
UPDATE: I'm using Safari, and this issue doesn't always appear. I have been able to scroll down after reloading 5 times the page.

**Comment by stephanegigandet** [comment]
Probably related to bug #115

**Comment by stephanegigandet** [comment]
Do you still have the issue? I added some calls to reequalize the page when it is changed dynamically by the product edit form.

**Comment by TaciteOFF** [comment]
Seems to be fixed, thanks :)
