### ISSUE TITLE
Some products don't appear in their category page

### ISSUE THREAD

**Issue by TaciteOFF** [openfoodfacts/openfoodfacts-server#1160]
**Summary:** 

Some products don't appear in their category page.

**Steps to reproduce:** 

Go to https://fr.openfoodfacts.org/produit/3168930003830/chips-a-l-ancienne-nature-lay-s
Clic on the "Chips-a-l-ancienne" link
Try to find the product in the category.

**Expected behavior:** 

More than 50 products should appear in the category

**Comment by stephanegigandet** [comment]
It's because we updated the taxonomies, but we didn't recompute yet the categories for all existing products.

**Comment by CharlesNepote** [comment]
Seems to be fixed, isn't it? https://fr.openfoodfacts.org/categorie/chips-a-l-ancienne
