### ISSUE TITLE
Products pages links in graphs don't work anymore

### ISSUE THREAD

**Issue by TaciteOFF** [openfoodfacts/openfoodfacts-server#117]
After generating a graph like this one :

http://fr.openfoodfacts.org/cgi/search.pl?action=process&tagtype_0=categories&tag_contains_0=contains&tag_0=Chocolats%20au%20lait&sort_by=unique_scans_n&page_size=20&axis_x=energy&axis_y=additives_n&graph=1

When clicking on a product, we're redirected to links like…

http://fr/produit/3046920003759

**Comment by stephanegigandet** [comment]
Fixed, thank you!
