### ISSUE TITLE
Broken logo on ir.openfoodfacts.org

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1171]
Broken logo on ir.openfoodfacts.org

**Comment by hangy** [comment]
https://github.com/openfoodfacts/openfoodfacts-server/tree/master/html/images/misc/openfoodfacts-logo-fa-178x150.png 404

**Comment by shahaman351** [comment]
Iran logo link is not working.
https://static.openfoodfacts.org/images/misc/openfoodfacts-logo-fa-178x150.png
it gives this error
404 Not Found
nginx/1.6.2

**Comment by hangy** [comment]
@teolemon You added a SVG in edec6741972b94562cad54a14ab538d7c3df6903, but that SVG does not contain text in Farsi. openfoodfacts-logo-fa-178x150.png, openfoodfacts-logo-fa-356.png, openfoodfacts-logo-fa-356x300.png, openfoodfacts-logo-fa-712.png, and openfoodfacts-logo-fa-712x600.png are missing from Git.

**Comment by teolemon** [comment]
fixed in prod:
https://ir.openfoodfacts.org/
 cp /srv/off/html/images/misc/openfoodfacts-logo-fa.png /srv/off/html/images/misc/openfoodfacts-logo-fa-178x150.png

**Comment by teolemon** [comment]
cc @shahaman351
