### ISSUE TITLE
Create a new API that checks a barcode on all 4 databases

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1174]
Create a new API that checks a barcode on all 4 databases (off, obf, opf, opff) and returns the name of the matching db, for moderation purposes.

### Part of
- #5536
- #5505 
- #5555

**Comment by stephanegigandet** [comment]
One possibility could be to merge the 4 databases into one, and have a tag on each product to indicate which database(s ?) it is in.

Issues with that:
- if we want to move the sites and database to different servers, it's not possible anymore
- there will be more barcode conflicts, especially in the self allocated 2* codes

**Comment by hangy** [comment]
An advantage would be that moving products would be much easier?

**Comment by teolemon** [comment]
Related: https://github.com/openfoodfacts/openfoodfacts-server/issues/797

**Comment by teolemon** [comment]
- Dart side issue: https://github.com/openfoodfacts/openfoodfacts-dart/issues/972
