### ISSUE TITLE
The mobile app doesn't work anymore for some users.

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1177]
It will say 
![image](https://user-images.githubusercontent.com/1689815/38193888-b46f6064-3674-11e8-8554-10e6e63326a1.png)
but:
https://uk.openfoodfacts.org/cgi/product.pl?type=edit&code=5035766061557

**Comment by stephanegigandet** [comment]
I looked into it, this happens when:
- the app does not specify the language
- and the product is a new product
- and the country code from geoip is different from the country code we use on off  (that would be only gb / uk for United Kingdom)

**Comment by stephanegigandet** [comment]
Fixed.
