### ISSUE TITLE
2 Additives names show up in English but not in French

### ISSUE THREAD

**Issue by TaciteOFF** [openfoodfacts/openfoodfacts-server#118]
Please take a look at this product : 

http://world.openfoodfacts.org/product/8000500188330

It's its World (English) product page.

Now take a look at the French version :  

http://fr.openfoodfacts.org/produit/8000500188330

E572 and E141ii names (Stéarate de Magnésium & Complexes cuivriques de chlorophyllines) aren't mentioned in the French version.

They are already present in the Global Additives Taxonomy wiki page.

**Comment by stephanegigandet** [comment]
This seems to happen when the same synonym is used for more than one additive, I'll write a script to find all of them, it affects more than those 2.

**Comment by stephanegigandet** [comment]
So we have issues with all those additives, in various languages. 

bg - e172ii - 1
bg - e172iii - 1
bg - e262i - 1
bg - e322ii - 1
bg - e440aii - 1
bg - e440aiii - 1
bg - e440aiv - 1
bg - e440i - 1
bg - e450viii - 1
bg - e452v - 1
bg - e452vi - 1
bg - e500i - 1
bg - e501i - 1
bg - e503i - 1
bg - e541ii - 1
bg - e580 - 1
cs - e101i - 1
cs - e172iii - 1
cs - e262i - 1
cs - e322ii - 1
cs - e420i - 1
cs - e440aii - 1
cs - e440aiii - 1
cs - e440aiv - 1
cs - e440i - 1
cs - e450i - 1
cs - e450iv - 1
cs - e450viii - 1
cs - e452vi - 1
cs - e501i - 1
cs - e503i - 1
cs - e504i - 1
cs - e514i - 1
cs - e515i - 1
cs - e541ii - 1
da - e172ii - 1
da - e172iii - 1
da - e322ii - 1
da - e420i - 1
da - e440aii - 1
da - e440aiii - 1
da - e440aiv - 1
da - e450iv - 1
da - e450viii - 1
da - e452v - 1
da - e452vi - 1
da - e500i - 1
da - e504i - 1
da - e514i - 1
da - e541ii - 1
de - e101i - 1
de - e160ai - 1
de - e172iii - 1
de - e262i - 1
de - e304i - 1
de - e322ii - 1
de - e332ii - 1
de - e333iii - 1
de - e352i - 1
de - e357 - 1
de - e401 - 0
de - e402 - 0
de - e403 - 0
de - e404 - 0
de - e440aii - 1
de - e440aiii - 1
de - e440aiv - 1
de - e440i - 1
de - e450viii - 1
de - e452v - 1
de - e452vi - 1
de - e492 - 1
de - e493 - 1
de - e494 - 1
de - e495 - 1
de - e500i - 1
de - e501i - 1
de - e503i - 1
de - e504i - 1
de - e514i - 1
de - e515i - 1
de - e541ii - 1
de - e553ai - 1
de - e627 - 1
de - e628 - 1
de - e629 - 0
de - e965ii - 1
el - e172ii - 1
el - e172iii - 1
el - e322ii - 1
el - e440aii - 1
el - e440aiii - 1
el - e440aiv - 1
el - e450iv - 1
el - e450viii - 1
el - e452v - 1
el - e452vi - 1
el - e541ii - 1
en - e101i - 1
en - e14xx - 1
en - e160ai - 1
en - e172iii - 1
en - e182 - 1
en - e262i - 1
en - e304i - 1
en - e305 - 1
en - e307b - 1
en - e307c - 1
en - e322i - 1
en - e336ii - 1
en - e350i - 1
en - e352i - 1
en - e440a - 1
en - e440i - 1
en - e458 - 1
en - e470b - 1
en - e500i - 1
en - e501i - 1
en - e503i - 1
en - e504i - 1
en - e540 - 1
en - e541ii - 1
en - e544 - 1
en - e545 - 1
en - e924a - 1
es - e101i - 1
es - e160ai - 1
es - e172iii - 1
es - e262i - 1
es - e304i - 1
es - e322ii - 1
es - e350i - 1
es - e352i - 1
es - e420i - 1
es - e440a - 1
es - e440aiii - 1
es - e440aiv - 1
es - e440i - 1
es - e452vi - 1
es - e500i - 1
es - e501i - 1
es - e504i - 1
es - e514i - 1
es - e515i - 1
es - e541i - 1
es - e965i - 1
et - e101i - 1
et - e172iii - 1
et - e262i - 1
et - e322ii - 1
et - e440aii - 1
et - e440aiii - 1
et - e440aiv - 1
et - e440i - 1
et - e450iv - 1
et - e450viii - 1
et - e452v - 1
et - e452vi - 1
et - e500i - 1
et - e504i - 1
et - e514i - 1
et - e541ii - 1
fi - e101i - 1
fi - e172iii - 1
fi - e262i - 1
fi - e322ii - 1
fi - e440aii - 1
fi - e440aiii - 1
fi - e440aiv - 1
fi - e440i - 1
fi - e450viii - 1
fi - e452v - 1
fi - e452vi - 1
fi - e500i - 1
fi - e501i - 1
fi - e503i - 1
fi - e504i - 1
fi - e514i - 1
fi - e515i - 1
fi - e541ii - 1
fr - e101i - 0
fr - e141ii - 1
fr - e160ai - 1
fr - e262i - 0
fr - e262ii - 1
fr - e304i - 1
fr - e305 - 1
fr - e307c - 1
fr - e322i - 1
fr - e322ii - 1
fr - e331iii - 1
fr - e332ii - 1
fr - e333iii - 1
fr - e335i - 1
fr - e335ii - 1
fr - e336i - 1
fr - e336ii - 1
fr - e339i - 1
fr - e341i - 1
fr - e341ii - 1
fr - e350i - 1
fr - e350ii - 1
fr - e352i - 1
fr - e352ii - 1
fr - e420i - 0
fr - e420ii - 1
fr - e425i - 1
fr - e425ii - 1
fr - e440aii - 1
fr - e440aiii - 1
fr - e440aiv - 1
fr - e440i - 0
fr - e452v - 1
fr - e458 - 1
fr - e460i - 1
fr - e460ii - 1
fr - e500i - 0
fr - e500iii - 1
fr - e501i - 1
fr - e501ii - 1
fr - e503i - 1
fr - e503ii - 1
fr - e504i - 1
fr - e504ii - 1
fr - e514i - 1
fr - e514ii - 1
fr - e515i - 1
fr - e544 - 1
fr - e545 - 1
fr - e553a - 1
fr - e553ai - 1
fr - e553aii - 1
fr - e629 - 1
fr - e640i - 1
fr - e900a - 1
fr - e905e - 1
fr - e905f - 1
fr - e905g - 1
fr - e924a - 1
fr - e927a - 1
fr - e965i - 1
fr - e965ii - 1
hu - e101i - 1
hu - e172iii - 1
hu - e262i - 1
hu - e304i - 1
hu - e305 - 1
hu - e322ii - 1
hu - e336ii - 1
hu - e350i - 1
hu - e352i - 1
hu - e440aii - 1
hu - e440aiii - 1
hu - e440aiv - 1
hu - e440i - 1
hu - e450viii - 1
hu - e452v - 1
hu - e452vi - 1
hu - e500i - 1
hu - e501i - 1
hu - e503i - 1
hu - e504i - 1
hu - e514i - 1
hu - e515i - 1
hu - e541ii - 1
it - e101a - 1
it - e101i - 1
it - e160ai - 1
it - e172iii - 1
it - e262i - 1
it - e304i - 1
it - e305 - 1
it - e322ii - 1
it - e352i - 1
it - e440aii - 1
it - e440aiii - 1
it - e440aiv - 1
it - e440i - 1
it - e450viii - 1
it - e452i - 1
it - e452v - 1
it - e452vi - 1
it - e500i - 1
it - e501i - 1
it - e503i - 1
it - e504i - 1
it - e514i - 1
it - e515i - 1
it - e541ii - 1
lt - e101i - 1
lt - e172ii - 1
lt - e172iii - 1
lt - e322ii - 1
lt - e440aii - 1
lt - e440aiii - 1
lt - e440aiv - 1
lt - e440i - 1
lt - e450iv - 1
lt - e450viii - 1
lt - e452v - 1
lt - e452vi - 1
lt - e500i - 1
lt - e515i - 1
lt - e541ii - 1
lv - e101i - 1
lv - e172ii - 1
lv - e172iii - 1
lv - e322ii - 1
lv - e440aii - 1
lv - e440aiii - 1
lv - e440aiv - 1
lv - e450iv - 1
lv - e450viii - 1
lv - e452v - 1
lv - e452vi - 1
lv - e500i - 1
lv - e501i - 1
lv - e503i - 1
lv - e514i - 1
lv - e515i - 1
lv - e541ii - 1
mt - e172ii - 1
mt - e172iii - 1
mt - e322ii - 1
mt - e440aii - 1
mt - e440aiii - 1
mt - e440aiv - 1
mt - e450iv - 1
mt - e450viii - 1
mt - e452v - 1
mt - e452vi - 1
mt - e541ii - 1
nl - e101i - 1
nl - e106 - 1
nl - e160ai - 1
nl - e172iii - 1
nl - e219 - 1
nl - e262i - 1
nl - e304i - 1
nl - e305 - 1
nl - e322ii - 1
nl - e350i - 1
nl - e352i - 1
nl - e388 - 1
nl - e440aii - 1
nl - e440aiii - 1
nl - e440aiv - 1
nl - e440i - 1
nl - e450viii - 1
nl - e452vi - 1
nl - e500i - 1
nl - e501i - 1
nl - e503i - 1
nl - e504i - 1
nl - e514i - 1
nl - e515i - 1
nl - e541ii - 1
nl - e543 - 1
nl - e544 - 1
nl - e553ai - 1
pl - e101i - 1
pl - e150d - 1
pl - e172iii - 1
pl - e262i - 1
pl - e304i - 1
pl - e305 - 1
pl - e322ii - 1
pl - e420i - 1
pl - e440aii - 1
pl - e440aiii - 1
pl - e440aiv - 1
pl - e440i - 1
pl - e450viii - 1
pl - e452v - 1
pl - e452vi - 1
pl - e501i - 1
pl - e503i - 1
pl - e504i - 1
pl - e514i - 1
pl - e515i - 1
pl - e541ii - 1
pl - e943b - 1
pt - e101i - 1
pt - e172iii - 1
pt - e262i - 1
pt - e322ii - 1
pt - e420i - 1
pt - e440aii - 1
pt - e440aiii - 1
pt - e440aiv - 1
pt - e440i - 1
pt - e450viii - 1
pt - e452v - 1
pt - e452vi - 1
pt - e500i - 1
pt - e501i - 1
pt - e503i - 1
pt - e504i - 1
pt - e514i - 1
pt - e515i - 1
pt - e541ii - 1
ro - e101i - 1
ro - e172iii - 1
ro - e322ii - 1
ro - e440aii - 1
ro - e440aiii - 1
ro - e440aiv - 1
ro - e450iv - 1
ro - e450viii - 1
ro - e452v - 1
ro - e452vi - 1
ro - e500i - 1
ro - e504i - 1
ro - e514i - 1
ro - e515i - 1
ro - e541ii - 1
sk - e101i - 1
sk - e172iii - 1
sk - e262i - 1
sk - e322ii - 1
sk - e420i - 1
sk - e440aii - 1
sk - e440aiii - 1
sk - e440aiv - 1
sk - e440i - 1
sk - e450iv - 1
sk - e450viii - 1
sk - e452v - 1
sk - e452vi - 1
sk - e501i - 1
sk - e504i - 1
sk - e541ii - 1
sl - e101i - 1
sl - e172iii - 1
sl - e262i - 1
sl - e322ii - 1
sl - e420i - 1
sl - e440aii - 1
sl - e440aiii - 1
sl - e440aiv - 1
sl - e440i - 1
sl - e450iv - 1
sl - e450viii - 1
sl - e452v - 1
sl - e452vi - 1
sl - e472e - 1
sl - e500i - 1
sl - e501i - 1
sl - e504i - 1
sl - e514i - 1
sl - e541ii - 1
sv - e101i - 1
sv - e172iii - 1
sv - e262i - 1
sv - e304i - 1
sv - e322ii - 1
sv - e440aii - 1
sv - e440aiii - 1
sv - e440aiv - 1
sv - e440i - 1
sv - e450viii - 1
sv - e452v - 1
sv - e452vi - 1
sv - e500i - 1
sv - e501i - 1
sv - e503i - 1
sv - e504i - 1
sv - e514i - 1
sv - e515i - 1
sv - e541ii - 1
sv - e553ai - 1

For

**Comment by hangy** [comment]
Is this fixed? The World and French additives list are identical now.
