### ISSUE TITLE
Reset password error - Undefined subroutine &Encode::find_mime_encoding

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#1183]
Undefined subroutine &Encode::find_mime_encoding called at /usr/local/lib/x86_64-linux-gnu/perl/5.20.2/Encode/MIME/Header.pm line 241.

**Comment by stephanegigandet** [comment]
cpan[1]> install Encode
Reading '/root/.cpan/Metadata'
  Database was generated on Thu, 05 Apr 2018 08:17:03 GMT
Encode is up to date (2.97).

cpan[2]> install Encode::MIME
Warning: Cannot install Encode::MIME, don't know what it is.
Try the command

    i /Encode::MIME/

to find objects with matching identifiers.

cpan[3]> install Encode::MIME::Header
Encode::MIME::Header is up to date (2.28).

**Comment by stephanegigandet** [comment]
That's kind of strange, that function is defined in Encode.pm which is called by the module.. Any idea @hangy

**Comment by hangy** [comment]
No idea. `@INC` path also does not look like it should load `Encode` from anywhere else. I'm afraid I don't know Perl well enogh to be a help.

**Comment by hangy** [comment]
Works in production.
