### ISSUE TITLE
Can't move products to Open Products Facts anymore

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1184]
Can't move products to Open Products Facts anymore
It's essential to speed up moderation.

**Comment by hangy** [comment]
That should never have been possible in the first place. Open Product Facts has never been known in `master`:

- https://github.com/openfoodfacts/openfoodfacts-server/blob/e9f7c54608cb663a67dccf9d5017a16c619d4e5d/lib/ProductOpener/Config_obf.pm#L260-L285
- https://github.com/openfoodfacts/openfoodfacts-server/blob/72e23a4460157383017f9339b6b04f1b7fc1e0d5/lib/ProductOpener/Config_off.pm#L406-L431
- https://github.com/openfoodfacts/openfoodfacts-server/blob/e9f7c54608cb663a67dccf9d5017a16c619d4e5d/lib/ProductOpener/Config_opff.pm#L289-L314

**Comment by stephanegigandet** [comment]
It's broken for images, not sure why, it may be related to the move of the product images from /srv to /srv2.

**Comment by stephanegigandet** [comment]
Fixed and deployed.
