### ISSUE TITLE
Adding "Gélatine de porc" adds "E428 gélatine" & "E441 gélatine animale" (comma related issue)

### ISSUE THREAD

**Issue by TaciteOFF** [openfoodfacts/openfoodfacts-server#119]
Il semblerait qu'ajouter dans une liste d'ingrédient "Gélatine de porc" ou "Gélatine porcine" ajoute 2 additifs à une fiche, E428 gélatine et E441 gélatine animale.

Voir : http://fr.openfoodfacts.org/produit/3023290454169

En revanche ce problème n'est pas présent sur toutes les fiches. Je me demande si ce n'est pas le fait d'ajouter un point au lieu d'une virgule qui génère le conflit dans la reconnaissance.
Car avec ce produit, on n'a bien que E441 qui est présent avec la mention "Gélatine porcine" : http://fr.openfoodfacts.org/produit/3023290720417

A priori pas de problème pour "Gélatine bovine" (cf http://fr.openfoodfacts.org/produit/3023290166079 )

**Comment by stephanegigandet** [comment]
I can't reproduce it now, but I think the underlying issue has been fixed by bug #801
