### ISSUE TITLE
The ingredient parser doesn't like Chinese commas

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1199]
https://cn.openfoodfacts.org/ingredient/%E6%B0%B4%EF%BC%8C%E7%99%BD%E7%A0%82%E7%B3%96%EF%BC%8C%E6%9E%9C%E8%91%A1%E7%B3%96%E6%B5%86%EF%BC%8C%E8%9C%82%E8%9C%9C%EF%BC%8C%E9%A3%9F%E5%93%81%E6%B7%BB%E5%8A%A0%E5%89%82%EF%BC%88%E4%BA%8C%E6%B0%A7%E5%8C%96%E7%A2%B3%EF%BC%8C%E6%9F%A0%E6%AA%AC%E9%85%B8%EF%BC%8C%E6%B0%AF%E5%8C%96%E9%92%BE%EF%BC%8C%E6%9F%A0%E6%AA%AC%E9%85%B8%E9%92%A0%EF%BC%8C%E8%8B%AF%E7%94%B2%E9%85%B8%E9%92%A0%EF%BC%8C%E5%AE%89%E8%B5%9B%E8%9C%9C%EF%BC%8C%E7%94%9C%E8%8F%8A%E7%B3%96%E8%8B%B7%EF%BC%8C%E6%97%A5%E8%90%BD%E9%BB%84%EF%BC%89%EF%BC%8C%E9%A3%9F%E7%94%A8%E9%A6%99%E7%B2%BE

```
Products that contain the ingredient 水，白砂糖，果葡糖浆，蜂蜜，食品添加剂（二氧化碳，柠檬酸，氯化钾，柠檬酸钠，苯甲酸钠，安赛蜜，甜菊糖苷，日落黄），食用香精 - 中华人民共和国

```

**Comment by GroverChouT** [comment]
Don't forget we often using '、' as '，'.
