### ISSUE TITLE
Support for allergens in ingredients list

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#12]
Since December 13th 2014, ingredients lists now have allergens in bold/italic/underline.
In Open Food Facts, we can create a special syntax to surround allergens with underscores.

e.g. protéines de _lait_, farine de froment (_gluten_)
(github transforms underscored words to italic)

Phases:
1. Accept the enhanced syntax, display allergens in bold.
2. Add allergerns from the ingredient list as "allegerns" tags (similar to the current "traces")
3. Create a taxonomy for allergens / traces.
4. Autodetection of allergens in ingredients lists that do not use the new syntax?

Possible extensions:

A. \* for organic ingredients, *\* for fair trade ingredients, **\* for organic + fair trade ingredients

**Comment by stephanegigandet** [comment]
1. (allergens surrounded by underscores _ or in CAPS) 2. and 3. are done.

**Comment by aleksejrs** [comment]
> Autodetection of allergens in ingredients lists that do not use the new syntax?

Why not only this?

**Comment by stephanegigandet** [comment]
Autodetection of allergens in ingredients list without the underscores also has been implemented and deployed.
