### ISSUE TITLE
Two words errors in CONTRIBUTING.md

### ISSUE THREAD

**Issue by JieDiscovery** [openfoodfacts/openfoodfacts-server#1217]
**Summary:** 
In the  CONTRIBUTING.md, I found that on the first paragraph, there are two little words "Explore" and "assigne" which could be corrected.

![off correction](https://user-images.githubusercontent.com/36447962/40590089-3e9d4256-61f9-11e8-906b-4a47a81cdda3.jpg)

**Steps to reproduce:**

We can simply correct them to make it looks more clear.

**Comment by Nikkistorme** [comment]
I think explore can stay. It makes sense in the context of the paragraph.
And "assignee" has been changed to "assigned."
