### ISSUE TITLE
[ru] "Why it matters" string cut off in Russian

### ISSUE THREAD

**Issue by aleksejrs** [openfoodfacts/openfoodfacts-server#1237]
`https://ru.openfoodfacts.org/cgi/product.pl?type=edit&code=3017620429484`

```
Информация и данные должны поступать с упаковки товара и этикеток (а не с других сайтов или сайта производителя), а фотографии должны быть сняты вами.
→ <а href="">Почему это важно
```

**Comment by hangy** [comment]
Just an observation: The Translation seems to be correct:

https://github.com/openfoodfacts/openfoodfacts-server/blob/a20838ccd90b752e1b20632b728f0ed2297db20e/po/common/ru.po#L2605-L2609

**Comment by VaiTon** [comment]
So what's the problem? @aleksejrs

**Comment by aleksejrs** [comment]
Compare to https://us.openfoodfacts.org/cgi/product.pl?type=edit&code=3017620429484 @VaiTon

**Comment by VaiTon** [comment]
Oh just found something: here the `span` tag is not closed. Let's see if this fixes the problem.
https://github.com/openfoodfacts/openfoodfacts-server/blob/881dfd85a36384130cbccae04d9d4f7646ce989b/cgi/product_multilingual.pl#L869

**Comment by aleksejrs** [comment]
Huh. The first "a" is also Cyrillic…
