### ISSUE TITLE
Add allergens input field in addition to the traces field in product edit form

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#1238]
Currently we have 2 fields for allergens:

- a "traces" field which is a taxonomized tag field that is listed below the ingredients list in the product edit form
- an "allergens" field which is also a taxonomy tag field, but that is not in the product edit form -> its value is computed from the ingredients list. It detects allergens that are either in all caps (when the ingredient list is not all in all caps, such as in the US), or that are between underscores.

The issue is that there isn't a good place to put allergens that are listed on the label with something like "Contains: soy, milk".  

Proposed change:

Add a "contains" field, and add it to the product edit form, just above "traces".

Use the current ingredient text detection of allergens to add allergens to the "contains" field (instead of the "allergens" field). Existing values (entered by users or imported from producers) are kept, the ingredient list detection only adds values to the "contains" field.

Merge "contains" and "traces" to populate the "allergens" field.

**Comment by aleene** [comment]
The nice thing about allergens is that it can not be edited by the user, giving it a higher quality. The detection should be extended to all ingredients (not just uppercased or underscored) and also the us ingredients lists. Allergens are to important to leave to the user only. So the user should not be able to delete something from the contains field.
Not sure if you should mix contains and traces in allergens. How do allergic people handle these two fields?

**Comment by stephanegigandet** [comment]
"user should not be able to delete something from the contains field." --> they would not, they may only add to it.

For some allergens like gluten, there are people who are truly allergic and who can't eat trace amounts. There are also people who are gluten or lactose intolerant but who will not suffer allergic reactions if they eat a very small amount. That's why I want to make the distinction, plus a field that merges the two.

**Comment by stephanegigandet** [comment]
Following discussions on slack, I will keep the existing "allergens" and "traces" tag fields, and add the "allergens" field to the product edit form. Allergens detected from the ingredients fields will still be added to the allergens field.

I will add detection of traces from ingredients: bug #1242

**Comment by stephanegigandet** [comment]
I'm changing a bit how the fields work:
- the traces and allergens fields are user editable, but they are not populated by ingredient detection
- I'm adding 2 fields allergens_from_ingredients and traces_from_ingredients that are populated automatically from the ingredient list
- the allergens_tags and traces_tags contain unique tags from the merged allergens + allergens_from_ingredients_list (and traces + traces_from_ingredients_list)

This is to resolve issues with imports and to make it more clear what comes from what.

**Comment by stephanegigandet** [comment]
Deployed in July 2018.
