### ISSUE TITLE
German allergens list contains Bergkäse (mountain cheese), although not mentioned in ingredients

### ISSUE THREAD

**Issue by SantosSi** [openfoodfacts/openfoodfacts-server#1239]
### What

- When the ingredients list contains undetermined milk products (either milk, whey or skimmed milk powder), the list of products causing allergies contains Bergkäse (mountain cheese), e.g.: https://de.openfoodfacts.org/produkt/4316268433372/big-choc-mandel-ice-fantasy. The english version lists milk (german: Milch) instead.

### Steps to reproduce
Add one of the above mentioned milk products to an ingredients list.

### Expected behavior
List Milch (milk) instead.

### Observed behavior
Bergkäse is listed.

**Comment by hangy** [comment]
@stephanegigandet Translation issue in https://github.com/openfoodfacts/openfoodfacts-server/blob/9cf2054bfef57be02517f676284e9d840bf099ce/taxonomies/allergens.txt#L225 - I updated it to the fixed Wiki verion in 2d0346ad350af9cb6b6210fc9e2cca057eff92d1.

**Comment by SantosSi** [comment]
Lactose is part of milk and should not be used for the whole. We should use "milk" instead.

**Comment by aleksejrs** [comment]
OK https://en.wikipedia.org/wiki/Milk_allergy#Diagnosis

**Comment by benbenben2** [comment]
This is solved. Bergkaese is in second position now.

`de:Milch, Bergkäse, Blauschimmelkäse, Butter, Buttermilch, Buttermilchpulver, Butterreinfett, Camembert, Cheddar, Edamer, Edamer-Käse, Emmentaler,  Frischkäse, Gorgonzola, Gouda, Hartkäse, Joghurt, Joghurtpulver, Käse, Käsepulver, Kondensmilch, Kuhmilch, Kuhvollmilch, Laktose, Rohmilch, Milchzucker, Milcheiweiß, Milchpulver, Milcherzeugnisse, Milcherzeugnissen, Magermilchpulver, Magermilchjoghurt, Magermilchkonzentrat, Magermilchjoghurtpulver, Magermilch, Magerquark, Molkenpulver, Molkenerzeugnis, Molkeneiweißkäse, Milchschokolade,  Mozzarella, Pecorino, Quark, Ricotta, Speisequark, Sahne, Sahnepulver, Sahnejoghurt, Sauermilchquark, Sauerrahm, Rahm, Rahmjoghurt, Sauermilch, Sauerrahmpulver, Schlagsahne,  Süssmolkenpulver, Süßmolkenpulver, Vollmilch, Vollmilchschokolade, Vollmilchpulver, Ziegenmilch, Süßmolke, Süssmolke, Butterfett, Kondensmagermilch, Joghurterzeugnis, Schafsmilch, Schafmilch, Käsereimilch, Milchfett, Milchprotein, Molke, Sauermolke, Molkeneiweiß, Molkeneiweiss, Molkepulver, Milcheiweißerzeugnis, Milcheiweisserzeugnis, Magermilchpulverzusatz, Molkenprotein, Buttereinfett, Süßmolkepulver, Süssmolkepulver, Vollmilchschokoladeüberzug`

![Screenshot_20231208_233248](https://github.com/openfoodfacts/openfoodfacts-server/assets/110821832/ea0f7203-b25f-4829-a584-5e8b8a51ca2d)


I will close the issue.
