### ISSUE TITLE
Pagination broken above 999 page

### ISSUE THREAD

**Issue by nicolasleger** [openfoodfacts/openfoodfacts-server#124]
General pagination above the `999`th page seems broken.
Example for the link displayed on the French homepage http://fr.openfoodfacts.org/1557

- Working
  - http://fr.openfoodfacts.org/2
  - http://fr.openfoodfacts.org/14
  - http://fr.openfoodfacts.org/999
- Failing
  - http://fr.openfoodfacts.org/1000
  - http://fr.openfoodfacts.org/1557 (last page)

**Comment by stephanegigandet** [comment]
There was a limit of 1000 pages, I removed it.

**Comment by nicolasleger** [comment]
Quick reaction, thanks.

**Comment by stephanegigandet** [comment]
Thanks for spotting and reporting the bug. :)
