### ISSUE TITLE
Trim white space from images during cropping

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#1243]
Some producers send us product images that have a white space around them. Use ImageMagick's Trim function to remove the white space during cropping / selection.

**Comment by teolemon** [comment]
http://www.imagemagick.org/Usage/crop/#trim

**Comment by hangy** [comment]
Fixed by 78a38959e1b8fad7d5b22163ee6acb9912b6ce48
