### ISSUE TITLE
Also hide nutrition photo area when selecting "Nutrition facts are not specified on the product."

### ISSUE THREAD

**Issue by SantosSi** [openfoodfacts/openfoodfacts-server#1244]
**Checklist**

- [X] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-server/issues) before creating or reporting a issue.

- [ ] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.

**Summary:** 
When activating the checkbox "Nutrition facts are not specified on the product." the nutrition table is hidden, but the image area is not.

**Steps to reproduce:** 
Click the "Nutrition facts are not specified on the product." checkbox

**Expected behavior:** 
The nutrition image area should be hidden.

**Observed behavior:** 
The nutrition image area is not hidden.

**Comment by VaiTon** [comment]
Still having this bug, pretty annoying lol
