### ISSUE TITLE
Remove "Ingredients: " keyword when running OCR on the ingredients text

### ISSUE THREAD

**Issue by SantosSi** [openfoodfacts/openfoodfacts-server#1247]
**Checklist**

- [X] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-server/issues) before creating or reporting a issue.

**Summary:** 
Remove "Ingredients" (resp. "Zutaten" in German), with and without a ":" colon, keyword when running OCR on the ingredients text. It can also be used as a marker.

**Steps to reproduce:** 
With the beginning of the ingredients at the top end of the image, click Cloud Vision.

**Expected behavior:** 
The string usually resp. always precedes the ingredients list, but is not an ingredient itself. 

**Observed behavior:** 
The keyword should be removed from the beginning.

**Comment by aleksejrs** [comment]
Russian: "Состав:", "Ингредиенты:".

**Comment by teolemon** [comment]
@stephanegigandet has started work on this. It's French only for the moment, but thanks for the stopwords. Keep them coming in your language.
poke @aleene

**Comment by teolemon** [comment]
fixed by @stephanegigandet
