### ISSUE TITLE
Registering yields blank page

### ISSUE THREAD

**Issue by kylesorkness** [openfoodfacts/openfoodfacts-server#1249]
**Checklist**

- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-server/issues) before creating or reporting a issue.

- [ ] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.

**Summary:** 

Registering yielded a blank page rather than confirmation.

**Steps to reproduce:** 

Register.

**Expected behavior:** 

I expected confirmation of successful registration.

**Observed behavior:** 

Finalizing registration by clicking the "Submit Query" button yielded a "blank" page. See attached screenshot. (Note: registration was successful.)

![open_food_facts_registration_issue](https://user-images.githubusercontent.com/6548430/42062988-a500adf4-7afd-11e8-80d9-71d5db2026c4.png)

**Comment by CharlesNepote** [comment]
I tried to register on dev server and it seems the problem does not occur anymore, see screenshot below.

![image](https://user-images.githubusercontent.com/562352/60257396-a7aa7b80-98d3-11e9-9f8c-99268a5492b8.png)

I close the bug but you can reopen if I missed something.
