### ISSUE TITLE
Apache + mod_perl segfault when loading startup script: segfault error 4 in encoding.so

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#1250]
The issue is caused by binmode being run in one of the modules loaded by the startup_apache2.pl script:

in syslog:

Jul  4 16:21:01 ns3362784 CRON[11097]: (root) CMD (/usr/local/rtm/bin/rtm 27 > /dev/null 2> /dev/null)
Jul  4 16:21:13 ns3362784 kernel: /usr/sbin/apach[10620]: segfault at 18 ip 0000717db2f5b16c sp 000075f3df8c7160 error 4 in encoding.so[717db2f59000+6000]
Jul  4 16:21:13 ns3362784 kernel: grsec: Segmentation fault occurred at 0000000000000018 in /usr/sbin/apache2[/usr/sbin/apach:10620] uid/euid:0/0 gid/egid:0/0, parent /usr/sbin/apache2ctl[apache2ctl:10617] uid/euid:0/0 gid/egid:0/0
Jul  4 16:21:14 ns3362784 apache2-obf[10601]: Starting web server: apache2/usr/sbin/apache2ctl: line 138: 10620 Segmentation fault      $HTTPD ${APACHE_ARGUMENTS} -k $ARGV
Jul  4 16:21:14 ns3362784 apache2-obf[10601]: Action 'start' failed.

**Comment by hangy** [comment]
I believe this was fixed completely in a912ee0852dfc3b3f76f813a2c9098ef3d6b1d95
