### ISSUE TITLE
Can't go back to page 1 when on another page

### ISSUE THREAD

**Issue by TaciteOFF** [openfoodfacts/openfoodfacts-server#126]
Hello,

When you land on the main page, if you go to page 2 or 3, clicking on the "1" to go back to the first page does nothing.

With Safari 8.0.5 on Mac.

**Comment by stephanegigandet** [comment]
Fixed by commit https://bitbucket.org/openfoodfacts/product-opener/commits/3c2874ae24539f1ee4b74cc332f9197c0c01b0eb
