### ISSUE TITLE
Additive ranking changes based on linking word. (comma related issue)

### ISSUE THREAD

**Issue by TaciteOFF** [openfoodfacts/openfoodfacts-server#127]
Si je tape "gomme xanthane et gomme guar", la gomme guar se retrouvera tout en bas de la liste des additifs.
Si je tape "gomme xanthane, gomme guar", la gomme guar se retrouvera juste après la gomme xanthane dans la liste des additifs.

Test effectué sur cette fiche : http://fr.openfoodfacts.org/produit/3478820073714/soja-special-cuisine-source-d-omega-3-jardin-bio

**Comment by stephanegigandet** [comment]
The ingredient parser now supports "X and Y" correctly. It also fixes this issue with additives.
