### ISSUE TITLE
[FOUNDATION] cestemballepresdechezvous div problem

### ISSUE THREAD

**Issue by TaciteOFF** [openfoodfacts/openfoodfacts-server#128]
Hello,

![capture](https://cloud.githubusercontent.com/assets/11161632/7866786/f0d6319a-0571-11e5-8088-4a465ffd44bd.png)

The div for product images on the map has to be edited to fix this :)

Thanks!

**Comment by teolemon** [comment]
It seems fixed @TaciteOFF ?

**Comment by TaciteOFF** [comment]
Fixed, thanks :)
