### ISSUE TITLE
Save-button website not visible on iPad 

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#1287]
**Checklist**

- [X ] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-server/issues) before creating or reporting a issue.

- [X ] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.

**Summary:** 

Website displays wrongly on iPad. In edit-mode I can no longer see the save-button!!!

**Steps to reproduce:** 

Used OFF in edit-mode on Ipad

**Add system logs:**

None, but I have a screen-shot.

**Expected behavior:** 

Show the save button.

**Observed behavior:** 

The save-button seems to be off-screen to the right.

**Comment by syl10100** [comment]
Same problem on my laptop

![save_button_not_display](https://user-images.githubusercontent.com/45109552/48671282-13e72480-eb26-11e8-9f89-86210ebaff60.jpg)

**Comment by stephanegigandet** [comment]
@aleene : Fix currently on the dev server:
https://fr.openfoodfacts.org/cgi/product.pl?type=edit&code=3484700000978
Can you try?
