### ISSUE TITLE
Detailed stats for a category: no column names

### ISSUE THREAD

**Issue by aleksejrs** [openfoodfacts/openfoodfacts-server#1290]
**Summary:** 

The detailed mode of the table on a category page has lost the column names.

**Steps to reproduce:** 

1. Open https://world.openfoodfacts.org/category/plant-based-foods-and-beverages
2. Check the "Show detailed stats: standard deviation, minimum, maximum, 10th and 90th percentiles" box.
3. Look at the columns that appear.

**Expected behavior:** 

All the columns used to have useful names in the table's header.

**Observed behavior:** 

Only the default columns have names.  The text "Show detailed stats: standard deviation, minimum, maximum, 10th and 90th percentiles" is not helping me understand what the unnamed columns are. I think two of the columns were median and average.

**Comment by hangy** [comment]
LGTM 
![image](https://user-images.githubusercontent.com/87124/48967330-f19a4e80-efde-11e8-9a24-7caa4a1c1cc2.png)
