### ISSUE TITLE
broken links 

### ISSUE THREAD

**Issue by rbigueras** [openfoodfacts/openfoodfacts-server#1294]
**Checklist**

- [ x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-server/issues) before creating or reporting a issue.

- [ x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.

**Summary:** 

Summarize your issue in one sentence (what goes wrong, what did you expect to happen)

**Steps to reproduce:** 

just go to https://world.openpetfoodfacts.org/ all images are broken

**Expected behavior:** 

the images should not be broken

**Observed behavior:** 

its a blank image. Also the website is not secure

**Comment by teolemon** [comment]
It seems the certificate hasn't been renewed @stephanegigandet

**Comment by teolemon** [comment]
This has been solved by @stephanegigandet by renewing the CERT.
