### ISSUE TITLE
Square brackets don't display

### ISSUE THREAD

**Issue by TaciteOFF** [openfoodfacts/openfoodfacts-server#1295]
https://fr.openfoodfacts.org/produit/5449000237354/coca-cola?rev=8

Quantity : 3 * [8 * 200 ml]

Shown on the home page:  3 * * 200 ml

**Steps to reproduce:** 

Put square brackets in the product quantity

**Comment by aleksejrs** [comment]
It happens with product names, too, and varies. Sometimes the bracketed part is skipped in the tooltip only, sometimes only the last bracket is skipped on the page itself.

**Comment by hangy** [comment]
Looks like this has been fixed: 
![image](https://user-images.githubusercontent.com/87124/48960819-291de200-ef70-11e8-8a22-c4f71ca98645.png)

**Comment by aleksejrs** [comment]
The closing bracket is still sometimes missing in the list at https://ru.openproductsfacts.org/
