### ISSUE TITLE
Bringing all domains on feature parity with fr.OFF & en.OFF

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#13]
Many languages have a different layout or outdated text, or even miss the Products being added link. 
We should bring them on par with the en.OFF and fr.OFF websites.

**Comment by teolemon** [comment]
I've added the state of the Index, Discover and Contribute pages (loaded, to be loaded…)
https://en.wiki.openfoodfacts.org/Translations_-_Index_page
https://en.wiki.openfoodfacts.org/Translations_-_Contribute_page
https://en.wiki.openfoodfacts.org/Translations_-_Discover_page

**Comment by hangy** [comment]
Is this still an issue?

**Comment by teolemon** [comment]
yes and no (we still have no automatic deployment of translations and static content).
Closing since the original issue has been largely fixed though
