### ISSUE TITLE
Content : wrong date format in English press page

### ISSUE THREAD

**Issue by nicolasleger** [openfoodfacts/openfoodfacts-server#130]
For example `21/05/2012` at http://world.openfoodfacts.org/press

**Comment by stephanegigandet** [comment]
I respectfully disagree. ;-) http://en.wikipedia.org/wiki/Date_format_by_country

I guess we should just say May 5th 2012 to avoid ambiguities.

**Comment by nicolasleger** [comment]
@stephanegigandet My bad, I took the US date format for world one.
You're right might be clearer to write down the month.
Thanks
