### ISSUE TITLE
Broken links in Open Pet Food Facts

### ISSUE THREAD

**Issue by rbigueras** [openfoodfacts/openfoodfacts-server#1302]
### Steps to reproduce
- go to https://world.openpetfoodfacts.org/discover
- the image links are broken, but the website is still up 

### Expected behavior
- Images should be shown 

### Observed behavior
- No images 

### Part of
- #5536

**Comment by teolemon** [comment]
This should be solved. Can you confirm?

**Comment by rbigueras** [comment]
images are still down

**Comment by CharlesNepote** [comment]
https://validator.w3.org/checklink?uri=https%3A%2F%2Fworld.openpetfoodfacts.org%2Fdiscover&hide_type=all&depth=&check=Check

Error 404 => 18
