### ISSUE TITLE
Unresponsive link

### ISSUE THREAD

**Issue by rbigueras** [openfoodfacts/openfoodfacts-server#1304]
**Checklist**

- [x ] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-server/issues) before creating or reporting a issue.

- [ x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.

**Summary:** 

On the search page, the "permanent link to these results" link doesn't go anywhere.

**Steps to reproduce:** 

use the search tab and click on the " Permanent link to these results, shareable by e-mail and on social networks" the link doesn't take you anywhere

**Expected behavior:** 

should move onto another page

**Observed behavior:** 

stayed on the same page

**Comment by hangy** [comment]
If you are on the permanent link already, the link won't change. Otherwise, when on the initial search result (URL `/cgi/search.pl?search_terms=test&search_simple=1&action=process`), the page will look the same, but the URL will change.
