### ISSUE TITLE
Android app 

### ISSUE THREAD

**Issue by rbigueras** [openfoodfacts/openfoodfacts-server#1305]
**Checklist**

- [ x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-server/issues) before creating or reporting a issue.

- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.

**Summary:** 

permission denied after going to manage account

**Steps to reproduce:** 

log in, click on manage account, it diverts back to openfoodfacts.org webpage and gives me an error permission denied 

**Expected behavior:** 
let me manage my account 
**Observed behavior:** 

and error message denying me permission

**Comment by teolemon** [comment]
Can you file the bug under the Android repository?

**Comment by hangy** [comment]
Moved to openfoodfacts/openfoodfacts-androidapp#1965
