### ISSUE TITLE
Android App Beta 

### ISSUE THREAD

**Issue by rbigueras** [openfoodfacts/openfoodfacts-server#1306]
**Checklist**

- [ x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-server/issues) before creating or reporting a issue.

- [ ] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.

**Summary:** 
I logged in and I'm still under anonymous 

**Steps to reproduce:** 

use the android app beta, and click on anonymous, 
the app asks to log in, 
log in
once logged in the user's name is still anonymous
and when you try to relog in, it says you already are.
**Add system logs:**

Add logcat files here (if you are able to add).

**Expected behavior:** 

log in see name
**Observed behavior:** 

log in, see anonymous

**Comment by teolemon** [comment]
Can you file the bug under the Android repository?

**Comment by hangy** [comment]
Moved to openfoodfacts/openfoodfacts-androidapp#1966
