### ISSUE TITLE
"Cacahuètes" category links to "Premier cru"

### ISSUE THREAD

**Issue by BenibenOFF** [openfoodfacts/openfoodfacts-server#1309]
When i'm searching the category "cacahuètes", the website displays the category "premier cru". A problem of synonyms must be the reason of this bug.

![taxo](https://user-images.githubusercontent.com/19907059/43507818-644ee61e-956e-11e8-8f9f-8a0545d4d972.jpg)

**Comment by odtvince** [comment]
Isn't this one fixed already?

**Comment by CharlesNepote** [comment]
@BenibenOFF I can't reproduce. Can you give the process to reproduce?

I made a search "cacahuètes" category and obtain 229 results: 4 of them have the "Premier cru" category. I deleted the "Premier cru" from this 4 products. Do you still have a problem?
