### ISSUE TITLE
Discover and Contribute page URLs were mistakenly translated to German

### ISSUE THREAD

**Issue by SantosSi** [openfoodfacts/openfoodfacts-server#1310]
**Checklist**

- [X] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-server/issues) before creating or reporting a issue.

**Summary:** 
Page names in the german website version were mistakenly translated, but should be left untranslated: "discover" was translated to "entdecken" and "contribute" to "beitragen", e.g. https://de.openfoodfacts.org/entdecken should be https://world-de.openfoodfacts.org/discover or https://de.openfoodfacts.org/discover, both load the expected content in German.

**Steps to reproduce:** 
Open https://de.openfoodfacts.org, click on Entdecken or Beitragen in the upper right corner.

**Expected behavior:** 
The german translated page of Discover/Contribute should appear.

**Observed behavior:** 
An error message is displayed: Fehler
Ungültige Adresse.
(In English: Error
Invalid address.)

**Comment by lan33** [comment]
This is the same problem as for footer links, cf. #931.
I'll fix this in `/po/common/de.po`.

**Comment by VaiTon** [comment]
![image](https://user-images.githubusercontent.com/12072630/59117740-d4134d80-894e-11e9-880a-99bf25a49489.png)
Which translates to "Error: Invalid URL"
![image](https://user-images.githubusercontent.com/12072630/59117746-d83f6b00-894e-11e9-862f-2f5effda9550.png)
