### ISSUE TITLE
code-of-conduct.html: "Reporting abuse" header is on Crowdin in one string with the following paragraph, appears strangely there

### ISSUE THREAD

**Issue by aleksejrs** [openfoodfacts/openfoodfacts-server#1314]
https://crowdin.com/translate/openfoodfacts/122/en-ru

`Reporting abuse</0>If you believe someone is harassing you or has otherwise violated this Code of conduct, please contact us at abuse@openfoodfacts.org to send us an abuse report.`

The translation of the whole string appears bold in the sidebar, followed by non-bold original text excluding "Reporting abuse".

**Comment by CharlesNepote** [comment]
Control: https://ru.openfoodfacts.org/code-of-conduct (?)

Is it fixed?

**Comment by teolemon** [comment]
The file has been deleted if you click on the link

**Comment by teolemon** [comment]
https://crowdin.com/translate/openfoodfacts/452/en-ru
