### ISSUE TITLE
Remove HTML from translatable content

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1319]
`<Img src="/ images / misc / Available_on_the_App_Store_Badge_EN_135x40.png " alt="Disponibile su App Store" width="135 " height="40 " />`

ios_app_badge

**Comment by teolemon** [comment]
I corrected it in that case, but it should be 2 strings:
`/images/misc/Available_on_the_App_Store_Badge_EN_135x40.png`
`Available on the App Store`

**Comment by VaiTon** [comment]
Fixed by #2749
