### ISSUE TITLE
Not enough space to edit labels (and categories?) conveniently.

### ISSUE THREAD

**Issue by aleksejrs** [openfoodfacts/openfoodfacts-server#1322]
People suggest that all kinds of stuff without a special field be put into "labels", but 500 characters do not fit into a single line. Normal categories at OFF also do not fit.

**Comment by CharlesNepote** [comment]
Hi @aleksejrs!

I'm not sure to understand your need. Do you mean that the "labels" field should accept more than 500 characters?

I've made a test on my local OFF installation and it seem it's possible to have more than 500 chars on both "labels" and "categories" fields:

![capture d ecran_2019-01-15_17-11-34](https://user-images.githubusercontent.com/562352/51193360-f990b380-18e8-11e9-9dde-21040a164aaa.png)

I've done a search on the whole database and I found only 16 products where the "labels" field countains more than 400 chars. I guess if it were a real need, there would have much products with 400+ chars in the "labels" field, isn't it?

Could you explain your need further? Thanks!

**Comment by aleksejrs** [comment]
I am talking about the edit mode.

**Comment by CharlesNepote** [comment]
Do you mean the size of the field should be visually bigger?

Did you see that the field size is growing while you add more content? Isn't it sufficient?

**Comment by aleksejrs** [comment]
It is not growing.
![screenshot from 2019-01-16 15-22-32](https://user-images.githubusercontent.com/1025861/51248949-c7dc2300-19a2-11e9-87da-6b96648e3b4f.png)

**Comment by CharlesNepote** [comment]
I apologize, you're right, it doesn't. Thanks for the screenshot, it helps.

We can solve this in two ways I think:

- [ ] the "`line-height`" CSS selector for the keywords is `1.5` which, I think, is big: we could have `1.2`; and the "`min-height`" for the field is `3rem`: I'm not sure but I will make some tests with "`auto`" or something else;
- [ ] the field could grow up while you type: it might need javascript code, I'll investigate

If you have technical skill don't hesitate to suggest some solutions.

Thanks again.

**Comment by aleksejrs** [comment]
The Ingredients field is already resizable.

**Comment by CharlesNepote** [comment]
@aleksejrs : the correction is deployed on OFF website (resizable box). Did you try it? Is that suit you?

**Comment by aleksejrs** [comment]
@CharlesNepote : Looks good (I haven't tried saving after resizing). Thanks.

**Comment by VaiTon** [comment]
Can this be closed?
