### ISSUE TITLE
Chinese comma "、" isn't considered a comma / delimiter

### ISSUE THREAD

**Issue by TaciteOFF** [openfoodfacts/openfoodfacts-server#1324]
、should be added as delimiter

**Comment by aleene** [comment]
Is that another separator than in this text? The transcribed chinese (and separators) is from Google translate

**Comment by hangy** [comment]
> Is that another separator than in this text ([https://world.openfoodfacts.org/product/4891028710660/no-sugar-jasmine-tea-drink-維他](https://world.openfoodfacts.org/product/4891028710660/no-sugar-jasmine-tea-drink-%E7%B6%AD%E4%BB%96))? The transcribed chinese (and separators) is from Google translate

According to [Unicode Lookup](https://unicodelookup.com/#%EF%BC%8C/1), that should be a fullwidth comma (U+FF0C). It was added in b26f0d1ffc5e33e2f90ca1f39c05350a185b5d2c, too. Based on the current text ""水，香片（茉莉綠茶），維他命（酸度調節劑（500））。"", tags `"ingredients_tags":["en:water","zh:香片（茉莉綠茶）","zh:維他命（酸度調節劑（500））"]` were [extracted](https://cn.openfoodfacts.org/api/v1/product/4891028710660.json). The commas look good IMHO. I'll create a PR to fix the unrecognized parenthesis.

**Comment by VaiTon** [comment]
@hangy can we close this?

**Comment by hangy** [comment]
No clue. I unassigned myself, because there was no response from TaciteOFF, and I thought everything looks OK.

**Comment by TaciteOFF** [comment]
Seems OK now
