### ISSUE TITLE
All projects call themselves Open Food Facts

### ISSUE THREAD

**Issue by aleksejrs** [openfoodfacts/openfoodfacts-server#1327]
This can make people upload food to the wrong project.

**Comment by teolemon** [comment]
Thx. 
This has been fixed in https://github.com/openfoodfacts/openfoodfacts-server/commit/7871dcd578d6e9f5e0f51fd86b2b33ebcfe366f0 and other commits.
This will be fixed in the next production refresh

**Comment by teolemon** [comment]
@aleksejrs can you confirm it's fixed in prod ?

**Comment by aleksejrs** [comment]
@teolemon, can't you check it yourself?

* https://ru.openpetfoodfacts.org/ and https://ru.openproductsfacts.org/ say "Открытые Факты о Еде - Россия"
* https://world.openpetfoodfacts.org/ and https://world.openproductsfacts.org/ say "Open Food Facts - World"

I don't remember what the rest is suppose to look like; the Russian text seems to contain ancient typos.

**Comment by teolemon** [comment]
Great news @aleksejrs this is fixed
