### ISSUE TITLE
Allergens list displays a blank page

### ISSUE THREAD

**Issue by nicolasleger** [openfoodfacts/openfoodfacts-server#133]
Seen in the World version allergens list (with 292 products) at http://world.openfoodfacts.org/allergens

> http://world.openfoodfacts.org/allergen/ a **blank page**

Also in the French version (**but with only** 16 products) at http://world.openfoodfacts.org/allergenes

> [http://fr.openfoodfacts.org/allergene/en:](http://fr.openfoodfacts.org/allergene/en:) a products list

**Comment by hangy** [comment]
I think this is fine. https://world.openfoodfacts.org/allergens displays 3849 allergens, and https://fr.openfoodfacts.org/allergenes displays 1906 allergens. Feel free to reopen, if you disagree. 🙂
