### ISSUE TITLE
MongoDB::NetworkError on production server

### ISSUE THREAD

**Issue by Bartozzz** [openfoodfacts/openfoodfacts-server#1330]
**Summary:** 

Endpoints from [API documentation](https://en.wiki.openfoodfacts.org/API/Read/Product) are not working anymore. The same applies for other endpoints I've been calling in my [`Foodie app`](https://github.com/Bartozzz/foodie-app).

**Steps to reproduce:** 

Open [`https://world.openfoodfacts.org/brand/monoprix.json`](https://world.openfoodfacts.org/brand/monoprix.json).

**Expected behavior:** 

Get list of products from brand `Monoprix`.

**Observed behavior:** 

```
Software error:

MongoDB::SelectionError: No readable server available for matching read preference primary. MongoDB server status:
Topology type: Single; Member status:
  localhost:27017 (type: Unknown, error: MongoDB::NetworkError: Could not connect to 'localhost:27017': Connection refused )

For help, please send mail to the webmaster (contact@openfoodfacts.org), giving this error message and the time and date of the error.
```

**Comment by teolemon** [comment]
Hey @Bartozzz ,
We had a very huge broadcast on French TV, and although we scaled the servers massively, we had to disable a few things.
We're working on it as we speak.

Can you join us on http://slack.openfoodfacts.org for status and API updates ?

Also, it would be great if you could help with the Polish translations. We're presenting the project to an 🇪🇺  European event soon, and it would be great to have the app and site in Polish 💪 
https://translate.openfoodfacts.org/project/openfoodfacts/pl#

**Comment by Bartozzz** [comment]
Sure, no problem – I'll translate a few things 😄

**Comment by Bartozzz** [comment]
Everything is working now. Thanks!
