### ISSUE TITLE
Add over-exposure risk levels for additives from EFSA evaluations

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#1374]
EFSA publishes evaluations for additives, that are referenced in particular in the OpenFoodTox database:
https://www.efsa.europa.eu/en/data/chemical-hazards-data

This projet is to incorporate data from those evaluations inside the OFF additives taxonomy so that we can surface it in the web site and in mobile apps.

In particular, we are going to go through (i.e. read) all the evaluations so that we can extract structured data for the risk of over exposure (consumption of the additive or from other sources with the same chemical) for certain population groups.

Currently being discussed in the #additives channel on Slack.

**Comment by teolemon** [comment]
@stephanegigandet I guess we can close this one (
Add over-exposure risk levels for additives from EFSA evaluations
)
