### ISSUE TITLE
Product Opener always assigns product to Åland Islands

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#14]
Tacite: 
When I write "德国" (Germany) in "Countries where sold" on OFF China, it converts to "奥兰群岛" (Åland Islands), but if I write "Germany" it convert to "德国". Weird

>> In some cases, Product Opener will default to Åland Islands if the recognition is ineffective.

**Comment by kyzh** [comment]
Any non latin character gets transformed into Åland Islands apparently

**Comment by stephanegigandet** [comment]
Just tested, it is now working.
