### ISSUE TITLE
Add button to revert whole product to previous revision

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1405]
### What

- [ ] Add button to revert whole product to previous revision

![image](https://user-images.githubusercontent.com/1689815/46919051-a6e9e780-cfd9-11e8-971d-9adb389bdc56.png)
Useful when only the last edit is involved.

### Part of
- #5538

**Comment by alexgarel** [comment]
I would be in favor of keeping the history, that is act as a revert in git.

That is : keep the faulty edit, but add an edit on top of that to be back on.

**Comment by stephanegigandet** [comment]
Yes, that's definitely how it should work. In practice: just read the old revision, and then use Products::store_product() to write it again. (that would have the drawback of losing images uploaded in between, we could be a bit more clever and add uploaded images (but not selected images) from the current "images" field.

**Comment by CharlesNepote** [comment]
We could also do this on the client side with JS. We could do a first prototype with the Power User Script, with the following advantages:
* the JS functions to use the API (write) would be reusable for other needs or projects
* this feature would be reusable if we decide one day to change the language used for the backend
* it enforces us to better separate backend and frontend
* it enforces us to produce a better HTML code, with classes and ids to manipulate the document (style, dynamics, etc.)

**Comment by alexgarel** [comment]
I don't think it would be handy to do this in JS. In our current settings it will be hard to test, easy to break. For a function like this, you really make your life easier by going as much close as possible to the database (which are the `.sto`, here)

**Comment by CharlesNepote** [comment]
Ok, I understand.

**Comment by teolemon** [comment]
@CharlesNepote would you be able to come up with a gross estimate of the time this feature could save per week. I've put 100 min (50 reverts * 2 min)

**Comment by CharlesNepote** [comment]
100 min per week, at least, seems reasonable. Maybe there are fewer products to revert but I think it takes more time than you expect. What I can say is that there are ~5-10 vandalisms per week detected thanks  to Mirabelle and probably ~20-30 detected via the moderation Slack channel.

The worst part is that sometimes it's very difficult and/or long to revert manually.

The more we grow, the more we will have vandalism. I would say that this is a good P1 candidate.
