### ISSUE TITLE
Check EAN13 digit

### ISSUE THREAD

**Issue by TaciteOFF** [openfoodfacts/openfoodfacts-server#141]
In order to avoid wrong barcodes, we could display a warning message to users that fill a product page with a barcode whose digits don't respect the EAN structure.
More details : http://www.gomaro.ch/lecheck.htm

Formulas can be found here : https://en.wikipedia.org/wiki/International_Article_Number_(EAN)#Calculation

**Comment by itchix** [comment]
I can do the same for the android app :).  So we want to verify if it's EAN 13?

**Comment by TaciteOFF** [comment]
Yes. We could also trigger a warning when the barcode is 13 digits long and starts with 978/979 as these are reserved for books/magazines.

**Comment by itchix** [comment]
http://commons.apache.org/proper/commons-validator/apidocs/org/apache/commons/validator/routines/package-summary.html#other.checkdigit

```java
// EAN / UPC / ISBN-13 check digit validation
boolean valid = EAN13CheckDigit.INSTANCE.isValid(code);
```

I think I have to check by this way and after check if it's books/magazines

**Comment by stephanegigandet** [comment]
Invalid EAN-13 codes are now listed on http://world.openfoodfacts.org/code/invalid-ean
