### ISSUE TITLE
Quality facet - Nutrition - Check that quantity of nutrients/ingredients match legal product claims

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1414]
### What
- Check that quantity of sugar match legal product claims
  - if label= "A faible teneur en sucre"= en:Low sugar <5g/100g
  - if label= "Sans sucres" = en:No sugar <0,5g/100g
  - if label = "Sans sucres ajoutés" = en:No added sugar ingredients should not contain: "saccharose, lactose, glucose, fructose…" (according to Test Achats)
- Jams
  - https://informaciongastronomica.com/la-mermelada-mas-sana-del-mercado/ "EU law stipulates that jams sold must contain a minimum percentage of fruit of 35%, as a general rule."
### Part of
- #5538

**Comment by hangy** [comment]
- "A faible teneur en sucre" = en:Low sugar
- "Sans sucres" = en:No sugar
- "Sans sucres ajoutés" = en:No added sugar

**Comment by benbenben2** [comment]
Under Regulation (EU) 1924/2006 (EC 2006) for health and nutrition claims made on foods, the following sugars-related nutrition claims are permitted:

Sugar-free claims, 'may only be made where the product contains no more than 0,5 g of sugar per 100 g or 100 ml'.

With no added sugars claims 'may only be made where the product does not contain any added mono- or disaccharides or any other food used for its sweetening properties. If sugars are naturally present in the food, the following indication should also appear on the label: CONTAINS NATURALLY OCCURRING SUGARS'.

Low sugars claims 'may only be made where the product contains no more than 5g of sugar per 100 g for solids or 2,5 g of sugar per 100 ml for liquid'.

https://knowledge4policy.ec.europa.eu/health-promotion-knowledge-gateway/sugars-sweeteners_en

https://eur-lex.europa.eu/legal-content/en/ALL/?uri=CELEX%3A32006R1924
See annexe for all others "high fibers", "low fat" etc

**Comment by benbenben2** [comment]
For jams.

The quantity of pulp and/or purée used for the manufacture of 1 000 g of finished product must not be less than:                  
350 g | as a general rule,



https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32001L0113

**Comment by aleene** [comment]
I agree. Regulation kind of things can be added to the labels taxonomy.

**Comment by benbenben2** [comment]
1. Idea is to start with warning, review after few weeks and switch to error if everything is fine.
Because there are a lot of new warnings, if they produce many false positive and if it ends up in the dq daily emails that may not be a good experience for contributors receiving the dq daily emails.

2. In general, I am in favor of moving away from the code all these mappings that we have. I think it is a good idea but I can see following challenges by moving them to the taxonomy:
- if you put all countries. For EU, regulations, that is 27.... If tomorrow there is one country more (or less) in EU, we will have to update all tags. 
- it is not only max value... Take the first example (see annex of https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A02006R1924-20141213)
> A claim that a food is low in energy, and any claim likely to have the same meaning for the consumer, may only be made where the product does not contain more than 40 kcal (170 kJ)/100 g for solids or more than 20 kcal (80 kJ)/100 ml for liquids. For table-top sweeteners the limit of 4 kcal (17 kJ)/portion, with equivalent sweetening properties to 6 g of sucrose (approximately 1 teaspoon of sucrose), applies.

You have liquid vs solid
And some condition for specific categories.

**Comment by benbenben2** [comment]
2. For jams, it may be a little bit easier to put it in the taxonomy. That may be something like this:
```
en:jam
# minimal_amount_ingredients:en:fruits
minimal_amount_specific_ingredients:en:fruits
minimal_amount:en:350
minimal_amount_unit:en:g
minimal_amount_countries:en:eu
```
But if we have another country/region, how will we deal with it?
```
en:jam
# minimal_amount_ingredients:1,en:fruits;2,en:fruits
minimal_amount_specific_ingredients:1,en:fruits;2,en:fruits
minimal_amount:1,en:350;2,en:400
minimal_amount_unit:1,en:g;2,en:g;
minimal_amount_countries:1,en:eu;2,en:brazil
```
And then we parse on the numbers?

What we did in the past for 


I will implement it in the code for now. And once we clarify how to have it in the taxonomy and how it can be parsed
