### ISSUE TITLE
Pressing CTRL to select multiple pictures (product, ingredients, nutrition facts etc.) doesn't work

### ISSUE THREAD

**Issue by HummingBrid** [openfoodfacts/openfoodfacts-server#142]
(using firefox) only one picture can be selected at a time.

**Comment by stephanegigandet** [comment]
It works for me on Windows 7 with Firefox 38.0.5 and Chrome Version 43.0.2357.130 m when I upload pictures through the web site. (edit product page form)

Which version of Firefox are you using and on which platform? What happens when you select one image, then press Ctrl and click to second another image? The first one is deselected?

**Comment by HummingBrid** [comment]
Build identifier: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0
Yes, the first one is de-selected.

**Comment by stephanegigandet** [comment]
Probably related to the OS / File manager. There are a few threads here and there about that.
e.g. http://ubuntuforums.org/showthread.php?t=948257
Try "System -> Preferences -> Windows -> Movement Key -> CTRL was selected.
I changed it to the Windows key."
Maybe.
Can you select multiple files in some other ways? e.g. shift key, drag and drop to select etc. ?

**Comment by HummingBrid** [comment]
Interesting.
Looks like CTRL _is_ my key, because it works for files in the file manager an in all the file selection dialog boxes from firefox.
Other key combinations do not work as well.

**Comment by stephanegigandet** [comment]
We use <input type="file" multiple ...>

Does this test work for you?
http://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_multiple

**Comment by HummingBrid** [comment]
Yes

**Comment by hangy** [comment]
Closing, as this works in current Chrome and we have too many old open issues 😉. Please reopen if this still a problem for you.
