### ISSUE TITLE
Use localStorage to add suggestions for most recently added tags in the autocomplete box

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#1422]
We are currently using tagsInput for tags like categories, labels, brands etc.  
A few of those fields like categories also use jquery.autocomplete. This is feature request to also store locally with localStorage the most recent tag (or tags) added by the current user for each type of field so that they can be suggested when the user clicks on the input field but has not typed in characters yet.  (feature request also listed in #1401)

One way to do it may be to try to piggy back on jquery.autocomplete so that we retrieve suggestions from localstorage when users have not typed anything yet.

https://github.com/xoxco/jQuery-Tags-Input

http://api.jqueryui.com/autocomplete/

$('#brands').tagsInput({
--
  | 'height':'3rem',
  | 'width':'100%',
  | 'interactive':true,
  | 'minInputWidth':130,
  | 'delimiter': [','],
  | 'defaultText':"add a brand"
  | });
  | $('#categories').tagsInput({
  | 'height':'3rem',
  | 'width':'100%',
  | 'interactive':true,
  | 'minInputWidth':130,
  | 'delimiter': [','],
  | 'defaultText':"add a category",
  | 'autocomplete_url': 'https://world.openfoodfacts.org/cgi/suggest.pl?lc=en&tagtype=categories&'

**Comment by teolemon** [comment]
Chrome already stores those values automatically. Doesn't Firefox do something similar ?

**Comment by stephanegigandet** [comment]
We don't want the values for the whole field, we want individual tags. e.g. If I click on "add a category", on Chrome, I don't get anything:

![image](https://user-images.githubusercontent.com/8158668/47078141-e6dfe300-d202-11e8-9765-d8195c513149.png)

If I start to type 2 characters, I get the autocomplete suggestions:

![image](https://user-images.githubusercontent.com/8158668/47078010-96688580-d202-11e8-87ad-fbf1e4bbb0c6.png)

This new feature would show suggestions (1 or a few) with the last added tags, in the same way that we display autocomplete suggestions, but before having to type anything.

**Comment by stephanegigandet** [comment]
Would it be possible to:

Do not save the same suggestions more than once.
Do not suggest a tag that is already there.
?

![image](https://user-images.githubusercontent.com/8158668/58895774-075aa000-86f5-11e9-940b-97fac212efd6.png)

For the fields that do not have a taxonomy, suggest.pl won't return suggestions, but it seems that there is now a (broken) call to product.pl :

![image](https://user-images.githubusercontent.com/8158668/58895805-13def880-86f5-11e9-9e7b-84449ae026ea.png)

**Comment by CharlesNepote** [comment]
My feedbacks after a few days:
- it's very useful for some fields such as "labels" (especially when you add Nutri-Score or labels like that)
- it's not when you fill fields such as "category", but it might be if you enter many products of the same categories; for fields like "category", maybe it can be counter-productive because newbies should think they have to choose one of the suggestions. Maybe it's a functionnality made for experienced users.

I think we could have 5 suggestions instead of 3. It would be useful for a field like "labels". But we should test if it plays well with small screens.

**Comment by stephanegigandet** [comment]
Now in production, thank you very much @VaiTon !
