### ISSUE TITLE
Automatically clean ingredients lists that contain nutrition facts and other non ingredients text

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#1433]
Some apps like Yuka send us ingredients lists that are just results of OCR that includes non ingredients text.
This is an attempt to clean some of them, to at least remove what is clearly not part of the ingredients list.

**Comment by teolemon** [comment]
```Ingrédlents: ``` Typo of ingredients as an additional cutter

**Comment by stephanegigandet** [comment]
A first version has been deployed.
