### ISSUE TITLE
"Nutrition score - France" link to https://ru.openfoodfacts.org/nutrition-score-france is 404

### ISSUE THREAD

**Issue by aleksejrs** [openfoodfacts/openfoodfacts-server#1436]
https://ru.openfoodfacts.org/%D0%BF%D1%80%D0%BE%D0%B4%D1%83%D0%BA%D1%82/90384103/dancing-cow-pandispan-cu-umplutura-cu-lapte-gem-de-capsuni-si-invelis-cu-aroma-de-ciocolata

**Comment by CharlesNepote** [comment]
@teolemon fixed?
