### ISSUE TITLE
Avoid unnecessary translation work by removing language name from translations

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1443]
### What
Language name can be probably translated using https://perldoc.perl.org/Locale/Language.html
### Part of
- #5528

**Comment by hangy** [comment]
That Perl module seems to be insufficient, because it only supports English. We might be able to use [Locales](https://metacpan.org/pod/Locales#Language-Methods) though, as it's built on Unicode CLDR and should be more complete.
