### ISSUE TITLE
Unable to edit and error "Code manquant" when uploading a picture with barcode

### ISSUE THREAD

**Issue by HummingBrid** [openfoodfacts/openfoodfacts-server#145]
Tried to create a product using the attached barcode picture. Got to a an empty page (as if product in db already) and when tried to edit got an error: "Code manquant".
![almond_4](https://cloud.githubusercontent.com/assets/13072575/8504832/4502ee5c-21a6-11e5-8221-57dde574c4d8.jpg)

UPDATE:
Even after creating a new page for this product (http://world.openfoodfacts.org/product/063667090067/fortified-almond-beverage-natura#), I am still taken to the old empty page and not to the new one.

**Comment by stephanegigandet** [comment]
The barcode scanner sees the QR code instead of the barcode.. :-(
http://goo.gl/Pf2JsC

I'll try to disable the QR code recognition.

**Comment by stephanegigandet** [comment]
Fixed. https://bitbucket.org/openfoodfacts/product-opener/commits/f17df3f289e42fd6b9910b6d63a14c41ffb1053f

````
			# scan the image for barcodes
			my $n = $scanner->scan_image($image);
			# print STDERR "Images::scan_code - $n symbols found\n";

			# extract results
			foreach my $symbol ($image->get_symbols()) {

				$code = $symbol->get_data();
				my $type = $symbol->get_type();
				print STDERR "Images::scan_code - found code: $code - type: $type\n";
				if (($code !~ /^[0-9]+$/) or ($type eq 'QR-Code')) {
					$code = undef;
					next;
				}
				last;
			}
