### ISSUE TITLE
Optimize images for high definition display (2x) - labels logos

### ISSUE THREAD

**Issue by TaciteOFF** [openfoodfacts/openfoodfacts-server#146]
Some users, including me, could benefit from the image optimization.
Some scripts already exist: http://imulus.github.io/retinajs/

Not yet optimized:

Main logo:
<img width="304" alt="capture d ecran 2015-07-09 a 11 23 51" src="https://cloud.githubusercontent.com/assets/11161632/8592206/cf5d4b70-262d-11e5-8c59-e88c752842aa.png"> 
Label logos:
<img width="131" alt="capture d ecran 2015-07-09 a 11 25 22" src="https://cloud.githubusercontent.com/assets/11161632/8592207/cf5f0226-262d-11e5-8a96-b7926f57d993.png">
Product images on their product page:
<img width="262" alt="capture d ecran 2015-07-09 a 11 27 13" src="https://cloud.githubusercontent.com/assets/11161632/8592205/cf413520-262d-11e5-9cd6-5e06436984f2.png"> 
Mission images:
<img width="346" alt="capture d ecran 2015-07-09 a 11 24 40" src="https://cloud.githubusercontent.com/assets/11161632/8592209/cf5fda2a-262d-11e5-978b-27605eebed97.png"> 
App download logos:
<img width="198" alt="capture d ecran 2015-07-09 a 11 24 03" src="https://cloud.githubusercontent.com/assets/11161632/8592208/cf5fa046-262d-11e5-8163-7d719d8965bf.png">

Already optimized (product image on front page) :
<img width="411" alt="capture d ecran 2015-07-09 a 11 27 07" src="https://cloud.githubusercontent.com/assets/11161632/8592210/cf6052ac-262d-11e5-8133-13559be6a75c.png">

**Comment by stephanegigandet** [comment]
Thanks for the screenshots. The right solution is probably just the srcset in img tags, no need for retina.js or other scripts (I believe those were useful before the introduction and support of srcset). srcset is what is used on the product thumbnails in the front page.

**Comment by stephanegigandet** [comment]
Added 2x versions of the OFF logo + product images.

Missions need a big overhaul (not just images, but internationalization)

2x images for labels need to be created.

**Comment by hangy** [comment]
+A lot of label logos were vectorized by @fuddl.

**Comment by teolemon** [comment]
I'm closing this, based on the vectorization work we've done
