### ISSUE TITLE
Add quality facet for dehydratated products that are missing prepared values

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1466]
Add quality facet for dehydratated products that are missing prepared values

**Comment by teolemon** [comment]
This one is important because very popular products are dehydrated, and they need to be well completed.

**Comment by zigouras** [comment]
I can work on this one if you want to assign it to me.
Can someone show me in the UI where the quality facets are collected?  I assume they are stored in the `"quality_tags" : [ ]` array element of the product record.

**Comment by CharlesNepote** [comment]
Thanks @zigouras.

All quality facets can be found here: https://world.openfoodfacts.org/quality/

The script producing quality facets can be found here: https://github.com/openfoodfacts/openfoodfacts-server/blob/master/lib/ProductOpener/SiteQuality_off.pm

It's not very well documented but it should be understandable.

**Comment by teolemon** [comment]
The right category to use is probably "https://world.openfoodfacts.org/category/dried-products-to-be-rehydrated"

**Comment by zigouras** [comment]
How can I tell if a product is "missing prepared values"?

**Comment by zigouras** [comment]
I am ready to create a pull request for this from my fork I just need answers to the above questions.  Thanks.

**Comment by stephanegigandet** [comment]
Hi @zigouras, the "nutriments" hash contains the nutrition values, you need to check that we have values suffixed with "_prepared_100g". e.g. "energy_prepared_100g" should be there. You can have a look at this product for instance: https://world.openfoodfacts.org/api/v0/product/7613034897930/puree-maggi

It will be better than just checking the nutrition_data_prepared field.

"missing-nutrition-data-prepared-with-category-dried-products-to-be-rehydrated" sounds good to me.

**Comment by zigouras** [comment]
Here is my proposed pseudo-logic:
`if not checked nutrition_data_prepared
or
nutriments hash contains at least one key suffixed with _prepared_100g with a defined value > 0
then
add quality tag missing-nutrition-data-prepared-with-category-dried-products-to-be-rehydrated
end if
`
or do I specifically have to look for the nutriment key `energy_prepared_100g`?
Thanks.

**Comment by stephanegigandet** [comment]
Hi @zigouras, the proposed logic is good. If they are specifying nutriments per serving, we will compute the per 100g values (provided they also specified the serving size).

**Comment by stephanegigandet** [comment]
Fixed by @zigouras and deployed. Thank you!
