### ISSUE TITLE
Map FoodGES ingredients to the Ingredients taxonomy

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1469]
Stéphane Gigandet [8:56 PM]
@Victor: directement au niveau de l'ingrédient.

Avec ce format là :
```
<en:meat
en:pork meat
fr:viande de porc
carbon_footprint_fr_foodges_ingredient:fr Viande de porc
```
-> si l'ingrédient existe déjà dans la taxo, il faut juste rajouter le ```carbon_footprint_fr_foodges_ingredient:fr:Viande de porc```
et ensuite on ajoutera automatiquement les valeurs
-> s'il existe pas dans la taxo, il faut le rajouter
le mieux c'est de faire des pull requests sur https://github.com/openfoodfacts/openfoodfacts-server/blob/master/taxonomies/ingredients.txt

**Comment by teolemon** [comment]
Maxime L [9:26 PM]
et pour qu'on se marche pas dessus, je vous propose de suivre les différentes catégories avec ce googlesheet (qui est modifiable par tous normalement) : https://docs.google.com/spreadsheets/d/1fiRNdvwRLnkguYPtgVK56sqMDA5GK-Bi9zq0f9VSrtE/edit#gid=0

**Comment by stephanegigandet** [comment]
Thanks to @RonanMorgan , the FoodGES values are now in the ingredients taxonomy

**Comment by teolemon** [comment]
closing then @stephanegigandet
