### ISSUE TITLE
Load packaging codes for Sweden

### ISSUE THREAD

**Issue by MaximeLaurenty** [openfoodfacts/openfoodfacts-server#1477]
CSV file : https://www.dropbox.com/s/ldhaojv5lrcvn83/Sweden.csv?dl=0
Conversion to CSV destroys a lot of characters in swedish.
xlsx file in case someone knows how to improve this : 
https://www.dropbox.com/s/4t0p8xp94zg2ihh/Sweden.xlsx?dl=0

### Part of 
- #338

**Comment by MaximeLaurenty** [comment]
@teolemon I don't see how to add labels to this ("packaging codes" code), does it require special rights ?

**Comment by hangy** [comment]
Yes, adding tags to issues requires additional permission.

**Comment by benbenben2** [comment]
@teolemon 
This seems to be done already for Sweden (https://se.openfoodfacts.org/packager-code/se-1031-ec).

Should we close this issue?

**Comment by teolemon** [comment]
Let's close. thanks @benbenben2
