### ISSUE TITLE
Bug changing the bar code

### ISSUE THREAD

**Issue by javichuOFF** [openfoodfacts/openfoodfacts-server#148]
This bug happens when you change your product bar code "A" by another "B", and after that, you want to reuse the initial bar code "A".

This use case could seem a little forced at first, but it occurred to me several times. Basically, it happens easily (to me) adding similar products (or when you have several images from different products in the same directory) and you add the wrong code bar for a product that belongs to another. Then you try to fix it and finally you mess everything :-)

Steps to reproduce it:

1) You add a product "1" with a bar code "A". After filling all tha data you realize that the bar code added was wrong and it really belonged to another product. So, you change your bar code to "B". At this point all the data is moved from the product with bar code "A" to the new one with bar code "B" but not the images. This problem is already reported in the related bug ticket:

*  Images disapear after changing the bar code - https://github.com/openfoodfacts/openfoodfacts-server/issues/35

2) At this point, a "ghost" product with the bar code "A" persist in the database and in some way is linked with the product with the bar code "B". Now, you want to use the "ghost" product with the bar code "A" for a real product "2". So, you add the new images, all the data and so on, but this is what we get:

2.1) The product doesn't show up searching for it, unless you search explicitely by the bar code "A" 

2.2) The product doesn't appear as part of any label, brand, origin, packager code ...

The product is in the limbo!!!

Cases:

1) This has happened recently:
http://es.openfoodfacts.org/producto/24039758/  <<--- the product with the bar code changed. This is OK
http://es.openfoodfacts.org/producto/24015516/  <<--- ghost !!

2) This is from a mess from 3 different products. In this case, I don't have the "ghost" product with me, so I don't know the code bar and I am not able to find the product. But I know is there!! ;) . Maybe it can be found (linked) throught one of these:

* http://es.openfoodfacts.org/producto/20499464/
* http://es.openfoodfacts.org/producto/20499457/

3) There is at least one more case that I can't remember now. I will add it later if I can found it.

**Comment by stephanegigandet** [comment]
Hi Javichu,
I tried to reproduce this bug, it seems to be now working.
Do you still have issues with changing barcodes? If so please re-open the bug.
Thanks,
Stephane
