### ISSUE TITLE
Update legal to reflect hosting changes

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1482]
The site is hosted on dedicated servers rented from OVH SAS (address: 2 rue Kellermann 59100 Roubaix - France).

**Comment by CloCkWeRX** [comment]
https://fr.openfoodfacts.org/mentions-legales seems to have the right detail; did you mean a different URL?

**Comment by teolemon** [comment]
https://github.com/openfoodfacts/openfoodfacts-server/pull/2847/files
