### ISSUE TITLE
Adding rH2 in Nutrition facts doesn't work - Error: Attempt to access disallowed key 'rh2' in a restricted hash

### ISSUE THREAD

**Issue by astrubel** [openfoodfacts/openfoodfacts-server#149]
Product : http://fr.openfoodfacts.org/produit/3257971082512/
Error : Attempt to access disallowed key 'rh2' in a restricted hash at /home/off-fr/cgi/product.pl line 428.

**Comment by stephanegigandet** [comment]
Now it seems to be working, but the "Attempt to access disallowed key" may be a transient error...

**Comment by teolemon** [comment]
closing ?

**Comment by hangy** [comment]
Closing, because not updated in some years. Probably outdated.
