### ISSUE TITLE
repeated lang prefix in category taxonomy

### ISSUE THREAD

**Issue by rndblnch** [openfoodfacts/openfoodfacts-server#1537]
https://github.com/openfoodfacts/openfoodfacts-server/blob/e4ed55419d5bb93bf3ac298dc061892552d02a85/taxonomies/categories.txt#L28514

The name of the parent category repeats the lang tag, which cause the category hanging out the taxonomy.
see missing "Belongs to" information on:
https://world.openfoodfacts.org/category/fr:sauces-armoricaines

**Comment by rndblnch** [comment]
and a second one here:

https://github.com/openfoodfacts/openfoodfacts-server/blob/e4ed55419d5bb93bf3ac298dc061892552d02a85/taxonomies/categories.txt#L16779

see empty lement in the "Belongs to" informatione here:
https://world.openfoodfacts.org/category/chocolate-powders

**Comment by teolemon** [comment]
Corrected on the Wiki

**Comment by stephanegigandet** [comment]
This has been fixed a while back.
