### ISSUE TITLE
malformed line in categories taxonomy

### ISSUE THREAD

**Issue by rndblnch** [openfoodfacts/openfoodfacts-server#1540]
the line is splitted:

https://github.com/openfoodfacts/openfoodfacts-server/blob/e4ed55419d5bb93bf3ac298dc061892552d02a85/taxonomies/categories.txt#L3616-L3617

**Comment by stephanegigandet** [comment]
Fixed in github: https://github.com/openfoodfacts/openfoodfacts-server/blob/master/taxonomies/categories.txt#L3987
