### ISSUE TITLE
malformed line in categories taxonomy

### ISSUE THREAD

**Issue by rndblnch** [openfoodfacts/openfoodfacts-server#1541]
the line has 2 language tags in it:

https://github.com/openfoodfacts/openfoodfacts-server/blob/e4ed55419d5bb93bf3ac298dc061892552d02a85/taxonomies/categories.txt#L30055

**Comment by stephanegigandet** [comment]
> so, is the wiki the primary source for the taxonomies ?

Currently yes. We may move it to github directly as it is becoming very large and the wiki has trouble to handle it.

**Comment by stephanegigandet** [comment]
@rndblnch : we are now maintaining the taxonomies directly in github

Fixed.
