### ISSUE TITLE
The Android app shouldn't let the user scan QR Codes

### ISSUE THREAD

**Issue by astrubel** [openfoodfacts/openfoodfacts-server#157]
I don't remember if I scanned a QRCode for this product:
http://fr.openfoodfacts.org/produit/http://qr.nestle.fr/atelier1

**Comment by teolemon** [comment]
Are there any cases where the QR code is the sole identifier ? How should we handle those ?

**Comment by astrubel** [comment]
If moodstock is still used for barcode detection, it was possible to disable QRCode for detection.
This issue appears on a product with both barcode and QRCode. I never see product with a QRCode used for the identification.

**Comment by hangy** [comment]
Which app is this about? Should this issue possibly be migrated to one of these?

- https://github.com/openfoodfacts/OpenFoodFacts-androidApp
- https://github.com/openfoodfacts/cordova-app
- https://github.com/openfoodfacts/openfoodfacts-android
- https://github.com/openfoodfacts/openfoodfacts-moodstocks
- https://github.com/openfoodfacts/www

**Comment by teolemon** [comment]
My take is that it might happen through the Web UI addition system ?

**Comment by hangy** [comment]
Well, the issue's title says it's about an Android app, but yes, [ZBar could be reading QR Codes, too](http://oylenshpeegul.typepad.com/blog/2012/01/reading-qr-codes-in-perl.html). I guess we could just check for EAN-13/UPC-A, UPC-E, EAN-8 type after reading the barcode. On the other hand, more validation when creating a product from a barcode via the API might be useful, too.

**Comment by hangy** [comment]
I'm closing this, because it's mostly out of date with [the new app](https://github.com/openfoodfacts/openfoodfacts-androidapp) being published.
