### ISSUE TITLE
Dataset shouldn't contain specials chars between \000-\007 and \013-\037

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#1585]
**Summary:**

Chars between \000-\007 and \013-\037 decimal codes are not used anymore -- they come from the old times where they were useful to control printers and so on. They break the CSV file which can't be processed by common tools such as csvkit.

**Steps to reproduce:**

A file listing every line containing bad chars can be produced with a simple command line (see [bad-chars.txt](https://github.com/openfoodfacts/openfoodfacts-server/files/2698784/bad-chars.txt)):
```
$ perl -ne 'print if /[\000-\007\013-\037]/' fr.openfoodfacts.org.products.csv > bad-chars.csv
```

**Expected behavior:**

Every data entered in the database should be controlled.

**Comment by teolemon** [comment]
https://world.openfoodfacts.org/api/v0/product/7290000170077.json

**Comment by teolemon** [comment]
Related to Veganeamos data entry. Contacted the creator of the app to fix that upstream. Alternatively, we could selectively fix their API calls
