### ISSUE TITLE
Add special detection for Peut contenir des restes de ***

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1599]
"Peut contenir des restes de noyaux" was truncated by the automatic cutter. This is probably an interesting information to extract

**Comment by stephanegigandet** [comment]
The ingredient list cut algorithm tries to keep only the ingredients, and it does not try to extract other data from the text blob that is next to the ingredient list. Extracting preparation data, warnings etc. is more a job for another process like Robotoff.
