### ISSUE TITLE
We should have page for packager codes even if we don't have any products yet for them

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#16]
We should have page for packager codes even if we don't have any products yet for them. That way people will discover the page when they're looking for it, have minimal info, and get the opportunity to add the product to the base.

We should have a text saying "Oooh :-( No product yet. Download the app and add your product."

**Comment by teolemon** [comment]
- adding a map
- adding clickable EU sections (http://en.wiki.openfoodfacts.org/Global_EC_marks_taxonomy)
- Adding Product address ? Phone numbers ? Fax ? SIRET ?
- Adding clickable territorial subdivisions

**Comment by fuddl** [comment]
http://codepen.io/Fuddle/pen/akXQyk

**Comment by hangy** [comment]
The map is actually displayed, if there is no product: https://web.archive.org/web/20181230115646/https://world.openfoodfacts.org/packager-code/de-by-10227-ec

**Comment by hangy** [comment]
I'm closing this, because the page does exist for packager-codes without barcodes. The improvements to the page are already being tracked in #337.
