### ISSUE TITLE
Filtering with the `fields` field does not work if commas are url-encoded

### ISSUE THREAD

**Issue by raphael0202** [openfoodfacts/openfoodfacts-server#1607]
**Checklist:**

* [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-server/issues) before creating or reporting a issue.

* [ ] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.

**Summary:**

Using the GET product API:
`curl 'https://world.openfoodfacts.org/api/v0/product/84352996.json?fields=image_front_url,code,categories_tags,brands,product_name'` works as expected, returning only the requested fields.

However, `,` is a reserved character (https://tools.ietf.org/html/rfc3986#section-2.2), so the correct URL is:
`https://world.openfoodfacts.org/api/v0/product/84352996.json?fields=image_front_url%2Ccode%2Ccategories_tags%2Cbrands%2Cproduct_name`
With the quoted version, no fields are returned:
`{"status":1,"status_verbose":"product found","product":{},"code":"84352996"}`

**Comment by hangy** [comment]
I think that's OK, as long as we define it that way. 😀

https://stackoverflow.com/a/2375597/11963
> The HTTP scheme doesn't use the comma or semi-colon as a delimiter in query strings, so they don't need to be escaped.

https://webmasters.stackexchange.com/a/109127/4212
> Neither the URI standard¹ nor the HTTP/HTTPS URI scheme specs define a special role for , in the query component. This means that authors may use , to represent data in the query component (i.e., for whatever they want).

**Comment by stephanegigandet** [comment]
It does not cost much to add support for %2C in addition to the comma, I'll do it.
