### ISSUE TITLE
Improve aggregations performance

### ISSUE THREAD

**Issue by syl10100** [openfoodfacts/openfoodfacts-server#1610]
**Summary:**
Aggregations can take a while, especially when none country is selected (e.g. https://world.openfoodfacts.org/labels )

**Steps to reproduce:**
Go to this URL https://fr-en.openfoodfacts.org/labels
It will execute in Mongodb :
```
db.products.aggregate( [
{"$match" : {countries_tags : "en:france"}},
{"$unwind" : "$labels_tags"},
{"$group" : {_id : "$labels_tags",count : {"$sum" : 1}}},
{"$sort" : {count : -1}}
])
```

**Proposition:**

For aggregation queries, we can assume that real-time is not mandatory. I propose to 
create a copy of products collection with only tags fields used in aggregation. This will allow to have a collection with smaller documents. And fetching small documents is faster.  
This new collection should be refreshed every night.

The following mongo shell command will copy in a collection called «**products_tags**» all tags field
used in drilldown menu.

```
db.products.aggregate( [
{"$project" : 
{
countries_tags:1,
brands_tags:1, 
categories_tags:1, 
labels_tags:1, 
packaging_tags:1, 
origins_tags:1, 
manufacturing_places_tags:1,
emb_codes_tags:1, 
ingredients_tags:1,
additives_tags:1,
vitamins_tags:1,
minerals_tags:1,
amino_acids_tags:1,
nucleotides_tags:1,
allergens_tags:1,
traces_tags:1,
nova_groups_tags:1,
nutrition_grades_tags:1,
languages_tags:1,
creator_tags:1,
editors_tags:1, 
states_tags:1,
entry_dates_tags:1,
last_edit_dates_tags:1,
codes_tags:1
}},
{"$out": "products_tags"}
])
```

All aggregate commands will run on products_tags collection instead of products collection.

**Comment by stephanegigandet** [comment]
I'm testing it on my test server (world.openfoodfacts.net) which has an old mongodb:

tail -f refresh_products_tags.log
MongoDB shell version: 2.6.6
connecting to: off
Thu Jan 31 2019 16:56:30 GMT+0100 (CET) : Refresh products_tags collection...
2019-01-31T16:57:14.528+0100 TypeError: Property 'estimatedDocumentCount' of object off.products_tags is not a function at refresh_products_tags.js:43
failed to load: refresh_products_tags.js

In production we have mongo 4.0.2, and it seems db.collection.estimatedDocumentCount() is new in 4.0.3.

I'm just going to use count() on my old server.

**Comment by syl10100** [comment]
I don't think that estimatedDocumentCount is part of this pull request

**Comment by stephanegigandet** [comment]
It's just a print in the refresh_products_tags script, no problem.

The refresh is very fast, about 1 minute on my test server with a DB with 400k products.

**Comment by syl10100** [comment]
> 
> 
> It's just a print in the refresh_products_tags script, no problem.
> 
Yes, my bad.

**Comment by stephanegigandet** [comment]
Deployed in production!

**Comment by syl10100** [comment]
> 
> 
> @syl10100 : is there a specific reason why there isn't an index for each of the fields?

Actually, index are usefull only for "two-level" aggregation.
I mean :
https://world.openfoodfacts.org/categorie/  -> none index can be used
https://fr.openfoodfacts.org/categorie/  -> uses index on "countries_tags"
https://fr.openfoodfacts.org/categorie/boissons/marques -> uses index on "categories_tags" (ie. filter products where categorie="boissons")

So, if you think that some fields are used on two-level aggregation, then yes, we should create index for these fields.

**Comment by stephanegigandet** [comment]
This has been deployed, closing the bug. Thank you very much @syl10100 !
