### ISSUE TITLE
Changes to French PNNS groups for beverages

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#1611]
As asked from the EREN team, add some new PNNS groups 2 for beverages:

"Artificially sweetened beverages" => "Beverages",
"Unsweetened beverages" => "Beverages",
"Sweetened beverages" => "Beverages",
"Fruit juices" => "Beverages",
"Fruit nectars" => "Beverages",
"Waters and flavored waters" => "Beverages",
"Teas and herbal teas and coffees" => "Beverages",

Remove the coffees and teas that are not actual drinks (e.g. tea bags) from the Beverages.

For Waters and Teas, "Sweetened beverages" and "Artificially sweetened beverages" take precedence (waters and teas should only be unsweetened).

**Comment by teolemon** [comment]
Assuming we can close ?

**Comment by stephanegigandet** [comment]
Closing.
