### ISSUE TITLE
Instead of the selected user, my login name will appear in the link

### ISSUE THREAD

**Issue by hunsly** [openfoodfacts/openfoodfacts-server#1613]
**Summary:**

Bad  "Products edited by" link URL. Instead of the selected user, my login name will appear in the link.

**Steps to reproduce:**

1.  check this site: https://world.openfoodfacts.org/contributor/kiliweb
2.  click on the "Products edited by Yuka" link

**Expected behavior:**

URL: https://world.openfoodfacts.org/editor/kiliweb

**Observed behavior:**

https://world.openfoodfacts.org/editor/my_login_name

**Comment by hunsly** [comment]
Tips: https://github.com/openfoodfacts/openfoodfacts-server/blob/bd0e379ba2e9922cc0adfa021fab98b1209c0fbc/lib/ProductOpener/Display.pm#L2854
$User_id instead of $tagid?

**Comment by CharlesNepote** [comment]
Plutôt cette ligne je pense :
https://github.com/openfoodfacts/openfoodfacts-server/blob/bd0e379ba2e9922cc0adfa021fab98b1209c0fbc/lib/ProductOpener/Display.pm#L2839

Je ne peux corriger car je ne parviens pas à reproduire en test...

**Comment by CharlesNepote** [comment]
Corrected and tested. It should be ok. Thanks for the bug report @hunsly.

**Comment by stephanegigandet** [comment]
Deployed, thank you!
