### ISSUE TITLE
Can't delete empty product listed in the Chilean homepage.

### ISSUE THREAD

**Issue by rampmaster** [openfoodfacts/openfoodfacts-server#162]
The product http://cl.openfoodfacts.org/producto/2000000018593 in Chilean Frontpage but to access not exist

**Comment by teolemon** [comment]
I tried to delete it but it won't disappear…

**Comment by teolemon** [comment]
@stephanegigandet can you reproduce ?

**Comment by hangy** [comment]
I can't edit this product at all.
