### ISSUE TITLE
Make fields documentation published on github repo

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#1626]
**Summary**

Fields documentation isn't published on github repo (thus it's impossible to make it better). I speak about
https://world.openfoodfacts.org/data/data-fields.txt

**TODO**

- [ ] Find a place for the file:  `/html/data/data-fields.txt` ?
- [ ] Change links in `/lang/xx/texts/data.en.html`

**Comment by hangy** [comment]
> Find a place for the file: `/html/data/data-fields.txt`

I suggest `/Lang/en/texts/data-fields.html`. In this location, it could be displayed on the OFF website without breaking the layout by linking to a plain text file. The description could then also be eglible for translation thorough crowdin.

**Comment by stephanegigandet** [comment]
/lang/en/texts/data-fields.html is a good idea.

**Comment by CharlesNepote** [comment]
Fine!

I will do a first html version without modification of the content. And then I will suggest progressive modifications.

**Comment by vanshikaarora** [comment]
Hey @CharlesNepote are you still working on this Issue, if not then shall I take this up?

**Comment by VaiTon** [comment]
@vanshikaarora sure you can!

**Comment by teolemon** [comment]
fixed in the repo /html/data/data-fields.txt
