### ISSUE TITLE
Link to "products to be completed"

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#1629]
Wrong link at https://world.openfoodfacts.org/products:
* "product pages to be completed" links to https://world.openfoodfacts.org/status/to-be-completed => Error
* The right link is: https://world.openfoodfacts.org/state/to-be-completed/

**Comment by adzshaf** [comment]
Hi! Can I work on this issue? @CharlesNepote

**Comment by CharlesNepote** [comment]
@adzshaf yes sure! It's a good start, welcome!

**Comment by adzshaf** [comment]
just to clarify, since the page that I need to fix has many translations, it means that I need to fix the broken link for every translation page, right? Thank you! @CharlesNepote
