### ISSUE TITLE
Error in icon loading

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1636]
2019/02/01 13:43:51 [error] 233670#233670: *13458305 open() "/srv/off/html/apple-touch-icon-precomposed.png" failed (2: No such file or directory), client: 90.24.177.24, server: openfoodfacts.org, request: "GET /apple-touch-icon-precomposed.png HTTP/1.1", host: "fr.openfoodfacts.org"
2019/02/01 13:43:51 [error] 233670#233670: *13458305 open() "/srv/off/html/apple-touch-icon.png" failed (2: No such file or directory), client: 90.24.177.24, server: openfoodfacts.org, request: "GET /apple-touch-icon.png HTTP/1.1", host: "fr.openfoodfacts.org"
2019/02/01 13:43:52 [error] 233670#233670: *13458305 open() "/srv/off/html/apple-touch-icon-precomposed.png" failed (2: No such file or directory), client: 90.24.177.24, server: openfoodfacts.org, request: "GET /apple-touch-icon-precomposed.png HTTP/1.1", host: "fr.openfoodfacts.org"
2019/02/01 13:43:52 [error] 233670#233670: *13458305 open() "/srv/off/html/apple-touch-icon.png" failed (2: No such file or directory), client: 90.24.177.24, server: openfoodfacts.org, request: "GET /apple-touch-icon.png HTTP/1.1", host: "fr.openfoodfacts.org"

**Comment by hangy** [comment]
That seems to be a browser pinging for URLs that we've never referenced. The [manifest](https://world.openfoodfacts.org/cgi/manifest.pl) references existing Apple Touch icons.
