### ISSUE TITLE
Rename the "Cloud Vision" button in "Extract the ingredients from the picture"

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1647]
I got a feedback the other day that the OCR was rubbish on the web. The person didn't use the "Cloud Vision" button, because the classic OCR button was more explicit ("Extract the ingredients from the picture").

So let's remove the old OCR and turn Cloud Vision in "Extract the ingredients from the picture"

**Comment by stephanegigandet** [comment]
This has been done in production.
