### ISSUE TITLE
Corrections on the ingredients extracted from the image are lost under specific conditions

### ISSUE THREAD

**Issue by lucaa** [openfoodfacts/openfoodfacts-server#165]
How to reproduce:
* open a product page, with an ingredients image already selected
* modify the ingredients list (without clicking on "extract from image")
* click on the image with ingredients
* click on an empty box in the nutrients form
* hit the Enter key

Expected result: form should be submitted with the modified ingredients list
Actual result: the text is extracted from the image of the ingredients and replaces the modified ingredients. Page is not reloaded.

Reproduced on Google Chrome on Ubuntu. 
There might be easier steps to reproduce, but this is what I managed to do so far.

**Comment by lucaa** [comment]
A pull request that fixes this issue was made.

**Comment by stephanegigandet** [comment]
Fixed by @lucaa (Thank you!) and deployed to production.
