### ISSUE TITLE
Compute and display carbon footprint from meat using ingredients list and FoodGES

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#1651]
Create a new carbon_footprint_from_meat value in the nutrient table (similar to the carbon_footprint field).

The value is only computed when we have at least 1 ingredient with a known % that is a child of beef/chicken/pork/turkey meat in the ingredients taxonomy. CO2 values for those come from the Ademe FoodGES database.

Display the value below the nutrient table (similar to the carbon footprint field).

Also compute the environment_infocard field to display in the mobile app:

````
<h2>Carbon impact</h2>
<b>4,9 kg</b> of carbon emission from beef for the whole product  (xx kg for a portion)<br>
<b>91%</b> of the sustainable daily emissions of 1 person (xx % for a portion)<br>
<b>xx%</b> of the sustainable weekly emissions of 1 person (xx % for a portion)<br>
<br>

<h2>Methodology :</h2><br>
- all carbon emissions computation rely on the CO<sub>2</sub> per kg values from the FoodGES program by ADEME (www.ademe.fr)<br><br>

- sustainable annual emissions : 2 tons of CO<sub>2</sub> equivalent per person to achieve goals set in COP21<br><br>

- all carbon footprint calculations have high uncertainty. Values should be looked at with caution and are more intended for relative comparison rather than as absolute values.<br><br>

**Comment by stephanegigandet** [comment]
I have not found a reliable source for the 2 tons of carbon per person per year, we need to identify one. cc @teolemon @CharlesNepote

**Comment by CharlesNepote** [comment]
Seen here but without source: https://timeforchange.org/CO2-emissions-by-country

Also here: https://www.proyectomirador.org/stove-benefits/mirador-stoves-can-reduce-your-greenhouse-gas-emissions

It seems to be well known but without "official" references.

**Comment by stephanegigandet** [comment]
This has been deployed, and @RonanMorgan has extended it for all FoodGES entry (not only meat and fish).
