### ISSUE TITLE
JSON API - fr subdomain but categories data in english

### ISSUE THREAD

**Issue by FabienZE** [openfoodfacts/openfoodfacts-server#166]
When requesting fr subdomain (per example : http://fr.openfoodfacts.org/api/v0/product/3165432640006.json), response shows english categories instead of french categories

**Comment by VaiTon** [comment]
I think this has been fixed. @teolemon @stephanegigandet

**Comment by stephanegigandet** [comment]
The subdomain currently has no effect on the values returned, and it never has.
