### ISSUE TITLE
Image colors shown as negative of the uploaded image when resized

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#1663]
A very strange bug, a specific jpg image has its colors completely messed up after upload to OFF, when it is resized by OFF.

![karma-kombucha-citron-fr](https://user-images.githubusercontent.com/8158668/52710609-078d2f00-2f90-11e9-958f-0bb6105b9492.jpg)

Turns into:

![image](https://user-images.githubusercontent.com/8158668/52710678-3c00eb00-2f90-11e9-935a-fe2e507c206f.png)

**Comment by teolemon** [comment]
Bad karma.

**Comment by stephanegigandet** [comment]
It seems to be a bug when the JPG has the CMYK color profile instead of RGB. What's weird is that the old version of imagemagick / perlmagick on the old server does not have this issue.

**Comment by stephanegigandet** [comment]
Probably due to this:

The behaviour of Set(colorspace) has changed:
https://www.imagemagick.org/discourse-server/viewtopic.php?p=143122#p143122
$magick->Set(colorspace => 'sRGB');

**Comment by stephanegigandet** [comment]
Fixed.
