### ISSUE TITLE
Hunger Games doesn't work on initial load from the app

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1688]
Hunger Games doesn't work on initial load from the app. A refresh makes it work.

**Comment by VaiTon** [comment]
I don't think this issue belong to this repo lol @teolemon

**Comment by teolemon** [comment]
Hunger Games is integrated within the production deployment of Product Opener, so that's why I opened it here. 
It has been fixed, so closing. Thanks @VaiTon :-)
