### ISSUE TITLE
New nutrition_table_html field that can be requested through the API

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#1692]
Add a nutrition_table_html field that can be requested through fields= in the API.
The language of the nutrients can be set through the lc code.

The query will look like this:
https://world.openfoodfacts.org/api/v0/produit/3222471975336?fields=product_name,nutrition_table_html&lc=fr

**Comment by hangy** [comment]
Wouldn't it be better to provide this at a separate endpoint? It seems like pretty bad practice to mix designed markup and JSON in a single endpoint ... Just provide it at a separate endpoint as a full HTML document, so that it can be embedded in an `iframe`. This isn't really good API design, I think.

**Comment by stephanegigandet** [comment]
@hangy : this is needed for the iOS app, that just needs the nutrition table as HTML, and the other fields as strings etc. Being able to do this in only one API call is better for both app users (faster loading), and for the server load (halves the number of mod_perl requests to the server).

**Comment by stephanegigandet** [comment]
Bug is related to https://github.com/openfoodfacts/openfoodfacts-ios/issues/241

**Comment by hangy** [comment]
We really shouldn't mix a product-specific API with a general one, though. If only some apps require (or can even use) the pre-defined HTML, then that should be a separate REST resource IMO. If you fear that this could be too slow on client-side, then HTTP2 should be a viable option. In the case that too many mod_perl requests are an issue, you could add an additional REST endpoint that wraps the other two subs. Why not just return the nutrient data as structured JSON and let the client decide about the presentation issue? That's an approach that works for all clients, not just ones that know how to parse/display HTML. I really don't understand the use case.

**Comment by stephanegigandet** [comment]
I wasn't clear about the context: we are racing around the clock to release a new version of the iOS app as soon as possible, as OFF will be featured on French TV. Coding the display of the nutrition table in iOS based on the already available nutrient data in JSON requires too much time, but it's very easy to display an HTML table, so the iOS developer asked for one. So this is a quick and dirty hack, that we will remove once we have a proper display of the nutrition table in iOS.

**Comment by hangy** [comment]
> So this is a quick and dirty hack, that we will remove once we have a proper display of the nutrition table in iOS.

Disregarding the French TV or iOS (both I know little to nothing about), that's kind of my point. Once such an API has been provided at that URL, it can turn out to be difficult to remove.
