### ISSUE TITLE
Allow passing an ordered list of preferred languages for returning language specific fields in the API

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#1693]
With the fields= parameter, it's possible to request only specific fields in the API. For language specific fields (ingredients_text, product_name etc.) apps can request a specific variant (ingredients_text_fr) or receive the value for the main language of the product (using just ingredients_text).

This feature is to allow passing one or more languages in the lc= field so that language specific fields return values in the preferred languages if they are available.

Sample query:

https://world.openfoodfacts.org/api/v0/product/5411188115533?fields=ingredients_text,ingredients_text_de,ingredients_text_it,ingredients_text_fr,ingredients_text_nl&lc=ja,nl,de,fr,it,es

-> ingredients_text will be equal to ingredients_text_de (the first matching language) instead of ingredient_text_fr (the main language of the product)

This solves part of bug #270 (language specific fields, but not yet taxonomies and images)

**Comment by hangy** [comment]
Why don't we discuss stuff like this first? I would definitely vote to support the standard `Accept-Language` header instead.
