### ISSUE TITLE
CSV export is not sent gziped

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#1697]
The [CSV file](https://static.openfoodfacts.org/data/en.openfoodfacts.org.products.csv) is not sent gziped while HTML files are. This is anoying as file transfert is during more than 30 minutes in my case. Gzip would probably cut this time by half or more.
```
$ curl -I -H 'Accept-Encoding: gzip,deflate' https://static.openfoodfacts.org/data/en.openfoodfacts.org.products.csv
HTTP/2 200 
server: nginx/1.10.3
date: Sat, 09 Mar 2019 09:55:26 GMT
content-type: application/octet-stream
content-length: 2180399176
last-modified: Sat, 09 Mar 2019 03:16:23 GMT
etag: "5c833007-81f64048"
strict-transport-security: max-age=63072000
x-frame-options: DENY
x-content-type-options: nosniff
accept-ranges: bytes

$ curl -I -H 'Accept-Encoding: gzip,deflate' https://world.openfoodfacts.org/data
HTTP/2 200 
server: nginx/1.10.3
date: Sat, 09 Mar 2019 09:55:01 GMT
content-type: text/html; charset=UTF-8
content-length: 10354
expires: Fri, 08 Mar 2019 09:55:01 GMT
set-cookie: b=82.66.168.200_1552125301; path=/; expires=Fri, 03-Dec-2021 09:55:01 GMT
x-frame-options: DENY
x-content-type-options: nosniff
x-download-options: noopen
x-xss-protection: 1; mode=block
x-request-id: sekRna1FjaIBotsB
vary: Accept-Encoding
content-encoding: gzip
strict-transport-security: max-age=63072000
x-frame-options: DENY
x-content-type-options: nosniff
```

Here is a resource about it: https://derekswingley.com/2016/11/06/make-nginx-gzip-more-than-json/

**Comment by hangy** [comment]
> This is anoying as file transfert is during more than 30 minutes in my case.

I just downloaded it in 3-4 minutes. 😮 But I totally agree that the response should be gzipped. 👍

Maybe the export should be gzipped in the cron script, so that [`gzip_static`](http://nginx.org/en/docs/http/ngx_http_gzip_static_module.html) can be used for the data directory, and nginx doesn't have to gzip on every request?

**Comment by stephanegigandet** [comment]
The issue with gzip_static is that it's not available in the nginx debian packets, we would need to compile it, which we can do of course, but it makes things less easy to set up. We could at least provide a link to the gzipped version.

**Comment by hangy** [comment]
> The issue with gzip_static is that it's not available in the nginx debian packets, we would need to compile it, which we can do of course, but it makes things less easy to set up.

Agreed. That's not a good idea unless we had someone that regularly checked for nginx/glibc CVSs.

**Comment by CharlesNepote** [comment]
@hangy you have a very efficient broadband connection!

I agree with both of you for gzip_static. And disagree to create a .gz version of the files as users need more operations and knowledge to use the .gz file (untar.gz, wait for it, delete the gz version and so on). Straight CSV file download is a good thing and lowers the barrier to usage.

Why not use on the fly gzip compression as used for HTML files, as suggests [this article](https://derekswingley.com/2016/11/06/make-nginx-gzip-more-than-json/)?

**Comment by stephanegigandet** [comment]
Done:

curl -I -H 'Accept-Encoding: gzip,deflate' https://static.openfoodfacts.org/data/en.openfoodfacts.org.products.csv
HTTP/1.1 200 OK
Server: nginx/1.10.3
Date: Sat, 09 Mar 2019 11:27:11 GMT
Content-Type: text/csv
Last-Modified: Sat, 09 Mar 2019 03:16:23 GMT
Connection: keep-alive
ETag: W/"5c833007-81f64048"
Strict-Transport-Security: max-age=63072000
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
Content-Encoding: gzip

Downsides:
- it consumes resources on the server side for every download
- there's no Content-Length anymore, so the client does not know how big it is and what % is done.

**Comment by stephanegigandet** [comment]
I guess we could add the .gz link too.
