### ISSUE TITLE
Set up CRON for offline export

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1698]
Set up CRON for offline export

**Comment by hangy** [comment]
> Set up CRON for offline export

Offline export of what? There already is https://github.com/openfoodfacts/openfoodfacts-server/blob/683fc4f739b91eab3d81f8edb2d6fdf9636c3c0e/scripts/gen_feeds_daily_off.sh#L1-L14
Or is this about adding the crontab to GitHub, as requested in #1673?

**Comment by stephanegigandet** [comment]
I think it's the offline database for the app. @teolemon : where is the code that generates that export?

**Comment by teolemon** [comment]
/home/teolemon/offline/generate_dump_for_offline_apps_off.py @stephanegigandet 
It doesn't zip the file though.

**Comment by stephanegigandet** [comment]
Which URL is the app requesting? There's a bunch of files in /srv/off/html/data/offline :

-rw-r--r-- 1 root root  37946313 Jan  7 17:46 fr.openfoodfacts.org.products.small.csv
-rw-r--r-- 1 root root  11524750 Jan  7 18:13 fr.openfoodfacts.org.products.small.csv.tgz
-rw-r--r-- 1 root root  11438258 Jan 11 10:23 fr.openfoodfacts.org.products.small.zip
-rw-r--r-- 1 root root  94373736 Feb 25 22:30 large.zip
-rw-r--r-- 1 root root  41454803 Mar  4 20:42 en.openfoodfacts.org.products.small.csv
-rw-r--r-- 1 root root 773612114 Mar  4 20:45 en.openfoodfacts.org.products.large.csv
-rw-r--r-- 1 root root  12347051 Mar  4 20:59 en.openfoodfacts.org.products.small.csv.zip
