### ISSUE TITLE
Notify Robotoff when a product is created/updated/deleted

### ISSUE THREAD

**Issue by raphael0202** [openfoodfacts/openfoodfacts-server#1707]
Notify Robotoff when a product is created/updated/deleted, so we can:
- generate insights (ex: category)
- delete insights associated with deleted products
- delete insights if the attribute has been manually provided (ex: a user manually set the category, the category insight is not necessarily relevant anymore)

For `created` actions, the best would be to wait for the form to be sent before triggering a notification (in other words, don't send a notification as soon as the images are uploaded)

Send an application/x-www-form-urlencoded `POST` request to `/api/v1/webhook/product` with the following parameters:
- barcode (string, required)
- action (string, required) : one of `updated`, `deleted`, `created`
- updated_fields (str, comma separated list): list of updated fields (only for `updated` action)

**Comment by stephanegigandet** [comment]
Currently the form does not keep track of what has been updated, can I just notify that it has been updated? Then you can delete all current insights and recompute new ones. Is that ok?

**Comment by hangy** [comment]
> Currently the form does not keep track of what has been updated, can I just notify that it has been updated? Then you can delete all current insights and recompute new ones. Is that ok?

Don't we have the changed fields available when the changelog entry is created?

**Comment by raphael0202** [comment]
@stephanegigandet Yes just notifying that the product has been updated is enough, no need to provide a detailed changelog

**Comment by raphael0202** [comment]
@stephanegigandet I believe this issue can be closed?
