### ISSUE TITLE
Ensure the JSON is moved properly as well when moving images

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1708]
Ensure the JSON is moved properly as well when moving images

**Comment by CharlesNepote** [comment]
Include json *inside* images?

**Comment by teolemon** [comment]
nope, move the JSON to the new barcode folder.

**Comment by stephanegigandet** [comment]
When images are moved, they are in fact reuploaded, so cloud vision is called again and a new JSON is saved.
But we did not remove the old json, I'll fix that.
