### ISSUE TITLE
Add a non-blocking « Packaging Code to be completed » status

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#171]
add the « Packaging code to be completed » status so that we can spot meats, milks… without packager codes

**Comment by stephanegigandet** [comment]
Many products do not have packaging codes though... Or we need to put a checkbox "no packaging code". Or we could put "unknow" in the packaging codes field.

**Comment by teolemon** [comment]
It would be mainly for power contributors, to intersect with specific categories.
Perhaps we could add a "has packager code in europe" attribute to categories

**Comment by teolemon** [comment]
Also, some products have to have a packaging code

**Comment by teolemon** [comment]
@stephanegigandet it could be non-blocking, removing the need to give it a "no packager code tickbox"

I see mainly this as a power tool for contributors to be able to do an advanced search.

**Comment by hangy** [comment]
Implemented in 9f294f1ae32565265a3cb370520dd53c9e319d8c, created [PR](https://bitbucket.org/openfoodfacts/product-opener/pull-requests/63) for internal review.

**Comment by hangy** [comment]
PR merged 17ed75f197b809ac53beb0947526896d14d1ff14
