### ISSUE TITLE
Open X Facts - Tweak config to support favicons

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1715]
### What
Tweak Open Beauty Facts server config to : 
- [ ] support favicons specific to Open X Facts
- [ ] add the Apple App Store shortcut to the Open X Facts app

### Part of
- #5505 
- #5536 
- #5555

**Comment by stephanegigandet** [comment]
Fixed in https://github.com/openfoodfacts/openfoodfacts-server/pull/10757
