### ISSUE TITLE
Add nova groups to horizontal and vertical axis in graph generation

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#1722]
### What
- In the search page: https://world.openfoodfacts.org/cgi/search.pl?graph=1
- Is it possible?

### Part of
- #5751 
- #5519

**Comment by stephanegigandet** [comment]
It's possible, but it requires a bit more code because NOVA is not stored as a nutrient, it's a separate field, we'll need to add some special code, as we do for the number of ingredients / additives.

**Comment by teolemon** [comment]
Also, it will create ugly clusters for dots.

**Comment by CharlesNepote** [comment]
Yes I understand it's not as easy as other data and the need has to be completed (is dot graph relevant? what kind of other graphs?).

It's not a high priority but Nova groups are an interesting score for non-specialists.

**Comment by teolemon** [comment]
We bumped into this issue again with Anouck, trying to generate a US histogram for NOVA

**Comment by teolemon** [comment]
Ok, done, as predicted, we do run into ugly cluster for dots. Having a more granular measurement of ultra-processing would be interesting
