### ISSUE TITLE
connecting open food facts library to android studio barcode scanner project (how to link it in?)

### ISSUE THREAD

**Issue by aqkd1** [openfoodfacts/openfoodfacts-server#1723]
**Checklist:**

* [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-server/issues) before creating or reporting a issue.

* [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.

**Summary:**

Summarize your issue in one sentence (what goes wrong, what did you expect to happen).

**Steps to reproduce:**

How can we reproduce the issue?

**Add system logs:**

Add logcat files here (if you are able to add).

**Expected behavior:**

What did you expect the app to do?

**Observed behavior:**

What did you see instead?  Describe your issue in detail here.

**Comment by teolemon** [comment]
For the mobile app, please see : https://github.com/openfoodfacts/openfoodfacts-androidapp

**Comment by aqkd1** [comment]
> For the mobile app, please see : https://github.com/openfoodfacts/openfoodfacts-androidapp

Thank you, I've looked at that already but i can't decipher how to link the database into my own app without copying the entire project :D

**Comment by stephanegigandet** [comment]
@aqkd1 : please see https://en.wiki.openfoodfacts.org/API for all the details about the API for Open Food Facts.
