### ISSUE TITLE
Show barcode image on product page

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#1728]
Barcode image should be displayed on the product page, not only barcode numbers.

**Rationale:**
* it becomes easier to test our mobile apps with products we don't have physically
* it becomes easier to compare Open Food Facts data with other mobile apps
* it makes data more trustable: I can verify the barcode of my product is the same as displayed on the web page
* some people, for whatever reason, could love to print the product page and scan it later
* it makes the web page more graphical
* last, but not least, it becomes easier to provide services for producers which do not have barcodes: we could build special pages for them

Here is **an interesting JS library** that can produce SVG based on the numbers: https://lindell.me/JsBarcode/

**Comment by sandy9999** [comment]
Where can I find the source/script that renders the individual product page?

**Comment by flyer1996** [comment]
it's so difficult!
