### ISSUE TITLE
Broken italian translation on the footer

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1729]
![image](https://user-images.githubusercontent.com/1689815/55167171-bc5e6280-5170-11e9-86ea-3ca228c5fd6a.png)

**Comment by teolemon** [comment]
Fixed in https://crowdin.com/translate/openfoodfacts/440/en-it#q=raccog
Will sync soon

**Comment by VaiTon** [comment]
This can be closed @teolemon 
![image](https://user-images.githubusercontent.com/12072630/58368458-9eea1280-7eed-11e9-988d-ad0a1cefd672.png)
