### ISSUE TITLE
Adding a picture button problem

### ISSUE THREAD

**Issue by TaciteOFF** [openfoodfacts/openfoodfacts-server#173]
When a product page is empty, clicking on the "Add a picture" button located under "Ingredients" moves us to the top of the page.

**Comment by chk1** [comment]
Photo upload buttons are surrounded by `<a>` elements with `href="#"`, my guess is that these are causing it. I can suppress the jump when I remove `href="#"` in my browser's devtools before clicking the button.

**Comment by chk1** [comment]
Awesome, thank you
