### ISSUE TITLE
Query search.pl?search_simple=1&json=1 return html reslt

### ISSUE THREAD

**Issue by deniger** [openfoodfacts/openfoodfacts-server#1732]
**Steps to reproduce:**

open the URL:
https://ssl-api.openfoodfacts.org/cgi/search.pl?search_simple=1&json=1&action=process&fields=image_small_url,product_name,brands,quantity,code,nutrition_grade_fr&search_terms=2000000088789&page=1

+ Expected: a json result
+ Result: a html page

**Comment by hangy** [comment]
The search page simply redirects to the product's web page if an exact barcode match is found. This is somewhat OK for interactive users on the website, but obviously pretty bad when using the API, because it doesn't product consistent JSON.

**Comment by deniger** [comment]
IMHO it shouldn't happen if json parameter is equal to 1 :)

**Comment by hangy** [comment]
> IMHO it shouldn't happen if json parameter is equal to 1 :)

I agree. If any kind of structured output is returned, then a list with `0..n` items should be returned, even if the query matches exactly one item.
