### ISSUE TITLE
Gluten automagically appears if sarrasin is an ingredient

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#1735]
Even if the product is without gluten.

See: https://world.openfoodfacts.org/product/3380380047749/tartines-bio-craquantes-au-sarrasin-sans-gluten-le-pain-des-fleurs

Or: https://fr.openfoodfacts.org/produit/3380380049743/farine-bio-de-sarrasin-ma-vie-sans-gluten

**Comment by stephanegigandet** [comment]
It's in our allergen taxonomy, I will remove it.
https://en.wiki.openfoodfacts.org/Global_allergens_taxonomy

fr:gluten, blé, seigle, orge, avoine, épeautre, sarrasin, kamut, son de blé, blé complet, gluten de blé, fibre de blé, malt d'orge, malt, froment, farine de blé, farine de froment, boulgour, petit épeautre

**Comment by VaiTon** [comment]
Is this still an issue?

**Comment by stephanegigandet** [comment]
Fixed with a new allergens taxonomy.
