### ISSUE TITLE
Incorrect URL for 2nd level search link

### ISSUE THREAD

**Issue by hangy** [openfoodfacts/openfoodfacts-server#174]
When you browse products by state/brand/contributor/… and use more than one level, then the second "type" link incorrectly leads to the first type.

Example: http://world.openfoodfacts.org/brand/nestle/country/germany
```html
<p><a href="/brands">Brands</a>: <a href="/brand/nestle">Nestle</a>
<br /><a href="/brands">Countries</a>: <a href="/country/germany">Germany</a></p>
```
The second link should lead to /countries instead of /brands, or it could point to /brand/nestle/countries to allow further faceted search.

**Comment by stephanegigandet** [comment]
Fixed, thank you @hangy!
