### ISSUE TITLE
New sources facet to identify apps, imports from producers, sellers, scan parties etc.

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#1746]
It would be useful to be able to easily see products that have been edited by a given source: a specific app, producer, or distributor/store, and by all apps / all producers etc.

We already have some of this info in the /editor facet for producer imports because we use a specific user for each import. We have that for some apps that use a single user (e.g. Yuka, Date Limite). But we don't have it for the OFF app (which does not use a specific user).

We could also use this facet for scan parties, to easily identify products gathered during a scan party.

The new /sources facets would have values like:

/source/casino-producer -> products made by casino 
/source/fleury-michon-producer -> products made by fleury michon
/source/producers -> products from all producers (parent)

/source/casino-store -> products sold by casino and data (e.g. product is sold by casino in this country) has been provided by casino
/source/stores

/source/foodrepo-import -> import of another database

/source/rotterdam-201904-scanparty
/source/scanparties

/source/off-app
/source/off-android-app
/source/date-limite-app
/source/apps

The source field will be assigned when doing imports, or from the useragent fields identifying apps. It will not be set directly through the API.

**Comment by hangy** [comment]
I like the idea! It could also make the data more transparent for stuff like attribution. We should probably store the information for each product revision (including image uploads), so that it's obvious (at least when reviewing the history) who contributed which fact.

> The source field will be assigned when doing imports, or from the useragent fields identifying apps. It will not be set directly through the API.

It could be useful to combine this with #1714. Due to the nature of OIDC, the `client_id` from the introspection endpoint directly correlates to a client (app), so that no guesswork based on user agents needs to be done for those clients.

**Comment by stephanegigandet** [comment]
Changed to /data-sources as we already have a sources field for imports.

Also reversed the order:  [producer|scanparty|import|app]-[casino|rotterdam-2019-04|date-limite]

**Comment by stephanegigandet** [comment]
@hangy : good idea, we can add the source to changes.sto. This is what we have currently:

	push @$changes_ref, {
		userid=>$User_id,
		ip=>remote_addr(),
		t=>$product_ref->{last_modified_t},
		comment=>$comment,
		rev=>$rev,
	};

**Comment by stephanegigandet** [comment]
I'm going to add the basic support for the data_sources field (just declaring the new field), and a way to populate it through upload_photos.pl (for scan parties). We need it in order to load thousands of photos that sebleouf took in the Netherlands, and be able to identify the corresponding products.

Then we can gradually add the population of this field for the producer imports, the apps etc.

**Comment by stephanegigandet** [comment]
Deployed.
