### ISSUE TITLE
Explain Nova computation result for each product

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#1754]
"Why this product has Nova X?" This a frequently asked question.

At least on Open Food Facts website, we should explain each Nova computation for each product, like we already do for Nutriscore (" -- energy 8 + sat-fat 5 + fr-sat-fat-for-fats 0 + sugars 0 + sodium 0 - fruits 0% 0 - fiber 0 - proteins 5 -- fsa 13 -- fr 13"), but in a more readable way.

**Comment by stephanegigandet** [comment]
There's a bit of code for that already: https://github.com/openfoodfacts/openfoodfacts-server/blob/master/lib/ProductOpener/Food.pm#L4956

and a $product_ref->{nova_group_debug} field. It certainly could be made more readable and complete.

**Comment by aleene** [comment]
I concur, it would be nice to show the user which ingredients trigger a certain nova level. Is the nova_group_debug usable for that?

**Comment by teolemon** [comment]
This was fixed by the NOVA knowledge panel. @CharlesNepote @stephanegigandet @aleene 


![Image](https://user-images.githubusercontent.com/1689815/201685734-d5f8303e-cfa0-4972-a18a-45827948860b.png)
