### ISSUE TITLE
Some products edited by some apps like Yuka have empty units for nutrition facts

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#1762]
It seems that Yuka is only passing a unit for energy (strangely in kcal). Which means we apply the default unit for the rest (grams), which is fine, but we have empty unit fields:

nutriments: {
nutrition-score-uk: 1,
fiber_unit: "g",
sugars_unit: "",
nova-group_serving: 4,
sodium: 0.0275590551181102,
fiber_100g: 0.5,
nova-group_100g: 4,
salt_value: 0.07,
energy_unit: "kcal",
proteins_100g: 0.5,
saturated-fat_100g: 0.1,
carbohydrates_unit: "",
saturated-fat: 0.1,

https://world.openfoodfacts.org/api/v0/product/8410509003624/boisson-vegetale-riz-quinoa-costa-eco

We probably should set the _unit fields to "g" for future updates, and convert existing products, as some apps seem to be using the _unit field.

**Comment by VaiTon** [comment]
This can be closed @stephanegigandet
