### ISSUE TITLE
Create an API to write quality facet

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1771]
Create an API to write quality facet so that Robotoff can populate facets

**Comment by eadaradhiraj** [comment]
@teolemon HI i am willing to take up this issue? Can you add me to slack? My email id is eadaradhiraj@gmail.com

**Comment by hangy** [comment]
How do you want this to be implemented? When a product is stored, the `quality_tags` are removed completely https://github.com/openfoodfacts/openfoodfacts-server/blob/c412cc745fdba9597061f0fdc66803af5265f24f/lib/ProductOpener/SiteQuality_off.pm#L873, and then get recalculated. We could probably have quality tags where we know that they're calculated by an external app, and not remove them. But that kinda depends on how you spec this feature request. 🙂

**Comment by VaiTon** [comment]
We could delete only the quality facets generated by the software.

**Comment by hangy** [comment]
Yup, but as the tag cannot contain any additional information about that (as far as I know), a list of tags that gets generated by an external API. I'm missing a good use case description for this issue. 🙂

**Comment by raphael0202** [comment]
@teolemon what kind of quality facet did you have in mind? As quality facets are populated using scripts, it may be easier to add the script on product opener side (even if not written in perl)

**Comment by teolemon** [comment]
Things where OCR or insights contradict existing values

**Comment by raphael0202** [comment]
Indeed it would be interesting. As it must be updated everyday, the simplest way would be to add it as a script. Robotoff already offers insight dumps, downloading the dump every night and populating the facet is feasible

**Comment by raphael0202** [comment]
Another (simpler) possibility would be that Robotoff has direct access to the MongoDB database, which would also make sense.

**Comment by raphael0202** [comment]
Now robotoff has access to the MongoDB, and adds directly every night quality facets, so we can close the issue.
