### ISSUE TITLE
Disable NOVA if too many ingredients are not in the taxonomy

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#1772]
If some ingredients are not known in the taxonomy, there is a risk that they might be triggers for NOVA 3 or 4, especially for languages for which we have not enough entries in the taxonomy.

If the other ingredients already have triggered NOVA 4, then it is fine to ignore unknown ingredients.

**Comment by VaiTon** [comment]
This can be closed @stephanegigandet
