### ISSUE TITLE
More cutting words for ingredients lists

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1773]
`Préparation Au four:`
Conservar em local fresco

**Comment by aleene** [comment]
What do you mean?

**Comment by VaiTon** [comment]
@aleene He means that when the text is auto-extracted from the ingredients list image strings like these should be removed automatically because they are just prefixes.

**Comment by stephanegigandet** [comment]
Those have been added at some point already.
