### ISSUE TITLE
Fix handling of quotes in ingredients list for ingredient parsing

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#1776]
Related to #1769 : we currently have &quot; in ingredients lists for ". The ingredient parser does not take this into account, which means we have ingredients like https://it.openfoodfacts.org/ingrediente/farina-di-grano-tenero-tipo-quot

We should fix the ingredient parser to handle &quot; (until we implement storing the " directly in mongodb)

**Comment by sandy9999** [comment]
What's the current state of this issue?

**Comment by VaiTon** [comment]
I think ef22aea should have closed it.

**Comment by hangy** [comment]
> I think [ef22aea](https://github.com/openfoodfacts/openfoodfacts-server/commit/ef22aea34391a4a0ee132982d9920cf808565a5a) should have closed it.

ACK.
