### ISSUE TITLE
Detected other nutrition repeated

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#1778]
**Checklist:**

* [X] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-server/issues) before creating or reporting a issue.

**Summary:**

The other nutrition elements are shown multiple times.

**Steps to reproduce:**

look at https://world.openfoodfacts.org/product/3760205598654/crazy-tiger-energy-drink.

**Expected behavior:**

Just once is enough

**Observed behavior:**

![Screenshot 2019-05-14 at 19 52 17](https://user-images.githubusercontent.com/1329905/57720518-452e5080-7682-11e9-80e1-4e1fd476d7e6.png)

**Comment by stephanegigandet** [comment]
Thanks, it's fixed.

I'm updating affected products:

./update_all_products.pl --process-ingredients --query other_nutritional_substances_tags=en:inositol
./update_all_products.pl --process-ingredients --query other_nutritional_substances_tags=en:taurine
./update_all_products.pl --process-ingredients --query other_nutritional_substances_tags=en:l-carnitine
