### ISSUE TITLE
Changes to contribution counts and attribution of products to users (creator field)

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#178]
There has been inconsistencies in the way that counts of contributions (number of products created, edited etc.) have been counted for each contributors:
1. Many products have been created through the mobile app by unidentified contributors. They used to be attributed to the first identified user that edited them. Then it was considered unwanted, but it was added again when running scripts that updated some other properties of all products.
2. the url /contributors list the counts of products created by each user, but the url /contributor/userid shows the count of products edited by user userid

To remove the inconsistencies, the following changes will be applied:
1. Products created by unidentified contributors through the app will be attributed to a special user "openfoodfacts-contributors". They will not be re-attributed to the first identified user to edit the product.

This change will also be applied to all existing products.
1. /contributor/userid will now return only products created by user userid

New urls /editors and /editor/userid will show products created and/or edited (in any way: photos or text / numeric fields) by each user.

Not changed:

/photographers and /photographer/userid show who has uploaded pictures

/infomers and /informer/userid show who has added values for some fields (with no values previously)

/correctors and /corrector/userid show who has changed values for some fields (with existing values previously)

**Comment by stephanegigandet** [comment]
Code changes: https://bitbucket.org/openfoodfacts/product-opener/commits/38506b0b7419d17dbc45fd7c19ebda8ce945b607

Applied to production.

**Comment by stephanegigandet** [comment]
Need to update links for logged-in contributors so that they have links to /contributor/userid and /editor/userid

**Comment by teolemon** [comment]
created #275

**Comment by teolemon** [comment]
@stephanegigandet edited your comment to point to the GitHub commit.

**Comment by VaiTon** [comment]
@stephanegigandet can we close?

**Comment by teolemon** [comment]
Yes, long been fixed @VaiTon @stephanegigandet 
I'm closing, thanks for the spot
