### ISSUE TITLE
Robotoff asking questions already for existing values

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#1790]
I've just completed quantity (with the correct value) and robotoff is asking to confirm quantity value. I'm confused.
![image](https://user-images.githubusercontent.com/562352/58085942-fde21b80-7bbd-11e9-9764-0f9c3de12e78.png)

**Comment by teolemon** [comment]
This is a Robotoff issue.

**Comment by hangy** [comment]
Moved to openfoodfacts/robotoff#52
