### ISSUE TITLE
Trimming of white background with ImageMagick Trim() during image crop is very slow 

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#1793]
It can take up to 10 seconds to trim the white space of one single image... 

In process_image_crop.pl :

	# add auto trim to remove white borders (e.g. from some producers that send us images with white borders)

	$source->Trim();

Test image: https://fr.openfoodfacts.org/images/products/325/622/638/3503/9.jpg

This is with ImageMagick 7.0.8-34 Q16 x86_64 2019-03-18

**Comment by stephanegigandet** [comment]
root@off1:/srv/off/html/images/misc# convert --version
Version: ImageMagick 7.0.8-34 Q16 x86_64 2019-03-18 https://imagemagick.org
Copyright: © 1999-2019 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP
Delegates (built-in): bzlib djvu fontconfig freetype gvc jbig jng jp2 jpeg lcms lqr lzma openexr png tiff wmf x xml zlib
root@off1:/srv/off/html/images/misc# time convert 3256226383671.jpg -trim 3256226383671_trim.jpg

real    0m38.503s
user    4m28.628s
sys     0m0.212s

**Comment by hangy** [comment]
Would you consider re-compiling ImageMagick without HDRI? Apparently, that costs a lot of performance with ImageMagick 7: https://github.com/ImageMagick/ImageMagick6/issues/47#issuecomment-498311922

**Comment by stephanegigandet** [comment]
We had huge problems with imagemagick making apache segfault, so I'd prefer not to touch it. ;)

See discussion in https://openfoodfacts.slack.com/messages/C1FPYCWM7/convo/GKB0C32TS-1559812818.045500/ 

I had a very bad night as I wasn't able to make imagemagick work correctly on the production server for several hours. We ended up installing imagemagick and perlmagick 7.0 from source, as the debian provided packages were making the server core..

**Comment by hangy** [comment]
> We ended up installing imagemagick and perlmagick 7.0 from source, as the debian provided packages were making the server core..

I think that's part of the "problem". ImageMagick shold probably be re-compiled the same way as you did here, but without HDRI. If the dev server's specs&setup are identical to the production server, you could test there. 🙂

**Comment by stephanegigandet** [comment]
This is causing big issues for the producers platform, when we import images: it takes a huge amount of cpu and time.

206657 off       20   0 1799052 997.8m   6292 R  1443  1.6   3448:55 minion_pr+

**Comment by stephanegigandet** [comment]
Going to try recompiling imagemagick.

dev server:

ns3135968:/home/stephane/imagemagick# time convert test-trim-lego.png -trim test-trim-lego.trimmed.png

real    0m1.289s
user    0m1.192s
sys     0m0.056s
root@ns3135968:/home/stephane/imagemagick# convert -v
Version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org

current prod:

off1:/home/off/imagemagick# time convert test-trim-lego.png -trim test-trim-lego.trimmed.png

real    0m44.565s
user    6m8.604s
sys     0m0.276s
root@off1:/home/off/imagemagick# convert --version
Version: ImageMagick 7.0.8-34 Q16 x86_64 2019-03-18 https://imagemagick.org

**Comment by stephanegigandet** [comment]
apt-get install libde265-dev
apt-get install libwebp-dev
apt-get install autotools-dev
apt-get install automake
apt-get install build-essential libtool
apt-get install pkg-config

apt-get install libpng-dev
apt-get install libjpeg-dev 

wget https://github.com/strukturag/libheif/releases/download/v1.6.2/libheif-1.6.2.tar.gz
tar xvfz libheif-1.6.2.tar.gz
cd libheif-1.6.2
./autogen.sh
./configure
make
make install
cd ..

wget http://www.imagemagick.org/download/ImageMagick.tar.gz
tar xvfz ImageMagick.tar.gz
cd ImageMagick-7.0.9-21/
./configure --with-heic=yes --with-webp=yes --disable-hdri --enable-shared --with-perl
make
make install

**Comment by stephanegigandet** [comment]
New imagemagick re-compiled on dev server and off1. Trimming is now more than 100 times faster. :)
