### ISSUE TITLE
Success button too bright

### ISSUE THREAD

**Issue by VaiTon** [openfoodfacts/openfoodfacts-server#1794]
**Checklist:**
* [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-server/issues) before creating or reporting a issue.

* [ ] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.

**Summary:**
The "Get the app" button on the top-right of the page is too bright to be seen.

![image](https://user-images.githubusercontent.com/12072630/58178537-ae2b4f00-7ca6-11e9-9a87-22736ced66b1.png)

**Comment by stephanegigandet** [comment]
This change has been deployed in production, closing the bug.
