### ISSUE TITLE
Missing categories

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1799]
![image](https://user-images.githubusercontent.com/1689815/58269163-413bb600-7d87-11e9-8370-dd7833626620.png)
https://world.openfoodfacts.org/product/2951726703134/comte-aoc-carrefour#

**Comment by aleene** [comment]
What happened at the "...cheeses, , Labeled..."?

**Comment by stephanegigandet** [comment]
We removed those categories: Aoc-cheeses, Labeled-cheeses. Same for categories containing "organic", "Label Rouge", "IGP" etc.
