### ISSUE TITLE
Invisible user

### ISSUE THREAD

**Issue by TaciteOFF** [openfoodfacts/openfoodfacts-server#180]
Looks like some products are still not linked to any username although openfoodfacts-contributors has been created.

<img width="298" alt="capture d ecran 2015-12-28 a 15 11 07" src="https://cloud.githubusercontent.com/assets/11161632/12019826/7208830c-ad75-11e5-9465-6e1614712931.png">

http://fr.openfoodfacts.org/etat/a-completer/contributeurs

**Comment by teolemon** [comment]
@TaciteOFF fixed ?

**Comment by TaciteOFF** [comment]
@teolemon Nope

**Comment by VaiTon** [comment]
Seems to be resolved. 
This can be closed @teolemon, @TaciteOFF
