### ISSUE TITLE
Create a developement guide

### ISSUE THREAD

**Issue by VaiTon** [openfoodfacts/openfoodfacts-server#1804]
### What
It would be good if there were a wiki entry to help people setup a dev environment for ProductOpener.

### Part of
#5512

**Comment by hangy** [comment]
There's some information about that at https://en.wiki.openfoodfacts.org/Product_Opener_installation. However, it can be a bit annoying to keep a local development environment up-to-date, so I usually use [Docker](https://github.com/openfoodfacts/openfoodfacts-server/tree/61819fe2e66da2a4cf24d3b8850f0f3e289c56dc/docker#docker-compose). 🙂 There's [another Docker container](https://github.com/nerocro/docker-off) that gets you started with some sample data, if you need that.

**Comment by ocervell** [comment]
I have updated the deployment guide for Docker + the dev environment quick start guide:
* https://github.com/openfoodfacts/openfoodfacts-server/blob/main/installation/dev-environment-quick-start-guide.md
* https://github.com/openfoodfacts/openfoodfacts-server/blob/main/installation/docker-developer-guide.md

If those are enough in your opinion, we can close this.
