### ISSUE TITLE
Prevent all apps (OFF + 3rd party apps) to modify images and data sent by manufacturers

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#1810]
Apps should still be able to send new pictures, but only to select them if the image is missing (e.g. no ingredient image sent by the manufacturer).

**Comment by stephanegigandet** [comment]
There are some edit rules in place to prevent that already, but they are not always working.

**Comment by CharlesNepote** [comment]
Many manufacturers have recently put the nutricore on their products. Will we have to wait for their new pictures to see it? Even if users publish updated photos?

Wouldn't it be better to provide a validating process for special products?
- Regular user modifies the product (whatever modification it is).
- If the product is flagged as "protected" then the modification needs moderator/editor validation.
- The user is told that his data will be published after a validation.

We could then protect:
- automatically, products from manufacturers
- automatically, verified products
- automatically, most scanned complete products
- manually (or automatically), sensitive products such as Coca-Cola, Nutella...

"Editors" could be new role between regular users and admins.

**Comment by hangy** [comment]
How do you know which fields were added by a manufacturer? If the manufacturer only sends data in for one language, it should still be possible to update other fields. Also, if a manufacturers provides a producer code, other producer codes could also be valid...

**Comment by stephanegigandet** [comment]
Apps will still be able to upload new pictures, and they will trigger robotoff changes (e.g. if there's a photo with the Nutri-Score label). Same for automatically recognized packaging codes.

We don't know exactly which fields were added by a manufacturer (there's some info about that in the sources field, but it's possible it was changed later).

My plan is that when a manufacturer has sent us data (with a bare minimum of ingredients in one language and nutrition facts) to:

1. Allow all editions on the Web site.
2. Restrict editions through the apps so that they can only add fields, but not edit or delete them.

**Comment by aleene** [comment]
Guess there is a relation with the checked status. Ideally behaviour should be similar.

**Comment by stephanegigandet** [comment]
For checked products, we don't know when the products change though. When we have data from manufacturers, we can somewhat assume that they have sent us the last version.

**Comment by stephanegigandet** [comment]
Deployed in production.
