### ISSUE TITLE
Broken footer for 404 not found pages, and remove exit() calls

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#1813]
404 pages have an extra header at the bottom of the generated page:

https://world.openfoodfacts.org/some-bogus-url

</body>
--
  | </html>
  | <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
  | <html><head>
  | <title>404 Not Found</title>
  | </head><body>
  | <h1>Not Found</h1>
  | <p>The requested URL /cgi/display.pl was not found on this server.</p>
  | <hr>
  | <address>Apache/2.4.25 (Debian) Server at world.openfoodfacts.org Port 80</address>
  | </body></html>

**Comment by hangy** [comment]
Sounds like we need to send the non-success status-code and tell Apache that evertyhing is OK.

https://stackoverflow.com/a/8288955/11963
https://metacpan.org/pod/release/GOZER/mod_perl-1.31/faq/mod_perl_faq.pod#So-how-do-I-use-mod_perl-in-conjunction-with-ErrorDocument?

**Comment by stephanegigandet** [comment]
Fixed by @hangy, thank you!
