### ISSUE TITLE
Extract the cutting word list to make the translation easier

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1817]
https://github.com/openfoodfacts/openfoodfacts-server/pull/1814/files#diff-1b9ef03a7c75fb2d89ed687ee8cb04a6R765
Extract it to the wiki, for instance

**Comment by aleene** [comment]
Or call it a taxonomy and make a text file

**Comment by stephanegigandet** [comment]
One thing to keep in mind: this list is very dangerous. If something matches before the ingredient list, or in it, then everything after will be discarded.

Anything added to it (or translated) should be tested first. We probably should create a tool that shows which ingredient list would be cut, and how, before actually applying those cut lists.

**Comment by hangy** [comment]
> Extract it to the wiki, for instance

No, please don't. We shouldn't put that stuff on the wiki as we're moving most translation efforts to GitHub right now.

**Comment by aleene** [comment]
I added the cutting words in the ingredients taxonomy as comments.

**Comment by stephanegigandet** [comment]
The words / phrases / regexps used to cut unwanted parts of ingredients lists can destroy data (and they did in some cases). They should not be translated out of context, and they should always be tested.
It's not really a translation effort, it's more a data collection (from actual ingredients lists) and testing effort.
So at this point, I think it is better to keep them in the code.
