### ISSUE TITLE
Automatically add additives, minerals, vitamins, nucleotides, other nutritional substances taxonomies to the ingredients taxonomy

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#1823]
When building the ingredients taxonomy, automatically include all the entries from the additives, minerals, vitamins, nucleotides, other nutritional substances taxonomies. cc @aleene 

When this is done, we can maintain the translations for the additives, minerals etc. only in their respective taxonomies.

**Comment by stephanegigandet** [comment]
Deployed in production.

**Comment by aleene** [comment]
Great, work to do then to clean the ingredients
