### ISSUE TITLE
Possibility to search a product by it's name

### ISSUE THREAD

**Issue by Nymerea** [openfoodfacts/openfoodfacts-server#183]
Hello,

For the ubuntu touch application, I would like to add the possibility to search a product by it's name (it's faster than typing the barcode) but the api doesn't allow me to do it !

I mean : 
http://world.openfoodfacts.org/cgi/search.pl?search_terms=yoplait&search_simple=1&jqm=1

the api return html code and no json format. it's quite annoying for handle the result into QML.

Best regards

**Comment by stephanegigandet** [comment]
Fixed by bug #186.

Documentation: http://en.wiki.openfoodfacts.org/API#READ_API_Documentation
