### ISSUE TITLE
Software error: The 'epoch' parameter (undef) to DateTime::from_epoch did not pass regex check

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#184]
Reported by an user on product http://fr.openfoodfacts.org/produit/3017760038409/lulu-la-barquette-fraise-kraft-foods

Software error:

The 'epoch' parameter (undef) to DateTime::from_epoch did not pass regex check
 at /usr/local/lib/perl/5.10.1/DateTime.pm line 488.
    DateTime::from_epoch(undef, "locale", DateTime::Locale::fr=HASH(0x134372e0), "time_zone", "Europe/Paris", "epoch", undef) called at /home/off-fr/cgi//Blogs/Display.pm line 594
    Blogs::Display::display_date(undef) called at /home/off-fr/cgi//Blogs/Display.pm line 610
    Blogs::Display::display_date_tag(undef) called at /home/off-fr/cgi//Blogs/Display.pm line 5436
    Blogs::Display::display_product(HASH(0x1304c7f8)) called at /home/off-fr/cgi/display.pl line 52
    ModPerl::ROOT::ModPerl::Registry::home_off_2dfr_cgi_display_2epl::handler(Apache2::RequestRec=SCALAR(0x13453600)) called at /usr/local/lib/perl/5.10.1/ModPerl/RegistryCooker.pm line 206
    eval {...} called at /usr/local/lib/perl/5.10.1/ModPerl/RegistryCooker.pm line 206
    ModPerl::RegistryCooker::run(ModPerl::Registry=HASH(0x1350fdc0)) called at /usr/local/lib/perl/5.10.1/ModPerl/RegistryCooker.pm line 172
    ModPerl::RegistryCooker::default_handler(ModPerl::Registry=HASH(0x1350fdc0)) called at /usr/local/lib/perl/5.10.1/ModPerl/Registry.pm line 31
    ModPerl::Registry::handler("ModPerl::Registry", Apache2::RequestRec=SCALAR(0x13453600)) called at -e line 0
    eval {...} called at -e line 0

**Comment by hangy** [comment]
Opening this product no longer causes an error, nor a warning in the modperl_error_log file. I believe it may have been fixed in d76865d5946770f2a705aa75e9ff5c5773bfd755 which was probably deployed after this report.
