### ISSUE TITLE
Main page shows last edited products

### ISSUE THREAD

**Issue by VaiTon** [openfoodfacts/openfoodfacts-server#1848]
### Summary
The main page show the last edited products even though it says "Last added products"
### Steps to reproduce
Edit a product and go to the main page. You should see it between the first ones.
### Screenshots
![image](https://user-images.githubusercontent.com/12072630/58759858-e6e1e880-8530-11e9-9a97-d6bcb6257196.png)

**Comment by hangy** [comment]
This is intentional: https://openfoodfacts.slack.com/archives/C02LDQDDD/p1559470809010200

We should probably just update the texts to reflect the current behaviour.
