### ISSUE TITLE
Bottom pagination not available in some cases

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1853]
![image](https://user-images.githubusercontent.com/1689815/58763955-f594c380-8561-11e9-807f-6888a28e5ce7.png)
Bottom pagination not available in some cases. It looks like the same bug as the "Save" button bug ?

**Comment by stephanegigandet** [comment]
It's a different bug, it is because the lazyload of images does not work well the equalizer to make the left column and the center column the same height. cc @hangy See #1198

I couldn't find a way to make the equalizer work with lazyload.

Same issue that makes the edit history not shown completely on product pages.

**Comment by VaiTon** [comment]
@stephanegigandet have you tried with `reInit()`? 
I think it could be useful to call it after every load.
Docs here: https://foundation.zurb.com/sites/docs/javascript.html#adding-content-to-plugins

**Comment by VaiTon** [comment]
`$(document).foundation('equalizer','reflow');` does work

**Comment by stephanegigandet** [comment]
@VaiTon : calling equalizer reflow works, but I don't know how to call it once a new image is loaded by lazyload, as I didn't find a way to specify a callback after an image is loaded.

**Comment by VaiTon** [comment]
@stephanegigandet we could switch to this library http://jquery.eisbehr.de/lazy/
It has callbacks for image loads and it's a jquery plugin

**Comment by VaiTon** [comment]
In particular we could use this example http://jquery.eisbehr.de/lazy/example_show-a-loading-image

**Comment by stephanegigandet** [comment]
My preference would be to remove javascript based lazy loading. This is the kind of thing that browsers will soon be able to do. (see https://addyosmani.com/blog/lazy-loading/ for upcoming support in Google Chrome).
