### ISSUE TITLE
Extend JSON/JSONP/XML API to lists of products (including search) and lists of tags

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#186]
Allow to retrieve structured results for different types of pages on Open Food Facts by just appending .json, .jsonp, .xml to the urls of the OFF web site. Or to add a parameter &json=1 &jsonp=1 &jqm=1 for urls that correspond to forms (e.g /cgi/search.pl)

Types of pages concerned:

1. Product pages
- already exists with urls /api/v0/product/[barcode].[json|jsonp|xml]
- will also support just adding .json / .xml (mostly for debugging purposes)

2. List of tags pages
- e.g. /categories or /category/soups/labels

3. List of products
- e.g. category/soups 

4. Search results

**Comment by Nymerea** [comment]
Duplicated of https://github.com/openfoodfacts/openfoodfacts-server/issues/183 ??

**Comment by stephanegigandet** [comment]
Yes, it will solve #183. While I'm at it, I'm thinking of taking a more general approach, both for the format of the API urls and for the implementation.

**Comment by stephanegigandet** [comment]
Deployed to production.

Documentation: http://en.wiki.openfoodfacts.org/API#READ_API_Documentation
