### ISSUE TITLE
Unknown Nutriscore Icon

### ISSUE THREAD

**Issue by VaiTon** [openfoodfacts/openfoodfacts-server#1863]
Could we add a new icon to represent an unknown nutriscore value?

**Comment by teolemon** [comment]
There can be 2 reasons for no Nutriscore:
- it's not computed because it's a food category not covered (eg: baby milks)
- it's not computed because we need a category and/or nutrition facts.

So we could have a grey logo with a question mark to prompt the user to type in the data.

**Comment by hangy** [comment]
We need to consider the Nutri-score the logo's copyright. Who owns the logo and do they allow creating derivates?

**Comment by VaiTon** [comment]
We can ask to nutriscore@santepubliquefrance.fr

**Comment by hangy** [comment]
https://www.santepubliquefrance.fr/Media/Files/NUTRISCORE/reglement_usage_EN
> The Industry actor commits not to modify, add, or remove any elements of the Logo.

However, it sounds like there should be a neutral logo.

**Comment by stephanegigandet** [comment]
We added a neutral logo for unknown Nutri-Score: https://static.openfoodfacts.org/images/attributes/nutriscore-unknown.svg
