### ISSUE TITLE
Nutrition score link dead

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#1865]
When listing the products in category, the average nutrition facts are shown. In this table there is a line with Nutrition Score - France. This is a link that is dead.

**Comment by teolemon** [comment]
https://world.openfoodfacts.org/category/milks
![image](https://user-images.githubusercontent.com/1689815/58876921-b2f0f980-86cf-11e9-8977-6e09ac0ca58f.png)

**Comment by hangy** [comment]
Not an as easy fix as it may seem. The nutriscore is defined as a nutrient: https://github.com/openfoodfacts/openfoodfacts-server/blob/25d4175330f9fadbba8bc80ec0afea358a9b4c3d/lib/ProductOpener/Food.pm#L3247-L3253

Maybe we should add a redirect?

**Comment by stephanegigandet** [comment]
Fixed.
