### ISSUE TITLE
[Tracker] cutting not working

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1867]
https://world.openfoodfacts.org/product/4099100016536/classic-bun-length-wieners-with-chicken-and-pork-parkview

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/59339112-dfc29380-8d03-11e9-868c-a97d4775e220.png)

**Comment by teolemon** [comment]
https://world.openfoodfacts.org/cgi/product.pl?type=edit&code=5412971016402

**Comment by teolemon** [comment]
arnaud leene [3:45 PM]
 Cutoff issue in polish: https://world.openfoodfacts.org/product/4022993045246/black-forest-teff-schnitzer

**Comment by stephanegigandet** [comment]
Fixed the first one, and the issue with too aggressive cutting in Polish. Not sure what the issue was for the others, please reopen if not fixed already.
