### ISSUE TITLE
Graphs can't be rendered because of products names containing antislashes ("\")

### ISSUE THREAD

**Issue by TaciteOFF** [openfoodfacts/openfoodfacts-server#188]
Since date-limite-app is automatically adding antislashes before apostrophe, map in Cestemballepresdechezvous website or graphs generated through the search engine aren't rendered.

**Comment by stephanegigandet** [comment]
Fixed the double escaping, thanks!

**Comment by TaciteOFF** [comment]
A bot will be needed to remove all the \ added to product name by date-limite-app.
Also searching "\" in the search engine returns all the products of the database (should return nothing and/or only the one with an actual "\" in the product name?)
