### ISSUE TITLE
demi-écrémé detection

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#1880]
**Describe the bug**
There is a detection issue with “demi-écrémé” and “demi - écrémé“. It is not detected as one ingredient.

**To Reproduce**
1. Go to https://world.openfoodfacts.org/ingredient/fr:ecreme
or https://world.openfoodfacts.org/ingredient/fr:demi

**Expected behavior**
Should not happen.

**Comment by stephanegigandet** [comment]
Some of them are a bit more complex:
"lait (Origine : France) écrémé"

**Comment by aleene** [comment]
I'll list the cumbersome ones in the taxonomy

**Comment by stephanegigandet** [comment]
Fixed and deployed. Some examples remain for "écrémé", but they do not come from "demi-écrémé". (e.g. things like "Lait entier (20%) et écrémé (10%)".
