### ISSUE TITLE
Packager codes set through the app can be deleted in next edit on the site

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1881]
The EMB code was destroyed without any action on my side

![image](https://user-images.githubusercontent.com/1689815/59030123-5ffa7c00-8860-11e9-9aa0-5e6126be5061.png)
![image](https://user-images.githubusercontent.com/1689815/59030147-7274b580-8860-11e9-97f5-488f06ae8dfd.png)
![image](https://user-images.githubusercontent.com/1689815/59030164-80c2d180-8860-11e9-9c80-981112ecf30d.png)

**Comment by stephanegigandet** [comment]
Please include the product url

**Comment by teolemon** [comment]
sorry: https://world.openfoodfacts.org/product/3512690000835/pate-oriental-gourmand-halal-isla-delice

**Comment by stephanegigandet** [comment]
It's a bug in the API that affects only the emb_codes field. On the site, and through the API when it is added with the add_emb_codes, the original value is saved to emb_codes_orig and the normalized value is set to emb_codes. This did not happen for emb codes set by the app.

**Comment by stephanegigandet** [comment]
Fixed and deployed.
