### ISSUE TITLE
"Nutrition facts are not specified on the product." is hard to see

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#1889]
Sometimes "Nutrition facts are not specified on the product." ([example](https://world.openfoodfacts.org/product/8423018110172/sesame-dore-hennedrog))

It's an important information. It could be highlighted a little bit. At least this information should have an id and or a class to let designers easily highlight it.

I suggest:
- `<p id="nutrition-facts-ns">Nutrition facts are not specified on the product.</p>`
- instead of `<p id="nutrition-facts-ns">Nutrition facts are not specified on the product.</p>`

That way we will be able to make some tests with the Open Food Facts power user extension script.

**Comment by CharlesNepote** [comment]
Found:
- https://github.com/openfoodfacts/openfoodfacts-server/blob/435a957fe5863ce9d2b99ebc3cf2978ddd8c8fcf/lib/ProductOpener/Display.pm#L7251
- https://github.com/openfoodfacts/openfoodfacts-server/blob/435a957fe5863ce9d2b99ebc3cf2978ddd8c8fcf/lib/ProductOpener/Display.pm#L7725

**Comment by stephanegigandet** [comment]
Foundation has "panel callout" classes:

<div class="panel callout">Nutrition facts are not specified on the product.</div>

Results in:

![image](https://user-images.githubusercontent.com/8158668/59114584-bc849680-8947-11e9-9d7f-21fc47057b47.png)

**Comment by VaiTon** [comment]
We could also use [this](https://foundation.zurb.com/sites/docs/callout.html#) with the classes `callout alert`

![image](https://user-images.githubusercontent.com/12072630/59117046-34a18b00-894d-11e9-90ab-9260cd30832d.png)

**Comment by VaiTon** [comment]
Ok this is just for Foundation 6 so we fallback on `panel callout`
