### ISSUE TITLE
Products count in API item page is as a String

### ISSUE THREAD

**Issue by nicolasleger** [openfoodfacts/openfoodfacts-server#189]
The products count in an item API page is as a string instead of integer.
Examples:
- http://world.openfoodfacts.org/label/utz-certified.json
- http://world.openfoodfacts.org/category/baby-foods.json

However it is already an integer for item lists pages:
- http://world.openfoodfacts.org/labels.json
- http://world.openfoodfacts.org/categories.json

**Comment by stephanegigandet** [comment]
Fixed, thank you @nicolasleger !
