### ISSUE TITLE
Translated URLs not working (Italian)

### ISSUE THREAD

**Issue by VaiTon** [openfoodfacts/openfoodfacts-server#1895]
![image](https://user-images.githubusercontent.com/12072630/59117740-d4134d80-894e-11e9-880a-99bf25a49489.png)
Which translates to "Error: Invalid URL"
![image](https://user-images.githubusercontent.com/12072630/59117746-d83f6b00-894e-11e9-862f-2f5effda9550.png)

**Comment by stephanegigandet** [comment]
Will be solved by #1818
