### ISSUE TITLE
Translating the existing documentation to other languages

### ISSUE THREAD

**Issue by vanshikaarora** [openfoodfacts/openfoodfacts-server#1899]
**Description**
In the code for the documentation [here](https://github.com/openfoodfacts/openfoodfacts-server/tree/master/lang/) . The documentation must be available in most of the languages. However currently it is written in very few languages like English and French. 

**Describe the solution you'd like**
Begin with the task of converting the existing documentation into other languages as well.

**Comment by teolemon** [comment]
closing, the associated PR was merged
