### ISSUE TITLE
Perform OCR on all uploaded images

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#190]
- Perform OCR on all uploaded images, with Tesseract and/or Cloud Vision 
- Save them as txt (or json if cloud vision) files next to the image (with the same name)

**Comment by teolemon** [comment]
Use the same routine used for manual processing.

**Comment by teolemon** [comment]
https://github.com/pavelsr/moo-google

**Comment by raphael0202** [comment]
@teolemon Can be closed
