### ISSUE TITLE
Prevention - On the fly quality checks in the product edit form (javascript)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1905]
### What
Create on the fly quality check for the web

- [ ] Saturated fat > Total fat
- [ ] Sugar > Glucids

### Part of 
- #5538

**Comment by CharlesNepote** [comment]
I think it's easy to add to my power user extension. Thus we can test it before launching it. I can code it with functions so that it will be easy to integrate in Product Opener later.

**Comment by VaiTon** [comment]
@CharlesNepote any news? Can I start working on this?

**Comment by CharlesNepote** [comment]
@VaiTon adding too much controls/warnings can be risky: some people could stop without saving their work. It's the kind of work that we need to test in real conditions, during some weeks, before it gets ready for everyone.
So I would suggest two options:
* adding this feature to my Power User extension (which is a sort of sandbox to test new features): https://gist.github.com/CharlesNepote/f6c675dce53830757854141c7ba769fc (did you ever test it?)
* building your own Greasemonkey/Tampermonkey extension

Maybe, if it's possible, these controls could be shown *after* saving, on the confirmation screen.

**Comment by yuktea** [comment]
done, @jnsereko.

**Comment by jnsereko** [comment]
created a PR https://github.com/openfoodfacts/openfoodfacts-server/pull/8258
