### ISSUE TITLE
Create UUID contribution pages

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1912]
Create contribution pages for each anonymous UUID, so that we can easily track non-quality on a per-user basis.

/uuid/345675GDFESD4678546453237487RFXB

**Comment by VaiTon** [comment]
And how do we create that UUID?
From the IP?
From the session?

**Comment by hangy** [comment]
Isn't it just some text content of the comment provided by a few apps?

**Comment by teolemon** [comment]
yes it is @hangy

**Comment by teolemon** [comment]
Normally, all major apps now send this uuid, including the official one

**Comment by stephanegigandet** [comment]
We discussed this with @teolemon, a simpler alternative is to use the uuid as the user name when we compute the edit history and the fields editors_tags etc.

**Comment by stephanegigandet** [comment]
@teolemon : which apps send a UUID besides Yuka, and in which format?

**Comment by stephanegigandet** [comment]
Not very pretty, for the display I'm just going to put "yuka - user".

![image](https://user-images.githubusercontent.com/8158668/59964742-115a0c80-9505-11e9-870a-6a8da6e355ec.png)

**Comment by stephanegigandet** [comment]
That looks better I think. The actual UUID is in the URL.

![image](https://user-images.githubusercontent.com/8158668/59966175-a9adbc80-9518-11e9-8a42-874057e240e0.png)

**Comment by teolemon** [comment]
This is solved. Thanks @stephanegigandet
