### ISSUE TITLE
API returns a CO2 level when no computation is done

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1915]
https://world.openfoodfacts.org/api/v0/product/20211394.json?fields=environment_impact_level_tags

https://world.openfoodfacts.org/product/20211394/lasagne-alla-bolognese-italiamo
We get a CO2 value where there should be none

**Comment by VaiTon** [comment]
@stephanegigandet is this fixed?

**Comment by teolemon** [comment]
fixed @VaiTon @stephanegigandet
