### ISSUE TITLE
Compress all static assets

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#192]
Compressing resources with gzip or deflate can reduce the number of bytes sent over the network.
Enable compression for the following resources to reduce their transfer size by 702.6KiB (75% reduction).
(That’s the homepage)

> Compressing http://static.openfoodfacts.org/js/jquery-ui-1.11.4/jquery-ui.min.js could save 171.7KiB (73% reduction).
> Compressing http://static.openfoodfacts.org/foundation/js/foundation.min.js could save 154.8KiB (79% reduction).
> Compressing http://static.openfoodfacts.org/foundation/css/app.css could save 139.3KiB (87% reduction).
> Compressing http://static.openfoodfacts.org/foundation/js/vendor/jquery.js could save 53.4KiB (64% reduction).
> Compressing http://world.openfoodfacts.org/ could save 37.6KiB (75% reduction).
> Compressing http://static.openfoodfacts.org/js/jquery.fileupload.js could save 28.7KiB (77% reduction).
> Compressing http://static.openfoodfacts.org/js/jquery-ui-1.11.4/jquery-ui.css could save 26.4KiB (76% reduction).
> Compressing http://staticxx.facebook.com/connect/xd_arbiter.php?version=42 could save 22.4KiB (66% reduction).
> Compressing https://staticxx.facebook.com/connect/xd_arbiter.php?version=42 could save 22.4KiB (66% reduction).
> Compressing http://static.openfoodfacts.org/…on/foundation-icons/foundation-icons.css could save 15.5KiB (81% reduction).
> Compressing http://static.openfoodfacts.org/foundation/js/vendor/modernizr.js could save 6.5KiB (58% reduction).
> Compressing http://slack.openfoodfacts.org/iframe could save 5.7KiB (57% reduction).
> Compressing http://static.openfoodfacts.org/js/jquery.iframe-transport.js could save 5.5KiB (72% reduction).
> Compressing http://slack.openfoodfacts.org/slackin.js could save 4.6KiB (68% reduction).
> Compressing http://static.openfoodfacts.org/js/jquery.fileupload-ip.js could save 4.4KiB (71% reduction).
> Compressing https://platform.twitter.com/…tton.b059c0eb61ea902a882e5c5b3c66a17a.js could save 2.8KiB (65% reduction).
> Compressing http://static.openfoodfacts.org/js/load-image.min.js could save 720B (56% reduction).
> Compressing http://static.openfoodfacts.org/foundation/js/vendor/jquery.cookie.js could save 639B (46% reduction).

[https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Ffr.openfoodfacts.org%2F]

**Comment by Astronja** [comment]
And, did somebody help you compressing the resources? 
I don´t know what to do, and didn´t find anybody who help me with this issue in the w.w.w 
Durch die Komprimierung von https://staticxx.facebook.com/…t/xd_arbiter/r/bz-D0tzmBsw.js?version=42 könnten 21,6 KB (66 %) eingespart werden.

**Comment by hangy** [comment]
Except for 3rd party libraries (ie. Slack, Facebook, Twitter), this was implemented by Stephane when we moved to nginx by enabling nginx' gzip module.
