### ISSUE TITLE
Error when editing product

### ISSUE THREAD

**Issue by VaiTon** [openfoodfacts/openfoodfacts-server#1922]
![image](https://user-images.githubusercontent.com/12072630/59448047-aaea3580-8e04-11e9-9dcd-d6afe1c5e3ce.png)

**Comment by stephanegigandet** [comment]
Was this for an Italian product?

**Comment by VaiTon** [comment]
Yep

**Comment by stephanegigandet** [comment]
It's because the vitamins taxonomy had Italian entries with open parenthesis.

**Comment by stephanegigandet** [comment]
Fixed.
