### ISSUE TITLE
Use Minified version of CSS files

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#193]
> Minify CSS for the following resources to reduce their size by 7.3KiB (14% reduction).
> Minifying http://static.openfoodfacts.org/js/jquery-ui-1.11.4/jquery-ui.css could save 6KiB (18% reduction).
> Minifying http://static.openfoodfacts.org/…on/foundation-icons/foundation-icons.css could save 1.3KiB (7% reduction).

Those files are already on the server by the way. It's just calling the minified versions instead.

**Comment by teolemon** [comment]
http://static.openfoodfacts.org/js/jquery-ui-1.11.4/jquery-ui.min.css

**Comment by hangy** [comment]
Fixed for jquery by @teolemon in bc7bcf4edb2952b509a9dae96ff8a622eee44348, and foundation-icons by me in 68f8d6dbe595d6175f8fbd3feb0a0fc516e3b084.
