### ISSUE TITLE
Check that alcoholic beverages have alcohol ≥ 0

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1935]
Check that alcoholic beverages have alcohol ≥ 0

https://world.openfoodfacts.org/cgi/search.pl?action=process&tagtype_0=categories&tag_contains_0=contains&tag_0=alcoholic%20beverages&nutriment_0=alcohol&nutriment_compare_0=lte&nutriment_value_0=0&sort_by=unique_scans_n&page_size=20&axis_x=energy&axis_y=products_n&action=display

**Comment by VaiTon** [comment]
Any suggestion for the facet name?

**Comment by VaiTon** [comment]
@teolemon why also equal to 0?
