### ISSUE TITLE
Quality - Prevention - Add a checkbox  "Fiber is not specified on the product"

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#1938]
### What
In Europe, dietary fiber is often not specified on the product. This information is important because:
- fiber is necessary for Nutri-Score computation
- as of today, we count [297,392 products without fiber](https://world.openfoodfacts.org/misc/nutrition-no-fiber), even if it is not specified on the product; see https://world.openfoodfacts.org/product/3095759537010/lardons-j-aime-fumes-25-de-sel-fleury-michon?rev=32
- as of today, we say "Warning: the amount of fiber is not specified, their possible positive contribution to the grade could not be taken into account" even if the product has no fiber at all but we don't know it because fiber is not specified on the product

We should be able to precise that "fiber is not specified on the product".

Finally, I think this issue should be a high priority.

### Part of
- #5538

**Comment by stephanegigandet** [comment]
What difference will it make exactly if we have a checkbox "Fiber is not specified on the product" that is checked? I don't understand what we will do differently.

**Comment by VaiTon** [comment]
> What difference will it make exactly if we have a checkbox "Fiber is not specified on the product" that is checked? I don't understand what we will do differently.

Explicitly stating that the product is not missing any information that is specified on the package.

**Comment by CharlesNepote** [comment]
@stephanegigandet if we have a checkbox "Fiber is not specified on the product", the differences will be:
- https://world.openfoodfacts.org/misc/nutrition-no-fiber will not count products where fibers are not mentionned on the package
- https://world.openfoodfacts.org/misc/nutrition-no-fiber will allow us to complete products where fibers are mentionned on the package but not completed in the database
- we will not show "Warning: the amount of fiber is not specified, their possible positive contribution to the grade could not be taken into account" when fiber is not specified on the product; this is the job of producers to show fiber if there is some in their products: Open Food Facts is not accountable for that; the warning we show today doesn't make sense for MANY products who will never have fiber

**Comment by CharlesNepote** [comment]
As a first step, is it possible to allow to enter a "null" value, such as the hyphen (-). A null value would mean that it is not zero (0) but the information is not specified on the product.

What is interesting with this solution, is that it could be used for other fields.

A "null" value is also easier to parse by stat software such as R.

**Comment by CharlesNepote** [comment]
When I enter a hyphen (-) as a null value, it is converted in number "0". It shouldn't IMHO.

Example:
* https://fr.openfoodfacts.org/produit/4056489007180/pain-de-mie-special-sandwich-complet-maitre-jean-pierre
* => https://fr.openfoodfacts.org/api/v0/product/4056489007180.json

**Comment by stephanegigandet** [comment]
I think the safest thing would be to use the fiber_modifier field (which is a string) to indicate the "-" in it.

https://fr.openfoodfacts.org/api/v2/produit/5038862932417/boisson-d-avoine-innocent?fields=nutriments

This is what we have today:

fiber: 0.5,
fiber_100g: 0.5,
fiber_modifier: "<",
fiber_unit: "g",
fiber_value: 0.5,

all the other fields are numeric, so we can't return a "-", as many languages expect a specific type for each JSON field.

If the user inputs "-" as the value, then we would internally save only 1 field:

fiber_modifier: "-"

**Comment by CharlesNepote** [comment]
> I think the safest thing would be to use the fiber_modifier field (which is a string) to indicate the "-" in it.

Perhaps your answer is pragmatic, but IMHO it creates technical debt and enforce data consumers to manage this case.

JSON spec is very clear about the fact that `null` can be a value:
```
A value can be a string in double quotes, or a number, or true or false or nul`, or an object or an array. 
```
(source: https://www.json.org/ official JSON spec.)

I guess the majority of languages should be able to deal with the whole official JSON spec, even the `null` value:
* at least javascript -- see https://stackoverflow.com/a/21121267/4098096
* JSON perl module: https://metacpan.org/pod/release/MAKAMAKA/JSON-2.59/lib/JSON.pm#null
* python -- https://stackoverflow.com/questions/27140090/how-can-json-data-with-null-value-be-converted-to-a-dictionary
* and probably the vast majority of other languages (add yours ;-) ).

We could convert the "-" value, when entered by a user (or even by API) to a `null` value. We would have `fiber: null` only. I think it is more suitable in terms of logic and efforts: you only have to analyze one field to know if the value is `0` or `null` for example.

**Comment by stephanegigandet** [comment]
Using null is a possibility, but that means clients have to differentiate values that don't exists in the nutrient hash and values that are null.

> We could convert the "-" value, when entered by a user (or even by API) to a null value. 

The API does not currently accept JSON for input, so apps will need to convert the null values to - , null or none etc. when using the write API.

**Comment by stephanegigandet** [comment]
Another thing is that if we want to allow apps to send JSON data directly to the API (using PUT for instance), then if we use "null" for "no value specified", then we can't use it to allow apps to completely remove a value.
