### ISSUE TITLE
Send Cache-Control and ETag headers for Static Files

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#194]
Setting an expiry date or a maximum age in the HTTP headers for static resources instructs the browser to load previously downloaded resources from local disk rather than over the network.

Leverage browser caching for the following cacheable resources:

http://static.openfoodfacts.org/…n/foundation-icons/foundation-icons.woff (expiration not specified)
http://static.openfoodfacts.org/foundation/js/foundation.min.js (expiration not specified)
http://static.openfoodfacts.org/foundation/js/vendor/jquery.cookie.js (expiration not specified)
http://static.openfoodfacts.org/foundation/js/vendor/jquery.js (expiration not specified)
http://static.openfoodfacts.org/foundation/js/vendor/modernizr.js (expiration not specified)
http://static.openfoodfacts.org/js/canvas-to-blob.min.js (expiration not specified)
http://static.openfoodfacts.org/js/jquery-ui-1.11.4/jquery-ui.min.js (expiration not specified)
http://static.openfoodfacts.org/js/jquery.fileupload-ip.js (expiration not specified)
http://static.openfoodfacts.org/js/jquery.fileupload.js (expiration not specified)
http://static.openfoodfacts.org/js/jquery.iframe-transport.js (expiration not specified)
http://static.openfoodfacts.org/js/load-image.min.js (expiration not specified)

**Comment by hangy** [comment]
Fixed by c878e6d50e135d91cd8cd758a94bab424a97f51e or earlier.
