### ISSUE TITLE
Lack of information in (and about) revision pages

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#1945]
In revision pages, some informations are missing or hard to find:
- timestamp
- contributor name
- revision content (ex. `Selected images (Changed: nutrition_fr) - new image nutrition_fr : 25.72`)
- revision source
- the link to the last revision of the product

To find these informations you have to go to "Changes history" at the bottom and find which entry match to current revision (with mouse over "view" link).

Also, for a beginner, it's difficult to understand that this is an old version of the product.

Related to this issue, each "Changes history" entry is poor:
`<li><time datetime="2018-06-10T15:06:20">June 10, 2018 at 3:06:20 PM CEST</time> - <a href="/contributor/kiliweb">kiliweb</a> Nutriments (Changed: energy, fat, saturated-fat, proteins)  - (app)User : UUpsZkc3WUIvLzlSdmZZQndSZkY2K0p6ekxhcUF6bUdjN0UrSVE9PQ - <a href="/product/3095756220014/fleuron-de-canard-fleury-michon?rev=40">view</a></li>`

I suggest either or both:
- show these informations at the beginning of the page, in a way that clearly shows that this is an old revision; this informations should be presented with semantic code (example below)
- modify "Changes history" entries to let designers and coders better use "Changes history" informations

**Example of code for warning revision block**
```
<div id="rev_summary">
<span class="rev_warning">This page is an old revision this product.</span> 
Rev. <span class="rev_nb">40</span> 
produced on <time datetime="2018-06-10T15:06:20">June 10, 2018 at 3:06:20 PM CEST</time> 
by <a href="/contributor/kiliweb" class="rev_contributor">kiliweb</a>, 
who changed <span class="rev_changes">Nutriments (Changed: energy, fat, saturated-fat, proteins)</span> 
from source <span class="rev_source">(app)User : UUpsZkc3WUIvLzlSdmZZQndSZkY2K0p6ekxhcUF6bUdjN0UrSVE9PQ</span>.<br/>
Link to this revision: <a href="/product/3095756220014/fleuron-de-canard-fleury-michon?rev=40">view</a><br/>
Link to last revision: <a href="/product/3095756220014/fleuron-de-canard-fleury-michon">view</a>
</div>
```

**Example of Changes history entry**
```
<li id="rev_40" class="rev_set"><!-- <= add class="current" if it matches current revision -->
Rev. <span class="rev_nb">40</span> - 
<time datetime="2018-06-10T15:06:20">June 10, 2018 at 3:06:20 PM CEST</time> - 
<a href="/contributor/kiliweb" class="rev_contributor">kiliweb</a> 
<span class="rev_changes">Nutriments (Changed: energy, fat, saturated-fat, proteins)</span> - 
<span class="rev_source">(app)User : UUpsZkc3WUIvLzlSdmZZQndSZkY2K0p6ekxhcUF6bUdjN0UrSVE9PQ</span> - 
<a class="rev_link">href="/product/3095756220014/fleuron-de-canard-fleury-michon?rev=40">view</a>
</li>`
```

Solving this issue will help solve #1408.

**Comment by VaiTon** [comment]
![image](https://user-images.githubusercontent.com/12072630/59767930-ab227f00-92a3-11e9-9467-29a93005ba73.png)
This is how wikipedia does it

**Comment by CharlesNepote** [comment]
That's it @VaiTon! I think we could reuse nearly the same sentence. I guess we could use `<div class="panel callout">..............</div>` to do it?

Would you work on that @VaiTon? You're doing a great job and this would help to solve #1408.

**Comment by VaiTon** [comment]
Sure! 😄
