### ISSUE TITLE
Negative query pagination doesn't work

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1960]
world.openfoodfacts.org/country/-spain

Works well on first page, but then lost at 2nd page

**Comment by hangy** [comment]
It's not just the pagination that's a bit off. If you're on a country-specific part of OFF, the `-` is removed from the world link, too. Same for the 2nd level tag. Also, if you visit https://de.openfoodfacts.org/country/-spain, then you should be redirected to https://de.openfoodfacts.org/land/-spanien, not https://de.openfoodfacts.org/land/spanien.

The reason likely is that `$request_ref->{current_link}` and related fields are built using `ProductOpener::Tags::canonicalize_taxonomy_tag_link` and `ProductOpener::Tags::canonicalize_taxonomy_2tag_link` which don't know about `$request_ref->{tag_prefix}` and `$request_ref->{tag2_prefix}`.

**Comment by zigouras** [comment]
I can work on this one if you guys want to assign it to me.

**Comment by hangy** [comment]
That would be great, @zigouras! Would you mind checking if #2010 might be related, too?

**Comment by zigouras** [comment]
@hangy, sure I can look at #2010 too.

**Comment by zigouras** [comment]
I didn't see that `ProductOpener::Tags::canonicalize_taxonomy_2tag_link` was used anywhere.  Can it be deleted?

**Comment by zigouras** [comment]
I made a PR for this. Please test the fixed functionality in a local build first as there are a few pieces of code that were touched.
Part of the problem was that the original regex that tried to add back the tag prefix was not working.  There were other issues too.
I replaced this original regex:
`s/^\/([^\/]+)$/\/$prefix$1/;`
with my own in the function
`add_tag_prefix_to_link`
and added some tests to validate the new function.

**Comment by stephanegigandet** [comment]
> I didn't see that `ProductOpener::Tags::canonicalize_taxonomy_2tag_link` was used anywhere. Can it be deleted?

Yes.

**Comment by stephanegigandet** [comment]
Thanks a lot for the fix @zigouras , I tested it on the dev server https://fr.dev.openfoodfacts.org/pays/-belgique (login and pass: off), and everything looks fine.

The negative tags are not currently supported for the 2nd tag, but that's a different issue. I just opened https://github.com/openfoodfacts/openfoodfacts-server/issues/2285

**Comment by stephanegigandet** [comment]
Thanks @zigouras, it is now in production.
