### ISSUE TITLE
[multilingual products] Products in multiple languages

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#197]
New set of features to handle products that have more than one language on their package.

Specs and design: http://en.wiki.openfoodfacts.org/Project:Multilingual_products

This bug is to track the overall implementation process. You can create "sub bugs" for individual issues.

Discussion on Slack: use the #multilingualproducts channel.

**Comment by aleene** [comment]
Is this still a valid issue? Seems to be done.

**Comment by stephanegigandet** [comment]
Done! :)
