### ISSUE TITLE
In edit mode, provide a link to get back to product view without saving

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#1973]
When we edit a product, we don't know how to get back to view mode. It's possible with the "back" button of the browser but not everybody knows that.

To get back, some people save without any modification (which save an empty entry in the changelog).

**Suggestions**
- First of all, we shouldn't save a modification without changes.
- We could have something in the interface to let the user get back to the product view; ideally, if the user made some changes, this link would prevent to leave the page without saving

**Comment by VaiTon** [comment]
The back button has been implemented however it doesn't check for any modifications before returning to the product page.

**Comment by stephanegigandet** [comment]
This has been fixed by @VaiTon and deployed, closing.
