### ISSUE TITLE
Missing CORS headers on cgi/product_jqm2.pl endpoint

### ISSUE THREAD

**Issue by alemit** [openfoodfacts/openfoodfacts-server#1977]
As a public API the endpoints responsible for creation of different resources MUST return CORS headers - ref. [https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)

**Expected behavior**
At least "Access-Control-Allow-Origin: *" value is expected as a header

**Comment by cvettelina** [comment]
I'm also interested in the topic

**Comment by alemit** [comment]
Guys are there some progress on this? It sounds like 5 minute bugfix but now it is part of the 700+ bugs.
