### ISSUE TITLE
Auto rotate ingredient and nutrition images

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#1991]
Yuka and other apps are sending a lot of images that are badly rotated.
This feature is to run all selected ingredients and nutrition images through Google Cloud Vision, and then to analyze the text blocks coordinates to compute the orientation of each image.

We can then autorotate the images that have an incorrect orientation.

It may be too slow to do this in real time when images are uploaded, but we can do it in batch mode on already uploaded and selected images.

**Comment by teolemon** [comment]
@raphael0202 has been working on that.

**Comment by teolemon** [comment]
Google announced this morning that it will be in their API by the end of August

**Comment by teolemon** [comment]
https://github.com/openfoodfacts/openfoodfacts-ai/issues/31

**Comment by stephanegigandet** [comment]
Deployed, applied on the products edited by kiliweb.
