### ISSUE TITLE
Please don't introduce backwards incompatible changes to the public APIs

### ISSUE THREAD

**Issue by cvettelina** [openfoodfacts/openfoodfacts-server#1993]
Hello,
As you are exposing public APIs that people integrate with you should not introduce backwards incompatible changes to the APIs as this breaks our integrations in unexpected ways.

The common rules usually followed are:
- don't add new required parameters
- don't introduce new HTTP codes
- don't change the format of the request and response
- don't remove parameters from the response

If any of the above changes should be done than you should bump the API version for example 
from v0/api you may go to v1.0/api
Both version 0 and 1.0 should co-exist unless you are absolutely sure that no one is using the old version anymore.

Please consider the following the common practices listed above for all future improvements of the API.

Note: for example Today I started receiving 404 instead of 200 when product is not found (which is totally correct from API point of view), however this is interpreted as an exception as it's not an expected status code and requires code changes.

**Comment by teolemon** [comment]
Hi @cvettelina We're working on a solution. We also broke the official Open Food Facts client in the way. Can you join us on the OFF slack ? https://slack.openfoodfacts.org

**Comment by stephanegigandet** [comment]
Sorry about that, the 404 is now returned only for version equal or above 1.
