### ISSUE TITLE
Strings instead of numbers for ingredients_n break graphs with ingredients as one axis

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#2002]
https://world.openfoodfacts.org/cgi/search.pl?action=process&tagtype_0=categories&tag_contains_0=contains&tag_0=fr%3Aglaces&sort_by=unique_scans_n&page_size=20&axis_x=additives_n&axis_y=ingredients_n&series_nutrition_grades=on&graph=1

**Comment by hangy** [comment]
It's not "graphs" that are broken, but that specific graph. For example, https://world.openfoodfacts.org/cgi/search.pl?action=process&nutriment_0=energy&nutriment_compare_0=gt&nutriment_value_0=2000&sort_by=unique_scans_n&page_size=20&axis_x=energy&axis_y=fat&graph=1 works.

**Comment by stephanegigandet** [comment]
Some products (not all) seem to have a string for ingredients_n, fixing.
