### ISSUE TITLE
[multilingual products] Style the language tabs in the multilingual product edit form

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#202]
Currently not clear where the language-specific tab content starts and ends.

**Comment by stephanegigandet** [comment]
Very ugly styling (border and padding) added so that we can see where tabs start and end.

Example: http://world.openfoodfacts.net/cgi/product.pl?type=edit&code=0056800528015
(login and password: off )

TODO: Find someone who can style the tabs.

**Comment by stephanegigandet** [comment]
I could not find any volunteer to style the tabs, so I did it myself. You had been warned. ;-)

**Comment by aleene** [comment]
Not able to log in

**Comment by stephanegigandet** [comment]
@aleene: I refreshed the users base on openfoodfacts.net (it had a stale copy), can you try to log in again?

**Comment by aleene** [comment]
Does not work wiith off off

**Comment by stephanegigandet** [comment]
off off is for accessing the password protected openfoodfacts.net web site (just to read it). Then you can login (e.g. to edit product) with your regular OFF account.
