### ISSUE TITLE
Prevent circular references in taxonomies, causes infinite loop

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#2020]
There is currently a circular reference in the ingredients taxonomy:

<en:oat
<en:oat flakes
en:oat flakes, rolled oat flakes

This causes an infinite loop in the get_inherited_property() function.

**Comment by aleene** [comment]
Can happen. Maybe another test to add?

**Comment by stephanegigandet** [comment]
@aleene : that's what the commit above does, the taxonomy build will fail, and there will be error messages like "XYZ cannot be a parent of itself".

I'm also going to check in modified versions of the taxonomies to remove the circular references.

**Comment by VaiTon** [comment]
Fixed with #2020 e6e6947
