### ISSUE TITLE
Compute and display stats of known / unknown tags in each taxonomy and how many products are associated with them

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#2028]
I'm planning to compute stats when we display lists of tags like https://fr.dev.openfoodfacts.org/editeur/scamark/ingredients `

Those queries already have the data we need: all the different tags, whether they exist in the taxonomy or not, and how many products have them.

		my %stats = (
			all_tags => 0,
			all_tags_products => 0,
			known_tags => 0,
			known_tags_products => 0,
			unknown_tags => 0,
			unknown_tags_products => 0,
		);

Then we can have a special ?stats=1 parameter to display the stats (and ?only_stats=1 ) to display just the stats and not the huge data table with all the entries.

**Comment by VaiTon** [comment]
Fixed by #2029
