### ISSUE TITLE
Ingredients parsing fails

### ISSUE THREAD

**Issue by alemit** [openfoodfacts/openfoodfacts-server#2032]
During ingredients parsing with Tessaract OCR the call fails with the following:
https://world.openfoodfacts.org/cgi/ingredients.pl?code=3800139143855&id=ingredients_en&process_image=1&ocr_engine=tesseract

Content:

```<h1>Software error:</h1>
<pre>Undefined` subroutine &amp;ProductOpener::Images::get_ocr called at /srv/off/lib/ProductOpener/Images.pm line 1467.

</pre>
<p>
For help, please send mail to the webmaster (<a href="mailto:contact@openfoodfacts.org">contact@openfoodfacts.org</a>), giving this error message 
and the time and date of the error.

</p>
```

Headers:
content-length:"345"
content-type:"text/html; charset=iso-8859-1"
date:"Sun, 30 Jun 2019 09:09:02 GMT"
okhttp-response-source:"NETWORK 500"
okhttp-selected-protocol:"h2"
server:"nginx/1.10.3"

Using the Google OCR success rate is less than 20%. Only one of each 5 calls is successful. All other calls with the same product/ingredients picture end up with data {status:1}.

**Comment by stephanegigandet** [comment]
Hi @alemit, Google OCR is rate limited, are you making many requests to ingredients.pl? If so, we need to coordinate.

**Comment by alemit** [comment]
@stephanegigandet can give me more information about this rate limiting? How many request/time I'm able to make?

**Comment by stephanegigandet** [comment]
I fixed the Tesseract bug.

@alemit : well what is your use case? The ingredients.pl is intended for the OFF app to extract ingredients when users upload photos. It should not be used for automated queries. What are you using it for?

**Comment by alemit** [comment]
Thanks for the fix ☺
@stephanegigandet we are manually adding products through the API and the call of ingredients.pl is again manual - on demand. It is not part of an automated process.

**Comment by stephanegigandet** [comment]
@alemit : perfect, it's all good then. Can you tell me who is "we"? Are you making an app? If so please tell us which app it is. Thanks!
