### ISSUE TITLE
Quality facet - "quantity-contains-e" has many false positives

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#2037]
### What
See: https://world.openfoodfacts.org/quality/quantity-contains-e

Example: "1 litre" in https://world.openfoodfacts.org/product/3464660002434/jus-d-aloe-vera-pur-aloe

The regexp recognize too much things: https://github.com/openfoodfacts/openfoodfacts-server/blob/aa25a7eb248399d5d61e6e90a221f74d35ff32ce/lib/ProductOpener/SiteQuality_off.pm#L747

I replaced:
- `/(?:.*e$)|(?:[0-9]+\s*[kmc]?[gl]?\s*e)/i` by
- `/(?:^e\s)|(?:\se[^a-z])|(?:\se$)/i`

And it deleted more than 1500 false positives (see file attached).

[4.txt](https://github.com/openfoodfacts/openfoodfacts-server/files/3343075/4.txt)

### Part of
- #5538

**Comment by stephanegigandet** [comment]
I agree that the regexp is broken, but the proposed change also delete true positives.

What we really want to identify is cases like this:

500 ge

**Comment by VaiTon** [comment]
In the first place, why do we want to identify quantities containing "e"? @stephanegigandet

**Comment by benbenben2** [comment]
See: (https://world.openfoodfacts.org/quality/quantity-contains-e) -> https://world.openfoodfacts.org/data-quality-info/en:quantity-contains-e

For the aforementioned example, see also from the API: https://world.openfoodfacts.org/api/v2/search?code=3464660002434

The aforementioned line of code can now be found in /lib/ProductOpener/SiteQuality_off.pm

Finally, to find more examples: 
https://mirabelle.openfoodfacts.org/products?sql=select+quantity+from+%5Ball%5D%0D%0AWHERE+quantity+%21%3D+%22%22+AND+quantity+LIKE+%22%25e%25%22%0D%0ALIMIT+100

**Comment by stephanegigandet** [comment]
> In the first place, why do we want to identify quantities containing "e"? @stephanegigandet

That's a  good question. :) (sorry @VaiTon I missed it 4 years ago).

The symbol is present on most products, I didn't see the point in including it in the quantity field.

**Comment by benbenben2** [comment]
Should we close this issue @CharlesNepote?
