### ISSUE TITLE
[multilingual products] Create new languages tags to give info on languages used on the product package

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#205]
Similar to http://world.openfoodfacts.org/codes but for languages on the package.

Values:
- 0, 1 or more [language code] -> indicates that a language is used on the package (e.g. "fr" + "nl")
- [n] -> indicates the number of languages used (e.g. 2 for "fr" + "nl")
- multi -> indicates more than one language is used

**Comment by stephanegigandet** [comment]
New fields "languages" and "languages_tags" have been created.

They can currently only be seen through the API:

http://world.openfoodfacts.net/api/v0/product/0056800528015/danone
"languages_tags":["en","es",2,"multi"], "languages":{"en":1,"es":1}

The languages_tags need to be searchable through URLs facets, like codes and other tags.

**Comment by aleene** [comment]
Why two fields? Not happy with the tags implementation. [...] should be an array of similar items. Create a {..} if you want to add other elements, but with a key.

**Comment by stephanegigandet** [comment]
The field "languages" is a hash to make implementation easier, but you can just look at the keys and you will get an array.

The field "languages_tags" is used by facets (e.g. urls like /languages/nl or /languages/multi or /languages/3). It is used to see products that have a given language, more than one language, or a given number of languages (3 in my example). It's the same mechanism that we use on all other fields, the XYZ field contains the actual value, and the XYZ_tags is for MongoDB and url / facets search.

**Comment by stephanegigandet** [comment]
The languages_tags field will be very similar to the countries_tags field. It will use the new languages taxonomy (bug #237).

**Comment by aleene** [comment]
OK, I read it as a json syntax.

**Comment by stephanegigandet** [comment]
Deployed a long time ago.
