### ISSUE TITLE
Inconsistency in csv-export

### ISSUE THREAD

**Issue by cutterkom** [openfoodfacts/openfoodfacts-server#206]
When I am seaching, e.g. for Müsli (German for cereals) and I export the data as a csv file (http://de.openfoodfacts.org/cgi/search.pl?search_terms=m%C3%BCsli&search_simple=1&action=process), the data is shifted two cells to the left. I seems as it starts at the variable `image_nutrition_url`, where the data seems to belong to `energy_100g`.

The problem can be replicated with other search terms.

**Comment by stephanegigandet** [comment]
Thanks for reporting the bug, it's fixed.
