### ISSUE TITLE
Add Robotoff id parsing

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#2061]
Add Robotoff id parsing
(automated edit, ID: d6c074ba-91f2-49ce-b291-632ef38b11d2)

**Comment by hangy** [comment]
What do you want to do with the `insight_id`? It will only ever be used in one edit.

**Comment by teolemon** [comment]
Ah my bad, I thought that was a user_id

**Comment by hangy** [comment]
Robotoff doesn't have a `user_id` AFAIK. 🙂
