### ISSUE TITLE
query error: bad skip value in query at /home/off-fr/cgi//Blogs/Display.pm line 2279.

### ISSUE THREAD

**Issue by TaciteOFF** [openfoodfacts/openfoodfacts-server#207]
This URL returns a software error

query error: bad skip value in query at /home/off-fr/cgi//Blogs/Display.pm line 2279.

http://fr.openfoodfacts.org/3095756213016

**Comment by stephanegigandet** [comment]
Where does this URL come from? It's is interpreted as the URL for page 3095756213016 of all products. Which MongoDB does not like. The limit for the number of pages is around 37450562130.

**Comment by stephanegigandet** [comment]
The error is gone (maybe because of a mongodb or mongodb driver update).
