### ISSUE TITLE
Ingredient cutting issue in Polish

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#2096]
![image](https://user-images.githubusercontent.com/1689815/61172120-8955a880-a580-11e9-9e95-b3f886bd9187.png)
https://world.openfoodfacts.org/cgi/product.pl?type=edit&code=4022993045246

**Comment by teolemon** [comment]
The word ingredient is repeated a second time for *biologic ingredients
Unsure if the first one is properly parsed

**Comment by stephanegigandet** [comment]
Fixed by https://github.com/openfoodfacts/openfoodfacts-server/pull/2876
