### ISSUE TITLE
"béta - carotène" and "choux - fleurs" are parsed as two ingredients.

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#2119]
**Describe the bug**
"béta - carotène" is parsed into two words.

**To Reproduce**
https://world.openfoodfacts.org/editor/systeme-u/ingredient/fr:beta

**Comment by aleene** [comment]
choux - fleurs as well https://world.openfoodfacts.org/editor/systeme-u/ingredient/fr:fleurs

**Comment by stephanegigandet** [comment]
Fixed and deployed.
