### ISSUE TITLE
Implement autocomplete suggestions for tags fields (e.g. labels, categories etc.)

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#213]
Currently we use this plugin to separate tags:
https://github.com/xoxco/jQuery-Tags-Input

It would be very useful to have some kind of autocomplete suggestions, especially for categories.

This would require two things:
1. add some client javascript / jquery plugin to display tag suggestions (need to be by tag, not the whole input field)
2. create an API on the backend to retrieve tags suggestions given the first characters (in particular for big / huge taxonomies like categories which can't be retrieved by the browser completely).

**Comment by stephanegigandet** [comment]
From the Tags Input plugin, it seems to work with jquery autocomplete:

If you want to use jQuery.autocomplete, you can pass in a parameter with the autocomplete url.

$('#tags').tagsInput({
  autocomplete_url:'http://myserver.com/api/autocomplete'
});
If you're using the bassistance jQuery.autocomplete, which takes extra parameters, you can also send in options to the autocomplete plugin, as described here.

$('#tags').tagsInput({
  autocomplete_url:'http://myserver.com/api/autocomplete',
  autocomplete:{selectFirst:true,width:'100px',autoFill:true}
});

**Comment by stephanegigandet** [comment]
Probably useful: http://api.jqueryui.com/autocomplete/#option-source

**Comment by TaciteOFF** [comment]
Will try to do something, at least for categories :)

**Comment by stephanegigandet** [comment]
Implemented a very dumb suggestion server for any taxonomy:

http://world.openbeautyfacts.org/cgi/suggest.pl?lc=fr&tagtype=ingredients&string=be
http://world.openbeautyfacts.org/cgi/suggest.pl?lc=fr&tagtype=categories&string=sh

Returns json, works with textcomplete.

**Comment by lucaa** [comment]
I have prepared the code that adds suggestions to a textarea using textcomplete and the service provided by stephane, find it here 
[autocomplete_ingredients_10_03_2016.tar.gz](https://github.com/openfoodfacts/openfoodfacts-server/files/241321/autocomplete_ingredients_10_03_2016.tar.gz)

**Comment by lucaa** [comment]
However, I think the service that Stephane prepared needs to be improved to suggest all the values that can appear on a label, not only the values from the taxonomy. The idea is that the user should be able to find in these suggestions exactly what is written on the label so that they can fill in fast, without having to know the synonyms. 

For example, the service does not return "aqua": http://world.openbeautyfacts.org/cgi/suggest.pl?lc=fr&tagtype=ingredients&string=a .

**Comment by hangy** [comment]
For OpenFoodFacts, using the existing taxonomy would be a good start, but considering that (at leat for the EU), a lot of ingredients of cosmetics are described in [INCI](https://en.wikipedia.org/wiki/International_Nomenclature_of_Cosmetic_Ingredients) terms, which consist of mixed scientific, Latin and English names, a special use case may be required. For example, the `name:inci:en:` value could always be included in the suggestion for OBF, disregarding the selected `lc`.

**Comment by lucaa** [comment]
Fix was pushed as 501158ad618226c691a35a7e41088be2af974605 in the openbeautyfacts branch and was deployed on openbeautyfacts.org . 

The fix only includes suggestions for elements that have tags fields (therefore no ingredients) and which use a taxonomy: Categories, Labels, Period of time after opening, Countries where sold . 

I will open a new ticket for ingredients, as it's a different type of functionality.
