### ISSUE TITLE
Add "no image" icon to products with no front image

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#2131]
Suggestion from Max Bredow, see: https://openfoodfacts.slack.com/archives/C02L4H55V/p1564144835002700

> I'm new to this group but I have a suggestion:
When browsing through the page, I was curious what all these colours mean and why pacman (or is it a pie?). Only after a while I realized that it's completely random. This completely takes away focus from the CTAs.I propose a less beautified but more logic design to help the user differentiate between important information (such as the NutriScore or NOVA rating) and information that the user can disregard (colours? pacman?)

![image](https://user-images.githubusercontent.com/562352/62382132-41a5b980-b54d-11e9-9a84-fed3c5b0f016.png)

**Comment by stephanegigandet** [comment]
We now have grey boxes in place of the colored Pac-Mans.

**Comment by VaiTon** [comment]
I would like to reopen this issue because I think grey boxes are somehow misplacing. In my opinion they should have some kind of symbol inside.
What do you think @stephanegigandet @CharlesNepote ?

**Comment by CharlesNepote** [comment]
The grey boxes are really an improvement. Though, I agree with you @VaiTon because they don't mean anything: we don't know if it's an error, or if it means that the products aren't sold anymore, or what else.

I would also prefer a meaningful symbol with a clear statement. I thought we already talked about symbol such as this one (but in a grey version): https://www.svgrepo.com/svg/208839/no-pictures-no-camera
![image](https://user-images.githubusercontent.com/562352/69575791-3e867b80-0fcb-11ea-8c9f-d9f21c3ccfe6.png)

**Comment by stephanegigandet** [comment]
It might be personal taste, but I really don't like the striked camera icon. It looks like an forbidden sign. The meaning is not that clear to me: it could be interpreted in different ways, like "we don't have the right to display a picture". Same thing for a question mark icon: it can be interpreted in different ways. Not showing a picture seems clearer to me.

**Comment by VaiTon** [comment]
What about a question mark? @stephanegigandet

**Comment by stephanegigandet** [comment]
Well a question mark just raises a question... Does it mean we are not sure about something about the product?
If we really must put something, my personal preference would be to put a silhouette of a product, just like on social media sites: if there's no picture of someone, they show a silhouette of a face with no distinctive feature.

e.g. here is something I just drew:

![image](https://user-images.githubusercontent.com/8158668/69673773-63e2ba80-109b-11ea-92b1-44d224a8727b.png)


[jar-silhouette.zip](https://github.com/openfoodfacts/openfoodfacts-server/files/3894066/jar-silhouette.zip)

**Comment by CharlesNepote** [comment]
I understand your concern @stephanegigandet and find your icon very interesting. I was wondering if your silhouette doesn't lead our minds to something that the product is not. May be a grey barcode could be more "neutral".

And also IMHO the grey should be more light.

**Comment by stephanegigandet** [comment]
@VaiTon : We had a discussion in Slack in the #design channel: https://openfoodfacts.slack.com/archives/C02L4H55V/p1574849428028600

The consensus is to use a light blue icon with a product silhouette. I'm attaching a SVG for it.

At a later point, we may introduce different silhouettes based on product categories etc. but for now let's put this one.

[jar-silhouette-white-on-light-blue.zip](https://github.com/openfoodfacts/openfoodfacts-server/files/3896587/jar-silhouette-white-on-light-blue.zip)
