### ISSUE TITLE
Fleury Michon bad front picture

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#2135]
All front pictures imported on july 25th are bad (dozen of products), see: https://world.openfoodfacts.org/editor/fleury-michon/4

**Comment by stephanegigandet** [comment]
The images sent by the producers are good, and I was able to upload them manually. I do not know what happened, maybe a transient error (e.g. not enough memory or something) that caused the image processing to fail in the middle.

I'm updating the import script so that we can put back the good images.

**Comment by stephanegigandet** [comment]
Original cause not identified, but products fixed.

**Comment by stephanegigandet** [comment]
Images are broken again. Only the top of the image is seen, and not up to the exact same position as last time...

**Comment by stephanegigandet** [comment]
![image](https://user-images.githubusercontent.com/8158668/62777450-dbb9b480-baad-11e9-8f0a-f360f1eda50a.png)

**Comment by stephanegigandet** [comment]
Probably a bug in ImageMagick, it fails even when using mogrify from the command line:

mogrify -background White -alpha Background -format jpg download/08032413630316_A1C1_s03.png
mogrify: Premature end of JPEG file `download/08032413630316_A1C1_s03.png' @ warning/jpeg.c/JPEGWarningHandler/396.
mogrify: Corrupt JPEG data: premature end of data segment `download/08032413630316_A1C1_s03.png' @ warning/jpeg.c/JPEGWarningHandler/396.

**Comment by stephanegigandet** [comment]
mogrify -version
Version: ImageMagick 7.0.8-34 Q16 x86_64 2019-03-18 https://imagemagick.org
Copyright: © 1999-2019 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP
Delegates (built-in): bzlib djvu fontconfig freetype gvc jbig jng jp2 jpeg lcms lqr lzma openexr png tiff wmf x xml zlib

**Comment by stephanegigandet** [comment]
the images now received from fleury michon now seem to be jpg files:

 identify download/08032413630316_A1C1_s03.png
download/08032413630316_A1C1_s03.png JPEG 2400x2400 2400x2400+0+0 8-bit sRGB 68599B 0.000u 0:00.000


broken jpeg files though.

**Comment by stephanegigandet** [comment]
It seems to be a download error, sometimes only part of the file is retrieved.

One way to solve this could be to try to detect broken images and deleting them.

e.g.

convert test.jpg NULL
convert: Premature end of JPEG file `test.jpg' @ warning/jpeg.c/JPEGWarningHandler/396.
convert: Corrupt JPEG data: premature end of data segment `test.jpg' @ warning/jpeg.c/JPEGWarningHandler/396.

**Comment by stephanegigandet** [comment]
Added a script that deletes images that are corrupted (not downloaded completely).
