### ISSUE TITLE
Issue with editor reported by pyrka

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#2137]
``` 
Edytor w przeglądarce posiada poważny błąd! Nie można nawet podejrzeć, zrewertować zmian jakie się dokonały podczas zmiany obrazka w tym przypadku dla języka bułgarskiego.
``` 
https://world.openfoodfacts.org/product/5449000131805/coca-cola-zero

**Comment by stephanegigandet** [comment]
"The editor in the browser has a serious error! You can not even see, change the changes that took place when changing the picture in this case for the Bulgarian language."

**Comment by stephanegigandet** [comment]
Everything looks good to me on https://bg.openfoodfacts.org/product/5449000131805/coca-cola-zero , can you ask the reporter for clarification @teolemon?

**Comment by stephanegigandet** [comment]
Closing, please reopen if we get more info.
