### ISSUE TITLE
Testing broken external URLs

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#2141]
https://www.perlmonks.org/?node_id=801302

**Comment by stephanegigandet** [comment]
Not sure what this bug is about, but an automated script crawling OFF to find broken links is a bad idea imho. This probably should be done on the po files instead. It would be a feature request though, not a bug.

**Comment by hangy** [comment]
Do we have that many dead outgoing links? Testing that during continuous integration scenarios has the disadvantage that the availability of external links can (and will) change without notice. It could detect typos or other mistakes for a PR, but how big would the impact actually be (compared to the effort required to implement the tests efficiently)?

**Comment by stephanegigandet** [comment]
I guess it could be a test we could run from time to time (e.g. once a year), but I agree that it should not be a continuous integration test. The builds are long enough already without having to wait for http servers to reply. :) (I'm not sure if we can actually make outgoing http requests in travis, that sounds dangerous in fact).

**Comment by teolemon** [comment]
Closing
