### ISSUE TITLE
Vegetable oil vs Vegetal oil

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#2148]
We are using Vegetal oil instead of Vegetable oil in the NOVA page
<li><a href="https://world.openfoodfacts.org/ingredient/en:vegetal-oil">vegetable oil</a></li>

**Comment by swetankraj** [comment]
Could you please elaborate on the problem?

**Comment by teolemon** [comment]
It was a typo in the methodology text of the NOVA groups on food processing, that I have fixed. Sorry for the cryptic issue @swetankraj , and thanks for your vigilance :-)
