### ISSUE TITLE
Lossless compression of images

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#216]
> Losslessly compressing http://static.openfoodfacts.org/…-on-google-play-en_app_rgb_wo_135x47.png could save 4.1KiB (47% reduction).
> Losslessly compressing http://static.openfoodfacts.org/…ble_on_the_App_Store_Badge_EN_135x40.png could save 3.8KiB (64% reduction).
> Losslessly compressing http://static.openfoodfacts.org/…s/misc/openfoodfacts-logo-en-178x150.png could save 2.3KiB (23% reduction).
> Losslessly compressing http://static.openfoodfacts.org/images/misc/154x40_WP_Store_blk.png could save 797B (50% reduction).

**Comment by teolemon** [comment]
We could also investigate doing so with the whole base

> Losslessly compressing http://static.openfoodfacts.org/…/314/292/002/6481/ingredients.11.200.jpg could save 14.5KiB (66% reduction).
> Losslessly compressing http://static.openfoodfacts.org/…/314/292/002/6481/ingredients.11.400.jpg could save 14.5KiB (41% reduction).
> Losslessly compressing http://static.openfoodfacts.org/…314/292/002/6481/ingredients.11.full.jpg could save 14.5KiB (15% reduction).
> Losslessly compressing http://static.openfoodfacts.org/…roducts/314/292/002/6481/front.5.200.jpg could save 13.5KiB (42% reduction).
> Losslessly compressing http://static.openfoodfacts.org/…roducts/314/292/002/6481/front.5.400.jpg could save 13.5KiB (17% reduction).
> Losslessly compressing http://static.openfoodfacts.org/…oducts/314/292/002/6481/front.5.full.jpg could save 13.5KiB (2% reduction).

**Comment by teolemon** [comment]
Would have a positive impact on the Mobile App load times.

**Comment by hangy** [comment]
Should be fixed for normal images in #725, product images are tracked in #648. 😄
