### ISSUE TITLE
Delete empty products

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#2167]
Today we have more than 33,000 empty products: https://world.openfoodfacts.org/state/empty

These products only have a barcode and nothing else.

I think it could be better to delete them because:
* it produces false statistics (number of products, quality stats...)
* I think it's better to ask for adding a non existing product, than completing an empty one

Some users may create empty products to remind them to complete the product. But there is probably no reason to keep a product older than a few days or weeks.

**Comment by hangy** [comment]
There's [remove_empty_products.pl](https://github.com/openfoodfacts/openfoodfacts-server/blob/a96d311a29f77671db885e69aeec7abc1c412850/scripts/remove_empty_products.pl), which used to be run daily from a crontab. Maybe this got lost during the server transition?

**Comment by teolemon** [comment]
Indeed. @stephanegigandet is going to set up the cron again.

**Comment by stephanegigandet** [comment]
Fixed, can someone review the pull request? https://github.com/openfoodfacts/openfoodfacts-server/pull/2173
