### ISSUE TITLE
Quality facet - ingredient % over 100

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#2168]
### What
`Purée 404% (pomme de terre 20,5%, carotte 141%, eau, crème fratche (lait), sel, fibres de lin), eau, boulettes de viande bovine cutes 228% (viande bovine (Oriqine France), eau, fécule de tapioca, sel), tomate 116%, échalotes, fibres de lin, huile de colza, concentré de tomate, sel.`

Anything over 100% should be flagged as it is an OCR error.

### Code pointer
 lib/ProductOpener/DataQuality*.pm

### Part of
- #5538

**Comment by stephanegigandet** [comment]
relevant file: lib/Producers/SiteQuality_off.pm

**Comment by manwar** [comment]
> relevant file: lib/Producers/SiteQuality_off.pm

You mean lib/ProductOpener/SiteQuality_off.pm ?

**Comment by stephanegigandet** [comment]
@manwar yes, thank you

**Comment by matheus-de** [comment]
Will work on this issue

**Comment by stephanegigandet** [comment]
@matheus-de : the relevant files are now lib/ProductOpener/DataQuality*.pm
