### ISSUE TITLE
Investigate 3rd party CDN use

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#217]
### What
- Some JS librairies and CSS are proposed by 3rd party CDNs with far better latency than Open Food Facts.
- This can reduce load time.
- Candidates are jQuery, Foundation and associated libs.
### Part of
- #8764

**Comment by teolemon** [comment]
jQuery on a CDN: 108 ms
jQuery on Open Food Facts: 873 ms

**Comment by teolemon** [comment]
Plus it has the advantage of being cached among websites.

**Comment by stephanegigandet** [comment]
But then Google complains of too many requests to too many different hosts...
An alternative is to do what I did on http://recettes.de/cuisine : just concatenate modernizer, jquery, foundation etc. in one single JS file, and make sure it can be served compressed.

**Comment by teolemon** [comment]
+1, plus it has privacy advantages.
How do you serve static files ? From the Apache or a CDN.
If from Apache, modespeed will provide compression and added speed
https://developers.google.com/speed/pagespeed/module/download

**Comment by raphael0202** [comment]
resources (JS, CSS) are cached by browser the first time the website is loaded, so I don't think it's really an issue.
