### ISSUE TITLE
Ingredient parsing issue for Spanish

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#2170]
`Vinagre, chile rojo y sal.`is not properly parsed while `Vinagre, chile rojo, sal` is.

**Comment by stephanegigandet** [comment]
That's because "chile rojo" is not in the taxonomy yet.
This how the parsing works:
if "A and B" is an entry in the taxonomy, assign it. Otherwise, if both A and B are known entries, convert "A and B" to "A, B".
I will add "chile rojo" to the taxonomy.

**Comment by stephanegigandet** [comment]
Fixed and deployed (although I don't know which product it is, so it might need reparsing)
