### ISSUE TITLE
Many food additions are not recognized.

### ISSUE THREAD

**Issue by Slawek234** [openfoodfacts/openfoodfacts-server#2177]
Many food additions are not recognized.
Examples
1. https://pl.openfoodfacts.org/product/5904277900566/kiełbasa-wieprzowa-z-dodatkiem-mięsa-wołowego-salami-z-pieprzem-konecke  - R̶e̶c̶o̶g̶n̶i̶z̶e̶d̶:̶ ̶E̶2̶0̶2̶,̶ ̶n̶o̶t̶ ̶r̶e̶c̶o̶g̶n̶i̶z̶e̶d̶:̶ ̶E̶3̶0̶1̶,̶ ̶E̶1̶2̶0̶,̶ ̶E̶2̶5̶0̶
2. https://pl.openfoodfacts.org/product/5900562001147/wieprzowina-w-sosie-wlasnym-sokołow - 
R̶e̶c̶o̶g̶n̶i̶z̶e̶d̶:̶ ̶E̶4̶5̶0̶,̶ ̶n̶o̶t̶ ̶r̶e̶c̶o̶g̶n̶i̶z̶e̶d̶:̶ ̶g̶l̶u̶t̶a̶m̶i̶n̶i̶a̶n̶ ̶m̶o̶n̶o̶s̶o̶d̶o̶w̶y̶ ̶(̶ ̶M̶S̶G̶,̶ ̶E̶6̶2̶1̶)̶

3. https://pl.openfoodfacts.org/product/5900344102444/płaty-śledziowe-w-zalewie-octowej-lisner - Recognized: E260, E262, not recognized: Sachary (E954),

4. https://pl.openfoodfacts.org/product/5908260252168/napoj-gazowany-o-smaku-jagod-acai-miechunki-peruwiańskiej-oshee - not recognized: Kwas cytrynowy (E330) Cytryniany sodu (E331)

5. https://pl.openfoodfacts.org/product/7622300644574/herbatniki-dekorowane-cukrem-san - not recognized: węglany amonu (E502), węglany sodu (E500),

**Comment by aleene** [comment]
These synonyms are not yet in the additives taxonomy.
I submitted a pull request: https://github.com/openfoodfacts/openfoodfacts-server/pull/2178

**Comment by aleene** [comment]
`węglany sodu` should have been recognised, it is in the file, but capitalised.

**Comment by stephanegigandet** [comment]
Thanks for the report @Slawek234

And thanks for adding synonyms @aleene . We should not add things like "barwnik E120", the additive class should not be added inside the synonyms of the additives taxonomy. 
I'm fixing the parsing so that the additives classes are properly recognized.

But we need to add the plurals to the additives classes taxonomy. e.g. przeciwutleniacze for przeciwutleniacz

It will also fix bug #2166

**Comment by aleene** [comment]
We could add barwnik E120 as child and add it barwnik as second parent. It specified the function. I have many more of those examples in ingredients, ready to integrate.

**Comment by stephanegigandet** [comment]
barnwik means "colour", we should not add it to the additives taxonomy.

**Comment by stephanegigandet** [comment]
@Slawek234 : this one is strange "Substancja konserwująca, Substancja niekonserwująca" --> not-preservative ??

**Comment by stephanegigandet** [comment]
I'm adding the Polish plurals to the additives classes.

**Comment by aleene** [comment]
Why not add as a child? It is more specific information in how the additive is used in this product.

**Comment by stephanegigandet** [comment]
We can support many more uses if we separate nature and function of ingredients. Same thing for all the properties like "organic", "fair trade" etc. The ingredients taxonomy is already huge, we cannot put all possible combinations of additives classes, labels, percentages etc. inside the taxonomy. Instead we can have separate taxonomies for labels, additives, additives classes etc. and during the parsing, we can tag each ingredient with its properties (how much % of it there is, its labels, function etc.).

**Comment by aleene** [comment]
If you separate things, aren't you losing information that was originally in the ingredients data? For instance the relation between colour and E120 (bad example, I know).

**Comment by stephanegigandet** [comment]
We can put it in the ingredients array, just like the properties for the organic labels etc.

**Comment by Slawek234** [comment]
@aleene , @stephanegigandet Thank you for quick response and action.
@stephanegigandet "We should not add things like "barwnik E120"" I agree. The word colour (barwnik) has been used only to help people better understand the food label text. 
I think the key information is in the add-in code, e.g. E120 and the name of the chemical compound e.g. Koszenila, karmina, kwas karminowy.

**Comment by Slawek234** [comment]
> @Slawek234 : this one is strange "Substancja konserwująca, Substancja niekonserwująca" --> not-preservative ??

@stephanegigandet Thanks for your perceptiveness. It seems to be my mistake. The text of the label is "Substancja konserwująca".

**Comment by Slawek234** [comment]
I think the ingredient "Ocet spirytusowy" should be recognized as E260 - kwas octowy.
Example: https://world.openfoodfacts.org/cgi/search.pl?search_terms=ocet+spirytusowy&search_simple=1&action=process

**Comment by Slawek234** [comment]
https://pl.openfoodfacts.org/product/5902891280231/cappuccino-z-magnezem-mokate
Substances not recognized: 
cytrynian trisodowy (E331 - cytryniany sodu: (i) cytrynian monosodu, (ii) cytrynian disodu, (iii) cytrynian trisodu); 
dwutlenek krzemu (E551 - ditlenek krzemu)

**Comment by stephanegigandet** [comment]
"Ocet spirytusowy" is just vinegar, it is used as an ingredient, not as an additive like E260 acetic acid.

**Comment by stephanegigandet** [comment]
@Slawek234 @aleene : all the reported issues above have been fixed by the new additives and additives classes taxonomy entries + improved ingredient parsing.
