### ISSUE TITLE
Please add automatic detection of table salt.

### ISSUE THREAD

**Issue by Slawek234** [openfoodfacts/openfoodfacts-server#2185]
Please add automatic detection of table salt in food products.

Table salt - NaCl, sodium chloride is a frequent food additive. I think that the information about additional addition of this substance to the product should appear.
Examples:
- https://pl.openfoodfacts.org/product/5906041030233/napoj-kawowy-na-bazie-pełnego-mleka-i-śmietanki-pkn-orlen
- https://world.openfoodfacts.org/product/20796273/sel-fin-chantesel

**Comment by aleene** [comment]
Salt is not a regulated food additive and has no E-number, so it will not appear in the list.

**Comment by aleene** [comment]
Or do you think of a special warning if the product has a lot of salt?

**Comment by Slawek234** [comment]
Indeed, sodium chloride is not on the list of additives E. I mean, as one of the food additives.

**Comment by Slawek234** [comment]
> Or do you think of a special warning if the product has a lot of salt?

The salt content is contained in Nutrition facts.

**Comment by teolemon** [comment]
We have several traffic lights to deal with this
https://world.openfoodfacts.org/nutrient-levels
![image](https://user-images.githubusercontent.com/1689815/63173415-2607dc00-c040-11e9-80a6-93f7b8af08b7.png)
