### ISSUE TITLE
nutrition-data-per-serving-missing-serving-size quality tag incorrectly assigned

### ISSUE THREAD

**Issue by zigouras** [openfoodfacts/openfoodfacts-server#2190]
**Describe the bug**
If the 'Nutrition facts are specified for the product as sold.' is not checked but the 'per serving' radio button is checked, the `nutrition-data-per-serving-missing-serving-size` quality tag is still generated if there are no nutriments entered.

**To Reproduce**
1. Go to edit product page
2. Make sure 'Nutrition facts are specified for the product as sold.' is not checked but the 'per serving' radio button is checked.
3. Save the product
4. Look in the db for the tag

**Expected behavior**
The tag should not be generated if the nutrition_data checkbox is not checked.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS Mojave 10.14.6
 - Browser Chrome
 - Version 76.0.3809.100

**Smartphone (please complete the following information):**

**Additional context**

**Comment by stephanegigandet** [comment]
Thank you for the detailed bug report @zigouras , it is fixed by this pull request: https://github.com/openfoodfacts/openfoodfacts-server/pull/2252

I sent you an invite to the Open Food Facts team on github, if you accept it you can then review the pull requests etc.

Thank you!
