### ISSUE TITLE
Error in parsing Polish ingredient lists

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#2201]
Error in parsing Polish ingredient lists

` jogurt*, cukier, owoce 7%, (maliny 2,3%, ananasy 1,8%, sok ananasowy z koncentratu 1,6%, sok malinowy z koncentratu 1,3%), musli 2,5% (otręby pszenne, płatki owsiane, pszenica, siemię lniane, ziarno słonecznika,orzechy laskowe), koncentrat soku z buraków czerwonych - aromat.
*zawiera składniki pochodzące z mleka oraz żywe kultury bakterii.`

we’re being too agressive with the cutter

it cuts after “skladniki” which is ingredients

**Comment by Slawek234** [comment]
Another example: https://fr.openfoodfacts.org/produit/8428532230078/boisson-amande-calcium-ecomil

**Comment by stephanegigandet** [comment]
Fixed by https://github.com/openfoodfacts/openfoodfacts-server/pull/2876
