### ISSUE TITLE
use strict; should be enabled in all Perl code, including ProductOpener modules

### ISSUE THREAD

**Issue by zigouras** [openfoodfacts/openfoodfacts-server#2202]
**Is your feature request related to a problem? Please describe.**
Perl best practice is to use this pragma.  This pragma is not used in any of core project code in the `ProductOpener/*.pm` modules.  It is risky not to use it as all variables become scoped globally, variable names are not checked, etc.

**Describe the solution you'd like**
Add `use strict;` to all Perl .pm modules 

**Describe alternatives you've considered**
There may be a reason it is not used in this project.

**Comment by hangy** [comment]
This *should* be enabled by `use Modern::Perl '2012';` ([CPAN](https://metacpan.org/pod/Modern::Perl)).

**Comment by CharlesNepote** [comment]
The Modern::Perl doc clearly says:
> This enables the strict and warnings pragmas

**Comment by zigouras** [comment]
OK sorry, didn't know that.
