### ISSUE TITLE
Document ProductOpener Perl modules.

### ISSUE THREAD

**Issue by zigouras** [openfoodfacts/openfoodfacts-server#2203]
**Is your feature request related to a problem? Please describe.**
There is little to no documentation in the code.  Perl POD (plain old documentation) can be used to generate a nice document page.

**Describe the solution you'd like**
Document all `ProductOpener/*.pm` modules with Perl POD including functions, classes, variables etc.

**Describe alternatives you've considered**
Moving blindly through the code.

**Additional context**
Since these Perl modules are the core of the business logic of the project they should be well documented.

### Part of 
- #5559

**Comment by stephanegigandet** [comment]
Agreed, we are lacking a lot in terms of documentation of the code. A lot of it could also certainly be simplified, reorganized etc. Maybe we can start with some of the simpler / most independent modules (and then also see if we could break / reorganize the more complex / big modules).

I could try with the Imports.pm module first. I have never used POD, is there a good example of POD best practices for documenting a module?

**Comment by zigouras** [comment]
Here is the official doc page for pod
https://perldoc.perl.org/perlpod.html

It lets you write inline markup in your code for headers, function documentation etc.  You then run
`perldoc myfile.pm`
to see a nicely formatted page.

Thanks for following up.

**Comment by VaiTon** [comment]
> **Describe alternatives you've considered**
> Moving blindly through the code.

Love you <3 lol

**Comment by CharlesNepote** [comment]
I appreciate recommendations from Damian Conway, in Perl Best Practices (2005). We could start with [comment templates](
https://books.google.fr/books?id=gJf9tI2mytIC&lpg=PT164&ots=Hn3hgNwthq&dq=perl%20%22comment%20templates%22&hl=fr&pg=PT163#v=onepage&q&f=false) for functions and methods.

Structured/templated comments are easier to write (you can't forget anything and it's easier to write) and also to read. Here is what he writes about it:
_Create comment templates that are suitable for your team. For example, to inter-
nally document a subroutine or method, you might use something like:_
```
############################################
# Usage      : ????
# Purpose    : ????
# Returns    : ????
# Parameters : ????
# Throws     : no exceptions
# Comments   : none
# See Also   : n/a
```
_which might be filled in like so:_
```
############################################
# Usage      : Config::Auto->get_defaults( )
# Purpose    : Defaults for 'new'
# Returns    : A hash of defaults
# Parameters : none
# Throws     : no exceptions
# Comments   : No corresponding attribute,
#            : gathers data from each
#            : attr_def attribute
# See Also   : $self->set_default( )
```

We could test it on a module to see if it fits well?

**Comment by zigouras** [comment]
I think Perl POD is a good option for a couple of reasons:
- Once POD is written then man pages, html pages, latex files, etc. can be generated from POD.  Scripts that are shipped with Perl such as `pod2html` and `pod2latex` do this for you.
- POD is the required standard for documentation for modules published on CPAN.  Any Perl developer will be familiar with the outline of a POD document.
- It will bring an industry standard to the documentation of your project's code base.

**Comment by teolemon** [comment]
@zigouras I have started automating generation using GitHub Actions to publish the doc to GitHub page. 
Currently it's using perldoc, but I'd like to have your input on what to use, especially if I want navigation between the various doc pages.
https://github.com/openfoodfacts/openfoodfacts-server/pull/5568/files#diff-a3dced34b21949749b803567be31b0966a3d875d413a529cf70fd5b1784a5a4b

**Comment by alexgarel** [comment]
It has been done since a long time (september 2022), see https://openfoodfacts.github.io/openfoodfacts-server/dev/ref-perl-pod/
