### ISSUE TITLE
Tags.pm loads geofiles every time it is referenced.

### ISSUE THREAD

**Issue by zigouras** [openfoodfacts/openfoodfacts-server#2204]
**Describe the bug**
When this module is loaded it takes a few seconds and prints to STDERR that it loaded two geofiles.  This slows down development and I am guessing is not intended or optimal behavior.

**To Reproduce**

```
Nicos-MacBook-Pro:lib nico$ perl -c -I . ProductOpener/Tags.pm
Tags.pm - loading geofile villes-geo-france-galichon-20130208.csv
Tags.pm - loading geofile villes-geo-france-complement.csv
...
ProductOpener/Tags.pm syntax OK
```
**Expected behavior**
Module should be loaded without calling this routine.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OSX Mojave

**Additional context**
Maybe this is necessary behavior, please let me know.

**Comment by stephanegigandet** [comment]
It's not intended, I don't know what would be the best way to avoid initializing some modules like Tags.pm twice.

**Comment by VaiTon** [comment]
Actually the Tags.pm file is extremely messy about where things get loaded and where they get used. I'm going to look into it.

**Comment by stephanegigandet** [comment]
Thank you @VaiTon !

**Comment by zigouras** [comment]
Thanks guys!
