### ISSUE TITLE
The default unit for caffeine should be mg.

### ISSUE THREAD

**Issue by Slawek234** [openfoodfacts/openfoodfacts-server#2206]
The default unit for caffeine should be mg not gram.
![Clipboard02](https://user-images.githubusercontent.com/26064514/63341264-21496d80-c349-11e9-8f59-12c02374e944.jpg)

I accidentally added Kofeina (pol. coffeine) and it, unlike caffeine, its unit is mg. Strange.
Example:
https://world.openfoodfacts.org/product/5900552021865/black-energy-zero-sugar

**Comment by aleene** [comment]
Good catch, no unit was specified, so you saw the default

https://github.com/openfoodfacts/openfoodfacts-server/pull/2207

**Comment by VaiTon** [comment]
Closed by #2207 via 36d4260

**Comment by stephanegigandet** [comment]
@VaiTon The file @aleene fixed is not yet used in production, the code still use the values in Food.pm, so I'm reopening the issue.

**Comment by aleene** [comment]
I guess there should be issue for removed this data from food.pm

**Comment by aleene** [comment]
It is now also in food.pm, so this one can be closed.
