### ISSUE TITLE
API JSON response is always different (values in random order)

### ISSUE THREAD

**Issue by VaiTon** [openfoodfacts/openfoodfacts-server#2219]
Currently the API JSON response is always different as the Values are in a random order. 

Proposal:
Order the result set alphabetically before generating a json response from the set.

This helps readability and should help developers get an quick overview of the result. 
This also helps getting some information about available fields, when some kind of documentation is missing.

_Originally posted by @Dwarfex in https://github.com/openfoodfacts/openfoodfacts-server/issues/1056#issuecomment-523791858_

**Comment by hangy** [comment]
The JSON module can do this, but also [warns](https://metacpan.org/pod/JSON::PP#canonical)
> If `$enable` is true (or missing), then the `encode` method will output JSON objects by sorting their keys. This is adding a comparatively high overhead.

**Comment by stephanegigandet** [comment]
I don't think it makes sense to add that overhead on the server (which is often enough overloaded already). Clients that need a sorted order can do it on their side.

**Comment by VaiTon** [comment]
I'll close this since we've agreed that it would add too much overhead for no reason.
