### ISSUE TITLE
Carrefour import script is broken

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#2227]
<h1>Software error:</h1>
<pre>hash- or arrayref expected (not a simple scalar, use allow_nonref to allow this) at ProductOpener/Import.pm line 717.

**Comment by stephanegigandet** [comment]
Caused by an empty XML file.

error parsing xml file with XML::Rules {error => "\nno element found at line 1, column 73, byte 73 at /usr/local/share/perl/5.24.1/XML/Rules.pm line 745.\n",file => "/srv/off/imports/carrefour/data/7618_3560070890224_valNut.xml"}

**Comment by VaiTon** [comment]
Is this still an issue? @stephanegigandet

**Comment by teolemon** [comment]
closing @stephanegigandet @VaiTon
