### ISSUE TITLE
Taxonomize Ingredients

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#224]
- Draft taxonomy exists
- Being done for OBF
- A couple of bugs/issues to solve before doing it.

**Comment by stephanegigandet** [comment]
Starting a taxonomy of French ingredients, using the ingredients from the existing products to start with.
The list needs to be cleaned to remove invalid entries (parsing errors, mispellings, OCR mistakes etc.). Then we can use the top of the list as the ingredients taxonomy.

**Comment by teolemon** [comment]
Can we edit on git ?

**Comment by stephanegigandet** [comment]
On git's web interface? No, the file is too large.

Using git: yes, but give me some time first to make an initial taxonomy.

**Comment by teolemon** [comment]
Fixed by @stephanegigandet
