### ISSUE TITLE
Mass incorrect automated change of Polish EMB codes

### ISSUE THREAD

**Issue by Slawek234** [openfoodfacts/openfoodfacts-server#2241]
The ending of Polis EMB codes has been overwritten by an incorrect EC.
Example: https://pl.openfoodfacts.org/packager-codes

The correct EMB code looks like this: PL28050201**WE** not PL28050201**EC**
![PL_WE](https://user-images.githubusercontent.com/26064514/63875419-b42a7d80-c9c3-11e9-9fb0-4f721fb5b4df.jpg)

**Comment by stephanegigandet** [comment]
Internally we normalize all EU codes to the form [country code] [actual code] EC (= European Commission).

At display time, we can localize them again, I'll do it for Polish too.

**Comment by VaiTon** [comment]
> 
> 
> Internally we normalize all EU codes to the form [country code] [actual code] EC (= European Commission).
> 
> At display time, we can localize them again, I'll do it for Polish too.

What changes between the "EU" and the "WE"? in this case?

**Comment by stephanegigandet** [comment]
> What changes between the "EU" and the "WE"? in this case?

When users enter "PL 28050201 WE", we already save it internally as "PL-28050201-EC" (EW means European Commission in Polish). 

Now when we display it (on the product pages, or in lists of EMB codes), we will display "PL 28050201 WE". (currently live on the dev server: http://pl.dev.openfoodfacts.org/packager-codes )

**Comment by stephanegigandet** [comment]
Fixed and deployed.
