### ISSUE TITLE
Styling of the nutrition table - in responsive edit mode

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#226]
![image](https://cloud.githubusercontent.com/assets/1689815/20648466/2310be46-b4a8-11e6-9604-51f6e5b79891.png)

Removing the 300px width for nutriment label fixes it.
`
.nutriment_label {
   text-align: left;
   /* width: 300px; */
}`

The issue is then alignment of table cells.

![image](https://cloud.githubusercontent.com/assets/1689815/13202242/d22c899c-d893-11e5-8248-432545fe3ebe.png)

**Comment by teolemon** [comment]
![image](https://cloud.githubusercontent.com/assets/1689815/13202242/d22c899c-d893-11e5-8248-432545fe3ebe.png)

**Comment by teolemon** [comment]
![image](https://cloud.githubusercontent.com/assets/1689815/13202246/1ea324ca-d894-11e5-9083-abf709824fbc.png)
![image](https://cloud.githubusercontent.com/assets/1689815/13202247/251f240c-d894-11e5-9208-6e116715572c.png)

**Comment by teolemon** [comment]
Ok, here's a proper android screenshot 
![image](https://cloud.githubusercontent.com/assets/1689815/20648466/2310be46-b4a8-11e6-9604-51f6e5b79891.png)

**Comment by hangy** [comment]
Yeah, I think the input's width is fixed. The edit view is not really made for responsive/mobile right now.

**Comment by teolemon** [comment]
We're going to use it more and more in the v2 of the Android app until we get native editing.
is removing the fixed width an issue ?
.nutriment_label { text-align: left; /* width: 300px; */ }

**Comment by hangy** [comment]
Depending on the label text width, that's not enough. I just tested it with Chrome's device toolbar. Without the fixed width, it looks fine for Nexus 5x and larger, but small displays (ie. iPhone 5) don't look that good, because the (possibly longer) German label is too long for that. So maybe the input form should be redesigned to use Foundation's responsive rows/columns instead.

**Comment by teolemon** [comment]
#109 is a duplicate

**Comment by hangy** [comment]
Works fine now for different browser sizes in Chrome's device toolbar, as well as on my Mi5s.
