### ISSUE TITLE
Ingredients-XX-4-consonants not relevant for many languages

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#2269]
This quality facet produce many false positive. At least 10 languages are relevant. Example:
* English: strenght: https://world.openfoodfacts.org/product/0065279101001/cranberry-juice-just-juice
* Danish: Melbehandlingsmiddel ; https://dk.openfoodfacts.org/product/5410041001204/biscuit-sal%C3%A9-crackers-tuc-original-lu
* Dutch: Verdikkingsmiddelen ; https://world-nl.openfoodfacts.org/product/3329770050419/yopa-yoplait
* Estonien: ekstract ; https://world-et.openfoodfacts.org/toode/20995553/sup%C3%A9rieur-85-cacao-j-d-gross
* Finnish: skummjölkspulver, emulgeringsmedel ; https://world-fi.openfoodfacts.org/product/5000159436465/snickers-ice-cream
* German: Verdickungsmittel ; https://world-de.openfoodfacts.org/produkt/3329770050419/yopa-natur-auf-blaubeerbett-yoplait
* Norwegian: fortykningsmiddel: https://world.openfoodfacts.org/product/7035620036033/multe-syltet%C3%B8y-eldorado
* Polish: dekstroza, ekstract ; https://pl.openfoodfacts.org/product/3250391699995/biscottes-compl%C3%A8tes-36-tranches-chabrior
* Slovenian: dekstroza, ekstrakt: https://world.openfoodfacts.org/product/3830001010190/pi%C5%A1%C4%8Dan%C4%8Dji-gyros-ave
* Sweedish: mjölbehandlingsmedel ; https://world-sv.openfoodfacts.org/product/5410041001204/biscuit-sal%C3%A9-crackers-tuc-original-lu

And probably for more languages.

* We could delete this kind of control (one day it will be solved by a real spell checker)
* We could delete this kind of control *for some languages* (one day it will be solved by a real spell checker)
* Probably better, we could use the ingredients dictionary to exclude false positive

**Comment by stephanegigandet** [comment]
@CharlesNepote : it's now 5 consonants: https://world.openfoodfacts.org/data-quality-warning/ingredients-fr-5-consonants
