### ISSUE TITLE
Unselecting images for admins is broken

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#2275]
https://world-fr.openfoodfacts.org/produit/5038862137775/jus-clementine-mandarine-innocent
![image](https://user-images.githubusercontent.com/1689815/64258477-9f03a080-cf27-11e9-9b2d-95affc581828.png)

**Comment by stephanegigandet** [comment]
https://github.com/openfoodfacts/openfoodfacts-server/blob/master/lib/ProductOpener/Display.pm#L6478

			if ($img =~ /data-src="([^"]*)\/([^\.]+)\./) {
				$idlc = $2;
			}

We need to change the regexp as the code for the lazy loading is now different. Otherwise we get "front" instead of "front_" + language code.

**Comment by stephanegigandet** [comment]
Fixed.
