### ISSUE TITLE
quantity-not-recognized for Russian quantities: мл, г, л

### ISSUE THREAD

**Issue by aleksejrs** [openfoodfacts/openfoodfacts-server#2279]
**Describe the bug**

When saving a product with a Russian quantity unit, "quantity-not-recognized" appears.

**To Reproduce**
1. Go to https://ru.openfoodfacts.org/cgi/product.pl?type=edit&code=4607030636597 or anyother product with a Russian quantity unit like мл, г, л, and possibly кг.
2. Click on "Сохранить" ("Save")
3. See "quantity-not-recognized" in "Quality".

**Expected behavior**
No error message, just like when "g" is used.

**Comment by stephanegigandet** [comment]
Thanks for the report, I will add them.

**Comment by VaiTon** [comment]
Closed by #2288
