### ISSUE TITLE
Negative query tags with a minus sign work only on first tag and not second tag

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#2285]
Prefixing the 2nd tag with a minus sign to specify the query should match products not containing that tag does not work.

https://world.openfoodfacts.org/country/-france/label/-organic results in products that are not from France but that have the organic label (yielding the same results as https://world.openfoodfacts.org/country/-france/label/organic )

**Comment by zigouras** [comment]
Yes I noticed this but was not sure if negative queries were supported on second-level tags so I did not change anything.

**Comment by stephanegigandet** [comment]
@zigouras If you can fix it, it would be great.

**Comment by zigouras** [comment]
@stephanegigandet you can assign this to me if you want.

**Comment by zigouras** [comment]
I was able to fix the MongoDB query so it does a 'not' condition on the second level tag with a prefix.

The product title does not reflect the 'not' condition on the second tag.  I don't see that we have translations for this 'without' phrasing for the second level tag so I am not sure how to fix it.  The linked country and second level tag in the header do not reflect the minus sign.

Also, clicking on a second tag, e.g. brands not in Spain, the web page never loads because it is a long list and there is no paging on this list.

**Comment by stephanegigandet** [comment]
If you want you can add translations by adding them to the file po/common/common.pot (just in English, the translations in other languages will be done later through Crowdin)

**Comment by zigouras** [comment]
@stephanegigandet I finished the coding for this and created a pull request.  I added my new language key "not_tag2_prefix" to common.pot but it was not being seen by the application code through the `lang()` function.  Once I added it to common.en and ran the scripts/build_lang.pl then I could see it.  I think you might need to clean it up or run some scripts to make sure it is common to all languages before translation.  Thanks.

**Comment by zigouras** [comment]
@stephanegigandet I finished the coding for this and created a pull request.  I added my new language key "not_tag2_prefix" to common.pot but it was not being seen by the application code through the `lang()` function.  Once I added it to common/po.en and ran the build lang script then I could see it.  I think you might need to clean it up or run some scripts to make sure it is common to all languages before translation.  Thanks.

**Comment by stephanegigandet** [comment]
Hi @zigouras , thanks for the fix and pull request, I tested it and the request works fine.

The title is a bit more complex, we have in fact a big h1 title, an h2 title (the one you changed), and in between we also have links to the individual tags 1 and 2:

![image](https://user-images.githubusercontent.com/8158668/64920266-cb37e080-d7b5-11e9-9662-3a33ad219e39.png)

I would like to change how we generate the h2, and we'll need to change the h1 and tags links too (maybe just putting the - before them).

I'm not very familiar with github and branches, so I will merge your pull request as it's clearly an improvement, and create another branch for the other changes.

**Comment by stephanegigandet** [comment]
Ok I think I figured out how to make a pull request on your branch: https://github.com/zigouras/openfoodfacts-server/pull/1

**Comment by zigouras** [comment]
Thanks @stephanegigandet, I merged your PR back into my branch.

**Comment by zigouras** [comment]
I also rolled back the language changes I made since they are not needed now and committed those to the original branch and PR.

**Comment by stephanegigandet** [comment]
@zigouras Perfect, thank you.

**Comment by stephanegigandet** [comment]
Merged and deployed, thanks!
