### ISSUE TITLE
Apply recent official change for colza, walnut and olive oils to the Nutri-Score computation

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#2296]
Apply recent official tweak to the Nutri-Score computation

**Comment by stephanegigandet** [comment]
Colza, walnut and olive oils are now counted in the fruits/vegetables/nuts category.

**Comment by stephanegigandet** [comment]
Added new estimates : 100% fruits/vegetable/nuts for products that are in the walnut / olive / colza oil category.

**Comment by VaiTon** [comment]
Partially fixed by #2297

**Comment by stephanegigandet** [comment]
Fixed and deployed.
