### ISSUE TITLE
the "Scatter plot" transform into a "bar plot" if the items on one axis is a count on the product search page

### ISSUE THREAD

**Issue by kyzh** [openfoodfacts/openfoodfacts-server#23]
On the [Products search](http://world.openfoodfacts.org/cgi/search.pl) page, the "scatter plot" functionality generate a "bar plot" when using items that are not numerical data, therefore imply a "count" of the return product(s).

Here is a user story: "A user search for categories containing beer, with Alcohol in Horizontal axis and number of product in vertical axis"
The results is [a bar plot](http://world.openfoodfacts.org/cgi/search.pl?action=process&tagtype_0=categories&tag_contains_0=contains&tag_0=beer&sort_by=unique_scans_n&page_size=20&axis_x=alcohol&axis_y=products_n&graph=1)

**Comment by stephanegigandet** [comment]
So we should just remove the mention "Scatter plot", and leave the "Display results on a graph" right?

Originally we just had scatter plots, I added bar plots a few months ago.

**Comment by kyzh** [comment]
I would go for the change to  "Display results on a graph".
It is the easiest way to have the behavior matching the label.

**Comment by stephanegigandet** [comment]
Fixed a long time ago.
