### ISSUE TITLE
Excessive cutting in Spanish

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#2305]
`Arroz salvaje rojo 100%. (* Ingredientes procedentes de la agricultura ecológica).`

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/66268435-ae834b80-e83d-11e9-8d3b-6c40bac0d938.png)

**Comment by stephanegigandet** [comment]
Fixed by https://github.com/openfoodfacts/openfoodfacts-server/pull/2876
