### ISSUE TITLE
[multilingual products] Make sure existing mobile apps & current API work with language specific fields

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#234]
In particular check that the right language specific fields are written for:
- images upload
- values for "product name".

**Comment by stephanegigandet** [comment]
The current API is supported. Apps continue to write to the non-suffixed fields, and for language specific fields, the value is copied the the field suffixed by the main language.

product_jqm.pl and product_jqm2.pl are redirected to product_jqm_multilingual.pm

			if ((defined $language_fields{$field}) and (defined $product_ref->{lc})) {
				my $field_lc = $field . "_" . $product_ref->{lc};
				$product_ref->{$field_lc} = $product_ref->{$field};
			}

**Comment by stephanegigandet** [comment]
The current READ API is also supported: for language specific fields, the value for the main language of the product is copied to the non suffixed field.

e.g. for a product with French as the main language, the product_name field contains the value of product_name_fr

**Comment by aleene** [comment]
Guess this one can be closed by now.
