### ISSUE TITLE
JSON defined detection rules for the Mobile apps

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#2341]
JSON defined detection rules for the Mobile apps, so that we can easily add additional ingredient detections on the fly on both platforms
```
default
{
color_maybe:
color_uncertain:
color_yes:
color_no:
icons_base_url: https://github.com/openfoodfacts/openfoodfacts-server/blob/master/icons/ 
},
palm_oil:
{
icon:
icon_no: monkey_happy.svg
icon_yes: monkey_unhappy.svg
icon_uncertain: monkey_uncertain.svg
icon_maybe:
color_maybe:
color_uncertain:
color_yes:
color_no:
name_fr:huile de palme
name_en:palm oil
},
vegetarian:
{
icon: egg.svg
color_maybe:
color_uncertain:
color_yes:
color_no:
name_fr:vegétarien
name_en:vegetarian
},
vegan:
icon: leaf.svg
color_maybe:
color_uncertain:
color_yes:
color_no:
}
```

**Comment by teolemon** [comment]
Also, the file structure is not the same for all diets. How about putting variants for egg and leaf, and adoptiing a yes/no structure everywhere ?

**Comment by teolemon** [comment]
Also, should we expose it in the taxonomy for ingredient detection ?

**Comment by stephanegigandet** [comment]
The easiest is to use the ingredients analysis taxonomy: https://static.openfoodfacts.org/data/taxonomies/ingredients_analysis.json

Then you can just reference it in your app config file:

[
	["en:vegan",
		["en:vegan", { "icon_url" : ..., "color": ...},],
		["en:maybe-vegan", { "icon_url" : ..., "color": ...},],
		["en:non-vegan", { "icon_url" : ..., "color": ...},]
	],
	["en:palm-oil",
		["en:palm-oil-free", { "icon_url" : ..., "color": ...},],
		["en:may-contain-palm-oil", { "icon_url" : ..., "color": ...},],
		["en:palm-oil", { "icon_url" : ..., "color": ...},]
	],	
...

**Comment by stephanegigandet** [comment]
> Also, the file structure is not the same for all diets. How about putting variants for egg and leaf, and adoptiing a yes/no structure everywhere ?

With the structure I proposed above, the app does not have to know about yes, no etc. so we can support any kind of ingredients analysis (including new ones we haven't thought about yet).

> Also, should we expose it in the taxonomy for ingredient detection ?

It's already in the ingredients_analysis taxonomy with references to it in the ingredients field.

**Comment by stephanegigandet** [comment]
Done with this file: https://static.openfoodfacts.org/files/app/ingredients-analysis.json
