### ISSUE TITLE
Translating anchors in the producers.html page

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#2359]
### What
```
<h3 id="exemples_de_producteurs_qui_transmettent_les_photos_et_donnees_de_leurs_produits_a_open_food_facts">
```
Translating anchors in the producers.html page

### Part of
- #5521

**Comment by aakankshabhende** [comment]
Can I work on this issue @teolemon ?

**Comment by aakankshabhende** [comment]
To what should I translate the anchors? @teolemon

**Comment by aakankshabhende** [comment]
Is this issue still open to work on @teolemon?
