### ISSUE TITLE
Make water NOVA 1 if not flavoured, sugared etc.

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#2362]
The NOVA classification is currently done through the ingredients list, but for most spring water, mineral water etc. we don't have ingredients listed.

**Comment by aleene** [comment]
You could use the category?

**Comment by stephanegigandet** [comment]
Yes, we can check the category, and still compute NOVA even if there are no ingredients listed.

**Comment by stephanegigandet** [comment]
FYI, here is the list of products that would be marked as NOVA 1 : https://world.openfoodfacts.org/category/-flavored-waters/category/waters
I think it would be good to review the list first.
