### ISSUE TITLE
Argument of product_path() must be a referece to the product hash object, not a scalar: 3000180018718

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#2374]
![image](https://user-images.githubusercontent.com/1689815/65527777-861d5800-def3-11e9-8b59-bc8cbca46a95.png)

Argument of product_path() must be a reference to the product hash object, not a scalar: 3000180018718

**Comment by stephanegigandet** [comment]
On which server? If it is the dev server, it's running the producer branch and other branches depending on what I'm coding.

**Comment by zigouras** [comment]
Is this problem only in dev?  Is the code or setup different in dev than prod?

**Comment by stephanegigandet** [comment]
I think it's just in dev, this would happen if we have the producer branch modules loaded in model, and the master branch cgi scripts.

**Comment by stephanegigandet** [comment]
I probably just need to restart Apache. I'm not in front of a computer, I'll do it in an hour.

**Comment by zigouras** [comment]
OK I will reassign to @stephanegigandet

**Comment by stephanegigandet** [comment]
Fixed.
