### ISSUE TITLE
Make list of product fields configurable

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#239]
### What
- For Open Beauty Facts, we will need to add some fields like "period_after_opening" and remove some fields:
  - best before date
  - the nutrition facts table
- Changes need to be reflected in product edit form, product display, CSV export, search form etc.
### Part of
- Open Pet Food Facts, Open Products Facts, Open Beauty Facts

**Comment by aleksejrs** [comment]
Why remove the best before date?  Most shampoos have one.

**Comment by teolemon** [comment]
PAO is the Best Before Date

**Comment by hangy** [comment]
Shouldn't this already be configurable through `@product_fields` and `@display_fields` in Config.pm? ([OFF](https://github.com/openfoodfacts/openfoodfacts-server/blob/0bac85e1b3383dd3cd3523e00428003bc2e75b31/lib/ProductOpener/Config_off.pm#L185-L221)/[OBF](https://github.com/openfoodfacts/openfoodfacts-server/blob/fc0d2f7544e07d0e6b0f9b44da023be007fee875/lib/ProductOpener/Config_obf.pm#L149-L186))

**Comment by teolemon** [comment]
@stephanegigandet @hangy I assume that this has been fixed ?
