### ISSUE TITLE
Have 2 separate nutrient fields for energy in kJ and energy in kcal

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#2396]
We currently have only 1 field for energy, which can be entered in kJ or in kcal (which is the same as the "big Calorie" Cal). Internally we convert the energy to kJ.

This is problematic because in Europe, the food labelling law stipulates that the energy should be computed from the other nutritional values, with conversion tables that have slightly differing kJ to kcal ratios for each nutrient.

https://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2011:304:0018:0063:EN:PDF

ANNEX XIV
CONVERSION FACTORS
CONVERSION FACTORS FOR THE CALCULATION OF ENERGY
The energy value to be declared shall be calculated using the following conversion factors:
— carbohydrate (except polyols), 17 kJ/g — 4 kcal/g
— polyols, 10 kJ/g — 2,4 kcal/g
— protein, 17 kJ/g — 4 kcal/g
— fat, 37 kJ/g — 9 kcal/g
— salatrims, 25 kJ/g — 6 kcal/g
— alcohol (ethanol), 29 kJ/g — 7 kcal/g
— organic acid, 13 kJ/g — 3 kcal/g
— fibre, 8 kJ/g — 2 kcal/g
— erythritol, 0 kJ/g — 0 kcal/g

That means that there isn't a single conversion ratio that we can apply to convert the energy from or to kJ and kcal to get exactly the same numbers as printed on food products.

e.g. current nutrient fields for https://fr.openfoodfacts.org/produit/3366321051594/saint-hubert-demi-sel-st-hubert : 

energy_value: 450,
energy_unit: "kcal",
energy_100g: 1883,
energy: 1883,

actual energy printed on label:  1850 / 450 kcal

Proposed solution:

1. Create 2 new nutrient fields: energy_kj and energy_kcal, with mandatory units: kj and kcal.

2. In the product edit form, remove the existing energy field that can be filled in kj or kcal, and display the 2 new fields. (for Europe ; in the US, just display the kcal field)

3. in the API, allow the values to be set through the 2 new fields, or through the existing energy field. If the energy is passed in kj, populate energy_kj. Same for kcal. 

4. When saving values, compute the energy field from energy_kj field if it exists, or from energy_kcal.

5. For existing products, depending on the unit of the energy field, populate energy_kj or energy_kcal.

As a result, we will have those nutrients:

energy_kcal_value: 450,
energy_kcal_unit: "kcal",
energy_kcal_100g: 450,
energy_kcal: 450,

energy_kj_value: 1850,
energy_kj_unit: "kJ",
energy_kj_100g: 1850,
energy_kj: 1850,

energy_value: 1850,
energy_unit: "kJ",  --> indicates the source of the energy field (energy_kj if we have it, or converted from energy_kcal if we don't have it, or for US products)
energy_100g: 1850,
energy: 1850,

This approach should be transparent for current apps that display or edit energy using the energy field, and allow us to separate the fields first on the web site, then in our app, and using the data we get from producers.

**Comment by VaiTon** [comment]
Implemented in #2596
