### ISSUE TITLE
Translating vitamins is impossible

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#2400]
``` 
ReferenceError: event is not defined
vitamins:1041:2
<anonyme>
https://world-ja.openfoodfacts.org/vitamins:1041:2
dispatch
https://static.openfoodfacts.org/js/dist/jquery.js:25:1263
add/q.handle
https://static.openfoodfacts.org/js/dist/jquery.js:24:30094
``` 
Quand je clique sur le bouton bleu ça fait rien
J’ai une erreur dans la console JavaScript

https://world-ja.openfoodfacts.org/vitamins

**Comment by teolemon** [comment]
reported by @TaciteOFF

**Comment by teolemon** [comment]
cc @stephanegigandet

**Comment by stephanegigandet** [comment]
Which url exactly? It seems to be working for me: https://world-ja.openfoodfacts.org/vitamins?translate=add

![image](https://user-images.githubusercontent.com/8158668/66158937-43f8c280-e627-11e9-9383-212558fccb6c.png)

**Comment by stephanegigandet** [comment]
Fixed and deployed.
