### ISSUE TITLE
Add data-quality taxonomy and split quality facet in data-quality-info/warnings/errors facets

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#2419]
The /quality facet currently mixes different things:

1. info tags that do not indicate an error (e.g. Carbon-footprint-from-known-ingredients-but-not-from-meat-or-fish) or that indicate that there isn't an error (e.g. Nutrition-grade-fr-producer-same-ok)

2. warning tags that indicate an error may be possible (e.g. Ingredients-50-percent-unknown)

3. error tags that indicate an error is very likely (if not certain). (e.g. Nutrition-value-over-105-for-salt)

For the producers platform, but also for the public database, it would be very useful to distinguish between what is information, a warning, or an error.

e.g. on the producers platform, if there are errors for some products, we won't synchronize them to the public database.

Proposed approach:

1. create a data_quality.txt taxonomy

2. add properties to indicate what is an info, warning or error.
e.g.
severity:en:warning

3. populate 3 different facets, based on the severity:
- data-quality-info
- data-quality-warnings
- data-quality-errors

The taxonomy will be the same file for all 3 sub-facets. It will allow us to translate the info / warnings / errors, and also to provide descriptions to explain some of them.

There will also be a property to indicate which quality entries will be shown to producers on the producer platform (e.g. the "% of unknown ingredients" entries are more likely to indicate issues with the ingredients taxonomy or parsing than issues in the ingredients text provided by producers).

**Comment by CharlesNepote** [comment]
This very interesting!

For the feature part, there could also a distinction between important warnings/errors and less important ones. For example:
* https://world.openfoodfacts.org/quality/quantity-contains-e is not very important
* https://world.openfoodfacts.org/quality/ingredients-ingredient-tag-length-greater-than-200 is more important as it impacts Nova, etc.

**Comment by stephanegigandet** [comment]
2. add properties to indicate what is an info, warning or error.  e.g.  severity:en:warning

-> This isn't such a good idea, as many data quality values may not be in the taxonomy (e.g. all the combinations of ingredients issues * langue like ingredients_fr_* )

The severity will be set directly in the code.

**Comment by zigouras** [comment]
Do you guys want me to work on this?
Why not create a mongodb table instead of a file.  It will make updating and querying much easier.
Will all of the taxonomy tags have to be extracted from the Perl code for this?

**Comment by stephanegigandet** [comment]
Hi @zigouras, I haven't closed the bug yet, but I already split the data-quality facets.
I'm not sure about "Why not create a mongodb table instead of a file". Are you referring to the data_quality.txt taxonomy ? That's how we define taxonomies on Open Food Facts, for categories, ingredients, labels etc. At this point the definition is in files. e.g. https://github.com/openfoodfacts/openfoodfacts-server/blob/master/taxonomies/labels.txt

**Comment by zigouras** [comment]
OK after I wrote my comment I noticed that you developed this already.  I will leave this issue for now.

**Comment by stephanegigandet** [comment]
The new data quality facets are deployed in production, closing.
