### ISSUE TITLE
CSV dataset broken due to control chars

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#2426]
**Describe the bug**
The CSV dataset fail to be open with some tools, due to control chars. Example of data:
https://world.openfoodfacts.org/product/10100200/helado-de-fresa-natural-los-laureles?rev=4
This product contains a [line separator U+2028](http://www.fileformat.info/info/unicode/char/2028/index.htm).

See also closed bug #1585

**To Reproduce**
Requirement: install [csvkit](https://csvkit.readthedocs.io/en/latest/).
```
$ csvclean -t en.openfoodfacts.org.products.csv
5 errors logged to en.openfoodfacts.org.products_err.csv
10 rows were joined/reduced to 4 rows after eliminating expected internal line breaks.
```

**Expected behavior**
```
$ csvclean -t en.openfoodfacts.org.products.csv
No errors.

$ egrep $'\u000C|\u0085|\u2028|\u2029' en.openfoodfacts.org.products.csv # should return nothing
```

**Where to fix?**
See the [sanitize_field_content](https://github.com/openfoodfacts/openfoodfacts-server/blob/master/scripts/export_database.pl#L84) function in `./scripts/export_database.pl`.

**Comment by DeffeDotCom** [comment]
I got this error:
`csvclean -t en.openfoodfacts.org.products.csv
'ascii' codec can't encode character '\xf3' in position 162: ordinal not in range(128)`
To solve it I did this in the terminal (change locals):
`export LC_ALL=C.UTF-8`
And that resulted in a correct new file: en.openfoodfacts.org.products_out.csv
