### ISSUE TITLE
Move Nutri-Score computation from ProductOpener::Food to dedicated Food::NutriScore cpan module

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#2427]
I plan to move the Nutri-Score computation logic to a new Food::NutriScore module, which would be independent from how we structure products in OFF / ProductOpener.

It should make the compute_nutrition_score() function more clear. It will also be useful to run multiple nutriscore computations in the producers platform, to test for opportunities to improve the Nutri-Score by reducing a bit salt, sugars, fat etc.

**Comment by CharlesNepote** [comment]
Also, couldn't it be a completely independent module with its own repository. Thus:
* It could be published in CPAN
* It could be interesting for devs that don't want to have to investigate ProductOpener source
* It might be easier to use, understand and contribute financially on platforms such as open collective

**Comment by CharlesNepote** [comment]
(Don't forget documentation ;-) https://github.com/openfoodfacts/openfoodfacts-server/blob/9b4390c7e775b6d06caecead4e115b708a94b326/lib/ProductOpener/Nutriscore.pm#L27

**Comment by stephanegigandet** [comment]
We now have a dedicated ProductOpener::NutriScore module.
