### ISSUE TITLE
Quality facet - Nutrition - Compare stated and calculated energy for higher accuracy of product listings and spotting faulty products

### ISSUE THREAD

**Issue by bredowmax** [openfoodfacts/openfoodfacts-server#2429]
### What
- Stated and calculated energy does not fit for approx. 14.000 products. Reason could be a simple type-o, a mistake in the label itself, but most often, it's editors that confuse kj and Kcal.

For example:
1. If calculated kcal is approx 4.2x higher than stated, then the editor probably meant KCal but wrote the energy in kj
2. If calculated kj is approx. 4.2x smaller than stated, then the editor probably meant kj but wrote the energy in KCal

### Proposed solution
An automatic test, something along ```Is kcal/100g approx. 9*fat+4*CH+4*protein (+/- 10%)```
If that test is not passed have it pass on to manual review, e.g. hunger games

These products would likely fail this test:
Sheet 1: Is calculated energy from fat+carbs+protein < 3800kj?--> 68 products
Sheet 2: Is calculated energy from fat+carbs+protein at least 80% of stated energy?--> 9000 products
Sheet 3: Is calculated energy from fat+carbs+protein max. 120% of stated energy? --> 5000 products
https://docs.google.com/spreadsheets/d/142UD8SrbOS2ZGNiaXLnNacw32Wtcia_iEMiPR2vxxAY/edit?usp=sharing

### Considered alternatives
1. Fix existing objects
2. Avoid future mistakes

Option 1: Calculate Kilocalories
Option 2: Calculate Kilojoules

Open question: Should g fibres be calculated with 7kj/g?

### Context
https://openfoodfacts.slack.com/archives/C03H290LF/p1569656651003000

### Part of
- #5538

**Comment by stephanegigandet** [comment]
I will add this to the data quality tests.

**Comment by stephanegigandet** [comment]
List of the different factors used to compute energy in kcal and kj used in the US, Canada, Mexico and the EU: https://esha.com/calorie-calculation-country/

EU law: https://eur-lex.europa.eu/legal-content/FR/TXT/HTML/?uri=CELEX:32011R1169&from=FR
