### ISSUE TITLE
Simplify taxonomy update

### ISSUE THREAD

**Issue by TaciteOFF** [openfoodfacts/openfoodfacts-server#243]
Maintaining Open Food/Beauty Facts is time consuming. 

Especially when only one administrator can push taxonomy live, I guess.

A new tool to update taxonomies could benefit to everybody! :)

**Comment by VaiTon** [comment]
Fixed as now taxonomies live on github @teolemon @stephanegigandet

**Comment by hangy** [comment]
Yes and no ... I don't think anyone but @stephanegigandet can actually deploy updated taxonomies right now. 🙂

**Comment by VaiTon** [comment]
Maybe we should set an automation?

**Comment by hangy** [comment]
I'd be in favour of a good CI/CD pipeline of the whole website, but that's for @stephanegigandet to decide, as he's the one who knows details about the [#infrastructure](https://openfoodfacts.slack.com/messages/C1FPYCWM7/details/).

**Comment by TaciteOFF** [comment]
Kind of fixed with the pull system
