### ISSUE TITLE
Remove bottom and top 5% when computing mean and standard deviation of nutrients for a category

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#2436]
Some very high values (that are in fact data errors, and not actual high values) for nutrients are completely changing the standard deviation (e.g. 20g of std for salt for a category like en:cakes).

Proposed solution by @odtvince : remove bottom and top 5% before computing mean and std.

**Comment by teolemon** [comment]
Can we keep an exception for admins ? @stephanegigandet

**Comment by stephanegigandet** [comment]
@teolemon : an exception to what? I don't see what this has to do with admins?

**Comment by stephanegigandet** [comment]
This has been deployed in production, closing.
