### ISSUE TITLE
[OpenBeautyFacts] Strange label behaviour

### ISSUE THREAD

**Issue by TaciteOFF** [openfoodfacts/openfoodfacts-server#245]
Since yesterday update : 

This label got added to some products for no reason
http://fr.openbeautyfacts.org/label/formule-resistante-a-l-eau-a-la-transpiration

NaTrue label disappeared and now redirects to "Sans acétone" that also inherited the broken label image
http://fr.openbeautyfacts.org/label/natrue 
http://fr.openbeautyfacts.org/label/sans-acetone

**Comment by stephanegigandet** [comment]
My bad, I forgot the taxonomy was split in two with the production taxonomy in the first part, and the bottom up taxonomy in the 2nd part.

The bottom up taxonomy has many issues and should not be used as is.

e.g.

fr:0 parfum
fr:Fabrication a l'ancienne
fr:Brevet déposé
fr:Impact environnemental réduit
fr:Haleine fraiche
fr:Test d'efficacité sur 13 personnes
fr:Formule résistante a l eau a la transpiration

-> all those are considered synonyms

Moving the bottom up taxonomy to a different page to avoid mistakes.
http://en.wiki.openbeautyfacts.org/Global_labels_taxonomy_bottom_up

**Comment by stephanegigandet** [comment]
Pushed live the correct labels taxonomy (excluding the work in progress bottom up taxonomy)
