### ISSUE TITLE
Actions is blocking builds

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#2473]
it bugs on python (also it's slowing things a lot). @hangy any ideas ? Can we make them optional to merge ?
https://github.com/yarnpkg/yarn/issues/2051
https://github.com/openfoodfacts/openfoodfacts-server/pull/2470/checks?check_run_id=270521287
```gyp verb `which` failed    'Error: not found: python\n    at getNotFoundError (/github/workspace/node_modules/which/which.js:13:12)\n    at F (/github/workspace/node_modules/which/which.js:68:19)\n    at E (/github/workspace/node_modules/which/which.js:80:29)\n    at /github/workspace/node_modules/which/which.js:89:16\n    at /github/workspace/node_modules/isexe/index.js:42:5\n    at /github/workspace/node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:153:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/github/workspace/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/github/workspace/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/github/workspace/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/github/workspace/node_modules/which/which.js:80:29)
gyp ERR! stack     at /github/workspace/node_modules/which/which.js:89:16
gyp ERR! stack     at /github/workspace/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /github/workspace/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
gyp ERR! System Linux 5.0.0-1020-azure
gyp ERR! command "/usr/local/bin/node" "/github/workspace/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /github/workspace/node_modules/node-sass
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
##[error]Docker run failed with exit code 1```

**Comment by hangy** [comment]
I don't know. Looks like it might be a intermittent error, because later checks like https://github.com/openfoodfacts/openfoodfacts-server/pull/2478/checks?check_run_id=273760859 did build without any issues. The change to those HTML files really shouldn't have any impact on this installation procedure.

**Comment by VaiTon** [comment]
Closing for now because, as @hangy said, later checks did build.
