### ISSUE TITLE
Big numbers localized

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#2474]
1009992 is hard to read (since we have more than one million products).

Big numbers should be split with locale separators. Here is an example for french locale (where groups of 3 digits are separated by a space):
![image](https://user-images.githubusercontent.com/562352/67378848-2fee1400-f588-11e9-97a6-2bbb8fc3d496.png)

The current HTML code is:
```
<div style="font-size:1.2rem;background-color:#eeeeee;padding:0.3rem 1rem;height:2.75rem;margin:0">1 009 392 products</div>
```
It should be improved: put CSS in a file, add ids, etc. Example:
```
<div id="xxxProducts"><span id="nbOfProducts" value="1009392">1 009 392</span> products</div>
```

**Comment by VaiTon** [comment]
We could mark fields that need to be formatted with a class and then use the `Intl` class in javascript (available for most browsers).

Ex:
```js
var num = "125452.22"
Intl.NumberFormat('it-IT').format(num); // 125.452,22
Intl.NumberFormat('fr-FR').format(num) // 125 452,22
```

**Comment by CharlesNepote** [comment]
Thanks a lot @VaiTon!
