### ISSUE TITLE
Weird bug with Belarus lang (be) on nl_be product

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#2489]
https://fr.openfoodfacts.org/cgi/product.pl?type=edit&code=5411223030081
Impossible to remove `be`

**Comment by zigouras** [comment]
Hi @teolemon, I can work on this if you want.  Can you clarify where the "be" text is that you cannot remove?  I see "Belgium" in three fields, is that what you mean?  Is this only on the French translation page or on all pages?  Thanks.

**Comment by stephanegigandet** [comment]
Somehow the product got some fields suffixed with nl_be, that should not happen anymore.
I'll fix the compute_language() function so that it does not think the fields ending in nl_be are related to the be language.

**Comment by stephanegigandet** [comment]
Fixed.
