### ISSUE TITLE
Add "contributor" to the searching capability of the "Products search" page

### ISSUE THREAD

**Issue by kyzh** [openfoodfacts/openfoodfacts-server#25]
It would be beneficial to be able to graph and map contribution by user from the [product search page](pl.openfoodfacts.org/cgi/search.pl).

So far one can only search by contributor, fromt the [home page link](http://world.openfoodfacts.org/contributors).
Here is an example of how a search can be done [from this link](http://pl.openfoodfacts.org/contributor/tacinte/additive/e330-kwas-cytrynowy)

It has the following shortcomings:
- It doesn't produce graphs.
- It doesn't produce maps.
- It doesn't produce CSV.
- One user looking for contributor, will only find the contributor after she choose a country (world. pl. uk. etc.).
- Choosing a country implies a language, since languages selections are done against a country.
- One can choose a maximum of 2 criteria in the follwoing set "countries, brands, categories, labels, packaging, origins of ingredients, manufacturing or processing places, packager codes, ingredients, additives, allergens, traces, contributors, states".

**Comment by hangy** [comment]
I think this was fixed in 99d38728c45e6d4adb74dfb826e55b0308fa256e. Feel free to reopen if it isn't .

**Comment by stephanegigandet** [comment]
creator is not a tag field (there's only one), so we need to add some special logic to do something like that.
