### ISSUE TITLE
TBHQ should trigger E319

### ISSUE THREAD

**Issue by TaciteOFF** [openfoodfacts/openfoodfacts-server#250]
Hello, 

Here are some things I noticed with ingredients lists on OFF US

http://us.openfoodfacts.org/product/0038000316104/pop-tarts-frosted-raspberry-kellogg-s

"WITH TBHQ FOR FRESHNESS" should add the E319 additive.
"SOYBEAN AND PALM OIL" should trigger the palm oil detector.

Thanks :)

**Comment by teolemon** [comment]
You can add the first in the Additives Taxonomy as an additive.
As for the second, it's still a manually crafted list within the code (poke @stephanegigandet ), that could gain being extracted, much like on Open Beauty.

**Comment by teolemon** [comment]
@TaciteOFF was it added ?

**Comment by teolemon** [comment]
Palm oil part is fixed.

**Comment by teolemon** [comment]
@stephanegigandet @aleene
