### ISSUE TITLE
Add the ability to mark a product as 'done' so that it is not displayed in the 'products that need to be completed' anymore.

### ISSUE THREAD

**Issue by bcatelin** [openfoodfacts/openfoodfacts-server#251]
often I scan a product, take a cooouple of pictures and then move on and forget about it. it can be days or even weeks before I go to the off website and then go through th 'products I have edited that need to be completed' page and clean my 'mess'. The problem is that this page is full of junk (well according to me) a I see products that are 100% fine as far as I can tell. This is usually due to a picture not yet approved or simply a product in a language/script I can't read so I really can't add any more value to the entry. I would like a way to mark the product/page as not-to-be-displayed any more in the 'to be completed' page, that way I could easily carry on cleaning the entries I have posted, without having to review the same product again and again.

**Comment by TaciteOFF** [comment]
"This is usually due to a picture not yet approved"
You can validate the picture by yourself! :)

**Comment by TaciteOFF** [comment]
For now, as a quick fix, I suggest you bookmarking a page like http://world.openfoodfacts.org/contributor/bcatelin/state/product-name-to-be-completed

**Comment by bcatelin** [comment]
The real problem is the way OFF deals with products and localisation I think. if you add a product in Thailand and your device location is off and it happens that th off app is in french then the pictures will end up being in france and thailand and there is no easy way to fix it, meaning that your product will always appear to be incomplete. also, another case is when not all information is available on the product, there will be no way for a product to be complete, ever, that means that the OFF user 'products to be completed' page will always be cluttered with products that are not complete. The 'done' markup was a solution, but probably not the right one, the real issues should be addressed instead. I am closing this issue.
