### ISSUE TITLE
Clarify the usage of the "Purchase location" field

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#252]
### What
- I am confused about the actual usage of the purchase location field. At the moment it is used in various ways. 
- I would be able to create a map based on all the purchase locations that have been supplied. 
- In the current approach one cannot distinguish between two locations as the information is mixed up into multiple tags, like (lyon, france, bruxelles, belgium, wetstraat). It is unclear which combination of tags comprises a single address.

### Proposal

- allow only one address per edit version. This address can not be added, only replaced. Multiple versions of a product store thus multiple purchase locations, each corresponding to an actual purchase. 
- Previous purchase locations can be shown, but not deleted. 
- The JSON version of the product presents that purchase locations as an array of an array of address part strings.

**Comment by teolemon** [comment]
Doesn't Open Prices solve this @aleene @raphodn ?
