### ISSUE TITLE
Read API JSON incomplete - nutriments

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#254]
Not all nutriments are published in the json read api. For instance alcohol percentage and ph value are missing. Guess a synchronisation must be carried out.

**Comment by teolemon** [comment]
Is is the case for cocoa value ?

**Comment by stephanegigandet** [comment]
Everything should be in the JSON, e.g. 

http://world.openfoodfacts.org/api/v0/product/3500610048999/lussac-saint-emilion-rouge-2007-tarje-du-chateau-la-claymore

"nutriments":{"alcohol_unit":"% vol","alcohol_100g":"12.5","alcohol_value":"12.5","alcohol_serving":"12.5","alcohol":"12.5"}

If you have a product where it's missing, can you send me the url?

**Comment by aleene** [comment]
I do not remember what the issue with alcohol was. I'll close this issue for now (will add something else).
