### ISSUE TITLE
Add key to taxonomies

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#255]
It is not possible to match the taxonomies found on the wiki and the taxonomy values available in the json files. The json files contain taxonomy entries as lower case entries with dashes. Usually these are in english, which is specified by the prefix "en:". I call these the keys.

These keys are however not found in the taxonomies on the wiki. This implies that he key must be "guessed", by using the english entry, changing to lower case and replacing spaces by dashes.

But does this work always?

**Comment by stephanegigandet** [comment]
The taxonomy keys are indeed lowercased, deaccented, and spaces and any non alphanumeric character is replaced by a dash. Multiples dashes are converted to a single dash.

Non latin characters are not converted.

**Comment by stephanegigandet** [comment]
This new json taxonomy export contains keys and translations, as well as direct parents and children: https://github.com/openfoodfacts/openfoodfacts-server/issues/1126

Does it solve the issue?

**Comment by teolemon** [comment]
@aleene does it fix it for you?
