### ISSUE TITLE
Bug - Quality facets - Incorrect flagging because of IU units

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#2580]
### What
Quality flagging IU values as incorrect:
nutrition-value-over-105-vitamin-d3 for 165 IU on this product: 
https://world.openfoodfacts.org/product/8934673576390/100-fresh-milk-vinamilk

### Part of 
- #5538

**Comment by CharlesNepote** [comment]
Here is what the API is answering for the product given as example:
![image](https://user-images.githubusercontent.com/562352/210241247-110a691d-b91d-4160-b9d3-395c038c84e7.png)

All is ok except that 165 IU is converted to `"en-vitamin-d3_100g": 165`

In fact only one product is having this issue: https://mirabelle.openfoodfacts.org/products?sql=select+*+from+%5Ball%5D+%0D%0A%0D%0Awhere+data_quality_errors_tags+%3D%3D+%27en%3Anutrition-value-over-105-en-vitamin-d3%27%0D%0A%0D%0Alimit+21

After a quick investigation, we can see that `Vitamin D3` is not existing in our nutrients.txt taxonomy (see below).

As of 2023-01, [9300+ products](https://mirabelle.openfoodfacts.org/products?sql=select+count%28*%29+from+%5Ball%5D+%0D%0Awhere+ingredients_text+like+%27%25vitamin+D3%25%27%0D%0A) contain "vitamin d3" as an ingredient.

```
zz:vitamin-d
en:Vitamin D, D
xx:Vitamin D, D
af:Vitamien D
ar:فيتامين دي
az:D vitamini
bg:Витамин D
bs:Vitamin D
ca:vitamina D
cs:vitamín D
cy:Fitamin D
da:Vitamin D
de:Vitamin D, D3 (Cholecalciferol)
dv:ވިޓަމިން ޑީ
el:Βιταμίνη D
eo:Vitamino D
es:Vitamina D
et:Vitamiin D, D-vitamiin
eu:D bitamina
fa:ویتامین د
fi:D-vitamiini
fr:Vitamine D, D3 (cholécalciférol), Vitamine D, Vitamine D3, cholécalciférol, calciférol, Vitamine D (Calciférol)
ga:Vitimín D
gl:Vitamina D
he:ויטמין D
hi:विटामिन डी
hr:Vitamin D
hu:D-vitamin
hy:Վիտամին D
id:Vitamin D
is:D-vítamín
it:Vitamina D (colecalciferolo), vitamina D
ja:ビタミン D, ビタミンD
ka:ვიტამინი D
ko:비타민 D
ky:Кальциферол
lt:Vitaminas D
lv:D vitamīns
ml:ജീവകം ഡി
mn:Д витамин
mr:ड-जीवनसत्त्व
ms:Vitamin D
mt:Vitamina D
nb:vitamin D
ne:भिटामिन डी
nl:Vitamine D
nl_be:Vitamine D
nn:vitamin D, D-vitamin
oc:Vitamina D
pa:ਵਿਟਾਮਿਨ ਡੀ
pl:Witamina D
pt:Vitamina D, vitaminas D
ro:Vitamina D
ru:Витамин D
sh:Vitamin D
si:විටමින් D
sk:Vitamín D
sl:Vitamin D
sq:Vitamina D
sr:витамин Д
su:Vitamin D
sv:vitamin D
ta:உயிர்ச்சத்து டி
te:విటమిన్ డి
tg:Витамини D
th:วิตามินดี
tr:D vitamini
tt:D витамины
ug:ۋىتامىن D
uk:Вітамін D
vi:vitamin D
yi:וויטאמין D
zh:维生素D
dv_2016_value:en: 20
dv_value:en: 40
iu_value:en: 0.025
unit:en: µg
wikidata:en: Q175621
wikipedia:en: https://en.wikipedia.org/wiki/Vitamin_D
```
