### ISSUE TITLE
Consider removing normalize_percentage() calls from Tags.pm

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#2589]
`normalize_percentages()` is called a lot when building taxonomies and inside `canonicalize_taxonomy_tag()`.

It is possible that it is not needed, or that we could find more efficient ways to deal with tags that contain the % sign.

Example categories tag that contain a % sign:
```
<en:Kefir
en:Kefir 2.5 %
de:Kefir 2.5 %
fr:Kéfir 2,5 %
ru:Кефир 2.5 %, Кефир 2.5%
```

**Comment by aleene** [comment]
Why not disallow such categories (for the moment)? Not sure if such granularity is useful.

**Comment by stephanegigandet** [comment]
@hangy : shall we close this issue now that you optimized normalize_percentages in https://github.com/openfoodfacts/openfoodfacts-server/pull/2593 ?
