### ISSUE TITLE
Usability - Web UI - Product view completion 'checklist'

### ISSUE THREAD

**Issue by CloCkWeRX** [openfoodfacts/openfoodfacts-server#2595]
**Is your feature request related to a problem? Please describe.**
Currently, when a product is viewed via the web UI, you get an indication it is not yet complete, but not a clear indication of what is incomplete.

![image](https://user-images.githubusercontent.com/365751/68823787-c1165d80-06e4-11ea-9a86-6dfc96446a2f.png)

Power users know to scroll all of the way to the bottom of the view to check the 'states' display, but this is not visible when editing.

![image](https://user-images.githubusercontent.com/365751/68823778-b360d800-06e4-11ea-8708-06b0082012ba.png)

Combined with the save-success page not redirecting to the view afterwards, it means repeatedly editing small aspects of the product require multiple clicks and cycles through to get it as close as possible to complete.

**Describe the solution you'd like**
Provide a smarter checklist control or controls, similar to the android mobile app.

Current:
![image](https://user-images.githubusercontent.com/365751/68823978-4732a400-06e5-11ea-867d-c852fe32e78e.png)

Name; Brand prompt if front photo:
![image](https://user-images.githubusercontent.com/365751/68824055-8a8d1280-06e5-11ea-97f2-d2c83873c69c.png)

Ingredient prompt if ingredients photo

Nutrition prompt if nutrition photo

Category prompt if name, photo or ingredients?

Serving Size prompt if nutrition facts

Quantity prompt if front photo

Packaging prompt if photos

![image](https://user-images.githubusercontent.com/365751/68824295-50704080-06e6-11ea-8258-be196e106cd2.png)

The individual banners should act effectively as edit controls for logged in users.

**Related**
#1005 , #733 - This could be an interim step to 'inline quick edit' UI
#1852 - Faster edit via a hotkey
#658 - Redirecting after save

**Comment by hangy** [comment]
Good idea. Ideally, the edit form could also highlight the fields required for a specific "complete" state.

**Comment by CloCkWeRX** [comment]
A related but minor annoyance - some products are incomplete but can't be completed without obtaining another physical version of the product (blurry or missing photos). The NOVA score sort of acts as a badge of 'minimal' completeness; which I very much like.

Its a pity there aren't really stats on "number of times this product is looked up by UI/API" to get an idea of which products are most popular but least complete; and ways to present that in a TODO list. The states do a good job of individual specific fields; but aren't hooked up to a specific edit UI (mobile app works well for this, hopefully this idea would also improve that).

Would be interesting to introduce a "data quality" metric, similar to https://www.ontotext.com/knowledgehub/fundamentals/five-star-linked-open-data/

ie: Name + photo? That's 1 star quality and immediately useful to a lot of consumers.
Nova score? 3 star quality, able to be compared to others in similar categories
Complete? 5 star quality.
