### ISSUE TITLE
Display additives listed by concentration not alphanumerical order

### ISSUE THREAD

**Issue by kyzh** [openfoodfacts/openfoodfacts-server#26]
One should be able to sort the additives either by:
- their order in the ingredients list
- their alphanumerical order
- their dangerousness.

The default should probably the former, since most ingredients are sorted by percentage within the end product.

**Comment by stephanegigandet** [comment]
Additives are now displayed in the order of the ingredient list. We are phasing out dangerousness, and alphanumerical order is probably not very useful compared to the added complexity of adding a sorting feature.
