### ISSUE TITLE
Tags input field values lost and not saved on Firefox (e.g. categories)

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#2631]
This is really annoying:

When entering categories on Firefox, values are not saved except if they have been typed and "validated" by clicking outside the field.

When saving, new values entered by typing in the field and validating the values with a comma or Enter, or by using the auto-complete will be lost.

It can be observed also when deleting a field using the [x] :

![image](https://user-images.githubusercontent.com/8158668/69268599-bde10d00-0bcf-11ea-9c3c-7fc90d6eaa70.png)

Clicking on the [x] next to the "test" entry automatically deletes other values:

![image](https://user-images.githubusercontent.com/8158668/69268743-026ca880-0bd0-11ea-8f93-e9813e3a59f2.png)

This does not seem to happen in Chrome.

**Comment by VaiTon** [comment]
We should replace jQuery tagsinput with https://bootstrap-tagsinput.github.io/bootstrap-tagsinput

**Comment by hangy** [comment]
> We should replace jQuery tagsinput with https://bootstrap-tagsinput.github.io/bootstrap-tagsinput

We don't use bootstrap, though. 🤔 Adding a second UI library in addition to Foundation just for the tagsinput sounds like overkill. Also, that project seems to be [abandoned](https://github.com/bootstrap-tagsinput/bootstrap-tagsinput/issues/653) and hasn't been updated in the last three years.

**Comment by VaiTon** [comment]
> 
> 
> > We should replace jQuery tagsinput with https://bootstrap-tagsinput.github.io/bootstrap-tagsinput
> 
> We don't use bootstrap, though. 🤔 Adding a second UI library in addition to Foundation just for the tagsinput sounds like overkill. Also, that project seems to be [abandoned](https://github.com/bootstrap-tagsinput/bootstrap-tagsinput/issues/653) and hasn't been updated in the last three years.
> 
> Ideally, we could use a library that doesn't depend on any dependency like jQuery.

It doesn't depend on Bootstrap. It's a jQuery plugin. The fact that it hasn't been updated is valid though. I agree with you on not choosing this library.

**Comment by CharlesNepote** [comment]
Firefox 70.0.1, Ubuntu 18.04 => no bug at all. None of the bug you described. Works perfctly. Weird.

@stephanegigandet Maybe you use an extension or something that conflict with the library. Could you try in "private navigation" or "safe mode"?

@VaiTon @hangy do you also have these behaviors?

**Comment by hangy** [comment]
> @VaiTon @hangy do you also have these behaviors?

I can't reproduce the behaviour with Firefox 70.0.1 on Manjaro.

**Comment by VaiTon** [comment]
> 
> 
> > @VaiTon @hangy do you also have these behaviors?
> 
> I can't reproduce the behaviour with Firefox 70.0.1 on Manjaro.

Me neither with Firefox 70.0.1 on Windows 10

**Comment by stephanegigandet** [comment]
Indeed in private mode it works. Must be one of my extensions. Good :-) I was worried that we were losing tags. Thanks for trying to reproduce the bug everyone!
