### ISSUE TITLE
Remove typo in nutrient cacao

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#264]
The word cacao is spelled as cocoa in the json file.

"cocoa_serving":"52","cocoa_value":"52","cocoa_100g":"52","cocoa":"52","cocoa_label":"Cacao (minimum)"

**Comment by stephanegigandet** [comment]
I think "cocoa" is the most common English form for "cacao" (which is also used, I've seen it on Ghirardelli's chocolate for instance). https://en.wikipedia.org/wiki/Cocoa_bean

I like this comment on https://en.wikipedia.org/wiki/Talk:Cocoa_bean#Cocoa_vs._Cacao :

"My suspicion is that the English word in common usage has long been "cocoa", but that pretentious manufacturers have decided that "cacao" adds to the mystique of their products, especially when these are of the ultra-premium, 70%+ variety. That or people are just trying too hard to "obey" the original word. For practical purposes, I find that "cocoa" is better suited to the patterns of English speech than "cacao". Not scientific evidence, admittedly...--Humphrey20020 17:32, 13 November 2007 (UTC)"

**Comment by aleene** [comment]
I did not realize that both were possible. Its seems that cocoa (or chocolate) should be used for the processed cacao ingredient, that we consume, and that cacao is the raw ingredient. So, here cacao seems more appropriate.

**Comment by highri5e** [comment]
@aleene that's what I've read as well: "Raw **cacao** is made by cold-pressing unroasted **cocoa** beans."

**Comment by teolemon** [comment]
Closing as won't fix ?

**Comment by aleene** [comment]
In my opinion it should be changed to **cacao** and not what it is now. It references the basic ingredient (minimal cacao present).

http://www.onegreenplanet.org/vegan-food/cacao-vs-cocoa-what-you-need-to-know/

**Comment by stephanegigandet** [comment]
In the EU, cocoa is the official term: http://eur-lex.europa.eu/legal-content/EN/TXT/?uri=celex:32000L0036

"3. The labelling of the cocoa and chocolate products defined in Annex I(A)(2)(c), (2)(d), (3), (4), (5), (8) and (9) must indicate the total dry cocoa solids content by including the words: "cocoa solids:... % minimum".

4. For the products referred to in Annex I(A)(2)(b) and (2)(d) (second part of the sentence), the labelling must indicate the cocoa butter content.

5. The sales names "chocolate", "milk chocolate" and "couverture chocolate" specified in Annex I may be supplemented by information or descriptions relating to quality criteria provided that the products contain:

- in the case of chocolate, not less than 43 % total dry cocoa solids, including not less than 26 % cocoa butter,

- in the case of milk chocolate, not less than 30 % total dry cocoa solids and not less than 18 % dry milk solids obtained by partly or wholly dehydrating whole milk, semi- or full-skimmed milk, cream, or from partly or wholly dehydrated cream, butter or milk fat, including not less than 4,5 % milk fat,

- in the case of couverture chocolate, not less than 16 % of dry non-fat cocoa solids."

In the US, it's a mess. Cacao and cocoa are used as synonyms (e.g. in cocoa bean / cacao bean and cocoa butter / cacao butter), but then cocoa is also used as synonym of "breakfast cocoa" which is processed. See http://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfcfr/CFRSearch.cfm?CFRPart=163&showFR=1&subpartNode=21:2.0.1.1.36.2

For white chocolate, the FDA uses a % of "cocoa butter" : http://www.fda.gov/Food/GuidanceRegulation/GuidanceDocumentsRegulatoryInformation/LabelingNutrition/ucm059076.htm

I think we should just continue using cocoa as an identifier, and local apps can display it as Cocoa or Cacao as they see fit.

**Comment by aleene** [comment]
OK, I'll close it.
