### ISSUE TITLE
Negative query tags with a minus sign on second tag does not work if it is on the same tag type than the first tag

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#2657]
If we want to see the products that have a specific category, but that do not have another category, we can construct a query like:

https://world.openfoodfacts.org/category/waters/category/-flavored-waters

But it doesn't work, the resulting query is:

```perl
[
  {
    'categories_tags' => 'en:waters'
  },
  {
    'categories_tags' => 'en:flavored-waters'
  }
]
```

If we reverse the order of the tags like this, it works:

https://world.openfoodfacts.org/category/-flavored-waters/category/waters

Resulting query:

```perl
[
  {
    'categories_tags' => {
      '$ne' => 'en:flavored-waters'
    }
  },
  {
    'categories_tags' => 'en:waters'
  }
]
```

Related to #2285

**Comment by VaiTon** [comment]
But...
![immagine](https://user-images.githubusercontent.com/12072630/69660016-b7dfa600-107f-11ea-9e65-b6371e254215.png)
(from https://world.openfoodfacts.org/category/waters/category/-flavored-waters)
