### ISSUE TITLE
Updated PostgreSQL causes issues in docker

### ISSUE THREAD

**Issue by VaiTon** [openfoodfacts/openfoodfacts-server#2658]
After the PostgreSQL update done in commit 7dc5ae0d6c75d9168db13e140fee1ff171be4435 datas are not compatible.

**This is not an issue, this is a warning about compatibility.**

`DETAIL:  The data directory was initialized by PostgreSQL version 11, which is not compatible with this version 12.1.`

**Comment by hangy** [comment]
Apparently this is quite an issue. A lot of docker containers do those upgrades themselves, but postgres doesn't:
- https://github.com/docker-library/postgres/issues/37
- https://github.com/bwbroersma/docker-postgres-upgrade
- https://github.com/tianon/docker-postgres-upgrade/blob/master/11-to-12/Dockerfile

Based on above links, it appears that everyone will need to do this on their own. I'll be more careful with updating those image tags after this. 🙁
