### ISSUE TITLE
Make it clearer what is needed to get the Nutri-Score and NOVA groups

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#2662]
### What

- [ ] Make it clearer on the Product page what is needed to get the Nutri-Score and NOVA groups.
  - [ ] "Add the category to get the Nutri-Score"
  - [ ] "Add the category and nutrition facts to get the Nutri-Score"
  - [ ] "Add the ingredients to get the degree of food processing (NOVA)"

### Design documents
Look for the use-cases in the API doc
- Nutriscore for 3rd party apps
- Ingredient features for 3rd party apps 

### Part of 
- #5708

**Comment by CloCkWeRX** [comment]
Related: #2595

**Comment by teolemon** [comment]
This is fixed.
