### ISSUE TITLE
Add support for XLSX format for on-demand exports (through search feature)

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#2666]
When searching for products, it's currently possible to export CSV files. We have a lot of people who have trouble to open them in Excel (which needs to be told the encoding + the separator (tab)).

We could use https://metacpan.org/pod/Excel::Writer::XLSX to output an XLSX file.

**Comment by teolemon** [comment]
There is a similar library for ODT: https://metacpan.org/pod/distribution/OpenOffice-OODoc/OODoc/Intro.pod

**Comment by stephanegigandet** [comment]
Deployed.
