### ISSUE TITLE
Make Product Opener deployable on PaaS (Heroku, Scalingo)

### ISSUE THREAD

**Issue by nicolasleger** [openfoodfacts/openfoodfacts-server#267]
- https://news.ycombinator.com/item?id=3570894
- https://github.com/judofyr/perloku
- https://github.com/miyagawa/heroku-buildpack-perl

**Comment by teolemon** [comment]
Do you mean Make Product Opener deployable on Heroku ?

**Comment by nicolasleger** [comment]
Yes or via Docker so it could be easier to setup a new environment for development or testing.

**Comment by nicolasleger** [comment]
For Docker purpose #306

**Comment by teolemon** [comment]
it's been dockerized. Heroku is a pricey platform, and I don't feel like we should be investing time to fit ProductOpener into the constraints of Heroku

**Comment by teolemon** [comment]
can I close, since #306 has been solved ?
