### ISSUE TITLE
Make account creation easier on editing

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#2673]
![image](https://user-images.githubusercontent.com/1689815/69830631-0333b900-1226-11ea-831c-e397ca229ef8.png)

**Comment by hangy** [comment]
How could we make this work if we actually checked that the mail address is valid, as (IMHO correctly) proposed in #2650?

**Comment by VaiTon** [comment]
The user has to verify his email before logging in so no problem

**Comment by muskangarg21** [comment]
@stephanegigandet @hangy 
What needs to be done in this issue ?

**Comment by teolemon** [comment]
Adding a button linking to account creation in the login page shown when you click on edit this product (as shown on the mockup).
Currently we only show a link on "register in 30 seconds", but it's not visible enough.

**Comment by muskangarg21** [comment]
@teolemon  
I am getting this error while trying to edit the page locally. it is showing when I try to edit a product while i am logged out. 
<pre>
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at contact@productopener.localhost to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.
Apache/2.4.38 (Debian) Server at world.productopener.localhost Port 80
</pre>

**Comment by muskangarg21** [comment]
and the code needs to be added in `po/common/en.po` correct ?

**Comment by teolemon** [comment]
Strings should be added in po/common/common.pot

**Comment by muskangarg21** [comment]
I am unable to test it locally,
although I think adding this line in `cgi/product_multilingual` will make it work
`<input type="submit" name=".create_account" value="$Lang{login_create_your_account}{$lc}" class="button small" />
@teolemon what do you say ?
`

**Comment by stephanegigandet** [comment]
@muskangarg21 : you can run the cgi script on the command line:

cd /srv/off/scripts (change /srv/of/ with path of your install)
export PERL5LIB=.
perl ../cgi/product_multilingual.pl
-> that will show you error messages showing which lines may be responsible

There are also error logs from Apache+mod_perl in /srv/off/logs/
