### ISSUE TITLE
Consider replacing jQuery UI

### ISSUE THREAD

**Issue by hangy** [openfoodfacts/openfoodfacts-server#2675]
I've been running a few website performance tests, and at least for mobile, Lighthouse points out that we load `jquery-ui.js` (587 KB pre-gzip) on all pages. Not only is this the largest single JS file we have, but it's stylesheet is also the largest file render-blocking resource after `app.css` (which is mainly Foundation 5, our main UI library).

- [x] The jQuery UI portion used by [blueimp-file-upload](https://github.com/blueimp/jQuery-File-Upload) can be replaced by [jquery.ui.widget](https://www.npmjs.com/package/jquery.ui.widget) which is around 15 KB (pre-gzip)
- [x] `autocomplete` is only really used for nutrients - this can probably replaced by [awesomplete](https://leaverou.github.io/awesomplete/) (or maybe even [select2](https://select2.org/), which we already load anyways)
- [x] `tagsInput` (which uses `autocomplete`) is [not maintained any more](https://github.com/xoxco/jQuery-Tags-Input), so it might be worthwhile to switch to a modern alternative like [tagify](https://github.com/yairEO/tagify)

**Comment by BathoryPeter** [comment]
jqueryui.com allows building custom packages. Just uncheck Toggle All and then check only the needed modules. It will pay attention to dependencies automatically.
For example enabling only autocomplete module (and its dependencies), jquery-ui.min.js is only 32 kB.

**Comment by hangy** [comment]
> jqueryui.com allows building custom packages. Just uncheck Toggle All and then check only the needed modules. It will pay attention to dependencies automatically.
> For example enabling only autocomplete module (and its dependencies), jquery-ui.min.js is only 32 kB.

That's a good suggestion. Thanks! I suppose we might also be able to achieve this by using just some source files form `jquery-ui` npm package instead of `jquery-ui-dist`.
