### ISSUE TITLE
Builds are failing because of node-sass and/or node-gyp

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#2678]
https://travis-ci.org/openfoodfacts/openfoodfacts-server/builds/618510886?utm_source=github_status&utm_medium=notification

136.07s$ yarn install
yarn install v1.19.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > @bower_components/leaflet.markercluster@1.4.1" has incorrect peer dependency "leaflet@~1.3.1".
warning " > leaflet.markercluster@1.4.1" has incorrect peer dependency "leaflet@~1.3.1".
[5/5] Building fresh packages...
error /home/travis/build/openfoodfacts/openfoodfacts-server/node_modules/node-sass: Command failed.

[..]

**Comment by stephanegigandet** [comment]
Is it normal that travis is using yarn to install dependencies @hangy ?

**Comment by hangy** [comment]
The build is for the 'robots.txt' branch, which is about 3000 commits behind 'master', and still contains a 'yarn.lock'. It should or be rebased.

**Comment by VaiTon** [comment]
Should be fixed with f5bb179c4d811ec7d47ff37311a560bfb6ed4323
