### ISSUE TITLE
Return 404 status code for the related page

### ISSUE THREAD

**Issue by Adraenwan** [openfoodfacts/openfoodfacts-server#268]
Currently, when you try to access a page that does not exists, you are redirected to the "error: invalid address", but the server returns a 200 status code.

This is particularly annoying for an API call, ie: http://world.openfoodfacts.org/foo/bar.json in this case, i expect json, but i get html, which makes error handling more tricky.

Returning a 404 status code would be more appropriate.

**Comment by hangy** [comment]
What about adding a 2nd optional parameter to `display_error`, which would be the status code? That would allow us to return the correct status code for different cases, ie. `display_error(sprintf(lang("no_product_for_barcode"), $code), 404);` or `        display_error("Permission refusée", 403);`. If no status code is defined, 500 could be used instead to avoid any error page being indexed by search engines.

**Comment by hangy** [comment]
This was integrated in [5991325](https://bitbucket.org/openfoodfacts/product-opener/commits/5991325e35cd17a7ec2a93ba79fc08d54aca4215) and is now live on openfoodfacts.org and openbeautyfacts.org. Thanks for the request!
