### ISSUE TITLE
Rearchitect madenearme

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#2688]
https://madenear.me , https://madenear.me.uk and https://cestfabriquepresdechezvous.fr are static pages that have been generated with CGI scripts that can Display.pm search_and_map() function. They are basically ProductOpener's search function with the option of displaying result on a map.

We have a nightly cron job to generate them:

*/45 1 * * *    wget -q -O /srv/off/html/cestemballepresdechezvous.html http://fr.openfoodfacts.org:8001/cgi/madenearyou.pl
*/50 2 * * *    wget -q -O /srv/off/html/madenearme-uk.html http://uk.openfoodfacts.org:8001/cgi/madenearme.pl
*/55 3 * * *    wget -q -O /srv/off/html/madenearme.html http://world.openfoodfacts.org:8001/cgi/madenearme.pl

The generation actually takes a lot of time, so much time (and memory) that it actually crashes sometime.

This bug is to:

1. Replace cgi/madenearme.pl and cgi/madenearyou/pl by script/generate_madenearme_page.pl so that we have a script that we can call outside of modperl to generate the HTML pages.

2. Investigate how to speed up the page generation.

**Comment by stephanegigandet** [comment]
Note: this bug is not for solving the issue that generating a huge static html file should be instead replaced by some kind of map where elements are loaded dynamically. That would be another bug. :)

**Comment by hangy** [comment]
> Note: this bug is not for solving the issue that generating a huge static html file should be instead replaced by some kind of map where elements are loaded dynamically. That would be another bug. :)

That's #1668 😉

**Comment by stephanegigandet** [comment]
So it turns out that a huge chunk of the time is actually used by the MongoDB perl driver to retrieve and process the results:

Profile of ./generate_madenearme_page.pl for 151s (of 156s), executing 6122657 statements and 1977824 subroutine calls in 742 source files and 266 string evals.


Calls | P | F | ExclusiveTime | InclusiveTime | Subroutine
-- | -- | -- | -- | -- | --
847 | 2 | 1 | 131s | 131s | MongoDB::_Link::CORE:sselect (opcode)
101 | 1 | 1 | 5.67s | 5.67s | BSON::XS::_decode_bson (xsub)
284 | 1 | 1 | 2.09s | 2.09s | Storable::pretrieve (xsub)
63345 | 13 | 5 | 1.16s | 1.37s | ProductOpener::Store::get_string_id_for_lang
1 | 1 | 1 | 1.07s | 10.4s | ProductOpener::Index::BEGIN@51

I was doing something very stupid: I didn't make a projection to get only the few fields we need, so we were getting all the fields from all the matching products...

We get a 10x speed improvement just by restricting the fields returned:

get_products_collection()->query($query_ref)
			->fields( { code => 1, lc => 1, product_name => 1, "product_name_$lc" => 1, brands => 1, images => 1,
				manufacturing_places => 1, origins => 1, emb_codes_tags => 1,
			});

Profile of ./generate_madenearme_page.pl for 13.8s (of 17.8s), executing 5695033 statements and 1866202 subroutine calls in 742 source files and 266 string evals.


Calls | P | F | ExclusiveTime | InclusiveTime | Subroutine
-- | -- | -- | -- | -- | --
284 | 1 | 1 | 2.09s | 2.09s | Storable::pretrieve (xsub)
1 | 1 | 1 | 1.10s | 10.4s | ProductOpener::Index::BEGIN@51
63345 | 13 | 5 | 1.06s | 1.28s | ProductOpener::Store::get_string_id_for_lang

**Comment by stephanegigandet** [comment]
Fixed and deployed.
