### ISSUE TITLE
E316 additive not properly detected

### ISSUE THREAD

**Issue by PhoenixOFF** [openfoodfacts/openfoodfacts-server#269]
L'additif E316 n'est pas (ou plus) détecté dans la liste des ingrédients sous la mention "Erythorbate de sodium" ou "érythorbate de sodium". Par contre, il est mentionné si l'on indique dans la liste des ingrédients "isoascorbate de sodium".
Exemple : Produit ajouté le 07/05/2016 avec "érythorbate", E316 non détecté : http://fr.openfoodfacts.org/produit/3180940081226/mes-lardons-fumes-madrange
Produit ajouté le 02/04/2015 avec "isoascorbate", E316 détecté : http://fr.openfoodfacts.org/produit/7613034781291/tendre-noix-superieur-sans-couenne-4-tranches-lot-de-2-1-gratuit-herta

**Comment by teolemon** [comment]
`en:E316, Sodium erythorbate
bg:E316, Натриев ериторбат
cs:E316, Erythorban sodný, Erythorbát sodný
da:E316, Natriumerythorbat
de:E316, Natriumisoascorbat, E 316, Natriumerythorbat
el:E316, Ερυθορβικο νατριο
es:E316, Eritorbato sódico, Eritorbato de sodio, D-isoascorbato, E 316
et:E316, Naatriumerütorbaat
fi:E316, Natriumerytorbaatti
fr:E316, Erythorbate de sodium, Isoascorbate de sodium, Érythorbate de sodium, 7378-23-6
hu:E316, Nátrium-eritroaszkorbát
it:E316, Eritorbato di sodio
lt:E316, Natrio eritorbatas
lv:E316, Nātrija eritorbāts
mt:E316, Eritorbat tas-sodju
nl:E316, Natriumerythorbaat
pl:E316, Izoaskorbinian sodu
pt:E316, Eritorbato de sódio
ro:E316, Eritorbat de sodiu
ru:E316, Эриторбат натрия
sk:E316, Erytorban sodný (izoaskorban sodný)
sl:E316, Natrijev eritorbat
sv:E316, Natriumisoaskorbat, E 316
e_number:en:316
wikidata:en:Q417003
`
Here's the current version on http://en.wiki.openfoodfacts.org/Global_additives_taxonomy

**Comment by teolemon** [comment]
http://world.openfoodfacts.org/api/v0/product/20021382.json

[4:05 PM]  
"ingredients_debug":["74% viande de dindonneau",null," eau",null," sel",null," dextrose",null," sirop de glucose",null," fibre de pois",null,"  ",null," ",null," diphosphates",null," triphosphates",null," polyphosphates",null,"",null,"  ",null,"  algues eucheuma transformées",null,"  ",null,"  érythorbate de sodium",null," arômes",null," arôme de fumée",null," paprika et extrait de paprika",null," gélatine de bœuf",null,"  ",null,"  caramel",null,"  ",null,"  nitrite de sodium."," paprika","extrait de paprika"]

[4:06 PM]  
"additives_tags":["en:e450","en:e451","en:e452","en:e407a","en:e160c","en:e441","en:e150","en:e250"],

[4:06 PM]  
"additives_old_tags":["en:e450","en:e451","en:e452","en:e316","en:e160c","en:e441","en:e150a","en:e250"],

[4:06 PM]  
bingo

[4:06 PM]  
additives_prev_tags":["en:e450","en:e451","en:e452","en:e407a","en:e160c","en:e441","en:e150","en:e250"]

[4:08 PM]  
fr:E316, Erythorbate de sodium, Isoascorbate de sodium, Érythorbate de sodium, 7378-23-6

**Comment by teolemon** [comment]
This one is pretty problematic.

**Comment by teolemon** [comment]
https://fr.openfoodfacts.org/additif/e316-erythorbate-de-sodium

**Comment by stephanegigandet** [comment]
Fixed in production.
