### ISSUE TITLE
Add input fields for language and or country in the query part of the API HTTP requests

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#271]
Related to bug #270 : allow to specify country code and/or language code in the fields of the HTTP API request instead of using the subdomain.

**Comment by stephanegigandet** [comment]
Maybe adding ?lc=fr&cc=be to the GET urls (or as POST parameters)

**Comment by Nymerea** [comment]
and add the possibility to get lc and cc throughout the api .

For example off.org/api/list_countrycode.xml

and return something like : 
<countries>
<country code="be" langue="fr"> Belgium</country>
<country code="fr" langue="fr">France</country>
...
</countries>

**Comment by stephanegigandet** [comment]
Currently tested on preprod: http://world.preprod.openfoodfacts.org/cgi/search.pl?search_terms=coke&search_simple=&cc=fr&lc=it

**Comment by stephanegigandet** [comment]
Live on production. You can now add cc and lc query parameters to the url. They will override the subdomain.

**Comment by stephanegigandet** [comment]
The way it works:

1. By default, the country code (cc) and language of the interface (lc) are set through the subdomain.
e.g. 
1.1. world.openfoodfacts.org --> cc = world, lc = en (default language for the "country")
1.2 fr.openfoodfacts.org --> cc = fr (France), lc = fr (French)
1.3 jp.openfoodfacts.org --> cc = jp (Japan), lc = ja (Japanese)
1.4 ch.openfoodfacts.org --> cc = ch (Switzerland), lc = de (German, set as main language for Switzerland)
1.5 ch-fr.openfoodfacts.org --> cc = ch, lc = fr (French)

2. If you pass ?cc=us and/or &lc=it, it will set the country to US and the language to Italian

-> if you just pass cc, the lc will be the one set in the subdomain.
e.g. world.openfoodfacts.org + cc = fr --> cc = fr, lc = en (default language of world)

3. The cc affects which results are returned. cc = fr -> you get only products with France listed in the countries where sold field.

4. The lc affects the language in which results will come back.

5. If the results include links to products, those links will use a new subdomain that corresponds to the overrides.
