### ISSUE TITLE
The json field "no_nutrition_data" is not a bool

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#276]
It would be nice if the field "no_nutrition_data" is listed as a BOOL. Now the values are either NULL or "on". Now I interpret NULL as false.

**Comment by benbenben2** [comment]
Examples 


"no_nutrition_data":"on"
https://world.openfoodfacts.org/api/v3/product/7630311550593.json

"no_nutrition_data":""
https://world.openfoodfacts.org/api/v3/product/3250391545025.json

**Comment by aleene** [comment]
too old
