### ISSUE TITLE
may I insert korean food informaion?

### ISSUE THREAD

**Issue by 2jaeyeol** [openfoodfacts/openfoodfacts-server#2771]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

I want insert korean food information if i success build. 
or distribute good first issue, may I?

**Comment by stephanegigandet** [comment]
Hi @2jaeyeol , you can add Korean food products on https://kr.openfoodfacts.org/
