### ISSUE TITLE
Error on the Translators table

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#2777]
![image](https://user-images.githubusercontent.com/1689815/70731897-d1cbea80-1d07-11ea-9ccb-ab98893c19b7.png)
https://de.openfoodfacts.org/cgi/top_translators.pl

**Comment by hangy** [comment]
When opened with Google Spreadsheets, there are no 335 rows, so it could be possible that Data tables has a problem parsing the some CSV content, or that there are trailing control chars. (I'm not at my PC right now and don't have a good editor to check that.)

BTW: On the plus side, the CORS issue when loading the data has been fixed! 🎉
