### ISSUE TITLE
Undefined author and date in the Admin photo management section

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#2783]
![image](https://user-images.githubusercontent.com/1689815/70862437-d2999200-1f3c-11ea-809d-d8cbfca1d119.png)
Undefined author and date in the Admin photo management section

**Comment by stephanegigandet** [comment]
Found the issue, something I forgot when I introduced the checkboxes to declare moderators. The uploader and uploaded date fields were only set for admins and not for the moderators.
