### ISSUE TITLE
Compute minimum and maximum percentage of ingredients and sub-ingredients

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#2793]
Ingredients lists are ordered by quantity, and sometime contain % for some ingredients.
We can use that information to compute the maximum amount of each ingredient, based on the available information.

e.g. : https://fr.openfoodfacts.org/produit/3178530408515/petits-muffins-au-chocolat-bonne-maman

"Sucre, œufs frais, beurre frais, farine de blé tendre, chocolat (13 %) (sucre, pâte de cacao, beurre de cacao, émulsifiant : lécithine de tournesol), poudre d'amande, sirop de sucre inverti, poudre de cacao, praliné (sucre, noisettes, huile de noisette) arôme naturel de cacao, poudres à lever (diphosphates et carbonate de sodium (blé)), sel, émulsifiant : lécithines (soja)."

The second ingredient "oeufs frais" is at most 50% of the product. Given that the 5th ingredient (chocolate) is 13%, we can assume that the 3rd and 4th ingredients are at least 13% too. Which means the first 2 ingredients are at most 100 - 3 * 13 = 61. So the 2nd one cannot be more than half of that: 30.5.

We can also try to do the same for sub ingredients. e.g. if we have 13% chocolate, and the first sub-ingredient of chocolate is sugar, then the 2nd sub-ingredient "pâtes de cacao" cannot be more than 6.5% of the total product.

**Comment by teolemon** [comment]
An interesting feature would be to send back the average percentage for the matching cat.

**Comment by stephanegigandet** [comment]
Deployed.
