### ISSUE TITLE
API V3: "-" sign should be excluded from field names 

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#2796]
`-` should be excluded from field names in the V3 of the API because Python considers it a minus.

'energy-kcal_unit'  is read as: `energy`-`kcal_unit`

**Comment by raphael0202** [comment]
@teolemon can you tell me more about it? I can't see myself any issue on Python side

**Comment by teolemon** [comment]
It created issues in a script I wrote when assigning variables

**Comment by raphael0202** [comment]
Can you copy the script hère?

**Comment by stephanegigandet** [comment]
@teolemon : can you attach the script to this bug?

**Comment by teolemon** [comment]
cannot find it but:
```  
A variable can have a short name (like x and y) or a more descriptive name (age, carname, total_volume). Rules for Python variables:
A variable name must start with a letter or the underscore character
A variable name cannot start with a number
A variable name can only contain alpha-numeric characters and underscores (A-z, 0-9, and _ )
Variable names are case-sensitive (age, Age and AGE are three different variables)
```

**Comment by teolemon** [comment]
https://www.w3schools.com/python/python_variables.asp

**Comment by raphael0202** [comment]
Sure, but you don't have to name your variable the same name as the field in the JSON returned by the API.

`energy_kcal_unit = data['energy-kcal_unit']`

**Comment by stephanegigandet** [comment]
This should not be an issue and having different names in MongoDB/OFF and the API would be really cumbersome, so I would rather not change the field names.
