### ISSUE TITLE
_label is French centric

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#2799]
"vitamin-d_label":"Vitamine D / D3 (cholécalciférol)"

**Comment by hangy** [comment]
Do you have a sample product? I think this probably depends on the product's main language (which some apps falsely set to French).

**Comment by teolemon** [comment]
Mmh. Not right now (on mobile)

**Comment by stephanegigandet** [comment]
the *_label fields contain whatever the user typed or selected in the dropdown, it is only for internal use to convert values. It should not be used by any app. In fact I think I'll just remove it in the new version of the API, along with the _value, _unit and no suffix fields. i.e. leave only salt_100g and salt_serving
