### ISSUE TITLE
Use international standards for date format: ISO 8601

### ISSUE THREAD

**Issue by kyzh** [openfoodfacts/openfoodfacts-server#28]
Looking at the date for when this product was added is misleading at best (12/14/14) http://uk.openfoodfacts.org/product/00939928

We should try to aim for something like the following http://en.wikipedia.org/wiki/ISO_8601

**Comment by hangy** [comment]
I unintentionally fixed this in 06e6636. Product Opener now uses the DateTime Perl module to output the date in the language of the subdomain, and it uses the `time` tag in order to provide a machine readable ISO 8601 version of the date. Example:
```html
<p>Produkt hinzugefügt am <time datetime="2015-01-18T17:08:31">18. Januar 2015 17:08:31 CET</time> von <a href="/beitragszahler/hangy">hangy</a></p>
```
