### ISSUE TITLE
Integrate Hunger Games on the category, labels and brands pages

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#2804]
### What
- Now that we can category target Hunger Games to categories, a link on the category, label and brand page for logged in users would be nice
- Note: the website layout is about to change
### Screenshot of the Power User Script implementation
![image](https://user-images.githubusercontent.com/1689815/201352819-dc10fdc7-4c35-4960-b1e0-6196c5f746be.png)

### Code pointers
- https://hunger.openfoodfacts.org/questions?type=category&value_tag=en%3Aalcoholic-beverages
- https://github.com/openfoodfacts/power-user-script
```
<sup><a class="button tiny round secondary label" href="https://hunger.openfoodfacts.org/questions?type=category&amp;value_tag=en:crystallized-ginger">Help categorize more of these</a></sup>
```

**Comment by raphael0202** [comment]
The country can be specified in the url as follow:
`https://hunger.openfoodfacts.org/questions?type=category&country=en:france&value_tag=en:bananas`

**Comment by stephanegigandet** [comment]
https://robotoff.openfoodfacts.org/api/v1/questions/random?lang=fr&count=10&insight_types=category&value_tag=en:cakes&country=en:france to get the count.

**Comment by alexgarel** [comment]
This may also come with https://github.com/openfoodfacts/facets-knowledge-panels
