### ISSUE TITLE
Wrong icons on the Ingredient Analysis Icons endpoint

### ISSUE THREAD

**Issue by matotim** [openfoodfacts/openfoodfacts-server#2811]
**Summary:** 

On the endpoint https://ssl-api.openfoodfacts.org/files/app/ingredients-analysis.json, the vegan and vegetarian icons are switch.

**Expected behavior:** 

`"en:maybe-vegan": {
		"type": "vegan",
		"icon": "leaf",
		"color": "#ff6600"
	},
	"en:non-vegan": {
		"type": "vegan",
		"icon": "leaf",
		"color": "#ff0000"
	},
	"en:vegan": {
		"type": "vegan",
		"icon" : "leaf", 
		"color": "#00aa00"
	},
	"en:vegan-status-unknown": {
		"type": "vegan",
		"icon" : "leaf", 
		"color": "#8c8c8c"
	},
	"en:vegetarian": {
		"type": "vegetarian",
		"icon" : "egg", 
		"color": "#00aa00"
	},
	"en:maybe-vegetarian": {
		"type": "vegetarian",
		"icon" : "egg", 
		"color": "#ff6600"
	},
	"en:non-vegetarian": {
		"type": "vegetarian",
		"icon" : "egg", 
		"color": "#ff0000"
	}, 
	"en:vegetarian-status-unknown": {
		"type": "vegetarian",
		"icon" : "egg", 
		"color": "#8c8c8c"
	},`

**Observed behavior:** 

`"en:maybe-vegan": {
		"type": "vegan",
		"icon": "egg",
		"color": "#ff6600"
	},
	"en:non-vegan": {
		"type": "vegan",
		"icon": "egg",
		"color": "#ff0000"
	},
	"en:vegan": {
		"type": "vegan",
		"icon" : "egg", 
		"color": "#00aa00"
	},
	"en:vegan-status-unknown": {
		"type": "vegan",
		"icon" : "egg", 
		"color": "#8c8c8c"
	},
	"en:vegetarian": {
		"type": "vegetarian",
		"icon" : "leaf", 
		"color": "#00aa00"
	},
	"en:maybe-vegetarian": {
		"type": "vegetarian",
		"icon" : "leaf", 
		"color": "#ff6600"
	},
	"en:non-vegetarian": {
		"type": "vegetarian",
		"icon" : "leaf", 
		"color": "#ff0000"
	}, 
	"en:vegetarian-status-unknown": {
		"type": "vegetarian",
		"icon" : "egg", 
		"color": "#8c8c8c"
	},`

**Comment by stephanegigandet** [comment]
Thanks for the report @matotim , it's fixed.
