### ISSUE TITLE
SSL certificate error on openfoodfacts.eu

### ISSUE THREAD

**Issue by sashabrava** [openfoodfacts/openfoodfacts-server#2816]
I've noticed one of my added products on domain .EU instead of .ORG (https://world-pt.openfoodfacts.eu/produto/5900820000066/mlekopol) and decided to check what it is. 
It seems to be a copy of your normal server .ORG, but I haven't found any info about it in the documentation. 

https://openfoodfacts.eu redirects to .org domain, while others (be.openfoodfacts.eu and others) work without redirection, plus they're available via Google Search with broken SSL certificate (it uses certificate issued to .org domain and Google Chrome doesn't trust it). 

**Smartphone :**
 - Device: Xiaomi
 - OS: Android 5.1.1
 - Browser: Chrome
 - Version: 77.0

**Comment by stephanegigandet** [comment]
Thanks for the report. the .EU domain was used for a test at some point, I removed it, and changed the configuration to serve a 404 for all domains that are not configured. There's no SSL certificate for the EU domain, I don't intend to make one as we don't use the domain. So hopefully will just remove those URLs soon.

New nginx config in this pull request: https://github.com/openfoodfacts/openfoodfacts-server/pull/2839
