### ISSUE TITLE
Packager codes not applied correctly

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#2821]
Packager codes not applied correctly the "EMB 13078" hasn't been stored
``` 
October 13, 2019 at 4:00:45 PM CEST - roboto-app - (app)Adding packager codes 'FR 29.046.532 EC,EMB 13078' (automated edit, ID: 61571c95-5fda-45dd-bf63-1d6bb5a4393e) - view
```
https://world.openfoodfacts.org/product/3564700119419/filets-de-sardines-huile-d-olive-peche-ocean

**Comment by stephanegigandet** [comment]
It seems packaging codes are now correctly added through Robotoff, e.g. https://world.openfoodfacts.org/product/2273693024938/jambon-superieur-avec-couenne-4-tranches

Closing this bug, reopen if you see a new instance of the problem.
