### ISSUE TITLE
'List of editors' page is loaded around 5 minutes

### ISSUE THREAD

**Issue by sashabrava** [openfoodfacts/openfoodfacts-server#2826]
Issue 1. The server has a page https://world.openfoodfacts.org/editors, which allows to get a list of users and amount of their contributions. However, the browser was waiting around 45s to get response from server and around 4.5 min to load the data (browser was consuming over 1GB RAM at that time).
![openfoodfacts](https://user-images.githubusercontent.com/11160215/71725925-d3d02780-2e35-11ea-9f34-ad7b3496cd9b.png)

Seems like this page makes a hard request on the database (I assume it calculates edits of 600.000 users in real time), and it gives a worry that such page might be used for an attack to slow down your server performance (what will happen if there are 100 such requests at the same time?).

Issue 2. I was scrolling the result, and there are users with weird nicknames - 
https://world.openfoodfacts.org/editor/yuka.SEpJYUliczlsL1lycTh3NXhCUEU1TlpFbVppTVpHanNPcnM3SUE9PQ
https://world.openfoodfacts.org/editor/yuka.UjRjeUhLazdvdFlnbk1JdTVSREY2b2w4bk03d2UyMkdkOVlqSVE9PQ
Their nickname in the database is shown as "yuka - user", and repeats multiple times. Seems like they are bots or auto-generated users (many of them have same amount of edits).

**Solutions**
If the page has only few views per day, it makes sense to calculate values once a day and show them 1000 per page with numeration (so that mobile devices won't go crazy).

**Comment by hangy** [comment]
Good catch! This is probably the same underlying issue as #262. In this case, the list is 88 MiB of dynamically generated HTML, which first needs to be downloaded and then gets made filterable/sortable client-side by [DataTables](http://datatables.net/). The reason why `/editors` is now this long is because of the changes in #1975.
