### ISSUE TITLE
CO2 footprint mission does not work

### ISSUE THREAD

**Issue by pamputt** [openfoodfacts/openfoodfacts-server#283]
Hello, it appears that no one earn yet the CO2 footprint mission award (http://fr.openfoodfacts.org/mission/releveur-d-empreintes)
I do not know for other but I think I already filled more than 3 different product with this CO2 footprint (I can provide you a list if you need). So probably something is not enable on the server side for this mission.

**Comment by TaciteOFF** [comment]
All the missions have been disabled a while ago

**Comment by pamputt** [comment]
Ok. Does it mean that it is planned to debug the mission and to enable them again once it will be done? If so, is there a bug report that track the mission issues?

**Comment by stephanegigandet** [comment]
Just created bug #284 for the missions system rearchitecture.

**Comment by hangy** [comment]
Closing this in favour of #284
