### ISSUE TITLE
Wrong parsing of UUID in edit comment for "(app)Updated via Power User Script" results in empty editor named Script

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#2835]
Some apps send user identifiers (UUIDs) in edit comments, there is a regexp that tries to find them, and there is a false positive for "(app)Updated via Power User Script - view"

This results in "Script" being added to editors_tags, which can then be seen in list of editors.

**Comment by stephanegigandet** [comment]
product: https://world.openfoodfacts.org/product/3113010126602/foie-gras-de-canard-entier-a-l-ancienne-larnaudie-prestige

https://world.openfoodfacts.org/entry-date/2019-12-01/editors


date-limite-app | 11
-- | --
script | 10
bank-pc | 9

**Comment by hangy** [comment]
Maybe related to #2592, where the description doesn't match the regex.
