### ISSUE TITLE
Support .HEIC / HEIF Upload

### ISSUE THREAD

**Issue by bredowmax** [openfoodfacts/openfoodfacts-server#2851]
**Is your feature request related to a problem? Please describe.**
I wish OFF on desktop would support uploading .HEIC photos - this is the format my iPhone saves photos to save space

**Describe the solution you'd like**
I wish OFF would take care of those conversions so I don't have to.

**Describe alternatives you've considered**
It's possible to convert locally with a free app called HEIC Converter that is available on the MacOS appstore

**Additional context**
https://openfoodfacts.slack.com/archives/C02LDQDDD/p1578854003049700

**Comment by stephanegigandet** [comment]
I looked a bit into that, imagemagick has support for HEIC in debian buster, but not in debian stretch (which we are running in production right now). It might be possible to build it from source, but I'm reluctant to do that as we had Apache + mod_perl crashing with the perlmagick modules and it was a lot of trouble to finally get a version of imagemagick that didn't crash in production.

So we definitely will be able to do it someday, but maybe not soon.

**Comment by teolemon** [comment]
http://stuffjasondoes.com/2019/07/10/batch-convert-heic-to-jpg-in-linux/

**Comment by teolemon** [comment]
it seems that there are alternative packages ?

**Comment by stephanegigandet** [comment]
Uploading HEIC images is now supported. Like PNG images, we convert them to JPEG.
