### ISSUE TITLE
Picture rotation bad behavior

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#2859]
**Describe the bug**
The picture shown doesn't follow user's choice.

**To Reproduce**
1. Edit https://world.openfoodfacts.org/product/3102627000115/calissons-d-aix-du-roy-rene-confiserie-du-roy-rene
2. Eventually unselect picture.
3. Select front picture (=> the picture auto-rotate which is weird).
4. Validate.
5. The picture is not rotated as you want.

**Comment by stephanegigandet** [comment]
I think that's an old bug: iOS was sending images with some rotate flag in EXIF metadata or something, and it was handled badly. I don't think it happens anymore, so I'd be in favour of closing this bug unless we find many more examples.

**Comment by stephanegigandet** [comment]
Closing.
