### ISSUE TITLE
Divide status between: TODO and DONE

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#2866]
![image](https://user-images.githubusercontent.com/1689815/72783344-76eeb280-3c26-11ea-8322-21ad5dbcb86b.png)
Note: the sorting is bogus, as you might notice ;-)

**Comment by areeshatariq** [comment]
@teolemon what needs to be done on this issue?

**Comment by stephanegigandet** [comment]
@areeshatariq : if you look at the Status displayed at the Bottom of each product page on OFF, all the statuses are on one-line. We want to separate them on 2 lines, based on whether the status indicates Something is done ("Nutrition facts completed" etc.) or not done ("Photos to be uploaded").

**Comment by VaiTon** [comment]
Still not completely fixed. It only works for english language.

**Comment by VaiTon** [comment]
Has this been deployed to production? @stephanegigandet
