### ISSUE TITLE
There is an issue with allergens. They are now doubled http://fr.openfoodfacts.org/produit/3263859491512/tarte-chevre-epinards-leader-price

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#287]
Substances ou produits provoquant des allergies ou intolérances : Œufs, Gluten, Lait, Huevos, Leche, Leite, Nata, Ovos, Queijo, Queso, Trigo

**Comment by stephanegigandet** [comment]
Thanks for the report, this is now fixed.
