### ISSUE TITLE
Tabs not properly updated for multilingual product

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#2880]
![image](https://user-images.githubusercontent.com/1689815/73156906-9b8fd200-40df-11ea-9df0-0521ddd370c3.png)

![image](https://user-images.githubusercontent.com/1689815/73157007-f3c6d400-40df-11ea-9a18-ce9988ffa654.png)

I can only see one tab, even after a refresh of the page

**Comment by teolemon** [comment]
https://world.openfoodfacts.org/cgi/product.pl?type=edit&code=8480017012944

**Comment by stephanegigandet** [comment]
I made a mistake yesterday, fixing it.
