### ISSUE TITLE
Junk characters in allergens and traces tags

### ISSUE THREAD

**Issue by Ban3** [openfoodfacts/openfoodfacts-server#2887]
**Describe the bug**
https://world.openfoodfacts.org/product/20995553/arriba-j-d-gross

After inserting Finnish information the resulting tags have extra `fr:f{:` added to them.

https://world.openfoodfacts.org/product/20005917/choco-softies-mister-choc

This one has extra `fm:` but I think it stems from the same issue.

**Comment by aleene** [comment]
Which site did you use to make the changes? On world?

**Comment by aleene** [comment]
When entering the traces on the finish site using the drop down menu, it adds the `fm:` prefix. I guess it should add `fi:`.

**Comment by stephanegigandet** [comment]
I made a stupid mistake, fixing it.

**Comment by stephanegigandet** [comment]
Fixed.
