### ISSUE TITLE
Add HTTPS for http://**.openfoodfacts.org

### ISSUE THREAD

**Issue by pamputt** [openfoodfacts/openfoodfacts-server#29]
Hello, as described here: https://github.com/openfoodfacts/cordova-app/issues/1
it would really usefull to have access to the website via https. Wainting to have "valid" certificate", you could use a self-signed certificate for free. It does not authentificate the website but at least the traffic is encrypted.

**Comment by stephanegigandet** [comment]
Do modern browsers issue warnings with self-signed certificates?

**Comment by pamputt** [comment]
Yes, they do but you can bypass the warning clicking on "I understand" or somerthing like. For a transition phase, it would be acceptable I think. As long as, you will not have a "commercial" certificate, the traffic will be encrypted for the users that know and that choose to use https connection. For others, the situation will be the same as now (their password will be sent without ny protection on the network). So, at the beginning, the website could be accessible by http or https without any redirection to one or the other. Once you will get a "valid" certificate, one can imagine that all the traffic will be in https (redirect http to https).

**Comment by kyzh** [comment]
On mobile, self certificate look pretty bad for non technical user
![screenshot_2015-02-15-21-07-10](https://cloud.githubusercontent.com/assets/43065/6205009/a70a24c4-b556-11e4-95d3-d6ad8d782c6e.png)

**Comment by pamputt** [comment]
Indeed, but as I said at the begining you should have both. For "advanced" users, you could provide a self-signed certificate to allow https connections (if one types https). For "normal" users, they will still use the "normal" connection via http (as now). Of course, you will probably need to buy a "commercial" certficate to avoid the message described above. But as a quick fix, the self-signed certificate could be a solution.

**Comment by kyzh** [comment]
an up to date guide for the csr generation.
https://certsimple.com/blog/openssl-csr-command

**Comment by nicolasleger** [comment]
:+1: At least for login and when uploading image or update product for the mobile Cordova app calls since user password seems to be sent in plain.

**Comment by epileptic-fish** [comment]
How about using Let's Encrypt instead of a self-signed cert: https://letsencrypt.org/? It's free, provides good tooling and the cert would be trusted by browsers.

Here's the getting started guide: https://letsencrypt.org/getting-started/

**Comment by TaciteOFF** [comment]
LetsEncrypt is great and could be a solution for the API. But they don't provide Wildcard certificates and OFF has numerous subdomains.

**Comment by epileptic-fish** [comment]
Ah ok. Just came across OFF today so I'm not familiar with the setup at all! Really cool project by the way! 

How many subdomains are we talking? Would it be prohibitive to get certs for each subdomain and set up automatic renewal so management of them isn't so bad?

**Comment by TaciteOFF** [comment]
More than a hundred, one for each country. 
Please join us on Slack! 
https://openfoodfacts.slack.com

**Comment by epileptic-fish** [comment]
Wowza. That's quite a few. Just joined :)

**Comment by rugk** [comment]
You can include up to I think more than hundred (sub)domains in one LE cert.
And if one cert is not enough, just create another one.

**Comment by rugk** [comment]
Quoting the [official docs](https://letsencrypt.org/docs/rate-limits/):
> If you have a lot of subdomains, you may want to combine them into a single certificate, up to a limit of 100 Names per Certificate. Combined with the above limit, that means you can issue certificates containing up to 2,000 unique subdomains per week. A certificate with multiple names is often called a SAN certificate, or sometimes a UCC certificate.

2000 certs per week should be enough, should not they? 😃

**Comment by hangy** [comment]
> 2000 certs per week should be enough, should not they? 

We thought so, too, but the way that OFF allows subdomains to be used (`$countrycode.openfoodfacts.org`, `$countrycode-$languagecode.openfoodfacts.org`, `world-$languagecode.openfoodfacts.org`) results in at over 46k _possible_ subdomains. While a lot of things could hopefully be automated, nearly 100k subdomains/1000 certificates (OpenFoodFacts.org and OpenBeautyFacts.org use the same subdomain scheme) is bit ridiculous.

We've talked about provisioning the most important/used subdomains first, but really haven't gotten around to making a decision, yet.

**Comment by rugk** [comment]
Why on hell do you have this strange subdomain system? One subdomain for each country would certainly be enough. Maybe consider dropping some subdomains? (or only support HTTPS with the main ones and depreciate the others)

Also, of course, `domain.example/$languagecode` would be enough, no one needs this subdomain system anyway. (also why support `world.domain.example` - a simple `domain.example` would be suitable)

**Comment by teolemon** [comment]
The goal of Open Food Facts is to have all products available in your language. In order for you to be able to find it using a search engine, we need handle many specific cases. For example:

**Switzerland**
ch.openfoodfacts.org (Products from Switzerland, German by default)
ch-fr (Products from Switzerland, French by default)
ch-it (Products from Switzerland, French by default)
ch-de (Products from Switzerland, French by default)

**French**
fr.open (France, French)
world-fr (World products in French)
ca-fr (Canadian products in French)
…

**Comment by rugk** [comment]
Then change it to use subdirectories.

**Comment by norganna** [comment]
The easiest way is to just get a cheap domain validated wildcard cert. It's not terribly expensive, means that everyone gets to keep using the site as they are currently used to, and you only have to renew it once a year.

Probably still good idea to make the API traffic go to ssl-api though.

**Comment by teolemon** [comment]
Ok, @stephanegigandet solved this issue for OFF. OBF is next.

**Comment by teolemon** [comment]
Closed for Open Food Facts. New bug for OBF.
