### ISSUE TITLE
Allow multilingual quantity

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#290]
### What
- I like to fill in all the details related to quantity, but can also be in multiple languages.
- Example for tea:
  - 35 g (25 sachets de 1.4g) (25 bags of 1.4 g) (25 bolsitas de 1.4 g)
### Part of
- #8049

**Comment by pamputt** [comment]
I do not understand what you ask for. If you are filling in a tea product on fr.openfoodfacts.org, you just need to specify the quantity in French. If you are on es.openfoodfacts then you fill in the information in Spanish. Do I miss something in your explanation?

**Comment by aleene** [comment]
An image might help:
![img_5787](https://cloud.githubusercontent.com/assets/1329905/15272941/8d6e0aaa-1a89-11e6-8f07-1fa26244761e.jpg)

**Comment by teolemon** [comment]
- value of product quantity (35), unit of product quantity (g) (globally)
- value of product quantity, unit of product quantity (without water, for stuff like tinned veggies)
- number of portions (25) / portion size (1,4) / portion units (g) / portion type (teabags)

**Comment by aleene** [comment]
Translation support via a taxonomy would also be possible.

**Comment by aleene** [comment]
too old
