### ISSUE TITLE
Prevention - Prevent "Undefined" from being stored as a value

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#2909]
### What

- Speisekammer sends us "Undefined" as a value sometimes. I've contacted them about it. Meanwhile, and in general, can we add an edit rule to prevent "Undefined" from being a storable value in any field.
- Example: https://world.openfoodfacts.org/product/4316268525602/beste-ernte

### Part of 
- #5538

**Comment by teolemon** [comment]
We already have 387 occurences: https://world.openfoodfacts.org/category/undefined

**Comment by teolemon** [comment]
`Food` being added as a category: https://world.openfoodfacts.org/product/7300400317801/original-crisp-wasa

**Comment by teolemon** [comment]
458 occurences

**Comment by VaiTon** [comment]
> 458 occurences

Now only 5 products.

> Food being added as a category: https://world.openfoodfacts.org/product/7300400317801/original-crisp-wasa

Not anymore apparently.

**Comment by benbenben2** [comment]
That is for categories. The example is from 2020: https://world.openfoodfacts.org/product/4316268525602/ajvar-scharf-beste-ernte?rev=1

Now only 2 occurrences: https://world.openfoodfacts.org/category/undefined

Should we close @teolemon ?

**Comment by benbenben2** [comment]
Should we close this @CharlesNepote?
