### ISSUE TITLE
Regularly add new selling countries based on scans

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#291]
As we now have multilingual support, it is crucial that products are displayed in all locales where they are sold, so that they are completed in all the languages the packaging is translated in.
We need to regularly add new selling countries based on scans.

**Comment by aleene** [comment]
If there is a translation present on the package, then there is no guarantee that is sold in a corrsponding locale. A local user has to confirm that.

However it would be nice to see products with dutch in dutch speaking locales.

**Comment by teolemon** [comment]
That's why it would be based on scans. 
I've filed another bug (#292) for detection based on packaging langages (and it would be a separate list, just for reference).

It just means that Products scanned in Belgium or the Netherlands would have Belgium or the Netherlands added and thus would be editable from those locale as well. They thus would become multilingual quicker.

**Comment by aleene** [comment]
You mean by people using any app, so you now where they come from? Not infallible, but I guess ok

**Comment by bredowmax** [comment]
Related to this: If I add a product through a 3rd party app like El Coco, it automatically adds Spain to 'Countries where sold'

More: https://openfoodfacts.slack.com/archives/C03H290LF/p1580488903002800

**Comment by CharlesNepote** [comment]
This issue has been solved since 2021 by #5079.
