### ISSUE TITLE
Let robot-off compute category of usda-ndb-import products to enable 120,000 NutriScores & NOVA scores

### ISSUE THREAD

**Issue by bredowmax** [openfoodfacts/openfoodfacts-server#2915]
**Summary**
OFF could increase the number of products with NutriScore and NOVA-score by approx. 50% through a relatively quick fix: adding categories to products from USDA import.

**Problem**
Products imported through USDA don't display their #nutriscore or #nova because one key ingredient is missing: the category. As a result to #783 almost none of the USDA imported products feature a NutriScore or NOVA score.
https://world.openfoodfacts.org/editor/usda-ndb-import

**Describe the solution you'd like**
OFF is good at predicting the category and #hunger-games often already suggests the correct category. One example: Accepting hunger-game's suggestion for https://world.openfoodfacts.org/product/0810607020703/popcorners-crispy-crunchy-popped-corn-medora-snacks-llc would likely add NOVA+NutriScore

**What's the potential impact?**
Approx. 120k new NutriScores & NOVA scores - an increase of 50% of the current products with NS/NOVA on OFF

**Slack Discussion:**
https://openfoodfacts.slack.com/archives/C03BNT0K8/p1580756648014600

**Comment by bredowmax** [comment]
Actually, the Fooddata Cental features a 'food category' field. If we properly update the USDA import like addressed in #650 (and #946) this should be solved at the same time.

This import would have a large impact: OpenFoodFacts would grow by +10% products, and products with NutriScore & NOVA score increase by roughly 50%

**Comment by teolemon** [comment]
This is largely fixed by the Food Central import.
