### ISSUE TITLE
Add top scanned products by countries in popularity facet + products representing 90% and 95% of scans

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#2918]
Add new values for each country in the /popularity facet, e.g. for Belgium:

"top-10-be-scans-2020",
"top-50-be-scans-2020",
"top-100-be-scans-2020",
"top-500-be-scans-2020",
"top-1000-be-scans-2020",
"top-5000-be-scans-2020",
"top-10000-be-scans-2020",
"top-50000-be-scans-2020",
"top-100000-be-scans-2020",

Also add global Top-90-percent-scans-2020 and Top-95-percent-scans-2020 facets on the top products that represent 90% or 95% of the scans worldwide.

**Comment by teolemon** [comment]
can we close @stephanegigandet ?

**Comment by stephanegigandet** [comment]
Deployed. One caveat is that we don't have enough products in the database to cover 90% of the scans, so those values are currently useless. (they are on all products that have been scanned)


Top-90-percent-scans-2019 | 344838
-- | --
Top-95-percent-scans-2019 | 344838
Top-95-percent-scans-2020 | 70622
Top-90-percent-scans-2020 | 70622
