### ISSUE TITLE
50 shades of red (Various shades of red and green are used for ingredient analysis)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#2929]
50 shades of red (Various shades of red and green are used for ingredient analysis)

![image](https://user-images.githubusercontent.com/1689815/74860330-c2d96800-5348-11ea-966b-bd46a6d1aec7.png)

**Comment by dev2919** [comment]
can you elaborate the bug ?

**Comment by teolemon** [comment]
done.
