### ISSUE TITLE
Some nutrition entries no longer appear where they should

### ISSUE THREAD

**Issue by TaciteOFF** [openfoodfacts/openfoodfacts-server#293]
http://fr.openfoodfacts.org/produit/8018338000014/bucaneve-pietro-castelli

Acides gras monoinsaturés and acides gras polyinsaturés used to appear under Matières grasses.
It's no longer happening.

**Comment by TaciteOFF** [comment]
Same goes for Acides gras Oméga 3, and so on.

**Comment by stephanegigandet** [comment]
Fixed, thanks for the report.

Matières grasses / Lipides	1.51 g	-29%
dont Acides gras saturés	0.277 g	-40%
dont Acides gras monoinsaturés	0.171 g	?
dont Acides gras polyinsaturés	0.564 g	?
dont Cholestérol	0 mg	?

**Comment by stephanegigandet** [comment]
Fixed but products edited in the last few days with typed (and not selected) nutrition fields will need to be revalidated.
