### ISSUE TITLE
If specified, use country of subdomain to assign country for new products instead of geo ip

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#2930]
New products created on the web site and/or through the API / mobile apps have their country field set to the country location of the ip address, retrieved from geo-ip.

This change is to use the subdomain country (e.g. https://de.openfoodfacts.org -> de -> Germany) when it is specified, and to use geoip only when not specified (e.g. on world.openfoodfacts.org).

**Comment by teolemon** [comment]
Just curious, what triggered the change ?

**Comment by stephanegigandet** [comment]
> Just curious, what triggered the change ?

It's mainly for the producers platform, so that we can upload photos from a given country. e.g. when we upload photos from Germany, we use de.pro.openfoodfacts.org

**Comment by stephanegigandet** [comment]
Deployed.
