### ISSUE TITLE
Cutter seems to be cutting sodium

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#2936]
### What

- [ ] Cutter seems to be cutting sodium

### Part of
- #5706 

### Screenshot
![image](https://user-images.githubusercontent.com/1689815/75037012-7fe7d380-54b3-11ea-8bc9-bd8951b3b867.png)

**Comment by stephanegigandet** [comment]
Any chance you know which product it was? It looks more like an OCR issue.

**Comment by benbenben2** [comment]
@teolemon @stephanegigandet 
It looks like this product: https://world.openfoodfacts.org/product/3222475121210/viande-de-boeuf-sechee-dans-les-alpes-10-tranches-casino

Image is not exactly the same but ingredients list is.
Parsing seems to be working

**Comment by benbenben2** [comment]
@teolemon, @stephanegigandet 
The product: https://world.openfoodfacts.org/product/3350033293069/viande-sechee-de-boeuf-monoprix

Extraction is working fine beside "sodium"

I suggest to close this issue

**Comment by stephanegigandet** [comment]
Most likely it was just an OCR issue, closing. Thanks @benbenben2
