### ISSUE TITLE
French product created with main language French but images in English

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#294]
http://fr.openfoodfacts.org/produit/3492171201008

{"status_verbose":"product found","status":1,"product":{"last_edit_dates_tags":["2016-05-15","2016-05","2016","2016-05-15","2016-05","2016","2016-05-15","2016-05","2016","2016-05-15","2016-05","2016"],"creator":"openfoodfacts-contributors","_id":"3492171201008","last_modified_by":null,"allergens":"","states_tags":["en:to-be-completed","en:nutrition-facts-to-be-completed","en:ingredients-to-be-completed","en:expiration-date-to-be-completed","en:characteristics-to-be-completed","en:categories-to-be-completed","en:brands-to-be-completed","en:packaging-to-be-completed","en:quantity-to-be-completed","en:product-name-to-be-completed","en:photos-to-be-validated","en:photos-uploaded"],"checkers_tags":[],"id":"3492171201008","countries":"en:FR","code":"3492171201008","images":{"1":{"uploader":"openfoodfacts-contributors","sizes":{"400":{"w":400,"h":225},"100":{"w":100,"h":56},"full":{"w":2000,"h":1125}},"uploaded_t":"1463318368"},"2":{"uploader":"openfoodfacts-contributors","sizes":{"400":{"w":400,"h":225},"100":{"w":100,"h":56},"full":{"w":2000,"h":1125}},"uploaded_t":"1463318375"},"front_en":{"normalize":null,"white_magic":null,"rev":"3","geometry":"0x0--5--5","sizes":{"200":{"w":200,"h":113},"400":{"w":400,"h":225},"full":{"w":2000,"h":1125},"100":{"w":100,"h":56}},"imgid":"1"}},"sortkey":463318375,"last_modified_t":1463318375,"correctors_tags":[],"rev":4,"_keywords":[],"interface_version_created":"20120622","max_imgid":"2","languages_tags":["en:english","en:1"],"informers_tags":["openfoodfacts-contributors"],"ingredients_tags":[],"photographers_tags":["openfoodfacts-contributors"],"codes_tags":["code-13","3492171201008","349217120100x","34921712010xx","3492171201xxx","349217120xxxx","34921712xxxxx","3492171xxxxxx","349217xxxxxxx","34921xxxxxxxx","3492xxxxxxxxx","349xxxxxxxxxx","34xxxxxxxxxxx","3xxxxxxxxxxxx"],"languages_codes":{"en":1},"states":"en:to-be-completed, en:nutrition-facts-to-be-completed, en:ingredients-to-be-completed, en:expiration-date-to-be-completed, en:characteristics-to-be-completed, en:categories-to-be-completed, en:brands-to-be-completed, en:packaging-to-be-completed, en:quantity-to-be-completed, en:product-name-to-be-completed, en:photos-to-be-validated, en:photos-uploaded","entry_dates_tags":["2016-05-15","2016-05","2016"],"ingredients_text_with_allergens":null,"allergens_hierarchy":[],"languages":{"en:english":1},"countries_tags":["en:france"],"languages_hierarchy":["en:english"],"countries_hierarchy":["en:france"],"states_hierarchy":["en:to-be-completed","en:nutrition-facts-to-be-completed","en:ingredients-to-be-completed","en:expiration-date-to-be-completed","en:characteristics-to-be-completed","en:categories-to-be-completed","en:brands-to-be-completed","en:packaging-to-be-completed","en:quantity-to-be-completed","en:product-name-to-be-completed","en:photos-to-be-validated","en:photos-uploaded"],"editors_tags":["openfoodfacts-contributors"],"allergens_tags":[],"lc":"en","ingredients":[],"ingredients_text_with_allergens_en":null,"created_t":1463318368,"complete":0},"code":"3492171201008"}

lc : en, no lang

**Comment by stephanegigandet** [comment]
The main language was in fact set to English, but not copied to the legacy "lang" field. Changed product_multilingual.pl to use field lc for main language instead of lang.

**Comment by hangy** [comment]
> The main language was in fact set to English, but not copied to the legacy "lang" field. Changed product_multilingual.pl to use field lc for main language instead of lang.

I assume this is done?
