### ISSUE TITLE
images of products with a multilingual component no longer appear in the json api

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#295]
The images of products with a multilingual component no longer appear in the json api. The old url keys for the images no longer appear.

Example: http://world.openfoodfacts.org/api/v0/product/3263859691820.json

**Comment by aleene** [comment]
There is a similar problem with the ingredients list

**Comment by stephanegigandet** [comment]
Thanks for the report, I'm now populating the old image keys. Depending on the language requested (currenty from the subdomain used), the best matching images are selected. (same images as you get on the web site for that language).
