### ISSUE TITLE
Units missing on some products

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#2955]
3560070846788

"nutriments":{"nutrition-score-fr":3,"energy-kcal_value":172,"energy_100g":720,"sugars_unit":"","fat_100g":10,"salt_100g":0.94,"energy-kcal":720,"nutrition-score-fr_100g":3,"nova-group":3,"salt_unit":"","energy":720,"energy-kcal_100g":720,"saturated-fat_unit":"","carbohydrates_unit":"","energy_serving":2160,"energy-kcal_unit":"kcal","sugars_100g":0.6,"proteins_serving":28.5,"sodium_value":0.376,"fiber":1.6,"fiber_value":1.6,"fat":10,"sugars_serving":1.8,"fat_value":10,"proteins_100g":9.5,"sodium_unit":"g","fat_unit":"","saturated-fat_serving":11.1,"saturated-fat":3.7,"carbon-footprint-from-known-ingredients_100g":154.84,"saturated-fat_value":3.7,"carbohydrates_100g":10,"nova-group_serving":3,"fat_serving":30,"nova-group_100g":3,"carbohydrates_value":10,"sugars_value":0.6,"fiber_serving":4.8,"salt_value":0.94,"carbohydrates_serving":30,"sodium_serving":1.13,"sugars":0.6,"nutrition-score-uk":3,"saturated-fat_100g":3.7,"carbon-footprint-from-known-ingredients_serving":465,"salt":0.94,"salt_serving":2.82,"carbon-footprint-from-known-ingredients_product":465,"proteins":9.5,"energy_unit":"kcal","proteins_unit":"","energy_value":172,"fiber_unit":"g","carbohydrates":10,"sodium_100g":0.376,"energy-kcal_serving":2160,"sodium":0.376,"proteins_value":9.5,"nutrition-score-uk_100g":3,"fiber_100g":1.6}

**Comment by teolemon** [comment]
https://user-images.githubusercontent.com/1689815/75118718-c3da0480-567c-11ea-9a35-6f13d446e0f1.png

**Comment by teolemon** [comment]
It's missing on fat for instance, but it's not missing for sodium

**Comment by teolemon** [comment]
```
sugars_unit":"",
"salt_unit":"",
"saturated-fat_unit":"",
"carbohydrates_unit":"",
"sodium_unit":"g",
"fat_unit":"",
"energy_unit":"kcal",
"proteins_unit":"",
"fiber_unit":"g",
```
for easier readability

**Comment by stephanegigandet** [comment]
The *_unit *_value and *_label fields are for internal use, they should not be used by apps or bad things will happen.

Those fields contain whatever the last user or API call entered. They are not normalized. If no unit was given, then the server used the default unit to convert them to the *_100g and *_serving field.

Apps should only use the *_100g or *_serving fields (for display and for edits).
