### ISSUE TITLE
Image selection colorization for admins is broken

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#2956]
Image selection colorization for admins is broken. The image is selected when I click on it, but the yellow color is not there anymore to confirm it.
![image](https://user-images.githubusercontent.com/1689815/75421622-ff095b80-593a-11ea-8656-67832d8f56b6.png)

**Comment by CharlesNepote** [comment]
This bug only appears with Power User Script. I didn't have time to investigate.

**Comment by teolemon** [comment]
Ok, closing.
