### ISSUE TITLE
Reload States Taxonomy

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#296]
Several new states are not loaded. 
Translations have been added.
http://world.openfoodfacts.org/states

**Comment by stephanegigandet** [comment]
Reloaded.

http://world-fr.openfoodfacts.org/etats

**Comment by teolemon** [comment]
https://en.wiki.openfoodfacts.org/Global_states_taxonomy

**Comment by teolemon** [comment]
There's the packager code states which was never loaded.

**Comment by VaiTon** [comment]
Is https://en.wiki.openfoodfacts.org/Global_states_taxonomy still used in prod?? @stephanegigandet

**Comment by teolemon** [comment]
still used in prod. We now have a system to translate them directly
https://fr.openfoodfacts.org/states?translate=1
