### ISSUE TITLE
UK version moved from uk to gb. Will lead UK visitors to the Ukrainian version

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#297]
we have a tiny issue

[9:15] 
http://gb.openfoodfacts.org/

[9:15] 
http://uk.openfoodfacts.org/product/91114807/tomato-ketchup-by-sainsbury-s

**Comment by teolemon** [comment]
fixed by @stephanegigandet

**Comment by stephanegigandet** [comment]
Reloaded correct country taxonomy with UK instead of GB for country code of United Kingdom. http://en.wiki.openfoodfacts.org/index.php?title=Global_countries_taxonomy&oldid=4872
