### ISSUE TITLE
Sometimes it's impossible to delete some labels

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#2974]
Sometimes it's impossible to delete some labels.

Some examples:
* https://world.openfoodfacts.org/product/3250392065034/tagliatelles-fiorini : it failed to delete [Nutriscore] and or [Nutriscore Grade E]
* https://world.openfoodfacts.org/product/02026459/vins-le-temps-des-gitans : delete "fr:Indication géographique protégée de la République populaire de Chine" doesn't work, but deleting "PGI" will probably work and make possible to delete "fr:Indication géographique protégée de la République populaire de Chine"

It's very annoying...

### Actual evidence
Browsers affected:
 - Firefox 75.0 Ubuntu Linux ([comment](https://github.com/openfoodfacts/openfoodfacts-server/issues/2974#issuecomment-617160484))

Browsers **not** affected:
 - Chromium Ubuntu Linux Version 80.0.3987.163 ([comment](https://github.com/openfoodfacts/openfoodfacts-server/issues/2974#issuecomment-617160484))
 - Firefox 75.0 Win 10 build 18363 ([comment](https://github.com/openfoodfacts/openfoodfacts-server/issues/2974#issuecomment-617439467))

**Comment by stephanegigandet** [comment]
@CharlesNepote I can't reproduce it, I just deleted the labels on both products, using the edit product form on the web, it worked for me.

**Comment by CharlesNepote** [comment]
Yes it's still a very annoying issue. I investigated further and the issue seems to come from our javascript code.

Here is what I do:
* test made with Firefox 75.0 Ubuntu Linux (official build), in **private browsing** mode (which deactivate most of my Firefox extensions, including the Power User Script)
* I open https://world.openfoodfacts.org/cgi/product.pl?type=edit&code=3564706603592
* I delete "Nutriscore E" with the mouse (clicking on the [x] box)
* then clic on "Save" button
* then looking at POST "resquest body" in Firefox devloper tools, I can see the following (abstract):

```
-----------------------------87121513537285779974119688838
Content-Disposition: form-data; name="labels"

fr:Fruits et Légumes de France,Nutriscore,Nutriscore Grade A,Nutriscore Grade E,fr:Légumes de France
```
It means that while I deleted "Nutriscore Grade E" with the mouse, it is still POSTted to the app.

It's very annoying because:
* I think I had solved a product issue while it's not
* it creates an entry in the product's changelog for nothing 
* I feel myself insecure about what is taken in account or not by the app

**The bug doesn't appear with Chromium Ubuntu Linux Version 80.0.3987.163 (official build).**

**Comment by VaiTon** [comment]
**Tested on Firefox 75.0 on Win 10 build 18363.**

Tried to add the label, save, then re-edit and remove.

Final POST request:
```
-----------------------------292537306440844495401560520893
Content-Disposition: form-data; name="labels"

fr:Fruits et Légumes de France,Nutriscore,Nutriscore Grade A,fr:Légumes de France
```
**Summary:** For me it's working.
What is going on? 🤔

**Comment by CharlesNepote** [comment]
Can't reproduce. All seems ok, sorry about the noise.
