### ISSUE TITLE
Always select newly uploaded images when they specify front / ingredients / nutrition

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#2975]
When an app uploads a new image with the imagefield field set to (front|ingredients|nutrition)_[language code], automatically select that image, even if there is a previously selected image.

This is a change from the current behaviour: if there was already an image selected, then the newly uploaded image was not selected.

**Comment by stephanegigandet** [comment]
If the app just sends "front", "nutrition", "ingredients" without a language code, then we use the main language set for the product (if the product already exists)

**Comment by hangy** [comment]
Do we assume or mandate that apps correctly rotate and crop images when uploading using those imageids? Considering some apps require workarounds in the server code to not send bad data or remove already validated content from products, there seems to be a risk of some apps incorrectly overriding images that were previously meticulously selected/cropped/rotated on the website.

**Comment by stephanegigandet** [comment]
@hangy sorry I had missed your comment. It is a risk, and we will have to watch for it. But so far the anecdotal evidence we have seen is that by not selecting new images, we keep photos with old ingredients lists and nutrition facts that do not match the current values on the packages. That's why we made that change. cc @teolemon
