### ISSUE TITLE
Show details of the ingredients analysis on the product page

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#2980]
Allow users to see how the ingredients list was parsed and match to the taxonomy.

![image](https://user-images.githubusercontent.com/8158668/76095104-00cec100-5fc4-11ea-9e1e-f94e4dc7050c.png)

**Comment by teolemon** [comment]
A few thoughts about this:
- admins/moderators… could have a way to mark an ingredient as vegan/vegetarian, and the result could be stored (before being applied) the same way as ingredient translations
- admins/moderators… could have a way to link (by autocomplete) to a taxonomized ingredient
- there could be a link to the taxonomy in GitHub for admins/moderator

**Comment by stephanegigandet** [comment]
It's tricky to make changes to the taxonomy without seeing it entirely, or without a tool that makes many checks. e.g. for vegan / vegetarian : we want the property to be added as high as possible on the parent chain.

The /ingredients page is probably a better place to make things like that.

**Comment by teolemon** [comment]
The analysis is always shown for the main language of the product:
![image](https://user-images.githubusercontent.com/1689815/76146020-72c00c80-608f-11ea-98c8-fa5b953e751b.png)

**Comment by teolemon** [comment]
eg: https://world.openfoodfacts.org/product/7610026007698/cannellonis-stuffed-with-spinach-and-ricotta-findus

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/76158324-199abc00-6115-11ea-8eaa-5d6316b07afe.png)

**Comment by teolemon** [comment]
@stephanegigandet would the above mockup do the trick ?

**Comment by stephanegigandet** [comment]
At this time, the analysis is only done on the main language of the product.

**Comment by stephanegigandet** [comment]
Deployed.
