### ISSUE TITLE
Product count not displayed correctly on the OFF web site for some languages

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#2991]
Reported by @teolemon:

On https://pt.openfoodfacts.org/ :

![image](https://user-images.githubusercontent.com/8158668/76165372-e11bd200-6156-11ea-85eb-472b66a5ea4b.png)

Instead of 3135 products.

This is because we used to have a string n_products equal to "%d products" in the .po strings.
It has been changed to "%s products" so that we can display a string instead of an integer. The string comes from the decimal number formatter:

$html_count .= sprintf(lang("n_products"), $decf->format($count)) ;

Some languages still have "%d" instead of "%s", which makes the string be converted to an integer first. So "2.143" becomes 2.

[15107] /srv/off/lib/ProductOpener/Display.pm 3873 ProductOpener.Display {count => 2376,decf => '2.376',n_products => '%d produtos',request => 'Py95QjUh0lQKIe15',sprintf => '2 produtos'} n_products

**Comment by stephanegigandet** [comment]
The issue exists only in Portuguese:

/srv/off/scripts# ./print_all_translations.pl n_products | grep '%d'
pt      %d produtos

It's because pt_PT.po has been updated, but not pt.po

/srv/off/po/common# ls -lrt pt*
-rw-r--r-- 1 off root 116151 Jan 23 12:39 pt.po
-rw-r--r-- 1 off root 132354 Mar  6 15:05 pt_PT.po
-rw-r--r-- 1 off root 131582 Mar  6 15:05 pt_BR.po

I suggest making pt.so a symlink to pt_PT.po

**Comment by teolemon** [comment]
done

**Comment by VaiTon** [comment]
bump

**Comment by stephanegigandet** [comment]
Fixed.
