### ISSUE TITLE
non-latin character create empty URLs

### ISSUE THREAD

**Issue by kyzh** [openfoodfacts/openfoodfacts-server#30]
This is one example:
http://world.openfoodfacts.org/product/8699158373351/tiyan-natural-spring-water

We can see that the latin character version of the countrie's name provde a link to a list relevant list, while the non-lation doesn't.
The "Origin of ingredients", "Manufacturing or processing places"  and "Countries where sold" links works for "Iraq" but doesn't for "العراق".

**Comment by stephanegigandet** [comment]
The link now works: http://world.openfoodfacts.org/origin/%D8%A7%D9%84%D8%B9%D8%B1%D8%A7%D9%82

I don't like the "en:Iraq" though, that should be changed to just Iraq when displaying / editing in English.

**Comment by stephanegigandet** [comment]
I changed en:Iraq to Iraq, origins of ingredients and manufacturing places are currently not taxonomy fields, they should not be prefixed with a language code.
