### ISSUE TITLE
Create http://windowsphone.openfoodfacts.org

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#301]
Should redirect to 
https://www.microsoft.com/en-us/store/apps/openfoodfacts/9nblggh0dkqr

**Comment by hangy** [comment]
> https://www.microsoft.com/en-us/store/apps/openfoodfacts/9nblggh0dkqr

404 Not Found

**Comment by teolemon** [comment]
The code for this has recently been commited by @stephanegigandet 
https://github.com/openfoodfacts/openfoodfacts-server/blob/e54d0240f1e495ec0018273b032e64de7f40b20e/conf/nginx/sites-available/off
