### ISSUE TITLE
Generate "raw *" versions of ingredients

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#3020]
Many producers add raw in front of ingredients in the US
Generating subingredients with raw would be helpful.
```
raw peruvian cacao nibs -> en:Raw peruvian cacao nibs
coconut sugar -> en:coconut-sugar - vegan: yes - vegetarian: yes
raw sprouted italian hazenuts -> en:raw sprouted italian hazenuts
raw figs -> en:raw figs
raw cacao butter -> en:raw cacao butter
coconut sugar sweetened cacao nibs -> en:coconut sugar sweetened cacao nibs
```

**Comment by hangy** [comment]
Could it be better to add language specific prefixes/suffixes for "raw" and thus detect "raw chicken" as "chicken"? One problem is, that not all ingredients have an actual "raw" variant. For example, there is likely no "raw salt" or "raw riboflavin". I feat that automatically generating "raw" versions for every ingredient would bloat the ingredient list out of proportions.

**Comment by stephanegigandet** [comment]
Agreed, we don't want to multiply entries in the ingredients taxonomy.
But we actually have another taxonomy to deal with that in a better way. :)

https://github.com/openfoodfacts/openfoodfacts-server/blob/master/taxonomies/ingredients_processing.txt

# This taxonomy lists prefixes and suffixes that:
# 1. are often found in ingredients lists before or after an ingredient
# 2. indicate some kind of processing done to the ingredient (like "cut", "dried" etc.)
# 3. are not labels that specify the quality of the ingredient ("organic", "origin Italy", "superior quality")
#
# The taxonomy is used for ingredient analysis:
# The ingredient "cooked pork" will be recognized as "pork" with the processing "en:cooked".
# This works only if "cooked pork" is not a known ingredient in the ingredients taxonomy,
# and if "pork" is a known ingredient.

en:cooked
fr:cuit, cuite, cuits, cuites, cuit au naturel, cuite au naturel, cuits au naturel, cuites au naturel, cuisiné, cuisinée, cuisinés, cuisinées
it:cotto, cotta, cotti, cotte, cotto al naturale, cotta al naturale, cotti al naturale, cotte al naturale, cucinato, cucinata, cucinati, cucinate
[..]

Just adding en:raw to it would probably solve the problem. And in fact we should remove all "raw something" ingrédients from the taxonomy (unless there's an actual difference that we want to preserve, like "raw milk" and "milk").

**Comment by stephanegigandet** [comment]
Going through https://us.openfoodfacts.org/ingredients?filter=raw- to see which raw ingredients we actually need to add to the taxonomy before making the "raw" part just a processing.

One word of note: raw in English has multiple meanings: unrefined and uncooked. When it means unrefined, we probably need to have a corresponding taxonomy entry. e.g. "raw sugar". cc @aleene

**Comment by stephanegigandet** [comment]
![image](https://user-images.githubusercontent.com/8158668/76538391-87c9e080-647f-11ea-806f-cc5b74a1242f.png)

**Comment by teolemon** [comment]
https://world.openfoodfacts.org/ingredients?filter=pulver

**Comment by bredowmax** [comment]
Btw, the same thing happens with 'organic'

**Comment by bredowmax** [comment]
Since adding 'raw' or 'organic' in front of every single ingredient can become lengthy, some producers opt to sum them up at the end of the list. I've opened a ticket at https://github.com/openfoodfacts/openfoodfacts-server/issues/3030

**Comment by stephanegigandet** [comment]
This has been implemented and deployed as part of ingredient processing parsing.

https://world.openfoodfacts.org/cgi/test_ingredients_analysis.pl?ingredients_text=raw+chicken%2C+raw+tomatoes%2C+raw+sugar%2C+raw+kombucha%2C+raw+milk%2C+raw+potatoes&type=add&action=process&.submit=Envoyer
