### ISSUE TITLE
Ignore explanations at end of list of ingredients like ". *Organic Ingredients"

### ISSUE THREAD

**Issue by bredowmax** [openfoodfacts/openfoodfacts-server#3030]
### What
OFF seems not to handle explanations at the end of lists of ingredients like * Organic Ingredients very well. I've seen examples of these quite often here in the US

### Steps to Reproduce
https://world.openfoodfacts.org/product/0850003875088/jalapeno-vegan-cheddar-hippeas
https://world.openfoodfacts.org/product/0099482485375/fried-rice-style-riced-cauliflower-whole-foods-market

### Expected behavior
OFF should ignore a string like `. *` and whatever follows after it. It's mostly just explanations

### Discussion
https://openfoodfacts.slack.com/archives/C06A7LENM/p1584094524048900

### Part of
- #5706

**Comment by stephanegigandet** [comment]
For the first product, we actually handle it well. We don't ignore the "* Organic Ingredients" --> we actually tag corresponding ingredients as organic.

![image](https://user-images.githubusercontent.com/8158668/76635880-6a147e00-6548-11ea-8060-62080c4d1423.png)

The second one is not handled well.

What we need to do is to identify the most common "* something" to see which ones are actually useful to understand (e.g. when it specifies that an ingredient is organic, fair trade etc.), with the most common wordings. (e.g. for French we support a ton of variations of "* : ingredients that have been produced in an organic way")

**Comment by bredowmax** [comment]
`May contain 2% or less of`
https://world.openfoodfacts.org/product/0603028799132/gluten-free-fusilli

**Comment by bredowmax** [comment]
https://world.openfoodfacts.org/product/0856500004013/organic-hummus-hope
https://world.openfoodfacts.org/product/0856500004037/organic-hummus-thai-coconut-curry-hope

**Comment by bredowmax** [comment]
`Contains:`
I've often added this accidentally to ingredients. Not sure if this is parsed correctly already
https://world.openfoodfacts.org/product/0029737700144/potato-cheese-severino

**Comment by bredowmax** [comment]
Another edge case: When ingredients are separated into 2 different groups:
https://world.openfoodfacts.org/product/0029737210070/raviolini-severino

**Comment by bredowmax** [comment]
`*SPICES AND OR VEGETABLE POWDER as last ingredient when that flavor`
https://world.openfoodfacts.org/product/2252559300126/egg-vermicelli

**Comment by bredowmax** [comment]
Another example of ingredients separated into 2 groups:
https://world.openfoodfacts.org/product/8006013990644/bertagni
