### ISSUE TITLE
Streamline image cropping / 'select interesting zone' for ingredients & nutrient table by using higher-quality images

### ISSUE THREAD

**Issue by bredowmax** [openfoodfacts/openfoodfacts-server#3031]
**Describe the bug**
When cutting out the image for ingredients & nutrient table, figuring out where the area of interest is is tough because the image is too much compressed. I wish these preview photos were higher quality

**Discussion**
https://openfoodfacts.slack.com/archives/C06A7LENM/p1584120407088800

**Number of products impacted**
Any product with an image of lists of ingredients

**Time loss per product**
It's an extra few clicks per product. It doesn't stop me editing products, but it definitely makes it less efficient than it could be

**Comment by stephanegigandet** [comment]
I'll try to make the crop area bigger, with a variable size depending on screen size, instead of the fixed 400x400 px.

I'll also try to use the new version of cropper https://github.com/fengyuanchen/jquery-cropper and see if we can load the full image and allow to zoom.

**Comment by bredowmax** [comment]
My assumption is that the issue isn't the size of the crop area but the high compression of the image. The image looks quite blurry and could be much sharper even in the same size

**Comment by stephanegigandet** [comment]
The image is 400x400 px and it's shown at 400x400 px, so it shouldn't be blurry, unless your browser displays it at another size. Or maybe on some retina display it's display 1 pixel over a 2x2 pixel block.

**Comment by bredowmax** [comment]
I'm on a 2018 MacBook Pro 13" on Chrome. Typically, I'd expect the smaller version to appear sharper than the zoomed-in version, but the opposite is the case.

<img width="839" alt="Screenshot 2020-03-14 at 11 06 36" src="https://user-images.githubusercontent.com/30573532/76684630-ee680f00-65e3-11ea-8fec-1095e91f8ca1.png">

https://world.openfoodfacts.org/product/0073872746147/artisola-kale-garlic-cheese-ravioli-valley-fine-foods-company

**Comment by bredowmax** [comment]
This exemplifies what I mean: Above image is the compressed image as shown in OFF when editing. On the bottom is the full version but forced to be displayed smaller because I made that Chrome window smaller

<img width="358" alt="Screenshot 2020-03-14 at 11 09 22" src="https://user-images.githubusercontent.com/30573532/76684678-53bc0000-65e4-11ea-8269-89f0ec026dfc.png">

**Comment by bredowmax** [comment]
Here a screenshot of my entire Chrome browser view. Not sure if this blurry image is a result of the relatively high pixel density but these days I'd say it's an actually pretty average resolution (2560-by-1600 pixels on a 13")

<img width="1440" alt="Screenshot 2020-03-14 at 11 12 41" src="https://user-images.githubusercontent.com/30573532/76684724-bd3c0e80-65e4-11ea-8b4c-c4cf4ddace62.png">

**Comment by stephanegigandet** [comment]
Right, in your view, the 400x400 pixels image is displayed at double resolution (800x800).

On a "normal" screen, the 400x400 pixels image is displayed at 400x400, that's why I don't see the blur you experience.

Here is what I have:

![image](https://user-images.githubusercontent.com/8158668/76685123-9811c500-6611-11ea-8c0f-2869e2a2198e.png)

Anyway, I'll try to load the full image so this should not be an issue anymore.

**Comment by stephanegigandet** [comment]
OK, this should be better (currently on test on .dev) :

1. Crop image can be larger if the screen is larger
2. It's possible to zoom with the mouse wheel or with fingers on multi touch screen (not tested)
3. The full image is loaded.

![image](https://user-images.githubusercontent.com/8158668/76685908-8df2c500-6617-11ea-8184-a7d3441d7fd2.png)

https://us.openfoodfacts.dev/cgi/product.pl?type=edit&code=0096619000036

**Comment by stephanegigandet** [comment]
I'm also adding a full size copy of ingredients just above the text of the ingredient list, so that it's easier to compare, as suggested by @bredowmax

**Comment by stephanegigandet** [comment]
Reported by @moon-rabbitOFF : 
the image for ingredients displayed just above the ingredient text can be too large (too high in particular). Going to add max-height:400px.

![image](https://user-images.githubusercontent.com/8158668/76791133-81f63700-67c0-11ea-92b7-71577e181020.png)

**Comment by stephanegigandet** [comment]
Deployed a new version in production.

**Comment by stephanegigandet** [comment]
Added checkbox to enable and disable zoom, deployed.
