### ISSUE TITLE
\x{a0} space not handled in Text::_format_percentage / normalize_percentages()

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#3039]
When updating products I get a bunch of warnings like this one:

Argument "100\x{a0}" isn't numeric in division (/) at ProductOpener/Text.pm line 175.

**Comment by stephanegigandet** [comment]
Steps to solve the bug:

1. Add one or more test cases in /t/text.t that enables to reproduce the problem
2. Change the function to handle the \x{a0} spaces (and possibly other kinds of spaces).

**Comment by muskangarg21** [comment]
On it.

**Comment by muskangarg21** [comment]
Along with the above mentioned bug I found out these cases to be interesting too. 
Please have a look @stephanegigandet 
`is( normalize_percentages("test %\N{U+00A0}123 hey", 'eu'), "test %\N{U+00A0}123 hey" );`
<pre>
Argument "\x{a0}123" isn't numeric in division (/) at ProductOpener/Text.pm line 175.
not ok 13
#   Failed test at ../t/text.t line 43.
#          got: 'test %�0 hey'
#     expected: 'test %�123 hey'
</pre>

`is( normalize_percentages('test 1.023,45% hey', 'de'), "test 1.023,45\N{U+00A0}% hey" );`
<pre>
not ok 7
#   Failed test at ../t/text.t line 32.
#          got: 'test 1.23,45�% hey'
#     expected: 'test 1.023,45�% hey'
</pre>
`is( normalize_percentages('test 1.23.045,67% hey', 'de'), "test  123.045,67\N{U+00A0}% hey" );`
<pre>
not ok 8
#   Failed test at ../t/text.t line 33.
#          got: 'test 1.23.45,67�% hey'
#     expected: 'test  123.045,67�% hey'
</pre>
`is( normalize_percentages('test 0,12,345.67% hey', 'ur'), 'test 12,345.67% hey' );`
<pre>
not ok 3
#   Failed test at ../t/text.t line 27.
#          got: 'test 0,12,345.67% hey'
#     expected: 'test 12,345.67% hey'
</pre>
`is( normalize_percentages('test 1,002.34% hey', 'ur'), 'test 1,002.34% hey' );`
<pre>
not ok 4
#   Failed test at ../t/text.t line 28.
#          got: 'test 1,2.34% hey'
#     expected: 'test 1,002.34% hey'
</pre>

**Comment by stephanegigandet** [comment]
Thank you, I think it would be a good idea to add them indeed. cc @hangy

**Comment by muskangarg21** [comment]
https://www.autohotkey.com/boards/viewtopic.php?t=64975
says:
`By default, characters whose code points are greater than 127 never match \d, \s, or \w, and always match \D, \S, and \W, although this may vary for characters in the range 128-255 when locale-specific matching is happening. These escape sequences retain their original meanings from before Unicode support was available, mainly for efficiency reasons.`
This is a list of all horizontal spaces. I would prefer to keep only the cases which concern us.
<pre>
U+0009 Horizontal tab (HT)
U+0020 Space
U+00A0 Non-break space
U+1680 Ogham space mark
U+180E Mongolian vowel separator
U+2000 En quad
U+2001 Em quad
U+2002 En space
U+2003 Em space
U+2004 Three-per-em space
U+2005 Four-per-em space
U+2006 Six-per-em space
U+2007 Figure space
U+2008 Punctuation space
U+2009 Thin space
U+200A Hair space
U+202F Narrow no-break space
U+205F Medium mathematical space
U+3000 Ideographic space
</pre>
I have handled the specific `\x{a0}` case in the PR.
What do you think about this approach @stephanegigandet ?
Thanks
