### ISSUE TITLE
Some uploaded images disappear

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#304]
Reported by tacite.

Front image disappeared on this product:
http://fr.openfoodfacts.org/cgi/product.pl?type=edit&code=3168930009917

In history:

19 mai 2016 à 20:43:29 CEST - tacite Images sélectionnées (Changement : front_fr_fr) - new image front_fr_fr : 3.5 - voir
19 mai 2016 à 20:43:28 CEST - tacite Images téléchargées (Ajout : 4) - new image 4 - image upload - voir
19 mai 2016 à 20:43:27 CEST - tacite Images sélectionnées (Ajout : front_fr_fr) - new image front_fr_fr : 2.4 - voir

In logs:

product_image_upload.pl - user: tacite - code: 3168930009917 - cc: fr - lc: fr - imagefield: front_fr_fr 
product_image_upload - imagefield: front_fr_fr - delete:
product_image_upload.pl - product code 3168930009917 already exists
Images.pm - process_image_upload - imagefield: front_fr_fr - file: IMG_9101.png - uploader: tacite - time: 1463683406
Images.pm - process_image_upload - imagefield: front_fr_fr - file: IMG_9101.png - format ok

**Comment by TaciteOFF** [comment]
The uploaded image that disappeared was IMG_9096.png

**Comment by stephanegigandet** [comment]
Fixed the "front_fr_fr" issue.

For the disappearing images, I couldn't really tell from the logs what was going on, so I added more logs with a tracking id specific to each upload so that it's easier to follow when multiple image uploads are happening simultaneously.

If this issue happens again, please add the product url to this bug. Thank you!
