### ISSUE TITLE
Ingredient Images 

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#3040]
**Describe the bug**
I see the english and estonian ingredients on the same page (web-interface), when the english is selected.

**To Reproduce**
1. Go to https://world.openfoodfacts.org/cgi/product.pl?type=edit&code=5411188099154
3. Scroll down to the ingredients

**Screenshots**
![Screenshot 2020-03-15 at 17 24 38](https://user-images.githubusercontent.com/1329905/76705657-f5754700-66e1-11ea-89ab-fd2bf873c881.png)

**Expected behaviour**
See only the english ingredients.

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Browser [safari]
 - Version [latest]

**Comment by stephanegigandet** [comment]
Good catch. The bug was introduced by #3031 , fixing.
