### ISSUE TITLE
Document the ProductOpener::URL.pm module in perlpod format

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#3044]
The /lib/ProductOpener/URL.pm is a small and rather independent module. It currently has no documentation in perlpod / POD format. (see https://perldoc.perl.org/perlpod.html )

It would be good to add perlpod documentation for the module and its functions.

See the /lib/ProductOpener/Nutriscore.pm module for an example of how to document a module with perlpod.

**Comment by areeshatariq** [comment]
Working on this issue

**Comment by stephanegigandet** [comment]
Fixed by @areeshatariq , thank you!

https://world.openfoodfacts.org/files/doc/perl/ProductOpener/URL.html
