### ISSUE TITLE
Document the ProductOpener::Text.pm module in perlpod format

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#3045]
The /lib/ProductOpener/Text.pm is a small and rather independent module. It currently has no documentation in perlpod / POD format. (see https://perldoc.perl.org/perlpod.html )

It would be good to add perlpod documentation for the module and its functions.

See the /lib/ProductOpener/Nutriscore.pm module for an example of how to document a module with perlpod.

**Comment by areeshatariq** [comment]
@stephanegigandet I would like to work on this issue

**Comment by areeshatariq** [comment]
Working on this

**Comment by muskangarg21** [comment]
A general approach in this module is using `Hashes` to store `keys` and retrieve `values` for much faster results.
I think we should add that somewhere in the documentation, it will allow a better and faster understanding of the code for a new developer.
@stephanegigandet what do you say ?
