### ISSUE TITLE
Dropdowns in Edit mode without background color

### ISSUE THREAD

**Issue by bredowmax** [openfoodfacts/openfoodfacts-server#3047]
## Discussion:
https://world.openfoodfacts.org/cgi/product.pl?type=edit&code=5760466896481

<img width="315" alt="Screenshot 2020-03-16 at 08 55 50" src="https://user-images.githubusercontent.com/30573532/76781604-5d309e00-6785-11ea-93b0-922ba0f6e1be.png">

**Comment by stephanegigandet** [comment]
I don't think the related code has changed, but we may have installed newer versions of the javascript library through npm. cc @hangy

**Comment by stephanegigandet** [comment]
There's an error in the console:

![image](https://user-images.githubusercontent.com/8158668/76788498-56bd1900-67bb-11ea-9e72-d97bb8a39d5c.png)

**Comment by nazimboudeffa** [comment]
I get this error when I tape enter after filling the name of a country
![error](https://user-images.githubusercontent.com/1375686/76795141-c8e82a80-67c8-11ea-8076-293c25389f8a.png)

**Comment by stephanegigandet** [comment]
OK, this is probably because the scss / sass stuff is not taken into account.
