### ISSUE TITLE
Peach is not recognized as singular of Peaches

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#305]
http://world.openfoodfacts.org/category/peach
http://world.openfoodfacts.org/category/peaches

**Comment by TaciteOFF** [comment]
Maybe a temporary fix could be : 

Before:
<en:Fruits
en:Peaches
es:Melocotones
fr:Pêches
de:Pfirsiche
nl:Perzikken

After:

<en:Fruits
en:Peaches, Peach
es:Melocotones
fr:Pêches
de:Pfirsiche
nl:Perzikken

**Comment by hangy** [comment]
> Maybe a temporary fix could be

That could be the only useful fix, also permanently. I didn't think that having an additional list of irregular plurals in all languages would be useful, so that's basically what we did for most irregular plural categories in German, too.

**Comment by stephanegigandet** [comment]
Let's add peach as a synonym to peaches indeed, no need to overengineer everything.

**Comment by teolemon** [comment]
fixed by @stephanegigandet 
basic stemming could be useful. Closing this one
