### ISSUE TITLE
Nutrition table image not shown anymore next to nutrition table

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#307]
Before the multilingual products change, validating a nutrition image would copy it next to the nutrition table, if there was enough width (detected via javascript).

It's not working any more.

**Comment by stephanegigandet** [comment]
Fixed.

**Comment by TaciteOFF** [comment]
![capture 007 - modifier un produit_ - http___fr openfoodfacts org_cgi_product pl](https://cloud.githubusercontent.com/assets/11161632/15454255/a3d8b6b4-2033-11e6-93ac-132719552a1a.png)

Not handled correctly with multilingual products.
I was in fr.openfoodfacts.org when editing but had the spanish image next to the table

**Comment by stephanegigandet** [comment]
Fixed. Now showing main language nutrition fact when the form is loaded, and the new nutrition facts (regardless of language) when a new one is validated. (but at the next form reload, the main language will be the one displayed)
