### ISSUE TITLE
`hazelnuts` entry in categories taxonomies to fix

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#3078]
### What
hazelnuts entry in [categories taxonomies](https://github.com/openfoodfacts/openfooseasonality%20supportdfacts-server/blob/main/taxonomies/categories.txt) to fix
```
<en:Hazelnuts
fr:Noisettes fraîches
season_in_country_fr:en: 9,10,11
```

### Part of
- #5497

**Comment by VaiTon** [comment]
What is the problem here?

**Comment by borrokk** [comment]
Can I know more about this issue? Which files need to be changed or what needs to be done?

**Comment by teolemon** [comment]
@borrokk this one has been fixed. I’m closing it. Thanks for spotting
