### ISSUE TITLE
Uncomplete products among completed

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#309]
http://world.openfoodfacts.org/3000

**Comment by TaciteOFF** [comment]
It's a normal behavior. The pages contains all products, with the completed one first and the incompleted ones at the end.
3000 * 20 = 60K
We don't have 60K completed products yet

**Comment by stephanegigandet** [comment]
What Tacite says is correct. If you want complete products only, use /state/complete.
The last page right now is http://world.openfoodfacts.org/state/complete/2245
On http://world.openfoodfacts.org/2245 you then get the incomplete products.
Closing the bug as it is the intended behavior.
