### ISSUE TITLE
Give a hint of the language of the image to users (power users?)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#3105]
When no ingredients are completed, powerusers and users have no way to see if the images are in the right language. Putting  the langcode in the alt description could be a way to solve this.
![image](https://user-images.githubusercontent.com/1689815/77517368-4ae8eb00-6e7c-11ea-9e78-72dea7292f06.png)

**Comment by teolemon** [comment]
My workaround was to inspect the image
![image](https://user-images.githubusercontent.com/1689815/77518101-702a2900-6e7d-11ea-9d33-95d0dab91fbe.png)

**Comment by areeshatariq** [comment]
@teolemon $product_ref->{lc} needs to be concatenated in alt, right?

**Comment by stephanegigandet** [comment]
@areeshatariq : not exactly, we want to put the language of the image, not the main language of the product. (products can have images in multiple languages)

The corresponding code is in Images.pm , in the function sub display_image($$$)
