### ISSUE TITLE
Ingredient parsing: remove "ingredients" when it is the first word, even if there is no separator

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#3115]
### What
Through OCR, we sometimes get things like "Ingredients eau, sucre" without a separator after "Ingredients".

e.g. 
![image](https://user-images.githubusercontent.com/8158668/77643383-890b0b00-6f5f-11ea-9461-5f6375d891d8.png)

https://fr.openfoodfacts.org/produit/3175681211018/riz-soja-tikka-massala-cereal-bio

### Part of
- #5706

**Comment by jolesh** [comment]
I guess we need sth simmilar to this(see below), which changes "Ingredients something" into "something". Can sb explain to me how the example works?
```
# Organic label can appear as a part of a longer word.
# Separate it so it can be detected
$text =~ s/\b(luomu)\B/$1 /ig;
```

**Comment by benbenben2** [comment]
@stephanegigandet 
That was 3+ years ago. Seems to be extracted correctly now if you extract from the same image as in this issue

**Comment by stephanegigandet** [comment]
@benbenben2 good, let's close it then.
