### ISSUE TITLE
Add a way to unselect images for Front/Ingredients/Calories

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#313]
Images might be selected for Front/Ingredients/Calories in a given language, while this language is not present on the packaging.

There should be a way to clear any selected image for one of those three, without having selected another, thus flagging the language for deletion if no image is selected.

**Comment by aleksejrs** [comment]
It is also a problem because the product is not shown in "pictures to be validated".

**Comment by stephanegigandet** [comment]
Live in production.
