### ISSUE TITLE
Lots of Perl warnings when initializing Product Opener

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#315]
Initialization of the different modules called in by Product Opener perl scripts (including startup.pl which loads all of them when mod_perl starts) results in a lot of repeated Perl warnings:

Step to reproduce:  perl product.pl

[..]
SiteLang{android_apk_app_link}
SiteLang{android_apk_app_link}{en}
[Thu Jun  2 14:27:04 2016] Tags.pm: Use of uninitialized value in substitution (s///) at Blogs/Lang.pm line 11538.
[Thu Jun  2 14:27:04 2016] Tags.pm: Use of uninitialized value in substitution (s///) at Blogs/Lang.pm line 11538.
[Thu Jun  2 14:27:04 2016] Tags.pm: Use of uninitialized value in substitution (s///) at Blogs/Lang.pm line 11538.
[Thu Jun  2 14:27:04 2016] Tags.pm: Use of uninitialized value in substitution (s///) at Blogs/Lang.pm line 11538.
[Thu Jun  2 14:27:04 2016] Tags.pm: Use of uninitialized value in substitution (s///) at Blogs/Lang.pm line 11538.
[Thu Jun  2 14:27:04 2016] Tags.pm: Use of uninitialized value in substitution (s///) at Blogs/Lang.pm line 11538.
[Thu Jun  2 14:27:04 2016] Tags.pm: Use of uninitialized value in substitution (s///) at Blogs/Lang.pm line 11538.
[Thu Jun  2 14:27:04 2016] Tags.pm: Use of uninitialized value in substitution (s///) at Blogs/Lang.pm line 11538.
[Thu Jun  2 14:27:04 2016] Tags.pm: Use of uninitialized value in substitution (s///) at Blogs/Lang.pm line 11538.
[Thu Jun  2 14:27:04 2016] Tags.pm: Use of uninitialized value in substitution (s///) at Blogs/Lang.pm line 11538.
[..]
[Thu Jun  2 14:27:04 2016] Tags.pm: Use of uninitialized value $file in substitution (s///) at Blogs/Store.pm line 79.
[Thu Jun  2 14:27:04 2016] Tags.pm: Use of uninitialized value $file in substitution (s///) at Blogs/Store.pm line 81.
[Thu Jun  2 14:27:04 2016] Tags.pm: Use of uninitialized value $file in substitution (s///) at Blogs/Store.pm line 83.
[..]
[Thu Jun  2 14:10:31 2016] Tags.pm: Use of uninitialized value in sprintf at Blogs/Tags.pm line 2285.
[Thu Jun  2 14:10:31 2016] Tags.pm: Use of uninitialized value in sprintf at Blogs/Tags.pm line 2285.
[Thu Jun  2 14:10:31 2016] Tags.pm: Use of uninitialized value in sprintf at Blogs/Tags.pm line 2285.
Tags.pm - loading tags texts
[Thu Jun  2 14:10:32 2016] Products.pm: "my" variable $sec masks earlier declaration in same scope at Blogs/Products.pm line 530.
[Thu Jun  2 14:10:32 2016] Products.pm: "my" variable $min masks earlier declaration in same scope at Blogs/Products.pm line 530.
[Thu Jun  2 14:10:32 2016] Products.pm: "my" variable $hour masks earlier declaration in same scope at Blogs/Products.pm line 530.
[Thu Jun  2 14:10:32 2016] Products.pm: "my" variable $mday masks earlier declaration in same scope at Blogs/Products.pm line 530.
[Thu Jun  2 14:10:32 2016] Products.pm: "my" variable $mon masks earlier declaration in same scope at Blogs/Products.pm line 530.
[Thu Jun  2 14:10:32 2016] Products.pm: "my" variable $year masks earlier declaration in same scope at Blogs/Products.pm line 530.
[Thu Jun  2 14:10:32 2016] Products.pm: "my" variable $wday masks earlier declaration in same scope at Blogs/Products.pm line 530.
[Thu Jun  2 14:10:32 2016] Products.pm: "my" variable $yday masks earlier declaration in same scope at Blogs/Products.pm line 530.
[Thu Jun  2 14:10:32 2016] Products.pm: "my" variable $isdst masks earlier declaration in same scope at Blogs/Products.pm line 530.
[Thu Jun  2 14:10:32 2016] Images.pm: "my" variable $x masks earlier declaration in same scope at Blogs/Images.pm line 476.
[Thu Jun  2 14:10:32 2016] Images.pm: "my" variable $x masks earlier declaration in same scope at Blogs/Images.pm line 744.
[Thu Jun  2 14:10:32 2016] Images.pm: "my" variable $x masks earlier declaration in same scope at Blogs/Images.pm line 848.
[Thu Jun  2 14:10:32 2016] Images.pm: "my" variable $html masks earlier declaration in same scope at Blogs/Images.pm line 1001.
[Thu Jun  2 14:10:32 2016] Ingredients.pm: Blogs::Ingredients::analyze_ingredients() called too early to check prototype at Blogs/Ingredients.pm line 324.
[Thu Jun  2 14:10:32 2016] Ingredients.pm: Blogs::Ingredients::analyze_ingredients() called too early to check prototype at Blogs/Ingredients.pm line 328.
[Thu Jun  2 14:10:32 2016] Ingredients.pm: Use of uninitialized value $other_names in split at Blogs/Ingredients.pm line 88, <IN> line 2.
[Thu Jun  2 14:10:32 2016] Ingredients.pm: Use of uninitialized value $other_names in split at Blogs/Ingredients.pm line 88, <IN> line 23.
[Thu Jun  2 14:10:32 2016] Ingredients.pm: Use of uninitialized value $other_names in split at Blogs/Ingredients.pm line 88, <IN> line 24.
[Thu Jun  2 14:10:32 2016] Ingredients.pm: Use of uninitialized value $other_names in split at Blogs/Ingredients.pm line 88, <IN> line 1.
[Thu Jun  2 14:10:32 2016] Ingredients.pm: Use of uninitialized value $other_names in split at Blogs/Ingredients.pm line 88, <IN> line 2.
[Thu Jun  2 14:10:32 2016] Ingredients.pm: Use of uninitialized value $other_names in split at Blogs/Ingredients.pm line 88, <IN> line 3.
[Thu Jun  2 14:10:32 2016] Ingredients.pm: Use of uninitialized value $other_names in split at Blogs/Ingredients.pm line 88, <IN> line 37.
[Thu Jun  2 14:10:32 2016] Ingredients.pm: Use of uninitialized value $other_names in split at Blogs/Ingredients.pm line 88, <IN> line 303.
[Thu Jun  2 14:10:32 2016] Ingredients.pm: Use of uninitialized value $other_names in split at Blogs/Ingredients.pm line 88, <IN> line 304.
[Thu Jun  2 14:10:32 2016] Ingredients.pm: Use of uninitialized value $other_names in split at Blogs/Ingredients.pm line 88, <IN> line 336.
[Thu Jun  2 14:10:32 2016] Display.pm: "my" variable $r masks earlier declaration in same scope at Blogs/Display.pm line 178.
[Thu Jun  2 14:10:32 2016] Display.pm: "my" variable $link masks earlier declaration in same scope at Blogs/Display.pm line 1128.
[Thu Jun  2 14:10:32 2016] Display.pm: "my" variable $html_nutrient_levels masks earlier declaration in same scope at Blogs/Display.pm line 6031.
[Thu Jun  2 14:10:32 2016] Display.pm: "my" variable $sodium masks earlier declaration in same scope at Blogs/Display.pm line 6584.
[Thu Jun  2 14:10:32 2016] Users.pm: "my" variable $email masks earlier declaration in same scope at Blogs/Users.pm line 315.

**Comment by teolemon** [comment]
@hangy do we still have many of those ?

**Comment by VaiTon** [comment]
@teolemon not for me. @hangy ?

**Comment by hangy** [comment]
Not as much unnecessary logging as before:
```
backend_1    | [Wed Jul 10 08:58:51 2019] Display.pm: Possible unintended interpolation of @: in string at /opt/product-opener/lib/ProductOpener/Display.pm line 6541.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: given is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 242.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: when is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 246.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: given is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 263.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: when is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 265.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: when is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 279.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: when is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 299.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: when is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 317.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: when is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 338.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: given is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 394.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: when is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 395.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: when is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 399.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: when is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 424.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: given is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 465.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: when is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 467.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: when is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 483.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: when is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 517.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: when is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 532.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: given is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 580.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: when is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 581.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: when is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 585.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: when is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 622.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: given is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 631.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: when is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 633.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: when is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 759.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: when is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 765.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: when is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 816.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: given is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 823.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: when is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 825.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: when is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 832.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: when is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 859.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: when is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 907.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: given is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 943.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: when is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 944.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: when is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 945.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: when is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 950.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: when is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 963.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: given is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 968.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: when is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 970.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: when is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 976.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: when is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 997.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: when is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 1002.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: when is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 1048.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: given is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 1073.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: when is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 1074.
backend_1    | [Wed Jul 10 08:58:51 2019] IsEmail.pm: when is experimental at /opt/perl/local/lib/perl5/Email/IsEmail.pm line 1080.
backend_1    | [Wed Jul 10 08:58:52 2019] Food.pm: Use of uninitialized value in sprintf at /opt/product-opener/lib/ProductOpener/Food.pm line 4767.
backend_1    | [Wed Jul 10 08:58:52 2019] Food.pm: Redundant argument in sprintf at /opt/product-opener/lib/ProductOpener/Food.pm line 4767.
backend_1    | [Wed Jul 10 08:58:52 2019] Food.pm: Use of uninitialized value in sprintf at /opt/product-opener/lib/ProductOpener/Food.pm line 4767.
backend_1    | [Wed Jul 10 08:58:52 2019] Food.pm: Redundant argument in sprintf at /opt/product-opener/lib/ProductOpener/Food.pm line 4767.
backend_1    | [Wed Jul 10 08:58:52 2019] Food.pm: Use of uninitialized value in sprintf at /opt/product-opener/lib/ProductOpener/Food.pm line 4767.
backend_1    | [Wed Jul 10 08:58:52 2019] Food.pm: Redundant argument in sprintf at /opt/product-opener/lib/ProductOpener/Food.pm line 4767.
backend_1    | [Wed Jul 10 08:58:52 2019] Food.pm: Use of uninitialized value in sprintf at /opt/product-opener/lib/ProductOpener/Food.pm line 4767.
backend_1    | [Wed Jul 10 08:58:52 2019] Food.pm: Redundant argument in sprintf at /opt/product-opener/lib/ProductOpener/Food.pm line 4767.
backend_1    | [Wed Jul 10 08:58:52 2019] Food.pm: Use of uninitialized value in sprintf at /opt/product-opener/lib/ProductOpener/Food.pm line 4767.
backend_1    | [Wed Jul 10 08:58:52 2019] Food.pm: Redundant argument in sprintf at /opt/product-opener/lib/ProductOpener/Food.pm line 4767.
backend_1    | [Wed Jul 10 08:58:52 2019] Food.pm: Use of uninitialized value in sprintf at /opt/product-opener/lib/ProductOpener/Food.pm line 4767.
backend_1    | [Wed Jul 10 08:58:52 2019] Food.pm: Redundant argument in sprintf at /opt/product-opener/lib/ProductOpener/Food.pm line 4767.
backend_1    | [Wed Jul 10 08:58:52 2019] Food.pm: Use of uninitialized value in sprintf at /opt/product-opener/lib/ProductOpener/Food.pm line 4767.
backend_1    | [Wed Jul 10 08:58:52 2019] Food.pm: Redundant argument in sprintf at /opt/product-opener/lib/ProductOpener/Food.pm line 4767.
backend_1    | [Wed Jul 10 08:58:52 2019] Food.pm: Use of uninitialized value in sprintf at /opt/product-opener/lib/ProductOpener/Food.pm line 4767.
backend_1    | [Wed Jul 10 08:58:52 2019] Food.pm: Redundant argument in sprintf at /opt/product-opener/lib/ProductOpener/Food.pm line 4767.
backend_1    | [Wed Jul 10 08:58:52 2019] Food.pm: Use of uninitialized value in sprintf at /opt/product-opener/lib/ProductOpener/Food.pm line 4767.
backend_1    | [Wed Jul 10 08:58:52 2019] Food.pm: Redundant argument in sprintf at /opt/product-opener/lib/ProductOpener/Food.pm line 4767.
backend_1    | [Wed Jul 10 08:58:52 2019] Food.pm: Use of uninitialized value in sprintf at /opt/product-opener/lib/ProductOpener/Food.pm line 4767.
backend_1    | [Wed Jul 10 08:58:52 2019] Food.pm: Redundant argument in sprintf at /opt/product-opener/lib/ProductOpener/Food.pm line 4767.
backend_1    | [Wed Jul 10 08:58:52 2019] Food.pm: Use of uninitialized value in sprintf at /opt/product-opener/lib/ProductOpener/Food.pm line 4767.
backend_1    | [Wed Jul 10 08:58:52 2019] Food.pm: Redundant argument in sprintf at /opt/product-opener/lib/ProductOpener/Food.pm line 4767.
backend_1    | [Wed Jul 10 08:58:52 2019] Food.pm: Use of uninitialized value in sprintf at /opt/product-opener/lib/ProductOpener/Food.pm line 4767.
backend_1    | [Wed Jul 10 08:58:52 2019] Food.pm: Redundant argument in sprintf at /opt/product-opener/lib/ProductOpener/Food.pm line 4767.
```

**Comment by CharlesNepote** [comment]
Email::IsEmail are easy to solve. I made a benchmark and we could easily change to Email::Valid library. I'm not in front of my computer but, as a reminder, we can search for "IsEmail" in Open Food Facts slack space to see the details.

**Comment by hangy** [comment]
There are no Perl warnings on start up any more.
