### ISSUE TITLE
Nudge to complete nutrition facts to get the Nutri-Score

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#3157]
### What
Add a Nudge to complete nutrition facts to get the Nutri-Score, to be shown if and only if we already have a nutrition facts picture

### Mockup
![image](https://user-images.githubusercontent.com/1689815/77848919-4730cd80-71c8-11ea-97d0-99081110191f.png)

### Part of 
- #5708 
- #5517

**Comment by areeshatariq** [comment]
@teolemon @stephanegigandet we need to add a button on the product page to direct the user to complete the nutrition facts when the nutrition facts picture is added?

**Comment by stephanegigandet** [comment]
@areeshatariq : when we already have a nutrition facts picture, we should add a button.

**Comment by teolemon** [comment]
Fixed by Knowledge Panels
