### ISSUE TITLE
Show Robotoff questions to non-logged users, with a prompt to sign-up or login

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#3158]
### What
Show Robotoff questions to non-logged users, with a prompt to sign-up or login.
Code pointer (original PR by @hangy) : https://github.com/openfoodfacts/openfoodfacts-server/pull/1705/files

### Part of
- #5708 

### Mockup
![image](https://user-images.githubusercontent.com/1689815/87070744-89cb6280-c219-11ea-9ae0-a101af7b521e.png)

**Comment by teolemon** [comment]
@hangy @VaiTon @raphael0202 added a mockup of an improved web experience for Robotoff that would enable to convert part of the 1,4 million monthly visitors into contributors

**Comment by teolemon** [comment]
display_robotoff(barcode):
on_button_click():
>>>>if is_logged_in:
>>>>>>>>current_behaviour(yes,barcode,user)
>>>>else:
>>>>>>>>login_or_signup_modal(yes, barcode) > redirect_to_the_product_page > current_behaviour(yes,barcode,user)

**Comment by teolemon** [comment]
Relevant integration points: 
Javascript that displays Robotoff: https://github.com/openfoodfacts/openfoodfacts-server/blob/9af7d8767d3e2a84b055f96b9fa18dc3a45988e6/html/js/display-product.js#L33
User signup: https://github.com/openfoodfacts/openfoodfacts-server/blob/b30b6152c0d970de44ad1f2f1bfdf124489c45e3/cgi/user2.pl
Template for user signup: user_form2.tt.html

**Comment by CharlesNepote** [comment]
The call to Robotoff questions is only available for registered users. Before rewrriting JS code we have to display it for every users:
https://github.com/openfoodfacts/openfoodfacts-server/blob/319b66b14a8717ddd3e8123eaaf6a30398d58d0c/templates/web/pages/product/product_page.tt.html#L50
```diff
- [% IF (user_id.defined) && (robotoff_url.defined) && (robotoff_url.length > 0) %]
+ [% IF (robotoff_url.defined) && (robotoff_url.length > 0) %]
```
Then test if user is connected or not. We can start with a simple check to the HTML id `logged_in_user_id` as we are doing in Power User Script.
```js
    /**
     * getConnectedUserID: returns user id of the current connected user
     *
     * @param    none
     * @returns  {String} user id; Example: "charlesnepote"
     */
    function getConnectedUserID() {
        // Extract connected user_id by reading <span id="user_id">charlesnepote</span>
        var user_name = $("#logged_in_user_id").text();
        console.log("getConnectedUserID() > user_name: "); console.log(user_name);
        return user_name;
    }
```
If the user is not connected, then display form in a modal.

1. If the user already has an account

2. If the user doesn't have an account
user.pl does not have a callback to get back to the product.

TO BE COMPLETED
```js
    /**
     * displayLoginForm
     *
     * @param    callback?
     * @returns  none
     */
    function displayLoginForm() {
        // Display form
        // TODO: manage i18n
        const form =
              `<form method="post" action="/cgi/session.pl">
                  <label>Nom d'utilisateur ou adresse e-mail :
                     <input type="text" name="user_id" autocomplete="username" required>
                  </label>
                  <label>Mot de passe
                     <input type="password" name="password" autocomplete="current-password" required>
                  </label>
                  <label>
                     <input type="checkbox" name="remember_me" checked>
                     Se souvenir de moi
                  </label>
                  <input type="submit" name=".submit" value="Se connecter" class="button small">
              </form>`;
        showPowerUserInfo(form); // open a new modal

        // TODO: if the user needs to create a user account

        document.getElementById('property').addEventListener('submit', function(e){
            e.preventDefault();

            // If the user validate the user login form
            const userLoginURL = "https://world.openfoodfacts.org/" + "/cgi/session.pl";
            const user = document.getElementsByName("user_id");
            const password = document.getElementsByName("password");
            fetch(userLoginURL, {
                // Adding method type
                method: "POST",
                // Adding body or contents to send
                body: `user=${user}&password=${password}`
            })
            // Converting to JSON
                .then(response.json())
            // Test if status is 200
                .then(response => {
                console.log(response);
            });
        });
    }
```

**Comment by alexgarel** [comment]
With google fellowship, anonymous contribution to robotoff questions was implemented.

So we can no use it, and, of course, we can still encourage users to create an account, but it can simply redirect to the account creation page.

We have yet to implement the client side features:

- https://github.com/openfoodfacts/openfoodfacts-server/issues/6506
- https://github.com/openfoodfacts/smooth-app/issues/1319

**Comment by alexgarel** [comment]
We can close this issue, you can test it on openfoodfacts.net

**Comment by raphael0202** [comment]
I've just tried it on dev instance, the vote is indeed registered on Robotoff dev :+1:
