### ISSUE TITLE
Tags.pm: Use of uninitialized value in substitution (s///) at Blogs/Lang.pm line 11538.

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#316]
Initialization of the different modules called in by Product Opener perl scripts (including startup.pl which loads all of them when mod_perl starts) results in:

Tags.pm: Use of uninitialized value in substitution (s///) at Blogs/Lang.pm line 11538.

Step to reproduce: perl product.pl

**Comment by hangy** [comment]
Fixed in 6c0b14cfe9019329d32aec902e471047e49f305b
