### ISSUE TITLE
encountered object '566943468dbe98e61000002b', but neither allow_blessed nor convert_blessed settings are enabled at /home/off-fr/cgi//Blogs/Display.pm line 6847.

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#317]
encountered object '566943468dbe98e61000002b', but neither allow_blessed nor convert_blessed settings are enabled at /home/off-fr/cgi//Blogs/Display.pm line 6847.
on page 500
http://world.openfoodfacts.org/cgi/search.pl?search_terms=&page=500&json=1

PAge 498 works fine:
http://world.openfoodfacts.org/cgi/search.pl?search_terms=&page=498&json=1

PAge 499 doesn't work:
http://world.openfoodfacts.org/cgi/search.pl?search_terms=&page=498&json=1

Page 501 works fine:
http://world.openfoodfacts.org/cgi/search.pl?search_terms=&page=501&json=1

**Comment by VaiTon** [comment]
Guess this has been fixed? @teolemon

**Comment by stephanegigandet** [comment]
This is due to invalid characters that cannot be encoded as JSON. Related to #1944. I'll close this one.
