### ISSUE TITLE
"*Ingrédients biologiques" is not parsed correctly

### ISSUE THREAD

**Issue by raphael0202** [openfoodfacts/openfoodfacts-server#3178]
**Describe the bug**
On organic products, we often find organic ingredients marked with '*'. At the end of the ingredient list, we often have "*ingrédients biologiques". Here, this mention is incorrectly detected as a "fr:S" ingredient.

**To Reproduce**
1. Go to https://fr.openfoodfacts.org/produit/8003716002988/tomates-concassees-biologique-au-jus-de-tomate-rega-marca
2.  Scroll down to ingredient analysis
3. Description of ingredients with '*' "*Ingrédients biologiques" is not parsed correctly:
`
    1. Tomates concassées -> en:chopped-tomatoes - vegan: yes - vegetarian: yes - percent_min: 33.3333333333333 - percent_max: 100
    2. jus de tomate -> en:tomato-juice - labels: en:organic - vegan: yes - vegetarian: yes - percent_min: 0 - percent_max: 50
    3. S -> fr:S - percent_min: 0 - percent_max: 33.3333333333333
`

**Expected behavior**
Either add the en:organic property to the marked ingredients, or discard the '*' description.

**Comment by stephanegigandet** [comment]
There's now an easier way to reproduce / test parsing bugs, with this form:

https://fr.openfoodfacts.org/cgi/test_ingredients_analysis.pl?ingredients_text=Tomates+concass%C3%A9es%2C+jus+de+tomate*.+*INGR%C3%89DIENTS+BIOLOGIQUES&type=add&action=process&.submit=Valider

**Comment by stephanegigandet** [comment]
811 instances of the ingredient "s" : https://fr.openfoodfacts.org/ingredient/s

**Comment by raphael0202** [comment]
Thank for the URL, is there a JSON page? It could be really useful for spellcheck on robotoff, to be sure that the spellcheck correction is recognized by the parser.

**Comment by stephanegigandet** [comment]
Fixed and deployed.
