### ISSUE TITLE
Provide a brand suggestions API

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#318]
Provide an API that returns brand suggestions if given a barcode.
== Use Case ==
Autocomplete magic in the official app, and in games to help complete Open Food Facts
== Implementation==
The idea would be to iterate until there's a least one answer (there won't be for the exact barcode if the product has no brand or doesn't exist yet in Open Food Facts)

http://world.openfoodfacts.org/code/9300462112923/brands.json
http://world.openfoodfacts.org/code/930046211292x/brands.json
http://world.openfoodfacts.org/code/93004621129xx/brands.json
http://world.openfoodfacts.org/code/9300462112xxx/brands.json

**Comment by CloCkWeRX** [comment]
#508 is a bit similar, and it would be nice if they just made GEPIR open/one click

**Comment by raphael0202** [comment]
I'm closing this issue, as Robotoff already offers a brand suggestion API (even though the barcode range is only use to validate the brand, not for detection)
