### ISSUE TITLE
Last ingredient of "May contain..."  mention is incorrectly parsed as an ingredient

### ISSUE THREAD

**Issue by raphael0202** [openfoodfacts/openfoodfacts-server#3185]
**Describe the bug**
See https://fr.openfoodfacts.org/cgi/test_ingredients_analysis.pl?ingredients_text=Farine%2C+levure.+Peut+contenir+des+traces+de+_soja_%2C+_amandes_%2C+_noisettes_+et+_noix+de+cajou_.&type=add&action=process&.submit=Envoyer

Here, "_noix de cajou_" is parsed as "cajou_" as ingredient.

**Number of products impacted**
41 products on https://fr.openfoodfacts.org/ingredient/cajou_
May be a more general bug.

**Comment by stephanegigandet** [comment]
the regexp was like (noix|noix de cajou) and the match stopped at noix for the last ingredient. I sorted the tokens by length, it seems to be working.
