### ISSUE TITLE
Issue cropping on a new product

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#3186]
Issue cropping on a new product, the result appears different than the preview

![image](https://user-images.githubusercontent.com/1689815/78243504-2b893800-74e4-11ea-9a8f-26adbbf521a0.png)

https://world.openfoodfacts.org/cgi/product.pl?type=edit&code=3273220135709

**Comment by CharlesNepote** [comment]
I experimented very few issues like this. I think it's when you use rotation + zoom, or when you use rotation to fast.

I fixed the product: https://world.openfoodfacts.org/product/3273220135709/creme-au-chocolat

**Comment by stephanegigandet** [comment]
We could try to disable rotation buttons until the image has loaded and the cropper has fully been initialized.
