### ISSUE TITLE
Label not properly displayed when viewing from world

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#32]
http://world.openfoodfacts.org/product/3273120010540/millet-celnat
EG: AB Bio on this page
It's probably related to the fact that the label is prefixed with Fr:

**Comment by sl956** [comment]
Are you sure it is a bug and not a feature? ;-)

**Comment by stephanegigandet** [comment]
I think it is a feature indeed. ;-) (showing "fr:Agriculture Biologique"). Should I remove the language indication?

We should display the logo in any case, that's a bug.

**Comment by stephanegigandet** [comment]
![bug_fr_label_image_on_world](https://cloud.githubusercontent.com/assets/8158668/15366750/11b061fc-1d26-11e6-912a-da210e36715b.png)

Added French logo, leaving the fr: prefix. Re-open if you think it should be removed/changed.
