### ISSUE TITLE
Organizing the Installation Docs

### ISSUE THREAD

**Issue by Jen-Lopez** [openfoodfacts/openfoodfacts-server#3204]
@alifafaruk, @lucasortizny, and I are new contributors and had trouble finding a way to install the dev environment. We looked at the website and thought it wasn't beginner-friendly and after some time, we found the docker installation guide in the repository that was easier. We want to create a guide for individuals new to open source that would have links to both the docker installation guide and a separate md file for the installation guide on the [website](https://en.wiki.openfoodfacts.org/Product_Opener/Installation).

**Comment by CharlesNepote** [comment]
Have you tried https://github.com/openfoodfacts/openfoodfacts-server/blob/master/docker/dev-environment-quick-start-guide.md ?

Though, this documentation may be hard to find...

**Comment by Jen-Lopez** [comment]
Yes we found that guide through the slack channel. What we would like to do is to make it easier for new contributors to find them. Possibly by making an "installation" folder in the repo with the guides and linking them to the readme file under the "How do I get set up" section.

**Comment by stephanegigandet** [comment]
@Jen-Lopez : that's a very good idea, it would be great if you can do it.
