### ISSUE TITLE
Search and apostrophe

### ISSUE THREAD

**Issue by TaciteOFF** [openfoodfacts/openfoodfacts-server#3215]
**Describe the bug**
I regularly use my iPhone to search for products on the OpenFoodFacts website.
On my iPhone, the apostrophe is written " ’ ".
On my Macbook, the apostrophe is written " ' ". 
(It probably depends on which keyboard or system locales I'm using)
The problem is that the results I get are very different.
If I want to find the brand "Comme j'aime" for instance.

On my iPhone I get only 13 products when I get 88 products on the website.

Mobile : https://fr.openfoodfacts.org/cgi/search.pl?action=process&search_terms=Comme%20j’aime&sort_by=unique_scans_n&page_size=20

Desktop : https://fr.openfoodfacts.org/cgi/search.pl?search_terms=Comme+j%27aime&search_simple=1&action=process

**Expected behavior**
These ASCII characters should be considered the same and give the same results : 
’
'

Thank you.

**Comment by stephanegigandet** [comment]
Working on it.

@TaciteOFF : we use the "assign" feature of github to mark who is actively working (or at least planning to in the near future) on a bug. If you just want to notify someone about the bug, it's best to just use a @ mention in the text or in a comment.

**Comment by TaciteOFF** [comment]
@stephanegigandet Oops, didn't know about that. Sorry!
By the way, still about the search feature, when you search for a single ASCII character, even if it doesn't exist, the search results returns all the database.
Exemple, I searched for "|" and got this https://world.openfoodfacts.org/cgi/search.pl?action=process&sort_by=unique_scans_n&page_size=20&action=display
Not a big issue and not urgent but maybe it would be better to pop-up a message like "Your search keyword should have at least 3 characters" or "No results found".
