### ISSUE TITLE
Ingredients recognition for delimiters

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#3222]
**Describe the bug**
The recognition process seems replace unknown characters with a `,`. This introduces errors  for ingredient delimiters that are unknown, such as the dot in M&S products.

**To Reproduce**
Look at https://world.openfoodfacts.org/product/00486842/spiced-lamb-stew-m-s

**Comment by stephanegigandet** [comment]
The ? characters instead of the · were sent by Yuka in 2017. Our current OCR recognizes the dots and parses them correctly. I've updated the product by running our OCR on top of the existing ingredient image.
