### ISSUE TITLE
Adding tags in product edit form is impossible on Microsoft Edge browser

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#3251]
Typing to add a tag does nothing.

![image](https://user-images.githubusercontent.com/8158668/79068382-c93fec80-7cc6-11ea-9060-36e13ff8e21d.png)

**Comment by hangy** [comment]
Is this Old Edge or Chromium Edge or both?

**Comment by stephanegigandet** [comment]
It may be this bug: https://github.com/yairEO/tagify/issues/440

**Comment by stephanegigandet** [comment]
I'm running Microsoft Edge 44.18362.449.0 - Microsoft EdgeHTML 18.18362

**Comment by hangy** [comment]
> It may be this bug: [yairEO/tagify#440](https://github.com/yairEO/tagify/issues/440)

I don't think so. In IE11, the tagify UI does not work at all 
![image](https://user-images.githubusercontent.com/87124/79069224-ef688b00-7ccc-11ea-9de5-a90e94d7acf3.png) whereas old Edge (about the same version as you) does not display any cursor at all 
![image](https://user-images.githubusercontent.com/87124/79069282-51c18b80-7ccd-11ea-9924-4b837b4188af.png).

**Comment by stephanegigandet** [comment]
This demo does work on my Edge browser: https://yaireo.github.io/tagify/

**Comment by stephanegigandet** [comment]
So it's not just a pure theoritical bug: I had a volunteer on the phone yesterday that could not enter categories, labels etc. We then exchanged through Slack and shared the screen, and she was running Edge and had this bug.

**Comment by GendelfLugansk** [comment]
Edge 44 reports this error: SCRIPT5007: SCRIPT5007: Unable to get property 'define' of undefined or null reference which happens here: https://github.com/openfoodfacts/openfoodfacts-server/blob/f482ca2e6c121556b61c92610a0ae95852f2c58c/html/js/display-product.js#L238

According to MDN, window.customElements is supported starting from Edge 79

**Comment by GendelfLugansk** [comment]
I made a PR that fixes JS error in Edge 44 and that seems to help with tags. However, I don't know what is that `RobotoffAsker` thing and how to check if it's working or not

**Comment by stephanegigandet** [comment]
@GendelfLugansk : I tried to deploy your PR to test, but the error in display-products.js still happens for me: "0: Unable to get property 'define' of undefined or null reference". But actually this error is on the product page, not the product edit form when someone modify the product, so I'm a bit confused.

**Comment by stephanegigandet** [comment]
RobotoffAsker is something to display questions about products on product pages. cc @raphael0202
