### ISSUE TITLE
Support for organic ingredients

### ISSUE THREAD

**Issue by BenibenOFF** [openfoodfacts/openfoodfacts-server#326]
Maybe we could create some indication in the "ingredients list" for "ingredients coming from biological agriculture" ?

For allergens  we use this method :  _allergen_ , we could create the same kind of indications.

**Comment by teolemon** [comment]
"Biologic ingredients are starred"
"Biologic ingredients are in bold"
We need a way to handle this.

**Comment by aleene** [comment]
Now I add the adjective "organic" to those ingredients. Is sometimes a lot of typing. Another way to mark these would be useful.

**Comment by BenibenOFF** [comment]
I think we need a kind of "balise" but it's difficult to choose an easy solution.

**Comment by teolemon** [comment]
This has been fixed.
