### ISSUE TITLE
Product URL redirects

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#327]
The url (http://ht.openfoodfacts.org/produit/0029000017993) for accessing a product consists of multiple components:
* scheme: http://
* region: ht
* server: openfoodfacts.org
* product_word: produit
* product_barcode: 0029000017993
In this url the region must be matched to the appropriate product_word. (what happens in multilingual countries?). This requires the knowledge of what the product_words are for each region. This is a long table.

Create a redirect which maps the generic product_word "product" to the appropriate region-specific product_word. So:

http://ht.openfoodfacts.org/product/0029000017993 redirects to http://ht.openfoodfacts.org/produit/0029000017993

**Comment by hangy** [comment]
What about conflicting URL component? I don't know of any right now, but it might be possible that "product" in one language means something completely different than in English - which is the value proposed to redirect from in the issue. This might be avoided by using "en:product" in the URL to qualify the language.

**Comment by hangy** [comment]
Implemented in changeset `f57483dbddbb6bf91bad432ca2fea14af897b9f7` as in my previous proposal.

**Comment by hangy** [comment]
Published to production.

**Comment by aleene** [comment]
Very good, I will implement this in my app.
