### ISSUE TITLE
Ingredient analysis parsing: cocoa powder processed w/alkali ->with alkali

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#3270]
https://world.openfoodfacts.org/product/0858687003001/brownie-mix-moon-rabbit-foods

**Comment by svensven** [comment]
Is this a candidate to go in %abbreviations, or does that only work for full stops? Other cases from the CSV:
> Dark chocolate (cocoa liquor w/potassium carbonate...
> Pasteurized milk, active cultures w/probiotics
> virginia ham (cured w/water, salt,,,
> raisins w/soybean oil

also "without":
> Organic garbanzo beans (cooked w/o salt)
> worcestershire sauce concentrate w/o anchovies
