### ISSUE TITLE
Product edit form does not handle values in mcg and IU from imports

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#3274]
The import platforms indicates "mcg" and "iu" while the edit form expects "µg" and "IU".

-> Make the product edit form accept both
-> Standardize the units from the producers platform imports to use "µg" and "IU".

**Comment by VaiTon** [comment]
@stephanegigandet can we close?

**Comment by stephanegigandet** [comment]
Fixed and deployed.
