### ISSUE TITLE
Untranslated string

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#3279]
https://github.com/openfoodfacts/openfoodfacts-server/blob/9eda3d89ab05bfdc50bb780543c133fe2f0abbf2/scripts/gen_top_tags.pl#L324
Untranslated string

**Comment by stephanegigandet** [comment]
This code is not used anymore, I'll remove it.

**Comment by stephanegigandet** [comment]
Removed.
