### ISSUE TITLE
Miniatures of products don't show anymore on facets after edit

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#3280]
Miniatures of products don't show anymore on facets after edit. It's not a problem of multilingual products. 
Here's the API result: https://world.openfoodfacts.org/api/v0/product/3073781069303.json
![image](https://user-images.githubusercontent.com/1689815/79544407-45ec1580-808f-11ea-87a4-5abc39f32bd6.png)
![image](https://user-images.githubusercontent.com/1689815/79544428-4e445080-808f-11ea-9ae2-36f9698cfb42.png)
![image](https://user-images.githubusercontent.com/1689815/79544454-57cdb880-808f-11ea-8c45-aec019600283.png)
![image](https://user-images.githubusercontent.com/1689815/79544500-674d0180-808f-11ea-94ee-29813e0e5193.png)

**Comment by stephanegigandet** [comment]
We were missing the "lc" field in the fields we requested. Since https://github.com/openfoodfacts/openfoodfacts-server/pull/3257 we fetch only the fields we need instead of all fields. (bug #1560)

Fixing.

**Comment by teolemon** [comment]
@stephanegigandet why were some of the products spared by the bug ?
