### ISSUE TITLE
Mobile layout on small screens clips left hand menu after login

### ISSUE THREAD

**Issue by CloCkWeRX** [openfoodfacts/openfoodfacts-server#329]
On a galaxy s6 or similar small resolution browser
- http://world.openfoodfacts.org
- Login
- Click on the person icon to reopen the left hand menu

Expected:
Site more or less works

Actual:
![image](https://cloud.githubusercontent.com/assets/365751/16354738/5732d18a-3ade-11e6-8241-895cf97575b6.png)

**Comment by hangy** [comment]
Can anyone reproduce this? This is what it looks like in Chrome's emulated S5: ![image](https://user-images.githubusercontent.com/87124/69903313-f0d98c80-1397-11ea-8b31-a7b4ac0c7f7c.png)

**Comment by CloCkWeRX** [comment]
No longer an issue on my s7; I'm happy to close it. I think a funky slide transition as added at some point that resolved it.
