### ISSUE TITLE
Unexpected use of undefined in html/js/product-multilingual.js#L658

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#3293]
html/js/product-multilingual.js#L658
Unexpected use of undefined

``` 
initializeTagifyInputs();

  if ($.cookie('use_low_res_images') !== undefined) {
 Check warning on line 658 in html/js/product-multilingual.js
html/js/product-multilingual.js#L658
Unexpected use of undefined
      use_low_res_images = true;
  }
```
![image](https://user-images.githubusercontent.com/1689815/79686900-fb5fca00-8243-11ea-9138-b066d6ec3609.png)

**Comment by GendelfLugansk** [comment]
That's a warning from a linter, not an actual bug. In my opinion, such line of code is perfectly fine. Also, as said in [rule](https://eslint.org/docs/rules/no-undefined) description,

> As an alternative, you can use the no-global-assign and no-shadow-restricted-names rules to prevent undefined from being shadowed or assigned a different value. This ensures that undefined will always hold its original, expected value.

In eslint config I see "extends": "eslint:recommended", which enables both [no-global-assign](https://eslint.org/docs/rules/no-global-assign) and [no-shadow-restricted-names](https://eslint.org/docs/rules/no-shadow-restricted-names). Additionally, we have `"no-shadow-restricted-names": "error",` rule in config. In these circumstances I don't see a reason to keep `"no-undefined": "warn",` rule in eslint config.

If nobody objects, I propose to remove `"no-undefined": "warn",` from config an leave that line of code at it is.
