### ISSUE TITLE
Mention every informers

### ISSUE THREAD

**Issue by TaciteOFF** [openfoodfacts/openfoodfacts-server#33]
Product pages footers state : 
"Product added on 02/05/15 00:25 by bcatelin"

We could add more information, like : 
"Product added on 02/05/15 00:25 by bcatelin, modified by X, Y, and Z on (last edit date)"

**Comment by stephanegigandet** [comment]
A good suggestion, now in production. :)

**Comment by TaciteOFF** [comment]
Thanks @stephanegigandet.

Not sure this is right : 

20 mai 2016 à 18:49:18 CEST - tacite - Création du produit - voir
27 août 2015 à 04:25:09 CEST - - automatic removal of product without information or images - voir
25 août 2015 à 15:32:47 CEST - Informations (Ajout : countries) - Création du produit - voir

When the page is created on May 20, openfoodfacts-contributors appears as informer.
Example : http://fr.openfoodfacts.org/produit/3660603000073
