### ISSUE TITLE
Images uploaded through the product edit form are automatically selected (before cropping and selection)

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#3306]
Images are selected as the new front / ingredients / nutrition images as soon as they are uploaded.

Images should not be automatically selected, especially if we have a previously selected / cropped image.

**Comment by stephanegigandet** [comment]
It's a recent change in product_image_upload.pl :

````
			if ((($imagefield =~ /^front_/) or ($imagefield =~ /^ingredients_/) or ($imagefield =~ /^nutrition_/))
				# Changed 2020-03-05: overwrite already selected images
				# and ((not defined $product_ref->{images}{$imagefield}) or ($select_image))
				) {
				$log->debug("selecting image", { imgid => $imgid, imagefield => $imagefield}) if $log->is_debug();
				process_image_crop($product_id, $imagefield, $imgid, 0, undef, undef, -1, -1, -1, -1, "full");
			}

**Comment by hangy** [comment]
Wasn't this done intentionally? #2975

**Comment by stephanegigandet** [comment]
@hangy : it was done intentionnaly for images uploaded through apps (we assume they did the cropping if they do select "ingredients", "nutrition" etc. as the image type). This change disables it for images uploaded through the OFF web site.

**Comment by stephanegigandet** [comment]
Deployed.
