### ISSUE TITLE
Load packaging codes for Luxembourg

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#331]
Claimed and done

### Part of 
- #338

**Comment by benbenben2** [comment]
@teolemon 
This seems to be done already for Luxembourg (https://lu.openfoodfacts.org/code-emballeur/lu-40-ec).

Should we close this issue?

**Comment by benbenben2** [comment]
The packaging code are there but the code to recreate them is missing. 
+ packaging codes are a bit outdated.

I will work on it.

**Comment by teolemon** [comment]
Yes, I believe I had done them manually
