### ISSUE TITLE
No ingredient analysis for a product with correct ingredients

### ISSUE THREAD

**Issue by raphael0202** [openfoodfacts/openfoodfacts-server#3315]
**To Reproduce**
1. Go to https://fr.openfoodfacts.org/produit/0613008730697/iced-tea-with-lemon-flavour-arizona
2. Even though the FR ingredients are completed and correct, no ingredient analysis is shown

**Comment by aleene** [comment]
Note that the main language is english and does not have any ingredients.

**Comment by stephanegigandet** [comment]
@aleene is right, we run the ingredients analysis only on the main language of the product. At some point we'll probably try to run the analysis on all languages, and it will be quite interesting to see if they match!

Closing this bug.

**Comment by raphael0202** [comment]
I missed the fact the main language was not French. The reason why the analysis is not shown is not easy to get though, a message in the error analysis popover to explain it would be useful in my opinion.
