### ISSUE TITLE
Load packaging codes for Poland

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#334]
### Part of 
- #338

**Comment by teolemon** [comment]
Claimed by @simonghrt

**Comment by benbenben2** [comment]
@teolemon 
This seems to be done already for Poland (https://pl.openfoodfacts.org/packager-code/pl-20131601-we).

Should we close this issue?

**Comment by teolemon** [comment]
Let's close, thanks @benbenben2
