### ISSUE TITLE
Let third-party scripts know if the user is a moderator

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#3341]
### What
- This feature is an opportunity to add a mass updating functions for moderators in Power User Script (or elsewhere). See https://github.com/openfoodfacts/power-user-script/issues/23.

### Proposed solution
I'm not sure about the best solution. It can be:

1. a special HTML class or id; e.g.: current code `<span id="user_id">charlesnepote</span>` could be enhanced to `<span id="user_id" class="moderator">charlesnepote</span>`
2. it can be an HTML class higher in the hierarchy, to let front end dev add special features; e.g.: `<body class="moderator-user">`; that way, for example, the page style could be modified to let the user knows he's using a moderator account
3. the session cookie could integrate a moderator=true information (a bit more secure?)

I think solution 2 might be the most interesting.

### Number of products impacted
The impact should be important, letting all moderators (more than 20-30 persons) to easily use Mass Update feature. For the moment, Mass Update feature in Power User Script is a bad hack only given to few people.

Note: as it's an important feature for third-party scripts, we should add unit tests to ensure it's working without regressions by the time.

### Part of
- #5538

**Comment by M123-dev** [comment]
> We now have an AUTH API

I was thinking about the same thing for producer accounts, I am not one but creating a user account I smoothie has no impact at all in the app, so maybe showing a moderator/producer tag or so

**Comment by teolemon** [comment]
@raphael0202 has the same issue: "Is there an endpoint to check a user session cookie and know whether it's a moderator/admin?".
