### ISSUE TITLE
Dropdown List for Country overlaps text

### ISSUE THREAD

**Issue by Jen-Lopez** [openfoodfacts/openfoodfacts-server#3354]
When you click on the country dropdown in the navigation bar, the dropdown overlaps the country text and makes it harder to click on the arrow button used to collapse the dropdown.  

<img width="300" alt="original" src="https://user-images.githubusercontent.com/21044058/80834462-c26a1280-8bbe-11ea-9b1a-54fbfa07328d.png">

**Comment by stephanegigandet** [comment]
Fixed by @Jen-Lopez and deployed. Thank you!
