### ISSUE TITLE
Return a 404 for tag pages that have 0 products

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#3361]
### What
- This is to prevent empty pages like https://world.openfoodfacts.org/ingredient/doesnotexist to be indexed in search engines.
- The 404 must be returned only if the mongodb query is successful but returns 0 result.

### Part of
- #7583

**Comment by hangy** [comment]
Yup, but this shouldn't return 404 if the tag is known in the taxonomy. Otherwise the tag would be linked from the parent taxonomy tag, and someone using the published taxonomy wouldn't expect a 404 error to be returned instead of an empty list.

**Comment by stephanegigandet** [comment]
@hangy : agree

> Yup, but this shouldn't return 404 if the tag is known in the taxonomy.

Good point, agreed.

**Comment by teolemon** [comment]
We have a nice 404 image: https://hunger.openfoodfacts.org/static/media/404.da694b05440877b1a5f4.png

**Comment by aakankshabhende** [comment]
Can I work on this issue @stephanegigandet ?

**Comment by stephanegigandet** [comment]
@aakankshabhende sure, thank you!

**Comment by teolemon** [comment]
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/1689815/195075507-17919b53-8a19-4948-91b7-1c7de881f0f2.png">

**Comment by dhruv1345** [comment]
In this issue, we need to show up the image for 404 error ?
If yes, then I would like to work on it.

**Comment by yuktea** [comment]
@dhruv1345: assigned

**Comment by MonalikaPatnaik** [comment]
Hey..if no one is working, I would like to work on this issue:) !

**Comment by yuktea** [comment]
@MonalikaPatnaik: the last time I checked @dhruv1345 was working on it a few days back. Feel free to pick any other issue :)

**Comment by raphael0202** [comment]
Ingredient facet pages are not longer indexed by search engine thanks to https://github.com/openfoodfacts/openfoodfacts-server/pull/8744.
