### ISSUE TITLE
Invalid Page 

### ISSUE THREAD

**Issue by alifafaruk** [openfoodfacts/openfoodfacts-server#3371]
Hi!
When users choose Bangladesh as their country, the discover page comes up as invalid. It may have something to do with the change in language. When I clicked on the discover button on the header, the page that popped up stated: "ত্রুটি অবৈধ ঠিকানা।" which means invalid.

<img width="1440" alt="Screen Shot 2020-05-04 at 5 20 06 PM" src="https://user-images.githubusercontent.com/47068889/81015329-7fad7200-8e2c-11ea-9081-dd3f3d474c38.png">

**Comment by teolemon** [comment]
https://crowdin.com/translate/openfoodfacts/440/en-bn#q=discover
I've fixed it. Should propagate soon. Meanwhile: 
https://bd.openfoodfacts.org/discover
