### ISSUE TITLE
Open Beauty Facts Link on site footer

### ISSUE THREAD

**Issue by Jen-Lopez** [openfoodfacts/openfoodfacts-server#3372]
### What
- Hi! I noticed that when you click on the "Open Beauty Facts - Cosmétiques" link in the [footer](https://world.openfoodfacts.org/), it's defaulted to the french version of the site which is https://world-fr.openbeautyfacts.org/. I think it would be better to have it defaulted to the english https://world.openbeautyfacts.org/ version. This way, users won't need to change the language back to english.

### Part of
- #5505

**Comment by teolemon** [comment]
I'm not quite sure why we did that 😊 
Maybe poor multilingual support, but that's not an excuse

**Comment by teolemon** [comment]
I'll fix that asap in openfoodfacts.pot

**Comment by knowyours** [comment]
Hello, can I work on this issue?

**Comment by jolesh** [comment]
Yes, I think so. Just go for it.

**Comment by n4i9kita** [comment]
Hi 
I see that the issue has not been resolved yet. 
Can I work on this issue  ?

**Comment by teolemon** [comment]
This has been fixed for a while. Closing.
