### ISSUE TITLE
Move taxonomies to submodule

### ISSUE THREAD

**Issue by hangy** [openfoodfacts/openfoodfacts-server#3373]
The taxonomies in the  `taxonomies` directory change quite often, without being re-compiled for deployment. I had suggested to automatically rebuild the taxonomies in this #2431, but have come to the conclusion that this would cause too many unnecessary changes to binary files in this already excessively large repository. Building the taxonomies on-the-fly when doing CI builds takes a lot of time and wastes quite some build resources.

As suggested in https://github.com/openfoodfacts/openfoodfacts-server/issues/1679#issuecomment-466766497, we could look into moving the taxonomies to their own submodules. Then, the unit tests and other CI checks for the server/web source could work with a fixed version of the taxonomy until the submodule gets updated to a new version, which will actually be deployed. There'll be some need to verify that PRs to the new taxonomy repos are valid and don't cause invalid syntax, but that could actually be done by using the [backend](https://github.com/openfoodfacts/openfoodfacts-server/packages/59115) container image and running the validation script from there.

**Comment by VaiTon** [comment]
So another repo?

**Comment by hangy** [comment]
@VaiTon yes, that's the main idea

**Comment by stephanegigandet** [comment]
Closing this bug as @john-gom has implemented a build cache repo to store built taxonomies:
https://github.com/openfoodfacts/openfoodfacts-server/pull/8027
