### ISSUE TITLE
(Typo) first betat testers in early 2012

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#340]
String typo
first betat testers in early 2012 >> first beta testers in early 2012
http://de.openfoodfacts.org/products

**Comment by teolemon** [comment]
http://de.openfoodfacts.org/products

**Comment by teolemon** [comment]
Can't find this in repo source. Uncommitted change ?

**Comment by hangy** [comment]
> Can't find this in repo source. Uncommitted change ?

Either that or non-updated HTML on the production server:

```
diff /home/off/lang/en/texts/products.html products.html
3c3
< <p>Open Food Facts publicly launched on May 19th 2012 (the site opened for the first betat testers in early 2012). The database contained then 648 products.</p>
---
> <p>Open Food Facts publicly launched on May 19th 2012 (the site opened for the first beta testers in early 2012). The database contained then 648 products.</p>
10c10
< <a href="http://world.openfoodfacts.org/status/to-be-completed">product pages to be completed</a> using the photos sent by other contributors.</p>
---
> <a href="https://world.openfoodfacts.org/status/to-be-completed">product pages to be completed</a> using the photos sent by other contributors.</p>

```

**Comment by RehabHussein** [comment]
@teolemon is this issue still there ?

**Comment by teolemon** [comment]
https://world.openfoodfacts.org/products

yes

**Comment by teolemon** [comment]
@stephanegigandet

**Comment by CharlesNepote** [comment]
Fixed on world. and de.

Is there more to be fixed?

**Comment by teolemon** [comment]
https://www.google.com/search?q=%22first+betat+testers+in+early+2012%22&oq=%22first+betat+testers+in+early+2012%22&aqs=chrome..69i57.1250j0j7&sourceid=chrome&ie=UTF-8

**Comment by teolemon** [comment]
fixed.closing
