### ISSUE TITLE
Very long categories are clipped on Robotoff questions

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#3401]
https://world.openfoodfacts.org/product/3560070906369/fromage-frais-aux-fruits-carrefour
![image](https://user-images.githubusercontent.com/1689815/81499879-d1437a00-92ce-11ea-9520-744ae9c12a8a.png)

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/81499941-1ff11400-92cf-11ea-8419-f6cc500e2924.png)

**Comment by GendelfLugansk** [comment]
Simple fix would be to add `left: 0` to robotoff-asker and result will look like this:

![screenshot](https://screenshots.gennady.pp.ua/20200510_52515bd90.png)

**Comment by GendelfLugansk** [comment]
Anyone knows how to reproduce this locally? I can't find a product that triggers Robotoff
