### ISSUE TITLE
Disable caching for state/to-be-completed.json

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#3407]
We use https://world.openfoodfacts.org/state/to-be-completed.json in the Android app to show a list of products recently edited that need to be completed.
As it is cached, it does not refresh real time. This has 2 consequences:
- People run out of products to complete and they have to wait for the cache to refresh
- People have a change to click on a product that has just been deleted, and be proposed to recreate it.

We'd need to disable caching for this page, possibly only when it's called using the API, to provide immediately a better Android experience.

**Comment by hangy** [comment]
I think there's a URL parameter `nocache=1` that should be used client-side.

**Comment by teolemon** [comment]
gee, thanks @hangy :-)

**Comment by VaiTon** [comment]
Not related to Product Opener
