### ISSUE TITLE
Can't log into Open Food Facts

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#342]
Chrome Canary, MacOs Sierra, Google DNS.

Open Food Facts won't let me login.

**Comment by stephanegigandet** [comment]
Happens when the client IP changes on every request (e.g. using Google's proxy).

Possible solution: use the leftmost value of the X-Forwarded-For header, which should contain the real client ip. (but can be spoofed by anyone)

**Comment by teolemon** [comment]
Let's close this one.
