### ISSUE TITLE
Mobile Layout for Product List (css fix)

### ISSUE THREAD

**Issue by Jen-Lopez** [openfoodfacts/openfoodfacts-server#3420]
### What
When viewing the site on mobile, there is some extra white space on the right hand-side. The pagination could also start on its own line. A few lines of CSS would fix this and make the mobile UI look great.
<img width="401" alt="product_before" src="https://user-images.githubusercontent.com/21044058/81865201-97c37680-953b-11ea-84dc-bae54a6cb53f.png">
<img width="405" alt="paging_before" src="https://user-images.githubusercontent.com/21044058/81865219-9bef9400-953b-11ea-8b17-af1023e0df14.png">

### Part of
- #5513

**Comment by teolemon** [comment]
The website has been redesigned. 
This might have fixed your issue and opened others.
 Please open new issues in #7295
