### ISSUE TITLE
Searching byStore is very slow.

### ISSUE THREAD

**Issue by VaiTon** [openfoodfacts/openfoodfacts-server#3458]
From https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/3160

> In fact searching by store is indeed very slow on the server. You can see that [here](https://world.openfoodfacts.dev/store/super-u.json).

On the android app this makes the client throw a `SocketTimeoutException` because response is not sent on time.

Edit: Apparently this only affects the dev server.

**Comment by syl10100** [comment]
Hi @VaiTon, do you have pb only on dev server ? Because on production server, it is very fast : https://world.openfoodfacts.org/store/super-u.json

**Comment by VaiTon** [comment]
Apparently yes, but we cannot use the prod server for testing on the android app.

**Comment by syl10100** [comment]
@VaiTon I think it is because you are logged in and products collection is used rather than products_tags collection in MongoDB. Can you try to log out and run the same query ?

**Comment by VaiTon** [comment]
Tried, TTFB is still 1 min.

**Comment by syl10100** [comment]
Ok index was missing.
`db.products.createIndex({"stores_tags": 1,"last_modified_t": -1}, { background: true })`
Now it should be better!

**Comment by VaiTon** [comment]
216 ms. Very good work @syl10100! 👍
