### ISSUE TITLE
Images disappear after changing the bar code

### ISSUE THREAD

**Issue by kyzh** [openfoodfacts/openfoodfacts-server#35]
Step to reproduce:
- add a product is with a bar code.
- add image added.
- change bar code
Images are now gone.

Here is an example: http://world.openfoodfacts.org/product/61941755/danette-chocolat-delice

**Comment by stephanegigandet** [comment]
I think this is now working, just tested and the images are following fine with the new barcode.
If this is still an issue, please reopen the bug. Thanks!
