### ISSUE TITLE
Compute similarity of a product's ingredient list with existing categories

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#350]
1. Perform ingredient extraction
2. Calculate distance with each category (taxonomized or not taxonomized)
3. Store top 3 results in a category candidates field.

**Comment by hangy** [comment]
http://indexoutofrange.com/How_I_calculate_similarities_in_cookit/

**Comment by hangy** [comment]
I incidentally stumbled upon this saga (via [Week in .NET](https://blogs.msdn.microsoft.com/dotnet/tag/week-in-net/)) on similarity comparison with ingredients: http://indexoutofrange.com/How_I_calculate_similarities_in_cookit/

**Comment by teolemon** [comment]
I believe we fixed this with Robotoff @raphael0202 :-)
