### ISSUE TITLE
Unify indication of non-taxonomized categories

### ISSUE THREAD

**Issue by aleksejrs** [openfoodfacts/openfoodfacts-server#353]
On product pages, names of the non-taxonomized categories are italicized.
At http://world.openfoodfacts.org/categories, they just have "-" instead of spaces.

**Comment by aleksejrs** [comment]
Does the asterisk mean the same?  It's not much clearer!

**Comment by hangy** [comment]
Added the italics and removed the asterisk to normal tag lists. This will be visible in the next release of product-opener.

**Comment by aleksejrs** [comment]
The asterisk is actually useful: you can sort the column to group the taxonomized and non-taxonomized categories.  Now http://world.openfoodfacts.org/categories has an empty third column that cannot be sorted.
