### ISSUE TITLE
energy-kcal_100g should be in kcal instead of kJ

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#3561]
On October 2019, we separated the energy field to 2 fields energy-kj and energy-kcal

#2396 describes the rationale and the expected result:

energy_kcal_value: 450,
energy_kcal_unit: "kcal",
energy_kcal_100g: 450,
energy_kcal: 450,

energy_kj_value: 1850,
energy_kj_unit: "kJ",
energy_kj_100g: 1850,
energy_kj: 1850,

energy_value: 1850,
energy_unit: "kJ", --> indicates the source of the energy field (energy_kj if we have it, or converted from energy_kcal if we don't have it, or for US products)
energy_100g: 1850,
energy: 1850,

It turns out that I implemented something different, with the energy-kcal_100g field set in kJ.

I described the current behaviour here: https://wiki.openfoodfacts.org/Nutrients_handling_in_Open_Food_Facts

I'm proposing that we consider the current behaviour a bug: it's not what I originally specified in bug #2936, it's not what people using the API expect, and it forces us to make conversion from and to kcal/kj that could and should be avoided.

So I will just change the energy-kcal_100g/serving fields to kcal in MongoDB, the API and the code that reads it / sets it.

**Comment by VaiTon** [comment]
Reminder: in the android app we are converting from kj the field energy-kcal.

**Comment by stephanegigandet** [comment]
This has been deployed and all products have been updated.
