### ISSUE TITLE
Search field editors does not work

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#3579]
Specifying an editor in the search form does not return any result.

This is because editors is not marked as a tag field, so the query is not made on editors_tags

**Comment by teolemon** [comment]
This old bug is strongly related: https://github.com/openfoodfacts/openfoodfacts-server/issues/25
This one is also interesting: https://github.com/openfoodfacts/openfoodfacts-server/issues/18
