### ISSUE TITLE
Impossible to click on the details of nutriscore or ingredients on Safari for iPhone

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#3587]
**Describe the bug**
Impossible to click on the details of nutriscore or ingredients on mobile, on Safari, iOS10.
Won't display anything. Iphone 5S

**Comment by stephanegigandet** [comment]
It's working well on Android with Firefox and Chrome.

Any error on the console on Safari for iOS? What about Safari for Mac, does it work for it?

**Comment by aleene** [comment]
I can click on the nutriscore and get the explanation page (safari on ios)

**Comment by aleene** [comment]
I think 5S is getting to old.

**Comment by teolemon** [comment]
I still can reproduce the issue. And I saw a lady happily using her 5S yesterday in the Paris metro

**Comment by aleene** [comment]
Did she have the issue as well?

My wife has an older IOS and has often issues with Safari.
