### ISSUE TITLE
It's easy to forget to click on the "Start upload" button in the Producer Platform

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#3594]
When you upload a large amount of images (and possibly in other cases), the platform does slowly its thing, and you kind of expect it to be done once the initial local loading is done. As a result, it's then easy to forget to click on the "Start upload" button in the Producer Platform to do the actual upload. It took me a couple of minutes to remember this behaviour, that I hadn't clicked on "Start upload" already, because the previous phase felt like an upload.
![image](https://user-images.githubusercontent.com/1689815/84363412-fe858f80-abce-11ea-9ab0-0b9c9efdd872.png)
A JS insert "Do not forget to click on start upload" could be useful until we have a better upload flow

**Comment by stephanegigandet** [comment]
The start button has been removed, upload now starts automatically.
