### ISSUE TITLE
Allow better control over additive color coding

### ISSUE THREAD

**Issue by kyzh** [openfoodfacts/openfoodfacts-server#36]
Depending on the version of the website, some color coding can be encountered.
The goal of this feature request is to allow better transparency on the source for the color coding and better control over what source a user want to choose.

Color coding is there as a visual clue on possible adverse effect an additive is regarded to have.
Some additives are even banned in some countries, either by food regulators or by religious authorities.
Other studies might cast a doubt on wether an additive should be regarded as 'bad' or not.

The best way to deal with such cases would be to have a preset per country.
That would serve as a base for user not logged.
User would then be able to add their own color scheme.

**Comment by stephanegigandet** [comment]
Current system (in French) only: http://fr.wiki.openfoodfacts.org/Projet:Fiches_sur_les_additifs

**Comment by sl956** [comment]
Example of the flaws and risks of the current system:

**Comment by stephanegigandet** [comment]
A first thing to do could be to list all official and non-official (e.g. from NGOs, companies etc.) sources of information on additives. Binary lists like "allowed / disallowed" in the EU, and lists with risk levels.

Then we can discuss what information to show on additive pages, and which one to use for classifying additive risks.

**Comment by sl956** [comment]
Binary lists like "allowed / disallowed in the EU" is an oversimplification: most additives are allowed  *in certain proportions* **for some kind of use**. 
For instance the maximal concentration allowed in the EU for E102 in Edible Cheese Rinds is 100 mg/kg, and it is the same for E120... except for Red Marbled Cheese and Red Pesto Cheese where it can be up to 125 mg/kg for E120. (No, I don't make that up: http://eur-lex.europa.eu/legal-content/EN/TXT/?uri=uriserv:OJ.L_.2014.299.01.0022.01.ENG )

**Comment by stephanegigandet** [comment]
Started a wiki page to gather the data and host the discussions: http://en.wiki.openfoodfacts.org/Project:Food_additives

@sl956: I added your link for Tartrazine on the wiki page, can you add your ideas / data / links etc. to it as well? Thank you!

**Comment by stephanegigandet** [comment]
Additives colors have been removed.
