### ISSUE TITLE
Nutrient names are missing in Russian "Nutrient levels for 100 g" output.

### ISSUE THREAD

**Issue by aleksejrs** [openfoodfacts/openfoodfacts-server#360]
http://world.openfoodfacts.org/product/5060058339359/danio-cherry-danone says “0.2 g Fat in low quantity”
http://fr.openfoodfacts.org/produit/5060058339359/danio-cherry-danone says “0.2 g Matières grasses / Lipides en faible quantité”
http://ru.openfoodfacts.org/product/5060058339359/danio-cherry-danone says “0.2 g в low quantity”.

**Comment by aleene** [comment]
Is now translated.
