### ISSUE TITLE
Accent handling in ingredients

### ISSUE THREAD

**Issue by AcuarioCat** [openfoodfacts/openfoodfacts-server#3615]
I'm coming across cases where accented characters aren't being correctly handled.
For example (Spanish):
The ingredients list includes arándanos
In the ingredients taxonomy arándanos (with accent exists) but arándanos doesn't get processed
arandanos (without accent) does get processed.

It appears ingredients in the ingredients.txt shouldn't have accents but there are hundreds of entries with accent (in all languages).

**Comment by hangy** [comment]
How significant are accents in Spanish? Right now, OFF is configured to unaccent the files: https://github.com/openfoodfacts/openfoodfacts-server/blob/ec3b8f37144b5e3c1ebd506ca998bcd74e324a64/lib/ProductOpener/Config_off.pm#L126-L129 There was some discussion around that topic in #458 and related issues/PRs.

**Comment by AcuarioCat** [comment]
In the written language not too significant but in the case of the ingredients it means the difference between translating or not. An accented character doesn't change the meaning of a word if that is what you mean.

**Comment by aleene** [comment]
In the taxonomy I prefer to have the accented versions, as this allows us to use the taxonomy for translations a well.

**Comment by AcuarioCat** [comment]
@aleene Yes, I agree

**Comment by AcuarioCat** [comment]
..however, I think the processing should allow for characters being either as there are lots of occurrences of falsely accented characters (due to OCR) in the ingredients lists so having a hard rule would throw up massive amounts of unknowns.

**Comment by aleene** [comment]
Yes, but that should be solved in the OCR, not in the taxonomy. But it might be helpful to add the unaccented ingredients to the taxonomy as synonyms, but it should not be necessary.

Where are the deaccenting rules defined? Are they language dependent. A simple `´` should have been deaccenting, it is done fro french all the time. There are more difficult languages in this sense.

**Comment by stephanegigandet** [comment]
It's a bug in the unaccenting, we unaccent arándanos but we don't unaccent arándanos:

https://es.openfoodfacts.org/cgi/test_ingredients_analysis.pl?ingredients_text=ar%C3%A1ndanos%2C+ara%CC%81ndanos&type=add&action=process&.submit=Valider

The difference is not visible, but in the second case, it's 2 Unicode characters instead of one:

U+0061 : LATIN SMALL LETTER A
U+0301 : COMBINING ACUTE ACCENT {stress mark; Greek oxia, tonos}

It currently does not work with our unaccenting:

		$string =~ tr/àáâãäåçèéêëìíîïñòóôõöùúûüýÿ/aaaaaaceeeeiiiinooooouuuuyy/;

**Comment by Ban3** [comment]
> The difference is not visible, but in the second case, it's 2 Unicode characters instead of one:

`Unicode::Normalize` would be a solution here.

**Comment by stephanegigandet** [comment]
> `Unicode::Normalize` would be a solution here.

@Ban3 : good point, thanks :)

I had a less elegant (but maybe faster) solution:

		# Remove diacritics marks -> use Unicode::Normalize instead
		#$string =~ s/\N{COMBINING ACUTE ACCENT}|\N{COMBINING GRAVE ACCENT}|\N{COMBINING CIRCUMFLEX ACCENT}|\N{COMBINING TILDE}|\N{COMBINING DIAERESIS}//g;

I'll try with Unicode::Normalize, it would probably be a good thing to apply it for all strings.

**Comment by AcuarioCat** [comment]
This appears to be almost working but 'é' isn't being handled.
In Catalan Goma de xanté is not handled whereas (from additives.txt) Goma de xantè is being handled.

**Comment by stephanegigandet** [comment]
That's because we didn't configure Catalan so that accents do not matter. I'll change it: https://es-ca.openfoodfacts.dev/cgi/test_ingredients_analysis.pl?ingredients_text=Goma+de+xant%C3%A9%2C+Goma+de+xant%C3%A8+%2C+%C3%80cid+asc%C3%B2rbic&type=add&action=process&.submit=Valider
