### ISSUE TITLE
Handle ingredients words split onto two lines

### ISSUE THREAD

**Issue by AcuarioCat** [openfoodfacts/openfoodfacts-server#3616]
See for example 8410297161407

The OCR correctly reads the ingredients list but as (in this case) a couple of words are split onto two lines with a hyphen the following results:

agua, habas de soja descascarilladas (4%), malto - dextrina (fibra), fructosa, azücar, car - bonato célcico, corrector de acidez (fosfato monopotésico), sal marina, aroma, estabilizante (goma gellan), vitaminas (riboflavina (B2), B12, D), aroma natural. Naturalmente sin lactosa y sin gluten.

which should be:

agua, habas de soja descascarilladas (4%), maltodextrina (fibra), fructosa, azücar, carbonato célcico, corrector de acidez (fosfato monopotésico), sal marina, aroma, estabilizante (goma gellan), vitaminas (riboflavina (B2), B12, D), aroma natural

**Comment by aleene** [comment]
We have this issue in german as well.

**Comment by stephanegigandet** [comment]
Same as #3007 , closing this one.
