### ISSUE TITLE
Add handling for INS food additives with syntax INS N°420

### ISSUE THREAD

**Issue by AcuarioCat** [openfoodfacts/openfoodfacts-server#3618]
https://en.wikipedia.org/wiki/International_Numbering_System_for_Food_Additives

There are many food items from outside of Europe that use the INS system. For example barcode 7840085000372

Currently there is no handling for the INS numbers.

**Comment by teolemon** [comment]
https://world.openfoodfacts.org/product/7840085000372/hecodulc-stevia

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/84567577-ebfb8980-ad79-11ea-8908-59105d4ea4b9.png)

**Comment by stephanegigandet** [comment]
INS is the same than the E numbers in Europe in fact, we do handle the syntax INS 420, but not INS N°420, I'll add it.

https://es.openfoodfacts.org/cgi/test_ingredients_analysis.pl?ingredients_text=INS+420%2C+INS+N%C2%B0+120&type=add&action=process&.submit=Valider
