### ISSUE TITLE
Show in which language the ingredient list is when it is not in the language of the interface

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#3620]
**Describe the bug**
On the main product page the ingredients are noted as english, but they are danish.

**To Reproduce**
1. Go to https://world.openfoodfacts.org/product/42115670/fanta-free-orange
2. Try to edit
**Expected behavior**

**Screenshots**
![Screenshot 2020-06-13 at 13 50 53](https://user-images.githubusercontent.com/1329905/84568056-26b2f100-ad7d-11ea-9912-c986a8ed7c87.png)

**Comment by stephanegigandet** [comment]
We should indicate it is the Danish list indeed (and remove the "Edit ingredients" buttons for admins)
