### ISSUE TITLE
Unknown Spanish ingredients that should be known

### ISSUE THREAD

**Issue by AcuarioCat** [openfoodfacts/openfoodfacts-server#3625]
### What

- I'm coming across several ingredients that should be recognized as their 'words' are in both ingredients and in ingredients_processing.
- These are the ones I've found to date - I imagine there is a common root for this so it should provide the information necessary to fix the problem.

```
leche desnatada de vaca
aroma natural de naranja
jugo concentrado de piña
jugo de pasas
```

### Part of
- #5706

**Comment by aleene** [comment]
What is the issue with `jugo de pasas`?

**Comment by AcuarioCat** [comment]
It doesn't get processed:
https://es.openfoodfacts.org/cgi/test_ingredients_analysis.pl?ingredients_text=jugo+de+pasas&type=add&action=process&.submit=Submit+Query

Returns es:jugo-de-pasas
Should return en:rasin-juice

**Comment by aleene** [comment]
Ah yes, it was not yet added to [the latest update].(https://github.com/openfoodfacts/openfoodfacts-server/pull/3619)

By the way what is the difference between `zumo` and `jugo`, And should I separate them?

**Comment by aleene** [comment]
For the others, the question is what we do with processing adjectives hidden (in bwteen other words) in the ingredient. @stephanegigandet ?

**Comment by AcuarioCat** [comment]
> Ah yes, it was not yet added to the latest update.(#3619)
> By the way what is the difference between zumo and jugo, And should I separate them?

The difference is very subtle and partly one of regions. For example in South America everything is 'Jugo de' whereas in Spain it tends to be Zumo when referring to fruit/vegetable and jugo when referring to juices of (for example) meat.

My wife (Spanish) says jugo refers more to something that comes out of something when cooked (jugo de carne) and zumo when it is squeezed/pressed (zoom de naranja).

I think that they are so similar and interchangeable that you don't need to worry and that you will come across both, however both need to be recognised.

**Comment by aleene** [comment]
The region thing makes it more difficult. I know other languages that differentiate between spanish jugo/zumo as well. Sounds like `zumo` is the more specific one, we can that make a child of `jugo`.

**Comment by AcuarioCat** [comment]
At the moment I have them listed as synonyms at the top of ingredients.txt

**Comment by AcuarioCat** [comment]
Here is an additional entry from 8480017680389
extracto vegetal colorante

**Comment by AcuarioCat** [comment]
It's improving a lot but still not quite there.
The following aren't getting processed:

aroma natural de naranja
caldo deshidratado de vegetales

**Comment by aleene** [comment]
Is not working in french either.

**Comment by stephanegigandet** [comment]
The only case that is not working yet is "caldo deshidratado de vegetales".

Maybe we could relax the ingredient processing so that it can match inside the ingredient string (and not only at the beginning and end).

https://es.openfoodfacts.org/cgi/test_ingredients_analysis.pl?ingredients_text=leche+desnatada+de+vaca%2C%0D%0Aaroma+natural+de+naranja%2C%0D%0Ajugo+concentrado+de+pi%C3%B1a%2C%0D%0Ajugo+de+pasas%2C%0D%0Acaldo+deshidratado+de+vegetales%2C%0D%0Apur%C3%A9+de+hortalizas%2C&type=add&action=process&submit=Envoyer
