### ISSUE TITLE
"cal." or "cal" (for "calibre") adds E529

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#3626]
"cal." or "cal" (for "calibre") adds E529
```Orange Valencia Late (cal. 6/7), traité avec Imazalil. E904, E914.```
https://fr.openfoodfacts.org/produit/8437016428276/oranges-a-jus-la-grappe

**Comment by stephanegigandet** [comment]
Good catch. We currently trying matching additives a bit too aggressively (Spanish "cal" == French "chaux"). I'll fix it.
