### ISSUE TITLE
Add handling for "amount of product for each Xg/mL of product"

### ISSUE THREAD

**Issue by AcuarioCat** [openfoodfacts/openfoodfacts-server#3642]
### What
- Commonly found in sauces and purees but also in meat products, an example:
  - Tomate* (160g de tomate por cada 100g de producto final), code 8425205013532
- This structure is currently unhandled and results in unknown.

Another example:
Elabora con 59 g de fruta por 100 g
Code 8410095507001

### Part of
- #5706

**Comment by aleene** [comment]
This is probably an issue in any language.

**Comment by Ban3** [comment]
> Elabora con 59 g de fruta por 100 g

I believe the French equivalents are ignored by the parser:

https://github.com/openfoodfacts/openfoodfacts-server/blob/master/lib/ProductOpener/Ingredients.pm#L1190-L1203

**Comment by aleene** [comment]
Dutch: `Bereid met 45 g vruchten per 100 g`

**Comment by aleene** [comment]
Préparée avec 61 g de fruits pour 100g 

Teneur totale en sucres: 61 g pour 100 g.

**Comment by AcuarioCat** [comment]
English: 148g per 100g

**Comment by Ban3** [comment]
Danish: `Fremstillet af x g frugt per 100g`
Swedish: `Fruktråvara x g per 100g`

**Comment by benbenben2** [comment]
HR
Proizvedeno od 80g voća na 100g gotovog proizvoda
https://hr.openfoodfacts.org/product/3859888295261/smokva-doma%C4%87a-d%C5%BEem-marina



What could we do with that:
- Ignore/remove that kind of text?
- Could it be used for something?   

@teolemon, @stephanegigandet

**Comment by stephanegigandet** [comment]
@benbenben2 in fact we now have a feature to parse those mentions from ingredients lists, in Ingredients.pm

=head2 parse_specific_ingredients_from_text ( product_ref, $text, $percent_or_quantity_regexp )

Lists of ingredients sometime include extra mentions for specific ingredients
at the end of the ingredients list. e.g. "Prepared with 50g of fruits for 100g of finished product".

This function extracts those mentions and adds them to the specific_ingredients structure.

This function is also used to parse the origins of ingredients field.

---

We could try to support all the languages / phrases that have been collected in this issue.

**Comment by benbenben2** [comment]
@stephanegigandet should we close this issue?

**Comment by stephanegigandet** [comment]
> @stephanegigandet should we close this issue?

Sure, thank you very much for all your work on this @benbenben2 !
