### ISSUE TITLE
Broken categories

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#3648]
taxonomy : did not find parentid foie-gras-from-ducks, trying stopped_parentid foie-gra-from-duck - result canon_parentid: foies-gras-from-ducks
taxonomy : did not find parentid foie-gras-from-ducks, trying stopped_parentid foie-gra-from-duck - result canon_parentid: foies-gras-from-ducks
taxonomy : did not find parentid foie-gras-from-ducks, trying stopped_parentid foie-gra-from-duck - result canon_parentid: foies-gras-from-ducks
taxonomy : did not find parentid foie-gras-from-ducks, trying stopped_parentid foie-gra-from-duck - result canon_parentid: foies-gras-from-ducks
taxonomy : did not find parentid foie-gras-from-ducks, trying stopped_parentid foie-gra-from-duck - result canon_parentid: foies-gras-from-ducks
taxonomy : did not find parentid foie-gras-from-ducks, trying stopped_parentid foie-gra-from-duck - result canon_parentid: foies-gras-from-ducks
taxonomy : did not find parentid raviolis, trying stopped_parentid ravioli - result canon_parentid: ravioli
taxonomy : did not find parentid tortellinis, trying stopped_parentid tortellini - result canon_parentid: tortellini
taxonomy : did not find parentid tortellinis, trying stopped_parentid tortellini - result canon_parentid: tortellini
Errors in the categories taxonomy definition:
ERROR - en:cooked-rabbit-meat is a parent of itself
ERROR - en:cooked-kidneys is a parent of itself
ERROR - en:salad-without-dressing has an undefined parent

**Comment by AcuarioCat** [comment]
My PR #3647 should fix the errors, just waiting on approval.
