### ISSUE TITLE
Mapquest API Shutdown has disabled maps across OFF And OBF

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#365]
http://de.openfoodfacts.org/cgi/search.pl?action=process&sort_by=unique_scans_n&page_size=20&axis_x=energy&axis_y=products_n&map_title=Test&generate_map=1

**Comment by teolemon** [comment]
fixed by @stephanegigandet

**Comment by TaciteOFF** [comment]
Maps don't work anymore. 

Example : https://fr.openfoodfacts.org/cgi/search.pl?action=process&tagtype_0=stores&tag_contains_0=contains&tag_0=Bio14&sort_by=unique_scans_n&page_size=20&axis_x=energy&axis_y=products_n&generate_map=1

If that may help:

<img width="1280" alt="capture d ecran 2017-02-01 a 10 34 29" src="https://cloud.githubusercontent.com/assets/11161632/22501654/0733f8dc-e86a-11e6-8d7d-49f4e66d6899.png">
