### ISSUE TITLE
Allow the user to specify whether the nutrition is presented in ml or g

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#367]
Allow the user to specify whether the nutrition is presented in ml or g.

For some products (icecreams), the data can be specified in grams or milliliters. From the context it is not always clear which one is used.
Example in ml: http://fr.openfoodfacts.org/produit/7613031030187/cup-s-smarties
Example in g: http://fr.openfoodfacts.org/produit/8711200564149/cookie-dough-ice-cream-ben-jerry-s

**Comment by aleksejrs** [comment]
One carbonated water bottle says "CO2 — 0,2-0,8 %".

**Comment by aleene** [comment]
too old
