### ISSUE TITLE
Problems parsing additives in Spanish

### ISSUE THREAD

**Issue by AcuarioCat** [openfoodfacts/openfoodfacts-server#3694]
The following fails to parse:
endulcorantes (acesulfamo K y neohespiridina DC)

Interestingly, changing the 'y' for a ',' and the first additive parses but the second doesn't.
Both are recognized if parsed individually.

[https://es.openfoodfacts.org/cgi/product.pl?type=edit&code=8480017102904](url)

**Comment by AcuarioCat** [comment]
Here is another one:
colorante (caramelo e150c)

**Comment by AcuarioCat** [comment]
Investigating this more, it seems the problem is when the additive + E-number are not separated by a punctuation mark.
It also seems to affect all languages

[https://world.openfoodfacts.org/cgi/test_ingredients_analysis.pl?ingredients_text=potassium+lactate+E326&type=add&action=process&.submit=Submit](url)

[https://world.openfoodfacts.org/cgi/test_ingredients_analysis.pl?ingredients_text=potassium+lactate%3A+E326&type=add&action=process&.submit=Submit](url)

**Comment by stephanegigandet** [comment]
"neohespiridina DC" is not in the additives or ingredients taxonomy

I can try to make the other ones work.

**Comment by AcuarioCat** [comment]
I'm not worried about 'neohespiridina DC' - but it should have identified acesulfamo K as a known additive. I'll add 'neohespiridina DC' later.

**Comment by stephanegigandet** [comment]
We separate "A y B" only when we know both A and B. It's by design, to avoid false positives.
