### ISSUE TITLE
Ingredient/process sometimes not parsing

### ISSUE THREAD

**Issue by AcuarioCat** [openfoodfacts/openfoodfacts-server#3697]
I'm finding cases of ingredients with a process that aren't being parsed. It seems inconsistent.
For example:
chips de coco tostadas - does not get parsed
copos de trigo tostadas - parsed correctly

Both have entries in ingredients.txt

**Comment by stephanegigandet** [comment]
Both now work:
https://es.openfoodfacts.org/cgi/test_ingredients_analysis.pl?ingredients_text=chips+de+coco+tostadas%2C+copos+de+trigo+tostadas&type=add&action=process&.submit=Valider

Do you have other examples, or can we close this issue?

**Comment by AcuarioCat** [comment]
Excellent. At the moment of this particular problem, no. I'll close it..
