### ISSUE TITLE
When entering the '<' in the salt or sodium field, the other one get filed with NaN

### ISSUE THREAD

**Issue by kyzh** [openfoodfacts/openfoodfacts-server#37]
The javascript doesn't like when people use a greater than or lesser than sign '>' '<' in the sodium or salt field.

A solution would be to strip the sign before doing the computing and prepending it to the results

**Comment by kyzh** [comment]
Also true for the word "trace"

**Comment by hangy** [comment]
Added a workaround in commit 3116a74.

**Comment by teolemon** [comment]
@hangy so fixed ?
