### ISSUE TITLE
"nterdit" --> "interdit"

### ISSUE THREAD

**Issue by alexouille123** [openfoodfacts/openfoodfacts-server#3705]
https://github.com/openfoodfacts/openfoodfacts-server/blob/e8c6c1d123bea14e474541d2927014f29e658578/ingredients/additifs/Liste_des_additifs_alimentaires.20120326#L336

**Comment by alexouille123** [comment]
I do this issue because I don't know how to use Github :) and therefore modify a code! @teolemon @stephanegigandet

**Comment by alexouille123** [comment]
#3707

**Comment by VaiTon** [comment]
Thank you for the report and for the PR! 🎉 

Unfortunately the PR file that you modified is wrong but no worries, I'll commit in another PR and tag you. 😄
