### ISSUE TITLE
First characters of ingredient sometimes cut after percentage

### ISSUE THREAD

**Issue by Ban3** [openfoodfacts/openfoodfacts-server#3706]
**To Reproduce**
[test_ingredients_analysis.pl: 23% purée de tomate](https://fr.openfoodfacts.org/cgi/test_ingredients_analysis.pl?ingredients_text=23%25+pur%C3%A9e+de+tomate&type=add&action=process)

[Product 4001724820000](https://world-fr.openfoodfacts.org/product/4001724820000/pizza-pollo-dr-oetker)

**Comment by stephanegigandet** [comment]
Good catch. I think the bug happens because "pur" meaning "pure" is treated specially.
