### ISSUE TITLE
Support "no more than" / "no less than" for nutrient quantities

### ISSUE THREAD

**Issue by aleksejrs** [openfoodfacts/openfoodfacts-server#373]
It seems that "`<`" is supported, but "`<=`" is not (results in "`< 0`").

**Comment by hangy** [comment]
Thanks for the suggestion, this is now supported.

**Comment by aleksejrs** [comment]
Thanks.

**Comment by aleksejrs** [comment]
One label says "`(no more than)`" in the column which contains ranges (`no more than 5-50`)…  Are ranges supported at all?  With "no more than", it turns into "`≤ 5`", but I guess it should be "`≤ 50`".

**Comment by hangy** [comment]
No, the code doesn't really do ranges (as far as I can see).
