### ISSUE TITLE
File not found on the producer platform if a special character is present in filename

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#3736]
When uploading a product catalog, the platform will show "file not found" on the producer platform if a special character is present in filename.

Example:
INFORMACIO╠üN NUTRICIONAL PRODUCTOS EL DULZE.xlsx

Removing the character fixes the issue.

**Comment by teolemon** [comment]
That's the bug also reported by Carrefour

**Comment by VaiTon** [comment]
Why should we store files with non-ascii characters?

**Comment by stephanegigandet** [comment]
> Why should we store files with non-ascii characters?

We should not.
