### ISSUE TITLE
Small issues in nutrition facts table template

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#3742]
2 small issues on the nutrition facts table displayed on categories pages: (e.g. /category/cheeses )

We should not show "% of difference  value for 100 g / 100 ml
→ Please note: for each nutriment, the average is computed for products for which the nutriment quantity is known, not on all products of the category."

And there's an issue with the label which makes the font a different size.

![image](https://user-images.githubusercontent.com/8158668/85749526-37fae680-b709-11ea-98da-8cb4ec190af4.png)

**Comment by VaiTon** [comment]
> → Please note: for each nutriment, the average is computed for products for which the nutriment quantity is known, not on all products of the category."

Why don't we leave this?
