### ISSUE TITLE
Most E- Numbers are now unrecognised

### ISSUE THREAD

**Issue by AcuarioCat** [openfoodfacts/openfoodfacts-server#3744]
Something has broken..
Most (but not all) E- numbers are now showing as unknown.

I'm guessing this is a result of the anomoly in Spanish of words being joined by 'y' or 'e'.

If it helps, the joining 'e' will NEVER be followed by a number, also the rule is that 'y' is replaced by 'i' ONLY if the next word starts with an 'i', for example 'queso y yema de huevo' but 'queso e incrementador de volumen'

In ingredients analysis they also show as unknown.

[https://es.openfoodfacts.org/cgi/test_ingredients_analysis.pl?ingredients_text=Agua%2C+Jugo+org%C3%A1nico+de+Aloe+Vera+%2821%25%29%2C+Fructosa%2C+Gel+de+Aloe+Vera+%289%25%29%2C+Correctores+de+acidez+%28E-330%3B+E-331%29%2C+Estabilizantes+%28E-327%3B+E-418%29%2C+Saborizante+natural+de+uva%2C+Az%C3%BAcar&type=add&action=process&.submit=Submit](url)

[https://es.openfoodfacts.org/ingredients?status=unknown&limit=100](url)

**Comment by stephanegigandet** [comment]
Working on it.
