### ISSUE TITLE
Errors in the packaging taxonomy

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#3748]
building taxonomy for packagings - publish: publish
Errors in the packagings taxonomy definition:
ERROR - en:70-gls already is a synonym of en:mixed-glass-container-multi-part-container for entry en:mixed-glass-container-multi-part-container - en:vegyes-uveg cannot be mapped to entry en:mixed-glass-container-multi-part-container
ERROR - en:73-gls already is a synonym of en:dark-sort-glass for entry en:dark-sort-glass - en:sotet-valogatott-uveg cannot be mapped to entry en:dark-sort-glass
ERROR - en:74-gls already is a synonym of en:light-sort-glass for entry en:light-sort-glass - en:vilagos-valogatott-uveg cannot be mapped to entry en:light-sort-glass
Errors in the packagings taxonomy definition at ProductOpener/Tags.pm line 983.

**Comment by svensven** [comment]
was fixed by https://github.com/openfoodfacts/openfoodfacts-server/pull/3935
