### ISSUE TITLE
Split the login_register_comment into translatable chunks

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#375]
login_register_content

**Comment by hangy** [comment]
The string exists in`lib/ProductOpener/Lang.pm` but is never used anywhere (according to `grep`). Maybe we should just remove it?

https://github.com/openfoodfacts/openfoodfacts-server/blob/228a17050abe3b54f01854dc82d47349a875aa7d/cgi/product_multilingual.pl#L189-L224 is one of the places where it may have been used, but it looks different now.

**Comment by teolemon** [comment]
Monolithic strings are a nightmare for translators. A comma changes, and 150 people have work to do ;-)
Also, any plan for sync with the GetText branch ?

**Comment by hangy** [comment]
Translation doesn't exist in https://github.com/openfoodfacts/openfoodfacts-server/blob/ed8d24013e63e457dcc76dc792c33e5807a96dd3/po/openfoodfacts/openfoodfacts.pot or in https://github.com/openfoodfacts/openfoodfacts-server/blob/f766b5b16b8e5e1ffd35a5c265caf5bdef4a1401/po/common/common.pot (any more?)
