### ISSUE TITLE
Problems with accents in Spanish

### ISSUE THREAD

**Issue by AcuarioCat** [openfoodfacts/openfoodfacts-server#3753]
The following is in ingredients:
es:Fruta, frutas

The following is in ingredients_processing:
es:pure,puré,pure de

'puré de frutas' does not parse 
'pure de frutas' parses ok

'puré frutas' does not parse
'pure frutas' parses ok

**Comment by svensven** [comment]
For some reason, in ingredients_processing.txt if the unaccented version is first, or the only version, it won't match accented terms.
But if the accented version is first, or the only version, that will match both accented and unaccented terms.

So, ```es:puré, pure, puré de, pure de, ...``` or ```es:puré, puré de, ...``` both match all 4 ingredients, 
but ```es:pure, pure de, ...``` doesn't match the accented ingredients.

**Comment by stephanegigandet** [comment]
> For some reason, in ingredients_processing.txt if the unaccented version is first, or the only version, it won't match accented terms.

That sounded very strange, but I check, and indeed, that is the case. What happens is that unaccented synonyms are added automatically, and when an accented synonym is after the un-accented version, it's not added at all.

**Comment by VaiTon** [comment]
Superseeded by #4810.
