### ISSUE TITLE
Aroma in Portuguese is not being recognized

### ISSUE THREAD

**Issue by AcuarioCat** [openfoodfacts/openfoodfacts-server#3754]
https://pt.openfoodfacts.org/cgi/test_ingredients_analysis.pl?ingredients_text=leite+desnatado+pasteurizado%2C+ananas+%289%2C8%25%29%2C+proteinas+do+leite%2C+leite+desnatado+em+po%2C+fibras+alimentares+%28oligofrutose%29%2C+amido+modificado+de+milho%2C+reguladores+de+acidez+%28E330%2C+E331%2C+E341%29%2C+espessantes+%28E412%2C+E440%29%2C+edulcorante+%28E951%29%2C+aroma%2C+conservante+%28E202%29%2C+fermento+lacteos&type=add&action=process&.submit=Submit

pt:aromatizante,aroma,aromas

'aroma' exists in ingredients.txt but is not being recognized when processed. I can't see any reason..
Changing to 'aromatizante' or 'aromas' and it is recognised.

**Comment by svensven** [comment]
This seems to be working now?

**Comment by teolemon** [comment]
going to close
