### ISSUE TITLE
Correcly handle min. in ingredients lists

### ISSUE THREAD

**Issue by AcuarioCat** [openfoodfacts/openfoodfacts-server#3762]
min. is not handled and results in unknown ingredients:

Leche pasteurizada de (vaca (mín. 50%), oveja (mín. 20%) y cabra (mín. 15%), sal, cuajo y fermentos lácticos.

**Comment by teolemon** [comment]
Related: https://world.openfoodfacts.org/product/3483461210183/galette-pois-chiches-et-cumin-tossolia
"pois chiche cuits 39%, oignons, flocons d'avoine sans gluten, carottes, huile d'olive, arrow root, sel, cumin 0,4%"
cumin 0,4% is parsed as cu -> fr:cu - percent_min: 0.4 - percent: 0.4 - percent_max: 0.4
