### ISSUE TITLE
Show packager code maps as a modal directly on the product page

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#3764]
Show packager code maps as a modal on the product page. 

There can be several packager codes, and thus several maps
- [ ] Option 1: Show them all expanded, side by side
- [ ] Option 2: show the first one, and put the subsequent ones in a modal, very much like ingredients
- [ ] Option 3: Put them all in a collapsible section

 If we load them by default, this asks the question of the tile server load

### Part of 
- #5501

**Comment by hangy** [comment]
I'd like a mock of the desktop+mobile view of this. How important should the map be in comparison to the product image? Also, why should it be a modal window?

**Comment by teolemon** [comment]
fixed
