### ISSUE TITLE
Additives parsing in Portuguese is very strange!

### ISSUE THREAD

**Issue by AcuarioCat** [openfoodfacts/openfoodfacts-server#3771]
Additive processing is adding extra E's to the additives. It seems to be due to the space between the E and the number.

Example ingredients:
Farinha de trigo, açúcar, água, levedura, xarope de glucose-frutose, óleo vegetal (girassol), ovo líquido pasteurizado, cacau magro em pó (2,9%), maltodextrina, gordura vegetal (palma), estabilizadores (E 422, E 412), emulsionantes (lecitina de girassot, E 471, E 492, E 481), pasta de avelas (1%), sal, conservantes (E 282, E 202, E 270), aromas, antioxidantes (E 306, E 304i), minerais (ferro) e agente de tratamento da farinha (E 300). Pode conter lelte.

Result:
Farinha de trigo, açúcar, água, levedura, xarope de glucose-frutose, óleo vegetal (girassol), ovo líquido pasteurizado, cacau magro em pó 2.9%, maltodextrina, gordura vegetal (palma), estabilizadores, e422, EE 412, emulsionantes, lecitina de girassot, e471, EE 492, EE 481, pasta de avelas 1%, sal, conservantes, e282, EE 202, EE 270, aromas, antioxidantes, e306, EE 304i, minerais (ferro), agente de tratamento da farinha (e300), Pode conter lelte

Code 8410022010888

**Comment by stephanegigandet** [comment]
It's one more case of breaking something by fixing something else. Here the issue is that "E" in Portuguese means "and", so it broke the assumptions of one of the regexps to parse additives enumerations. Fixing.
