### ISSUE TITLE
Automatically dispatch imports to Open Beauty Facts, Open Product Facts etc.

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#3776]
Some producers send us non food products through the platform for producers.

We can move those products to OBF, OPF, OPFF etc. but then they will get imported again on OFF at the next synch from the producers platform to the public database.

When we import products from the producers platform to OFF, we can check if the product already exists on OBF etc. In that case, we can redirect the import to the right database.

**Comment by stephanegigandet** [comment]
This means that we would still get non-food products once on OFF, but once moved to OBF etc. the next time they are imported, they would go to the right platform.

**Comment by teolemon** [comment]
We could also help the producer do the right thing even before. 
Look for cosmetic clues to auto-triage the product:
- boolean in a specific column and visible in the producer platform, and that can be triggered by various conditions (Robotoff based on the name of the product, category prediction, actual category, specific ingredients, specific labels…)

**Comment by AcuarioCat** [comment]
Not all but a vast majority have one of several select ingredients that don't appear in food products, which would be a good clue, for example AQUA, PARFUM - this is a pretty strong clue that it is not a food product.

**Comment by stephanegigandet** [comment]
Yes, we can find ways to detect non food products, but it will be another feature. :) This issue is about first creating the plumbing that allows the dispatching. It will allow us to import the current non food products we have, and we can find smarter ways to do things later.
