### ISSUE TITLE
If % is before ingredient then ingredient is truncated

### ISSUE THREAD

**Issue by AcuarioCat** [openfoodfacts/openfoodfacts-server#3826]
https://fr.openfoodfacts.org/cgi/test_ingredients_analysis.pl?ingredients_text=31%25+pur%C3%A9e+de+fraise%2C+25%25+pur%C3%A9e+de+banane%2C+23%25+jus+de+raisin+blanc+concentr%C3%A9%2C+9%25+jus+d%27orange%2C+2%25+jus+de+raisin+blanc%2C+jus+de+betterave+rouge%2C+1%25+jus+de+citron%2C+stabilisants%3A+farine+de+graines+de+caroube%2C+gomme+guar%2C+acidifiant%3A+acide+citrique%2C&action=process

31% purée de fraise, becomes ée de fraise 31%,

Tested in Spanish with the same results.

**Comment by Ban3** [comment]
#3706 is the same issue
