### ISSUE TITLE
ee de tomates

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#3827]
**Describe the bug**
`ee de tomate` is analysed as an ingredient.

**To Reproduce**
Check out any product in [https://be.openfoodfacts.org/ingrediënt/fr:ee-de-tomate](https://be.openfoodfacts.org/ingrediënt/fr:ee-de-tomate)

**Additional context**
It looks like `pur` is removed. It is not defined in `ingredients_processing.txt`. Somewhere else maybe?

**Comment by Ban3** [comment]
#3706 and #3826

**Comment by aleene** [comment]
Ah it due to the % processing maybe

**Comment by Ban3** [comment]
> Ah it due to the % processing maybe

Moving the percentage to end "fixes" it, so there seems to be some connection. Haven't looked further than that

**Comment by aleene** [comment]
> Moving the percentage to end "fixes" it
What does this mean?

**Comment by AcuarioCat** [comment]
The problem occurs when the ingredient list has the structure 'Quantity% ingredient'
So  '25% puree de tomate, 10% sucre, ....' is a problem.

With the structure 'Ingredient Quantity%' the problem does not occur.

So if it is changed to 'puree de Tomate 25%, sucre 10%, ...' then the problem does not appear and the ingredients aren't truncated.

**Comment by Ban3** [comment]
This is the pattern truncating the ingredient:
https://github.com/openfoodfacts/openfoodfacts-server/blob/83886ce282ee191c8432c4084ccd46084a03b36d/lib/ProductOpener/Ingredients.pm#L1125-L1130

[Regexr.com visualisation](https://regexr.com/588r1)

I don't really speak French, but wouldn't word boundary `\b` after `pur` (and I guess `de`?) what's wanted here? (It doesn't work properly on regexr, but does with Perl)

**Comment by aleene** [comment]
And why not `(pur\s|de\s|d')?`

**Comment by stephanegigandet** [comment]
> I don't really speak French, but wouldn't word boundary `\b` after `pur` (and I guess `de`?) what's wanted here? (It doesn't work properly on regexr, but does with Perl)

That's right, adding \b after (pur|de|d') would probably solve it.

````
 if ($ingredient =~ /^\s*(\d+((\,|\.)\d+)?)\s*(\%|g)\s*((pur|de|d')\b)?\s*/i) {
