### ISSUE TITLE
Parsing issue

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#3838]
**Describe the bug**
In `minéraux (carbonate de calcium, carbonate de magnésium, fer élémentaire)` `fer élémentaire` is parsed as `carbonate de fer élémentaire`.

**To Reproduce**
See: [https://be.openfoodfacts.org/ingrediënt/fr:carbonate-de-fer-elementaire](https://be.openfoodfacts.org/ingrediënt/fr:carbonate-de-fer-elementaire)

**Comment by aleene** [comment]
@stephanegigandet Didn't you solve this one?

**Comment by svensven** [comment]
the products still showing up under that search just haven't had their ingredients re-parsed. editing them and saving them, or running update_all_products.pl, should fix them.

**Comment by stephanegigandet** [comment]
That's right. There's still a small issue when "fer elementaire" is unaccented (or with wrong accents), I'll fix it.
