### ISSUE TITLE
Navigating to the 2nd page of contributors is broken

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#3850]
### What
- Navigating to the 2nd page of contributors is broken: the bottom links redirects to users/
- https://world.openfoodfacts.org/contributors/users/2

### Code pointer
```html
<ul id="pages" class="pagination"><li class="unavailable">Pages:</li><li class="current"><a href="">1</a></li><li><a href="/contributors/users/2">2</a></li><li><a href="/contributors/users/2" rel="next$nofollow">Next</a></li></ul>
```

### Screenshot
Still in production with the redesign (Nov 2022)

![Image](https://user-images.githubusercontent.com/1689815/201684105-cb6998e1-9173-42f5-a616-5263ac221199.png)

### Part of
- #5529

**Comment by jolesh** [comment]
Yes the link doesn't work, where have you found it?

**Comment by Ban3** [comment]
@jolesh https://world.openfoodfacts.org/contributors You can get there from homepage by selecting `Contributors` from `Explore products by...`

**Comment by jolesh** [comment]
Ah thanks, found it

**Comment by teolemon** [comment]
Given that we have fixed perf issue on the contributors page, this issue is now impactful again.

**Comment by teolemon** [comment]
I have spotted a similar issue on packager codes: I have a similar issue on the packager codes: https://world.openfoodfacts.org/packager-codes/emb_codes/2
