### ISSUE TITLE
Carbonated water: Dureté de l'eau / Жёсткость воды

### ISSUE THREAD

**Issue by aleksejrs** [openfoodfacts/openfoodfacts-server#386]
Some carbonated waters specify "[Жёсткость воды](https://ru.wikipedia.org/wiki/%D0%96%D1%91%D1%81%D1%82%D0%BA%D0%BE%D1%81%D1%82%D1%8C_%D0%B2%D0%BE%D0%B4%D1%8B)" ([Dureté de l'eau](https://fr.wikipedia.org/wiki/Duret%C3%A9_de_l%27eau)) in мг-экв/л.

**Comment by hangy** [comment]
https://en.wikipedia.org/wiki/Hard_water#Measurement
https://de.wikipedia.org/wiki/Wasserh%C3%A4rte#Einheiten_und_Umrechnung

**Comment by hangy** [comment]
Reopening. The basic logic works fine, but apparently, the UI's JavaScript needs to be modified to support this changed range of units for `water-hardness`.
