### ISSUE TITLE
Default language entries + language-less entries for taxonomies, using the xx: prefix

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#3872]
The current taxonomy work very well for entries that are in one language and can be translated in other languages (e.g. categories, ingredients), but it is much less adapted for entries that do not have translations in other languages (e.g. labels like "AB - Agriculture Biologique" or "Red Tractor" should not really be translated and displayed in another language), or that are more or less language-less (like many brands, and labels that are in fact brands like Demeter or Max Havelaar).

This is causing issues for labels where we have to add the same entries like "Demeter" in many different languages, so that we can match it for products entered in different languages, and also so that we can display it without a fr: or de: etc. prefix.

To create a brands taxonomy, we also need language-less entries that match in all languages, and are displayed in all languages. (there are a few rare exceptions where brands are translated)

The proposed solution is a xx: language prefix that can be used as a default language:

fr:AB Agriculture Biologique -> canonical name is fr:ab-agriculture-biologique
xx:AB Agriculture Biologique -> makes AB Agriculture Biologique match in all languages, and also makes AB Agriculture Biologique a default translation for all languages (unless they have their own entry)

And that can also be used for language less entries:

xx:Nestlé -> xx:nestle is the canonical name, it matches in all languages, and is the default translation for all languages

the xx: code is currently unassigned, and using a 2 letter code will require much less changes (and create much less risks of breaking something) than using something different.

**Comment by VaiTon** [comment]
> The proposed solution is a xx: language prefix that can be used as a default language:

But do we want to use this as the default label? I mean the one we pass via api and the one we do computation on? Right now we use `en`, have you thought about switching?

**Comment by stephanegigandet** [comment]
> > The proposed solution is a xx: language prefix that can be used as a default language:
> 
> But do we want to use this as the default label? I mean the one we pass via api and the one we do computation on? Right now we use `en`, have you thought about switching?

We will keep en:something as the canonical name for entries that are in English. e.g. for ingredients and categories, we will continue to have en:garlic and en:beverages as the canonical names.

For entries that don't have a language, like most brands, we will use xx:nestle as the canonical name.

**Comment by stephanegigandet** [comment]
The discussion about the choice of which prefix to use in the comments of this PR: https://github.com/openfoodfacts/openfoodfacts-server/pull/4385
