### ISSUE TITLE
Ingredients that may be from palm oil not translated

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#388]
![image](https://cloud.githubusercontent.com/assets/1689815/17277300/ef531f2e-573f-11e6-94a3-1c37660aada5.png)

**Comment by teolemon** [comment]
http://ru.openfoodfacts.org/product/7622210210920/%D1%88%D0%BE%D0%BA%D0%BE%D0%BB%D0%B0%D0%B4-%D0%BC%D0%BE%D0%BB%D0%BE%D1%87%D0%BD%D1%8B%D0%B9-%D0%B0%D0%BB%D1%8C%D0%BF%D0%B5%D0%BD-%D0%B3%D0%BE%D0%BB%D1%8C%D0%B4-%D0%BC%D0%B0%D0%BA%D1%81%D1%84%D0%B0%D0%BD-%D1%81-%D0%B0%D1%80%D0%B0%D1%85%D0%B8%D1%81%D0%BE%D0%BC-%D1%80%D0%B0%D0%B7%D0%BD%D0%BE%D1%86%D0%B2%D0%B5%D1%82%D0%BD%D1%8B%D0%BC%D0%B8-%D0%B4%D1%80%D0%B0%D0%B6%D0%B5-%D0%B8-%D0%BA%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D0%BB%D1%8C%D1%8E-mondelez

**Comment by hangy** [comment]
The Russian translation of `ingredients_that_may_be_from_palm_oil` is commented out on the [Wiki](http://en.wiki.openfoodfacts.org/Translations_-_Web_site_interface) and in the current git version of Lang.pm. Probably needs to be checked by a native speaker.

**Comment by teolemon** [comment]
https://en.wiki.openfoodfacts.org/Global_palm_oil_taxonomy

**Comment by aleene** [comment]
Is part of #522, but might need to double check the additives taxonomy
