### ISSUE TITLE
The (ii) is parsed as ingredient

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#3883]
**Describe the bug**
The (ii) in `colorant (E160a(ii))` is parsed as ingredient.

**To Reproduce**
See [https://be.openfoodfacts.org/ingrediënt/fr:ii](https://be.openfoodfacts.org/ingrediënt/fr:ii)

**Expected behavior**
Needs to be expanded as `E160a-ii `??

**Comment by stephanegigandet** [comment]
E160a(ii) works, but the ) after it makes the detection fail, fixing
