### ISSUE TITLE
The "Change criteria" button in Advanced Search is not working anymore

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#3885]
The "Change criteria" button in Advanced Search is not working anymore

**To Reproduce**

1. Go to 'https://de-en.openfoodfacts.org/cgi/search.pl?action=process&sort_by=unique_scans_n&page_size=20&action=display'
2. Click on 'Change search criteria'
3. You are redirected to the same page

**Comment by areeshatariq** [comment]
I'll look into the Search products template

**Comment by stephanegigandet** [comment]
Deployed last week.
