### ISSUE TITLE
Editing a product removes it from under https://world.openfoodfacts.org/code/...xx

### ISSUE THREAD

**Issue by aleksejrs** [openfoodfacts/openfoodfacts-server#3903]
There were two or more products under https://world.openfoodfacts.org/code/200929xx (e.g., https://world.openfoodfacts.org/product/20092955/trancio-di-salmone-aromatizzato-al-pepe-nero)
After editing them, they are not there any more.

**Comment by stephanegigandet** [comment]
@aleksejrs It's in fact a feature ;) There were too many possible value for codes, so we removed the entries that have less than 3 x at the end.

You should see your products here: https://world.openfoodfacts.org/code/20092xxx
