### ISSUE TITLE
Head after merged-PR #3831 raises error message

### ISSUE THREAD

**Issue by oricdev** [openfoodfacts/openfoodfacts-server#3908]
**Describe the bug**
Head at merged-PR #3831 is ok with docker; but then, with the next heads, when docker starts, backend_1 says "Software error: global symbol producers_email requires explicit package name (did you forget to declare $producers_email at /opt/product_opener/lib/ProductOpener/Mail.pm line 97)

**To Reproduce**
cd openfoodfacts-server/docker
./start_dev.sh

**Screenshots**
![image](https://user-images.githubusercontent.com/15727915/87984286-04c63000-cada-11ea-9bd8-d7948f8b56f3.png)

**Desktop (please complete the following information):**
 - OS: Kubuntu 20.04 LTS

**Comment by hangy** [comment]
Can you update to master? O
I believe I fixed that in #3881.

**Comment by oricdev** [comment]
I created a fork, before the fixup. But never mind. I will adapt. Thanks!

**Comment by GendelfLugansk** [comment]
I also see this error (on master branch as well)
