### ISSUE TITLE
Issues with, and a question about en:Red kidney beans

### ISSUE THREAD

**Issue by aleksejrs** [openfoodfacts/openfoodfacts-server#3917]
**Describe the bug**
* The obvious issue is "`en:Dried red kidney beans`" is not in "`en:Red kidney beans`".
* Am I correct that "kidney common beans" are always "red kidney beans"? Then "`en:Canned kidney common beans`" must also be in "`en:Red kidney beans`".
* Am I correct that "фасоль красная натуральная" in Russia is always "red kidney bean"?

**Number of products impacted**
Over a hundred.

**Comment by jolesh** [comment]
Seems to be already fixed if not open the issue again. @aleksejrs
