### ISSUE TITLE
Doubled complete products update list in Russian (ru.openfoodfacts.org, by.openfoodfacts.org)

### ISSUE THREAD

**Issue by aleksejrs** [openfoodfacts/openfoodfacts-server#3918]
![Screenshot_2020-07-22-double](https://user-images.githubusercontent.com/1025861/88217391-27d21a80-cc67-11ea-9e06-5a78c4cc1ac7.png)
https://ru.openfoodfacts.org/
https://by.openfoodfacts.org/

**Comment by teolemon** [comment]
Bumping to P1 @aleksejrs

**Comment by aleksejrs** [comment]
@teolemon Why did you ping me?

**Comment by aleksejrs** [comment]
Works now, thanks @teolemon.
