### ISSUE TITLE
The blue "Explore by" button is broken

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#3919]
The links have `https://us.openfoodfacts.org/misc/nutriscore-computed/nutrition-grades%20rel=`
As a result they are broken.

**Comment by stephanegigandet** [comment]
Happens for the second level of drilldown:

![image](https://user-images.githubusercontent.com/8158668/88527933-3a00df80-cffe-11ea-95a4-09159e1300eb.png)
