### ISSUE TITLE
[Ingredient parser] в/с, х/п

### ISSUE THREAD

**Issue by aleksejrs** [openfoodfacts/openfoodfacts-server#3925]
* "в/с" after an ingredient name means "высшего сорта" or "высший сорт".
* "мука пшеничная х/п" means "мука пшеничная хлебопекарная".

**Comment by svensven** [comment]
(The problem is that the parser is splitting the / into a new ingredient, not just that they're unrecognised terms.)
![image](https://user-images.githubusercontent.com/5736616/93077194-63de9600-f680-11ea-9d4f-b2a69b9e3aec.png)

**Comment by Ban3** [comment]
Abbreviations in Ingredients.pm can be used for expanding them so they don't get split (combined with ingredient taxonomy stopwords and/or ignore regexps if needed)

**Comment by svensven** [comment]
> 
> 
> Abbreviations in Ingredients.pm can be used for expanding them so they don't get split (combined with ingredient taxonomy stopwords and/or ignore regexps if needed)

cool, I'll add them, thanks.
