### ISSUE TITLE
Enable linking cities with Wikidata

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#393]
Packaging codes cities need to somehow be linked with Wikidata. 

This bug is an open question on how to do this.

**Comment by hangy** [comment]
Somewhat related to #282. Maybe add some kind of datagame (like [Mix'n'match](https://tools.wmflabs.org/mix-n-match/) to links the cities?

**Comment by teolemon** [comment]
I'm superseding this one by #2011 which is a more generic version (allow linking the value of a facet to Wikidata, pretty much with the same code we use for translations)
