### ISSUE TITLE
Romanian "To Be Completed Page" doesn't work

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#395]
http://ro.openfoodfacts.org/state/to-be-completed

@lucaa

**Comment by TaciteOFF** [comment]
It's here 
http://ro.openfoodfacts.org/status/de-completat

**Comment by teolemon** [comment]
Corrected at http://en.wiki.openfoodfacts.org/Translations_-_Index_page_-_Romanian

**Comment by teolemon** [comment]
Needs refresh.

**Comment by hangy** [comment]
Shouldn't this just be added to [%wiki_texts](https://github.com/openfoodfacts/openfoodfacts-server/blob/57157dc3162bd28093224352a724091bdfff5b1b/lib/ProductOpener/Config_off.pm#L154-L174) in order to refresh automatically?

**Comment by teolemon** [comment]
we have the po branch. I'd very much like to split the static pages into strings translatable using gettext
