### ISSUE TITLE
Facet Bug on Romanian page

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#396]
http://ro-en.openfoodfacts.org/ingredient/zahar/categories
for products that contain the ingredient Zahar - Romania
It should probably read
Categories for products that contain the ingredient Zahar - Romania

**Comment by TaciteOFF** [comment]
it works here though http://ro-en.openfoodfacts.org/ingredient/zahăr/categories

**Comment by stephanegigandet** [comment]
zahar and zahăr are currently considered to be different ingredients, as we currently do not deaccent ă to a

**Comment by hangy** [comment]
Looks to be fixed, since zahăr and zahar are separate categories now.
