### ISSUE TITLE
Show and edit nutrition facts in a special order in Russian

### ISSUE THREAD

**Issue by aleksejrs** [openfoodfacts/openfoodfacts-server#397]
Russian products usually list them as:
* proteins / белки
* fat / жиры
* carbohydrates / углеводы
* energy / энергетическая ценность / калорийность

**Comment by aleksejrs** [comment]
Also, kcal is used more often than kJ, or at least it usually comes first and is more likely to be the only one.

**Comment by hangy** [comment]
Published to production.
