### ISSUE TITLE
Add a warning if the barcode is known to be ambiguous

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#403]

**Comment by hangy** [comment]
Based on [GS1-8 Prefix](https://www.gs1.org/docs/barcodes/GS1_General_Specifications.pdf), we should probably add a blanket warning for products starting with 000 – 099 and 200 – 299. As these prefixes are reserved for restricted circulation numbers in a company, it is to be expected that there will be conflicts between different companies.

**Comment by stephanegigandet** [comment]
Fixed by @hangy in #1646
