### ISSUE TITLE
The APK file of Open Products Facts is 404

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#4035]
### What
- ```Lyroy Link to "Download APK" lead to a 404 Error :disappointed: (For OpenProductsFacts only it seems) (edited) ```
![image](https://user-images.githubusercontent.com/1689815/90378012-2125a000-e079-11ea-9357-05efe95f4364.png)

### Part of
- #5555

**Comment by hangy** [comment]
- Apple store link is wrong (Open Beauty Facts)
- Google and Microsoft links use French language for the world subdomain (should be English)
- Microsoft link is wrong (Open Food Facts) - should we just remove that button on all pages? Windows mobile is no more and the linked app is likely not maintained to reflect any current changes, which leads to a bad first impression
- Is there any build pipeline that place the built APKs anywhere? Maybe the APK download button should link (through a URL shortener?) to the newest release on https://github.com/openfoodfacts/openfoodfacts-androidapp/releases? cc @VaiTon

**Comment by github-throwaway** [comment]
@teolemon remove or point to the correct apk?
