### ISSUE TITLE
Add a clear invitation to edit on uncomplete products

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#404]
"Complete this product to get the nutrition grade"
"Complete the ingredient list and get additives deciphered"
"Complete the packager code to know where this product was made"

**Comment by teolemon** [comment]
```
<div data-alert="" class="alert-box info store-state" id="warning_not_complete" style="display: block;">
<span>This product is not complete. You can help complete it by editing it, or taking photos using the app for <a href="https://android.openfoodfacts.org">Android</a> or <a href="https://ios.openfoodfacts.org">iPhone/iPad</a>.<br>
 <a href="#" class="close">×</a>
</span></div>
```

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/27480504-7c87fbf6-5818-11e7-99bd-b827c3de7796.png)
![image](https://user-images.githubusercontent.com/1689815/27480508-81c6235e-5818-11e7-875b-e6136eda28ae.png)

**Comment by stephanegigandet** [comment]
Great idea, done and pushed to production.
