### ISSUE TITLE
Greek language is listed as "Modern Greek" instead of "Greek"

### ISSUE THREAD

**Issue by svensven** [openfoodfacts/openfoodfacts-server#4070]
I was editing a product, and trying to find Greek in the language list, and eventually discovered it in the M's under "Modern Greek", which was not intuitive. 

As we're not likely to enter products in older forms of Greek, perhaps "Greek" could be the preferred term, at least in languages where it changes the prefix?

![image](https://user-images.githubusercontent.com/5736616/91165869-5cebe580-e6c9-11ea-9a3c-45b527952eb1.png) ![image](https://user-images.githubusercontent.com/5736616/91165882-62e1c680-e6c9-11ea-9c8e-3ea4e7189b8c.png)

**Comment by aleene** [comment]
I agree. Wonder what needs to be changed for this? Only the translations in `languages.txt`?

**Comment by Ban3** [comment]
>Only the translations in languages.txt?

The languages are build from wikidata, so you need to take that into account as well. See [build_languages_taxonomy_from_wikidata.pl](https://github.com/openfoodfacts/openfoodfacts-server/blob/master/scripts/build_languages_taxonomy_from_wikidata.pl)

**Comment by hangy** [comment]
> > Only the translations in languages.txt?
> 
> The languages are build from wikidata, so you need to take that into account as well. See [build_languages_taxonomy_from_wikidata.pl](https://github.com/openfoodfacts/openfoodfacts-server/blob/master/scripts/build_languages_taxonomy_from_wikidata.pl)

That's true, but I also think that this has only been run once, since @stephanegigandet has already done some manual changes to work around other bugs/usability issues with the Wikidata translations. 🙂

**Comment by svensven** [comment]
Also the wikidata list might not be an ideal source to pull from automatically on an ongoing basis.
It often has the very formal e.g."Greek language" in a lot of languages, where the normal usage might be "Greek".
E.g. for Spanish it has "Idioma griego", but the wikipedia page https://es.wikipedia.org/wiki/Idioma_griego itself shortens that to "Griego": 
![image](https://user-images.githubusercontent.com/5736616/91289336-21fdb680-e78a-11ea-8320-505d5b89ff2c.png)
Actually, the same holds for Greek itself: "Ελληνική γλώσσα" vs "Ελληνικά".
"Spanische Sprache" vs "Spanisch", etc...

**Comment by stephanegigandet** [comment]
(I wrongly referenced this issue, sorry)

@hangy is right, we only initialized the languages taxonomy once from wikidata, we can make individual changes to languages.txt

If we do want to update from wikidata again (e.g. if we think there are some new translations), we'll review all diffs manually.
