### ISSUE TITLE
Hard to click tag completions

### ISSUE THREAD

**Issue by Ban3** [openfoodfacts/openfoodfacts-server#4071]
**Describe the bug**
Extracting this from #4052 so that it doesn't get lost now that the other issue is fixed:

> Also, it can be quite hard to click on the result we want, as seen on this video :
> https://imgur.com/a/pWJUPJW
> 
> I'm using Safari 13.1.2.
> 
> Thanks

**Comment by hangy** [comment]
@stephanegigandet Do you know if the most recent version of tagify is released in production? This seems to be out of scope of our project, and caused by some bug in Safari, as it works well in Chrome. I'd like to create an issue [upstream](https://github.com/yairEO/tagify).

**Comment by svensven** [comment]
A problem I often have while editing a tag field is if my mouse happens to be over the suggestion dropdown while i'm typing something different, and press enter, it will delete what i've typed and choose the suggestion my mouse was over instead.

**Comment by stephanegigandet** [comment]
@hangy : I ran npm install + npm run build yesterday, but I don't know how to see which version is installed

**Comment by hangy** [comment]
@TaciteOFF could you please check if the bug still happens with the current update?

**Comment by stephanegigandet** [comment]
I'm closing this bug as it's very old and hopefully solved. @Ban3 @TaciteOFF @svensven : Hello! :) and feel free to re-open if it is still an issue.
