### ISSUE TITLE
Broken product map

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#4088]
https://world.openfoodfacts.org/countries

The map of countries is not displayed

![image](https://user-images.githubusercontent.com/1689815/91646007-17be0f80-ea4b-11ea-8010-62d24decff68.png)

**Comment by hangy** [comment]
The reason is `var countries_map_names=JSON.parse('` with the text `"CI":"Côte d'Ivoire"`. The string is terminated after `'`.
