### ISSUE TITLE
Issue with the Fleury-Michon import

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#4108]
Some ingredient lists were replaced by HTML::Entities

**Comment by Ban3** [comment]
Good chance I broke it [here](https://github.com/openfoodfacts/openfoodfacts-server/commit/60323469890bcffbec29b81487c922064de1f99b#diff-09fccc61f6d903b8934727a5148d4ff6), if that's the script used.

**Comment by Ban3** [comment]
Confirmed that's the issue. Will make a PR.
