### ISSUE TITLE
No nutrition average for Pet food is being generated

### ISSUE THREAD

**Issue by aleksejrs** [openfoodfacts/openfoodfacts-server#412]
http://world.openfoodfacts.org/category/pet-food

**Comment by teolemon** [comment]
weird. We're not Open Dog Food Facts, but it should get generated…

**Comment by aleksejrs** [comment]
> We're not Open Dog Food Facts

It doesn't say "Open Human Food Facts", or even "Open Human-Edible Food Facts" anywhere.

**Comment by teolemon** [comment]
:-)

**Comment by aleksejrs** [comment]
Seems to work now: http://world.openfoodfacts.org/category/pet-food http://ru.openfoodfacts.org/category/%D0%BA%D0%BE%D1%88%D0%B0%D1%87%D0%B8%D0%B9-%D0%BA%D0%BE%D1%80%D0%BC

**Comment by aleksejrs** [comment]
Seems to work now: http://world.openfoodfacts.org/category/pet-food http://ru.openfoodfacts.org/category/%D0%BA%D0%BE%D1%88%D0%B0%D1%87%D0%B8%D0%B9-%D0%BA%D0%BE%D1%80%D0%BC

**Comment by aleksejrs** [comment]
Actually, http://ru.openfoodfacts.org/category/%D0%BA%D0%BE%D1%80%D0%BC%D0%B0-%D0%B4%D0%BB%D1%8F-%D0%B4%D0%BE%D0%BC%D0%B0%D1%88%D0%BD%D0%B8%D1%85-%D0%B6%D0%B8%D0%B2%D0%BE%D1%82%D0%BD%D1%8B%D1%85 says only 13 products are being used, but there are 15-16 that have proteins and fats specified.

**Comment by hangy** [comment]
I think this is fine on Open Pet Food Facts: https://world.openpetfoodfacts.org/category/dog-food

Please reopen if I'm wrong.
