### ISSUE TITLE
— isn't considered as a separator

### ISSUE THREAD

**Issue by TaciteOFF** [openfoodfacts/openfoodfacts-server#413]
The OCR sometimes uses "—" instead of "-".

Doing so causes problems in the API.

**Comment by aleksejrs** [comment]
What does it mean for you?  In Russian, it is used (optionally) in entries like "acidifier — citric acid".

**Comment by hangy** [comment]
Published to production.

**Comment by TaciteOFF** [comment]
Can ● please be added as separator for OpenBeautyFacts? Thanks.
