### ISSUE TITLE
Journalists with a 13-inch MacBook pro have no way to tell we have an app

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#4132]
Journalists with a 13-inch MacBook pro or MacBook Air have no way to tell we have an app. 
![image](https://user-images.githubusercontent.com/1689815/92096781-92828400-edd7-11ea-95dd-63f8dbada9b1.png)

They will also never be able to discover charts.

**Comment by hangy** [comment]
> Journalists with a 13-inch MacBook pro or MacBook Air have no way to tell we have an app.
> ![image](https://user-images.githubusercontent.com/1689815/92096781-92828400-edd7-11ea-95dd-63f8dbada9b1.png)

"No way" is just not true: ![grafik](https://user-images.githubusercontent.com/87124/92099054-556bc100-edda-11ea-9337-7ddeae8542ab.png) Also, there's the small green app button in the top right of navbar. A call to install some app is not useful if you don't even know which device the user has. For example, as an Android user, I hate it when people link to "install our app" and that just links to the Apple Store.

> They will also never be able to discover charts.

Why not? The link to the charts is visible in the navbar.

**Comment by teolemon** [comment]
From anecdotal evidence, the little icon for charts is not self explanatory, not is the mobile phone. 
There is a difference between above below floating line. The app comes as an afterthought, at the very end.
Also, note that we have deeplinks to the product page in the app for Android, if you have the app installed.

**Comment by teolemon** [comment]
Ok, again today in a call with @stephanegigandet 
And a week ago in a call about gamification, also with @stephanegigandet 
Same string of questions, again and again: 
```
Can you tell us what OFF is ?
A database
Did you go on the website ?
Yes
Did you notice we had an app ? 
No
What size is your screen ?
13 inch.
```
I strongly believe we need something like the web banner, above the floatline. It will produce conversions for Android through the install to your device mechanism, and awareness for both platform.
![image](https://user-images.githubusercontent.com/1689815/116419130-0b3dc100-a83d-11eb-834f-c6094b538443.png)

**Comment by teolemon** [comment]
fixed by the redesign
