### ISSUE TITLE
Products to be completed is not working

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#4141]
Products to be completed is not working. This might be purely server related.

- [ ] Products to be completed
- [ ] Additives explorer
- [ ] Category explorer
- [ ] My Contributions
![image](https://user-images.githubusercontent.com/1689815/92211895-72af9680-ee91-11ea-8db8-780f6cdbbbdf.png)

**Comment by stephanegigandet** [comment]
looks like .json is not triggering the JSON

query from the app:

https://world.openfoodfacts.org/state/to-be-completed/1.json?nocache=1&fields=brands%2Cproduct_name_fr%2Cproduct_name%2Cimage_small_url%2Cquantity%2Cnutrition_grades_tags%2Ccode

probably related the change related to how to process query parameters
