### ISSUE TITLE
Wrong nutri-score because doesn't detect fruits, vegs even though they are entered manually.

### ISSUE THREAD

**Issue by Kezxo** [openfoodfacts/openfoodfacts-server#4150]
**Describe the bug**
This product has the wrong Nutri Score: https://world.openfoodfacts.org/product/7340083442605/ekologiskt-jordnotssmor-creamy-garant?rev=20
It says ``Fruits, vegetables, nuts, and colza/walnut/olive oils: 0 / 5 (value: 0, rounded value: 0)`` even though it's 99% nuts.

**To Reproduce**
I guess check the history to see what happened.

**Expected behavior**
It should get a B or something based on this nearly identical product: https://world.openfoodfacts.org/product/7340083442612/ekologiskt-jordnotssmor-crunchy-garant?rev=18

This one also shows the Nutri Score below the ``Fruits, vegetables, nuts and rapeseed, walnut and olive oils (manual estimate from ingredients list)`` thing so maybe that's related? Does the site check them from top to bottom?

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 80.0.1 (64-bit)

**Number of products impacted**
No idea.

**Comment by aleene** [comment]
I re-entered the name of the nutrient and now it is working. It gets 5 positive points and moves to C.

So I do not know what the issue was. The nutrient seems not to have been recognised.

**Comment by stephanegigandet** [comment]
This is because peanuts are not included in nuts (the <en:nuts parent is commented out)

# <en:nut
en:peanut, peanuts

Unless there is a good reason for commenting out the parent, I think we should uncomment it.

peanuts are explicitly listed as nuts for the Nutri-Score:

"Nuts include:
 Walnut, hazelnut, pistachio, Brazil nut, cashew, pecan, coconut (see clarifications above), peanut,
almond, chestnuts"

**Comment by Kezxo** [comment]
@aleene 
> I entered the name of the nutrient

I'm not sure what that means and I can't see any difference between the two revisions except the ingredients list now puts the nutri score at the bottom so I'm not exactly sure what you did. Anyway, it did the trick.

@stephanegigandet 
> This is because peanuts are not included in nuts

But why didn't that happen in the second link? It also had peanuts in the ingredients?

While we're talking nuts, any reason why they aren't vegetarian or vegan?

**Comment by aleene** [comment]
Maybe the peanuts have been kept separate from nuts as they are a separate allergen.

**Comment by aleene** [comment]
Probably I did that in order to prepare an integration of the allergens taxonomy into the ingredients taxonomy. The allergens taxonomy is starting to be unmaintainable.

**Comment by stephanegigandet** [comment]
In terms of ingredients, peanuts are nuts, so we should put them under nuts. We will deal with allergens differently (e.g. the best way is probably to add properties like allergens:en: en:peanuts)

**Comment by aleene** [comment]
In english they distinguish between `tree nuts` and `peanuts`, also for allergens. So it would be sufficient to assign tree nuts and its children as allergen.

**Comment by aleene** [comment]
Which makes me wonder: when they write allergen `nuts` on a package, do they also mean peanuts?

**Comment by aleene** [comment]
wikipedia redirects `nut allergy` to https://en.wikipedia.org/wiki/Tree_nut_allergy

**Comment by aleene** [comment]
@Kezxo in the revisions I see the nut ingredients only mentioned once (my edit). So did you add it manually as well?

**Comment by Kezxo** [comment]
I see what you mean now, the revision mentions ``Added: fruits-vegetables-nuts-estimate`` but the others don't.
And yet in revision 20 which is linked in the first post you can see it at the very bottom of the nutrients. (and also in the ingredients, allergens and traces) 
This is what is confusing me and sounds like a bug. If it shows up I'm pretty sure I added the exact same thing originally and it's there on the page for revision 20.

**Comment by aleene** [comment]
What you (also) see on the nutrient list is the value from automatic detection, which failed.
I guess it is mentioned in the nutrients list, because a nut was detected, but the algorithm failed to work out the percentage. Removing these "bugs" is a continuous battle. Producers are very creative in making their ingredients unparsable.

**Comment by Kezxo** [comment]
Yeah, I understand. I'm not complaining that bugs happen, I just wanted to report this one. Thank for the help and all the hard work you all do here. 😊

**Comment by aleene** [comment]
Please continue reporting bugs. That is the only way to find them, thanks.
