### ISSUE TITLE
Huge ASC logo

### ISSUE THREAD

**Issue by Ban3** [openfoodfacts/openfoodfacts-server#4179]
**Describe the bug**
The image for the ASC label is huge.

**Screenshots**
![huge_asc](https://user-images.githubusercontent.com/236182/92745415-08b05900-f38b-11ea-8c70-a6c4d21d3953.png)

**Desktop (please complete the following information):**
 - Browser Chromium
 - Version Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36

**Number of products impacted**
https://world.openfoodfacts.org/label/responsible-aquaculture-asc

**Comment by teolemon** [comment]
https://github.com/openfoodfacts/openfoodfacts-server/blob/master/html/images/lang/en/labels/responsible-aquaculture-asc.867x90.svg?short_path=899641d

**Comment by stephanegigandet** [comment]
That's because the file name has 867x90 in it, we display a 867 pixels wide logo. The file needs to be named with the correct width for a 90pixel high image, otherwise it will be big and/or distorted.
