### ISSUE TITLE
Keep "empty" products with "unimportant" data specified for a longer time.

### ISSUE THREAD

**Issue by aleksejrs** [openfoodfacts/openfoodfacts-server#418]
### What
- I have added some products, but, IIRC, only specified store and location.  The products were deleted two days later.  I came back to edit them two or three weeks later.
- Another solution: warn contributors about the empty products they had added recently and let them delete them.

**Comment by TaciteOFF** [comment]
I don't see the point. If you edit them later it means you have pictures, so you have the barcode to recreate it. 
Encouraging people to create product pages without pictures isn't a good idea

**Comment by aleksejrs** [comment]
But I can forget the store and its location.  Are those fields very optional?

**Comment by TaciteOFF** [comment]
IMHO yes. Anyway, the auto delete occurs only for the product pages with the Empty state. So if you add the name, the quantity or anything else, it shouldn't be auto deleted
