### ISSUE TITLE
To validate a picture, you need to overwrite one of the three existing choices (main/ingredients/nutrition).

### ISSUE THREAD

**Issue by aleksejrs** [openfoodfacts/openfoodfacts-server#419]

**Comment by aleksejrs** [comment]
Or does "Photos to be validated" mean that there is not a picture selected for each of the three places?

**Comment by hangy** [comment]
> Or does "Photos to be validated" mean that there is not a picture selected for each of the three places?

I'm pretty sure that's what it is. At least, I have not seen any other "validation" of the product images.

**Comment by aleksejrs** [comment]
Then it's probably misnamed.
