### ISSUE TITLE
Producers platform fails to read some XLS files - ssconvert hangs

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#4203]
We use ssconvert (part of gnumeric) to convert Excel files to CSV before importing them in the producers platform.

Some xslx files sent by producers fail to load because ssconvert hangs.

ssconvert --version
ssconvert version '1.12.32'
datadir := '/usr/share/gnumeric/1.12.32'
libdir := '/usr/lib/gnumeric/1.12.32'

[Produits surgelés LES ATELIERS DE LA VEGGISSERIE.xlsx](https://github.com/openfoodfacts/openfoodfacts-server/files/5216650/Produits.surgeles.LES.ATELIERS.DE.LA.VEGGISSERIE.xlsx)

**Comment by stephanegigandet** [comment]
ssconvert is called like this:

ssconvert file.xlsx file.csv

what's strange is that the file is actually converted, file.csv is created and complete, but ssconvert does not come back (and takes 100% of a cpu).

**Comment by Ban3** [comment]
Maybe it's just about ssconvert version? I tried that file with ssconvert from Arch repos and it returned normally.

```sh
$ ssconvert --version
ssconvert versio 1.12.48
datakansio: /usr/share/gnumeric/1.12.48
kirjastokansio: /usr/lib/gnumeric/1.12.48
```

```sh
$ ssconvert Produits.surgeles.LES.ATELIERS.DE.LA.VEGGISSERIE.xls Produits.surgeles.LES.ATELIERS.DE.LA.VEGGISSERIE.csv 
Unhandled object of type Note
Unhandled object of type Note
Unhandled object of type Note
Unhandled object of type Note
Unhandled object of type Note
Unhandled object of type Note
Unhandled object of type Note
Unhandled object of type Note
Unhandled object of type Note
Unhandled object of type Note
Unhandled object of type Note
Unhandled object of type Note
Unhandled object of type Note
Unhandled object of type Note
Unhandled object of type Note
Unhandled object of type Note
Unhandled object of type Note
Unhandled object of type Note
Unhandled object of type Note
Unexpected element 'x:UIObj' in state : 
	{catch all)} -> shape -> ClientData
Unexpected element 'x:WidthMin' in state : 
	{catch all)} -> shape -> ClientData
Unexpected element 'x:UIObj' in state : 
	{catch all)} -> shape -> ClientData
Unexpected element 'x:WidthMin' in state : 
	{catch all)} -> shape -> ClientData
```

**Comment by svensven** [comment]
1.12.38 on cygwin still has the bugged behaviour.

**Comment by svensven** [comment]
sadly, i can't see anything obvious in the gnumeric .32-.48 changelogs like "we fixed a hang in ssconvert" to work out which version is fine.

**Comment by Ban3** [comment]
I was thinking about doing git bisect but 1.12.32 is old enough to not be buildable with my system libraries. Probably more trouble than it's worth.

**Comment by Ban3** [comment]
I can reproduce it on Debian buster with Gnumeric 1.12.44. That narrows it quite a bit if it's about gnumeric version.

**Comment by svensven** [comment]
possibly related: https://gitlab.gnome.org/GNOME/gnumeric/-/issues/499

**Comment by stephanegigandet** [comment]
Thanks a lot for investigating this. I'll try to build 1.12.48 from source, and just use that.

**Comment by stephanegigandet** [comment]
Thanks a lot for investigating this. I'll try to build 1.12.48 from source, and just use that.

**Comment by stephanegigandet** [comment]
Build notes for debian stretch:

apt-get install intltool
apt-get install bison
apt-get install itstool
apt-get install gtk+-3.0
wget http://ftp.gnome.org/pub/gnome/sources/goffice/0.10/goffice-0.10.48.tar.xz
./configure --prefix=/usr/
make
make install

wget http://ftp.gnome.org/pub/gnome/sources/gnumeric/1.12/gnumeric-1.12.48.tar.xz
./configure --prefix=/usr/
make
make install

**Comment by stephanegigandet** [comment]
Were also missing in production (off1):
apt-get install libxslt-dev
apt-get install libgsf-1-dev

**Comment by stephanegigandet** [comment]
Deployed on dev and off1.
