### ISSUE TITLE
Question marks in ingredient list should make the list considered "incomplete"

### ISSUE THREAD

**Issue by aleksejrs** [openfoodfacts/openfoodfacts-server#421]
Sometimes a picture or a label is suitable for entering only a part of the list, so instead of refusing to type what you can, or even deleting what you've typed, you can add question marks.  If there is no real ingredient list with question marks, PO should identify such lists as incomplete, like with empty ones (but not lose the content).

**Comment by hangy** [comment]
Fixed in 32611b82b8225ed2ed508aa7cb3e91354f30cac3, created [PR](https://bitbucket.org/openfoodfacts/product-opener/pull-requests/59) for internal review.

**Comment by hangy** [comment]
PR merged bef6b0df82802f15b31fb86f13e0d69d2834a980
