### ISSUE TITLE
Italian site is broken because of a bad CSS URL

### ISSUE THREAD

**Issue by svensven** [openfoodfacts/openfoodfacts-server#4233]
**Describe the bug**
![image](https://user-images.githubusercontent.com/5736616/93690957-9b14d300-fad6-11ea-86ba-01709d9834eb.png)
![image](https://user-images.githubusercontent.com/5736616/93690992-1c6c6580-fad7-11ea-9e50-ffdcc32c32e7.png)

**To Reproduce**
1. Go to https://it.openfoodfacts.org/

**Expected behavior**
![image](https://user-images.githubusercontent.com/5736616/93690962-c13a7300-fad6-11ea-851a-90598c8ce170.png)
![image](https://user-images.githubusercontent.com/5736616/93690977-edee8a80-fad6-11ea-8e98-a54c7bcf8c1a.png)

(possibly related to #4172?)

**Comment by hangy** [comment]
https://github.com/openfoodfacts/openfoodfacts-server/blob/23860303865cac14998375d01d8941b52cae70de/po/common/it.po#L4318 😄

**Comment by hangy** [comment]
> https://github.com/openfoodfacts/openfoodfacts-server/blob/23860303865cac14998375d01d8941b52cae70de/po/common/it.po#L4318 😄 

I changed this in Crowdin, but we should add a test to ensure this translation cannot get broken from Crowdin again.

**Comment by svensven** [comment]
Added test: #4234

**Comment by svensven** [comment]
working again now.
