### ISSUE TITLE
Unable to run OFF server locally with Docker

### ISSUE THREAD

**Issue by astagi** [openfoodfacts/openfoodfacts-server#4239]
**Describe the bug**
I'm not able to run OFF server locally using Docker, logs keep saying

```
backend_1    | Build %Lang - data_root: /mnt/podata
backend_1    | [Mon Sep 21 14:21:28.919221 2020] [so:warn] [pid 14:tid 140658699195520] AH01574: module perl_module is already loaded, skipping
backend_1    | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.22.0.5. Set the 'ServerName' directive globally to suppress this message
backend_1    | Killed
backend_1    | Action '-DFOREGROUND' failed.
backend_1    | The Apache error log may have more information.
docker_backend_1 exited with code 137
```

**To Reproduce**
1. Go to 'docker' folder
2. Run 'docker-compose -f ./docker-compose.yml -f ./docker-compose.dev.yml up'

**Desktop (please complete the following information):**
 - OS: Mac OSX Catalina 10.15.6
 - Docker v. 2.3.0.5 stable

**Comment by svensven** [comment]
Do you have enough ram? backend alone uses 3-4 GB for me.
What to the logs in `/var/lib/docker/volumes/docker_podata/_data/logs/` say?

**Comment by Ban3** [comment]
If it's a memory issue, the mod_perl.log probably has `unable to fork` messages. I'm sure there was an issue reported for it somewhere.

**Comment by astagi** [comment]
Ok I've just increased the RAM used by Docker from the app and everything works fine! 🎉 Thank you @svensven @Ban3 🙏
