### ISSUE TITLE
Packaging codes containing a slash '/' generates buggy URLs

### ISSUE THREAD

**Issue by TaciteOFF** [openfoodfacts/openfoodfacts-server#424]
Most Spanish packaging codes contain a slash. 

ES 10.01699/GE CE adds "ES 10.01699/GE C CE" to the product page and the following link :  
http://fr.openfoodfacts.org/code-emballeur/es-10-01699-ge-cececececececececececececececececececececec-ce

**Comment by hangy** [comment]
http://fr.openfoodfacts.org/api/v0/product/8410060401105.json contains
```
{
  "emb_codes":"ES 10.01699/GE EC",
  "emb_codes_orig":"ES 10.01699/GE CE",
  "emb_codes_tags":["es-10-01699-ge-ec"],
}
```
http://fr.openfoodfacts.org/code-emballeur/es-10-01699-ge-ec redirect to the incorrect http://fr.openfoodfacts.org/code-emballeur/es-10-01699-ge-cececececececececec-ce while http://fr.openfoodfacts.org/code-emballeur/es-10-01699-ge-ce is displayed correctly.

**Comment by teolemon** [comment]
Still occurring

`
Display::init - subdomain: factsworld-es 
Display::init - subdomain 1 cc-lc ip: 180.76.15.150 - hostname: factsworld-es.openfoodfacts.orgquery_string: packager-code/es-21-25538-le-cececececececececececececececececececececececececececececececececececececececec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec subdomain: factsworld-es - lc: en  - cc: world - country: en:world - 2
Display::init - ip: 180.76.15.150 - hostname: factsworld-es.openfoodfacts.orgquery_string: packager-code/es-21-25538-le-cececececececececececececececececececececececececececececececececececececececec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec subdomain: factsworld-es - lc: en - cc: world - country: en:world - redirect to world.openfoodfacts.org
display.pl : query_string: packager-code/es-21-25538-le-cececececececececececececececececececececececececececececececececececececececec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec
analyze_request : query_string 1 : packager-code/es-21-25538-le-cececececececececececececececececececececececececececececececececececececececec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec 
analyze_request : query_string 2 : packager-code/es-21-25538-le-cececececececececececececececececececececececececececececececececececececececec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec 
analyze_request : query_string 3 : packager-code/es-21-25538-le-cececececececececececececececececececececececececececececececececececececececec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec 
[Thu Oct 13 17:52:22 2016] -e: Use of uninitialized value in concatenation (.) or string at /home/off/lib/ProductOpener/Display.pm line 468.
Display::analyze_request - last component - es-21-25538-le-cececececececececececececececececececececececececececececececececececececececec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec - plural?  
Display::analyze_request - tag_type_from_singular en : packager-code
Display::analyze_request - lc: en lang: en - tagtype: emb_codes - tagid: es-21-25538-le-cececececececececececececececececececececececececececececececececececececececec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec
display.pl blogid:  tagid: es-21-25538-le-cececececececececececececececececececececececececececececececececececececececec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec urlsdate:  urlid:  user:  query:  
display_tag - normal - emb_codes - tagid: es-21-25538-le-cececececececececececececececececececececececececececececececececececececececec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec - canon_tagid: es-21-25538-le-cececececececececececececececececececececececececececececececececececececececec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec - newtagid: es-21-25538-le-cececececececececececececececececececececececececececececececececececececececec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec - title: ES 21.25538/LE CECECECECECECECECECECECECECECECECECECECECECECECECECECECECECECECECECECECECECECEC EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC-EC 
[Thu Oct 13 17:52:22 2016] -e: Use of uninitialized value $tagid2 in concatenation (.) or string at /home/off/lib/ProductOpener/Display.pm line 1835.
[Thu Oct 13 17:52:22 2016] -e: Use of uninitialized value $newtagid2 in concatenation (.) or string at /home/off/lib/ProductOpener/Display.pm line 1835.
Display.pm display_tag - redirect - tagid: es-21-25538-le-cececececececececececececececececececececececececececececececececececececececec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec - newtagid: es-21-25538-le-cececececececececececececececececececececececececececececececececececececececec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec - tagid2:  - newtagid2:  - url: /packager-code/es-21-25538-le-cececececececececececececececececececececececececececececececececececececececec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec-ec 
Display::init - subdomain: world 
`

**Comment by teolemon** [comment]
@hangy @stephanegigandet still occurring

**Comment by hangy** [comment]
> @hangy @stephanegigandet still occurring

Do you have an example at hand? I searched for products with slashes in production, and this seems to work fine. For example: https://world.openfoodfacts.org/packager-code/es-12-06648-c-ec

**Comment by teolemon** [comment]
https://es.openfoodfacts.org/codigo-de-envasador/es-26-06854-t-c-ec

**Comment by hangy** [comment]
OK, so apparently, https://world.openfoodfacts.org/packager-code/es-26-06854-t-ec works, and https://world.openfoodfacts.org/packager-code/es-26-06854-t-c-ec does not. Apparently `normalize_packager_codes` adds additional CE incorrectly.

**Comment by hangy** [comment]
I've tried adding some unit tests to figure out what's going on. However, I don't get where the additional "EC is coming from, though.

If I call `$normalize_ce_code('ES', '26.06854/T C')` manually, the result is as expected: `ES 26.06854/T C EC`. But apparently, in https://github.com/openfoodfacts/openfoodfacts-server/blob/c2d74a1f9a9b4d0fe853d0c8f0396bf0eaf07e1f/lib/ProductOpener/Food.pm#L4866 the "EC" source is kept, whereas it is not kept for `ES 26.06854/T CE`.

What I don't understand is that the captured groups seem to be the "same"/correct regarding the content that's passed to the replace statement: https://regexr.com/49tmj and https://regexr.com/49tmm

**Comment by stephanegigandet** [comment]
The issue is from a different regexp:

	$codes =~ s/(^|,|, )(es)(\s|-|_|\.)?(\d\d)(\s|-|_|\.|:|;)*(\d+)(\s|-|_|\.|\/|\\)?(\w+)(\.|_|\s|-)?(ce|eec|ec|eg)?\b/$1 . $normalize_es_ce_code->('es',$4,$6,$8)/ieg;

-> the CE|EC part is optional, and in this case is not matched, so it is kept.

A solution could be something like this:

$s =~    s/(^|,|, )(es)(\s|-|_|\.)?(\d\d)(\s|-|_|\.|:|;)*(\d+)(\s|-|_|\.|\/|\\)?(\w+)(\.|_|\s|-)?(ce|eec|ec|eg)?(?=,|$)/$1 . $normalize_es_ce_code->('es',$4,$6,$8)/ieg;

**Comment by hangy** [comment]
Yup, that works.
