### ISSUE TITLE
Country dropdown could put World first, instead of alphabetically sorted

### ISSUE THREAD

**Issue by svensven** [openfoodfacts/openfoodfacts-server#4254]
At the moment the World option is sorted alphabetically, so under W in english, and E for every other language, because `en:World` has no translations in taxonomies\countries.txt 

english: ![image](https://user-images.githubusercontent.com/5736616/94219009-ab192200-fedd-11ea-940a-da88f5360d75.png)
other languages: ![image](https://user-images.githubusercontent.com/5736616/94219028-b8cea780-fedd-11ea-88b6-43d9a1a25ed8.png)

Instead, it could be listed at the top of the list:

![image](https://user-images.githubusercontent.com/5736616/94219095-e4ea2880-fedd-11ea-8aef-2c5dc20c5833.png)

Of course, we'd probably want translations first.
https://github.com/openfoodfacts/openfoodfacts-server/blob/406569b557e681372f4faf6d3c91663781f4c57b/taxonomies/countries.txt#L131-L134

**Comment by svensven** [comment]
Possible fix for the sorting part. It works on my docker instance, but I don't know if it's good JS.
https://github.com/openfoodfacts/openfoodfacts-server/compare/master...svensven:issue-4254-dropdown-world-first

**Comment by hangy** [comment]
Is the alphabetical sort order caused by the HTML being generated in that way, or by the JS Script, that is applied there? Maybe it can already be done server-side, when the HTML fragment is created from the translations …

**Comment by svensven** [comment]
> Is the alphabetical sort order caused by the HTML being generated in that way, or by the JS Script, that is applied there? Maybe it can already be done server-side, when the HTML fragment is created from the translations …

AIUI the JS is sorting it, no matter what the server returns:
https://github.com/openfoodfacts/openfoodfacts-server/blob/406569b557e681372f4faf6d3c91663781f4c57b/html/js/display.js#L105-L109

**Comment by svensven** [comment]
Speaking of translating World, there's this: https://www.wikidata.org/wiki/Q16502. Worth adding?

**Comment by hangy** [comment]
> > Is the alphabetical sort order caused by the HTML being generated in that way, or by the JS Script, that is applied there? Maybe it can already be done server-side, when the HTML fragment is created from the translations …
> 
> AIUI the JS is sorting it, no matter what the server returns:
> https://github.com/openfoodfacts/openfoodfacts-server/blob/406569b557e681372f4faf6d3c91663781f4c57b/html/js/display.js#L105-L109
> 
> Also, it's not generated as HTML initially, it's populated by an AJAX call to /cgi/i18n/countries.pl only when you click on it.

I actually implemented the cgi script, but totally forgot about how it's used. 😅 In that case, can you create a PR for your suggestion?

> Speaking of translating World, there's this: https://www.wikidata.org/wiki/Q16502. Worth adding?

I'm not sure, if we use the linked data for world anywhere, but sure why not? @stephanegigandet

**Comment by svensven** [comment]
> > Speaking of translating World, there's this: https://www.wikidata.org/wiki/Q16502. Worth adding?
> 
> I'm not sure, if we use the linked data for world anywhere, but sure why not? @stephanegigandet

well, if we don't, AFAICT all non-english pages are going to have "en:World" at the top of the country list.
