### ISSUE TITLE
Add Welsh (cy) and Scottish Gaelic (gd) as language options for the UK

### ISSUE THREAD

**Issue by svensven** [openfoodfacts/openfoodfacts-server#4255]
I noticed countries with minority/multiple languages get a dropdown with language choices. I don't know what the criteria are for adding them, but they do have some level of official status in the UK.

And them being more accessible may drive someone to work on the translations?

**Comment by aleene** [comment]
We should have an approach for adding other languages. We could use https://en.wikipedia.org/wiki/European_Charter_for_Regional_or_Minority_Languages for this, as it they have been officially recognised by the governments.

**Comment by aleene** [comment]
And otherwise any wikipedia country info.
