### ISSUE TITLE
Autosuggest for Packaging Codes

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#426]
Since we already have all the packager codes for many countries, we could offer a suggestion system. 
It would need an API tweak to get a list of packaging codes, even if they're not used yet.

**Comment by hangy** [comment]
Fixed in aa998e5284bdecf417c3a55490450f0b54379be6, created [PR](https://bitbucket.org/openfoodfacts/product-opener/pull-requests/65) for internal review.
