### ISSUE TITLE
Add an API field to display the Eco-Score

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#4262]
Add an API field to display the Eco-Score with placeholder values for a few test products.

**Comment by hangy** [comment]
What's the Eco-score? Is it present on the packaging, or can it be derived from other values?

**Comment by stephanegigandet** [comment]
@hangy : the Eco-Score is not on the packaging, it is derived from the product category (that we match to environmental impacts thanks to a newly released open data database called Agribalyse), + the origins of ingredients, some labels, and data about the packaging.

I put a bit more details in #4287

**Comment by stephanegigandet** [comment]
Done in https://github.com/openfoodfacts/openfoodfacts-server/pull/4288

Available fields:

- ecoscore_score : numeric Eco-Score value
- ecoscore_grade : corresponding A to E grade
- ecoscore_data : Eco-Score computation details

And there is also an Ecoscore product attribute.
