### ISSUE TITLE
Consider migrating gluten support to ingredient analysis

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#4265]
Consider migrating gluten support to ingredient analysis. 
This would:
- [ ]  enable gluten intolerant users to better understand which ingredients contain gluten, as opposed to showing them only as an allergen.
- [ ]  make gluten detection more discoverable in the mobile apps

**Comment by aleene** [comment]
Note that this is for all allergens. It is already prepared. There is another issue for this.

**Comment by stephanegigandet** [comment]
Duplicate of #3297
