### ISSUE TITLE
Add gluten/vegan/vegetarian/palm oil to product attributes

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#4266]
Add gluten/vegan/vegetarian/palm oil to product attributes so that it can be made mandatory in smoothie.

**Comment by stephanegigandet** [comment]
All allergens and ingredients analysis tags will be individual attributes: https://wiki.openfoodfacts.org/Product_Attributes#Examples_of_Product_Attributes

**Comment by stephanegigandet** [comment]
Deployed in production.
