### ISSUE TITLE
Nutrient autocomplete issue in Chinese

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#427]
![image](https://cloud.githubusercontent.com/assets/1689815/17857210/293c8796-6881-11e6-9962-49005710eaa5.png)

**Comment by teolemon** [comment]
http://cn.openfoodfacts.org/cgi/product.pl?type=edit&code=6952229200072

**Comment by hangy** [comment]
There's a bunch of empty entries in `otherNutriments` that cause this:

```
var otherNutriments = [
{ "value" : "", "unit" : "kj" },
{ "value" : "", "unit" : "g" },
{ "value" : "", "unit" : "g" },
...
```

This is built by `$other_nutriments .= '{ "value" : "' . $Nutriments{$nid}{$lang} . '", "unit" : "' . $Nutriments{$nid}{unit} . '" },' . "\n";`, so I guess it's basically caused by missing translations (and no fallback)?

**Comment by hangy** [comment]
If we don't have values in the current `$lc`, just fallback to `en`?

**Comment by teolemon** [comment]
We need that one fixed. It's embarrassing.
