### ISSUE TITLE
Config discrepancy re Catalan

### ISSUE THREAD

**Issue by svensven** [openfoodfacts/openfoodfacts-server#4276]
I was trying to rebuild the countries taxonomy, and ran into a discrepancy.

lib/ProductOpener/Config_off.pm has this, and generates different countries.results.txt lines for Catalan than in the repo:
https://github.com/openfoodfacts/openfoodfacts-server/blob/5f716061cb04859437783e35ab59c799b351d3e6/lib/ProductOpener/Config_off.pm#L125-L134

docker/backend-dev/conf/Config.pm doesn't, and generates the same as in the repo:
https://github.com/openfoodfacts/openfoodfacts-server/blob/5f716061cb04859437783e35ab59c799b351d3e6/docker/backend-dev/conf/Config.pm#L120-L125

Which is correct/used in live?

**Comment by stephanegigandet** [comment]
I think we have changed Config_off.pm in prod to add unaccenting for Catalan, but we haven't rebuilt the country taxonomy after that.
