### ISSUE TITLE
No tag completions for tags with non-ASCII characters

### ISSUE THREAD

**Issue by Ban3** [openfoodfacts/openfoodfacts-server#4280]
**Describe the bug**
I tried 'ä' and 'ö' for Finnish tags, 'ü' for German tags and 'ê' for French tags. All of these seem to clear any suggestions.

**To Reproduce**
1. Edit any product
2. Click on 'Labels, certifications, awards' field
3. Start typing `DE-ÖKO-001`
4. After typing `Ö` no suggestions are shown.

**Desktop (please complete the following information):**
 - Browser Chromium
 - Version `Chromium 85.0.4183.83 Arch Linux`

**Comment by svensven** [comment]
It looks like the issue's in the JS, the server is returning an appropriate response:
![image](https://user-images.githubusercontent.com/5736616/94539260-e8aedf80-023c-11eb-9de7-8caa31eacc3c.png)

**Comment by Ban3** [comment]
> It looks like the issue's in the JS

Maybe a new version tagify was deployed recently.

**Comment by svensven** [comment]
This is hard to debug, because there's no non-minified version of the tagify js available.
