### ISSUE TITLE
New image type for packaging info / recycling instructions

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#4286]
We currently have 3 types of images that can be cropped and selected : front of the product, ingredients list, and nutrition facts table.

As more and more products have packaging information and recycling instructions printed on their label in more and more countries, it would be very useful to enable users to upload and select / crop images for recycling instructions.

In addition to "front", "ingredients" and "nutrition", we can add a new "packaging" image type, to hold either packaging info / logos, or if available recycling instructions. (if both are available, they are often close)

**Comment by teolemon** [comment]
fixed
