### ISSUE TITLE
Compute an EcoScore with data from the French Agribalyse food products environmental impacts database

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#4287]
The Agribalyse V3 database has been released as open data. It contains detailed environmental impacts for 2500 food products categories.

In the last few months, we have been adding properties in the categories taxonomy so that we can match our categories with the Agribalyse categories.

This will allow us to compute an EcoScore using the AgriBalyse data, adjusted with other parameters (e.g. the packagings, some labels like the organic label etc.).

The EcoScore will be computed and made available in a similar way than the NutriScore: we will keep all the computation details of every step so that we can explain the score (like we do for the NutriScore), and the score will also be made available to apps as a new product attribute.

**Comment by VaiTon** [comment]
@stephanegigandet @teolemon can we close?
