### ISSUE TITLE
Create an API to indicate which images would need to be taken (again)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#4292]
Create an API to indicate which images would need to be taken (again), with language and field, based on some conditions

```
ingredients_fr_to_refresh
ingredients_pt_to_take
recycling_instructions_to_take
labels_to_take
packager_code_to_take
```

if front_fr=selected and ingredients_fr=empty
if category=meat and packager_codes=to_be_completed
if recycling_instructions=to_be_completed (or a more sophisticated condition required for Eco-Score)

**Comment by aleene** [comment]
If you add this to the json, corresponding to the images, we could use it.
