### ISSUE TITLE
JS cropper is unmaintained, deprecated in favour of jquery-cropper

### ISSUE THREAD

**Issue by svensven** [openfoodfacts/openfoodfacts-server#4296]
https://fengyuanchen.github.io/cropper/ says 
>As of v4.0.0, the core code of Cropper is replaced with Cropper.js. I recommend you to use the jquery-cropper instead of Cropper. 

https://github.com/fengyuanchen/jquery-cropper

https://github.com/fengyuanchen/cropper has been archived, so won't get any more updates.

**Comment by hangy** [comment]
I was sind If we could just ignore the jQuery wrapper and use the native JavaScript version Cropper.js instead. 😀

**Comment by svensven** [comment]
yeah, https://github.com/fengyuanchen/cropperjs

i'm afraid i haven't looked into the JS side much, i don't know how the npm/etc stuff works.
