### ISSUE TITLE
Advanced search download link appears on homepage

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#4314]
Advanced search download link appears on homepage

```→Download results in XLSX or CSV format. Please note that for performance reasons, you can download up to 10.000 results only.```

![image](https://user-images.githubusercontent.com/1689815/95075238-28c80380-0710-11eb-9382-c93632d79ab2.png)

**Comment by waridrox** [comment]
Can you please elaborate more about the problem...

**Comment by teolemon** [comment]
Actually everywhere: 
https://world.openfoodfacts.org/editor/teolemon

**Comment by teolemon** [comment]
Code pointer: https://github.com/openfoodfacts/openfoodfacts-server/blob/522f058ac891b7b8b2b8f3ea091fa6608aa53a6c/templates/search_and_display_products.tt.html#L14
