### ISSUE TITLE
Load packaging codes for Switzerland

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#432]
Swiss codes doesn't seem loaded either on MadeNearMe or OFF

**Comment by teolemon** [comment]
The work has been done to convert them at the same time as the German codes, they are on the server, but for some reason, they don't show up

**Comment by stephanegigandet** [comment]
They don't seem to have coordinates in them:

openfoodfacts-github/openfoodfacts-server/packager-codes# more CH-merge-UTF-8.csv
Bew.-Nr.;"Bur Number";Firmenname;"Company Street";"Company Zipcode";"Company Cit
y/Region";"[TRANSLATE] Category";"Weitere Aktivitäten";"[TRANSLATE] Species";"[T
RANSLATE] Remarks"
74021004;74021004;"Hügli Nährmittel AG";Industriestrasse15;9015;"9015 SG";"CS, R
W";"PP(VI), PP(VIII), PP(IX), PP(X)";;
5124;42650240;"Hungerbühler Walter";Oberrindal57;9604;"9604 SG";RW;PP(IX);;
115;42135665;"Spiess Gustav AG";Musterplatzstr.2;9442;"9442 SG";"CS, RW";"SH(I),
 CP(I), MP(V), PP(VI)";;
2141;40130528;"Bernasconi SA";"via Industria11";6814;"6814 TI";"RW, WM";PP(VI);;
038;71445115;"Nestlé Suisse S.A. Fabrik Rorschach / Zentrallager";Blumenfeldstra
sse15;9403;"9403 SG";"CS, RW";"CP(I), CP(II), CP(III), MM(V), MP(V), PP(IX), PP(
X), PP(XII)";;

**Comment by teolemon** [comment]
https://github.com/openfoodfacts/openfoodfacts-server/blob/5b43a3584b7843716870e2c349c6dc136bcef37f/packager-codes/CH-merge-UTF-8.csv

**Comment by teolemon** [comment]
File ready, with geocoding. Would be great if loaded by Friday.

**Comment by teolemon** [comment]
Fixed by @stephanegigandet
