### ISSUE TITLE
Nutrients stats for categories not computed for the "country" world

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#4321]
This is due to the recent performance improvements to gen_top_tags_per_country.pl

It is because some countries do not have 2 letter country codes, and they overwrite the world stats:

not defined country_code_2:en: en:european-union
not defined country_code_2:en: en:nakhchivan-autonomous-republic
not defined country_code_2:en: en:republika-srpska
not defined country_code_2:en: en:sint-eustatius
not defined country_code_2:en: en:ascension-island
not defined country_code_2:en: en:palestinian-territories
not defined country_code_2:en: en:bonaire
not defined country_code_2:en: en:jan-mayen
not defined country_code_2:en: en:east-germany
not defined country_code_2:en: en:galmudug
not defined country_code_2:en: en:northland-state
not defined country_code_2:en: en:iraqi-kurdistan
not defined country_code_2:en: en:soviet-union
not defined country_code_2:en: en:alderney
not defined country_code_2:en: en:saba
not defined country_code_2:en: en:antarctica

I'll fix it.

**Comment by svensven** [comment]
ah, that wasn't a performance thing, it was providing a default value to clear perl warnings.
