### ISSUE TITLE
Current "front" image no longer visible on product edit page.

### ISSUE THREAD

**Issue by svensven** [openfoodfacts/openfoodfacts-server#4324]
**Describe the bug**
The record has a front image saved,
> ![image](https://user-images.githubusercontent.com/5736616/95207941-5b413180-07e0-11eb-994c-6f60c68b9ebd.png)

but on editing it's not showing up as the "current image" the way the ingredients/etc pictures do:
> ![image](https://user-images.githubusercontent.com/5736616/95208180-ad825280-07e0-11eb-903c-13e35e8d1181.png)

(unless I'm completely imagining that it did that in the past?)

vs

> ![image](https://user-images.githubusercontent.com/5736616/95208263-c3901300-07e0-11eb-8d27-29db6edd0148.png)

**To Reproduce**
https://world.openfoodfacts.org/cgi/product.pl?type=edit&code=0250980001102

**Comment by chk1** [comment]
The nutrition facts image also has this bug, ingredients and packaging images work
