### ISSUE TITLE
Dutch "Pecorino Romano" ingredient disappears

### ISSUE THREAD

**Issue by svensven** [openfoodfacts/openfoodfacts-server#4337]
This record has "pecorino romano kaas" has an ingredient, but the parser just disappears it, and assigns its subingredients to the previous ingredient.
https://nl.openfoodfacts.org/product/23026520/pesto
> ![image](https://user-images.githubusercontent.com/5736616/95582116-114f8a00-0a32-11eb-89fc-4edbbb153ff6.png)

vs
> ![image](https://user-images.githubusercontent.com/5736616/95582163-2fb58580-0a32-11eb-897d-3f1dca5a7d41.png)

https://nl.openfoodfacts.org/cgi/test_ingredients_analysis.pl?ingredients_text=zout%2C+Pecorino+Romano%2C+Pecorino+Romano+kaas%2C+Grana+Padano%2C+Grana+Padano+kaas&type=add&action=process&.submit=Submit+Query

**Comment by stephanegigandet** [comment]
Added some traces to figure out what's going on:

# debug: unknown ingredient matches a phrase to ignore {ingredient => "Pecorino Romano",regexp => "o.a."}

I'm changing the regexp to 'o\.a\.'
