### ISSUE TITLE
Forbid Google Spreadsheet to connect to the API

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#4357]
Google Spreasdheet queries can overload the server (especially if they use the search API).

sample queries:

66.249.92.138 - - [14/Oct/2020:10:35:09 +0200] "GET /cgi/search.pl?action=process&search_terms=Cepe&tagtype_0=categories&tag_contains_0=does_not_contain&tag_0=Cepe&sort_by=unique_scans_n&page_size=20&axis_x=energy&axis_y=products_n&action=display HTTP/1.0" 200 9359 "-" "Mozilla/5.0 (compatible; GoogleDocs; apps-spreadsheets; +http://docs.google.com)" 0/18105
66.249.92.140 - - [14/Oct/2020:10:35:09 +0200] "GET /cgi/search.pl?action=process&search_terms=Bl%C3%A9s&tagtype_0=categories&tag_contains_0=does_not_contain&tag_0=Bl%C3%A9s&sort_by=unique_scans_n&page_size=20&axis_x=energy&axis_y=products_n&action=display HTTP/1.0" 200 9135 "-" "Mozilla/5.0 (compatible; GoogleDocs; apps-spreadsheets; +http://docs.google.com)" 0/21850
66.249.92.138 - - [14/Oct/2020:10:35:09 +0200] "GET /cgi/search.pl?action=process&search_terms=Wrap&tagtype_0=categories&tag_contains_0=does_not_contain&tag_0=Wrap&sort_by=unique_scans_n&page_size=20&axis_x=energy&axis_y=products_n&action=display HTTP/1.0" 200 9141 "-" "Mozilla/5.0 (compatible; GoogleDocs; apps-spreadsheets; +http://docs.google.com)" 0/16930
66.249.92.138 - - [14/Oct/2020:10:35:10 +0200] "GET /cgi/search.pl?action=process&search_terms=Chev&tagtype_0=categories&tag_contains_0=does_not_contain&tag_0=Chev&sort_by=unique_scans_n&page_size=20&axis_x=energy&axis_y=products_n&action=display HTTP/1.0" 200 7483 "-" "Mozilla/5.0 (compatible; GoogleDocs; apps-spreadsheets; +http://docs.google.com)" 0/8316
66.249.92.140 - - [14/Oct/2020:10:35:10 +0200] "GET /cgi/search.pl?action=process&search_terms=Cerf&tagtype_0=categories&tag_contains_0=does_not_contain&tag_0=Cerf&sort_by=unique_scans_n&page_size=20&axis_x=energy&axis_y=products_n&action=display HTTP/1.0" 200 9104 "-" "Mozilla/5.0 (compatible; GoogleDocs; apps-spreadsheets; +http://docs.google.com)" 0/14582
66.249.92.140 - - [14/Oct/2020:10:35:10 +0200] "GET /cgi/search.pl?action=process&search_terms=en:P&tagtype_0=categories&tag_contains_0=does_not_contain&tag_0=en:P&sort_by=unique_scans_n&page_size=20&axis_x=energy&axis_y=products_n&action=display HTTP/1.0" 200 6909 "-" "Mozilla/5.0 (compatible; GoogleDocs; apps-spreadsheets; +http://docs.google.com)" 0/7163
66.249.92.139 - - [14/Oct/2020:10:35:54 +0200] "GET /cgi/search.pl?action=process&search_terms=Eaux&tagtype_0=categories&tag_contains_0=does_not_contain&tag_0=Eaux&sort_by=unique_scans_n&page_size=20&axis_x=energy&axis_y=products_n&action=display HTTP/1.0" 200 8992 "-" "Mozilla/5.0 (compatible; GoogleDocs; apps-spreadsheets; +http://docs.google.com)" 0/14230
66.249.92.145 - - [14/Oct/2020:10:35:54 +0200] "GET /cgi/search.pl?action=process&search_terms=Chou&tagtype_0=categories&tag_contains_0=does_not_contain&tag_0=Chou&sort_by=unique_scans_n&page_size=20&axis_x=energy&axis_y=products_n&action=display HTTP/1.0" 200 9266 "-" "Mozilla/5.0 (compatible; GoogleDocs; apps-spreadsheets; +http://docs.google.com)" 0/14865
66.249.92.139 - - [14/Oct/2020:10:35:54 +0200] "GET /cgi/search.pl?action=process&search_terms=Elan&tagtype_0=categories&tag_contains_0=does_not_contain&tag_0=Elan&sort_by=unique_scans_n&page_size=20&axis_x=energy&axis_y=products_n&action=display HTTP/1.0" 200 8017 "-" "Mozilla/5.0 (compatible; GoogleDocs; apps-spreadsheets; +http://docs.google.com)" 0/8761
66.249.92.146 - - [14/Oct/2020:10:35:55 +0200] "GET /cgi/search.pl?action=process&search_terms=Daim&tagtype_0=categories&tag_contains_0=does_not_contain&tag_0=Daim&sort_by=unique_scans_n&page_size=20&axis_x=energy&axis_y=products_n&action=display HTTP/1.0" 200 8873 "-" "Mozilla/5.0 (compatible; GoogleDocs; apps-spreadsheets; +http://docs.google.com)" 0/12788
66.249.92.142 - - [14/Oct/2020:10:35:55 +0200] "GET /cgi/search.pl?action=process&search_terms=Ales&tagtype_0=categories&tag_contains_0=does_not_contain&tag_0=Ales&sort_by=unique_scans_n&page_size=20&axis_x=energy&axis_y=products_n&action=display HTTP/1.0" 200 8843 "-" "Mozilla/5.0 (compatible; GoogleDocs; apps-spreadsheets; +http://docs.google.com)" 0/27598

**Comment by CharlesNepote** [comment]
Sorry for the late answer but like @hangy , I suggest modifying Ngnix conf. Here is an example on how to limit bot rates. I added lots of comments to let you understand, with the help of @cquest . There's a dry-run mode but I'm not sure how it works. What's interesting with this config file is that smart bots are slowing themselves due to 429 status code.

```(conf)
# Inspired from: https://gist.github.com/supairish/2951524
http {


    # ### create limit rates for a defined zone
    # * zone identifies the name of the zone ("bots") and its size in megabytes
    # * rate=30r/m is the rate in requests per seconds or minutes
    # * It is possible to create many zones and apply these zones on different locations
    map $http_user_agent $limit_bots {
        default '';
        ~*(GoogleDocs|google|bing|yandex|msnbot) $binary_remote_addr;
    }
    limit_req_zone $limit_bots zone=bots:10m rate=60r/m;

    server {
        location / {

            # ### apply limit_req_zone of zone "bots" to all
            # "burst" is like a leaky bucket:
            # * rate=Xr/s is the speed of the leak
            # * "burst" is the size of the bucket
            # * when the bucket is full (burst=50 requests), Ngninx answers to current requests but with a 429 Too Many Requests response status code
            #   https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429
            # * "Googlebot reduces your site's crawling rate when it encounters a significant number of URLs with 500, 503, or 429 HTTP result codes"
            #   https://developers.google.com/search/docs/guides/reduce-crawl-rate#reduce-with-search-console
            # * eventually fail2ban can ban IPs for a few moment if there's too much 429
            # * Christian Quest also advice "nodelay" (but I don't really understand why)
            limit_req zone=bots burst=50 nodelay;
            limit_req_status 429;   # 503 by defaults

            # Allows the dry run mode (on|off).
            #   https://nginx.org/en/docs/http/ngx_http_limit_req_module.html
            #   To be used with limit_req_log_level?
            limit_req_dry_run off;

        }
    }
}
```
