### ISSUE TITLE
0% in 65.0% detected as an allergen

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#4365]
https://world.openfoodfacts.org/product/7613036049368/fitnesse-granola-nestle

````````
'Whole Grain Oat Flakes (65.0%)'
````````
is displayed
````````
'Whole Grain Oat Flakes (65.<span class="allergen">0%</span>)'

**Comment by hangy** [comment]
> 'Whole Grain Oat Flakes (65.0%)'
> is displayed
> 'Whole Grain Oat Flakes (65.0%)'

It's the same?

**Comment by stephanegigandet** [comment]
> It's the same?

I forgot that github would not display the tags, I updated the bug description.
