### ISSUE TITLE
Typo corrected on wiki but still present "select multipe pictures"

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#437]
With Chrome, Firefox and Safari, you can select multipe pictures (product, ingredients, nutrition facts etc.) by clicking them while holding the Ctrl key pressed to add them all in one shot.

http://world.openfoodfacts.org/cgi/product.pl?type=edit&code=3302741820105

**Comment by teolemon** [comment]
Can't find in source code @stephanegigandet 
Uncommited change ?

**Comment by teolemon** [comment]
@stephanegigandet seems you just fixed it in translations

**Comment by hangy** [comment]
LGTM
