### ISSUE TITLE
Add photographer and informer to the sidebar option

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#439]
### What
In addition to 
- Products you added or edited (http://world.openfoodfacts.org/contributor/teolemon)
- Products you added that need to be completed (http://world.openfoodfacts.org/contributor/teolemon/state/to-be-completed)

Add
- Products you photographed but are not complete (photographers)
- Products you added info to  but are not complete (informers)

### Part of 
- #5516

**Comment by VaiTon** [comment]
The photo part has been done.

Isn't the second point the same as "edited by"?

**Comment by teolemon** [comment]
This has been fixed by the redesign, on the topbar @VaiTon @teolemon
