### ISSUE TITLE
Search - Searching with world-en redirects to the wrong page

### ISSUE THREAD

**Issue by UlricusR** [openfoodfacts/openfoodfacts-server#4396]
### What
- The following links work (https://world-de.openfoodfacts.org/cgi/search.pl?action=process&search_terms=Mehl&sort_by=unique_scans_n&json=true, https://world-fr.openfoodfacts.org/cgi/search.pl?action=process&search_terms=Mehl&sort_by=unique_scans_n&json=true)
- but not this one (https://world-en.openfoodfacts.org/cgi/search.pl?action=process&search_terms=Mehl&sort_by=unique_scans_n&json=true). 
- The only thing changed was "-en" instead of "-fr" or "-de".

### Part of
- #5492

**Comment by stephanegigandet** [comment]
world-en redirects to world, but the /cgi/search.pl part is removed from the redirect.

**Comment by stephanegigandet** [comment]
This now works, closing.
