### ISSUE TITLE
Image Cropping tool gives me wrong image

### ISSUE THREAD

**Issue by john-hu** [openfoodfacts/openfoodfacts-server#440]
STR:
1. Open URL http://tw.openfoodfacts.org/product/4710085104130/%E4%BC%AF%E6%9C%97%E5%92%96%E5%95%A1%E8%97%8D%E5%B1%B1%E9%A2%A8%E5%91%B3-%E4%BC%AF%E6%9C%97%E5%92%96%E5%95%A1
2. Edit the product
3. Choose the back image of bottle 
4. Rotate the image left
5. crop the image like the attached image
6. press "Validate and/or resize image"  <<=== NG here.

The image should be correct. But it gives me partial image.

![capture](https://cloud.githubusercontent.com/assets/6179015/18083658/9f559872-6ed6-11e6-9df0-207ded08cb58.PNG)

**Comment by john-hu** [comment]
![capture2](https://cloud.githubusercontent.com/assets/6179015/18083937/ebbbaa48-6ed7-11e6-9fd2-ad05a8681f28.PNG)

**Comment by john-hu** [comment]
Environment: Windows 10 with Firefox 47.0.1 Browser.

**Comment by aleksejrs** [comment]
I've seen this twice since this bug report on GNU/Linux with Firefox 49.0b8.

**Comment by hangy** [comment]
I'm closing this, as the issue is stale and we upgraded to a different major version of [cropper](https://github.com/fengyuanchen/cropper) since it was opened. Please feel free to reopen if this is still an issue for you.
