### ISSUE TITLE
Country Search Is not working properly #4411

### ISSUE THREAD

**Issue by prashantpatel0** [openfoodfacts/openfoodfacts-server#4411]
**Country  Search Is not working properly**
When we type any initials of country it does not show suggestions and if we write in lowercase then also it fails to recognize the country.

**To Reproduce**
1. Go to 'Country Search'
2. Click on 'Country'
3. Type 'india'

**Expected behavior**
If we start writing any country's name then it should start giving name of country or any name within the search list.

**Screenshots**

[OpenFoodFacts.pdf](https://github.com/openfoodfacts/openfoodfacts-server/files/5432816/OpenFoodFacts.pdf)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version any

**Comment by svensven** [comment]
i think i fixed this the other day, but it may not have gone live yet. #4388

**Comment by stephanegigandet** [comment]
@svensven 's fix is now deployed. The page may need to be refreshed.
