### ISSUE TITLE
Create an origins taxonomy, populate it and use it

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#4427]
We currently use the countries taxonomy to parse origins of ingredients. It works well for countries, but origins are sometimes defined with another granularity, such as a bigger region like "South America", or a smaller region like "Normandy".

This bug is to track efforts to define this taxonomy (e.g. what to include (regions, states, fishing zones..) and what not to include in it (e.g. smaller regions, cities)), to implement a minimal version of it with a few extra entries so that we can test its integration in features such as ingredients analysis, and to see how we can populate it automatically from sources such as Wikidata.

**Comment by svensven** [comment]
it would be useful for providing tagify suggestions to the not-just-country location fields on the edit form too.
