### ISSUE TITLE
Travis tests are failing. Do we need them or the Github actions test the same things?

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#4438]
e.g. https://github.com/openfoodfacts/openfoodfacts-server/pull/4433

The Travis tests are failing for all PRs. I still don't know if they are actually useful at all, or if all the things they test are already tested with the Github Actions PR tests.

If not, can we just remove them?

``````
> product-opener@1.0.0 build /home/travis/build/openfoodfacts/openfoodfacts-server
> gulp
/home/travis/build/openfoodfacts/openfoodfacts-server/node_modules/node-sass/lib/binding.js:15
      throw new Error(errors.missingBinary());
      ^
Error: Missing binding /home/travis/build/openfoodfacts/openfoodfacts-server/node_modules/node-sass/vendor/linux-x64-83/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 14.x
Found bindings for the following environments:
  - Linux 64-bit with Node.js 12.x
This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.

**Comment by teolemon** [comment]
this specific case is related to https://github.com/openfoodfacts/openfoodfacts-server/issues/4434 
but @stephanegigandet 's question is still valid

**Comment by VaiTon** [comment]
I don't think travis is needed anymore.

**Comment by svensven** [comment]
i'm new, and don't know the history of how the various workflows came to be, or if there's a benefit to one over the other, but they do seem to duplicate each other.
