### ISSUE TITLE
"Evolution of the number of products" stopped updating?

### ISSUE THREAD

**Issue by aleksejrs** [openfoodfacts/openfoodfacts-server#444]
http://ru.openfoodfacts.org/products
last update Aug 26th: 578 total, 190 complete.
  real on 31st 08 UTC: 618 total, 203 complete.
http://world.openfoodfacts.org/products
last update Aug 27th: 91855 total, 47636 complete.
  real on 31st 08 UTC: 94767 total, 47721 complete.

**Comment by aleksejrs** [comment]
Maybe related: http://ru.openfoodfacts.org/category/breads continually says “12 products”, although there are more complete products in that category.

**Comment by aleksejrs** [comment]
Still not updated.

**Comment by stephanegigandet** [comment]
The batch scripts have been moved to a new directory and one of them was not running, fixing it.

**Comment by stephanegigandet** [comment]
Fixed.
