### ISSUE TITLE
Edit dates not available in the json.

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#445]
This product (http://fr.openfoodfacts.org/produit/3175460030083/echalote-ciboulette-40-mg-boursin) has been extensively edit. However these edit-dates do not appear in the corresponding json (http://world.openfoodfacts.org/api/v0/product/3175460030083.json).

**Comment by hangy** [comment]
What do you think about providing this in a subresource? Including all edits in every API request sounds pretty wasteful (because most consumers won't display them in a lot of cases). We could add a subresource, though. For example: http://world.productopener.org/api/v2/products/2000000000001/edits

**Comment by aleene** [comment]
too old
