### ISSUE TITLE
Products are always the same on the home page

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#4464]
See: https://world.openfoodfacts.org/

Stéphane [replied](https://openfoodfacts.slack.com/archives/C02KVRT2C/p1604394125231600?thread_ts=1604247289.208700&cid=C02KVRT2C):
> we have the dynamic view, it's an issue with the sort order / completeness of products
> it's related to the new packaging image / fields, I haven't had time to fix it yet

**Comment by CharlesNepote** [comment]
Fixed?

Seems to be. I'll close in a few days if nobody answers.

**Comment by stephanegigandet** [comment]
the sort by completeness has been removed when we deployed personal search
