### ISSUE TITLE
Fix upload dialog box that shows up unexpectedly

### ISSUE THREAD

**Issue by kyzh** [openfoodfacts/openfoodfacts-server#45]
Some user report being presented with a upload dialog box when clicking on different part of the website.
I personally get one when clicking on the numbers available on the points page http://world.openfoodfacts.org/points

[Previous discussion](https://openfoodfacts.slack.com/archives/roadmap/p1422397661000065) talked about " the <input id="imgupload_search" ..> is in a huge 1760x408 box when javascript is disabled".
Also "weird css rules [being] applied"
```
border-width: 0px 0px 100px 200px;
opacity: 0;
transform: translate(-300px, 0px) scale(4);
.fileinput-button {
 position: relative;
 overflow: hidden;
}
.fileinput-button input {
 position: absolute;
 top: 0;
 right: 0;
 margin: 0;
 border: solid transparent;
 border-width: 0 0 100px 200px;
 opacity: 0;
 filter: alpha(opacity=0);
 -moz-transform: translate(-300px, 0) scale(4);
 direction: ltr;
 cursor: pointer;
} 
```
And finally the version of "https://github.com/blueimp/jQuery-File-Upload" being old.

**Comment by stephanegigandet** [comment]
Fixed during the Foundation redesign I believe.
