### ISSUE TITLE
No nutrient autocomplete with Russian language selected

### ISSUE THREAD

**Issue by aleksejrs** [openfoodfacts/openfoodfacts-server#451]
There is no autocompletion with Russian language selected (neither Russian, nor English nutrient names). If I switch from `ru.` to `ru-en.`, I get autocompletion of English text.

**Comment by hangy** [comment]
Is this okay now? It seems to work for most nutrients on ru.openfoodfacts.org now, as far as I can tell.

**Comment by hangy** [comment]
This is fine now, as long as nutrients have been translated already.
