### ISSUE TITLE
Result graphs generated from advance search no longer work correctly

### ISSUE THREAD

**Issue by TaciteOFF** [openfoodfacts/openfoodfacts-server#4519]
**Describe the bug**
Products appearing in graphs can no longer be clicked on to access product pages;

**To Reproduce**
https://fr.openfoodfacts.org/cgi/search.pl?action=process&tagtype_0=categories&tag_contains_0=contains&tag_0=Glaces&sort_by=unique_scans_n&page_size=20&axis_x=energy-kcal&axis_y=sugars&series_nutrition_grades=on&graph=1

Tested on MacOS 10.15.7 with Safari 14.0.1 and Chrome 89.0.4326.0.

**Comment by stephanegigandet** [comment]
Seems to be this option: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/tooltip/stickoncontact/
