### ISSUE TITLE
Moving this product to OPF

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#4525]
Tried to move this product to OPF but got a **software error**: `Undefined subroutine &ProductOpener::Products::display_error called at /srv/off/lib/ProductOpener/Products.pm line 809`.

https://world.openfoodfacts.org/cgi/product.pl?type=edit&code=40235974

But moving [this product](https://world.openproductsfacts.org/product/8717163835623/liquide-vaisselle-ecolabel-neutral) worked. Maybe a barcode issue?

**Comment by Ban3** [comment]
#4441 The actual error is invalid barcode, the undefined subroutine is just missing import for the error display.

**Comment by stephanegigandet** [comment]
I'm guessing this has been fixed through @Ban3 's fix of #4441. I just moved the product to OPF, it worked.

**Comment by stephanegigandet** [comment]
https://world.openproductsfacts.org/product/40235974
