### ISSUE TITLE
API does not accep %DV

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#4527]
**Describe the bug**
I try to write values in %DV units (tried as percent and fraction). The API seems to convert any value specified as %DV to grams. It does take into account the `nutrition_data_per=serving`, indication to accept it per 100g or per serving.

**To Reproduce**
https://ssl-api.openfoodfacts.org/cgi/product_jqm2.pl?code=0041770332809lang=en&nutriment_vitamin-c=0.09&nutriment_vitamin-c_unit=%25DV&nutrition_data_per=serving&no_nutrition_data

It should accept %DV as a percentage (0-100) and convert to a value per serving AND a value per 100g. The specification of `nutrition_data_per=serving` should not matter (a percentage is a percentage).

**Comment by stephanegigandet** [comment]
It works if you set the unit to "% DV" in fact (with a space).

https://world.openfoodfacts.dev/cgi/product_jqm2.pl?code=0041770332809lang=en&nutriment_vitamin-c=0.09&nutriment_vitamin-c_unit=%25%20DV&nutrition_data_per=serving&no_nutrition_data

**Comment by aleene** [comment]
Confirm, it works as required.
