### ISSUE TITLE
Pressing "Why it matters" when editing does nothing

### ISSUE THREAD

**Issue by josve05a** [openfoodfacts/openfoodfacts-server#453]
When editing a product, on "Information and data must come from the product package and label (and not from other sites or the manufacturer's site), and you must have taken the pictures yourself" pressing the link "Why it matters" only reloads the page instead of giving any info on "why it matters".

**Comment by hangy** [comment]
Empty URL in the translation http://en.wiki.openfoodfacts.org/Translations_-_Web_site_interface (warning_3rd_party_content).

**Comment by teolemon** [comment]
Probably move the content from the uservoice to the wiki, and get translations.

**Comment by teolemon** [comment]
Is it still the case with the new translation system ?

**Comment by teolemon** [comment]
Fixed. Will be deployed soon.
