### ISSUE TITLE
Take varying spacing of the percent sign into account

### ISSUE THREAD

**Issue by aleksejrs** [openfoodfacts/openfoodfacts-server#454]
https://en.wikipedia.org/wiki/Percent_sign#Spacing

https://ru.wikipedia.org/wiki/Знак_процента##.D0.9F.D1.80.D0.B0.D0.B2.D0.B8.D0.BB.D0.B0_.D0.BD.D0.B0.D0.B1.D0.BE.D1.80.D0.B0 says that in Russian, % must be spaced with a non-breaking space since 1982, although that's not done everywhere.

I guess "%" is almost never used in any other context, so:
1. "`\d %`", "`\d&nbsp;%`" and "`\d%`" should be considered synonyms at least in categories.
2. "`\d %`" should be rendered as "`\d&nbsp;%`" at least in some languages.

**Comment by hangy** [comment]
We could maybe do it with CLDR without having to maintain everything manually. CLDR knows the different locale specific formats, so [CLDR::Number::Format::Percent](http://search.cpan.org/~patch/CLDR-Number-0.19/lib/CLDR/Number/Format/Percent.pm) could be used - at least for formatting the output.

Based on CLDR 29, the following distinct formats are known:

Format	|	Count
-----------|-------------
#,##,##0 %	|	1
#,##,##0%	|	9
#,##0 %	|	25
#,##0%	|	639
% #,##0	|	1
%#,##0	|	1

Based on it's parent package, [CLDR::Number](http://search.cpan.org/~patch/CLDR-Number-0.19/lib/CLDR/Number.pm), we could also remove `group_sign` and normalize `decimal_sign` for parsing the percent based on the text's locale.

**Comment by hangy** [comment]
I have most of this implemented by normalizing percentage signs according to the Unicode CLDR when canonicalizing the tags (categories etc.) in commit 457635acec1c021fda5316559dc40946021ad5be, and created [a PR](https://bitbucket.org/openfoodfacts/product-opener/pull-requests/56) for review.

**Comment by hangy** [comment]
PR merged 308956566cbeb48288f703f826d1dad2a8f040d6
