### ISSUE TITLE
Email address with space

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#4549]
It's possible to create a new user account which email address contains spaces.
Eg. `bibi @fricotin.org`

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/101169982-0a15b880-363e-11eb-8479-f2a0482ae655.png)

**Comment by hangy** [comment]
Also check why [`Email::Valid`](https://github.com/openfoodfacts/openfoodfacts-server/blob/d2304f5887e2aaf33899d878f09afe90cee99ba6/cpanfile#L37) doesn't catch this. A client-side check is nice, but it should be validated server-side, too.

**Comment by AghaSaad04** [comment]
Hi,
I want to work on this issue. Can anyone give me some directions how to reproduce the error? Thanks.

**Comment by mairna** [comment]
Hi! I found the issue and investigated how this works. Email::Valid however modifies the email to no longer contain spaces if it previously did. Here is an example of how this works (referenced from https://metacpan.org/pod/Email::Valid):

![image](https://user-images.githubusercontent.com/45151776/114342541-fddcc300-9b29-11eb-902d-edb78ab05a28.png)

As you can see, it changes the email accordingly. It does not need to provide an error then. For reference, the exact code being discussed is located in lib -> ProductOpener -> Users.pm in the function in check_user_form($$$), starting at line 531. Let me know if you have any more comments or concerns, but I think we can close the bug!

**Comment by akash5100** [comment]
I'm new to open source and want to contribute can I help with something.

**Comment by alexgarel** [comment]
@mairna I can't reproduce your snippet, in the docker for dev I only get a Boolean value.

If the address contains a space however it is not considered valid.

**Comment by aadarsh-ram** [comment]
@teolemon @alexgarel I will be working on this issue. I have created PR #6578 which will close this issue.
