### ISSUE TITLE
Docker environment not starting, related to ecoscore

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#4591]
Reported by @leventgunay : 

Log::Any::Proxy=HASH(0x563476144e58)[Sun Dec 06 10:59:36.205749 2020] [perl:error] [pid 24:tid 140342709499008] 30 unrecognized materials in CSV /mnt/podata/ecoscore/data/Eco_score_Calculateur.csv.11 at /opt/product-opener/lib/ProductOpener/Ecoscore.pm line 285, <$io> line 31.\nCompilation failed in require at (eval 2) line 1.\n
[Sun Dec 06 10:59:36.205917 2020] [perl:error] [pid 24:tid 140342709499008] Can't load Perl file: /opt/product-opener/lib/startup_apache2.pl for server productopener.localhost:0, exiting...

12 h 02
could anyone help me addressing this issue? i try to run start_dev but failing while processing eco score data.
12 h 02
[3688] /opt/product-opener/lib/ProductOpener/Ecoscore.pm 264 ProductOpener.Ecoscore {material => 'PS',material_id => 'fr:PS'} ecoscore material does not exist in taxonomy

**Comment by hangy** [comment]
I get errors like
```
[7067] /opt/product-opener/lib/ProductOpener/Ecoscore.pm 178 ProductOpener.Ecoscore {origin => 'Zimbabwe',origin_id => 'en:Zimbabwe'} ecoscore origin does not exist in taxonomy
```
`/mnt/podata/taxonomies/origins.result.sto` does exist

**Comment by stephanegigandet** [comment]
Thanks @hangy. I think I found the issue, it's because the docker/backend-dev/conf/Config.pm file does not specify to load the new taxonomies. It's very much outdated in fact. Maybe we could try to use Config_off.pm instead, and just update the few lines that need to be updated (like removing the Google Analytics code and changing the admin)
