### ISSUE TITLE
Add Sin TACC, gluten-free label in Argentina

### ISSUE THREAD

**Issue by mrmd8** [openfoodfacts/openfoodfacts-server#4600]
Hi! I've been using OpenFoodFacts for a few weeks now in Argentina. I would like start helping to add different labels and ingredients from Argentina

I've created label [es:sin-tacc](https://ar.openfoodfacts.org/etiqueta/sin-tacc) for "Sin TACC" certification label. A gluten-free label meaning "Sin Trigo, Avena, Cebada, Centeno" (No Wheat, Oats, Barley, Rye)

It's probably the most common label in Argentina, it's present in a lot of products and more common than the "Gluten free" standard logo

- [Wikidata Q101542317](https://www.wikidata.org/wiki/Q101542317)
- [Logo](https://wiki.openfoodfacts.org/File:Sin-tacc.86x90.png)

I hope I uploaded and created everything the right way, sorry if I made any mistakes
Thanks a lot!

**Comment by teolemon** [comment]
Hello @mrmd8 and thank you for the research :-) 

You can add it in 
https://github.com/openfoodfacts/openfoodfacts-server/tree/master/html/images/lang/es/labels/ using the instructions on : https://wiki.openfoodfacts.org/Global_packaging_taxonomy_logos

And in there as well: 
https://github.com/openfoodfacts/openfoodfacts-server/blob/master/taxonomies/labels.txt

You can join the #argentina channel on the slack chat room: you can self invite at https://slack.openfoodfacts.org

**Comment by mrmd8** [comment]
@teolemon Thanks! I have created pr #4668
