### ISSUE TITLE
Add "stuffed" in ingredients_processing.txt

### ISSUE THREAD

**Issue by Chri92000** [openfoodfacts/openfoodfacts-server#4615]
The tool doesn't recognizes the french expression "tomates farcies", which means "stuffed tomatoes".
Actually, https://github.com/openfoodfacts/openfoodfacts-server/blob/master/taxonomies/ingredients_processing.txt doesn't contains fr:farcie, farci, farcies, farcis en:stuffed.

May be somebody could add it?

Number of products impacted: 658 products for french word "farci"
Example:  3248830000914(EAN / EAN-13)

**Comment by aleene** [comment]
I'll add it to the ingredients. Stuffed is not really a process on a (single) ingredient. It is more a compound ingredient, which contains multiple other ingredients.

So I'll add it to the ingredients.

Thanks.
