### ISSUE TITLE
XML Error in Individual product API

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#463]
![image](https://cloud.githubusercontent.com/assets/1689815/18417170/c9c0a150-7828-11e6-9ea2-c99cf1dd77d7.png)
http://world.openfoodfacts.org/api/v0/product/3263851286512.xml
This page contains the following errors:

error on line 156 at column 30: Namespace prefix en for french on languages is not defined
Below is a rendering of the page up to the first error.

san leader mer la vierge conserve produit extra huile arete sardine olive poisson en de filet price leader-price en:canned-foods en:seafood en:fishes en:canned-fishes en:sardines en:canned-sardines en:fish-fillets en:sardines-in-oil en:sardine-fillets en:sardines-in-olive-oil fr:filets-de-sardines-a-l-huile-d-olive en:canned-foods en:seafood en:fishes en:canned-fishes en:sardines en:canned-sardines en:fish-fillets en:sardines-in-oil en:sardine-fillets en:sardines-in-olive-oil fr:filets-de-sardines-a-l-huile-d-olive en:canned-foods en:seafood en:fishes en:canned-fishes en:sardines en:canned-sardines en:fish-fillets en:sardines-in-oil en:sardine-fillets en:sardines-in-olive-oil fr:filets-de-sardines-a-l-huile-d-olive en:canned-foods en:seafood en:fishes en:canned-fishes en:sardines en:canned-sardines en:fish-fillets en:sardines-in-oil en:sardine-fillets en:sardines-in-olive-oil fr:filets-de-sardines-a-l-huile-d-olive douarnenez-finistere-france code-13 3263851286512 326385128651x 32638512865xx 3263851286xxx 326385128xxxx 32638512xxxxx 3263851xxxxxx 326385xxxxxxx 32638xxxxxxxx 3263xxxxxxxxx 326xxxxxxxxxx 32xxxxxxxxxxx 3xxxxxxxxxxxx jacob80 phoenix en:france en:france hommedanslalune jacob80 hommedanslalune jacob80 phoenix fr-29-046-532-ec 2012-11-17 2012-11 2012 hommedanslalune hommedanslalune jacob80 Filets de sardines 80 % huile d'olive vierge extra sel. filets-de-sardines 80 huile-d-olive-vierge-extra sel 3 1-10 filets-de-sardines huile-d-olive-vierge-extra sel fr:Sans arêtes fr:Sans arêtes fr:sans-aretes fr:sans-aretes

**Comment by teolemon** [comment]
@stephanegigandet @hangy This is blocking the new Ubuntu release.

**Comment by teolemon** [comment]
poke @nymerea

**Comment by stephanegigandet** [comment]
The easiest would be to remove the languages field before doing the xml conversion. I'll do that when I get back.

**Comment by stephanegigandet** [comment]
Fixed by removing the languages field in the XML export.
