### ISSUE TITLE
Origin display bug for the Eco-Score explanation

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#4663]
Origin display bug for the Eco-Score
![image](https://user-images.githubusercontent.com/1689815/103016276-1bb5f600-4542-11eb-9c3b-0a57afe33691.png)

https://world.openfoodfacts.org/product/3230890849541/cordons-issus-de-volaille-fermiere-bio-maitre-coq

**Comment by teolemon** [comment]
https://world.openfoodfacts.org/product/3230890849541/cordons-issus-de-volaille-fermiere-bio-maitre-coq?rev=22

`template error: undef error - Illegal division by zero at /srv/off/templates/ecoscore_details.tt.html line 42.`

**Comment by stephanegigandet** [comment]
The issues reported happen when the Eco-Score data structure changes (it's still in flux) and the products have not been updated yet. Fixed.
