### ISSUE TITLE
Add a platform promo and calls to action in the Eco-Score explanation

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#4664]
Add a platform promo and calls to action (with deep links to the right part of the edit form) in the Eco-Score explanation so that users and producers both have an easy way forward.

![image](https://user-images.githubusercontent.com/1689815/103017038-4b193280-4543-11eb-8de0-713572e1077a.png)

**Comment by VaiTon** [comment]
I really like the font though :P

**Comment by teolemon** [comment]
it's Google Sans @VaiTon

**Comment by stephanegigandet** [comment]
Added some prompts.

**Comment by teolemon** [comment]
Fixed for me. Thanks
