### ISSUE TITLE
Cropping seems broken

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#4678]
Cropping seems broken. I can reliably recreate the issue in the production Android app that used to be working like a charm.
Open Food Facts Android 3.6.1
https://photos.app.goo.gl/9EvngfoQ18idAS3o8

**Comment by teolemon** [comment]
I've created a client-side issue, but I now believe the issue lies server side: https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/3635
Has there been any recent deployment related to cropping ?

**Comment by teolemon** [comment]
Also reported by @TaciteOFF : "Quand tu coches la case pour afficher les images en plus petite résolution"
When the small resolution checkbox is ticked.

**Comment by stephanegigandet** [comment]
# The new product_multilingual.pl form will set $coordinates_image_size to "full"
# the current Android app will not send it, and it will send coordinates related to the ".400" image
# that has a max width and height of 400 pixels
my $coordinates_image_size = param('coordinates_image_size') || $crop_size;

-> is that still correct for the Android app?

**Comment by stephanegigandet** [comment]
Found the issue, fixing.
