### ISSUE TITLE
MongoDB errors: "couldn't get header response to throw out", "can't get db response, not connected"

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#468]
After migrating to the new OFF server, we are getting a lot of errors like this:

Software error:

couldn't get header response to throw out at /usr/lib/x86_64-linux-gnu/perl5/5.20/MongoDB/Collection.pm line 562.
For help, please send mail to the webmaster (contact@openfoodfacts.org), giving this error message and the time and date of the error.

**Comment by stephanegigandet** [comment]
http://search.cpan.org/~flora/MongoDB-0.01/lib/MongoDB/Connection.pm

Changing:

$connection = MongoDB::Connection->new("host" => "localhost:27017");

to

$connection = MongoDB::Connection->new("host" => "localhost:27017", "auto_reconnect"=>1);

**Comment by stephanegigandet** [comment]
the auto_reconnect seems to be an old parameter which does not exist anymore : https://metacpan.org/pod/MongoDB::MongoClient

**Comment by stephanegigandet** [comment]
we could try a newer version of the MongoDB perl module:

[10:47]  
(no description)
       M/MO/MONGODB/MongoDB-v1.4.5.tar.gz
       /usr/lib/x86_64-linux-gnu/perl5/5.20/MongoDB.pm
       Installed: v0.705.0.0
       CPAN:      v1.4.5  Not up to date
       MongoDB Inc (MONGODB)
       mongodb@cpan.org

[10:47]  
hopefully it won't break everything

[10:48]  
according to https://docs.mongodb.com/ecosystem/drivers/perl/ the version we are using is very old and does not support mongo 3.2

**Comment by stephanegigandet** [comment]
Updated the MongoDB perl driver from v0.705.0.0 to v1.4.5. There were a few changes (syntax to connect to the DB, and format of results of aggregate queries). There may be other I haven't noticed.

Hopefully it will solve or alleviate the db connection errors.

**Comment by hangy** [comment]
I don't think these happen any more. If they do, please reopen.
