### ISSUE TITLE
Ecoscore data: no way to know if "packaging" or "origins_of_ingredients" scores are provided or not

### ISSUE THREAD

**Issue by FredJul** [openfoodfacts/openfoodfacts-server#4686]
**Describe the bug**
While playing a bit with the ongoing ecoscore API during my PR (https://github.com/openfoodfacts/openfoodfacts-dart/pull/63), I noticed that there is no way for an app to know how to correctly display the "packaging" and "origins_of_ingredients" score if this one is not known.

**To Reproduce**
For instance, we can notice that values are not exact (it's hard to believe that 0 is a correct score for a plastic bottle) if we look at this product:
https://world.openfoodfacts.org/api/v0/product/5000112548167?fields=product_name,ecoscore_data,ecoscore_alpha

**Expected behavior**
I suggest to simply not return these fields when there is no information. Another solution would be to add a known/unknown status but I believe this is a bit more complex.

**Comment by teolemon** [comment]
Related: 
https://github.com/openfoodfacts/openfoodfacts-server/issues/4663 (Origin display bug for the Eco-Score explanation)
https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/3644 (adds prompt for missing info related to Eco-Score (solves issue 3624) )

**Comment by stephanegigandet** [comment]
> (it's hard to believe that 0 is a correct score for a plastic bottle)

In fact the Eco-Score formula is quite complex, and for packaging material, the score indicates the "circularity" of the material. 0 is the worse score. (not a recycled material, not recycled). Other types of plastic have better scores.

**Comment by stephanegigandet** [comment]
@FredJul : there are now more warning fields in ecoscore_data, that we use to display the details of the Eco-Score on the OFF site.
Can we close this bug?

**Comment by FredJul** [comment]
I guess it clearly does the job, thanks!
