### ISSUE TITLE
All glass bottles should be recyclable by default

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#4698]
### What
All glass bottles should probably be recyclable by default.

### Screenshot
![image](https://user-images.githubusercontent.com/1689815/103459044-90d8b680-4d0c-11eb-99ad-c95186cacec3.png)

### Part of 
- #6374

**Comment by Fienne** [comment]
@stephanegigandet can I work on this

**Comment by Fienne** [comment]
@teolemon should this change be on the frontend or the server?
