### ISSUE TITLE
ecoscore_grade not present on product json

### ISSUE THREAD

**Issue by VaiTon** [openfoodfacts/openfoodfacts-server#4699]
1. [Open the url](https://ssl-api.openfoodfacts.org/api/v0/product/20237790.json?fields=product_name%2Cgeneric_name%2Cimage_small_url%2Cimage_front_url%2Cimage_ingredients_url%2Cimage_nutrition_url%2Cimage_packaging_url%2Cimage_url%2Cselected_images%2Clanguages_codes%2Cvitamins_tags%2Cminerals_tags%2Camino_acids_tags%2Cother_nutritional_substances_tags%2Curl%2Ccode%2Ctraces_tags%2Cingredients_that_may_be_from_palm_oil_tags%2Cadditives_tags%2Callergens_hierarchy%2Cmanufacturing_places%2Cnutriments%2Cingredients_from_palm_oil_tags%2Cbrands_tags%2Ctraces%2Ccategories_tags%2Cingredients_text%2Cingredients_from_or_that_may_be_from_palm_oil_n%2Cserving_size%2Callergens_tags%2Callergens%2Corigins%2Cstores%2Cnutrition_grade_fr%2Cnutrition_grades_tags%2Cnutrient_levels%2Cecoscore_grade%2Ccountries%2Ccountries_tags%2Cbrands%2Cpackaging%2Clabels_tags%2Clabels_hierarchy%2Ccities_tags%2Cquantity%2Cingredients_from_palm_oil_n%2Clink%2Cemb_codes_tags%2Cstates_tags%2Ccreator%2Ccreated_t%2Clast_modified_t%2Clast_modified_by%2Ceditors_tags%2Cnova_groups%2Clang%2Cpurchase_places%2Cnutrition_data_per%2Cno_nutrition_data%2Cother%2Cother_information%2Cconservation_conditions%2Crecycling_instructions_to_discard%2Crecycling_instructions_to_recycle%2Cwarning%2Ccustomer_service%2Cenvironment_infocard%2Cenvironment_impact_level_tags%2Cingredients_analysis_tags%2Cingredients%2Cproduct_name_en%2Cgeneric_name_en%2Cingredients_text_en%2Cother_information_en%2Cconservation_conditions_en%2Crecycling_instructions_to_discard_en%2Crecycling_instructions_to_recycle_en%2Cwarning_en%2Cattribute_groups_en%2Ccustomer_service_en%2Cimage_front_url_en%2Cimage_ingredients_url_en%2Cimage_nutrition_url_en%2Cimage_packaging_url_en)
2. The field `ecoscore_grade` is missing

**Comment by teolemon** [comment]
We still need the alpha parameter for a few more days @VaiTon

**Comment by stephanegigandet** [comment]
ecoscore is now deployed for all.
