### ISSUE TITLE
The Android Application badge should be localized

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#47]
fr >> https://developer.android.com/images/brand/fr_app_rgb_wo_45.png
es >> https://developer.android.com/images/brand/es_app_rgb_wo_45.png
……
https://developer.android.com/distribute/tools/promote/badges.html

**Comment by hangy** [comment]
https://github.com/openfoodfacts/openfoodfacts-server/blob/9f7e5d146f2d76c7a826353b38248c35edd8c4fb/po/common/common.pot#L154-L158
