### ISSUE TITLE
Remove 3 ASC sublabels from labels taxonomy

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#4700]
Remove 3 ASC sublabels from labels taxonomy. We automated extraction to the packager code field.
https://world.openfoodfacts.org/label/responsible-aquaculture-asc
```
Belongs to:

Responsible aquaculture

Contains:

ASC C00386
fr:ASC C 00026
fr:ASC C 00473
```

**Comment by benbenben2** [comment]
Seems to be fixed already @teolemon
