### ISSUE TITLE
Illegal division by zero at ecoscore_details.tt.html line 42.

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#4701]
`template error: undef error - Illegal division by zero at /srv/off/templates/ecoscore_details.tt.html line 42.`

![image](https://user-images.githubusercontent.com/1689815/103476966-6fce9f00-4dba-11eb-87f1-bffc3e2bdbcb.png)

https://github.com/openfoodfacts/openfoodfacts-server/blob/master/templates/ecoscore_details.tt.html#L42

https://world.openfoodfacts.org/product/4099200068152/crevettes-almare-seafood

**Comment by stephanegigandet** [comment]
Due to a change in the ecoscore_data field, fixed now that all products have been re-processed.
