### ISSUE TITLE
Missing icons and titles for some server attributes

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#4702]
Missing icons and titles for some server attributes

![image](https://user-images.githubusercontent.com/1689815/127300228-73737f7c-cc1c-4f6b-98c0-384cf3496a33.png)

### Icons: 
- [ ] Forest footprint
- [ ] NOVA
- [ ] Allergens: None

### Section titles
- [ ] ingredients "Ingredients"
### Descriptions
- [ ] Number of additives "This product contains %n additives"

**Comment by roshnaeem** [comment]
Can you please send me the link to this page?
