### ISSUE TITLE
Undefined subroutine &ModPerl::ROOT::ModPerl::Registry::home_off_cgi_reset_password_2epl::unix_md5_crypt called at reset_password.pl line 177.

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#471]
Software error:

Undefined subroutine &ModPerl::ROOT::ModPerl::Registry::home_off_cgi_reset_password_2epl::unix_md5_crypt called at /home/off/cgi/reset_password.pl line 177.
For help, please send mail to the webmaster (contact@openfoodfacts.org), giving this error message and the time and date of the error.

**Comment by hangy** [comment]
Fixed in 3dd50f83c17ebff7754ecb469ef74de65adca368
