### ISSUE TITLE
"barquette en aluminium" not recognized

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#4718]
"barquette en aluminium" not recognized

barquette en aluminium, emballage en plastique 
barquette aluminium, emballage en plastique

https://fr.openfoodfacts.org/produit/3596710477500/lasagne-a-la-bolognaise-auchan

**Comment by teolemon** [comment]
@stephanegigandet did your PR fix this ?

**Comment by stephanegigandet** [comment]
fixed.
