### ISSUE TITLE
No display products in "Eco-score A"

### ISSUE THREAD

**Issue by Manu1400** [openfoodfacts/openfoodfacts-server#4725]
**Describe the bug**
https://fr.openfoodfacts.org/eco-score/a is empty

**To Reproduce**
1. Go to https://fr.openfoodfacts.org/eco-score/a
2. See error: "Pas de produits." (no product)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome

**Comment by Manu1400** [comment]
Not having the bug in world instance : https://world.openfoodfacts.org/eco-score/a 👍

**Comment by stephanegigandet** [comment]
@Manu1400 : it's working for me, this can happen when the mongodb server is overloaded.

**Comment by jolesh** [comment]
Also worked for me

**Comment by stephanegigandet** [comment]
Issue is due to database overload. A few improvements have been deployed, and we'll be installing SSD disks for Mongo which should help.
