### ISSUE TITLE
Password reset does not work anymore

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#4734]
We got multiple reports from users saying that they are unable to reset their password.

"For some reasons, I just can't reset my password and get access to my account.
Tried on firefox, safari, chrome, edge... to no avail.

I do get the link in my mailbox, and then get access to the form to enter a new password. But as I press send, the boxes to enter the password and the send button dissapear, and nothing happens.

The new password is obviously not registered, i still get my access refused."

**Comment by jolesh** [comment]
Can't replicate it with Linux Mint 20; Firefox, Chrome and Tor. Even allows thing like "Password"

**Comment by jolesh** [comment]
Do you know which browsers and OS they used?

**Comment by jolesh** [comment]
Ah, the forgotten password option?

**Comment by jolesh** [comment]
I don't get any mail when I request a new password.

**Comment by jolesh** [comment]
I got five OFF-mails for reseting my password in the spam folder. Google said: "Why is this message in spam?
It is similar to messages that were identified as spam in the past."
But if I use the link from the mail, I can only make the query but my password doesn't change.

**Comment by stephanegigandet** [comment]
Investigating.
