### ISSUE TITLE
Colours in ingredient list (German white and yellow beeswax: Bienenwachs, Weiß und Gelb)

### ISSUE THREAD

**Issue by jolesh** [openfoodfacts/openfoodfacts-server#4737]
How should we analyze colours like "[weiß und gelb](https://de.openfoodfacts.org/zutat/wei%C3%9F-und-gelb)" in the ingredients list. There are 59 products at the moment who have the issue with "weiß und gelb" but there are probably many more since it effects all languages.

**Comment by stephanegigandet** [comment]
I had a look at a few examples, does it always come from "Überzugsmittel Bienenwachs, weiß und gelb" ? In that case we could just look for that in the preparse_ingredients_text() function : https://github.com/openfoodfacts/openfoodfacts-server/blob/master/lib/ProductOpener/Ingredients.pm#L3540

And the function could just remove the comma. It should then match this entry in the ingredients taxonomy:

<en:beeswax
en:white and yellow beeswax
bg:пчелен восък - бял и жълт
ca:cera d'abelles blnaca i groga
cs:včelí vosk bílý a žlutý
da:bivoks hvidt og gult
de:Bienenwachs Weiß und Gelb

Do you want to try to do it?

**Comment by jolesh** [comment]
I will try. But I will have to train a bit before and find an example of how it is done in another case.

**Comment by jolesh** [comment]
@stephanegigandet Where exactly should I add it in the code and is the an example from which I can learn/copy?

**Comment by stephanegigandet** [comment]
Inside the preparse_ingredients_text function, there is a part where we do language-specific transformations of the ingredients text:

`````
	$log->debug("preparse_ingredients_text - before language specific preparsing", { text => $text }) if $log->is_debug();

	if ($product_lc eq 'es') {

		# Special handling for sal as it can mean salt or shorea robusta
		# aceites vegetales (palma, shea, sal (shorea robusta), hueso de mango)
		$text =~  s/\bsal \(shorea robusta\)/shorea robusta/ig;
		$text =~  s/\bshorea robusta \(sal\)/shorea robusta/ig;
	}
	elsif ( $product_lc eq 'fi' ) {

		# Organic label can appear as a part of a longer word.
		# Separate it so it can be detected
		$text =~ s/\b(luomu)\B/$1 /ig;
	}
``````

So for instance, in the Finnish language, if we see "luomusomething", it is turned to "luomu something".

You can add a German specific transformation, where you turn "Bienenwachs, weiß und gelb" to "Bienenwachs weiß und gelb"

Something like $text =~ s/Bienenwachs, weiß und gelb/Bienenwachs weiß und gelb/ig;

You might want to look at the products where we have "weiß und gelb" to see what we need to match in ingredients list. Maybe sometimes it's listed as "Bienenwachs (weiß und gelb)" for instance.

Then in the t/ directory, you can add tests to verify that it works, in this file:

t/ingredients_parsing.t

**Comment by jolesh** [comment]
Yes found one with [Bienenwachs (weiß und gelb)](https://de.openfoodfacts.org/produkt/4337185303739/choc-it-k-classic) how would I handle that? Isn't there an option for such variants? I think I saw sth like that befor.

**Comment by stephanegigandet** [comment]
> Yes found one with [Bienenwachs (weiß und gelb)](https://de.openfoodfacts.org/produkt/4337185303739/choc-it-k-classic) how would I handle that? Isn't there an option for such variants? I think I saw sth like that befor.

Well either you would add another regexp for that, or you could try to cover it in the same regexp, but it may make it more complicated and dangerous. A separate regexp is probably simpler and safer.

**Comment by Ban3** [comment]
Additives taxonomy is more complete if looking for other languages https://github.com/openfoodfacts/openfoodfacts-server/blob/c0a039282d5d9bd29f87a2c4a393c425c1072ffb/taxonomies/additives.txt#L17662-L17684

examples: [fi:valkoinen-ja-keltainen](https://world.openfoodfacts.org/ingredient/fi:valkoinen-ja-keltainen), [sv:vitt-och-gult](https://world.openfoodfacts.org/ingredient/sv:vitt-och-gult), [pl:biały-i-żółty](https://world.openfoodfacts.org/ingredient/pl:bia%C5%82y-i-%C5%BC%C3%B3%C5%82ty)

**Comment by jolesh** [comment]
I am confused with what to do in ingredients and what in additives.
