### ISSUE TITLE
Sorting lists, feature lost?

### ISSUE THREAD

**Issue by TaciteOFF** [openfoodfacts/openfoodfacts-server#474]
Hello.

A very useful and important feature has disapeared.

We used to be able to sort lists (http://fr.openfoodfacts.org/categories for example) alphabetically and to do search on it.

It's no longer possible.

What happened?

**Comment by hangy** [comment]
That's a bug. We did update the DataTables plugin that makes the table searchable and sortable to the current release, but for some reason, the JS and CSS files are missing from the production deployment.

**Comment by stephanegigandet** [comment]
Fixed, thanks @hangy.
