### ISSUE TITLE
"Sodium" word in nutrition facts table (Hungarian)

### ISSUE THREAD

**Issue by TaciteOFF** [openfoodfacts/openfoodfacts-server#475]
The "sodium" word doesn't appear in the table : 

http://hu.openfoodfacts.org/product/8594010426117/tonhal-salata-deli

**Comment by TaciteOFF** [comment]
sometimes it even adds a blank line : 

http://hu.openfoodfacts.org/product/5999033871143/spar

**Comment by VaiTon** [comment]
Guess this has been fixed. @teolemon @stephanegigandet
