### ISSUE TITLE
MongoDB::DatabaseError: operation exceeded time limit

### ISSUE THREAD

**Issue by Ban3** [openfoodfacts/openfoodfacts-server#4754]
**Describe the bug**

> Software error:
MongoDB::DatabaseError: operation exceeded time limit
For help, please send mail to the webmaster (contact@openfoodfacts.org), giving this error message and the time and date of the error.

Loading the website gives this error often but not on every load.

**To Reproduce**
1. Go to https://fi.openfoodfacts.org/

**Comment by stephanegigandet** [comment]
I fixed an issue with caching that should help with the mongodb load. And we'll install SSD disks for the Mongo database tomorrow, hopefully it will help. :)

**Comment by Ban3** [comment]
Closing this as fixed as I haven't encountered it in a while.
