### ISSUE TITLE
Authentification with the wiki is partially broken

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#476]
http://fr.wiki.openfoodfacts.org/Sp%C3%A9cial:Modifications_r%C3%A9centes

**Comment by stephanegigandet** [comment]
Just tested, it seems to work for me. Don't know what happened, will investigate if it continues.

**Comment by teolemon** [comment]
People who didn't use the wiki before, or just the French wiki ?

**Comment by stephanegigandet** [comment]
the sso.pl is called with the user_id and the session id inverted:

sso.pl - check_session call - user_id: 5Rp5P2Cdv7oKdOVoD1kpBs5dYL9ARYl4FurAUYXtbLPSKPHOyTyYOXy3EfAsIXsF - user_session: stephane

This is what we do on the mediawiki side to get the user_id and session id from the cookie:

```
                                                $website_cookie = ".openfoodfacts.org";
                                                $name_cookie = "session";
                                                $cookie = $_COOKIE; // tu peux récupérer le cookie en PHP

                                                /*              user_session
                                                        &       [session_id]
                                                        &       user_id
                                                        &       stephane                        */
                                                $valeur_cookie = $cookie[$name_cookie];

                                                //Parser user_session&4414725571&user_id&manu1400
                                                $tab_valeurs = split("&", $valeur_cookie); //Pas de limite
                                                $numero_session = $tab_valeurs[1]; //numéro de la session
                                                $username = $tab_valeurs[3]; 
````

Apparently we always got the values in the same order.
But now that order is reversed, at least sometimes.

The order is not specified in the code:

$session = { 'user_id'=>$user_id, 'user_session'=>$user_session };

$cookie = cookie (-name=>$cookie_name, -value=>$session, -path=>'/', -domain=>".$server_domain",	   -expires=>'+' . $length . 's') ;

It's just bad code that somehow used to work before.

We can do the right thing on the mediawiki side (just parse correctly the parameters), or we could workaround it by outputting the parameters in the expected order.

One thing is that the sso code on mediawiki is broken anyway: there is no session and the sso.pl says so, but mediawiki still identifies the user (with the sessionid as the userid...).

Anyone familiar with PHP to fix it?

The corresponding code is in /var/www/off.wiki.en/extensions/CASAuth/CASAuth.php

**Comment by stephanegigandet** [comment]
I added the PHP code for the mediawiki extension on product-opener / mediawiki / extensions / CASAuth /
