### ISSUE TITLE
Compute complete scan data for 2020 with scanbot and populate popularity facet

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#4763]
This is a tracking / documenting bug to process the 2020 scans of the Android and iOS OFF apps to populate the popularity facets.

**Comment by stephanegigandet** [comment]
We need to isolate the app scans from the nginx logs:

cd /srv/off/logs

There isn't an automated log rotation.

nginx.access2.log.20200716 contains logs from 20200908
nginx.access2.log contains logs from 20200716

Creating a new log file:

mv nginx.access2.log nginx.access2.log.20210118

grep "GET /api/" nginx.access2.log.20210118 > api.20200716-20210118

**Comment by VaiTon** [comment]
Instead of using the nginx logs, why don't we create a table in mongo and add the tracking code to the interested endpoints?

**Comment by stephanegigandet** [comment]
> Instead of using the nginx logs, why don't we create a table in mongo and add the tracking code to the interested endpoints?

I'm not sure what you mean by tracking code and endpoints?

There is a discussion about implementing a smarter way to do things here: https://github.com/openfoodfacts/openfoodfacts-server/issues/1501

But so far nothing has been decided / implemented, so in the mean time I'm doing it in a dumb and manual way. It is at least enough to get values for the popularity facet.

**Comment by VaiTon** [comment]
> 
> 
> > Instead of using the nginx logs, why don't we create a table in mongo and add the tracking code to the interested endpoints?
> 
> I'm not sure what you mean by tracking code and endpoints?
> 
> There is a discussion about implementing a smarter way to do things here: #1501
> 
> But so far nothing has been decided / implemented, so in the mean time I'm doing it in a dumb and manual way. It is at least enough to get values for the popularity facet.

Actually I mean what issue #1501 refers to. Creating a table (or collection) in the db and populating it with the data we need. 
Eg
- barcode
- n of scans (total)
- n of scans (this month)

And when the app queries the `/vX/whatever` it gets recorded there.

**Comment by stephanegigandet** [comment]
Right, #1501 is the right thing to do. It's a significant effort though, and at this time nobody is working on it. So using the logs is a workaround until we have a better solution in place.

**Comment by stephanegigandet** [comment]
2020 logs have been loaded in the popularity facet.
