### ISSUE TITLE
Contributeur page doesn't show modified products

### ISSUE THREAD

**Issue by jchristin** [openfoodfacts/openfoodfacts-server#477]
Contributeur link on home page says "Les produits que vous avez ajoutés ou modifiés" but [my contributeur page](http://ca-fr.openfoodfacts.org/contributeur/jchristin), for instance, only shows products I added (i.e. [this product](http://ca-fr.openfoodfacts.org/produit/0065633440685/cheerios-a-saveur-de-chocolat) should appears since I did some modifications on it).

**Comment by TaciteOFF** [comment]
Hello!

There are different pages

/contributeur/
/photographe/
/editeur/
/informateur/ 

Find the one that suits you! :)

**Comment by jchristin** [comment]
Great! This is what I was looking for.

However, link text and page content still do not match. I think we should either:
1. Change the link text or
2. Change the link reference or page content.

**Comment by TaciteOFF** [comment]
Yup. I think it has already been reported. Just a matter of time before it get fixed :)

**Comment by CharlesNepote** [comment]
Is it fixed? I think the actual page clearly provide links to added products, modified products, etc.

Please let me know or I'll close the issue.
