### ISSUE TITLE
Eco-Score calculation details dropdown is not fully visible on some screens

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#4789]
The Eco-Score methodology is not fully visible on some screen. 
In some case, the popup explaining the points is masked.

**Comment by stephanegigandet** [comment]
which screen? please include a product url

**Comment by teolemon** [comment]
I was on a videoconference, it was a windows laptop. It's that bug that we usually solve by hitting tab a few times.

**Comment by teolemon** [comment]
https://fr.openfoodfacts.org/marque/food4good

**Comment by stephanegigandet** [comment]
I cannot reproduce it, when the dropdown is opened, the page is extended.

Can you reproduce it?

``````
	# call equalizer when dropdown content is shown
	$initjs .= <<JS
\$('.f-dropdown').on('opened.fndtn.dropdown', function() {
   \$(document).foundation('equalizer', 'reflow');
});
JS
;

**Comment by stephanegigandet** [comment]
It can happen if the page is resized after opening the dropdown.

**Comment by teolemon** [comment]
I saw it happen live. No resize, probably a low screen resolution.

**Comment by teolemon** [comment]
ah: https://fr.openfoodfacts.org/produit/3426434010106/tranches-panees-lieu-noir-colin-lieu-de-norvege-food4good

**Comment by teolemon** [comment]
no, does not happen consistently
