### ISSUE TITLE
Packagings computed incorrectly after imports

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#4791]
Ignore weight in the packaging parser:
```
1 x Etui carton 32g à recycler
4 x Film plastique 6g à jeter
```
yields no results at all
https://fr.openfoodfacts.org/produit/3426434000015/saumon-sauvage-argente-du-pacifique-msc-peche-a-la-ligne-surgele-food4good

**Comment by stephanegigandet** [comment]
Weights are already handled in the packaging parser, this is an issue with imports.
