### ISSUE TITLE
UserVoice needs to be translated to the language of the subdomains

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#48]
Works fine for FR and EN, but not for NL for instance.

**Comment by hangy** [comment]
What about closing UserVoice? The [activity](https://openfoodfacts.uservoice.com/forums/163583-general/filters/new) is rather low compared to GitHub and Slack, and combined with social media channels, and email, closing UserVoice would require one less channel to be monitored.

**Comment by teolemon** [comment]
That sounds like a reasonable idea. @stephanegigandet  Can I close this bug, meanwhile?

**Comment by stephanegigandet** [comment]
Added "not done" label and closing.
