### ISSUE TITLE
CSS issue with the save button

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#4804]
![image](https://user-images.githubusercontent.com/1689815/106353988-d201bd80-62ee-11eb-8dfa-8a17bcd7184c.png)

**Comment by Britt96** [comment]
Hi,
I am new to this repo and would like to help. Can you be more specific as to what issue you're having?
Thank you.

**Comment by CharlesNepote** [comment]
I can't reproduce. @teolemon have you try without Power User Script? Can you give more context? An example?
