### ISSUE TITLE
NOVA 4 image is not returned by the attributes API

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#4809]
![image](https://user-images.githubusercontent.com/1689815/106388654-e1146880-63df-11eb-8d64-2238b8427ed8.png)

**Comment by stephanegigandet** [comment]
It is returned, but there's no png image, that might be the issue you see in the app.

https://world.openfoodfacts.org/api/v0/product/4058172324086/tomate-reis-dm-bio?fields=attribute_groups

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/127300057-6a9a8cd1-27c8-4a1b-8517-8031679741f5.png)

**Comment by stephanegigandet** [comment]
I'm guessing this has been fixed, there are both png and svg images.
