### ISSUE TITLE
Allow language removal

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#483]
I had a product, where the languages were no longer available. Thus I wanted to remove the languages, but it is not possible (apart from blanking the fields).

**Comment by Sebleouf** [comment]
This issue is very important for me. For instance, look at http://fr.openfoodfacts.org/langue/anglais : there is a lot of errors we can fix when this issue will be resolved...

**Comment by benbenben2** [comment]
@aleene on slack recently 
> a specific language can be removed if you empty all images, product name AND ingredients for that language. You might also like to experiment with changing the main language and using the option to move all current entries to that new language.

**Comment by aleene** [comment]
78 000 products by now

**Comment by aleene** [comment]
By the way not all of these have to be errors. If a product with a main language English, but also sold in France light end up here.

**Comment by aleene** [comment]
too old
