### ISSUE TITLE
Product count is not computed on language subdomains

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#484]
http://ru.openfoodfacts.org/products will work right
http://ru-en.openfoodfacts.org/products has stopped working

**Comment by hangy** [comment]
@stephanegigandet Could this be caused by weird permissions or is the script not in sync with git?
From the server:
```
-rw-r--r-- 1 off users 55663 Dec 22 23:39 /home/off/lang/ru/texts/products_stats_by.html
-rw-r--r-- 1 off off    1964 Dec 22 19:39 /home/off/lang/ru/texts/products_stats_.html
-rw-r--r-- 1 off root  50641 Jan 21  2014 /home/off/lang/ru/texts/products_stats.html
-rw-r--r-- 1 off users 10857 Dec 22 23:38 /home/off/lang/ru/texts/products_stats_il.html
-rw-r--r-- 1 off users 55422 Dec 22 23:38 /home/off/lang/ru/texts/products_stats_kz.html
-rw-r--r-- 1 off users 11376 Dec 22 23:38 /home/off/lang/ru/texts/products_stats_ru.html
```

When I ran it locally on my test server, it created a larger `products_stats.html` for me, and I don't have `products_stats_.html` at all.

**Comment by hangy** [comment]
> http://ru.openfoodfacts.org/products will work right
> http://ru-en.openfoodfacts.org/products has stopped working

Actually, the product stats are only calculated for official languages of the country: https://github.com/openfoodfacts/openfoodfacts-server/blob/24542ee59105b2f90ab5721bac9e027f5610ae31/scripts/gen_top_tags_per_country.pl#L854 Calculating the stats for each country for each language would likely be too many files.

Please reopen, if having the product stats for all countries in all languages is actually required.
