### ISSUE TITLE
photo already uploaded

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#486]
www.facebook.com/photo.php?fbid=10207850614559606&set=gm.1272785312766949&type=3&theater

> [4:34 PM]  
> Maxime Loth  | Facebook
> Je n'arrive pas à uploader les images que j'ai faites d'un produit "photo déjà envoyé", possible que ca soit un bug en ce moment ?
> 
> twoflower
> i cant upload new images right now, i always get the error "already uploaded"
> Posted in #generalToday at 2:36 PM 

product_image_upload.pl - last change on this file was 3 days ago

-use JSON;
+use JSON::PP;

**Comment by hangy** [comment]
Could be related to #369, as the "already uploaded" status is not always accurate.

**Comment by stephanegigandet** [comment]
Closing old bug.
