### ISSUE TITLE
Move images between servers (e.g. OFF to OBF)

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#4880]
It is currently possible to move a whole product from OFF to OBF, but only if a product with the same barcode does not exist on OBF.

We can also move images from one product to another (with a different barcode), but that works only on the same server (an OFF product to another OFF product).

This feature is to allow moving images to another server, by typing "obf" in the barcode of the admin feature to move images.

While it is not as powerful as allowing a full merge with history (long standing but quite complex to resolve issue: #8), it would allow to move images from OFF to OBF, and then delete the product on OFF.

**Comment by teolemon** [comment]
Will close: https://github.com/openfoodfacts/openfoodfacts-server/issues/319
Will close: https://github.com/openfoodfacts/openfoodfacts-server/issues/320

You might also consider implementing: https://github.com/openfoodfacts/openfoodfacts-server/issues/497

**Comment by teolemon** [comment]
Can someone test this works ?
