### ISSUE TITLE
Submit button of the create user form has no associated label, causing "localized string not found" in some contexts

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#4889]
Missing translations on the Producer Platform
![image](https://user-images.githubusercontent.com/1689815/108744969-dbbbc100-753a-11eb-982a-227765bee690.png)

**Comment by stephanegigandet** [comment]
@teolemon : can you provide more details of where that bug happens? Is that in a webview of the iOS app?

That button is just a normal submit button, with no text. Usually browsers just put "Send" for it. We can add a text.

**Comment by teolemon** [comment]
@stephanegigandet on the producer platform, while attempting to signup. Another point is that the form is not responsive, unlike the rest of the page, which reduces conversion rate.
