### ISSUE TITLE
Chrome autofills username field with e-mail address

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#4968]
A lot of users are created with their email address as the username, it's probably because Chrome can autofill the username field with the email address:

![image](https://user-images.githubusercontent.com/8158668/110920543-cd80e980-831d-11eb-9f14-066ba5b3fa30.png)

The signup form has this:

<tr><td>Nom</td><td><input type="text" name="name"  size="80" autocomplete="name" id="name" /></td></tr>
--
  | <tr><td>Adresse e-mail</td><td><input type="text" name="email"  size="80" autocomplete="email" type="email" /></td></tr>
  | <tr><td>Nom d'utilisateur<br/><span class="info">(lettres non accentuées, chiffres et/ou tirets)</span></td><td><input type="text" name="userid"  size="40" autocomplete="username" id="userid" onkeyup="normalize_string_value(this)" /></td></tr>

I'm not sure how to handle that. If we remove autocomplete="username", then the browser won't remember it. If we do put it, we have the risk that the browser autofills with an email address.

**Comment by teolemon** [comment]
Add autocomplete="off" onto <form> element;
Add hidden <input> with autocomplete="false" as a first children element of the form.

**Comment by teolemon** [comment]
or strip everything right of @

**Comment by hangy** [comment]
I believe the `autocomplete="username"` is best practice in [chromium](https://www.chromium.org/developers/design-documents/form-styles-that-chromium-understands) to actually support auto-fill with password managers. I don't quite understand why Chrome would suggest an email even though `type="email"` is not set ...

**Comment by stephanegigandet** [comment]
@hangy A lot of sites use e-mails as usernames, and those fields have autocomplete="username". So I'm guessing Chrome then remembers that for some email address, the username field is also that e-mail address.

We started to get email addresses in usernames on January 10th 2020, and we now have a lot of them:

/srv/off/users# ls -lrt | grep gmail-com | wc -l
1154

So it would be great to find a solution. A workaround might be to have some javascript remove email addresses as usernames in the signup form (in fact there's already some javascript that turns the @ to - )

**Comment by stephanegigandet** [comment]
> or strip everything right of @

@teolemon : that could work. or maybe just clearing the field completely when there's a @

**Comment by hstauff** [comment]
Hi! I have been working on this issue and believe I have found a solution. Could you assign me to it please?
