### ISSUE TITLE
openfoodfacts.org and openbeautyfacts.org redirect to world.xxx.org

### ISSUE THREAD

**Issue by bcatelin** [openfoodfacts/openfoodfacts-server#498]
When going to http://openfoodfacts.org/ we are redirected to http://world.openfoodfacts.org/ instead of seeing the landing page which lists the number of products per countries. this is the case for OBF too.

**Comment by stephanegigandet** [comment]
We need to add a server directive for openfoodfacts.org in the nginx configuration file, something like this:

````
server {
        server_name preprod.openfoodfacts.org;

        root /home/off/html;

        access_log /home/off-preprod/logs/nginx.access.log;
        error_log /home/off-preprod/logs/nginx.error.log;

        gzip on;
        gzip_min_length 1000;

        ssi on;
        index index.shtml;

        include /etc/nginx/expires-no-json-xml.conf;
}

server {
        #listen 80 default_server;
        #listen [::]:80 default_server;

        server_name *.preprod.openfoodfacts.org preprod.openfoodfacts.eu *.preprod.openfoodfacts.eu;

**Comment by stephanegigandet** [comment]
But for some reason my ssi directive is not applied:

http://preprod.openfoodfacts.org/



We probably need to change that virtual to a file, but that may not be the only issue.

**Comment by CharlesNepote** [comment]
I'm closing this, it's outdated.
