### ISSUE TITLE
Editing a product in French on world changes prefix of tags

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#499]
So there was a product with Main Language: French
Tags (label) in French: fr:Experimentation NutriScore

Edited a category in World.

Product Opener changed the label to en:Experimentation NutriScore (no human modification on it)

**Comment by stephanegigandet** [comment]
Can you give me the url of the product?

**Comment by aleksejrs** [comment]
https://world.openpetfoodfacts.org/product/4627109380312/second-age-kitten-royal-canin

Do a null edit at world-es, world-ru or world-zh. The categories' prefix will be changed to that language.

**Comment by hangy** [comment]
Also happens on non-world subdomains. I just tested with http://world.openfoodfacts.net/product/3302740967108. It had some categories with the `ru:` prefix. When I edited it on http://de.openfoodfacts.net/product/3302740967108, `ru:Gratins dauphinois` was changed to `de:Gratins dauphinois`. Same for untaxonomized labels.

**Comment by hangy** [comment]
I'm unable to reproduce this any more.
