### ISSUE TITLE
Get checkbot to skip "error on label" 

### ISSUE THREAD

**Issue by kyzh** [openfoodfacts/openfoodfacts-server#50]
When label are wrong, we keep the data from the label.
We should tag those product "error on label"  (as opposed to error by the person that typed the product in).

Checkbot should not repport those as a problem, hence skip the product with "error on label"

**Comment by sl956** [comment]
Already done. The label skipped by checkbot is "Incorrect data on label" (which has a child label "Incorrect nutrition facts on label")
