### ISSUE TITLE
Upgrade api document on wiki

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#500]
I am working on updating a product from my app. Reading the api-document leaves me with some questions:
- status-codes - posting an edit returns with a json-files with the results. Please add an overview of possible statusses. Then I can handle these errors. (Also nice for read errors)
- login required? - the examples do not make it clear whether a login/password is required. There is an example without the credentials in the url. How would this work in an app?
- field codes - the list with field codes is incomplete;
- https - add the info required for secure posting;

**Comment by teolemon** [comment]
- https: added the url. We cannot do lang-specific queries for now. @stephanegigandet is working on adding the most used locales as ssl. We might instead get away by adding a parameter to filter the domain.
- status codes: added the "product not found" for read
- field codes : added a prettyfied json dump. also added this: http://en.wiki.openfoodfacts.org/API/Auto . 
- We need to move to Swagger for good documentation : https://github.com/openfoodfacts/openfoodfacts-server/issues/187#issuecomment-250930241
- posting photos doesn't require a login. posting a product does it using the openfoodfacts-contributors account. not sure if a password is required.

**Comment by aleene** [comment]
Nice to have a more complete doc

**Comment by CharlesNepote** [comment]
I close this old bug as we actually have an API documentation, I suggest to open more specific issues if necessary.
