### ISSUE TITLE
Add option to unlink user from org

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#5005]
- Add an option to clear the org from a user in the org creation email when the user clearly has no relation to the org.
- Normally, he/she will then have to submit a request to rejoin the org. Admins should probably receive the request since the org has no user anymore (or the legitimate user if a legitimate user has been added meanwhile)

### Part of
- #5521

**Comment by stephanegigandet** [comment]
You can edit any user profile to remove the org they are associated with. Is this bug about adding a link in the org creation email that would do it automatically? That should be doable.
