### ISSUE TITLE
Bad id palm-oil-free instead of palm_oil_free for attribute

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#5007]
There's a mistmatch between the id used in attribute preferences and the attributes returned for products.

e.g. https://fr.openfoodfacts.org/api/v2/produit/3038354256207/panzani-original-sauce?fields=attribute_groups

**Comment by monsieurtanuki** [comment]
@stephanegigandet  It looks like your `-_` fix provoked dangerous side-effects:
* https://world.openfoodfacts.org/api/v2/attribute_groups?lc=en is now empty
* some confusion with svg icon names too: in the cache asset file the name is `sesame-seeds-content-unknown.svg` while it's looking for a different name in the network `sesame_seeds-content-unknown.svg`

**Comment by stephanegigandet** [comment]
Looking into it.

**Comment by stephanegigandet** [comment]
@monsieurtanuki : new fix : https://github.com/openfoodfacts/openfoodfacts-server/pull/5019

**Comment by stephanegigandet** [comment]
New fix is deployed.
