### ISSUE TITLE
Add a link to userprofile in the org request email

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#5013]
Add a link to userprofile in the org request email

### Part of
- #5521

**Comment by teolemon** [comment]
Bonjour, 
Nous venons de mettre à jour votre compte. Vous pouvez accéder à votre espace producteur depuis votre compte (XXXX) sur https://fr.pro.openfoodfacts.org

Bien sincèrement,

**Comment by manon-corneille** [comment]
Nice to have, but not a priority imo because people receive the email to their email address (which is needed to log in) so that should give them a clue no? :)
