### ISSUE TITLE
prefer svg over png label images

### ISSUE THREAD

**Issue by fuddl** [openfoodfacts/openfoodfacts-server#503]
[This product](http://de.openfoodfacts.org/produkt/4101080009825) should have [this label](http://static.openfoodfacts.org/images/lang/de/labels/g-g-a.90x90.svg) but instead it uses [this one](http://static.openfoodfacts.org/images/lang/de/labels/g-g-a.90x90.png) (which is not even in the repository anymore).

**Comment by hangy** [comment]
Fixed in 5dfb0d783f12b26101dbb94447ad547aed0aa770, created [PR](https://bitbucket.org/openfoodfacts/product-opener/pull-requests/60) for internal review.

**Comment by hangy** [comment]
PR merged c1e089366e36d685c501c823677e963d97a66281
