### ISSUE TITLE
Adding more metadata for admins to the org page on the producer platform

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#5044]
Adding more metadata for admins to the org page on the producer platform

- [ ] account creation date
- [ ] first file import date
- [ ] last file import date
- [ ] first manual creation date
- [ ] last manual creation date
- [ ] first import to the public db
- [ ] last import to the public db
- [ ] number of members (and list of members)
- [ ] unlinked accounts with the same domain name
- [ ] List the technical system they have (if they have both equadis and codeonline for instance)

**Comment by manon-corneille** [comment]
Nice :) Note included in the reflexion for creating a producer' dashboard
