### ISSUE TITLE
Add garlic and onion as allergens

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#5055]
https://twitter.com/jrdorkin/status/1371512549192138753
Could you add Garlic and onion as allergens in your database?  I just discovered your platform, and would love to see it help folks like me that struggle with those foods.

**Comment by stephanegigandet** [comment]
I 'm not sure that adding new ingredients as allergens in the database is a good idea. The allergens we have are those for which there is a mandatory declaration. We already recognize garlic and onions (and mangoes, kiwis, carrots, peaches, cherries and dozens of other ingredients people are commonly allergic to) as ingredients. We could change the clients (web site, app) to be able to declare allergies to specific ingredients, but in terms of database structure, it may not make sense to add possibly hundreds of allergens.

**Comment by stephanegigandet** [comment]
Closing this in favor of #6430
