### ISSUE TITLE
Allow for image multi-mapping

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#5069]
Allow for image multi-mapping. When nutrition tables are shared among products, producers send us those kind of files. Consider multiple barcode mapping 

```3073781100617 -3073781070279 -3073781070286 -3073781070293 -3073781070309.nutrition_fr.PNG```

**Comment by stephanegigandet** [comment]
I'd prefer not to add code for very isolated cases, that we have then to document and maintain.
