### ISSUE TITLE
Allow producers to find out which of their products they haven't updated

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#5076]
Allow producers to find out which of their products they haven't updated

- [ ] Take into account the facts that it might be the Polish version of the product, that the French branch of their company has no data about
- [ ] Be crystal clear that it will only be archiving, not deletion, and that we'd like a stop date.
- [ ] Repeat the process for all brands on their producer account
- [ ] Be clear that promotion and multipack should not be archived.

Query: Products with La Vache Qui Rit as a brand which haven't been edited by bel-groupe: https://world.openfoodfacts.org/cgi/search.pl?action=process&tagtype_0=brands&tag_contains_0=contains&tag_0=la%20vache%20qui%20rit&tagtype_1=editors&tag_contains_1=does_not_contain&tag_1=org-groupe-bel&sort_by=unique_scans_n&page_size=20

### Part of
- #5521

**Comment by manon-corneille** [comment]
Something we can add to the producer's dashboard :)
