### ISSUE TITLE
Values deleted when setting nutrient values through API

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#509]
Bug reported by François on Slack, could not find it on github so creating one, merge if duplicate.

The query /cgi/product_jqm2.pl?code=3368958898139&nutriment_energy_unit=kcal&nutrition_data_per=100g&nutriment_energy=411 does not save values for energy.

**Comment by stephanegigandet** [comment]
Verified on production.

Works on .net which has older code.

**Comment by stephanegigandet** [comment]
updated the code in product_jqm_multilingual.pm (a big portion of it is in product_multilingual.pm and needs to be factorized).

**Comment by lemonlab** [comment]
Works great.
Thank you !
