### ISSUE TITLE
Rename master branch to main branch

### ISSUE THREAD

**Issue by nicolasleger** [openfoodfacts/openfoodfacts-server#5102]
Following Github impulse https://github.com/github/renaming
See also https://en.wikipedia.org/wiki/Master/slave_(technology)

I already made the change to [OFF Ruby projects](https://github.com/openfoodfacts?q=&type=&language=ruby&sort=).

**Comment by stephanegigandet** [comment]
Sounds good to me, and it looks easy. Anything special we should watch for? e.g. crowdin @teolemon ?

**Comment by nicolasleger** [comment]
Github manages the redirects, just need each develope to update its local repository.

**Comment by teolemon** [comment]
Docker hub ?

**Comment by stephanegigandet** [comment]
OK, renaming done, we'll fix things if something breaks.

The default branch has been renamed!
master is now named main

If you have a local clone, you can update it by running:

git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
