### ISSUE TITLE
"Install the mobile app" is too long in some languages, causing header to span 2 rows

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#5112]
In English we have "get_the_app", but in some languages, the strings become too long and the header goes on 2 rows:

![image](https://user-images.githubusercontent.com/8158668/113896643-6ba38a80-97ca-11eb-8ecb-4b000da4cb3e.png)

Maybe we can add a comment to tell translators to make it very bried. "Installez l'app".

**Comment by stephanegigandet** [comment]
I'm not convinced "appli" is the best name, but it's shorter than application. :)

![image](https://user-images.githubusercontent.com/8158668/113897132-e2408800-97ca-11eb-8fb0-363a6c92b7b1.png)

**Comment by idotj** [comment]
Bonjour,
Just an idea, why not to keep it simple and use "App mobile" for desktop resolutions?, here in France is quite used and understandable.
I tried changing some CSS styles and took me less than 5 minutes:
![Screen Shot 2021-06-12 at 16 05 21](https://user-images.githubusercontent.com/6554216/121778681-43ecec00-cb98-11eb-82c0-e48c7474b0cd.png)

If it's ok I can do the changes and send a PR.

**Comment by Fienne** [comment]
@stephanegigandet can I work on this too?

**Comment by Fienne** [comment]
The issue has already been solved by Using the phone icon without any text attached to it. I think the issue can be closed now.
![Screenshot from 2022-03-29 10-03-47](https://user-images.githubusercontent.com/72187339/160575996-a6f1dadb-7654-4b73-9246-903d3d1672da.png)

**Comment by alexgarel** [comment]
I can still broke it in some configuration… but I don't know if it's that important.
![Capture d’écran de 2022-04-01 12-16-00](https://user-images.githubusercontent.com/144788/161244771-2f0f6cfa-b9c7-4bf3-969d-5dd419ee5f31.png)

**Comment by teolemon** [comment]
closing, we added a warning in the redesign string
