### ISSUE TITLE
Change packaging examples

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#514]
Currently we have 

> Examples: Fresh, Canned, Frozen, Bottle, Box, Glass, Plastic...

What about:

> Examples: Fresh, Canned, Frozen, Bottle, Glass, Plastic, 21-PAP,♲,♳,♴,♵,♶,♷,♸,♹,♺,♻,♼,♽,...

**Comment by teolemon** [comment]
http://graphemica.com/characters/tags/recycling

**Comment by aleene** [comment]
First figure out the taxonomy?

**Comment by hangy** [comment]
> First figure out the taxonomy?

That would be nice, too. 👍 

> Examples: Fresh, Canned, Frozen, Bottle, Glass, Plastic, 21-PAP,♲,♳,♴,♵,♶,♷,♸,♹,♺,♻,♼,♽,...

Part of the translation http://en.wiki.openfoodfacts.org/Translations_-_Web_site_interface `packaging_example`, and corresponding Launchpad string. Just like for #534 and #531, we need to figure out, if we want to ditch the wiki translation in favor of the `po` files now.

**Comment by hangy** [comment]
Can be translated now.
https://github.com/openfoodfacts/openfoodfacts-server/blob/9f7e5d146f2d76c7a826353b38248c35edd8c4fb/po/common/common.pot#L1792-L1794
