### ISSUE TITLE
Website (url) structure

### ISSUE THREAD

**Issue by M123-dev** [openfoodfacts/openfoodfacts-server#5148]
I don't use the website very often, but I do use it regularly and I have noticed many irregularities. Here I am mainly concerned about the urls.

I come from Germany, so I use de.openfoodfacts instead of world.openfoodfacts.

### Product Page:
In German, /produkt/x is opened which is the correct German translation of product. 

### Vision, Mission, Values and Programs Page:
Here the fun begins.

EN: I get to world.openfood.....org/open-food-facts-vision.... 

DE: I get to world-de.openfood.....org/open-food-facts-vision...

The beginning of the url is strange (what even is world-de) and the path is in English not in German as it is on the product page.
Here sone parts like the donataion banner and the profile section  is in German but the content is in English.

But when we go to who we are with world-de. the path is again in German /wer-wir-sind.

I can go into more detail, but what I mean should have gotten clear.
Such a mess is not good for a big project. We need some kind of structure on how to build the url.

**Comment by stephanegigandet** [comment]
The link https://world.openfoodfacts.org/open-food-facts-vision-mission-values-and-programs is not supposed to change in fact, as we only have this in English right now.  https://world-de makes the language of the interface become German, but it's probably not a good idea here. I think someone "translated" the link in crowdin.

**Comment by stephanegigandet** [comment]
Also see https://github.com/openfoodfacts/openfoodfacts-server/issues/1818 for a potential solution
