### ISSUE TITLE
/tmp fills up with images uploaded... and never deleted

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#518]
-rw------- 1 off     off     1812111 Oct 17 14:50 TxGHPquSBU
-rw------- 1 off     off     1895206 Oct 17 14:51 0T65JC9aKr
-rw------- 1 off     off     1998024 Oct 17 14:52 kcdxXxXDV5
-rw------- 1 off     off     1892965 Oct 17 14:53 7NENn9ngM2
-rw------- 1 off     off     1932673 Oct 17 14:54 UXXoUcS9Hh
-rw------- 1 off     off     1754787 Oct 17 14:58 SBxUsRvx9X
-rw------- 1 off     off     1747262 Oct 17 14:59 sOosFIgjyM
-rw------- 1 off     off     1842138 Oct 17 15:04 B0ECh9eoQC
-rw------- 1 off     off      675328 Oct 17 15:06 MYrOYy2Az0
-rw------- 1 off     off      124749 Oct 17 15:07 gq5iXwXB2_
-rw------- 1 off     off      144953 Oct 17 15:07 VeuLqplD72
-rw------- 1 off     off      861048 Oct 17 15:10 ZW93zZPo8A
-rw------- 1 off     off      158162 Oct 17 15:13 wQ4BHXf6qU

**Comment by stephanegigandet** [comment]
Given the files belong to the off user, it's not nginx who writes them, but Apache + mod_perl.

Maybe related: https://rt.cpan.org/Public/Bug/Display.html?id=50407

Stopping and starting Apache does not delete the files.

**Comment by stephanegigandet** [comment]
Fix: https://bitbucket.org/openfoodfacts/product-opener/pull-requests/53/delete-uploaded-image-in-tmp-after-reading/diff

**Comment by teolemon** [comment]
@stephanegigandet looks merged. Can it be closed ?

**Comment by teolemon** [comment]
seems fixed. Closing (poke @stephanegigandet )
