### ISSUE TITLE
Make email templates in the admin notifications for the platform translatable

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#5182]
### What

- [ ] Adding multilingual (at least English) support for followup emails
- [ ] Make email templates in the admin notifications for the platform translatable and send the English version if lang≠fr

### Why

- It will save valuable time for admins to handle international requests.

### Part of
- #5521 

### Screenshot
![image](https://user-images.githubusercontent.com/1689815/112607363-6a14b280-8e19-11eb-82da-ea683030220b.png)

### Code pointer
https://github.com/openfoodfacts/openfoodfacts-server/blob/9af7d8767d3e2a84b055f96b9fa18dc3a45988e6/lib/ProductOpener/Users.pm#L592

**Comment by stephanegigandet** [comment]
@teolemon so currently those mails are in templates:

e.g. https://github.com/openfoodfacts/openfoodfacts-server/blob/main/templates/emails/user_new_pro_account.tt.txt

How do you want to do handle the translations?

Option 1:

we create files in /templates/emails/ :+1: 

user_new_pro_account.tt.en.txt
user_new_pro_account.tt.fr.txt

And either those files are updated manually, or the translations are managed through Crowdin.

Option 2:

we put the emails templates out of the /templates/email dir and we put them in common.pot (or email.pot)


Same question for the welcome email when a user creates an account on OFF (normal account or pro account)

**Comment by stephanegigandet** [comment]
Note: some email templates are HTML email templates, so we would need to make sure that the translation method does not break the HTML code.

e.g. https://github.com/openfoodfacts/openfoodfacts-server/blob/main/templates/emails/user_new_pro_account_admin_notification.tt.html

**Comment by aakankshabhende** [comment]
I would like to work on this issue @teolemon
