### ISSUE TITLE
API: We should minify JSON responses

### ISSUE THREAD

**Issue by VaiTon** [openfoodfacts/openfoodfacts-server#5183]
As the title says, we should minify JSON responses. In some cases this could means a ~20% increase in file sizes.

### Example:
 https://world.openfoodfacts.org/files/app/ingredients-analysis.json

**Comment by stephanegigandet** [comment]
Minify as in remove extra spaces, tabs, line feeds etc. ? We already do that for actual API responses (products etc.)

This specific file https://world.openfoodfacts.org/files/app/ingredients-analysis.json is generated by hand, it's more of a config file for the app, so I think it's best to keep it in a more human readable form.
