### ISSUE TITLE
Accept `saturated-fat` AND `saturated_fat` as a quick fix to a bug in Android prod

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#5185]
The fact is that while saving, the app takes the field name from the layout file. In android you can't name a layout with the "_" and that's why it is named saturated-fat and it's not parsed by the server.
@stephanegigandet @VaiTon so if the API accepted `saturated-fat` AND `saturated_fat`, it would solve the issue immediately for everybody ?

_Originally posted by @teolemon in https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/3780#issuecomment-829157357_

**Comment by teolemon** [comment]
```
We send this query when updating a product:

code=5281026003670&
lang=fr&
code=5281026003670&
lc=en&
imageUrl=https://static.openfoodfacts.org/images/products/528/102/600/3670/front_fr.4.400.jpg&
nutrition_data_per=100g&
nutriment_energy-kj=20&
nutriment_energy-kcal=532&
nutriment_salt_unit=g&
nutriment_salt=2.9&
nutriment_fat_unit=g&
nutriment_fat=33.5&
nutriment_proteins_unit=g&
nutriment_proteins=20.7&
nutriment_saturated-fat_unit=g&
nutriment_saturated-fat=6.1&
nutriment_carbohydrates_unit=g&
nutriment_carbohydrates=35&
nutriment_sugars_unit=g&
nutriment_sugars=4.6
Isn't it correct? @teolemon
```

**Comment by teolemon** [comment]
actually, we send the right query

**Comment by stephanegigandet** [comment]
well that query works.
