### ISSUE TITLE
Add interactive chat for producers

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#5198]
How about adding an option to start a chat from the producer platform ?

```
<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
```

```
<button class="open-zammad-chat">Chat with us</button>

<script src="https://support.openfoodfacts.org/assets/chat/chat.min.js"></script>
<script>
$(function() {
  new ZammadChat({
    background: '#e6e5e5',
    fontSize: '12px',
    chatId: 1,
    show: false
  });
});
</script>
```

**Comment by stephanegigandet** [comment]
The script is deployed on https://world.pro.openfoodfacts.org/chat but it's not working yet, as it thinks no agents are available (there are 2 available agents though).

It may be an issue with the websocket configuration to access the container, e.g. a reverse proxy config like https://www.nginx.com/blog/websocket-nginx/

**Comment by stephanegigandet** [comment]
@CharlesNepote found the solution: on https://support.openfoodfacts.org/#channels/chat -> click on the "default" chat and add openfoodfacts.org as an authorized web site
