### ISSUE TITLE
Add a code of conduct

### ISSUE THREAD

**Issue by kyzh** [openfoodfacts/openfoodfacts-server#52]

**Comment by kyzh** [comment]
https://www.npmjs.com/policies/conduct
https://github.com/bundler/bundler/blob/master/lib/bundler/templates/newgem/CODE_OF_CONDUCT.md.tt
http://contributor-covenant.org
https://github.com/gitlabhq/gitlabhq/blob/master/CONTRIBUTING.md
https://getfedora.org/code-of-conduct
http://jsconf.com/codeofconduct.html
http://bundler.io/conduct.html
https://github.com/WomenWhoCode/guidelines-resources/blob/master/code_of_conduct.md
https://wiki.gnome.org/action/show/Foundation/CodeOfConduct?action=show&redirect=CodeOfConduct
http://en.m.wikipedia.org/wiki/Wikipedia:Administrator_Code_of_Conduct
http://en.m.wikipedia.org/wiki/Code_of_conduct

**Comment by kyzh** [comment]
Draft https://lite5.framapad.org/p/OFF-CoC

**Comment by kyzh** [comment]
The wiki page that make a case for it http://en.wiki.openfoodfacts.org/Code_of_conduct

**Comment by teolemon** [comment]
@kyzh solved ?

**Comment by teolemon** [comment]
@kyzh closing, since fixed.
