### ISSUE TITLE
Move to Tesseract 4

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#520]
https://openfoodfacts.slack.com/archives/ocr/p1438440784000055

with tesseract 2 on prod, and 3 on .net
https://openfoodfacts.slack.com/archives/productopener/p1421773135000027
Tesseract 3 instead of 2, with the default French dict. on http://fr.openfoodfacts.net/

**Comment by teolemon** [comment]
Also, add all available languages to 
product-opener / lib / ProductOpener / Config_off.pm
product-opener / lib / ProductOpener / Config_obf.pm

**Comment by teolemon** [comment]
especially Russian and Ukrainian

**Comment by teolemon** [comment]
https://github.com/tesseract-ocr/tesseract/issues/892

**Comment by raphael0202** [comment]
@teolemon As it seems we've dropped tesseract support, can be closed

**Comment by hangy** [comment]
> @teolemon As it seems we've dropped tesseract support, can be closed

From a quick glance, Tesseract support is still in the source: https://github.com/openfoodfacts/openfoodfacts-server/blob/d554b3096dab7c7e02b11d8d104b3cadfc375ab7/lib/ProductOpener/Ingredients.pm#L270 https://github.com/openfoodfacts/openfoodfacts-server/blob/2cdb223de8fcc47ea3b97b40de53d78034c7910d/html/js/product-multilingual.js#L423

**Comment by teolemon** [comment]
Tesseract 4 has been released:
https://github.com/tesseract-ocr/tesseract

**Comment by stephanegigandet** [comment]
We are currently using Cloud Vision, and there is no plan to move to Tesseract right now. Closing this, we can reopen if we need Tesseract at some point.
