### ISSUE TITLE
Palm oil detection needs to be made global and multiligual

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#522]
http://world.openfoodfacts.org/ingredients-that-may-be-from-palm-oil
http://world.openfoodfacts.org/ingredients-that-may-be-from-palm-oil/e470b-stearate-de-magnesium

**Comment by teolemon** [comment]
https://en.wiki.openfoodfacts.org/Global_palm_oil_taxonomy

**Comment by VaiTon** [comment]
Is this still an issue?

**Comment by stephanegigandet** [comment]
Yes, palm oil detection still rely on an old list of ingredients in French. It has been slightly improved thanks to the new multilingual ingredients taxonomy, but it's still far from perfect.

**Comment by aleene** [comment]
I'll try to integrate the two. Where was the palm oil stuff?

**Comment by stephanegigandet** [comment]
@aleene : 2 files in https://github.com/openfoodfacts/openfoodfacts-server/tree/master/ingredients
The additives one can be ignored, it's old stuff.

**Comment by aleene** [comment]
I added the synonyms from the files into the ingredients taxonomy.
You can use the parent en:palm and may be from palm oil for the detection. It is a flat structure, i.e. there are multiple children, but no need to traverse the tree any further.

**Comment by stephanegigandet** [comment]
I'm thinking it may be better to use a property instead of a parent.
Something like:
from_palm_oil:en:maybe
or
from_palm_oil:en:yes

And we should think about other ingredient properties that would be useful. e.g. is it vegetarian or vegan?

vegetarian:en:yes
vegetarian:en:no
vetetarian:en:maybe

I think it's better to make it a property of specific items, instead of a parent. That way it's easier to show ingredients that make something not vegetarian, or not palm oil free.

**Comment by aleene** [comment]
OK. For palm it is not to much work. Could you use the hierarchy to indicate that everything below is yes. And vice versa everything above will be maybe.

**Comment by stephanegigandet** [comment]
Yes, we should put the property only on the upper parent that is yes.

**Comment by aleene** [comment]
Nice that vegetarian much less work as well. Would work for nova as well.

**Comment by aleene** [comment]
I had to add "from_palm_oil:en:yes" on one node. Below is palm, above might be palm.

**Comment by aleene** [comment]
You can also just use the corresponding ingredient node. No need for a special property at the moment.

**Comment by teolemon** [comment]
Can we close @stephanegigandet @aleene ?

**Comment by Slawek234** [comment]
Incorrectly detected presence of palm oil.
https://pl.openfoodfacts.org/product/5902891280231/cappuccino-z-magnezem-mokate
This product contains palm oil.
