### ISSUE TITLE
Add "xxxxxx de France" logos

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#5239]
There are official logos for:
* "oeufs de France" label, see: https://agriculture.gouv.fr/oeufs-de-france-un-logo-pour-garantir-lorigine-et-la-tracabilite
* "fruits et légumes de France" et "pommes de terre de France" : https://www.uncgfl.fr/10-actualites-publiques/229-logos-fruits-legumes-de-france-et-pommes-de-terre-de-france

**Comment by stephanegigandet** [comment]
The logos need to be added here:

/openfoodfacts-server$ ls -lrt html/images/lang/fr/labels/
total 1204
-rw-rw-r-- 1 stephane stephane  22304 nov.  24 11:42 cosmetique-eco-charte-cosmebio.107x90.png
-rw-rw-r-- 1 stephane stephane  29245 nov.  24 11:42 cosmetique-bio-charte-cosmebio.130x90.png
-rw-rw-r-- 1 stephane stephane   7180 nov.  24 11:42 controle-de-la-mosquee-d-evry-courcouronnes.90x90.png
-rw-rw-r-- 1 stephane stephane   3820 nov.  24 11:42 commerce-equitable.96x90.png
-rw-rw-r-- 1 stephane stephane  24804 nov.  24 11:42 bleu-blanc-coeur.98x90.svg
[..]

They need to be named  like this:   name-of-the-label.[width]x90.png  where width is the width for the logo when it is 90 pixels high.
