### ISSUE TITLE
No palm oil ids

### ISSUE THREAD

**Issue by 3ph** [openfoodfacts/openfoodfacts-server#524]
Palm oil ingredients are detected but are exported as tags (ids to separate palm oil ingredients file). This id is different from main ingredient id so AFAIK there is no link between them.

The code causing this seems to be in lib / ProductOpener / Ingredients.pm line 570:
`push @{$product_ref->{$tagtype . '_tags'}}, $ingredients_classes{$class}{$ingredient_id}{id};`

I'm not sure what use are these tags but if it's not possible to change to $ingredient_id would it be maybe possible to add another field maybe `$product_ref->{$tagtype . '_ids'}` where the actual ids would be stored?

**Comment by teolemon** [comment]
https://en.wiki.openfoodfacts.org/Global_palm_oil_taxonomy

**Comment by aleene** [comment]
# 522?

**Comment by teolemon** [comment]
fixed @stephanegigandet @aleene
