### ISSUE TITLE
Non-vegan product marked as vegan

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#5249]
### What

https://world-fr.openfoodfacts.org/product/8718265015494/groente-loempia-albert-heijn

### Screenshot
![image](https://user-images.githubusercontent.com/1689815/119271472-008b0780-bc02-11eb-8bba-a5b4f0b8cf22.png)

### User report
Johan Vandingenen Hi, i noticed there’s a product marked as vegan (by analysis) but it contains egg. Is it a bug? Or is it a human error? https://world.openfoodfacts.org/product/8718265015494/groente-loempia-albert-heijn

### Part of
- #5706

**Comment by stephanegigandet** [comment]
It's not a bug, this product has the "Vegan" label, which has priority over ingredients analysis. There's a "Vega" logo on the product, not sure what that is. cc @aleene

**Comment by blazern** [comment]
Are you sure the ticket should be closed?
I mean, the problem could be avoided altogether if OFF would not give the "vegan" label to the product one of which ingredients is 100% non-vegan.

**Comment by cyclomaticcomplexity1981** [comment]
> It's not a bug, this product has the "Vegan" label, which has priority over ingredients analysis. There's a "Vega" logo on the product, not sure what that is. cc @aleene

The Albert Heyn "VEGA" logo refers to Vegetarian not Vegan. Do products with the VEGA logo automatically get the Vegan label?

**Comment by svensven** [comment]
maybe they typed "vega" into the app, and the spellchecker autocompleted it to vegan?

**Comment by stephanegigandet** [comment]
@blazern we could do that indeed, and create a separate data quality facet when the ingredients analysis does not agree with the label

**Comment by teolemon** [comment]
@benbenben2 a similar work would be useful for palm oil, gluten and more.
