### ISSUE TITLE
Improve write API's authentication failure response

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#525]
### What

If the users adds the wrong credentials in the write API, the response is a standard HTML-page.

It should respond with a json-file and add the failure as a separate status code.
### Code pointers
You can find some [code pointers here](https://github.com/openfoodfacts/openfoodfacts-server/blob/main/.github/labeler.yml). If some are missing, feel free to add them yourself in this file, or to ask them.

**Comment by hangy** [comment]
Totally agree and the change should be easy. However, I fear that some apps depend on the way that the "product_jqm2.pl" (jquery mobile?) file works right now. Maybe it would be better to fix authentication in general (user/password in the URI is bad) and "RESTfulness" (see #510) in the new API? A good RESTful option might be to enable `POST` and `PUT` to the /api/v0/product/12345 url.

**Comment by aleene** [comment]
Time to think about the next version of the api, which exist next to the old version (and supports versions).

**Comment by aleene** [comment]
too old
