### ISSUE TITLE
error on line 270 at column 30: Namespace prefix en for french on languages is not defined Below is a rendering of the page up to the first error.

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#526]
This page contains the following errors:
error on line 270 at column 30: Namespace prefix en for french on languages is not defined
Below is a rendering of the page up to the first error.

http://world.openfoodfacts.org/cgi/search.pl?search_terms=banania&search_simple=1&action=process&xml=1

**Comment by teolemon** [comment]
This page contains the following errors:

error on line 104 at column 31: Namespace prefix en for english on languages is not defined
Below is a rendering of the page up to the first error.

**Comment by teolemon** [comment]
http://world.openfoodfacts.org/cgi/search.pl?search_terms=coke&search_simple=1&xml=1

**Comment by stephanegigandet** [comment]
Fixed.
