### ISSUE TITLE
Use docker to install and maintain the openfoodfacts.net test server?

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#5275]
We currently run the test server (used by apps etc. to test the API) https://world.openfoodfacts.net on a very cheap (but that we have to pay) OVH server. We are going to replace that server with proxmox containers on much more powerful servers provided for free by OVH, so we need to move https://world.openfoodfacts.net to a proxmox container. (and also openfoodfacts.dev that we use for development)

I'm wondering if we should also try to use docker to install that instance of product opener and to keep it up-to-date. It would have the advantage of forcing us to keep the docker environment current and working, and so would facilitate things for developers.

It would probably require some changes though, as the product and images directories would be synchronized from production regularly. I'm guessing we might want to just bind all the data directories to the host filesystem instead of using docker volumes.

Any thoughts or suggestions?

**Comment by stephanegigandet** [comment]
I think one reason to use docker is that product opener has tons of dependencies (libraries, external programs, Perl modules) that are difficult to track.

**Comment by VaiTon** [comment]
I fully support the idea. It would also encourage us to build in "microservices" instead of a big monorepo.
