### ISSUE TITLE
Javascript error on Google Chrome: Uncaught TypeError: $(...).foundation is not a function

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#5279]
On Chrome, but not on Firefox, there is a javascript error that prevents some Foundation functions to work (in particular functions for the "equalizer" that resizes the height of the columns).

To reproduce:

1. https://mq-en.openfoodfacts.dev/cgi/user.pl
2. click on  "This is a producer or brand account. "
3. the columns are not resized and there is an error in the javascript console:

```
user.pl:689 Uncaught TypeError: $(...).foundation is not a function
    at HTMLInputElement.<anonymous> (user.pl:689)
    at HTMLInputElement.dispatch (jquery.js? [sm]:25)
    at HTMLInputElement.v.handle (jquery.js? [sm]:24)
```

**Comment by svensven** [comment]
the example works without errors for me in chrome 90 & 91.

**Comment by stephanegigandet** [comment]
@svensven thanks. it seems to be caused by the folksonomy engine user script, I forgot to test without it.

**Comment by CharlesNepote** [comment]
Closed by https://github.com/openfoodfacts/folksonomy_frontend/commit/776e648b2d4278e1eb7be78f688540ebe1422c68
