### ISSUE TITLE
Error in string 95<sup>th</supe> centile

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#531]
`95<sup>th</supe> centile`

**Comment by hangy** [comment]
http://en.wiki.openfoodfacts.org/Translations_-_Web_site_interface
https://bitbucket.org/openfoodfacts/product-opener/src/d94fd222841bff8d85bcb9c312d62fa1c7601272/lib/ProductOpener/Lang.pm?at=master&fileviewer=file-view-default
And maybe Launchpad?

nutrition_data_per_5 and nutrition_data_per_95

**Comment by teolemon** [comment]
Note @hangy edited your comment to point to GitHub
