### ISSUE TITLE
Update and Localize Google Play Badges

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#534]
https://play.google.com/intl/en_us/badges/

**Comment by hangy** [comment]
Do we still want to update the [wiki translation](http://en.wiki.openfoodfacts.org/Translations_-_Web_site_interface) or rather merge the `i18n-po` branch and continue with the [Launchpad translation](https://translations.launchpad.net/openfoodfacts/trunk/+pots/common-web/de/28/+translate)?

**Comment by teolemon** [comment]
@stephanegigandet @maddingue  any issues with merging po support and moving to Launchpad ?

**Comment by teolemon** [comment]
https://github.com/steverichey/google-play-badge-svg/tree/master/img
They have done the work of downloading them all and normalizing them.
Let's get it out of translations, to avoid broken images.

**Comment by teolemon** [comment]
fixed, and being deployed.
