### ISSUE TITLE
Add a promo for the mobile app if someone types a barcode that does not exist

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#538]
We have thousands of people typing barcodes in te search field. We should return barcode results in addition to regular results.

**Comment by teolemon** [comment]
Many people looking for a barcode currently leave the website immediately after searching for it (and not finding it)

**Comment by herau** [comment]
Why people not using the scanner instead of filling the barcode ?

**Comment by teolemon** [comment]
This happens on the website. Thus, no barcode scanner :-)

**Comment by aleene** [comment]
Not sure what the issue is. You can enter a barcode and search for it. And the search might fail. 

So what should happen?

**Comment by teolemon** [comment]
My bad. It actually works. So the data I get is for products which don't exist yet.
Thus: "This product doesn't exist yet. You can add it manually or using the mobile app" ?
