### ISSUE TITLE
Accept '+' in email address for registration

### ISSUE THREAD

**Issue by hydrargyrum** [openfoodfacts/openfoodfacts-server#544]
When I try to register, my email address is rejected as being supposedly invalid because it contains a '+', but it's [perfectly valid](http://emailregex.com/).

**Comment by hangy** [comment]
e-mail validation is a bit difficult. The best fast change is probably to use the `Email::IsEmail` module, which is a Perl port of isemail.info.

**Comment by hangy** [comment]
Fixed in 1e4920959553bfe0fcc4a36300f645ac0ef16c36, created [PR](https://bitbucket.org/openfoodfacts/product-opener/pull-requests/57) for internal review.

**Comment by hangy** [comment]
PR merged 895ccc7718635d04d1cfbe253dd255c12e8a7d37

**Comment by hydrargyrum** [comment]
@hangy when approximately will this be deployed on openfoodfacts.org?

**Comment by hangy** [comment]
No idea, sorry. @stephanegigandet?

**Comment by hangy** [comment]
It's live in production now, so do retry if you want. 👍

**Comment by hydrargyrum** [comment]
Indeed, it works, thank you!
