### ISSUE TITLE
support for gettext

### ISSUE THREAD

**Issue by kyzh** [openfoodfacts/openfoodfacts-server#55]
In order to provide a framework to do translation, productopener  should use gettext

**Comment by teolemon** [comment]
http://search.cpan.org/~pvandry/gettext-1.05/gettext.pm

**Comment by hangy** [comment]
Is this a duplicate of #3?

**Comment by teolemon** [comment]
use POSIX qw (setlocale);
use Locale::gettext;
use Locale::TextDomain ('script');

#And the messages to be translated/localized
print __"String to be translated/localized."; #or
print gettext("Another string to be translated/localized");

**Comment by teolemon** [comment]
solved by @stephanegigandet
