### ISSUE TITLE
Create a JSON version of the JQM compact search

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#554]
Rationale: 10X improvement in performance for the Android Search
URL: http://world.openfoodfacts.org/cgi/search.pl?search_terms=nutella&search_simple=1&action=process&jqm=1

**Comment by herau** [comment]
I think the API should take care about the `Accept` request header ( for example `application/json` instead of using query parameter like `json=1`).

**Comment by hangy** [comment]
> Rationale: 10X improvement in performance for the Android Search
URL: http://world.openfoodfacts.org/cgi/search.pl?search_terms=nutella&search_simple=1&action=process&jqm=1

Do you have a quick overview on how the output should be formatted and in how far it would be different from `?json=1`?

> I think the API should take care about the Accept request header ( for example application/json instead of using query parameter like json=1).

That would be cool, but some other APIs like OpenSearch do depend on different formats being available at different URLs. In general, I do like the "magic" behind content-negotiation, though. :)

**Comment by teolemon** [comment]
The same data as jqm=1 but in a json format.
For simple implementation, it could be a simple_json=1 parameter

**Comment by hangy** [comment]
Could the Android app also use the OpenSearch standard (see #605) or is that not enough information?

**Comment by herau** [comment]
@hangy do you have any sample of the json output of this api ? don't find any example in #605

**Comment by hangy** [comment]
There's no JSON, just RSS 2.0 with OpenSearch 1.1, pretty much the same as in the [example in the specs](http://www.opensearch.org/Specifications/OpenSearch/1.1#Example_of_OpenSearch_response_elements_in_RSS_2.0).

**Comment by herau** [comment]
Ok, so no match our JSON format requirement for the android app

**Comment by teolemon** [comment]
@hangy Here's what the new search looks like (kudos to @herau )
![image](https://cloud.githubusercontent.com/assets/1689815/22058442/2890a3f6-dd69-11e6-95a1-0dd0de7371ce.png)

**Comment by teolemon** [comment]
@stephanegigandet @hangy 
## Search
To sum up:
- same kind of minimal output as `https://world.openfoodfacts.org/cgi/search.pl?search_terms=nutella&search_simple=1&action=process&jqm=1`
- We need `product name, brand, quantity`
- `?simple_json=1`

It will dramatically speed up search in the new Android version for Open Food Facts and Open Beauty Facts.
## Product
- Also, if you can do a very lightweight product json
- `barcode, product name, brand, quantity, nutriscore`
- `number of uploaded images, whether an image is selected for ingredients, nutrition and front`
- `?simple_product_json=1`

**Comment by stephanegigandet** [comment]
Maybe we could just add a fields parameters. e.g. &fields=product_name,brands,quantity

**Comment by teolemon** [comment]
More modular. Better. +1 :-)

**Comment by stephanegigandet** [comment]
Added fields parameter, as in the product read API bug #623 : 

https://world.openfoodfacts.net/cgi/search.pl?search_terms=nutella&search_simple=1&action=process&json=1&fields=product_name,nutrition_grades_tags

**Comment by stephanegigandet** [comment]
Also works on facets: https://world.openfoodfacts.net/category/pizzas.json?fields=product_name,categories_tags,ingredients_text,image_front_small_url,nutrition_grades_tags
