### ISSUE TITLE
Serve Eco-Score data in the new KP API

### ISSUE THREAD

**Issue by jasmeet0817** [openfoodfacts/openfoodfacts-server#5541]
### Description
Serve eco score data in the new KP API

New KP API: https://docs.google.com/document/d/1vJ9gatmv8pCXxyOERmYD16jOKRWJpz1RaQQ5MEcTxms/edit#
Example JSON response: https://github.com/openfoodfacts/openfoodfacts-server/blob/main/html/files/knowledge_panel_test.json

### Acceptance criteria
Feature parity with the current API

### What would a demo look like
The API can be queried to see the results.

### Tasks
TBD

### Part of 
- #5493

**Comment by stephanegigandet** [comment]
This has been done and deployed.
