### ISSUE TITLE
You're seriously missing HTTPS

### ISSUE THREAD

**Issue by rugk** [openfoodfacts/openfoodfacts-server#556]
You should setup HTTPS for all your domains. E.g. http://world.openfoodfacts.org has no HTTPS and there one even submits login credentials (username & password).

**Comment by hangy** [comment]
Yes, this is a long standing problem. Unfortunately, there seeems to be no good way to cover all OFF/OBF domains with Let's Encrypt. #29 #256 #414

**Comment by rugk** [comment]
Why? You can include up to I think more than hundred subdomains in one LE cert.
And if one cert is not enough, just create another one.

**Comment by rugk** [comment]
Okay, so this issue is a dupe.
