### ISSUE TITLE
Add link to FDroid app

### ISSUE THREAD

**Issue by rugk** [openfoodfacts/openfoodfacts-server#557]
Your app is on FDroid. On the website there is however only the apk & Google Play link. I'd suggest to add a link/button for FDroid too.

**Comment by teolemon** [comment]
Yes. The current F-Droid one (Open Food) is the beta of the v2 (and will probably stay a beta). We need to change the namespace of the app to "org.openfoodfacts.scanner" and stabilize it a little before promoting it heavily on the website.

**Comment by teolemon** [comment]
https://github.com/openfoodfacts/OpenFoodFacts-androidApp/issues/105

**Comment by ArchangeGabriel** [comment]
I think that while updating for 0.8.0, a rename of openfoodfacts.github.scrachx.openfood and openfoodfacts.github.scrachx.openbeauty in F-Droid should be requested.

**Comment by teolemon** [comment]
@ArchangeGabriel We should. That will leave users in the dust for upgrades though

**Comment by ArchangeGabriel** [comment]
Won’t be the first app without a clean upgrade path. Last one was muPDF (https://f-droid.org/wiki/page/com.artifex.mupdfdemo), you should likely do what they did, i.e. add a message telling this app is deprecating and linking to the new one (you’ll probably have to see how to do that with F-Droid people).

**Comment by jo-so** [comment]
How about this issue? Is the current link <https://f-droid.org/de/packages/openfoodfacts.github.scrachx.openfood/> stable enough to be added to the website?

**Comment by jolesh** [comment]
Can we add it now? I am using the F-Droid app for some time and it looks perfectly stable for me.

**Comment by rugk** [comment]
Ah, this repository seems to have been renamed to "sever" or so, because I very certainly did not open it here, if this was named as such in 2016… woah, long ago…

Anyway, I found the link in the correct repo:
https://github.com/openfoodfacts/openfoodfacts-androidapp#test-it-on-your-phone-or-tablet

So it seems to be solved.

Only thing: The F-Droid screenshot and badge is horrible distorted:
![grafik](https://user-images.githubusercontent.com/11966684/104774697-6f99b080-5777-11eb-9f8a-350a75a52645.png)
