### ISSUE TITLE
Make it possible to navigate Product Opener using keyboard shortcuts

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#5577]
### What
Make it possible to navigate Product Opener using keyboard shortcuts
- [ ]  product edition (e)
- [ ]  product JSON (a)
- [ ]  view mode (v), etc.

Code is available here: https://github.com/openfoodfacts/power-user-script

**Comment by hangy** [comment]
Do we want it to be localized?

**Comment by teolemon** [comment]
I have moved the bug to the previous one where we discussed on
