### ISSUE TITLE
No color differentiation between selected and unselected images in EDIT mode

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#5600]
### Describe the bug

When selecting images for cropping, deletion… There's no more color differentiation between selected and unselected images in EDIT mode as shown here:
![image](https://user-images.githubusercontent.com/1689815/131976958-9969c7f8-a591-4a62-9612-9b8816c43b44.png)

### To Reproduce

1. Go in edit mode
2. Try to select an image

### Expected behavior

I expect to see a different color like shown here: 
![image](https://user-images.githubusercontent.com/1689815/131977405-3ea76016-9529-4fd1-8ba5-3ab02d3da688.png)

### Part of 
- #5525

**Comment by CharlesNepote** [comment]
The issue is due to Power User Script, see https://github.com/openfoodfacts/power-user-script/issues/56
