### ISSUE TITLE
When moving pictures using the change main language feature, packaging is not mentioned in the changelog

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#5657]
When moving pictures using the `change main language` feature, packaging is not mentioned in the changelog

September 12, 2021 at 2:08:50 PM CEST - teolemon Selected images (Added: ingredients_es, front_es, nutrition_es) (Deleted: nutrition_fr, ingredients_fr, front_fr) -- Data (Added: product_name_es) (Changed: lang) (Deleted: product_name_fr) - view

Example = https://world.openfoodfacts.org/product/8410131001081/rianxeira-tony-oli

**Comment by hangy** [comment]
I think the packaging image is simply not moved. https://world.openfoodfacts.org/api/v2/product/8410131001081.json?rev=13 has a packaging image marked as French, https://world.openfoodfacts.org/api/v2/product/8410131001081.json?rev=14 doesn't have a packaging image in Spanish, but still has one in French: https://fr.openfoodfacts.org/api/v2/product/8410131001081.json?rev=14
