### ISSUE TITLE
Investigate the possibility of exposing producers to Hunger Games

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#5673]
### What
We have the ability to filter insights by brands. If we could empower brand to complete easily whatever data is missing, either on the production base (or in their private space with a 2nd custom install of Hunger Games), that would be great
https://hunger.openfoodfacts.org/questions?brand=tesco&type=label

### Part of
- #5521

**Comment by manon-corneille** [comment]
+1
