### ISSUE TITLE
The country taxonomy mention GB as the official UK country-code while the Eco-Score API wants UK 

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#5694]
The country taxonomy mention GB as the official UK language while the Eco-Score API wants UK 
https://static.openfoodfacts.org/data/taxonomies/countries.json

**Comment by stephanegigandet** [comment]
Everything seems correct.

country_code_3: {
en: "GBR"
},
languages: {
en: "en"
},
official_country_code_2: {
en: "GB"
},
country_code_2: {
en: "UK"
}

We use country_code_2.

**Comment by teolemon** [comment]
I have added proper documentation of this : https://openfoodfacts.github.io/api-documentation-staging/#jump-7Metadata-ListCountries
