### ISSUE TITLE
Producers want more flexibility on which image is used in the platform

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#5714]
### What

- Producers want more flexibility on which image is used in the platform

``` 3 / Retrieving visuals in OFF: we understand that you only retain the "isprimaryfile" flag but it is important for us that you also take into account the other visual metadata and especially the start and end dates of validity```

### Part of 
- #5521

**Comment by stephanegigandet** [comment]
We only select the front image, and a newer image will replace the older one. What do you want to do with the start and end dates?
