### ISSUE TITLE
Expose more information to the Producer Platform Admins (with mockup)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#5719]
### Who for
- admins and moderators
### What

- [ ] Expose more information to the Producer Platform Admins (with mockup)
  - [ ] #2910

### Mockup
![image](https://user-images.githubusercontent.com/1689815/134162444-f126fedb-058e-4027-b029-74731d07333f.png)

### Why
- Save time
- Ensure we keep on top

### Part of
- #5521

**Comment by manon-corneille** [comment]
I close the issue but include your idea in the proposition for a producer' dashboard :)
