### ISSUE TITLE
Allow setting locale when using SSL API URL

### ISSUE THREAD

**Issue by norganna** [openfoodfacts/openfoodfacts-server#573]
When using the ssl-api url (https://ssl-api.openfoodfacts.org/) it would be good to be able to set the desired locale via a header as you can't add a country code to the subdomain (ie: ssl-api-fr.openfoodfacts.org is not the CN of the certificate, and besides the current code would try to match the country "api" anyhow).

It would be good to allow setting the desired locale via a header such as `X-LOCALE: fr` or something of the ilk.

**Comment by teolemon** [comment]
We deployed HTTPS for OFF and are going to do it for OBF. Does it solve the issue ? 
Can you file a new one specific to ```X-LOCALE: fr```?

**Comment by norganna** [comment]
If you don't mind people using fr.openfoodfacts.org for api usage?

I had assumed you want to make api usage on a seperate subdomain for possible traffic isolation/partitioning at some later date?

**Comment by stephanegigandet** [comment]
You will be able to set the locale in the query part of the url: https://github.com/openfoodfacts/openfoodfacts-server/issues/271#issuecomment-270658906

**Comment by hangy** [comment]
I think we can close this, as #271 is done, and we have a wildcard SSL certificate for the country-based subdomains.
