### ISSUE TITLE
Edam Sprint Goals

### ISSUE THREAD

**Issue by gcalsmith** [openfoodfacts/openfoodfacts-server#5739]
- [Jasmeet/Slava] Summary Card implementation
- documentation for design pattern
- [Martin] Deploying to pre-prod product level score calculation
- determining new requirements
- [Stephane] Making progress on server side implementation of API for Summary Card & Eco Score
- [Olivier] Continuing:  Deploy to Robotoff dev
- Automate PO releases
- [Cal] Updating PRD for Summary Card based on feedback, starting Eco Card PRD
- [Tim] First UX for Eco Card

**Comment by teolemon** [comment]
fixed. Thanks @gcalsmith
