### ISSUE TITLE
The move image to another product tool has a harcoded url in the confirmation message

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#574]
```Successfully sent image to http://world.openfoodfacts.org/produit/3273120022918```
It should be product

**Comment by hangy** [comment]
Worked fine for me on my test server:

    <div id="moveimagesmsg">Images moved → <a href="/product/20002251">20002251</a></div>

Also, the product url doesn't seem to be hard coded in [product_image_move.pl](https://github.com/openfoodfacts/openfoodfacts-server/blob/920d13efc4ffd4c77c3bfdd0d1ece409eb230f41/cgi/product_image_move.pl#L172)

    $response{url} = product_url($move_to);

Actually, I cannot find the string at all in the Product Opener source. 😕 ("Successfully" doesnt exist anywhere in `master` (outside of Leaflet.markercluster)).

**Comment by teolemon** [comment]
Let me try this again.

**Comment by hangy** [comment]
The translations are in the following locations. Please reopen if you can still reproduce. 🙂 

https://github.com/openfoodfacts/openfoodfacts-server/blob/cea7e9f07390a346c213655aacb41c5ddb2c562a/cgi/product_multilingual.pl#L1085
https://github.com/openfoodfacts/openfoodfacts-server/blob/12f4375984221aaf6c9465c20b8f9a85164c47bc/po/common/common.pot#L1947-L1949
