### ISSUE TITLE
typo ?

### ISSUE THREAD

**Issue by OpenChris** [openfoodfacts/openfoodfacts-server#5742]
https://github.com/openfoodfacts/openfoodfacts-server/blob/15caacb4c1d2d659bc9eefbf62fb3c092aa8daa8/lib/ProductOpener/Ecoscore.pm#L459

variable name is "packaging_m**e**terials" : is that correct ? Typo also appears once later in the file.

**Comment by teolemon** [comment]
nice catch 👍 
Can you make a PR ?

**Comment by stephanegigandet** [comment]
@OpenChris fixed, thank you!

**Comment by OpenChris** [comment]
Ha ha ! Thanks Stéphane, I was desperately trying to remember how to make a PR ;-) but you're too fast !
