### ISSUE TITLE
Add link to the Ubuntu Mobile app

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#575]

**Comment by hangy** [comment]
Do you happen to have an Ubuntu appstore button with about the same dimensions as the Android/iOS button? I can't seem to find anything that resembles these buttons.

**Comment by stephanegigandet** [comment]
Is this still needed?

**Comment by stephanegigandet** [comment]
I'm guessing this is not needed anymore, closing.
