### ISSUE TITLE
Add facet to identify products with all ingredients with specified percent

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#5763]
### Is your feature request related to a problem? Please describe.

Needed in particular to verify the accuracy of percent estimate computations.

### Describe the solution you'd like

Add stats for each product:

Compute the total % of "leaf" ingredients (without sub-ingredients) with a specified %, and unspecified %.

- ingredients_with_specified_percent_n : number of "leaf" ingredients with a specified %
- ingredients_with_specified_percent_sum : % sum of "leaf" ingredients with a specified %
- ingredients_with_unspecified_percent_n
- ingredients_with_unspecified_percent_sum	

And data quality facets:

en:all-ingredients-with-specified-percent
en:all-but-one-ingredient-with-specified-percent (if there's only one ingredient missing %, then it's easy to compute it)
en:sum-of-ingredients-with-unspecified-percent-lesser-than-10 (for some users, we may be able to ignore a few small ingredients like flavours etc.)
en:sum-of-ingredients-with-specified-percent-greater-than-100 (can happen when water evaporates)
en:sum-of-ingredients-with-specified-percent-greater-than-200 (is probably an error)

**Comment by teolemon** [comment]
fixed by #5764
