### ISSUE TITLE
Producer Platform - Broken link for products that don't exist yet on the public database

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#5771]
### What

- [ ] Producer Platform - Broken link -  `→ Product page on the public database`

### Code Pointer

- https://github.com/openfoodfacts/openfoodfacts-server/blob/9b7ddf4ec0d381e730691aafe2d8448050503fdf/templates/web/pages/product/product_page.tt.html#L47

### Screenshot
![image](https://user-images.githubusercontent.com/1689815/134898577-a6861d62-7371-47e1-8eda-b4c4428d4a02.png)

### Part of
- #5521

**Comment by stephanegigandet** [comment]
We could add a check to see if the product exists in the public database and display a special message if it does not exist.

**Comment by teolemon** [comment]
It would be extra nice but the issue is just templating and concatenation

**Comment by stephanegigandet** [comment]
> It would be extra nice but the issue is just templating and concatenation

Ahhh. For some reason it's only for world.pro, I was checking on fr.pro and everything was looking fine.
