### ISSUE TITLE
Broken banner for English and most other languages except French, German and Spanish

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#5776]
![image](https://user-images.githubusercontent.com/1689815/135090283-e383b683-c82b-46c5-8974-df61d0334b5a.png)
https://uk.openfoodfacts.org/product/7616700037531/brioche-safran-migros

**Comment by stephanegigandet** [comment]
Translations are missing, even in English for those strings:

msgctxt "donation_title"
msgid "Important: we need your support!"
msgstr "" 

msgctxt "donation_body"
msgid "Open Food Facts is a collaborative project built by tens of thousands of volunteers and managed by a non-profit organization with 3 employees."
msgstr "" 

msgctxt "donation_why"
msgid "We need your donations to fund the Open Food Facts 2021 budget and to continue to develop the project. <strong>Thank you! ❤️</strong>"
msgstr "" 

msgctxt "donation_cta"
msgid "Donate"
msgstr "" 

I'll add them to en.po
