### ISSUE TITLE
Donation baner is empty

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#5786]
### Describe the bug

At least for us, uk, es.openfoodfacts.org.

![image](https://user-images.githubusercontent.com/562352/135299104-859ff70d-5480-4dcc-af58-da1c59945926.png)

### To Reproduce

Go to https://es.openfoodfacts.org/

### Expected behavior

...

### Type of device

Browser

**Comment by teolemon** [comment]
Duplicate of #5776 
Fixed by #5784
