### ISSUE TITLE
Nutrition values for extra small serving (e.g. less than 1 g spray) cannot be extrapolated to 100g

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#5848]
### Is your feature request related to a problem? Please describe.

As of today (2021-10) we have 149 oils that should be Nutri-Score C, at most, but which are B (0.95% of the category). Nearly all these products are sprays. Producers are displaying nutrition facts per serving. As a serving represent less than 1g (spray), all the values are 0. Eg, https://world.openfoodfacts.org/product/0077890440834/olive-oil-cooking-spray-wegmans
This has bad effects:
- the products seem very healthy (!)
- the Nutri-Score is wrong
- we can't compare the products
- etc.

### Describe the solution you'd like

To be discussed
* Nutri-Score is not shown if all values are 0 and category is different from mineral waters, etc.? + alert to the user
* Nutri-Score not shown if product has values too different from category mean? + alert to the user
* Values not exported (json, api, CSV) if all values are 0 and category is different from mineral waters, etc.

### Number of products
* [Number of products with `serving_quantity` <= 10 g](https://mirabelle.openfoodfacts.org/products?sql=--+Products+with+a+data+quality+errors+and+serving_size+%0D%0Aselect+count+%28*%29+%0D%0A--code%2C+url%2C+serving_size%2C+serving_quantity%2C+data_quality_errors_tags%0D%0Afrom+%5Ball%5D%0D%0Awhere+%0D%0Aserving_size+%21%3D+%22%22%0D%0Aand+serving_quantity+%3C%3D+10%0D%0A--and+data_quality_errors_tags+%21%3D+%22%22%0D%0Aorder+by+random+%28%29%0D%0Alimit+100): ~47000 (2022-12)
* [Number of products with `serving_quantity` <= 10 g and a data quality error](https://mirabelle.openfoodfacts.org/products?sql=--+Products+with+a+data+quality+errors+and+serving_size+%0D%0Aselect+count+%28*%29+%0D%0A--%2C+code%2C+url%2C+serving_size%2C+serving_quantity%2C+data_quality_errors_tags%0D%0Afrom+%5Ball%5D%0D%0Awhere+%0D%0Aserving_size+%21%3D+%22%22%0D%0Aand+serving_quantity+%3C%3D+10%0D%0Aand+data_quality_errors_tags+%21%3D+%22%22%0D%0Alimit+100): 7100+ (2022-12)
* [Still 3965 products with `serving_quantity` <= 2 g](https://mirabelle.openfoodfacts.org/products?sql=--+Products+with+a+data+quality+errors+and+serving_size+%0D%0Aselect+count+%28*%29+%0D%0A--%2C+code%2C+url%2C+serving_size%2C+serving_quantity%2C+data_quality_errors_tags%0D%0Afrom+%5Ball%5D%0D%0Awhere+%0D%0Aserving_size+%21%3D+%22%22%0D%0Aand+serving_quantity+%3C%3D+2%0D%0Aand+data_quality_errors_tags+%21%3D+%22%22%0D%0Alimit+100)

**Comment by john-gom** [comment]
I did some simple queries looking for products that indicate that the nutriscore can be computed but have zero quantities of the following nutrients:

- energy
- carbohydrates
- salt
- calcium

`{"misc_tags":"en:nutriscore-computed", $and: [{$or:[{"nutriments.energy":0}, {"nutriments.energy": {$exists: false}}]},{$or:[{"nutriments.carbohydrates":0}, {"nutriments.carbohydrates": {$exists: false}}]}, {$or:[{"nutriments.salt":0}, {"nutriments.salt": {$exists: false}}]}, {$or:[{"nutriments.calcium":0}, {"nutriments.calcium": {$exists: false}}]}]}`

Looking at the results I'm not sure that a nutriscore should be calculated for any of them as either the serving is too small or there is is some problem with the data.

Previous comments mention still including mineral waters for nutriscore, but is this even appropriate. Would be simpler to not calculate the nutriscore at all of key nutrients are either missing or all zero?

**Comment by stephanegigandet** [comment]
Hi @john-gom, thanks a lot for the investigation into US rules. I think we should stick to a simpler rule: if serving size is less than 5g (or 10g), then we don't extrapolate any nutrient to 100g. Otherwise it will very weird and difficult to understand if we have some nutrients and not others. And the fact that a nutrient is 0g doesn't make much difference I think. If fat is 1g and serving size is 5g, the 100g value could be 10.1g or 29.9g...

**Comment by john-gom** [comment]
I've changed the code to simply not calculate 100g figures from serving figures if the serving quantity <= 5. However, this looks like it would only affect around 500 products based on the following query:

```
[
  {
    $match:
      {
        nutrition_data: "on",
        nutrition_data_per: "serving",
        serving_quantity: {
          $ne: 0,
          $lte: 5,
        },
      },
  },
  {
    $count:
      "string",
  },
]

```
