### ISSUE TITLE
Cordova Android app unable to upload images if we 301 redirect http to https

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#593]
App wrongly says "success", but image is not on the server.

**Comment by stephanegigandet** [comment]
Product search, barcode scan, and adding textual information (e.g. product name) did work.

**Comment by stephanegigandet** [comment]
Short answer: requests with POST data (e.g. images upload) cannot be reliably redirected.

We could redirect all GET queries I guess.

**Comment by hangy** [comment]
Probably an issue in the app, not the server. HTTP clients should discard POST data when getting a 301 redirect, so the app should be updated to POST to the HTTPS URL instead.

**Comment by stephanegigandet** [comment]
The app will be updated, at some point, but there are many apps out there. The idea is to see if we can instruct the server now to send 301 redirects to https when it receives http requests. I'm thinking it's probably safe to do it for GET requests (hopefully most browsers and apps will just handle that without any change). And we will tell apps developers to change their queries to https.

**Comment by stephanegigandet** [comment]
The cordova app has been replaced by a native iOS app.
