### ISSUE TITLE
Add ecoscore and nutriscore to dev data

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-server#5959]
### Is your feature request related to a problem? Please describe.

When you use make dev, which create a dataset for development, products in database have neither nutriscore nor ecoscore. This make testing of features around those themes. difficult.

### Describe the solution you'd like

dev data should have some realistic eco-score and nutriscore value (taken from production db I think).

**Comment by stephanegigandet** [comment]
We now have a nightly export of ~100 random products:

-rw-r--r-- 1 off off      2438275 Nov  9 06:08 products.random-modulo-10000.tar.gz
-rw-r--r-- 1 off off    674410370 Nov  9 06:10 products.random-modulo-10000.images.tar.gz

The import is used in import_sample_data.sh
