### ISSUE TITLE
Labels from Mexican ministery of health

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#5967]
### Is your feature request related to a problem? Please describe.

In 2020 Mexico has voted mandatory labels on front of pack:
* Exceso calorías
* Exceso azúcares
* Exceso grasas saturadas
* Exceso grasas trans
* Exceso sodio
* Contiene edulcorantes, no recomendable en niños
* Contiene cafeína evitar en niños

With the mention "Secretaría de salud".

Currently, we don't have this labels in our label's taxonomy, and the first products with these labels are entering the database. See:
* https://world.openfoodfacts.org/product/7501023505211/chilorio-el-original-chata
* https://world.openfoodfacts.org/product/000500201855/nutella
* etc.

Some contributors started to add the label. Eg. https://world.openfoodfacts.org/label/es:exceso-de-azucares

### Describe the solution you'd like

How to enter these values? Other countries or label systems could reuse these labels because these are common names, eg. _Exceso calorías_.

Should we use something more clear, such as: **es:Exceso calorías (Secretaría de Salud de México)**

**Comment by CharlesNepote** [comment]
More information:
* https://es.wikipedia.org/wiki/Etiquetado_de_alimentos_en_M%C3%A9xico
* https://en.wikipedia.org/wiki/Food_labeling_in_Mexico

File to be changed: https://github.com/openfoodfacts/openfoodfacts-server/blob/main/taxonomies/labels.txt

## Suggestion [to be investigated]
```
# Food labeling in Mexico
# https://en.wikipedia.org/wiki/Food_labeling_in_Mexico
# Example: https://world.openfoodfacts.org/product/7501023505211/chilorio-el-original-chata
es:Sistema de Etiquetado Frontal de Alimentos y Bebidas - SEFAB, SEFAB, NOM-051, NOM-051-SCFI/SSA1-2010
xx:Sistema de Etiquetado Frontal de Alimentos y Bebidas - SEFAB, SEFAB, NOM-051, NOM-051-SCFI/SSA1-2010

# ???
<es:es:Sistema de Etiquetado Frontal de Alimentos y Bebidas - SEFAB
es:Exceso calorías - Secretaría de Salud de México
xx:Exceso calorías - Secretaría de Salud de México

es:Exceso azúcares - Secretaría de Salud de México
xx:Exceso azúcares - Secretaría de Salud de México

es:Exceso grasas saturadas - Secretaría de Salud de México
xx:Exceso grasas saturadas - Secretaría de Salud de México

es:Exceso grasas trans - Secretaría de Salud de México
xx:Exceso grasas trans - Secretaría de Salud de México

es:Exceso sodio - Secretaría de Salud de México
xx:Exceso sodio - Secretaría de Salud de México

es:Contiene edulcorantes, no recomendable en niños - Secretaría de Salud de México
xx:Contiene edulcorantes, no recomendable en niños - Secretaría de Salud de México

es:Contiene cafeína evitar en niños - Secretaría de Salud de México
xx:Contiene cafeína evitar en niños - Secretaría de Salud de México
```

**Comment by stephanegigandet** [comment]
Long names are ok, but they cannot contain commas (Contiene edulcorantes, no recomendable en ninos -> use a dash instead)
