### ISSUE TITLE
Broken ingredients tests in main branch - turmeric

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#5981]
### Describe the bug

Tests are failing for all PRs, it looks like the turmeric change broke the tests:

```
Failed test at t/ingredients.t line 368.
# 
#     Structures begin differing at:
#          $got->{ingredients_hierarchy}[1] = 'en:e100'
#     $expected->{ingredients_hierarchy}[1] = 'en:turmeric'
# 
# {
```

### To Reproduce

Run the tests ingredients.t

### Expected behavior

Tests should pass.

### Type of device

Other

**Comment by aleene** [comment]
Where did that come from? An old version got pushed?
