### ISSUE TITLE
refresh_taxonomies.js does not refresh the ingredients taxonomy when an included taxonomy source (e.g. additives) change

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#5985]
### Describe the bug

There is a github workflow to rebuild taxonomies that have their source file (e.g. category.txt) newer than the build file (category.result.sto).

This does not work for the ingredients taxonomy that automatically includes other categories such as additives.

### To Reproduce

Change additives.txt

### Expected behavior

Both additives and ingredients taxonomy should rebuild

### Type of device

Other

**Comment by alexgarel** [comment]
FYI there is now a make script instead of the js script (yet to be used in github workflows)

See build_taxonomies in Makefile

**Comment by alexgarel** [comment]
I think we can close this one. @john-gom has developped a system to cache taxonomies and it take into account included taxonomies: in Tags.pm, the get_from_cache function use @files list which includes sub taxonomies.
