### ISSUE TITLE
Add a special badge for Apps that contribute to Open Food Facts

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#599]
"App" badge with a link to the official website/App store page
DateLimite, CanIEatThisApp…

**Comment by aleene** [comment]
Are you talking about some sort of certification thing?

**Comment by teolemon** [comment]
Nope, just a way to spot app accounts without having to track them separately.
We could also do that for mass edit accounts.
We try to ask for an app suffix, but that is not always the case.

**Comment by aleene** [comment]
Still not sure what you mean. It sounds like yoy want to know the client an user uses to update OFF. Just username is not sufficient. You can list the default usernames the apps are using (not that many).
