### ISSUE TITLE
On web lists of products, add the product's barcode to its front picture, next to the Nutri-score and Eco-score

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#5994]
### Is your feature request related to a problem? Please describe.

[From @chevalstar report] When viewing web lists of similar products (eg. products with the same name such as "Vache qui rit'), it is not possible to make a difference between all the products shown: they share the same Nutri-Score and Eco-Score, the front picture is nearly the same. You have to open all the products manually to see the difference (barcode) between each product.

### Describe the solution you'd like

Some users would like to have the barcode displayed next to the Nutri-Score and the Eco-Score.

Ideally, the 4 last numbers should be in highlighted (bold or something like that).

**Comment by alexgarel** [comment]
We have seen with @stephanegigandet 

- put the settings in user settings (not in search prefs, as this is used for smoothie)
- use material designs icons and reuse the edit icons already used on product page

So there I am back to the starting point ;-)
