### ISSUE TITLE
Incorrect nesting of nutrients and sub-nutrients in /cgi/nutrients.pl API

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#5997]
### Describe the bug

https://world.openfoodfacts.org/cgi/nutrients.pl returns a nested structure with nutrients so that apps can know how to display nutrition table, in which order etc. (the result varies based on the country code cc parameter).

The nutrients are not nested correctly though.

e.g.

```
{
name: "Carbohydrates",
nutrients: [
{
name: "Sugars",
nutrients: [
{
name: "Sucrose",
nutrients: [
{
id: "glucose",
important: false,
display_in_edit_form: false,
name: "Glucose"
},
{
id: "fructose",
important: false,
display_in_edit_form: false,
name: "Fructose"
},
{
name: "Lactose",
display_in_edit_form: false,
important: false,
id: "lactose"
},
{
important: false,
display_in_edit_form: false,
id: "maltose",
name: "Maltose"
},
{
name: "Maltodextrins",
id: "maltodextrins",
important: false,
display_in_edit_form: false
},
{
name: "Starch",
display_in_edit_form: false,
important: false,
id: "starch"
},
{
display_in_edit_form: false,
important: false,
id: "polyols",
name: "Sugar alcohols (Polyols)"
},
{
id: "fiber",
display_in_edit_form: true,
important: false,
name: "Fibers"
},
{
name: "Soluble fiber",
id: "soluble-fiber",
display_in_edit_form: false,
important: false
},
{
id: "insoluble-fiber",
display_in_edit_form: false,
important: false,
name: "Insoluble fiber"
}
],
important: false,
display_in_edit_form: false,
id: "sucrose"
}
],
id: "sugars",
important: false,
display_in_edit_form: true
}
],
important: true,
display_in_edit_form: true,
id: "carbohydrates"
},
```

### To Reproduce

https://world.openfoodfacts.org/cgi/nutrients.pl 

### Expected behavior

Nutrients should be in the order defined in Food.pm

### Additional context

Reported by @monsieurtanuki : https://github.com/openfoodfacts/openfoodfacts-dart/issues/210#issuecomment-945765672

### Type of device

REST-API

**Comment by monsieurtanuki** [comment]
Not 100% related, but there seems to be a little difference between `https://fr.off...` and `https://world.off/?cc=fr` links.
In the first case, the (default) language seems to be deduced from the country.
In the second case, the language is the default (English) language, regardless of the country.
I heard that we were supposed to use rather the "https://world?cc=" syntax, but there's a side effect.
* ok "Énergie (kJ)" https://fr.openfoodfacts.org/cgi/nutrients.pl
* KO "Energy (kJ)" https://world.openfoodfacts.org/cgi/nutrients.pl?cc=fr
* ok "Énergie (kJ)" https://world.openfoodfacts.org/cgi/nutrients.pl?cc=fr&lc=fr

**Comment by stephanegigandet** [comment]
> Not 100% related, but there seems to be a little difference between `https://fr.off...` and `https://world.off/?cc=fr` links.

It is the expected behaviour. If you use a subdomain like [country code].openfoodfacts.org, it will set a default country cc and a default language lc. For instance ch.openfoodfacts.org will set the country to Switzerland, and the language to German.

If you use ?cc= or ?lc= to override the country or language, it will work, but setting ?cc will only override the country, it will not set a default language.

You can do this: https://world.openfoodfacts.org/cgi/nutrients.pl?cc=fr&lc=fr

One thing about the nutrients.pl API is that you will get different results per country (which nutrients and in which order), and by language (translation of the name of the nutrient).

**Comment by monsieurtanuki** [comment]
@stephanegigandet Understood.
As we are supposed from now on to use the `world.` domain in off-dart, I've made the language parameter mandatory in https://github.com/openfoodfacts/openfoodfacts-dart/pull/272.
