### ISSUE TITLE
Display a health message for Alcohol in France

### ISSUE THREAD

**Issue by TaciteOFF** [openfoodfacts/openfoodfacts-server#60]
"Toute publicité en faveur de boissons alcooliques, (…), doit être assortie d'un message de caractère sanitaire précisant que l'abus d'alcool est dangereux pour la santé."

http://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006072665&idArticle=LEGIARTI000006688013

**Comment by teolemon** [comment]
We should see if it actually applies to us, and if so display a warning.
