### ISSUE TITLE
Docker: product pictures are not shown

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#6025]
### Describe the bug

Fresh docker install following the [quick start guide](https://github.com/openfoodfacts/openfoodfacts-server/blob/main/installation/dev-environment-quick-start-guide.md): pictures are 404.

Even `make import_sample_data` does nothing.

### To Reproduce

Follow https://github.com/openfoodfacts/openfoodfacts-server/blob/main/installation/dev-environment-quick-start-guide.md

### Expected behavior

Picture should be displayed.

### Type of device

Browser

**Comment by alexgarel** [comment]
@ocervell this bug is fixed isn't it ?

**Comment by ocervell** [comment]
yes
