### ISSUE TITLE
Create an edit rule for halal-app-chakib

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#6043]
Create an edit rule for halal-app-chakib since the app stores French translation of the categories in English, thus destroying Eco-Scores and Nutri-Scores
https://world.openfoodfacts.org/product/4056489012481/nectar-de-goyave-solevita#

October 30, 2021 at 6:41:21 PM CEST - halal-app-chakib Data (Changed: categories) -- Nutriments (Changed: nutrition-score-fr) - (app)added with the allergy Android app - view

### Code pointers
[Edit rules](https://github.com/openfoodfacts/openfoodfacts-server/blob/a139e327cabab0fd2f2dbeee358a0672a5530806/lib/ProductOpener/Config_off.pm#L185)

### Part of
- #5538

**Comment by teolemon** [comment]
Still an issue, on very popular products: https://world.openfoodfacts.org/product/5449000131836/coca-cola-zero

**Comment by aleene** [comment]
The app also creates a lot of empty products.

**Comment by alexgarel** [comment]
Could we do this on robotoff side ? A bit like the idea of check spelling, if a category, label, etc. has just a language mismatch, fix it.

**Comment by teolemon** [comment]
Here's the place where edit rules live: 
https://github.com/openfoodfacts/openfoodfacts-server/blob/main/lib/ProductOpener/Config_off.pm#L204

And yes, I'm commenting because of a broken product I spotted
