### ISSUE TITLE
Write API emb_codes

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#608]
The write API for emb_codes does not work, i.e. the data is not changed.

For instance: https://ssl-api.openfoodfacts.org/cgi/product_jqm2.pl?code=3560070514847&emb_codes=Test

**Comment by teolemon** [comment]
https://ssl-api.openfoodfacts.org/cgi/product_jqm2.pl?code=3560070514847&emb_codes_tag=Test

**Comment by aleene** [comment]
It is working now. However it (was?) is not a write issue.

It turns out that I did not understand the json-keys for emb-codes:
- `emb-codes` gives the data as the user entered it;
- `emb_codes_orig` gives an OFF-filtered version (which is why my 'test' never turned up);

**Comment by teolemon** [comment]
Can I thus close ?

**Comment by aleene** [comment]
too old
