### ISSUE TITLE
Keep the edit and save button always visible in the edit page (responsive mode)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#609]
Keep the edit and the save buttons always visible in the product and edit pages. 
Currently you have to scroll down to the bottom of the page to save.

![image](https://cloud.githubusercontent.com/assets/1689815/21927797/9ea09730-d987-11e6-873a-6345e880ddc8.png)

This is really important for the new mobile app that lets you edit products.

**Comment by hangy** [comment]
Just positioning the rectangular button with `bottom: 45px; right: 24px; position: fixed; z-index:9999999;` looks a bit out of place. Do you think we should make it circular like the the [fab](https://material.io/guidelines/components/buttons-floating-action-button.html)? 
![capture](https://cloud.githubusercontent.com/assets/87124/21954455/63f0c0e0-da51-11e6-818e-a19c77d1ec4e.PNG)

**Comment by teolemon** [comment]
Not necessary.

**Comment by teolemon** [comment]
You can add a shadow if you want to make it clearer.

**Comment by stephanegigandet** [comment]
It looks a bit odd when the Save is going into the footer, but I guess I need to get used to it.

![image](https://user-images.githubusercontent.com/8158668/36357457-8b5a2fa2-14fe-11e8-8003-7d6ca1b98512.png)

**Comment by teolemon** [comment]
Perhaps adding  a white edge to edge background ?
