### ISSUE TITLE
Return an explanation for Eco-Score exemptions

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#6092]
## What
The eco-score does not grade bottled waters, and there's no way to know why.

## Describe the solution you'd like

- [ ] Return an explanation for Eco-Score exemptions, and a suggestion to drink tap water or self-carbonated water.
- [ ] Expose this explanation in knowledge panels and in the legacy HTML methodology

## Part of
- #5520 
- #5493

**Comment by teolemon** [comment]
"L'Eco-Score n'est pas encore dispo pour cette catégorie."

**Comment by alexgarel** [comment]
@teolemon it's not in current sprint ?

**Comment by alexgarel** [comment]
@teolemon we got two options here:

- continue to consider this as "nutriscore unknown" but adapt messages
- consider it as a new status: "nutriscore not applicable"
- a mix of those (continue to put it as unknown but use a specific panel instead of ecoscore_unknown.tt.json)

Would you also like a different icon ?

**Comment by stephanegigandet** [comment]
@alexgarel It should be "Eco-Score not applicable", as we do for "Nutri-Score not applicable".

In fact we already compute it:

https://uk.openfoodfacts.org/eco-score/not-applicable

ecoscore_data: {
adjustments: { },
ecoscore_not_applicable_for_category: "en:sodas",
status: "unknown"
},
ecoscore_grade: "not-applicable",
ecoscore_tags: [
"not-applicable"
],

And we will need a different icon, similar to the Nutri-Score not applicable icon.

**Comment by stephanegigandet** [comment]
Discussed with @teolemon and @alexgarel:

- New messages : "Eco-Score not applicable", "Nutri-Score not applicable".
- Color should be grey.
- Icon to be discussed. (maybe just an outline).
