### ISSUE TITLE
People asking for Reset password process do not receive an email

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#6110]
### Describe the bug

Many people are writing us that they don't receive any email when they ask for reset password process.

I tested today (2021-11-24), and I don't receive anything either.

### To Reproduce

* Log out if necessary.
* Ask for a new password via https://world.openfoodfacts.org/cgi/reset_password.pl
* Wait...

### Expected behavior

An email should be received.

**Comment by stephanegigandet** [comment]
It works for me, with my email hosted on OVH.

I just tested with https://www.mail-tester.com/ as well, the email is ok.

![image](https://user-images.githubusercontent.com/8158668/144575721-cb0f7e6d-f94b-4092-a1e0-104a2e62065a.png)

**Comment by stephanegigandet** [comment]
Looks like an issue with gmail, we have errors like this one in /var/log/exim4 

2021-12-03 06:36:19 1msI9j-000XTg-MK ** contact@openfoodfacts.org R=dnslookup T=remote_smtp H=a
spmx.l.google.com [66.102.1.26] X=TLS1.2:ECDHE_ECDSA_CHACHA20_POLY1305:256 CV=yes DN="CN=mx.goo
gle.com": SMTP error from remote mail server after end of data: 550-5.7.1 [213.36.253.206] The 
IP you're using to send mail is not authorized to\n550-5.7.1 send email directly to our servers
. Please use the SMTP relay at your\n550-5.7.1 service provider instead. Learn more at\n550 5.7
.1  https://support.google.com/mail/?p=NotAuthorizedError g12si3887984wri.283 - gsmtp

**Comment by teolemon** [comment]
I believe this one is fixed.

**Comment by alexgarel** [comment]
Yes it is.

**Comment by alexgarel** [comment]
[Install of proxmox gateway server](https://github.com/openfoodfacts/openfoodfacts-infrastructure/blob/master/docs/reports/2022-02-proxmox-mail-gateway-install.md#install-of-proxmox-gateway-server)Install of proxmox gateway server) did it.
