### ISSUE TITLE
Improve %Lang initialization in Lang.pm and Tags.pm + current behaviour description

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#614]
There is some weird logic in Lang.pm and Tags.pm that make them interdependent:

1. Languages and countries translations from the languages and countries taxonomies, that are loaded when Tags.pm is loaded.

2. Lang.pm loads strings from .po files, and for each key (string id) and each language, if we don't have a translation in that language, it copies the English value to the hash for that language. This is done so that we can have things like $Lang{some_key}{$lc} in the code.

This copying actually takes a long time (around 30 seconds) as we have hundreds of languages. So it is done in Lang::init_language($recompute_language), which is called by %Tags.pm with $recompute_language == 0 when loaded. In that case, %Lang is loaded from a stored .sto file, and not recomputed.   /scripts/recompute_language.pl calls init_language(1) in order to compute all values and store the resulting %Lang .sto file.

It is a messy, not sure what's the right solution here.

We do have a lang("some_key) function that looks up the value for $lc first, and then "en" if it does not exist. So maybe we could try to use it everywhere instead of the $Lang{some_key}[$lc}, so that we can get rid of this copying thing.

**Comment by hangy** [comment]
Is this still an issue or was this fixed in a695a0027aeb9729606f73f314995dfc6321c76d?

**Comment by stephanegigandet** [comment]
I think I fixed it indeed. Closing.
