### ISSUE TITLE
Existing stored Lang.sto not wiped out completely by /scripts/recompute_language.pl

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#615]
See bug #614.

We currently store a computed %Lang in $data_root/Lang.sto with English values for all missing translations.

This file is generated by the recompute_languages.pl script, but currently any preexisting Lang.sto file is loaded first and the recomputation is done over it.  It kind of worked when Lang.pm contained the translations, but for the .po files it doesn't work any more, as the .po files are loaded first, then Tags.pm loads Lang.sto over it, and they are not loaded again.  (if this bug description is hard to understand, that's because I have troubles to understand the bug myself, sorry)

**Comment by stephanegigandet** [comment]
"fixed" by https://github.com/openfoodfacts/openfoodfacts-server/compare/461edcc295d4...7935d537a737

**Comment by hangy** [comment]
> "fixed" by [461edcc...7935d53](https://github.com/openfoodfacts/openfoodfacts-server/compare/461edcc295d4...7935d537a737)
