### ISSUE TITLE
KP bug for Nutri-Score on alcohols

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#6175]
### What
- KP bug for Nutri-Score on alcohols
- https://world.openfoodfacts.org/product/3514123109733/prima-nature-gerard-bertrand
### Part of
- #2408 
- #5517 
### Screenshot
![image](https://user-images.githubusercontent.com/1689815/145542066-28ab5f0a-cd88-4b17-b1e9-870898b0c8d4.png)

**Comment by stephanegigandet** [comment]
fixed
