### ISSUE TITLE
Typo in the Folksonomy script

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#6177]
### What
Typo in the Folksonomy script

### Code pointer
- https://github.com/openfoodfacts/openfoodfacts-server/blob/main/html/js/folksonomy.js#L679
### Part of 
- #5556

**Comment by pizzaz93** [comment]
@teolemon some potential options:

`These non-restricted properties are created and filed by users` 
`These properties are created and filed by users with no usage restrictions` 
`These properties are created and filed by users for multiple purposes` 
`These properties are created and filed by users for multiple uses` 
`These properties are created and filed by users for multiple use cases`
