### ISSUE TITLE
Small typo in the legacy "Nutri-Score" not applicable message

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#6230]
### What

- [ ] Small typo in the legacy "Nutri-Score" not applicable message
  - [ ] Example product: https://world.openfoodfacts.org/product/3130630133018

### Part of
- #5517 

### Screenshot
![image](https://user-images.githubusercontent.com/1689815/147667415-5952b9dd-584b-4bc4-91aa-5447c882e3de.png)

**Comment by stephanegigandet** [comment]
fixed
