### ISSUE TITLE
Refuse code that are too long on add product, or file import

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-server#6262]
### Describe the bug

On producer platform, a user was able to create a product with a code so long (53 chars) that exceed db (or something) capacity resulting in an error as the app tries to display the product. (invalid bar code).

The product is even stored in a directory named "invalid/" !

### To Reproduce

Maybe entering code manually or importing a file with a code which is too long.

### Expected behavior

No product should be created and an error displayed to the user.

### Type of device

Browser

**Comment by 4nt0ineB** [comment]
Seems fixed
https://github.com/openfoodfacts/openfoodfacts-server/blob/2105897bde8cdd01c642be9acdf3ee24a720c048/lib/ProductOpener/Products.pm#L414
