### ISSUE TITLE
Different icons and text for not applicable Nutri-Score (e.g. alcohol, baby food) in product attributes and knowledge panels

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#6276]
Different icons and text for not applicable Nutri-Score (e.g. alcohol, baby food) in product attributes and knowledge panels### Is your feature request related to a problem? Please describe.

When the Nutri-Score is not applicable for a product category, we currently show the same image and text as when we do not have enough information to compute the Nutri-Score.

- Related: https://github.com/openfoodfacts/openfoodfacts-server/issues/6223

### Describe the solution you'd like

Create specific text and icons for non-applicable Nutri-Score, possibly with a different message based on categories.

**Comment by alexgarel** [comment]
Also we should add a new category beside from unknown, like not-applicable. (see https://world.openfoodfacts.org/nutrition-grades)

On image side, I would preferably change the icon for incomplete nutriscore. We could either replace the C by an interrogation point or have make part of the image finish with cubes, or both.

**Comment by alexgarel** [comment]
A proposal for yet to compute nutriscore: 

![nutriscore-unknown-2](https://user-images.githubusercontent.com/144788/148935832-1261dcd2-ef28-4298-b140-87cb5ce2fdfb.png)
source: [nutriscore-unknown-2.zip](https://github.com/openfoodfacts/openfoodfacts-server/files/7846125/nutriscore-unknown-2.zip)

**Comment by stephanegigandet** [comment]
Replacing the C with a question mark for incomplete Nutri-Score is a good idea. I'd prefer to keep the colors shades of grey.

For not-applicable, crossing the Nutri-Score is probably our best bet.

![image](https://user-images.githubusercontent.com/8158668/148984680-058c6bd1-57f4-425b-90a7-ba72a413605d.png)

**Comment by teolemon** [comment]
@stephanegigandet I just realized we should do exactly the same for Eco-Score and drinks, and when the category is not specific enough.
