### ISSUE TITLE
Exempted category visual asset deployment issue

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#6306]
### What

- [ ] Exempted category visual asset deployment issue
  - [ ] https://world.openfoodfacts.org/category/celery-salt
### Screenshot
![image](https://user-images.githubusercontent.com/1689815/149619171-50142511-0f13-4f35-bd7d-d1f87429e7cf.png)

**Comment by teolemon** [comment]
https://static.openfoodfacts.org/images/attributes/nutriscore-not-applicable.svg

**Comment by stephanegigandet** [comment]
Fixed.
