### ISSUE TITLE
"Haricot princesse" not categorized as "haricot vert"

### ISSUE THREAD

**Issue by bigon** [openfoodfacts/openfoodfacts-server#6307]
### Describe the bug

In Belgium "haricot vert" are often called "Haricot princesse"

But the ingredients parsing is not categorized them as such

Could you please add this to the ingredient list?

### To Reproduce

1. Go to https://be-fr.openfoodfacts.org/produit/5400111271156/haricots-princesses-brisees-delhaize
2. The site complains that there is a problem analyzing the ingredients

### Expected behavior

"Haricot princesse" is recognized as a synonym for "haricot vert"

### Type of device

Browser

**Comment by aleene** [comment]
Yes in dutch it is similar prinsessenboon is the sam as sperzieboon.
