### ISSUE TITLE
Frais/Fraiche not detected as processing in french

### ISSUE THREAD

**Issue by bigon** [openfoodfacts/openfoodfacts-server#6308]
### Describe the bug

Hello,

In English it seems that "Fresh" is detected as a type of (non) processing:

https://world.openfoodfacts.org/cgi/test_ingredients_analysis.pl?ingredients_text=fresh+potato&type=add&action=process

In French, the term Frais/Fraiche is not:

https://fr.openfoodfacts.org/cgi/test_ingredients_analysis.pl?ingredients_text=Pommes+de+terres+fra%C3%AEches&type=add&action=process&submit=Envoyer

### To Reproduce

1. Go to https://world.openfoodfacts.org/cgi/test_ingredients_analysis.pl?ingredients_text=fresh+potato&type=add&action=process and notice that `"processing" : "en:fresh"` is set
2. Go to https://fr.openfoodfacts.org/cgi/test_ingredients_analysis.pl?ingredients_text=Pommes+de+terres+fra%C3%AEches&type=add&action=process&submit=Envoyer notice that it's not

### Expected behavior

Frais/Fraîche/Fraîches should be detected as "fresh" processing

### Type of device

Browser

**Comment by aleene** [comment]
Or we should suppress the en:fresh from processing. How is fresh produce detected? Via the ingredients or the categories?

**Comment by stephanegigandet** [comment]
I think we should keep en:fresh in the processing (even though it is a non-processing :)). I'll add it, and first check that we don't have ingredients where frais/fraiche should be kept (crème fraîche is already in the ingredients taxonomy).

https://fr.openfoodfacts.org/ingredients?filter=fraiche

I'm seeing a lot of "crème (dont lait) fraîche", that's going to be tough to parse.
