### ISSUE TITLE
obsolete tests to update

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#6334]
msgctxt "attribute_nutriscore_unknown_description_short"
msgid "Unknown nutritional quality"
msgstr "Qualité nutritionnelle inconnue"

has been replaced by 

msgctxt "attribute_nutriscore_unknown_description_short"
msgid "Missing data to compute the Nutri-Score"
msgstr "Données manquantes pour calculer le Nutri-Score"

but the matching test haven't been updated

t/expected_test_results/attributes/fr-sesame-seeds.json
t/expected_test_results/attributes/fr-palm-kernel-fat.json
t/expected_test_results/attributes/fr-palm-oil-free.json
t/expected_test_results/attributes/fr-palm-oil.json
t/expected_test_results/attributes/fr-vegetable-oils.json

_Originally posted by @teolemon in https://github.com/openfoodfacts/openfoodfacts-server/pull/6294#issuecomment-1019340486_

**Comment by stephanegigandet** [comment]
tests updated in l10n_main branch https://github.com/openfoodfacts/openfoodfacts-server/pull/6294
