### ISSUE TITLE
Improve ingredients analysis to record ingredients that cause a product to be non vegan / vegetarian / palm oil free or to be NOVA 3 or 4

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#6366]
### Problem
- Needed for https://github.com/openfoodfacts/openfoodfacts-server/issues/6365

### Describe the solution you'd like

- In addition to the existing ingredients_analysis_tags structure that store the result of the ingredients analysis (e.g. non-vegan), also store lists of ingredients that caused that result (e.g. a list of non-vegan ingredients).

### Describe alternatives you've considered

- The existing ingredients field does contain info about vegan and non vegan ingredients, but it would be more convenient to store pre-analyzed lists of ingredients for each of the ingredients analysis properties.

**Comment by stephanegigandet** [comment]
Done for vegan / vegetarian / palm oil free, need to add NOVA.

**Comment by teolemon** [comment]
Note: Vegetarian and Palm oil already seem to be working in the corresponding Knowledge Panel, but not vegan, for some reason.

**Comment by stephanegigandet** [comment]
> Note: Vegetarian and Palm oil already seem to be working in the corresponding Knowledge Panel, but not vegan, for some reason.

Which product?

**Comment by teolemon** [comment]
3263859502027
