### ISSUE TITLE
Vitamin K1 (Phylloquinone)  and Choline not understood

### ISSUE THREAD

**Issue by TaciteOFF** [openfoodfacts/openfoodfacts-server#64]
Choline (http://en.wikipedia.org/wiki/Choline)
Vitamin K1 (http://en.wikipedia.org/wiki/Phylloquinone)

…aren't well detected by the nutrition facts table, as you can see here : 

http://fr.openfoodfacts.org/produit/3041090796562/bledilait-croissance-3-bledina

**Comment by TaciteOFF** [comment]
same for Bêta-Glucanes (a type of fibers) : 

http://fr.openfoodfacts.org/produit/3760151011054/biscuits-de-son-d-avoine-saveur-noisette-dukan

**Comment by Sebleouf** [comment]
And same for beta-Carotene (https://en.wikipedia.org/wiki/Beta-Carotene) :
http://fr.openfoodfacts.org/produit/3080920100025/abricots-de-mediterranee-st-mamet

**Comment by TaciteOFF** [comment]
Same for Inositol and Carnitine

http://fr.openfoodfacts.org/produit/7613032505103/evolia-relais-1-guigoz

**Comment by CloCkWeRX** [comment]
> Bêta carotène
That should be present/working as far as I can tell from the code.

**Comment by CloCkWeRX** [comment]
Hey all,
Can I get you to add your feedback to #1044; particularly if:
 * There are translations or more common names that should be added
 * There are default units of measurement that should be modelled
