### ISSUE TITLE
Make it possible to call the API without knowing the translation of the facet name

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#642]
Currently to get localized country name, you have to get ```https://world-fr.openfoodfacts.org/pays.json``` (for French) and ```https://world.openfoodfacts.org/countries.json``` (for English)

Make it possible to get something like ```https://world-fr.openfoodfacts.org/countries.json``` or ```https://world.openfoodfacts.org/countries-fr.json``` (or perhaps insert multilingual values in the original json, but that makes it heavier)

**Comment by stephanegigandet** [comment]
http://fr.openfoodfacts.net/allergen/lait/packager-codes

**Comment by Kuyas** [comment]
Is it still a problem?

**Comment by teolemon** [comment]
Looks solved.
