### ISSUE TITLE
No explanation of cause for Nutella

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#6434]
### What
- No explanation of cause for Nutella (The ingredient is obvious in this specific case, "palm oil", but the panel is empty)

### Part of
- #5493 

### Screenshot
https://world.openfoodfacts.net/product/80135463/nutella-ferrero

![image](https://user-images.githubusercontent.com/1689815/155178079-596a0b73-5fb6-4a8b-8d75-17fde27f9114.png)

**Comment by alexgarel** [comment]
Hum this look like some command should have been run, that was not run.

We should run `scripts/update_all_products.pl --process-ingredients`

(this is a command to run, specific to the new feature).

**Comment by alexgarel** [comment]
@stephanegigandet would it make sense to run this kind of command once in a while on preprod and on prod ?

**Comment by alexgarel** [comment]
I launched the command on preprod, but this will take a long time ! (8 days…)

**Comment by stephanegigandet** [comment]
Fixed in production.
