### ISSUE TITLE
Allow to initiate account deletion from the website/API

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#6435]
### What
- [ ] Allow to initiate account deletion from the website/API
  - [ ] Minimal version: Link pre-filling an email to contact@openfoodfacts.org
  - [ ] Maximal version: self-service system, with an API for the apps
### Why
`
Account deletion within apps
App Store Review [Guideline 5.1.1](https://developer.apple.com/app-store/review/guidelines/#5.1.1) provides people with greater control over their personal data by stating that all apps that allow for account creation must also allow users to initiate deletion of their account from within the app. This requirement was set to apply to all app submissions by January 31, 2022. Due to the complexity of implementing this requirement, we’ve extended the deadline to June 30, 2022 to give you more time.
`

### Part of
- #5809
- #6436

**Comment by alexgarel** [comment]
Note: it's better to have anonymization than removal.

**Comment by alexgarel** [comment]
@teolemon can we close this in favour of https://github.com/openfoodfacts/openfoodfacts-server/issues/8164 ?
