### ISSUE TITLE
Adding a robots.txt to the preprod server

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#644]
https://www.google.fr/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=site%3A*.preprod.openfoodfacts.org

We have many results from preprod

**Comment by hangy** [comment]
Done. http://world.preprod.openfoodfacts.org/robots.txt

Changed

        location = /robots.txt {
                try_files $uri $uri/ =404;
        }

to

        location = /robots.txt {
                root /home/off-preprod/html-preprod-override;
                try_files $uri $uri/ =404;
        }

in `/etc/nginx/sites-enabled/off-preprod` and added the robots.txt file there.
