### ISSUE TITLE
Compress the CSV export

### ISSUE THREAD

**Issue by moreymat** [openfoodfacts/openfoodfacts-server#6443]
### Is your feature request related to a problem? Please describe.

I am regularly using openfoodfacts to teach data science (intro or "real world") and get students to work on the CSV dump. As it's getting bigger, I found myself having more troubles providing it to all students at once.

### Describe the solution you'd like

In my last class, a student suggested to compress it (I should have thought about that...) and I was surprised how much we could gain : from 5.1 GB down to 438 MB (dump from 2022-02-21, using gzip or zip).
Wouldn't it make sense for the project to compress the CSV file, at least for the international dump ? Easier on the server, less traffic, faster download time for users.

**Comment by alexgarel** [comment]
Note, as reported by @moreymat that nginx is not compressing the file over HTTP. This is however better for users to store the gzipped version.

**Comment by stephanegigandet** [comment]
There's a compressed version of the CSV in fact, with .gz added to the name. We just have to add the link to it (and maybe make nginx use it when the csv is requested with accept-encoding gzip)

**Comment by CharlesNepote** [comment]
We choose to deliver uncompressed files, as it lowers a bit the barrier to reuse. Nginx do compresses files over HTTP as you can see:
```
charles@barbapapa2020:~$ curl https://static.openfoodfacts.org/data/en.openfoodfacts.org.products.csv --silent --write-out "%{size_download}\n" --output /dev/null
5443123485
charles@barbapapa2020:~$ curl https://static.openfoodfacts.org/data/en.openfoodfacts.org.products.csv --silent -H "Accept-Encoding: gzip,deflate" --write-out "%{size_download}\n" --output /dev/null
203821048
```
To get a compress file you can do this (but it takes some time):
```bash
curl -o - https://static.openfoodfacts.org/data/en.openfoodfacts.org.products.csv | gzip > file.gz
```

Thus I would agree to provide the [already compressed file](https://static.openfoodfacts.org/data/en.openfoodfacts.org.products.csv.gz) in addition to non-compressed file. There are already there, as mentioned Stephane, it's just a matter of documentation, see: https://github.com/openfoodfacts/openfoodfacts-web/pull/231

**Comment by moreymat** [comment]
Thanks for the answers @alexgarel @stephanegigandet @CharlesNepote .

I was able to reproduce what @CharlesNepote described and download a compressed file through nginx. My previous unsuccessful attempt included `"Accept-Encoding: gzip"` without `deflate`.

For the record, the file compressed by nginx that I got is however larger than reported by @CharlesNepote (which is weird), and larger than the existing compressed file linked by @stephanegigandet:
```terminal
➜ curl https://static.openfoodfacts.org/data/en.openfoodfacts.org.products.csv --silent --write-out "%{size_download}\n" --output /dev/null 
5446864986
➜ curl https://static.openfoodfacts.org/data/en.openfoodfacts.org.products.csv --silent -H "Accept-Encoding: gzip,deflate" --write-out "%{size_download}\n" --output /dev/null
744765344
➜ curl https://static.openfoodfacts.org/data/en.openfoodfacts.org.products.csv.gz --silent --write-out "%{size_download}\n" --output en.openfoodfacts.org.products.csv.gz
461173773
```

In any case, the solution in openfoodfacts/openfoodfacts-web#231 will neatly solve my issue. Thanks again !
