### ISSUE TITLE
Footer hides Eco-Score computation details

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-server#6447]
### Describe the bug

If I clic on Eco-Score computation detail, footer hides most of the data. No way to get it !

### To Reproduce

1. go to see eg. https://fr.openfoodfacts.org/product/2358340005260/jambon-superieur (better as anonymous to have the smaller footer)
2. click on "Détails du calcul de l'Éco-score »
3. you only see part of the information

### Expected behavior

Ideally the footer should go below the content, 
or in some way user should be able to see information

### Screenshots

![Capture d’écran de 2022-02-25 19-26-10](https://user-images.githubusercontent.com/144788/155768289-10b144a9-9665-4769-93e5-c878179875c2.png)

### Type of device

Browser

### Browser version

firefox 97.0.1 (64 bits)

**Comment by stephanegigandet** [comment]
I tried to fix that sometime ago: the page extends when clicking on the link, but it works only on Chrome, and not on Firefox.

**Comment by teolemon** [comment]
Potentially fixed by #6667

**Comment by alexgarel** [comment]
Fixed, indeed.
