### ISSUE TITLE
Impossible to edit nutritional informations on a product

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-server#6457]
### Describe the bug

On https://fr.openfoodfacts.org/cgi/product.pl?type=edit&code=3068236309998 you can't add nutritional information

### To Reproduce

Go to https://fr.openfoodfacts.org/cgi/product.pl?type=edit&code=3068236309998 / nutritional info, there is no table

### Expected behavior

There should be the table to add informations

### Screenshots

![Capture d’écran de 2022-03-04 18-53-20](https://user-images.githubusercontent.com/144788/156816081-01723091-7313-46da-8782-8d7b5ba1d2e8.png)

### Type of device

Browser

**Comment by stephanegigandet** [comment]
It's just because the checkbox " Les informations nutritionnelles ne sont pas mentionnées sur le produit." is checked, uncheck it and you will see the table.

**Comment by alexgarel** [comment]
Hum, I see, I think still there is a bit of incongruency there. Why do we hide this part and not the rest !

@stephanegigandet do you agree we should hide image selection, the image itself and the checkbox to tell for how big a portion data is ? This would make it clearer !

**Comment by stephanegigandet** [comment]
@alexgarel That sounds good to me.

**Comment by alexgarel** [comment]
Closed in favor of #6729
