### ISSUE TITLE
No nutriments

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#646]
The codes for setting no nutriments does not seem to work (no_nutriments):
`"https://ssl-api.openfoodfacts.org/cgi/product_jqm2.pl?code=1234&no_nutriments"	
`
Shouldn't this also delete all existing nutriments?

**Comment by hangy** [comment]
I'm not sure if that's supposed to work. The only instance where something similar is in the code would be https://github.com/openfoodfacts/openfoodfacts-server/blob/fff62a4aebdd12826a4c65a2f68c74d93d1f34d8/cgi/product_jqm_multilingual.pl#L127, but that's apparently not built to delete existing nutrients, either.

**Comment by aleene** [comment]
If OFF does not delete existing nutrients, the app should do it.

It is also a consistency question for the OFF-data. Which is true? The no_nutriments or the nutriment values?

**Comment by teolemon** [comment]
Admins now have a button to delete all nutriments, but I believe that's just JS

**Comment by aleene** [comment]
too old
