### ISSUE TITLE
CORS add hunger.openfoodfacts.org to authentication url

### ISSUE THREAD

**Issue by alexfauquette** [openfoodfacts/openfoodfacts-server#6462]
### Is your feature request related to a problem? Please describe.

- In Hunger Games, requests to verify if a user is logged in or not fail due to a CORS issue

- Tod do so I tried `axios.get("https://world.openfoodfacts.org/cgi/auth.pl");`
  
- More information in the following PR I merge to be sure it was falling under hunger.openfoodfacts.org domain name
https://github.com/openfoodfacts/openfoodfacts-hungergames/pull/290

- In brief, I need to set `withCredentials=true` to let send the cookies, to `world.openfoodfacts.org` but I can not read the answer if the response header does not contain `Access-Control-Allow-Credentials=true`

### Describe the solution you'd like

- add `Access-Control-Allow-Credentials=true` when the request comes from `hunger.openfoodfacts.org`

**Comment by stephanegigandet** [comment]
@alexfauquette I deployed https://github.com/openfoodfacts/openfoodfacts-server/pull/7022 in production, can you check if it works for you?

**Comment by alexfauquette** [comment]
@stephanegigandet I added a console log to verify in production what JS have access to: The following script is run when loading the page https://hunger.openfoodfacts.org/logos/search

```js
axios.get("https://world.openfoodfacts.org/cgi/auth.pl", { withCredentials: true })
      .then((rep) => console.log({ rep }))
      .catch((err) => console.log({ err }));
```

The line you added allows sending the cookies. What is missing is the `Access-Control-Allow-Origin`

since for know it seems I'm the only JS app using it you can set `Access-Control-Allow-Origin: https://hunger.openfoodfacts.org`

I tried with the extension [Moesif Origin & CORS Changer](https://chrome.google.com/webstore/detail/moesif-origin-cors-change/digfbfaphojjndkpccljibejjbppifbc) which allows to modify the response header.

With `Access-Control-Allow-Origin: https://hunger.openfoodfacts.org` or `Access-Control-Allow-Origin: *` I can see in the axios response if I'm logged in (code 200) or not (code 403) compared to now where I always get a message "network error"

**Comment by stephanegigandet** [comment]
> since for know it seems I'm the only JS app using it you can set Access-Control-Allow-Origin: https://hunger.openfoodfacts.org

mmmh. I'm not sure about that. Folksonomy Engine uses /cgi/auth.pl as well. cc @CharlesNepote  @cquest 

I can put Access-Control-Allow-Origin: * ,  I guess, the only thing this script does is to check if a session is opened.

**Comment by stephanegigandet** [comment]
@alexfauquette does it work now?

**Comment by alexfauquette** [comment]
Does not seems to work. I search  bit on the internet what could be wrong. Seems `*` is not working with credential

https://httptoolkit.tech/blog/how-to-debug-cors-errors/
> - The response must include a `Access-Control-Allow-Origin` header, whose value either matches the page's origin or is *. The page's origin is sent in the request in an `Origin` header.
> - If the request included credentials (e.g. `fetch(url, { credentials: 'include' })`) then the response headers must include `Access-Control-Allow-Credentials: true`, and the `Access-Control-Allow-Origin` header must match exactly (i.e. `*` is not allowed).

About Folksonomy Engine, from what I understand, it is added to the main website, so the origin website and the server are the same

**Comment by alexfauquette** [comment]
It works when not logged in but not when logged in.

The first request is done when not logged in (nb of cookies is 0 and the request status is 403)
The second request is done after being logged to the main website (nb of cookies is 1 and the status is CORS error)

![image](https://user-images.githubusercontent.com/45398769/178151621-38eaa5d2-0fa0-422c-8dd1-1cdf5cc9c6c2.png)

**Comment by stephanegigandet** [comment]
@alexfauquette ok I think it is working now :)

![image](https://user-images.githubusercontent.com/8158668/178493573-0ad4d214-c712-4a73-a5c7-3cd51b716c3e.png)

**Comment by alexgarel** [comment]
@stephanegigandet as discussed today we should handle the port, so that hunger game developers can test on a preprod server.

**Comment by alexfauquette** [comment]
@stephanegigandet Thanks 🎉
By curiosity, what did you change to make it work?

**Comment by stephanegigandet** [comment]
This should be fixed
