### ISSUE TITLE
Migrate Open Beauty Facts to HTTPS

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#647]
https://security.googleblog.com/2016/09/moving-towards-more-secure-web.html
In a few days, Chrome 56 will be deployed, marking HTTP sites as unsecure. We must thus migrate OBF to HTTPS.

**Comment by teolemon** [comment]
![image](https://cloud.githubusercontent.com/assets/1689815/22223022/9277e91a-e1b9-11e6-82ed-37d6b22160ea.png)

**Comment by stephanegigandet** [comment]
OBF now has a wildcard SSL certificate.
