### ISSUE TITLE
Consider using google's guetzli for jpeg encoding

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#648]
https://github.com/google/guetzli

**Comment by hangy** [comment]
Let's wait until someone builds a Perl module that wraps `guetzli::Process`? 😄

**Comment by stephanegigandet** [comment]
Doing some experiments.

It is very slow. 10 seconds for a 297x400 image.

/home/off/html/images/guetzli# time ./guetzli_linux_x86-64 1.400.png  1.400.g.jpg

real    0m10.487s
user    0m10.240s
sys     0m0.240s

with ImageMagick:

root@ns3362784:/home/off/html/images/guetzli# time convert 1.400.png 1.400.convert.jpg

real    0m0.012s
user    0m0.008s
sys     0m0.000s

and the file is actually bigger (that's with default settings on both, not sure how they compare)

-rw-r--r-- 1 root root   28843 Mar 20 14:37 1.400.jpg
-rw-r--r-- 1 root root  403453 Mar 20 14:58 1.full.jpg
-rw-r--r-- 1 root root 3223247 Mar 20 14:59 1.full.png
-rw-r--r-- 1 root root  490732 Mar 20 15:01 1.full.g.jpg
-rw-r--r-- 1 root root  196834 Mar 20 15:03 1.400.png
-rw-r--r-- 1 root root   52792 Mar 20 15:03 1.400.g.jpg
-rw-r--r-- 1 root root   43185 Mar 20 15:05 1.400.convert.jpg

**Comment by stephanegigandet** [comment]
https://static.openfoodfacts.org/images/guetzli/1.400.jpg (current convert process)

https://static.openfoodfacts.org/images/guetzli/1.400.g.jpg (guetzli) -> it does look better, especially above the red "Auchan" logo.

**Comment by stephanegigandet** [comment]
ImageMagick's convert seem to have a default of 85, and guetzli a default of 95, but I'm not sure if they are comparable.

-rw-r--r-- 1 root root   28843 Mar 20 14:37 1.400.jpg
-rw-r--r-- 1 root root  403453 Mar 20 14:58 1.full.jpg
-rw-r--r-- 1 root root 3223247 Mar 20 14:59 1.full.png
-rw-r--r-- 1 root root  490732 Mar 20 15:01 1.full.g.jpg
-rw-r--r-- 1 root root  196834 Mar 20 15:03 1.400.png
-rw-r--r-- 1 root root   52792 Mar 20 15:03 1.400.g.jpg
-rw-r--r-- 1 root root   43185 Mar 20 15:05 1.400.convert.jpg
-rw-r--r-- 1 root root   31556 Mar 20 15:13 1.400.convert.q85.jpg
-rw-r--r-- 1 root root   72489 Mar 20 15:13 1.400.convert.q95.jpg
-rw-r--r-- 1 root root   52792 Mar 20 15:14 1.400.g.q95.jpg
-rw-r--r-- 1 root root   29463 Mar 20 15:15 1.400.g.q85.jpg

**Comment by hangy** [comment]
Interestingly the guetzli image is only 399 pixels high. If it's that slow, it would be a bad idea for on-the-fly use.

**Comment by teolemon** [comment]
Nope, but if we can save 10%-20% disk drive…

**Comment by stephanegigandet** [comment]
Guetzli is way too slow for use on our product images. It seems it is not been working on. Closing the bug.
https://en.wikipedia.org/wiki/Guetzli
