### ISSUE TITLE
product_image_upload: user identification doesn't seem to work

### ISSUE THREAD

**Issue by g123k** [openfoodfacts/openfoodfacts-server#6496]
### Describe the bug

When requesting `/cgi/product_image_upload.pl` with valid fields, the photo on the website & the APIs are not linked to the user.

This issue is reproducible on the Android app: https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/4338

### To Reproduce

Two ways to test this issue: use the Android app (by uploading a photo) or make a call directly.

Fields passed to this endpoint are:
- imagefield
- password
- comment
- code
- user_id
- imgupload_front

### Expected behavior

Photos should be marked as uploaded by the correct user

### Type of device

REST-API

**Comment by stephanegigandet** [comment]
looking into it

**Comment by g123k** [comment]
After (re)checking the Android app, it seems that some requests provide a user_id, but not a password.
I will resolve this issue on the app, but shouldn't the API refuse the upload if the field is missing?

**Comment by stephanegigandet** [comment]
> I will resolve this issue on the app, but shouldn't the API refuse the upload if the field is missing?

We accept anonymous image uploads, if there's no password, the user is just not identified, but we still accept the upload.

**Comment by stephanegigandet** [comment]
Closing this issue as the server side is working as expected.
