### ISSUE TITLE
Add Facebook's Opengraph meta-tag

### ISSUE THREAD

**Issue by TaciteOFF** [openfoodfacts/openfoodfacts-server#65]
Selecting the right product image URL with meta property="go:image" makes it fancier when sharing product pages on Facebook because it displays the product image instead of OFF's logo.

More info here : http://stackoverflow.com/questions/1138460/how-does-facebook-sharer-select-images

**Comment by hangy** [comment]
I think this was fixed in 91d6df1d4dae7fc459d698cd34e2efe02f22332e. Feel free to reopen if it isn't.
