### ISSUE TITLE
Ask question to non logged-in users

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-server#6506]
We should use the new anonymous voting feature of robotoff to asks questions to non login users.

- [ ] ask question even to non login users
- [ ] add device_id parameter based on ip address fingerprint (or a random stored value ?)
- [ ] eventually https://github.com/openfoodfacts/openfoodfacts-infrastructure/issues/104
- [ ] add a confirmation/thank you message also encouraging users to create an account
  (Ideally this should come back from time to time, maybe tracking state in a stored value, also it could tell how many contributions where already done).

See also:
-  https://github.com/openfoodfacts/smooth-app/issues/1319

**Comment by teolemon** [comment]
- Duplicate of #3158
