### ISSUE TITLE
.dev has been broken for a while

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#6511]
### What
- .dev has been broken for a while
- Software error:
Not a HASH reference at /srv/off/lib/ProductOpener/Ecoscore.pm line 1502.
For help, please send mail to the webmaster ([contact@openfoodfacts.org](mailto:contact@openfoodfacts.org)), giving this error message and the time and date of the error.

### Who for
- developpers
### Part of
- #5512

**Comment by alexgarel** [comment]
@teolemon, sorry I don't understand what you are talking about !

**Comment by teolemon** [comment]
The home page of the . dev server is broken. The product pages do work well

**Comment by teolemon** [comment]
ping @stephanegigandet

**Comment by stephanegigandet** [comment]
https://world.openfoodfacts.dev/ is currently working, but should not be used for anything, it's just for dev
