### ISSUE TITLE
This is not a Top 10 issue

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#6518]
### Describe the bug

A GitHub action adds a Top 10 Issue label on issues, but the result is that most new issues are marked as a Top 10 issue (maybe because we don't vote on issues much).

It's distraction and misleading.

### To Reproduce

https://github.com/openfoodfacts/openfoodfacts-server/issues?q=is%3Aissue+is%3Aopen+label%3A%22%F0%9F%91%8D+Top+10+Issue%21%22

### Expected behavior

Top 10 issues should not be random. We probably should label top issues manually (e.g. using the P1 label).

Proposed resolution: remove the github action.

### Type of device

Other

**Comment by teolemon** [comment]
https://github.com/mapbox/top-issues

**Comment by teolemon** [comment]
It is possible to fix the issue at the core by making the action able to traverse pagination https://github.com/TinkurLab/top-issues-action/issues/5
