### ISSUE TITLE
Estimation of fruits can be > 100 %

### ISSUE THREAD

**Issue by KommX** [openfoodfacts/openfoodfacts-server#6524]
### Describe the bug

When the list of ingredients contains nested ingredients the percentage of fruit is not calculated correctly and may be > 100 %.

### To Reproduce

1. Go to https://de.openfoodfacts.org/produkt/4061458009263/obst-riegel-knusperone
2. See the sentence "Warnhinweis: Die Menge an Früchten, Gemüse und Nüssen ist auf dem Etikett nicht angegeben und wurde anhand der Zutatenliste geschätzt: 121%" (English translation: "Warning: The amount of fruits, vegetables and nuts is not indicated on the label and has been estimated from the list of ingredients: 121%.")

### Expected behavior

The percentage of nested ingredients should be calculated as relative percentages based on the parent ingredient. In this case the product doesn't contain 57 % cranberries, but the ingredient "getrocknete Cranberrystücke mit Apfelsaftkonzentrat (6 %)" contains 57 % cranberries, so that the overall percentage of cranberries should only be 6 % * 57 % = 3,42 %.
I guess, that the fruit percentage of 121 % comes from this miscalculation.

### Screenshots

![image](https://user-images.githubusercontent.com/7859245/160696242-7ec76bf1-31a9-48b1-8a32-130dd02c314a.png)

### Type of device

Browser

**Comment by stephanegigandet** [comment]
Thanks for the report @KommX 

It's tricky because in many cases, the % listed in sub ingredients are absolute, and not relative.

In at least some cases, when a % of a sub ingredient is greater than the % of the ingredient, we could assume it's relative.

**Comment by stephanegigandet** [comment]
related code in Ingredients.pl : init_percent_values()
