### ISSUE TITLE
Ingredient parsing improvement for additives

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#6536]
```Emulsifying (INS 471, INS 477) & Stabilizing Agents (INS 412, INS 410)```
is not properly parsing: https://world.openfoodfacts.org/product/8904057300040/chocobar-flavoured-ice-cream-arun

**Comment by stephanegigandet** [comment]
This can probably solved just by adding "emulsifying" as a synonym of emulsifiers in taxonomies/additives_classes.txt

**Comment by borrokk** [comment]
should I delete this PR and give a separate one just for this issue?
