### ISSUE TITLE
Prevent people from entering email addresses as values

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#6539]
### What
- Prevent people from entering email addresses as values
### Screenshots
<img width="283" alt="Capture d’écran 2022-04-01 à 18 27 54" src="https://user-images.githubusercontent.com/1689815/161304387-10889002-3315-46c5-9dc6-79edc1c5c9bb.png">

### Part of
- #5538

**Comment by stephanegigandet** [comment]
Files with the corresponding code:

Server-side:

cgi/product_multilingual.pl - web form to edit products
cgi/product_jqm_multilingual.pl - API
lib/ProductOpener/Products.pm

**Comment by yuktea** [comment]
working on this!

**Comment by MonalikaPatnaik** [comment]
I would like to work on this!

**Comment by alexgarel** [comment]
Relevant comment from [old PR](https://github.com/openfoodfacts/openfoodfacts-server/pull/6655#issuecomment-1104800802):

> This would work, but as you suggest, we probably should think more about this, to decide what would be the right behaviour:
> 
>     1. reject the changes completely if there is an error in one of the fields
> 
>     2. ignore the fields that have errors
> 
> 
> And how to convey this information to users so that they can correct the fields.
> 
> It's also complexified a bit by the fact that those changes can be made through the OFF website (and app), but also through third parties that use our API to add / edit products. It's relatively easy for us to introduce new behaviours on the website (such as redisplaying the form with messages about errors), but for the API, we need to find a solution that does not break existing applications that use the API.

**Comment by alexgarel** [comment]
My proposal to keep things simple (as a first iteration):

- just remove values that are email in fields and accept the rest of the edit (for single valued fields remove the field edit, for multi-valued fields just remove  entries that are emails)
- on the web application add a warning thanks to javascript

That way we can do it in process_product_edit_rules (but in a separate method, it's already big).

(in fact process_product_edit_rules could be renamed to check_product_edit, that call both methods and still return a boolean).

**Comment by MonalikaPatnaik** [comment]
> My proposal to keep things simple (as a first iteration):
> 
> * just remove values that are email in fields and accept the rest of the edit (for single valued fields remove the field edit, for multi-valued fields just remove  entries that are emails)
> * on the web application add a warning thanks to javascript
> 
> That way we can do it in process_product_edit_rules (but in a separate method, it's already big).
> 
> (in fact process_product_edit_rules could be renamed to check_product_edit, that call both methods and still return a boolean).

Working on this..will resolve it soon!
Thanyouu :-)
