### ISSUE TITLE
Activate automated daily exports of product data and photos to the public database

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#6558]
### Is your feature request related to a problem? Please describe.

We have nightly imports of data from Equadis into the producers platform. And we have a nightly cron to export data from the producers platform to the public platform. This export is currently done for each organization, and the corresponding organizations have to be listed in scripts/export_producers_platform_data_to_public_database.sh

That means that new organizations that send us data from Equadis don't see their data on the public platform until we add them to the script.

### Describe the solution you'd like

We already have a checkbox "Activate automated daily exports of product data and photos to the public database." in the admin fields of each organization.

- Check that the checkbox is checked when orgs are created by Equadis and Agena3000 imports.
- Instead of listing each organization in scripts/export_producers_platform_data_to_public_database.sh , launch the exports for all organizations that have the checkbox checked.

**Comment by Starla26** [comment]
Hello @stephanegigandet 

I would love to be assigned to this issue.

Thanks

**Comment by 4nt0ineB** [comment]
> * Check that the checkbox is checked when orgs are created by Equadis and Agena3000 imports.

Seems ok there, but I can't test it.

https://github.com/openfoodfacts/openfoodfacts-server/blob/3f3196e976c6986ca41c2ae6fe8014a7e29a5af5/lib/ProductOpener/Import.pm#L1700-L1705
