### ISSUE TITLE
Update GA to GAv4 and remove cookie + ip tracking

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-server#6561]
GA as a new version (v4) with no cookie and no ip tracking.

Change the js script to use it.

Part of:
- https://github.com/openfoodfacts/openfoodfacts-infrastructure/issues/108

**Comment by alexgarel** [comment]
Do we need a banner ?


From my understanding based on :

- https://www.google.com/about/company/user-consent-policy/ 
  
  > You must obtain end users’ legally valid consent to:
  > - the use of cookies or other local storage where legally required; and
  > - the collection, sharing, and use of personal data for personalization of ads.

- https://lincnil.github.io/Guide-RGPD-du-developpeur/#Les_traceurs_qui_ne_sont_pas_vis%C3%A9s_par_ces_obligations

we do not need one because:

1. we do not have any google cookie (verified on the website)
2. we do not send personal data as IP is anonymized by the javascript client, and email is never sent
3. we do not do any targeted advertizing (we do not have advertizing at all !)

@teolemon do you agree ?

**Comment by teolemon** [comment]
I propose closing since we are now on Matomo. I'm not pleased with the efficiency of the tool, but I guess it does the minimum job.
