### ISSUE TITLE
Accessibility [2.4.1]: Provide a skip links option to let a user skip repetitive content. (Bypass Blocks)

### ISSUE THREAD

**Issue by yuktea** [openfoodfacts/openfoodfacts-server#6575]
### Is your feature request related to a problem? Please describe.

This issue was reported by the Accessibility Foundation (https://github.com/openfoodfacts/openfoodfacts-server/issues/4640)
Quoting from [Accessibility_report.pdf](https://github.com/openfoodfacts/openfoodfacts-server/files/5702582/Report.OpenFoodFact.15-12-2020.pdf)
Quoting this report:
> 2.4.1 Headings and Labels
> The site does not use so-called skip links. Offering skip links makes navigation easier and
faster for people who depend on the keyboard or auxiliary software. These skip links allow
keyboard users to skip repeating content such as the main menu and navigate directly to
the main content.

### Describe the solution you'd like

Skip links could be helpful.

### Part of
- #4640

**Comment by abbyrhart** [comment]
I can work on this!
