### ISSUE TITLE
Streamline web saving product pages

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#658]
It would be nice to streamline the webpages when saving a product.

Currently we get to see a save status page after saving. It would be nice to see the saved product right away. Add a status message on the saved product page to make clear the product has been saved.

**Comment by teolemon** [comment]
I had opened a bug to try triggering a chain edit by showing a list of uncomplete products. But your suggestion seems reasonable as well.

**Comment by hangy** [comment]
Probably related to #4, which I started working on at https://github.com/openfoodfacts/openfoodfacts-server/tree/issue/4-product-after-edit - suggestions welcome. 🎊

**Comment by CloCkWeRX** [comment]
Could we do a minimal version of this, perhaps just using a javascript redirect after a few moments on the success page?
Its not the best pattern, but its quick and dirty.

![image](https://user-images.githubusercontent.com/365751/68824657-84983100-06e7-11ea-8339-24d8403e6063.png)

```
setTimeout(function() {window.location.href = '/product/5000221506867?saved';}, 1000);
```

**Comment by VaiTon** [comment]
> 
> 
> Could we do a minimal version of this, perhaps just using a javascript redirect after a few moments on the success page?
> Its not the best pattern, but its quick and dirty; and would save a lot of effort
> 
> ![image](https://user-images.githubusercontent.com/365751/68824657-84983100-06e7-11ea-8339-24d8403e6063.png)
> 
> ```
> setTimeout(function() {window.location.href = '/product/5000221506867?saved';}, 1000);
> ```

I would opt for reidirecting the user directly to the saved page.

**Comment by CloCkWeRX** [comment]
Yeah, happy with that too; just means having to implement flash notifications, a bit of XSS injection proofing if we rely on URL params, etc vs a 1 liner.

**Comment by aleene** [comment]
too old
