### ISSUE TITLE
Make the experimental environmental template translatable

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#6580]
Task:

- [ ] Make the experimental environmental template translatable
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/blob/0092e2e0a119290742574bf7e8de8d52d58ea6d9/templates/api/knowledge-panels/environment/ecoscore/ecoscore_extended.tt.json

**Comment by stephanegigandet** [comment]
Well before translating it, we decide what to do with it. I think we should disable it for the time being.

**Comment by stephanegigandet** [comment]
The experimental environmental panel was disabled by #6678 , closing this bug.
