### ISSUE TITLE
Clicking "Env impact 81% greater than similar products" should open products that are better than this one

### ISSUE THREAD

**Issue by jasmeet0817** [openfoodfacts/openfoodfacts-server#6584]
### What
- I was at the supermarket today and saw that a product I was about to buy has bad env impact compared to it's peers. I tried finding a better one but couldn't find. Could clicking this button do a search for these products that are actually better?

![image](https://user-images.githubusercontent.com/7541730/151249471-76ab1c58-e368-4d48-8946-ed8b1bd2cac4.png)

**Comment by stephanegigandet** [comment]
I think we should just remove this panel for now, as it's still very experimental.
