### ISSUE TITLE
Missing title for the environment card in the knowledge panels

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#6590]
### Describe the bug

See https://github.com/openfoodfacts/smooth-app/issues/1534

### To Reproduce

https://world.openfoodfacts.org/product/3017620422003/nutella-ferrero?fields=knowledge_panels

### Expected behavior

there should be a non empty title

### Type of device

Other

**Comment by yuktea** [comment]
@stephanegigandet I was testing this PR out, the link you mentioned in the issue seems off. Is it the correct link?
