### ISSUE TITLE
Better distinction between user-created Categories and taxonomized Categories

### ISSUE THREAD

**Issue by TaciteOFF** [openfoodfacts/openfoodfacts-server#66]
The current *List of Categories* pages allows us to see which categories were added by users and aren't present in the Global Categories Taxonomy. 
Allowing visitors to see that directly in each product page could also help contributors to easily spot errors, thus easily correcting product pages with misleading categories.

**Comment by hangy** [comment]
Added a possible solution in commit f1e4462.
