### ISSUE TITLE
HTTPS Open Beauty Facts redirects to Open Food Facts

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#660]
![image](https://cloud.githubusercontent.com/assets/1689815/22247976/bbd4b5ee-e23c-11e6-9328-4afc73ad48ee.png)

**Comment by stephanegigandet** [comment]
Open Beauty Facts now has a wildcard SSL certificate to. :)
https://world.openbeautyfacts.org/
