### ISSUE TITLE
Recognize "Dry" as an ingredient processing type synonymous to "Dried"

### ISSUE THREAD

**Issue by yuktea** [openfoodfacts/openfoodfacts-server#6634]
### Describe the bug

A considerable number of products used the prefix "dry" instead of "dried" when indicating the processing type.
Ingredients are not recognized correctly when "dry" is used.
Example: `Dry Mango` is not recognized as an ingredient but `Dried Mango` is
 

### To Reproduce

https://us.openfoodfacts.org/ingredients?filter=dry

### Expected behavior

We should recognize include `dry` as a secondary word for `dried`

**Comment by ditsuke** [comment]
Closed in #6636
