### ISSUE TITLE
Harcoded string

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#665]
Hardcoded string in French
```Effacer l'utilisateur```
https://github.com/openfoodfacts/openfoodfacts-server/blob/aefb7fb577072af3164ab7f368df3b6488391bca/cgi/user.pl#L115

**Comment by hangy** [comment]
https://github.com/openfoodfacts/openfoodfacts-server/blob/397f6c08970cade271ea9ec3a1ab04938df4e198/cgi/product_multilingual.pl#L1842
https://github.com/openfoodfacts/openfoodfacts-server/blob/397f6c08970cade271ea9ec3a1ab04938df4e198/cgi/product_multilingual.pl#L1854-L1860

**Comment by hangy** [comment]
https://github.com/openfoodfacts/openfoodfacts-server/blob/1846caf9514e6b570b87c7676b31f0026bfda355/lib/ProductOpener/Images.pm#L582

**Comment by stephanegigandet** [comment]
I'd leave the edit comments in English for now, I don't see a good way to translate them (and comments entered by users in free text are not translated anyway)

			my $store_comment = "new image $imgid";

**Comment by suhasdarsi** [comment]
I would like to take this up, can you describe what is that you exactly want me to fix here
thank you :)

**Comment by areeshatariq** [comment]
Is this issue has been solved? SInce I could not find **Effacer l'utilisateur** in **user.pl** file

**Comment by teolemon** [comment]
It has been solved, indeed @areeshatariq 👍 
https://github.com/openfoodfacts/openfoodfacts-server/blob/master/cgi/user.pl#L129
I'm closing the issue
