### ISSUE TITLE
Add the NOVA and Nutri-Score page as source of the Nutri-Score/NOVA computation details knowledge panel

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#6679]
### What

- [ ] Add the NOVA and Nutri-Score page url as source of the Nutri-Score/NOVA computation details knowledge panel

### Part of 
- #5493

**Comment by stephanegigandet** [comment]
This is the same as https://github.com/openfoodfacts/openfoodfacts-server/issues/6689 right? It's not really a source, it's a detailed presentation.

**Comment by teolemon** [comment]
Yes, probably (we link to the scientific paper in the detailed presentation though)

**Comment by stephanegigandet** [comment]
Closing.
