### ISSUE TITLE
No more sold products should not be available for search

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-server#6696]
### What

We promise to producer that if they mark a product as "taken off the market" they should not be found doing a search.
But as you search them, you find them.

### Steps to Reproduce

1. Go to https://world.openfoodfacts.org/product/3760307950145/la-jucerie and see that it is "taken off the market"
2. Go to front page and [search "jucerie"](https://world.openfoodfacts.org/cgi/search.pl?action=process&search_terms=Jucerie&sort_by=unique_scans_n&page_size=24)
3. you see the product in result page

### Expected behavior

The product should not appear in a search (but maybe, a search on barcode).
Still, it should be reachable by its url.

### Part of
- #8814

**Comment by teolemon** [comment]
We downrank them, not make them disappear alltogether

**Comment by alexgarel** [comment]
@manon-corneille this issue might be of interest to you.

**Comment by aakankshabhende** [comment]
I would like to work on this issue @alexgarel

**Comment by alexgarel** [comment]
@aakankshabhende this might be a difficult issue, just because the codebase is large ! Also because it's a bit controversial, and I think to make this resolution acceptable we should also add a "include unsold products" checkbox on the advanced search, and/or display the number of hidden unsold products on a search.

**Comment by alexgarel** [comment]
We finally separated in two collections : obsolete products and others.

See #8277
