### ISSUE TITLE
[l10n ru] Barcode recognition failure message does not appear correctly.

### ISSUE THREAD

**Issue by aleksejrs** [openfoodfacts/openfoodfacts-server#670]
Upload a barcode image that cannot be recognized.  The red rectangle says:
"Ð§Ð¸Ñ‚Ð°ÐµÐ¼Ñ‹Ð¹ ÑˆÑ‚Ñ€Ð¸Ñ…-ÐºÐ¾Ð´ Ð½Ð° ÐºÐ°Ñ€Ñ‚Ð¸Ð½ÐºÐµ Ð½Ðµ Ð¾Ð±Ð½Ð°Ñ€ÑƒÐ¶ÐµÐ½."

**Comment by hangy** [comment]
Most likely not a translation bug, but just wrong encoding. The content-type of the AJAX response is incorrect `Content-Type:text/html; charset=ISO-8859-1`.
