### ISSUE TITLE
Há uma coisa NOVA

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#6702]
### What
- Há uma coisa NOVA. 
- Also visible @ https://world-es.openfoodfacts.org/product/4063367145599/party-gurken-k-classic
### Screenshot
![image](https://user-images.githubusercontent.com/1689815/165360841-532e7faf-54fa-47d2-93f8-2c764361b0d4.png)

**Comment by teolemon** [comment]
Can we test it ?

**Comment by stephanegigandet** [comment]
Yes, I added tests.

**Comment by teolemon** [comment]
purrrfect. closing
