### ISSUE TITLE
Editing Salt/Sodium content field does not work correctly with fractions without leading zero

### ISSUE THREAD

**Issue by aquilax** [openfoodfacts/openfoodfacts-server#6717]
### Describe the bug

On the product edit page, setting fractional salt or sodium value without leading zero produces incorrect calculated value for the corresponding field.

### To Reproduce

1. Open a product edit page
2. Set Salt content to `.53` and move to the next field
3. Sodium content is calculated as `.21.200000000000003`

### Expected behavior

Calculation to work without setting leading zero to the fraction.

### Screenshots

![Screenshot_2022-04-29_10-07-34](https://user-images.githubusercontent.com/328067/165907201-0a153cc1-cd3f-42a4-955a-11c8512fd4c6.png)

### Additional context

```js
	function swapSalt(from, to, multiplier) {
		var source = from.val().replace(",", ".");
		var regex = /^(.*?)([\d]+(?:\.[\d]+)?)(.*?)$/g;
		var match = regex.exec(source);
		if (match) {
			var target = match[1] + (parseFloat(match[2]) * multiplier) + match[3];
			to.val(target);
		} else {
			to.val(from.val());
		}
	}
```
The swap salt function concatenates `match[1]` in front of the result which leads to having the decimal point twice.

### Type of device

Browser

### Browser version

Version 100.0.4896.127 (Official Build) (64-bit)

**Comment by danwyk** [comment]
@teolemon  I can work on this. Can you assign this bug to me.
