### ISSUE TITLE
Add capability to search for users

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-server#6720]
### Is your feature request related to a problem? Please describe.

In pro platform we would like to retrieve users that are part of an org.
Also we may want to know all users with a certain mail domain (corresponding to a producer).

We may also want to be able to list all moderators of the platform.

### Describe the solution you'd like

Put users in mongodb, in their own collection.

We would avoid "personal information" like email. But we could keep "email domain" as it is meaningfull.

* at user creation / edition / deletion,  index user data in mongo
* create a script to re-sync user folder in mongo (will also bootstrap the db)

### Additional context

First feature we could do is to display the list of users on the pro platform org profile.

We could also simplify script that export users for NL to a simple mongo request.

This could also help add monitoring capabilities to users (logging to the right monitoring db, if we want historical data)

**Comment by stephanegigandet** [comment]
> We could also simplify script that export users for NL to a simple mongo request.

Then we need emails. I don't see the issue with having the emails in the mongodb collection, it won't be made public.

**Comment by alexgarel** [comment]
>> We could also simplify script that export users for NL to a simple mongo request.
> Then we need emails. I don't see the issue with having the emails in the mongodb collection, it won't be made public.

No we need second part of the mail ;-)

Yes this is some kind of RGPD extra security, for I feel this is easier that mongo leaks at some point (we just protect it by a firewall rule) than our filesystem…
But yes it disable eg. exporting users for ML.
So we can discuss it ;-)

**Comment by alexgarel** [comment]
Note that we might want current work on Ory to land before thinking of this (as we may use Kratos capabilities).

**Comment by manon-corneille** [comment]
Fixed by https://github.com/openfoodfacts/openfoodfacts-server/issues/6978
