### ISSUE TITLE
Hide all nutritional related info if we say that there are no nutritional info on the box

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-server#6729]
- Following #6457 

This misunderstanding happens because while the checkbox saying "Nutrition facts are not specified on the product.", we hide some nutrional info form elements but we still display others.

Solution: on the product edit page, hide all form elements related to nutritional info in this case, including image selection, image etc.

**Comment by CharlesNepote** [comment]
As of 2023-03-15 there are at least [5000+ products in this case](https://mirabelle.openfoodfacts.org/products?sql=select+--rowid%2C+code%2C+url%2C+creator%2C+created_t%2C+created_datetime%2C+last_modified_t%2C+last_modified_datetime%2C+last_modified_by%2C+product_name%2C+abbreviated_product_name%2C+generic_name%2C+quantity%2C+packaging%2C+packaging_tags%2C+packaging_en%2C+packaging_text%2C+brands%2C+brands_tags%2C+categories%2C+categories_tags%2C+categories_en%2C+origins%2C+origins_tags%2C+origins_en%2C+manufacturing_places%2C+manufacturing_places_tags%2C+labels%2C+labels_tags%2C+labels_en%2C+emb_codes%2C+emb_codes_tags%2C+first_packaging_code_geo%2C+cities%2C+cities_tags%2C+purchase_places%2C+stores%2C+countries%2C+countries_tags%2C+countries_en%2C+ingredients_text%2C+ingredients_tags%2C+ingredients_analysis_tags%2C+allergens%2C+allergens_en%2C+traces%2C+traces_tags%2C+traces_en%2C+serving_size%2C+serving_quantity%2C+no_nutrition_data%2C+additives_n%2C+additives%2C+additives_tags%2C+additives_en%2C+nutriscore_score%2C+nutriscore_grade%2C+nova_group%2C+pnns_groups_1%2C+pnns_groups_2%2C+food_groups%2C+food_groups_tags%2C+food_groups_en%2C+states%2C+states_tags%2C+states_en%2C+brand_owner%2C+ecoscore_score%2C+ecoscore_grade%2C+nutrient_levels_tags%2C+product_quantity%2C+owner%2C+data_quality_errors_tags%2C+unique_scans_n%2C+popularity_tags%2C+completeness%2C+last_image_t%2C+last_image_datetime%2C+main_category%2C+main_category_en%2C+image_url%2C+image_small_url%2C+image_ingredients_url%2C+image_ingredients_small_url%2C+image_nutrition_url%2C+image_nutrition_small_url%2C+%5Benergy-kj_100g%5D%2C+%5Benergy-kcal_100g%5D%2C+energy_100g%2C+%5Benergy-from-fat_100g%5D%2C+fat_100g%2C+%5Bsaturated-fat_100g%5D%2C+%5Bbutyric-acid_100g%5D%2C+%5Bcaproic-acid_100g%5D%2C+%5Bcaprylic-acid_100g%5D%2C+%5Bcapric-acid_100g%5D%2C+%5Blauric-acid_100g%5D%2C+%5Bmyristic-acid_100g%5D%2C+%5Bpalmitic-acid_100g%5D%2C+%5Bstearic-acid_100g%5D%2C+%5Barachidic-acid_100g%5D%2C+%5Bbehenic-acid_100g%5D%2C+%5Blignoceric-acid_100g%5D%2C+%5Bcerotic-acid_100g%5D%2C+%5Bmontanic-acid_100g%5D%2C+%5Bmelissic-acid_100g%5D%2C+%5Bunsaturated-fat_100g%5D%2C+%5Bmonounsaturated-fat_100g%5D%2C+%5Bpolyunsaturated-fat_100g%5D%2C+%5Bomega-3-fat_100g%5D%2C+%5Balpha-linolenic-acid_100g%5D%2C+%5Beicosapentaenoic-acid_100g%5D%2C+%5Bdocosahexaenoic-acid_100g%5D%2C+%5Bomega-6-fat_100g%5D%2C+%5Blinoleic-acid_100g%5D%2C+%5Barachidonic-acid_100g%5D%2C+%5Bgamma-linolenic-acid_100g%5D%2C+%5Bdihomo-gamma-linolenic-acid_100g%5D%2C+%5Bomega-9-fat_100g%5D%2C+%5Boleic-acid_100g%5D%2C+%5Belaidic-acid_100g%5D%2C+%5Bgondoic-acid_100g%5D%2C+%5Bmead-acid_100g%5D%2C+%5Berucic-acid_100g%5D%2C+%5Bnervonic-acid_100g%5D%2C+%5Btrans-fat_100g%5D%2C+cholesterol_100g%2C+carbohydrates_100g%2C+sugars_100g%2C+%5Badded-sugars_100g%5D%2C+sucrose_100g%2C+glucose_100g%2C+fructose_100g%2C+lactose_100g%2C+maltose_100g%2C+maltodextrins_100g%2C+starch_100g%2C+polyols_100g%2C+erythritol_100g%2C+fiber_100g%2C+%5Bsoluble-fiber_100g%5D%2C+%5Binsoluble-fiber_100g%5D%2C+proteins_100g%2C+casein_100g%2C+%5Bserum-proteins_100g%5D%2C+nucleotides_100g%2C+salt_100g%2C+%5Badded-salt_100g%5D%2C+sodium_100g%2C+alcohol_100g%2C+%5Bvitamin-a_100g%5D%2C+%5Bbeta-carotene_100g%5D%2C+%5Bvitamin-d_100g%5D%2C+%5Bvitamin-e_100g%5D%2C+%5Bvitamin-k_100g%5D%2C+%5Bvitamin-c_100g%5D%2C+%5Bvitamin-b1_100g%5D%2C+%5Bvitamin-b2_100g%5D%2C+%5Bvitamin-pp_100g%5D%2C+%5Bvitamin-b6_100g%5D%2C+%5Bvitamin-b9_100g%5D%2C+folates_100g%2C+%5Bvitamin-b12_100g%5D%2C+biotin_100g%2C+%5Bpantothenic-acid_100g%5D%2C+silica_100g%2C+bicarbonate_100g%2C+potassium_100g%2C+chloride_100g%2C+calcium_100g%2C+phosphorus_100g%2C+iron_100g%2C+magnesium_100g%2C+zinc_100g%2C+copper_100g%2C+manganese_100g%2C+fluoride_100g%2C+selenium_100g%2C+chromium_100g%2C+molybdenum_100g%2C+iodine_100g%2C+caffeine_100g%2C+taurine_100g%2C+ph_100g%2C+%5Bfruits-vegetables-nuts_100g%5D%2C+%5Bfruits-vegetables-nuts-dried_100g%5D%2C+%5Bfruits-vegetables-nuts-estimate_100g%5D%2C+%5Bfruits-vegetables-nuts-estimate-from-ingredients_100g%5D%2C+%5Bcollagen-meat-protein-ratio_100g%5D%2C+cocoa_100g%2C+chlorophyl_100g%2C+%5Bcarbon-footprint_100g%5D%2C+%5Bcarbon-footprint-from-meat-or-fish_100g%5D%2C+%5Bnutrition-score-fr_100g%5D%2C+%5Bnutrition-score-uk_100g%5D%2C+%5Bglycemic-index_100g%5D%2C+%5Bwater-hardness_100g%5D%2C+choline_100g%2C+phylloquinone_100g%2C+%5Bbeta-glucan_100g%5D%2C+inositol_100g%2C+carnitine_100g%0D%0Acode%0D%0A%2C+url%0D%0A%2C+creator%0D%0A%2C+count%28no_nutrition_data%29+as+c%0D%0A%2C+no_nutrition_data%0D%0A%2C+image_nutrition_url%0D%0Afrom+%5Ball%5D%0D%0Awhere+true%0D%0A--and+no_nutrition_data+%21%3D+%22%22%0D%0A--and+%28no_nutrition_data+%3D%3D+%22true%22%29--+or+no_nutrition_data+%3D%3D+%22on%22%29%0D%0Aand+image_nutrition_url+%21%3D+%22%22%0D%0Agroup+by+no_nutrition_data%0D%0Aorder+by+c+desc%0D%0A--order+by+random%28%29%0D%0Alimit+210).

**Comment by jnsereko** [comment]
hey @yuktea 
This looks interesting.  Can you kindly assign it to me 
thanks

**Comment by jnsereko** [comment]
created  PR:https://github.com/openfoodfacts/openfoodfacts-server/pull/8232
