### ISSUE TITLE
Migrate data from one language to another

### ISSUE THREAD

**Issue by archanox** [openfoodfacts/openfoodfacts-server#6731]
### Is your feature request related to a problem? Please describe.

Contributors using the yuka app are are prone to inputting data with the wrong language. Which also causes the app to input the data as available in France. Whilst the data is in English, it is marked against the French language
https://world.openfoodfacts.org/product/9310412003881/natural-pink-himalayan-table-salt-shaker-saxa?rev=1

### Describe the solution you'd like

When fixing this issue, it leads to reentering the data in English from the source imagery. Preferably there'd be a "Migrate to English" button.

### Describe alternatives you've considered

The alternative as described above is to re-enter the already entered data for the correct language and then deleting the incorrectly inputted data for the wrong language.

### Additional context

I don't know if this is purely caused by the yuka app, but I have seen this issue appear time and time again.

### Number of products impacted

I have thus far witnessed at least half a dozen, but I believe the issue is widespread.

### Time per product

An extra 5-10 minutes re-entering and deleting data from one language to another.

**Comment by archanox** [comment]
Unfortunately there doesn't seem to be a way for me to do this using the standard plugins on iOS/iPadOS. So I'm left a little high and dry as this is my primary device I use.

I was told maintainer permissions would also allow me to do this, but alas I do not see the relevant buttons.

**Comment by stephanegigandet** [comment]
So when you change the value of "Main language", you do not see those 2 checkboxes appear?

![image](https://user-images.githubusercontent.com/8158668/167665112-190e26a6-5743-49ab-bde9-cdfb6baa6873.png)

**Comment by archanox** [comment]
On Safari on iPadOS, no I do not. Perhaps it is a UserScript only thing?
