### ISSUE TITLE
The UTZ Certified label has no French translation in the labels taxonomy

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#6746]
### What
- The UTZ Certified label appears untaxonomized in Smoothie
- Link for a scannable barcode: barcode-20968663

### Screenshots
![image](https://user-images.githubusercontent.com/1689815/167113200-4eee3268-7504-42e7-bfbb-5c8a4c319f2c.png)

### Part of
- https://github.com/openfoodfacts/openfoodfacts-server/milestone/37

**Comment by stephanegigandet** [comment]
Just a missing translation in the labels taxonomy, I'll add it.
