### ISSUE TITLE
UI: identify features that are only available for moderators

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#6758]
### What
- Sometimes we, as moderators, think a feature is available to everybody while it is not. That can create confusion when talking with other users.

### Proposed solution

- We should visually identify features that are only available for moderators.

### Part of
- #9308

**Comment by alexgarel** [comment]
In `/templates/web/pages/product_edit/product_edit_form_display.tt.html`, add a class to every elements that are under a `[% IF moderator...` or a `[% IF admin...`. 

Then add a CSS rule for this class to make it visible (in _off.scss ?)

**Comment by teolemon** [comment]
@stephanegigandet We could use the shield/police material symbols, and also have a distinctive color, like "traffic light orange" or "construction yellow"
