### ISSUE TITLE
Brand json write api fail

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#676]
I am not able to update a brand with the json write api. Example url (without the userID/password):

https://ssl-api.openfoodfacts.org/cgi/product_jqm2.pl?code=3256225094585&lang=fr&brand=U

**Comment by aleene** [comment]
Found the solution. 

The write key to use is "brands=".

**Comment by teolemon** [comment]
Does it work with brand= when there is no brand ?
It was already documented in the API doc afaik.

**Comment by aleene** [comment]
No, that was my bug report, i.e. creating a brand from scratch.
