### ISSUE TITLE
Fix file system path structure for short bar codes

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#677]
In the file system, products and images are stored in a separate directory for each product (using the barcode).

In order to avoir 1 big directory with 150000 (and growing) sub-directories (1 for each product), the barcode is split in groups of 3 digits.

````
sub product_path($) {

	my $code = shift;
	$code !~ /^\d+$/ and return "invalid";
	
	if (length($code) > 100) {
		print STDERR "invalid code, too long code: $code\n";
		return "invalid";
	}
	
	my $path = $code;
	if ($code =~ /^(...)(...)(...)(.*)$/) {
		$path = "$1/$2/$3/$4";
	}
	return $path;
}
````

This causes issues for shorter barcodes, and even path collisions in some cases. There is one case where this causes problems.

We need to find a better directory structure. One idea could be to pad all barcodes with leading or tailing digits (or another char) so that they have the same length on disk.

**Comment by hangy** [comment]
Would it maybe make sense to solve this and the request to use unique product ids in one go? If we go and move from the product barcode being the products primary identifier to the product id and the possibility of using a barcode for multiple products, a similar migration of the existing product files/images would be required.

**Comment by hangy** [comment]
@stephanegigandet 
> One idea could be to pad all barcodes with leading or tailing digits (or another char) so that they have the same length on disk.

IMHO, the [GS1 Spec](https://www.gs1.org/docs/barcodes/GS1_General_Specifications.pdf) provides a good guideline in the chapter `2.1.1.10 GTIN data string`:
> When any of these GTINs is encoded in a data carrier that must encode a fixed-length data string of
14-digits, the GTINs less than 14-digits in length must be prefixed by leading zeroes that simply act
as filler digits.

**Comment by stephanegigandet** [comment]
Prefixing with 0 sounds good to me. One challenge is how to change the paths while keeping the site working. One option could be to move the directories to the new structure, and leave a symbolic link from the original path.

**Comment by hangy** [comment]
Yes, that's what I thought, too. Do we need to keep the old directory structure in place in the images directory, because other apps (ie. robotoff) link there? If we need to keep the directories/files at the old structure for compatibility reasons, we could also save the problems related to moving and then symlinking files (race condition if someone tries to edit the product at the same time) by just symlinking the new directory structure.

**Comment by stephanegigandet** [comment]
Well I'd like to remove the symlinks at some point... so I'd prefer to move to the new structure. The chance that someone would update a product at the exact time that we move it to the new structure and then create the symlink is very very small I believe.

**Comment by stephanegigandet** [comment]
There are 2 different problems in fact:

1. Which id we use to store products (the topic of this bug: the path structure).
2. How we normalize barcodes that we receive from scanners, from producers etc. that may be padded with extra 0s compared to what is actually printed.

For 1. , internally, we could use the EAN-13 digits, and add leading 0s if we have less digits (e.g. EAN-8). I think we should use 13 and not 14. This works unless it actually happens that an EAN-8 with leading 0s becomes a different EAN-13.

**Comment by hangy** [comment]
> I think we should use 13 and not 14.

I'd actually prefer GTIN-14. If not for [variable measure trade items](https://gs1lv.org/img/upload/ENG.Variable%20measure_in_Latvia.pdf), then for other products (ie. regulated medical items) on Open Product Facts (see [GS1 spec](https://www.gs1.org/docs/barcodes/GS1_General_Specifications.pdf) section 2.1.8).

**Comment by stephanegigandet** [comment]
The code we store should be the barcode that is on the package: EAN-8 or EAN-13 or GTIN-14 or whatever is coming next. Ideally the id we use (for mongo, the path etc.) should match the code, possibly padded with 0s if there is no chance of conflict. Or maybe it's in fact better to pad them with another character.

**Comment by stephanegigandet** [comment]
I looked at the GTIN-14, the good thing is that the usual GTIN-14 for EAN-13 is to put a 0 first, then the 12 first digits of the EAN-13, and then to compute the check digit. With a leading 0, it's the same check digit as the EAN-13, so we end up with GTIN-14 = 0 + EAN-13. :-)

In practice, we have about 100K OFF generated codes (for products without barcodes) that started at 2000000000000 with 1 added. (I wasn't aware of the check digit at that time), so those are not valid EAN-13. I guess we can just add a leading 0 anyway, that will make invalid GTIN-14 but that's already the case with the EAN-13.

**Comment by hangy** [comment]
> I looked at the GTIN-14, the good thing is that the usual GTIN-14 for EAN-13 is to put a 0 first, then the 12 first digits of the EAN-13, and then to compute the check digit. With a leading 0, it's the same check digit as the EAN-13, so we end up with GTIN-14 = 0 + EAN-13. :-)

Yup, to store GTIN-13 as a GTIN-14 data string, the string would be right aligned and padded with zeroes. (source: "Figure 2.1.1.10-2. 14-digit representation of the four GTIN formats") The advantage is that this can also be done with GTIN-8 and would allow equal distribution of path segments for this file system path issue. I'd probably normalize them to GTIN-14 for storage and search, and display them without padded zeroes for readability.

> In practice, we have about 100K OFF generated codes (for products without barcodes) that started at 2000000000000 with 1 added. (I wasn't aware of the check digit at that time), so those are not valid EAN-13. I guess we can just add a leading 0 anyway, that will make invalid GTIN-14 but that's already the case with the EAN-13.

IMHO, the internal code range should be reviewed anyways, because of potential conflicts with actual products: https://github.com/openfoodfacts/openfoodfacts-server/issues/1642#issue-406092206

**Comment by stephanegigandet** [comment]
Fixed by https://github.com/openfoodfacts/openfoodfacts-server/pull/10472
