### ISSUE TITLE
No way to know what the portion is

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#6777]
### What
No way to know what the portion is
### Screenshot
![image](https://user-images.githubusercontent.com/1689815/168047071-5a6ee17e-4d48-4112-9d37-f842acb73887.png)

**Comment by alexgarel** [comment]
I've done a PR: #6793 though I'm not sure: do we want the serving size to always be there or only if nutrition table is "per serving size" ?
