### ISSUE TITLE
Image uploads fail

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#678]
I think the issue is the code that I'm commenting below:

(in Images.pm)

			# ! the following does not work, the file is not created
			
			#open (my $FILE, q{>}, "$www_root/images/products/$path/$imgid.$extension") or print STDERR "Images.pm - Error - Could not save $www_root/images/products/$path/$imgid.$extension : $!\n";
			#while (<$file>) {
			#	print $FILE;
			#}
			#close ($FILE);

Replacing with the original code, until we find a better code.
			
			open (FILE, ">$www_root/images/products/$path/$imgid.$extension") or print STDERR "Images.pm - Error - Could not save $www_root/images/products/$path/$imgid.$extension : $!\n";
			while (<$file>) {
				print FILE;
			}
			close (FILE);

**Comment by TaciteOFF** [comment]
Still not working on the website.

"Erreur lors de l'envoi"

**Comment by stephanegigandet** [comment]
Thanks. Fixed for web site uploads.

**Comment by hangy** [comment]
That's weird. 😢 
According to https://perlmaven.com/open-files-in-the-old-way this should be the better way to use file handles, and the following test actually works fine on my shell. Any idea what might be wrong?

```
use utf8;
use Modern::Perl '2012';

my $filename = "test.txt";
open (my $FILE, q{>}, $filename) or die "could not open $filename";
print $FILE "test";
close ($FILE);
```
