### ISSUE TITLE
Add a way to have knowledge panels collapsed in the app but not on the website (list of ingredients + nutrition table)

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#6786]
### What
Add a way to have knowledge panels collapsed in the app but not on the website (list of ingredients + nutrition table)
### Part of
- #5493

**Comment by alexgarel** [comment]
@stephanegigandet for this, my proposal would be:

* pass expended to false
* add a property expand_for: with a list of device size (eg: large) (alternatively it cloud also be device type like "web")
* modify the web rendering to take expand_for into account (as first implementation, we will always consider we are large)

**Comment by stephanegigandet** [comment]
@alexgarel That sounds perfect to me. Using device size is a very good idea I think, on mobile web it certainly makes sense to have less things expanded by default. I'm not sure how easy it will be to make it work with Foundation on the web, but it doesn't matter, in a first iteration, we can just web = large, and we can figure it out later.
