### ISSUE TITLE
Add all PRs (including chores) in changelog generated by release-please, or use fix: or feat: for taxonomy updates

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#6795]
### Is your feature request related to a problem? Please describe.

The CHANGELOG.md file generated by release-please lists only PRs that are marked as features and bug fixes:

https://github.com/openfoodfacts/openfoodfacts-server/pull/6754

This hides PRs that were marked as chores that are still very useful to list (in particular additions to taxonomies).

### Describe the solution you'd like

So either we could include chores in the changelog, or we could mark taxonomy updates as fixes.

### Describe alternatives you've considered

Changelog configuration seems to be possible:

https://github.com/conventional-changelog/standard-version/blob/227712d7eaf930fb8896c26e6391ac3bcb810edb/README.md#customizing-changelog-generation

https://github.com/conventional-changelog/conventional-changelog-config-spec/blob/master/versions/2.1.0/README.md

**Comment by alexgarel** [comment]
@teolemon and @stephanegigandet 

I agree this is an issue.

I would advise to keep chore out of Changelog but preserve it for real chores !

I think we can add more prefixes to PR:
* one for taxonomies: maybe `data:`
* one for translations: maybe `lang:`

and include them in releases.

**Comment by alexgarel** [comment]
It's done.
