### ISSUE TITLE
teolemon needs to be able to reload taxonomies

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#680]
States taxonomy needs to be reloaded since we have a new state
```Packaging-code-to-be-completed```

https://en.wiki.openfoodfacts.org/Global_states_taxonomy

**Comment by stephanegigandet** [comment]
We need a better streamlined process to update taxonomies. At least for "simple" taxonomies where the risk of exploding everything is not too high. (categories can be dangerous)

**Comment by teolemon** [comment]
is it about replacing a file and running a perl script ?
