### ISSUE TITLE
Facets: non existing facets url should return a 404

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-server#6802]
### Describe the bug

If you mispell a facet : 
* https://world.openfoodfacts.org/data-quality/non-nutrition-data (*non* instead of *no*) show you a page (eventually with no products)
* https://world.openfoodfacts.org/category/breads/no-nutrition-data (forgot data-quality in uri) the application show you breads

this would be better to have a 404, "the facet does not exists".

It bites me once or twice, and bites again today ! (on the producer platform)

**Comment by stephanegigandet** [comment]
> * https://world.openfoodfacts.org/data-quality/non-nutrition-data (_non_ instead of _no_) show you a page (eventually with no products)

For this one, non-nutrition-data is the value of the facet data-quality. It does not exist in the taxonomy, but facets can contain non taxonomized values, so I think the behaviour here is correct.

> * https://world.openfoodfacts.org/category/breads/no-nutrition-data (forgot data-quality in uri) the application show you breads

Agreed, that one should return an error like "The no-nutrition-data facet does not exist".

**Comment by dipietroR** [comment]
It sounds like https://world.openfoodfacts.org/category/breads/no-nutrition-data is supposed to have data-quality somewhere in it. Can I get an example of a link with data-quality in it?

**Comment by stephanegigandet** [comment]
> It sounds like https://world.openfoodfacts.org/category/breads/no-nutrition-data is supposed to have data-quality somewhere in it. Can I get an example of a link with data-quality in it?

The right url would be https://world.openfoodfacts.org/category/breads/data-quality/no-nutrition-data


The URL structure is like this:

/[facet name like brands, labels, data-quality] : gives the list of values for that facet
/[facet name]/[facet value] : gives the list of products that have the facet value (e.g. /label/organic )
/[facet name]/[facet value]/[another facet name] : list of values for "another facet" for all products that have the first facet value
/[facet name]/[facet value]/[another facet name]/[another facet value] : list of products with both facet values

**Comment by teolemon** [comment]
Nice 404 page from Hunger Games
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/1689815/195075593-3aeb2e48-da55-4be7-be17-6d9eca164b97.png">

**Comment by MonalikaPatnaik** [comment]
> 

Hii..I would like to work on this..Could you pls tell me the path of file Display.pm, I'm unable to find it :)

**Comment by hangy** [comment]
> Hii..I would like to work on this..Could you pls tell me the path of file Display.pm, I'm unable to find it :)

The method that Stéphane mentioned has now been moved: https://github.com/openfoodfacts/openfoodfacts-server/blob/9253e4e24068629ed4e0ca1d947f38920c96dd30/lib/ProductOpener/Routing.pm#L59-L552
