### ISSUE TITLE
Collapse by default the ingredients and the nutrition on mobile knowledge panels

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#6805]
### What

- [ ] Collapse by default the ingredients and the nutrition on mobile knowledge panels

### Related to 
- #6786 

<img width="374" alt="image" src="https://user-images.githubusercontent.com/1689815/169603892-773cc85c-3690-424d-bfe9-e6cae5d848dd.png">

**Comment by stephanegigandet** [comment]
Same as #6786

**Comment by teolemon** [comment]
Done
