### ISSUE TITLE
Refactor and document current_link / current_link_query 

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#6819]
In many part of the code (in particular Display.pm, search.pl and templates/web/common/includes/list_of_products.tt.html) we have variables like $current_link and $current_link_query that are passed through $request_ref and used in some templates.

The use of those variables is often to construct an URL to point to the current page, but with all parameters included either in the path or in the query part of the URL. So for instance if we have a search request with POST parameters, we reconstruct a URL with GET parameters that can be shared, and that the templates can extend with extra parameters (e.g. adding a parameter to download the search results, or changing the subdomain to make the query on world.openfoodfacts.org).

The distinction between current_link and current_link_query is probably not useful. Also it's not very clear / consistent whether those links are / should be absolute or relative URLs.

So it would definitely make a lot of sense to rethink this, and use a consistent, simple, and documented method to do this.

See original discussion on https://github.com/openfoodfacts/openfoodfacts-server/pull/6817

**Comment by dipietroR** [comment]
I'd like to work on this, I'll start looking at what the variables are doing and how we might clean them up and document them.

**Comment by yuktea** [comment]
Closed in #6832
