### ISSUE TITLE
Refreshing the Eco-Score with the logos from Quentin

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#6825]
### What

- [ ] Refreshing the Eco-Score with the logos from Quentin
- [ ] Server side PR: https://github.com/openfoodfacts/openfoodfacts-server/pull/6830

<img width="210" alt="image" src="https://user-images.githubusercontent.com/1689815/170727357-ea104b98-e258-4d3c-93e5-de3433f26e38.png">
https://www.figma.com/file/nFMjewFAOa8c4ahtob7CAB/Mobile-App-Design-(Quentin)?node-id=155%3A1991

**Comment by VaiTon** [comment]
Closed by #6848
