### ISSUE TITLE
Add the F-Droid version in the website

### ISSUE THREAD

**Issue by ghost** [openfoodfacts/openfoodfacts-server#6826]
I'd like to suggest to add a button for [F-Droid version](https://f-droid.org/en/packages/openfoodfacts.github.scrachx.openfood) in https://world.openfoodfacts.org/open-food-facts-mobile-app together with App Store, Play Store and others

![image](https://user-images.githubusercontent.com/105953528/170816134-a0a4e0d6-9dc3-4de2-bf30-35c0fd6da265.png)

![image](https://user-images.githubusercontent.com/105953528/170816188-ac3c3190-627d-4cdf-9eec-3ae21e28aca3.png)

**Comment by alexgarel** [comment]
@ghost you are perfectly right. But before we have to ship the last version of the app in F-Droid, which is not as easy as it seems, see: https://github.com/openfoodfacts/smooth-app/issues/1882

**Comment by alexgarel** [comment]
Fdroid is now on https://world.openfoodfacts.org/open-food-facts-mobile-app

![image](https://github.com/openfoodfacts/openfoodfacts-server/assets/144788/002d40ed-080d-46dd-8df3-6476a2b2cb17)
