### ISSUE TITLE
Unit names (e.g. grams) are not recognized for quantity and serving size normalization (only unit symbol e.g. g)

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#6843]
### Describe the bug

Nutri-Score not computed when per serving = "100grams".

### To Reproduce

https://world.openfoodfacts.org/product/7350002400104/kikartor-zeta?rev=7

### Expected behavior

Nutri-Score should be computed.

### Type of device

Browser

**Comment by stephanegigandet** [comment]
The function we use to normalize quantity and serving size currently only support unit symboles (like g), but not unit names (like grams or grammes).

Related code: https://github.com/openfoodfacts/openfoodfacts-server/blob/main/lib/ProductOpener/Food.pm#L1224

sub normalize_quantity($)
