### ISSUE TITLE
Undefined variable in search.pl

### ISSUE THREAD

**Issue by dipietroR** [openfoodfacts/openfoodfacts-server#6845]
### Describe the bug

When a blank search is made the following warnings appear:
[Wed Jun  1 20:43:53 2022] -e: Use of uninitialized value in concatenation (.) or string at /opt/product-opener/cgi/search.pl line 661.
[Wed Jun  1 20:43:53 2022] -e: Use of uninitialized value in concatenation (.) or string at /opt/product-opener/cgi/search.pl line 661.
[Wed Jun  1 20:43:53 2022] -e: Use of uninitialized value in concatenation (.) or string at /opt/product-opener/cgi/search.pl line 661.
[Wed Jun  1 20:43:53 2022] -e: Use of uninitialized value in concatenation (.) or string at /opt/product-opener/cgi/search.pl line 661.
[Wed Jun  1 20:43:53 2022] -e: Use of uninitialized value in concatenation (.) or string at /opt/product-opener/cgi/search.pl line 747.

This appears to be because $request_ref->{count} is not defined at those lines.

In looking at search.pl and Display.pm I'm not seeing a point where $request_ref->{count} is set in Display.pm where search.pl is or was calling it. I'm seeing a few instances of the element being set in the hash using:
git log -S'equest_ref->{count}' -- Display.pm

96d31df70a4914b240c66a73d35f436f63093af7
shows the element being removed from search_and_export_products, which is called in search.pl, though adding a static
$request_ref->{count} = 5;
Does not remove the warning.

8f2cfcdee1b03c60530babb225cd6516b08ddab8
shows the element added to the display_ecoscore_calculation_details_simple_html subroutine, though it does not appear that this was ever used in search.pl
`git log -S'display_ecoscore_calculation_details_simple_html' -- search.pl`

2a202e5cdae1da9683d5feccaa69772c8f2883cc
shows the element removed from search_and_display_products. This is used in search.pl. However adding it back in with a static value does not seem to remove the warnings.

926843164eed8f68fe439b9c65935aecb4f6dac4
shows up in the git log search, but I'm not finding $request_ref->{count} in it, perhaps my git search is not correct?

Expanding the search to `git log -S'equest_ref->{count}' -- .` from lib/ProductOpener does not yield any more results

In Display.pm $request_ref->{count} is defined in:
search_and_graph_products
search_and_map_products
search_and_analyze_recipes

of which:
search_and_graph_products
search_and_map_products

are found in the initial commit of search.pl, search_and_analyze_recipes is not found in any version of the file. 

introducing either of these before the $request_ref->{count} variable is used in search.pl will remove two of the warnings, reducing the original warnings to:
[Wed Jun  1 16:44:12 2022] -e: Use of uninitialized value in concatenation (.) or string at /opt/product-opener/cgi/search.pl line 664.
[Wed Jun  1 16:44:12 2022] -e: Use of uninitialized value in concatenation (.) or string at /opt/product-opener/cgi/search.pl line 664.
[Wed Jun  1 16:44:12 2022] -e: Use of uninitialized value in concatenation (.) or string at /opt/product-opener/cgi/search.pl line 664.

It remains unclear to me why the first print is called, at least, four times. So a solution may be further upstream than this. Regardless it seems like this may have never been getting the variable that it needs.

It looks like the second warning line was introduced in 0bbc249b86e38f9110a5643325e9e0f93969c409 other commits that have a string change on 'count' are unrelated counts, 'countries' or the initial commit. So it doesn't look like the $request_ref->{count} variable moved around in the file.

Leaving me with three thoughts, 
1) This print has never had a defined count variable
2) My git searching is lacking
3) There is somewhere else that search.pl would get this variable and I don't understand where it would be.

My guess is 3, but I need some guidance on what that would be.

### To Reproduce

Click the search button with nothing in it; warning will appear in modperl_error_log 

### Expected behavior

No warning should appear.

### Type of device

Browser

**Comment by stephanegigandet** [comment]
> [Wed Jun 1 20:43:53 2022] -e: Use of uninitialized value in concatenation (.) or string at /opt/product-opener/cgi/search.pl line 661. [Wed Jun 1 20:43:53 2022] -e: Use of uninitialized value in concatenation (.) or string at /opt/product-opener/cgi/search.pl line 661. [Wed Jun 1 20:43:53 2022] -e: Use of uninitialized value in concatenation (.) or string at /opt/product-opener/cgi/search.pl line 661. [Wed Jun 1 20:43:53 2022] -e: Use of uninitialized value in concatenation (.) or string at /opt/product-opener/cgi/search.pl line 661. [Wed Jun 1 20:43:53 2022] -e: Use of uninitialized value in concatenation (.) or string at /opt/product-opener/cgi/search.pl line 747.
> 
> This appears to be because $request_ref->{count} is not defined at those lines.

Looking at line 661:

	open (my $OUT, ">>:encoding(UTF-8)", "$data_root/logs/search_log_debug");
	print $OUT remote_addr() . "\t" . time() . "\t" . decode utf8=>param('search_terms') . " - map: " . param("generate_map")
	. " - graph: " . param("graph") . " - download: " . param("download")
		. "\tpage: $page\tcount:" . $request_ref->{count} . "\n";
	close ($OUT);

You can look at what id does: writing some info to a log file.

If you look at the log file:

~/openfoodfacts-server$ tail -f logs/apache2/search_log_debug 

You will see which values are undefined (4 of them, that's why the warning is printed 4 times).

This log is printed before the query is executed, so count is never set, we can remove it. And for the other variables, we can check if they are undef and in that case use an empty string.  Something like $variable || ""

**Comment by alexgarel** [comment]
I think we can close this (see PR above)
