### ISSUE TITLE
Implement ory kratos

### ISSUE THREAD

**Issue by LandonPattison** [openfoodfacts/openfoodfacts-server#6864]
### What

- [ ] Quickstart guide - https://www.ory.sh/docs/kratos/quickstart
- [ ] Allows For - 
- [ ] Login 
- [ ] Logout
- [ ] Registration(with safe passwords)
- [ ] Email Verification
- [ ] Credential Management(change password, forgot password, etc)

### Part of
- #5809
- #6436
Installation - docker -  https://www.ory.sh/docs/kratos/install

**Comment by hangy** [comment]
Deprecated by #1596
