### ISSUE TITLE
Rotate image return wrong HTTP code

### ISSUE THREAD

**Issue by fabricetheytaz** [openfoodfacts/openfoodfacts-server#69]
product_image_rotate.pl return 500 (Internal Server Error) for success and 200 in case of error !

**Comment by stephanegigandet** [comment]
It's strange, it returns 200, but the reverse proxy transforms it to 200:

Product Opener response:

- - [24/Mar/2015:18:07:39 +0100] "GET /cgi/product_image_rotate.pl?code=20080686&imgid=1&angle=9 HTTP/1.1" 200 44946 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36"

Reverse proxy response:

 - - [24/Mar/2015:18:07:39 +0100] "GET /cgi/product_image_rotate.pl?code=20080686&imgid=1&angle=9 HTTP/1.1" 500 44946 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36"

**Comment by fabricetheytaz** [comment]
Maybe a fix for this issue... (not tested with proxy)
```perl
my $r = CGI->new->r;
$r->status(500); # The real status code (Apache2::Const::XXX not allowed in strict mode ???)
$r->rflush(); # Force send headers
$r->status(200); # Tell Apache everything is OK (so it doesnt send custom error page)
```

**Comment by stephanegigandet** [comment]
Thanks, I looked a bit more into it, it seems the right way to return an image through mod_perl is:
```
use Apache2::Const 'OK';
my $r = shift;
$r->content_type( 'image/jpeg' );
$r->print( $image->ImageToBlob(magick=>'jpeg') );
return OK;
```
