### ISSUE TITLE
Releasing the knowledge panels to the public on the web ?

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#6921]
### What
- Releasing the knowledge panels to the public on the web ?
- they are currently behind login, afaik
###
Solved by the #6985

**Comment by alexgarel** [comment]
@teolemon and @stephanegigandet for this an alternative we could consider:

- propose "use knowledge panels" as a user preference to everybody (and maybe add an article to invite to test on the blog)
- had some conditions in the template (or even some css classes) to hide the part that are already covered by knowledge panels.

**Comment by alexgarel** [comment]
I close as it will be push with the new design #7295
