### ISSUE TITLE
Add more actions to panels

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#6987]
### What
- Original PR: https://github.com/openfoodfacts/openfoodfacts-server/pull/6903/files#diff-d6b9a7ba08e9ecb060d8284b1bd62bcd2861eccd7d3f65f479830b915c679761R2447
- Add more actions to panels
  - [x] Start by listing all the actions that are possible in the app
  - [x] Add matching string in the GetText files
  - [x] Packaging (we have native editing) - [templates/api/knowledge-panels/environment/packaging_recycling.tt.json](https://github.com/openfoodfacts/openfoodfacts-server/tree/main/templates/api/knowledge-panels/environment/packaging_recycling.tt.json)
    - [ ] **Where:** in the related the sub-knowledge panel
    - [ ] **Where:** in the matching ecoscore sub-knowledge panel if an eco-score is already computed
    - [ ] **Action:** 
    - [ ] TODO: Add differentiated support for packaging photo and packaging text
  - [ ] Ingredient Photo taking
    - [ ] **When:** in case it's missing
    - [ ] **Where:** as a supplement with the current prompt for opening the editing section
    - [ ] **Where:** potentially directly on the top of the Health panel
    - [ ] **Where:** [templates/api/knowledge-panels/health/health_card.tt.json](https://github.com/openfoodfacts/openfoodfacts-server/blob/main/templates/api/knowledge-panels/health/health_card.tt.json)
    - [ ] **Action:** 
  - [ ] Ingredient extraction
    - [ ] In case they are not extracted but the ingredients photo is already here
    - [ ] **Action:** 
    - [ ] **Where:** [templates/api/knowledge-panels/health/health_card.tt.json](https://github.com/openfoodfacts/openfoodfacts-server/blob/main/templates/api/knowledge-panels/health/health_card.tt.json)
  - [ ] Nutrition Photo taking
    - [ ] **When:** in case it's missing
    - [ ] **Where:** as a supplement with the current prompt for opening the editing section
    - [ ] **Where:** [templates/api/knowledge-panels/health/health_card.tt.json](https://github.com/openfoodfacts/openfoodfacts-server/blob/main/templates/api/knowledge-panels/health/health_card.tt.json)
    - [ ] **Action:** 
  - [ ] Front Photo taking
    - [ ] **When:** in case it's missing
    - [ ] **Where:** as a supplement with the current prompt for opening the editing section
    - [ ] **Action:** 
  - [ ] Traceability codes
    - [ ] **Where:** in lieu of the map
    - [ ] **When:** for specific categories like meat, milk, for European countries
    - [ ] if category in (meat, milk, fish) & cc in (FR,…): action=1
    - [ ] **Action:** 
  - [ ] Labels and certifications 
    - [ ] **When:** 
    - [ ] **Where:** 
    - [ ] **Action:** add_labels
    - [ ] Show only in the case there are none at all on the product in the Eco-Score sub-knowledge panel section about labels if an Eco-Score is already computed
  - [x] Origins of ingredients - [templates/api/knowledge-panels/environment/origins_of_ingredients.tt.json](https://github.com/openfoodfacts/openfoodfacts-server/tree/main/templates/api/knowledge-panels/environment/origins_of_ingredients.tt.json)
    - [ ] **When:** In case there are none
    - [ ] **Where:** in the Eco-Score sub-knowledge panel section about origins (if an eco-score is already computed)
    - [ ] **Action:**  Open 'add_origins'
  - [ ] Nutrition table
    - [ ] **Where:** [templates/api/knowledge-panels/health/health_card.tt.json](https://github.com/openfoodfacts/openfoodfacts-server/blob/main/templates/api/knowledge-panels/health/health_card.tt.json)
    - [ ] **Action:** open nutrition table editing
  - [ ] Portion size
    - [ ] if portion size is missing, 
    - [ ] **When:** 
    - [ ] **Where:** [templates/api/knowledge-panels/health/nutrition/serving_size.tt.json](https://github.com/openfoodfacts/openfoodfacts-server/blob/main/templates/api/knowledge-panels/health/nutrition/serving_size.tt.json)
    - [ ] **Action:** open nutrition table editing

![image](https://user-images.githubusercontent.com/1689815/200181915-703c2fc0-1bc1-4228-841c-37442fad12a2.png)

<img src="https://user-images.githubusercontent.com/1689815/177008480-42394375-c499-4651-b2a0-9a53c8f9c8f4.png" height="400px">

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/177008480-42394375-c499-4651-b2a0-9a53c8f9c8f4.png)

**Comment by teolemon** [comment]
unassigning you @stephanegigandet for the time being

**Comment by M123-dev** [comment]
👍🏼
