### ISSUE TITLE
Extra bracket in Search form

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#699]
![image](https://cloud.githubusercontent.com/assets/1689815/22461618/41b4987e-e7aa-11e6-9eb7-3b1d86900dde.png)

**Comment by hangy** [comment]
Translation key `search_download_results_description`. Tracking an issue for every translation problem might be a bit excessive. :grinning:

**Comment by VaiTon** [comment]
This can be closed @teolemon
