### ISSUE TITLE
Import packaging components data (shape 1, material 1, shape 2, material 2 etc.) from producers

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#7021]
### What

- Some producers send us Excel files that have some data about packaging components, usually with different columns in Excel files.

e.g. from the Eco-Score template:

Format | Matériau | Format | Matériau | Format | Matériau
-- | -- | -- | -- | -- | --

A retailer:

Format_1 | Matériau_1 | Format_2 | Matériau_2
-- | -- | -- | --

A producer

Format | Matériau
-- | --

This data currently cannot be loaded through the producers platform.

### Proposed solution

- The values for shapes and materials are in a specific language (e.g. French), and not necessarily normalized.
- Like we do for other kind of data (e.g. ingredients lists), we can store the values as-is, and then normalize them to populate another field.
- We could store this data in a new structure in the product:

producer_packagings : {
lc : "fr",
shape_1 : "some shape name in French",
material_1 : "some material name in French",
shape_2 : "another shape",
material_2 : "another material",
}

- I'd like to avoid a more complex structure (e.g. list of packaging components, each with a hash for shape and material) and keep this data similar to the input we get (columns).
- Then once we have this structure, it can be parsed, normalized etc. to enrich the packagins structure that we already derive from packaging tags and recycling instructions.

### Part of
- #5521 
- #6374

**Comment by stephanegigandet** [comment]
We need the same feature for ingredients: https://github.com/openfoodfacts/openfoodfacts-server/issues/6931

**Comment by manon-corneille** [comment]
Hi guys, any idea of when this issue will be resolved please? It's preventing org-bonduelle to import their data
