### ISSUE TITLE
Maps not loading - leaflet move to bower

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#703]
Reported by Tacite:

Maps don't work anymore. 

Example : https://fr.openfoodfacts.org/cgi/search.pl?action=process&tagtype_0=stores&tag_contains_0=contains&tag_0=Bio14&sort_by=unique_scans_n&page_size=20&axis_x=energy&axis_y=products_n&generate_map=1

If that may help:

<img width="1280" alt="capture d ecran 2017-02-01 a 10 34 29" src="https://cloud.githubusercontent.com/assets/11161632/22501654/0733f8dc-e86a-11e6-8d7d-49f4e66d6899.png">

**Comment by stephanegigandet** [comment]
I think @hangy moved leaflet to bower, I need to run bower install on the server. First I need to install node, npm and bower. ;)

@hangy: shouldn't bower.json be in the html directory?

**Comment by stephanegigandet** [comment]
mmmh...

apt-get install nodejs
apt-get install npm
npm install -g bower

bower install
/usr/bin/env: node: No such file or directory

**Comment by stephanegigandet** [comment]
ln -s /usr/bin/nodejs /usr/bin/node

From: https://github.com/nodejs/node-v0.x-archive/issues/3911#issuecomment-12798913

"These explain why:

http://lists.debian.org/debian-devel-announce/2012/07/msg00002.html
http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=614907
http://debian.2.n7.nabble.com/Node-js-and-it-s-future-in-debian-td1042211.html (only read this last thread if you're a masochist)

As a Node developer, I would think hard before using Debian's packaged version of node, and would use Ubuntu with chrislea's PPA for Node or Debian stable with Node built from source in preference to the stock Debian nodejs package for the foreseeable future. The discussion on this bug makes clear that Debian has a very different idea of the role of Node in the wider world than most of the Node community."

Installed leaflet from bower, maps work again.

**Comment by hangy** [comment]
Yes, the node.js version on Ubuntu and Debian seems to be quite outdated. I added the official nodesource repository and installed from there. 😄
