### ISSUE TITLE
Wrong URL constructed in the informer facet

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#705]
https://world.openfoodfacts.org/informer/kiliweb/states
Will redirect you to the contributor facet.

**Comment by hangy** [comment]
Same for https://world.openfoodfacts.org/photographers as reported by @TaciteOFF in #755

**Comment by TaciteOFF** [comment]
(also happens when you try to go to page 2 of /photographer/<yournickname> by clicking on "2" at the bottom)

**Comment by hangy** [comment]
My guess is that OFF just tries to build a "user" link as informer/photographer/… are somewhat like aliases to the contributor tagtype.

**Comment by hangy** [comment]
Redirect does not happen any more, and the 2nd level facet link contains `informer`, too. Please reopen if you still see this happening.
