### ISSUE TITLE
Nutrition facts completed state is not computed properly

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#7061]
### Describe the bug

Products that have no nutrition facts have the state "nutrition facts completed".

e.g.

https://th-en.openfoodfacts.org/api/v2/product/8851727003056.json
```

{
fruits-vegetables-nuts-estimate-from-ingredients_100g: 0,
fruits-vegetables-nuts-estimate-from-ingredients_serving: 0,
nova-group: 4,
nova-group_100g: 4,
nova-group_serving: 4
},
```

```
states_tags: [
"en:to-be-completed",
"en:nutrition-facts-completed",
"en:ingredients-completed",
"en:expiration-date-to-be-completed",
"en:packaging-code-to-be-completed",
"en:characteristics-to-be-completed",
"en:origins-to-be-completed",
"en:categories-to-be-completed",
"en:brands-to-be-completed",
"en:packaging-to-be-completed",
"en:quantity-to-be-completed",
"en:product-name-to-be-completed",
"en:photos-to-be-validated",
"en:packaging-photo-to-be-selected",
"en:nutrition-photo-selected",
"en:ingredients-photo-selected",
"en:front-photo-selected",
"en:photos-uploaded"
],
```

### To Reproduce

This is because we look for entries in the "nutriments" structure, and if we have some, we consider the nutrition facts have been completed.

But we now use this structure to store some fields like NOVA and the estimated % of fruits and vegetables from the list of ingredients.

Products.pm:

```
	if (((defined $current_ref->{nutriments}) and (scalar keys %{$current_ref->{nutriments}} > 0))
		or ((defined $product_ref->{no_nutrition_data}) and ($product_ref->{no_nutrition_data} eq 'on')) ) {
		push @states_tags, "en:nutrition-facts-completed";
		$notempty++;
		$completeness += $step;
	}
	else {
		push @states_tags, "en:nutrition-facts-to-be-completed";
		$complete = 0;
	}
```

### Expected behavior

Ignore NOVA and estimated % of fruits and vegetables when determining if the nutrients are completed.

### Type of device

Other

**Comment by captain-sal** [comment]
Can you please assign this issue to me?

**Comment by jnsereko** [comment]
this hasn't been updated for quite some time.  I am sorry if this violates community guidelines.
PR => https://github.com/openfoodfacts/openfoodfacts-server/pull/8271
