### ISSUE TITLE
Translate email template for the producers platform 

### ISSUE THREAD

**Issue by manon-corneille** [openfoodfacts/openfoodfacts-server#7087]
### What

- Communication with producers happen in various languages. The translation of templates would be very helpful to save time when answering producers. 

### Proposed solution

- The template to be translated is [user_new_pro_account_org_request_validated.tt.txt](https://github.com/openfoodfacts/openfoodfacts-server/blob/main/templates/emails/user_new_pro_account_org_request_validated.tt.txt)

- Ideally, I would like to have this template translated in 4 languages : 
  - German 
  - Italian 
  - Spanish 

FYI : It is only existing in French for now. Please find below the translation in English   
----

Subject: You are now connected to the organisation [% user.requested_org %]

Hi,

We have just updated your account to connect it with the organisation [% user.requested_org %]. 

You can access your producer workspace from your account [% user.userid %] on https://world.pro.openfoodfacts.org

From the producer platform, you can easily: 

- **Consult** all your products by clicking on the Open Food Facts logo on the top left of the page
- **Discover** product improvement opportunities by clicking on "→ Number of products with improvement opportunities" at the very top of the page
- **Explore** products according to certain criteria (e.g. Nutriscore) by clicking on "Explore products by" which is located above the product listing
- **Analyse** your data via customised graphs: by clicking on the "graph" icon in the top right-hand corner

We are constantly improving this platform, so don't hesitate to send us your comments or areas for improvement.

Thank you very much for supporting food transparency,

Best,

### Part of
- #5521

**Comment by alexgarel** [comment]
As discussed with @manon-corneille : the mail sent to producers is created using this template, so the task is to make this template translatable, and then let crowdin translations comes in.

**Comment by manon-corneille** [comment]
Also related to https://github.com/openfoodfacts/openfoodfacts-server/issues/5182
