### ISSUE TITLE
Automate the creation of a user sheet in Odoo 

### ISSUE THREAD

**Issue by manon-corneille** [openfoodfacts/openfoodfacts-server#7091]
### Is your feature request related to a problem? Please describe.

.

### Describe the solution you'd like

Linked issue : https://github.com/openfoodfacts/openfoodfacts-server/issues/6978

Two cases : 

1. New user created in Open Food Facts, with a new organisation 
→ Add an URL in the email template to allows the OFF admin to validate or not creation of a contact sheet in Odoo.  

2. New user created in Open Food Facts, with an existing organisation 
→ when the connexion of the user to the org is validated by an Open Food Facts admin, a contact sheet should be created in Odoo

Fields that would be needed : 
- userid
- name
- email
- langage (lc)
- country (cc)
- date of last activity
- organisation (this would suppose that the org sheet in Odoo is also being created)

**Comment by alexgarel** [comment]
> Add an URL in the email template to allows the OFF admin to validate or not creation of a contact sheet in Odoo.
 
 Note that this is a link to the pro platform, triggering the creation of the user sheet in odoo.

**Comment by alexgarel** [comment]
I'll close in favor of https://github.com/openfoodfacts/openfoodfacts-server/issues/7296
