### ISSUE TITLE
Email template - new user for new org : are you really a producer? 

### ISSUE THREAD

**Issue by manon-corneille** [openfoodfacts/openfoodfacts-server#7093]
### What

- I need to have a template to check with a new user if he is really from the organisation that he is requesting. 

### Proposed solution

Add the template below would be awesome : 
```


Hi [% user.name %],

Thank you so much for your interest in Open Food Facts ! :-)

Do you please confirm that you are working for the company [% user.org or user.requested_org %]?

We would be very happy to grant you access to [% user.org or user.requested_org %]’s workspace if you create an account with your professional email address.

Thank you for your understanding, 

Best, 
```
### Part of
- #5521

**Comment by alexgarel** [comment]
This would be a link in the mail "new account … for existing org…" isn't it ?

**Comment by manon-corneille** [comment]
Hi @alexgarel yes you are right, for now, it is need only in the  "new account … for existing org…" mail. Thanks :)

**Comment by manon-corneille** [comment]
Extra point : 

During the meeting we had last friday (Producers process workshop) we also mention that it would be interesting if we could automate this email (Are you a producer?) if the email of the user is generic (@gmail.com, @yahoo.fr, @rakuten.com, etc) .
