### ISSUE TITLE
First bug :), last debrief

### ISSUE THREAD

**Issue by boudeffa** [openfoodfacts/openfoodfacts-server#71]
Thank you very much for inviting me to join Open Food Facts organization on GitHub, i am one of the memebers on it's wiki site for the first day of its creation, untill i don't know when :8ball: , and this make me realy belive in open softwares, and this freedom of developping open softwares, i am in a reflexion on engagement in projects that can satisfy both sides, mine and the project it self, and this open a subject on how one can live in freedom and have vital ressources to continue this kind of work freely, in fact for doing better softwars.

So i use this occasion to speak about two display bugs issues : 
- [x] The first is fixing the display of ADD A PRODUCT at the left of the page
- [ ]  The second is fixing APK one in footer

**Comment by teolemon** [comment]
@boudeffa It seems that both issues are fixed ? Closing ?
