### ISSUE TITLE
Points are not clickable anymore on MadeNearMe

### ISSUE THREAD

**Issue by TaciteOFF** [openfoodfacts/openfoodfacts-server#712]
Tested with Safari 10 and Chromium 58.

I can only move around, zoom in or zoom out but I can't click on any of the factories on the map to see the products.

**Comment by hangy** [comment]
Looks like we should re-do the MadeNearMe page in general. The page currently loads 1.2 MiB (uncompressed 10 MiB) of JSON data about the products and their location as inline JSON. The document loaded event handler takes ~1.4 seconds on Chrome Canary on my desktop. I really don't want to know how it runs on a mobile device. 😉

It would probably be better to aggregate products by their coordinates on the server and also only get those that are in the current viewport (currently it starts on Europe and only contains European geodata, but we do want worldwide geodata eventually). MongoDB does have geospatial indexes that could help with that. The actual product data for popups doesn't need to be loaded until the marker cluster is clicked and the popup is opened, so the popup could just be loaded as via AJAX as well.

**Comment by hangy** [comment]
I kinda started on the basics for this: Queryable GeoJSON added in a5e764a87a723c10c71ff0105c8165a2c6d66ff9.

**Comment by teolemon** [comment]
This has been fixed by @stephanegigandet
