### ISSUE TITLE
The drop-down menu is hiden by the footer  

### ISSUE THREAD

**Issue by manon-corneille** [openfoodfacts/openfoodfacts-server#7123]
### Describe the bug

In the Pro Platform, I can't access the lower items of the drop-down menu "Explore food by"

### To Reproduce

1. Go to https://world.pro.openfoodfacts.org/
2. Select the producer "org-ideel-garden" or any other producer that only has a few products 
3. Click on "Explore products by" 

### Expected behavior

I would expect a cursor to help me scroll through the menu  

### Screenshots

![Uploading Bug PPro liste déroulante.png…]()

### Type of device

Browser

**Comment by alexgarel** [comment]
I believe this would be fixed by #6783
