### ISSUE TITLE
check_perl fails

### ISSUE THREAD

**Issue by dipietroR** [openfoodfacts/openfoodfacts-server#7125]
### Describe the bug

https://github.com/openfoodfacts/openfoodfacts-server/pull/7124 appeared to be failing and the error didn't seem to be related to the PR. 

The error:
```
[Fri Jul 22 18:46:24 2022] login.pl: Variable "$cookie" is not imported at cgi/login.pl line 52.
[Fri Jul 22 18:46:24 2022] login.pl: 	(Did you mean &cookie instead?)
Status: 500
Content-type: text/html

<h1>Software error:</h1>
<pre>Global symbol &quot;$cookie&quot; requires explicit package name (did you forget to declare &quot;my $cookie&quot;?) at cgi/login.pl line 52.
cgi/login.pl had compilation errors.
</pre>
<p>
For help, please send mail to this site's webmaster, giving this error message 
and the time and date of the error.

</p>
[Fri Jul 22 18:46:24 2022] login.pl: Global symbol "$cookie" requires explicit package name (did you forget to declare "my $cookie"?) at cgi/login.pl line 52.
[Fri Jul 22 18:46:24 2022] login.pl: cgi/login.pl had compilation errors.
if [ -f cgi/nutrients.pl ]; then perl -c -CS -Ilib cgi/nutrients.pl; else true; fi
make: *** [Makefile:225: cgi/login.pl] Error 255
```

So I reran the test on the main branch and it still failed.

### To Reproduce

1. Go to the main branch
2. Run `make check_perl`

Or make a PR and it should supposedly fail

### Expected behavior

For `make check_perl` to run successfully, with no errors.

### Type of device

Other

**Comment by stephanegigandet** [comment]
That's probably my refactor https://github.com/openfoodfacts/openfoodfacts-server/pull/7106 that broke it, I will fix it.https://github.com/openfoodfacts/openfoodfacts-server/pull/7106

**Comment by dipietroR** [comment]
check_perl seems to be working now, so this issue is not needed
