### ISSUE TITLE
Change Mongodb port exposure when running test

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-server#7127]
So that we can override it when running integration tests, to be able to run them while having the dev server up.

**Comment by alexgarel** [comment]
@yuktea  was wrong, MongoDB expose port is already a variable, we just have to add it when running test. I will do the PR, it's really easy.
cc: @stephanegigandet

**Comment by yuktea** [comment]
> @yuktea was wrong, MongoDB expose port is already a variable, we just have to add it when running test. I will do the PR, it's really easy. cc: @stephanegigandet

that makes more sense
