### ISSUE TITLE
Redirect for links sent via app share feature are broken

### ISSUE THREAD

**Issue by KommX** [openfoodfacts/openfoodfacts-server#7161]
### Describe the bug

When I share a link from the app, this link will be redirected via HTTP 302 to a broken URL. I file this bug report here, because I think, that the redirect is the bug here and not the URL generated by the mobile app.

### To Reproduce

1. Share a product link from the app. (e.g. https://de-de.openfoodfacts.org/product/4005514040975?app_name=Smoothie+-+OpenFoodFacts&app_version=3.5.1%2B693&app_uuid=d1445660a73e40bd&app_platform=ios%2BVersion+15.6+%28Build+19G71%29&comment).
2. Go to this URL via desktop browser.

### Expected behavior

I expect that I end up on the product page.

### Additional context

The redirect is returning a malformed URL with the tld '.orgproduct'.

```
curl 'https://de-de.openfoodfacts.org/product/4005514040975?app_name=Smoothie+-+OpenFoodFacts&app_version=3.5.1%2B693&app_uuid=d1445660a73e40bd&app_platform=ios%2BVersion+15.6+%28Build+19G71%29&comment'

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://de.openfoodfacts.orgproduct/4005514040975?app_name=Smoothie+-+OpenFoodFacts&amp;app_version=3.5.1%2B693&amp;app_uuid=d1445660a73e40bd&amp;app_platform=ios%2BVersion+15.6+%28Build+19G71%29&amp;comment">here</a>.</p>
<hr>
<address>Apache/2.4.25 (Debian) Server at de-de.openfoodfacts.org Port 80</address>
</body></html>
```

### Type of device

Browser

### Browser version

Firefox 103.0

**Comment by stephanegigandet** [comment]
Fixed, thanks for the report.
