### ISSUE TITLE
Small or large calories

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#720]
Energy info on american products are noted in small calories (kcal). In order to be consistent with what is on the package, these should be large calories (Cal).

https://en.wikipedia.org/wiki/Calorie

**Comment by hangy** [comment]
This basically means that we'd need to have translations for units, because "1 Cal" == "1 kcal", and storing both would be weird. On another note, I just saw that the nutrition tables (in products and categories, not the product edit form) incorrectly show energy as "kj" instead of "kJ".

**Comment by stephanegigandet** [comment]
Interesting point. In practice we could show 3 options in the dropdown "kJ / kcal / Cal", and selecting kcal or Cal would just do the same thing. And by default, in the US, we could display "Cal".

**Comment by aleene** [comment]
Sounds good.

**Comment by CoryADavis** [comment]
The current implementation actually looks good to me! Most people in the US wont know the difference between Calorie and calorie, but they should be able to figure out that "Energy (kcal)" is the field they should use when entering the Calories listed on the label.
