### ISSUE TITLE
Improve the image POST API

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#722]
### What
- I have been experimenting with the current image write api. Several remarks:
  - add username/password as parameters;
  - image load does not replace current image, then front etc has no meaning;
  - allow to upload images in general, not related to front/ingredients/nutrition;

### Part of
- #5523

**Comment by stephanegigandet** [comment]
Regarding the 2nd point, the current intended behavior of product_image_upload.pl is to select the image for front / ingredient / nutrition only if there isn't an existing image selected. It is kind of a default image, it is expected that it will then be cropped by the user using product_image_crop.pl

For the 3rd point, I haven't tried it, but just putting "other" for the imagefield probably works. (or any other name for that matter, but maybe we can standardize on other)

**Comment by stephanegigandet** [comment]
Regarding the password, you can pass user_id and password in the post parameters.

**Comment by aleene** [comment]
So I delete the image first, and then upload/select the image.
I intend to implement a native crop solution.

**Comment by aleene** [comment]
too old
