### ISSUE TITLE
Water should be ignored when computing percent of fruit

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-server#7222]
### What
If we have a product with this composition (in french): "prune, eau", the estimated percentage of fruit is min:50% which affects the nutriscore, for Fruits‚ vegetables‚ nuts and rapeseed‚ walnut and olive oils (estimate from ingredients list analysis) is then 50%.
see: https://world.openfoodfacts.org/product/3760324841617/pruneaux-d-agen-entiers-tres-gros-la-fourche?rev=16

Shouldn't the water be estimated as part of this ? Thus making estimated percentage 100% ?

### To Reproduce

see: https://world.openfoodfacts.org/product/3760324841617/pruneaux-d-agen-entiers-tres-gros-la-fourche?rev=16

### Expected behavior

Fruits‚ vegetables‚ nuts and rapeseed‚ walnut and olive oils (estimate from ingredients list analysis) should be 100%

### Part of
- #5706

**Comment by alexgarel** [comment]
cc @stephanegigandet

**Comment by stephanegigandet** [comment]
Water should not be ignored, the % of fruits is the % of fruits. e.g. a fruit nectar with 25% fruits, sugar 10% and 65% water should have 25% of fruits.

**Comment by stephanegigandet** [comment]
For https://fr.openfoodfacts.org/produit/3760324841600/pruneaux-d-agen-la-fourche , we should add "Prunes d'Ente" in the ingredients taxonomy though.

**Comment by stephanegigandet** [comment]
Closing as the % of fruits is working as specified (not ignoring water).
