### ISSUE TITLE
Add the logo for the Label Bee Friendly 

### ISSUE THREAD

**Issue by manon-corneille** [openfoodfacts/openfoodfacts-server#7231]
The Label [Bee Friendly](https://fr.openfoodfacts.org/label/bee-friendly) is available on Open Food Facts, but the logo is missing. 

You can find the logo below in two different resolutions : 
- ![bee-friendly 90x90](https://user-images.githubusercontent.com/104015489/185884742-b8def68c-f30e-49ff-8bed-b9bdd4f58b3f.png)
- ![bee-friendly 1772x1772](https://user-images.githubusercontent.com/104015489/185884744-54e1c06b-be46-41b0-913c-2de4c54e8b48.png)
 
Thank you :)

**Comment by alexgarel** [comment]
if needed to do ourselves the reduction https://www.certifiedbeefriendly.org/wp-content/uploads/2022/01/cropped-cropped-BEEFRIENDLY_logoHD_RVB_020318-300x300.png is a better starting point.

**Comment by pratyaksh1610** [comment]
@alexgarel I have added the above URL image in path - https://github.com/openfoodfacts/openfoodfacts-server/tree/main/html/images/lang/fr/labels . Is it preferred , then I can drop a PR for the same.

**Comment by alexgarel** [comment]
good idea @pratyaksh1610, I can't see your PR though.

**Comment by pratyaksh1610** [comment]
@alexgarel I was asking , is it the correct path ?

**Comment by alexgarel** [comment]
Sorry @pratyaksh1610 for the latency, yes you are correct on the path.

**Comment by pratyaksh1610** [comment]
@alexgarel Okay, cool 👍

**Comment by manon-corneille** [comment]
Hi guys, 
Bee Friendly got back to me with the SVG logo (not sure if it's still relevant, but here it is) :) 

[BEE FRIENDLY logo png_adobe_express](https://user-images.githubusercontent.com/104015489/190621811-37caa057-b0ae-4b86-9ae8-46d09fc10598.svg)

**Comment by alexgarel** [comment]
@pratyaksh1610 do you want to do it ?

**Comment by pratyaksh1610** [comment]
@alexgarel Oh, I missed track of this.
Dropping a PR for the same.

**Comment by alexgarel** [comment]
@pratyaksh1610 I think for this to work, we also have to taxonomize this entry, that is, add it to labels.txt in english and french, at least.

**Comment by alexgarel** [comment]
Note: the code displaying this, I think is in [Display.pm, display_list_of_tags](https://github.com/openfoodfacts/openfoodfacts-server/blob/978fe5de246708a035a82bccd8c1f0d41c97332a/lib/ProductOpener/Display.pm#L2256)
