### ISSUE TITLE
List of ingredients to add

### ISSUE THREAD

**Issue by manon-corneille** [openfoodfacts/openfoodfacts-server#7242]
The ingredients below are relevant but not recognized by our system yet:

- "haricots beurre très fins"
- [en:chocolate-pieces](https://fr.openfoodfacts.org/ingredient/en:chocolate-pieces) (1429 products)
- [piment-doux](https://fr.openfoodfacts.org/ingredient/piment-doux) (463 products)

More examples here: https://fr.openfoodfacts.org/ingredients

**Comment by aleene** [comment]
what is the issue with chocolate pieces? It is already listed as synonym.
