### ISSUE TITLE
Edit the computation of NOVA for 100% natural products  

### ISSUE THREAD

**Issue by manon-corneille** [openfoodfacts/openfoodfacts-server#7254]
### Problem description

A producer is questioning the NOVA classification of his products :
[This product](https://fr.openfoodfacts.org/produit/5060088705926/lemon-drizzle-bar-nakd) is 100% made from natural ingredients and assembled via a “pressing” process.

The category "Snacks" causes the fact that the product is classified in NOVA 3. 

### Desired solution

As there is no sugar or salt added, this product could be classified at NOVA 1 but code changes are required. 

→ Issue discussed with @stephanegigandet on Slack #nova on the 23/08 

### Part of
- #5519

**Comment by teolemon** [comment]
A hint of natural flavorings

**Comment by manon-corneille** [comment]
Thanks @teolemon I close the issue then. :)

**Comment by manon-corneille** [comment]
Hi, 

I'm reopening this issue because we have 2 other example where the product is classified as NOVA 3 only because its category is "Snacks" whereas it's made of 100% natural ingredients, and doesn't contain any hint of natural flavouring or natural aroma :  
 - https://fr.pro.openfoodfacts.org/produit/5060088705124/nakd-noix-de-pecan-140g-4x1p
- https://fr.pro.openfoodfacts.org/produit/5060088705063/nakd-noix-de-cajou-140g-4x1p

Could you do something for these specific cases please? :)

**Comment by alexgarel** [comment]
We can't see the product @manon-corneille if you don't give the org

**Comment by manon-corneille** [comment]
Oups, just seeing your comment now @alexgarel 
→ org-lotus-bakeries :-)

**Comment by benbenben2** [comment]
For first product, if we remove category "snack sucré" nova grade switches to 1. A hint of flavouring, was not in ingredients list, I added it but it is unknown ingredient. Flavouring alone would make nova grade 4....

**Comment by fabi003** [comment]
[This](https://world.openfoodfacts.org/product/8714100799123/gemusesuppe-knorr) product should be NOVA 1 instead of NOVA 4 due to its "100% natural ingredients". ;-) Hopefully nobody asks about ingredients such as the carrot concentrate...

Welcome to the reality of food industry!

**Comment by stephanegigandet** [comment]
No categories now trigger group 4, although a few trigger group 3.

	"categories/en:sodas" => 3,
	"categories/en:ice-creams" => 3,
	"categories/en:chocolates" => 3,
	"categories/en:candies" => 3,
	"categories/en:sugary-snacks" => 3,
	"categories/en:salty-snacks" => 3,
	"categories/en:baby-milks" => 3,
	"categories/en:sausages" => 3,
	"categories/en:hard-liquors" => 3,

Closing this bug.
