### ISSUE TITLE
Barcode not displayed for products with fake barcodes attributed by OFF, breaks Folksonomy Engine

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#7267]
### What

- The paragraph "Barcode: xxxxxxxxxxxx" is not displayed on this product: https://world.openfoodfacts.org/product/2000000009452/pate-d-olives-noires-prior
- The following test seems to fail:
- https://github.com/openfoodfacts/openfoodfacts-server/blob/main/templates/web/pages/product/product_page.tt.html#L57
- It makes Folksonomy Engine failing.

### To Reproduce

- Just open: https://world.openfoodfacts.org/product/2000000009452/pate-d-olives-noires-prior

### Part of
- Folksonomy Engine

**Comment by stephanegigandet** [comment]
The product does not have a real barcode, so we don't display it. We could have a hidden <span id="barcode">.

**Comment by teolemon** [comment]
The solution is either:
- to handle Folksonomy Engine server side
- to change the way the FE JS scripts gets the barcode (hidden in the DOM, or from the URL ?)

**Comment by alexgarel** [comment]
The way to go IMO is to always have barcode but with display none (and no schema if it's fake)

**Comment by teolemon** [comment]
I have added the number of impacted products to the GH project: https://world.openfoodfacts.org/code/2xxxxxxxxxxxx
