### ISSUE TITLE
Replace all instances of param() by scalar param()

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#7270]
### Describe the bug

The param() function in CGI.pm has a weird behaviour : when called in list context, it returns an array of values. But that means that if no value is provided for the parameter, it returns an empty array. That causes problems when param("something") is passed itself as a parameter for a function.

See https://metacpan.org/pod/CGI#Fetching-the-value-or-values-of-a-single-named-parameter

This caused issues in this PR: https://github.com/openfoodfacts/openfoodfacts-server/pull/7212

### To Reproduce

And we currently have a bug for image upload because of this:

my $previous_code = normalize_code(param('previous_code'));

If "previous_code" is not passed, this is like calling normalize_code() with an empty array, which makes the prototype of normalize_code() fail : it expects 1 and only 1 parameter.

### Expected behavior

Replace all instances of param("something") by scalar param("something").

### Type of device

Browser

**Comment by stephanegigandet** [comment]
We have a lot of instances of code like:  decode utf8=>param("something")
for reading text parameters. The decode utf8=> will also force the scalar context.

**Comment by Ban3** [comment]
Would writing our own wrapper for `scalar param($s)` make sense? CGI already provides `multi_param` for always getting a list. Something like:

```perl
sub single_param($s) {
    scalar param($s)
}
```
Then you wouldn't need to remember the `scalar` every time and the intention would be clear.

**Comment by stephanegigandet** [comment]
@Ban3 that's a good idea, I will do that.

**Comment by alexgarel** [comment]
fixed by pr.
