### ISSUE TITLE
What is this file about ?

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#7277]
Story: https://github.com/openfoodfacts/openfoodfacts-server/blob/removing-old-logo-flavors/po/openfoodfacts/openfoodfacts

**Comment by alexgarel** [comment]
@teolemon can we close this ?

**Comment by hangy** [comment]
Looks like some kind of symlink, and is still in `main`: https://github.com/openfoodfacts/openfoodfacts-server/blob/d671883225c3df85612764c72ab47e7322699df1/po/openfoodfacts/openfoodfacts I honestly don't remember, what this was good for, or if it was a mistake, sorry.
