### ISSUE TITLE
Imag Post return code -4

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#729]
I get this when posting an image "The picture is too small. Please do not upload pictures found on the Internet and only send photos you have taken yourself.".

I do not understand this error, as the image is certainly not to small. Can this be something else.

Is there a list of possible return cordes/errors?

**Comment by hangy** [comment]
This is -4: https://github.com/openfoodfacts/openfoodfacts-server/blob/9a43d1378b1c0e8f942fc4353fc63ccb91b45918/lib/ProductOpener/Images.pm#L517-L521
The known codes seem to be listed at: https://github.com/openfoodfacts/openfoodfacts-server/blob/086ed6fb5a47e0bed499d5d9b98ca3eaa320ea7a/cgi/product_image_upload.pl#L115-L118

**Comment by TaciteOFF** [comment]
Is the image bigger than 640x160 ?

**Comment by aleene** [comment]
Yes

**Comment by hangy** [comment]
If the problem persists, could you upload it somewhere else and share it here? That could allow us to debug problem with some additional log statements (without experimenting on production 😉).
