### ISSUE TITLE
All vegetal milks are part of the dairy products (in fr)

### ISSUE THREAD

**Issue by astrubel** [openfoodfacts/openfoodfacts-server#73]
Les laits vagétaux font partie des Laits ainsi que des Produits laitiers. Faut-il également garder l'inclusion à la catégorie Lait ?

**Comment by hangy** [comment]
This should only be an issue for older products. The taxonomy has been fixed now, and works correctly on OFF.NET. I’ll look into adding a [quality](https://world.openfoodfacts.org/quality) facet for that.
