### ISSUE TITLE
Translate barcode not found

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#730]
I noticed that when the barcode is not recognizable, it gives an error in french.

It seems the message is not part of the translation files.

**Comment by stephanegigandet** [comment]
I can't reproduce this, there is a message in the .po file:

msgctxt "image_upload_error_no_barcode_found_in_image_short"
msgid "No barcode found in the image."
msgstr "Aucun code-barre trouvé dans l'image."

Can you give me steps to reproduce and the message you see? Thank you!

**Comment by aleene** [comment]
![img_7131](https://cloud.githubusercontent.com/assets/1329905/23100681/68b87bc0-f687-11e6-920e-38e5f0f87efd.PNG)

To reproduce, use world.openfoodfacts.org, and scan a picture without a barcode.

**Comment by hangy** [comment]
This is translated nowadays.
