### ISSUE TITLE
Search with right single quotation mark ’ instead of apostrophe ' returns 0 result

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#7301]
### Describe the bug

See https://github.com/openfoodfacts/smooth-app/issues/2921

We index words without apostrophes / right quotation marks (in lib/ProductOpener/Products.pm index_product() )
but we keep the right quotation marks when searching (in cgi/search.pl)

Solution: remove right quotation marks also when searching.

### To Reproduce

search for "boisson à l’amande" : https://world.openfoodfacts.org/cgi/search.pl?search_terms=boisson+%C3%A0+l%E2%80%99amande&search_simple=1&action=process -> only 1 result

search for "boisson à l'amande" : https://world.openfoodfacts.org/cgi/search.pl?search_terms=boisson+%C3%A0+l%27amande&search_simple=1&action=process -> 1669 results

### Expected behavior

Same number of results.

### Type of device

Browser

**Comment by kaneki-dot** [comment]
@stephanegigandet I want to contribute to this project, how can I start with this  Issue  I am new to open source.
I am currently learning Android, C++, Python, and Kotlin.

**Comment by stephanegigandet** [comment]
Hi @kaneki-dot, welcome! The Open Food Facts backend is coded in Perl. This issue has been fixed already.
