### ISSUE TITLE
taxonomy: category: add collard greens

### ISSUE THREAD

**Issue by jayaddison** [openfoodfacts/openfoodfacts-server#7315]
As described at: https://en.wikipedia.org/wiki/Collard_(plant)

(note: should this be an `ingredient` or a `category`?  I think a `category`, but could be mistaken)

**Comment by aleene** [comment]
I wondered why you are adding this. Is there a product, which corresponds to this? 

By the way it is both an ingredient and a category. We have no way yet link the two.

**Comment by alexgarel** [comment]
@jayaddison do you feel like doing it yourself ? (as you will need more additions, it can be better to be able to do pull requests by yourself).

See https://wiki.openfoodfacts.org/Global_taxonomies for some help.

**Comment by aleene** [comment]
Great. I have been integrating ingredients with wikidat, and found that the wikidata info is often of bad quality. So I copied OFf-data to wikidata. Sometimes the creation of ingredient on wikidata is required. Doublechecking with wiktionary can be useful as well.

**Comment by jayaddison** [comment]
> @jayaddison do you feel like doing it yourself ? (as you will need more additions, it can be better to be able to do pull requests by yourself).

@alexgarel yep, I'll try to complete this task :+1:

(I have #7311 as a work-in-progress for small wikidata edits -- I have gotten to the letter "C" in the English alphabet, so there's quite a lot more to do.  After completing that, I'll return to these tasks.  I won't create more issues because there are already 5, and I don't want to create (more?) ticket spam)

Also, thanks for the wiki link - after following that through to https://wiki.openfoodfacts.org/Project:Ingredients_ontology#Categories_Taxonomy, I think I understand more about categories vs ingredients.

To try to explain in my own words: a product is an item that can be found for-sale with an associated barcode; a product contains one or more ingredients (things that in many cases are listed on a product's label), and a product belongs to a category (where a category is perhaps how consumers are likely to think about a purchase - and it may have the same/similar name as an ingredient).

From editing experience so far, some of the recipe ingredients in RecipeRadar are mapped (via WikiData) to an OFF `ingredient` -- and some refer to an OFF `category`.  Some have references to both.

> Great. I have been integrating ingredients with wikidat, and found that the wikidata info is often of bad quality. So I copied OFf-data to wikidata. Sometimes the creation of ingredient on wikidata is required. Doublechecking with wiktionary can be useful as well.

Working with WikiData seems difficult but worthwhile, yep (in an "eventual consistency" kind of way).  The manual review and editing process is slow (especially when resolving data issues across the datasets), but I find it strangely enjoyable.  Do you use any tools to help with the lookups?

I'm planning to publish the RecipeRadar ingredient set on GitHub (perhaps CC0, perhaps ODbL) after adding the WikiData IDs.  Generally I think the datasets will have similar purposes: the OpenFoodFacts dataset is organized around identifying ingredient names on product labels, and the RecipeRadar dataset is organized around identifying ingredient names within "recipe ingredient lines" ("four large potatoes", etc).

As mentioned in the pull request I'll hope to say hello on Slack soon.

**Comment by aleene** [comment]
I think you grasped the difference between ingredients and categories very well. Ping me on Slack and we can discuss further in #taxonomies.

**Comment by jayaddison** [comment]
> I'm planning to publish the RecipeRadar ingredient set on GitHub (perhaps CC0, perhaps ODbL) after adding the WikiData IDs. Generally I think the datasets will have similar purposes: the OpenFoodFacts dataset is organized around identifying ingredient names on product labels, and the RecipeRadar dataset is organized around identifying ingredient names within "recipe ingredient lines" ("four large potatoes", etc).

Since I mentioned it previously, and on the unlikely chance that anyone is still subscribed to this issue thread: backups of the RecipeRadar database (with the exclusion of event-log data for safety, even though that also contains no personally-identifiable-information) [are now published](https://backups.reciperadar.com) under the Open Database License (ODbL).

This includes a dataset of ~2,400 ingredients, many of which are mapped to WikiData IDs - and where found, those were mapped/updated to match OpenFoodFacts ingredient IDs, in pull requests like this one.

**Comment by jayaddison** [comment]
Although again I'm not sure whether anyone continues to follow this thread, I thought I should admit to a couple of mistakes regarding the previously-mentioned backups, for transparency.

Firstly, between the dates 2023-08-28 and 2023-10-16 (last week), the database backups inadvertently contained the text of recipe instructions -- and that's not content that RecipeRadar needs or that it serves to users.  It was stored for legacy reasons and has been filtered out since 2023-10-16.

Secondly, although there is no personally identifiable data in the event tables, and none of the data from those tables in the backup, there was one other table that held some publicly-sourced contact information for recipe websites, and the status of RecipeRadar's contact with them.  That data has now also been removed as of today, 2023-10-23.

If you had downloaded one of those backups, loaded it into a database system, or know someone who may have done, I'd kindly ask if you could please delete that data and/or pass on a request to do that.  Thank you.

**Comment by aleene** [comment]
I wonder whether we need to document your work somewhere. If useful the wiki could be used for this.

**Comment by jayaddison** [comment]
That sounds good.  The process I followed was _approximately_ to work through each of the 2400-or-so ingredients in RecipeRadar (many of them are, like OpenFoodFacts, arranged in hierarchies), and then to pick each distinct ingredient, and check whether it is in WikiData and OpenFoodFacts, and to resolve/interlink them when present.

However, it could be good to write that process in some more detail (with a few of the edge cases to consider) and document it.  Somewhere like the link below perhaps on the wiki?

https://wiki.openfoodfacts.org/Structured_Data/Wikidata#Ingredients

**Comment by jayaddison** [comment]
(oh, and to make clear: I'm volunteering to do that!)

**Comment by aleene** [comment]
Or call the page `Recipe radar synchronisation`. Add also 
```
[[Category:Ingredients]]
```
at the bottom.

**Comment by jayaddison** [comment]
@aleene I've begun writing this up here: https://wiki.openfoodfacts.org/Ingredient_datasource_synchronization (more generally than for RecipeRadar).  Mostly it's context so far - I'll add some suggested process documentation next (likely tomorrow or Thursday).
