### ISSUE TITLE
taxonomy: ingredients: add Muenster cheese

### ISSUE THREAD

**Issue by jayaddison** [openfoodfacts/openfoodfacts-server#7316]
As described at https://en.wikipedia.org/wiki/Muenster_cheese

:warning: Note that this is _not_ the same as Munster cheese! (which already exists within the `ingredient` taxonomy)

Muenster cheese is from the U.S. and _named after_ a town in the Alsace region; [Munster cheese](https://en.wikipedia.org/wiki/Munster_cheese) is a separate product _made in the vicinity of_ the Alsace region.

**Comment by aakankshabhende** [comment]
@yuktea @alexgarel Can I work on this issue?

**Comment by alexgarel** [comment]
@aakankshabhende, please do :-) Feel free to work on issues, a comment stipulating you work on this is enough.
