### ISSUE TITLE
NEW DESIGN: Product page navigation tabs don't work

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#7336]
In the new design, the product page has different sections like "Product", "Match", "Health", "Ingredients", "Nutrition", "Environment" etc. There are some navigation tabs at the top that should lead to those sections, and show which section is active.

In the current version of the redesign2 branch, only the first 2 tabs "Product" and "Match" work. Clicking on the other links leads to roughly the top of the page, and while scrolling, multiple tabs can become active.

![image](https://user-images.githubusercontent.com/8158668/189942886-41e52806-8fc5-4151-8ad2-9fa51798b83e.png)

The corresponding code is:

https://github.com/openfoodfacts/openfoodfacts-server/blob/redesign2/templates/web/pages/product/product_page.tt.html
https://github.com/openfoodfacts/openfoodfacts-server/blob/redesign2/html/js/scrollNav.js

**Comment by stephanegigandet** [comment]
This page is currently live on the dev environment: https://world.openfoodfacts.dev/product/3336970409060/la-legere-vico  (login and password: off )

**Comment by stephanegigandet** [comment]
So, to make tabs work, the links need to go to sections blocks, and all blocks need to be under the same parent element. So we can't link to deeply nested knowledge panels like ingredients and nutrition.

I kept only one level, it's simpler. Fixed by https://github.com/openfoodfacts/openfoodfacts-server/issues/7336

**Comment by alexgarel** [comment]
:clap:
