### ISSUE TITLE
NEW DESIGN: on login page there is no link to the registration form.

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#7349]
### What
- NEW DESIGN: on login page there is no link to the registration form.

### Part of
- #7295 

![image](https://user-images.githubusercontent.com/8158668/190631295-8be13101-0dab-4e06-bb73-6e9c15805314.png)

We need to add links to create an account, and to reset the password, as we have in production today:

![image](https://user-images.githubusercontent.com/8158668/190631502-5a1e0659-d133-412b-aadb-597c8f0b82cd.png)

**Comment by Edrees-creator** [comment]
can I contribute to this project?

**Comment by alexgarel** [comment]
@Edrees-creator please do :-) Every help is really welcome.

**Comment by stephanegigandet** [comment]
Fixed by @LandonPattison
