### ISSUE TITLE
Sync data in CRM on org and user updates

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-server#7356]
With #7351 and #7352, we creates users and orgs in the CRM.

But we need to keep data up to date in the CRM. Also we want to have in the CRM some data from the pro platform that can help target right producers, follow their journey and eventually create emails workflows.

For org we would like to track:
- date of last export to public plateform
- typology of last import (manual / csv)  (postpone if not easy) / use a tag import_from_csv/manual
- number of products exported and in progress
- pim it's imported via (use tags, like import_from_xxxx)

For a user we would like to track:
- date of last connexion

PS: remember to always prefix specific fields in the CRM with `off_`

**Comment by teolemon** [comment]
- the goal is to do https://github.com/openfoodfacts/openfoodfacts-server/issues/5012. Do we do it Product Opener side with Brevo, or Odoo side ?
