### ISSUE TITLE
Show the Eco-Score on world.off.org on non-logged in users

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#7378]
### Problem description

Most of our traffic comes from world.off.org where we don't show the Eco-Score because we don't know the core country
This is a massive lost opportunity to educate about Eco-Score and show the value of Open Food Facts

### Desired solution

Show the Eco-Score on world.off.org on non-logged in users, possibly with a warning or a country refiner

### Number of products impacted

100%

### Mockups
![image](https://user-images.githubusercontent.com/1689815/194266014-409435ba-378c-4a00-8a95-7e04d3c942b6.png)

- https://www.figma.com/file/iyFnUGkJTizApXGnQCdh5I/Eco-Score-on-world.off.org?node-id=3%3A11

**Comment by john-gom** [comment]
First pass is available in branch [issue/7378](https://github.com/openfoodfacts/openfoodfacts-server/tree/issue/7378)

Currently enabling in all regions with a warning in the Knowledge Panel where full information is not available. Looks like this on the web site:

![image](https://user-images.githubusercontent.com/116556069/208481683-06d4dbd5-be24-433b-a470-0b7e898c8156.png)

On mobile:

![image](https://user-images.githubusercontent.com/116556069/208481754-aa9c47cf-7d5e-4c80-96a1-30c49b41afc8.png)

**Comment by john-gom** [comment]
Have also updated the attribute panel to show a short warning (using the existing "missing" property):

![image](https://user-images.githubusercontent.com/116556069/209931844-44e22aef-8746-4e05-8492-ada6900e8c64.png)

This isn't implemented on mobile.

**Comment by john-gom** [comment]
> Have also updated the attribute panel to show a short warning (using the existing "missing" property):
> 
> ![image](https://user-images.githubusercontent.com/116556069/209931844-44e22aef-8746-4e05-8492-ada6900e8c64.png)
> 
> This isn't implemented on mobile.

This has now been reverted following PR feedback. The only warning will be on the main knowledge panel. The warning text has also been simplified to either:

      Select a country in order to include the full impact of transportation.
or   The full impact of transportation to your country is currently unknown.
