### ISSUE TITLE
Several Images are HTML Files

### ISSUE THREAD

**Issue by AaronAsAChimp** [openfoodfacts/openfoodfacts-server#738]
**Current Behavior:** A broken image icon is displayed because they are not valid images. They are actually HTML files that were saved from the wiki (which is down right now). 

**Expected Behavior:** The following images should be displayed on their label pages and on products pages that have this label.

- html/images/lang/en/labels/biogarantie.90x90.png
  Label Page: https://world.openfoodfacts.org/label/fr:biogarantie
- html/images/lang/en/labels/certified-belgian-abbey-beer.66x90.png
  Label Page: https://world.openfoodfacts.org/label/certified-belgian-abbey-beer
- html/images/lang/en/labels/natrue.90x90.png
  Label Page: https://world.openbeautyfacts.org/label/natrue
- html/images/lang/en/labels/nordic-ecolabel.84x90.png
  Label Page: https://world.openbeautyfacts.org/label/nordic-ecolabel
- html/images/lang/fr/labels/cosmetique-eco-charte-cosmebio.107x90.png
  Label Page: https://fr.openbeautyfacts.org/label/cosmetique-eco-charte-cosmebio
- html/images/lang/en/labels/real-california-milk-90x90.png
  Is this used? real-california-milk.90x90.png is the one thats used on the label page

**Comment by stephanegigandet** [comment]
Thanks for the report, it's fixed. And the wiki is now back online.
