### ISSUE TITLE
NEW DESIGN: Move donation banner close button to top right

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#7412]
### What
- The donation banner should have a close button at the top right, instead of the current message.

### Part of
- #7295 

### Current
![image](https://user-images.githubusercontent.com/8158668/192773022-71c4adba-4850-424e-b67c-f7113befd95c.png)

### Mockup
![image](https://user-images.githubusercontent.com/8158668/192772843-c09dca75-15a2-4562-a812-3801ac327c24.png)

**Comment by yashfalke77** [comment]
hey @stephanegigandet can i work on this issue?

**Comment by stephanegigandet** [comment]
> hey @stephanegigandet can i work on this issue?

Hi @yashfalke77 , sure!

**Comment by stephanegigandet** [comment]
@yashfalke77 This bug is on the new "redesign2" branch, there is more details on how to deploy / test etc. in this meta bug: https://github.com/openfoodfacts/openfoodfacts-server/issues/7295

**Comment by Nainish-Rai** [comment]
hey, I want to contribute, Please assign me so that I can start working on it.
