### ISSUE TITLE
NEW DESIGN: header is hiding target of fragment

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-server#7415]
On the product Edit page, we have a link to explain why users should take infos from the package. It leads to 
https://world.openfoodfacts.dev/faq#pictures_and_data_from_other_sites

But as you click it, you don't see the question, because it is hidden by the header (floating).

I think it's something we can fix.

more annoying it also affects actions in panels like "add a category", which links to https://world.openfoodfacts.dev/cgi/product.pl?type=edit&code=3336995409151#categories

**Comment by alexgarel** [comment]
There is a JS for that, it works if I reload the page but not on first opening… :-/

**Comment by alexgarel** [comment]
The js is in scrollNav.js

[Relevant code](https://github.com/openfoodfacts/openfoodfacts-server/blob/redesign2/html/js/scrollNav.js#L131): 
```javascript
    window.addEventListener('load', () => {
        if (window.location.hash) {
            if (select(window.location.hash)) {
                scrollto(window.location.hash)
            }
        }
    });
```

Of course if you use debugger, it's working fine :-D so this is a race condition. Maybe just adding a small delay (triggering the scrollto using a timer) might fix it…

**Comment by stephanegigandet** [comment]
I can replicate it in Firefox, but not Chrome.

![image](https://user-images.githubusercontent.com/8158668/193068236-c52d8779-bdc2-4492-842a-61f981fe99f1.png)

**Comment by alexgarel** [comment]
It works now, thanks to the timeout.
