### ISSUE TITLE
http:// versions of the Wiki show up the Apache error page

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#742]
http:// versions of the Wiki show up the Apache error page
It should redirect to the https version instead

**Comment by stephanegigandet** [comment]
Fixed.

There were 2 issues:

1. apache2.conf was loading sites-enabled/*.conf but the http conf files where not suffixed by .conf and thus not loaded.

2. the redirect to https was placed after another redirect that took precedence
