### ISSUE TITLE
Emails sent by the OFF production server are rejected by Google Mail, and possibly rejected or marked as spam by other email providers

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#743]
Found in /var/log/exim4/mainlog :

2017-02-16 14:21:05 1ceLzc-0000fO-VW ** contact@xxxx.com R=dnslookup T=remote_smtp X=TLS1.2:ECDHE_RSA_AES_128_GCM_SHA256:128 DN="C=US,ST=California,L=Mountain View,O=Google Inc,CN=mx.google.com":

 SMTP error from remote mail server after end of data: host ASPMX.L.GOOGLE.COM 

Our system has detected that this message does not meet IPv6 sending guidelines regarding PTR records and authentication. Please review https://support.google.com/mail/?p=IPv6AuthError for more information

**Comment by stephanegigandet** [comment]
mail-tester.com score: 2/10

sendmail -t
From:contact@openfoodfacts.org
To:web-zoed0@mail-tester.com
Subject: test blabla

blablabla


Vous n'êtes pas autorisé à utiliser l'une de vos adresses e-mail d'envois
Nous vérifions que votre serveur d'envoi est authentifié
-1
[SPF] ns3362784.ip-37-187-74.eu n'autorise pas votre serveur 37.187.74.28 à utiliser root@ns3362784.ip-37-187-74.eu
-3
[Sender ID] openfoodfacts.org n'autorise pas votre serveur 37.187.74.28 à utiliser contact@openfoodfacts.org
-1
Votre message n'est pas signé avec DKIM
Vous n'avez pas d'enregistrement DMARC
Votre serveur 37.187.74.28 est correctement associé avec ns3362784.ip-37-187-74.eu
-3
Nous n'avons pas trouvé de serveur mail (MX Record) derrière votre nom de domaine ns3362784.ip-37-187-74.eu.
Votre nom d'hôte ns3362784.ip-37-187-74.eu est rattaché à un serveur.

**Comment by stephanegigandet** [comment]
Disabling ipv6:

more exim4.conf.localmacros

DCdisable_ipv6 = true
DC_DISABLE_IPV6 = true
disable_ipv6 = true

root@ns3362784:/etc/exim4# update-exim4.conf
root@ns3362784:/etc/exim4# service exim4 restart

Result: mail received :-)

2017-02-17 00:22:45 1ceVNh-0000NJ-Bg <= root@ns3362784.ip-37-187-74.eu U=root P=local S=394
2017-02-17 00:22:46 1ceVNh-0000NJ-Bg => stephanegigandet@gmail.com R=dnslookup T=remote_smtp H=gmail-smtp-in.l.google.com [66.102.1.27] X=TLS1.2:ECDHE_RSA_AES_128_GCM_SHA256:128 DN="C=US,ST=California,L=Mountain View,O=Google Inc,CN=mx.google.com" C="250 2.0.0 OK 1487287117 k27si10472936wrd.232 - gsmtp"
2017-02-17 00:22:46 1ceVNh-0000NJ-Bg Completed

**Comment by stephanegigandet** [comment]
added OFF's server ip to spf record for openfoodfacts.org:

openfoodfacts.org.	600	SPF	"v=spf1 a mx ip4:37.187.74.28 include:mx.ovh.com ~all"
