### ISSUE TITLE
Logic error in the Producer section of user profile

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#7433]
### What
- Logic error in the Producer section of user profile
- Will warn of an error with Cacolac
### Steps to reproduce:
- as an admin, try to convert an account to producer. 
https://world.openfoodfacts.org/cgi/user.pl?userid=XXXX&type=edit&action=display (specific user available on request)
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/1689815/193536345-9a5612d9-7941-43a0-b0a2-a6a3672af18e.png">

**Comment by alexgarel** [comment]
The warning is correct, it's to tell the user it needs approval from the team. (But maybe your bug is about the value being removed ?)

**Comment by teolemon** [comment]
It's that I was on the public platform, as an admin, on a user unrelated to Cacolac I believe

**Comment by alexgarel** [comment]
Shall it be closed then, or is there a real bug ?

**Comment by manon-corneille** [comment]
Seems to be fixed
