### ISSUE TITLE
NEW DESIGN: Your contributions links in user menus are not set

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#7434]
### What
- These links have no `href=""` attribute so they redirect to main page (From @VaiTon)

### Screenshots
![image](https://user-images.githubusercontent.com/8158668/193537389-356c9f6b-0a16-4f3a-bb4d-361bd0a9d975.png)
![image](https://user-images.githubusercontent.com/8158668/193537406-9f25d7f3-9e32-4f28-87a4-0b0f200e41de.png)
### Part of
- #7295

**Comment by Anurag-Singh-04** [comment]
Hey @stephanegigandet how can I contribute to this project.

**Comment by stephanegigandet** [comment]
Fixed.
