### ISSUE TITLE
Adding a language for image or ingredients does not make appear a tab.

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#7483]
### What
- Adding a language for image or ingredients does not make appear a tab.

### Possibly related
- #7477 

### Screenshot
<img width="426" alt="Screenshot 2022-10-11 at 15 06 43" src="https://user-images.githubusercontent.com/1329905/195099121-30af235e-5003-4122-a134-0baece5ab8a7.png">

_Originally posted by @aleene in https://github.com/openfoodfacts/openfoodfacts-server/issues/7295#issuecomment-1274660871_

**Comment by stephanegigandet** [comment]
Same as #7477, Fixed by https://github.com/openfoodfacts/openfoodfacts-server/pull/7479
