### ISSUE TITLE
images not saved by ios cordova app

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#749]
reported by bcatelin

ios reports "image received, thank you!" but the image is not saved

The app query for that product has a strange world-en-gb subdomain, not sure if that's related:

hostname: world-en-gb.openfoodfacts.orgquery_string: api/v0.1/product/00944908.jqm.json subdomain: world-en-gb - lc: en  - cc: world - country: en:world - 2

**Comment by hangy** [comment]
Probably related. I guess the domain ist redirected to world.off.org and thus the POST data ist gone. The App should bei fixed to use the correct subdomain and check the status code.

**Comment by stephanegigandet** [comment]
corresponding log entries in nginx log:

- - [25/Feb/2017:18:25:37 +0100] "GET /api/v0.1/product/8412075603710.jqm.json HTTP/1.1" 200 760 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/602.4.6 (KHTML, like Gecko) Mobile/14D27 (5165328192)"
 - - [25/Feb/2017:18:26:23 +0100] "POST /cgi/product_jqm.pl HTTP/1.1" 200 70 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/602.4.6 (KHTML, like Gecko) Mobile/14D27 (5165328192)"
 - - [25/Feb/2017:18:26:52 +0100] "POST /cgi/product_image_upload.pl HTTP/1.1" 408 0 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/602.4.6 (KHTML, like Gecko) Mobile/14D27 (5165328192)"

408 status code = request time out. Maybe an issue with image size. Let's try to set a bigger timeout in nginx and apache.

**Comment by hangy** [comment]
I'm not sure how much that'll help, but it's worth a try. It does sound like possibly a flaky mobile or wifi connection.
FWIW, I just uploaded (from Chrome Canary on my PC, so the photo was resized and the connection was stable) an image to my slow testserver with a throttled 50kb/s connection (Chrome Dev Tools) for 3.6 min and it worked well enough. The default connect and send timeouts for proxies in nginx seem to be 60 seconds and anything longer than that would probably look really unresponsive client-side. Maybe the app just needs to check the status code differently allow the user to retry in that case?

**Comment by stephanegigandet** [comment]
The cordova app has been replaced by a native iOS app.
