### ISSUE TITLE
NEW DESIGN - Personal search settings are too narrow in mobile mode

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#7492]
### What

- [ ] Personal search settings are too narrow in mobile mode
### Screenshot
![image](https://user-images.githubusercontent.com/1689815/195128219-31b3a706-6593-4573-95b9-3e8fcd676f42.png)
### Part of
- #7295

**Comment by karthiknadar1204** [comment]
i'll work on this issue @teolemon

**Comment by teolemon** [comment]
Noted @karthiknadar1204 🦖
