### ISSUE TITLE
NEW DESIGN - The go up button in edit mode should not overlap with the change summary

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#7494]
### What

- [ ] The go up button in edit mode should not overlap with the change summary
### Screenshot
![image](https://user-images.githubusercontent.com/1689815/195128959-0c76268d-09d4-4d49-af18-075a9901754a.png)
### Part of
- #7295

**Comment by Such6** [comment]
Can you assign me this issue

**Comment by MonalikaPatnaik** [comment]
hey..I would like to work on this issue!
