### ISSUE TITLE
NEW DESIGN - Not enough padding between tabs in edit mode in responsive view

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#7495]
### What

- [ ] Not enough padding between tabs in edit mode in responsive view
### Screenshot
![image](https://user-images.githubusercontent.com/1689815/195129320-de9a5a5b-dd31-401b-9dfb-a8420b17adc0.png)
### Part of
- #7295

**Comment by vannam-akash** [comment]
Please assign me this issue

**Comment by dipanshu18** [comment]
Hey, I would like to work on this issue.

**Comment by dhruv1345** [comment]
Hi, I will be able to work on this issue.
Please assign it to me.

**Comment by alexgarel** [comment]
Hi @dhruv1345, we do not assign issue most of the time, just comment to say you work on it :-)

**Comment by karthiknadar1204** [comment]
@oyenuga17 ,hows the work going on,any help needed?

**Comment by Egnodia** [comment]
I found this issue on https://ovio.org/projects and would love to contribute!
