### ISSUE TITLE
Debian 8 migration issues

### ISSUE THREAD

**Issue by kyzh** [openfoodfacts/openfoodfacts-server#75]
Debian 8 'jessie' will be released soon.
It would be a good idea to migrate our server to it as soon as we can.

There will be some issue blocking the migration.
This ticket will serve to track the relevant issue.

**Comment by wolfshtein** [comment]
Hi ! What could be the effects of changes in the 'jessie'

**Comment by kyzh** [comment]
New version for perl, for apache (maybe getting rid of the need to compile them), newer version of mongodb, newer version of few libs.
Also newer version of part of the stack that is not used yet like varnish, haproxy,memcache etc...

Also debian 8 will have more package compiled for arm like mongod, providing more options

**Comment by stephanegigandet** [comment]
Notes from lolando: http://en.wiki.openfoodfacts.org/Product_Opener_installation_on_Debian_/_Ubuntu#Installation_on_Jessie

**Comment by hangy** [comment]
OFF and OBF have now been running on Debian 8 for some time on the new server.
