### ISSUE TITLE
NEW DESIGN - Product name is truncated (JS disabled only ?)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#7502]
### What

- [ ] Product name is truncated (JS disabled only ?)
### Screenshot
![image](https://user-images.githubusercontent.com/1689815/195130318-409faadf-d217-4e01-b434-4b90166d6c02.png)
### Part of
- #7295

**Comment by TCatinaud** [comment]
Hello @teolemon, 
I would like to work on this issue, could you assign it to me please?

**Comment by alexgarel** [comment]
Hi @TCatinaud just write you are working on it on any issue and it is ok. Feel free to join [our slack](https://slack.openfoodfacts.org/) to discuss it.
