### ISSUE TITLE
NEW DESIGN - The Sort icon is too small in responsive mode

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#7505]
### What
- [ ] The Sort icon is too small in responsive mode
### Screenshot
![image](https://user-images.githubusercontent.com/1689815/195130464-45b30a9e-b3fe-49e4-8f54-0244d35a836e.png)
### Part of
- #7295

**Comment by alexgarel** [comment]
Thank you @sultanowski for those contributions !
