### ISSUE TITLE
NEW DESIGN - z-index of the map is weird

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#7509]
### What
- z-index of the map is weird
<img width="295" alt="image" src="https://user-images.githubusercontent.com/1689815/195284363-733328c6-8236-4bdb-88eb-689f8ead0d60.png">
### Part of
- #7295

**Comment by karthiknadar1204** [comment]
Please assign this issue to me,i can fix this bug
