### ISSUE TITLE
Fix or Silence SonarCloud about Regex danger

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#7514]
### What
- We have a red build because Sonarcloud is warning us about exponential backtracking on a Regex
- Either Fix the regex or Silence SonarCloud about Regex danger
- https://sonarcloud.io/project/security_hotspots?id=openfoodfacts_openfoodfacts-server&hotspots=AXvohTmvKtyiYifGNfFe

### Part of
- Devops

**Comment by alexgarel** [comment]
You can silence it. It's minor, and we have far more easier surface for a potential DoS :-/

**Comment by alexgarel** [comment]
Done, it's not even an issue, it's in the browser.
