### ISSUE TITLE
fix button title (sorting criteria list)

### ISSUE THREAD

**Issue by ashed** [openfoodfacts/openfoodfacts-server#752]
Title of button (Развернутый в продукты с...) (sorting criteria list)
better change to Сортировка продуктов

**Comment by aleksejrs** [comment]
You can see the English string at https://world.openfoodfacts.org/ or https://ru-en.openfoodfacts.org/, it's "Drilldown into products by...".  You can correct it at https://translations.launchpad.net/openfoodfacts/trunk/+pots/common-web/ru/+translate?batch=10&show=all&search=Drilldown

**Comment by aleksejrs** [comment]
Maybe just "Продукты по", because "Сортировка" looks like it will sort the list already displayed, not show a list of countries or similar.

**Comment by ashed** [comment]
fixed translation at https://translations.launchpad.net/openfoodfacts/trunk/+pots/common-web/ru/+translate?batch=10&show=all&search=Drilldown[https://translations.launchpad.net/openfoodfacts/trunk/+pots/common-web/ru/+translate?batch=10&show=all&search=Drilldown](url)

**Comment by hangy** [comment]
Probably fixed on Crowdin now?

**Comment by ashed** [comment]
![openfoodfacts-website-ru_marked-2017-11-22-15 50-36-001](https://user-images.githubusercontent.com/6615946/33124096-3e1c562c-cfa6-11e7-8722-0d18324c4ff2.png)
I cannot see any fixing in Russian interface of https://ru.openfoodfacts.org/

**Comment by hangy** [comment]
ACK, looks like it was missed in Crowdin: https://crowdin.com/translate/openfoodfacts/103/en-ru#36262
Added your suggestion on there.

**Comment by hangy** [comment]
Updated on https://ru.openfoodfacts.org/
