### ISSUE TITLE
NEW DESIGN - When trying to delete an image, the image is not highlighted when clicked

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#7522]
### What
- When trying to delete an image, the image is not highlighted when clicked

### Screenshot
<img width="497" alt="image" src="https://user-images.githubusercontent.com/1689815/195385040-95178daa-94df-4ee9-8efa-a9e5c7708d86.png">

### Part of
- #7295

**Comment by TaciteOFF** [comment]
Same issue for me on Safari 16.0 :(
A bit dangerous because I deleted too many pictures on a product by mistake
