### ISSUE TITLE
NEW DESIGN: account_circle

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#7545]
### Describe the bug

account_circle

### To Reproduce

on https://nl.openfoodfacts.org/entry-date/2022-10-14

### Expected behavior

What is this?

### Screenshots

<img width="427" alt="Screenshot 2022-10-14 at 13 13 02" src="https://user-images.githubusercontent.com/1329905/195833832-fc747062-ae2a-4a1c-85ae-82d6730d9009.png">

### Type of device

Browser

**Comment by teolemon** [comment]
This was due to a font bug, and is now fixed. Feel free to reopen if still affected.
