### ISSUE TITLE
NEW DESIGN: strange values

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#7547]
### Describe the bug

English values before the dutch ones.

### To Reproduce

is this a translation issue?

### Expected behavior

get rid of the english values

### Screenshots

<img width="619" alt="Screenshot 2022-10-14 at 13 20 51" src="https://user-images.githubusercontent.com/1329905/195835068-fae0f84d-20c8-49cf-938d-c1cbf46e3f79.png">
<img width="244" alt="Screenshot 2022-10-14 at 13 27 02" src="https://user-images.githubusercontent.com/1329905/195836117-890b3e7d-f576-4892-87bb-a0d47aa8ceb8.png">

**Comment by teolemon** [comment]
- Fixed by #7551

**Comment by teolemon** [comment]
This was due to a font bug, and is now fixed. Feel free to reopen if still affected.
