### ISSUE TITLE
NEW DESIGN: stange squares

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#7548]
### Describe the bug

What are these squares? Missing image?

### To Reproduce

...

### Expected behavior

dutch page

### Screenshots

<img width="225" alt="Screenshot 2022-10-14 at 13 28 11" src="https://user-images.githubusercontent.com/1329905/195836527-89fb9644-ac10-41cb-9b88-eaae87e94821.png">

### Type of device

Browser

**Comment by teolemon** [comment]
This was due to a font bug, and is now fixed. Feel free to reopen if still affected.
