### ISSUE TITLE
NEW DESIGN: Editing folksonomy property

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#7559]
### Describe the bug

If I change the value of folksonomy item and tap save, the interface does not update, but the change has been saved.

### To Reproduce

try changing

### Expected behavior

change the edited field to the non-editable variant and allow editing again

### Type of device

Browser

**Comment by aleene** [comment]
I no longer get suggestions and can not submit.
<img width="573" alt="Screenshot 2022-10-17 at 08 57 23" src="https://user-images.githubusercontent.com/1329905/196109584-8fbd8b8f-0bd8-41d0-bf44-1d37996f4083.png">

**Comment by teolemon** [comment]
- I've reported it in the #infrastructure channel, since it seems to be a problem with the folksonomy server being down or something.
- Note that we also have https://github.com/openfoodfacts/openfoodfacts-infrastructure

**Comment by CharlesNepote** [comment]
https://api.folksonomy.openfoodfacts.org/docs was ok but some requests were leading to 500 errors. I restarted the server and it's fine now.
