### ISSUE TITLE
Regression getting product's environment impact levels and infocard

### ISSUE THREAD

**Issue by monsieurtanuki** [openfoodfacts/openfoodfacts-server#7592]
### Describe the bug

off-dart tests fail from less than a week, about the following product fields:
* environment_impact_level_tags
* environment_infocard

### To Reproduce

* https://world.openfoodfacts.net/api/v0/product/7613331814562.json?lc=en&fields=environment_impact_level_tags - no data at all
* https://world.openfoodfacts.net/api/v0/product/5701184005007.json?lc=fr&fields=environment_infocard - no data at all

### Expected behavior

* For `environment_impact_level_tags`, we expect several items.
* For `environment_infocard`, we expect a non-null result

### Type of device

REST-API

**Comment by teolemon** [comment]
@stephanegigandet has deprecated them

**Comment by stephanegigandet** [comment]
@monsieurtanuki The environment impact levels were an experimental feature that has been replaced by the Eco-Score. We should remove them from openfoodfacts-dart.

**Comment by M123-dev** [comment]
Filed https://github.com/openfoodfacts/openfoodfacts-dart/issues/598, we can close this

**Comment by monsieurtanuki** [comment]
Thank you guys!
