### ISSUE TITLE
Update Agribalyse database from 3.0 to 3.1 to compute the Eco-Score

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#7601]
A new version of the Agribalyse database has been released this month: https://doc.agribalyse.fr/documentation/acces-donnees

One change is that it adds new vegetarian and vegan categories.

**Comment by john-gom** [comment]
I'm starting to look at this

**Comment by john-gom** [comment]
The new database and updated test results are now in https://github.com/openfoodfacts/openfoodfacts-server/tree/issue/7601. There seem to be quite a few changes to the excoscore numbers for existing products so would be good if someone else could cross-check that there is nothing surprising.

Next step is to review any changed categories and update existing taxonomies. New categories will be dealt with in #7602

**Comment by john-gom** [comment]
Quite a lot of products changed. Attached summarises number of changes by category and grade before and after.

[results.csv](https://github.com/openfoodfacts/openfoodfacts-server/files/10007623/results.csv)

**Comment by john-gom** [comment]
Previous file wasn't escaping quotes properly. New one attached.
[results.csv](https://github.com/openfoodfacts/openfoodfacts-server/files/10012294/results.csv)

**Comment by stephanegigandet** [comment]
So that's against the whole database?

Maybe it could be useful to add some columns with the previous Agribalyse ef_total, the new ef_total, and the difference between the 2.

**Comment by john-gom** [comment]
Please ignore previous results, I hadn't rebuild the categories taxonomy before running the update_all_products script. Restoring locally now and will try again and post revised results

**Comment by john-gom** [comment]
New results here. Much fewer entries where there is no longer a matching AGRIBALYSE code. Investigating these...
[results.csv](https://github.com/openfoodfacts/openfoodfacts-server/files/10029755/results.csv)

**Comment by john-gom** [comment]
Here's another version but first of all I ran update_all_products on main and then ran for this branch. Also added the categories fields switch sop full command line was:

./update_all_products.pl --fields categories --compute-ecoscore --mongodb-to-mongodb 

[results.csv](https://github.com/openfoodfacts/openfoodfacts-server/files/10035047/results.csv)

**Comment by john-gom** [comment]
Found an issue where the first code in the AGRIBALYSE source file was being skipped (11084). Now resolved.
[results.csv](https://github.com/openfoodfacts/openfoodfacts-server/files/10040587/results.csv)

**Comment by john-gom** [comment]
Attached is the full list of products that have had a change in ecoscore grade. The "... Before Main" columns apply where the ecoscore was changed when running updatge_all_products using the current main. If these are undefined then the ecoscore wasn't changed by the main branch. The "... Before Change" show the values before the new branch changes were applied.

[detail.zip](https://github.com/openfoodfacts/openfoodfacts-server/files/10040834/detail.zip)
