### ISSUE TITLE
In the Nutri-Score knowledge panel, indicate the missing nutriments that prevent computing the Nutri-Score

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#7609]
### What
- In the Nutri-Score knowledge panel, indicate the missing nutriments that prevent computing the Nutri-Score
- eg: "Salt missing to compute the Nutri-Score" or "Salt and saturated fat are missing to compute the Nutri-Score"

### Mockups
![Sub-knowledge panel - Nutri-Score - Salt -Light - FR](https://user-images.githubusercontent.com/1689815/199030998-60b43262-7a58-436a-9fed-28f94e8bf90e.png)

### Part of
- #5517
- #road to score

**Comment by teolemon** [comment]
@g123k @sineptic @alexgarel @galnaf: @stephanegigandet has created a fix: https://github.com/openfoodfacts/openfoodfacts-server/pull/10655

**Comment by sineptic** [comment]
@teolemon, thank you, but now I have other problem. last version of OFF in fdroid from 03.09.24. Why it doesn't updates for 7 month?

**Comment by g123k** [comment]
> @teolemon, thank you, but now I have other problem. last version of OFF in fdroid from 03.09.24. Why it doesn't updates for 7 month?

Thanks for the report.
I will contact Fdroid to know why we have this issue.
