### ISSUE TITLE
 In Edit Mode, indicate the required nutriments to compute the Nutri-Score by an asterisk

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#7610]
### What
- In Edit Mode, indicate the required nutriments to compute the Nutri-Score by an asterisk
### Part of
- #Nutri-Score tracker
- #road to score

**Comment by MonalikaPatnaik** [comment]
Hey..is the issue still open?can i work upon this?

**Comment by alexgarel** [comment]
Let's do it @MonalikaPatnaik :-)

This should be happen in templates/web/pages/product_edit/product_edit_form_display.tt.html
