### ISSUE TITLE
Allow to inform that the product does not have ingredient or packaging information

### ISSUE THREAD

**Issue by raphael0202** [openfoodfacts/openfoodfacts-server#7611]
It's possible to inform that a product doesn't have any nutritional information on the app and the website (seemingly through the `no_nutrition_data`). However, this is not possible for ingredients or packaging.
Ingredients or packaging information are not always displayed on the product packaging.

**Comment by teolemon** [comment]
- https://github.com/openfoodfacts/openfoodfacts-server/issues/2817 
- @raphael0202

**Comment by teolemon** [comment]
Also a wider option: https://github.com/openfoodfacts/openfoodfacts-server/issues/277

**Comment by raphael0202** [comment]
Closing this issue as we already have many duplicated issues on this subject.
