### ISSUE TITLE
NEW DESIGN: barcode missing

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#7620]
### What

- It seems that the barcode is gone in the new design. 
- For me essential to check if the product corresponded to the one I have in my hand.

### To Reproduce

- just look

### Expected behavior

- show the barcode somewhere

### Part of
- #7295

**Comment by stephanegigandet** [comment]
Fixed by https://github.com/openfoodfacts/openfoodfacts-server/pull/7855
