### ISSUE TITLE
Reintroduce the checkbox to show the donation banner again if you collapsed it

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#7621]
### What
-  Reintroduce the checkbox to show the donation banner again if you collapsed it
### Why
- Currently impossible to donate again without knowing there's a link in the footer, if you have dismissed the banner
<img width="956" alt="image" src="https://user-images.githubusercontent.com/1689815/199262885-267d841e-888c-4cf5-a454-ab831573fceb.png">

### Part of
- #7295

**Comment by teolemon** [comment]
@stephanegigandet @alexgarel @CharlesNepote

**Comment by sultanowski** [comment]
Maybe we should put smaller banner or bigger visible button on bottom of the page when someone close the banner? Or just renew a cookie with banner every {number} days...

**Comment by alexgarel** [comment]
Even in mobile mode, there would be space, right to the openfoodfacts logo for a small donate link (with a heart emoticon or something positive).

**Comment by stephanegigandet** [comment]
There is now a 2nd donation banner in the footer, which cannot be closed.
