### ISSUE TITLE
New design: it's not possible anymore to click on the images to zoom them

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#7624]
### What
- New design: it's not possible anymore to click on the images to zoom them

### Part of
- #7295

**Comment by teolemon** [comment]
Honestly, P0, this is annoying as *****

**Comment by stephanegigandet** [comment]
You can zoom images with the zoom button just below them

**Comment by teolemon** [comment]
Yes, I do know, but long living habits from the previous design, plus time lost targeting this tiny button.

**Comment by CharlesNepote** [comment]
I agree with @teolemon. It's really annoying to have to focus on the small "Zoom" button. Clicking somewhere on the image is:
* intuitive
* easier
