### ISSUE TITLE
Remove broken entries due to broken f-droid release

### ISSUE THREAD

**Issue by natrius** [openfoodfacts/openfoodfacts-server#7648]
### Describe the bug

The current f-droid release (3.6.8) causes broken entries in the database. As far as i'm aware such a broken entry leads to desinterest when stumbling upon those. 
In my opinion, these entries all should be deleted. Sorted by my country on page 95 (random choice)

![image](https://user-images.githubusercontent.com/7243447/199664881-03232715-811b-42df-a3b8-28a6097edd2d.png)

That are entries cause by at least 3.6.8, i was able to reproduce it. I don't know if the apk from the website is causing the same problem but its even older, 3.6.6 (580?) if i recall correctly. 

The most current 'old' one on F-Droid should be 3.8.1 (582) according to github.

### To Reproduce

- Download app from F-Droid (3.6.8)
- Enter product with pictures and information
- Get an entry with solely the product number. See https://world.openfoodfacts.org/product/0698845484187 for example. 

### Expected behavior

A entry in the database with alle the info and pictures. 

### Additional context

I raised the issue here https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/4868 already with no answer. I also tried the to download the new smooth app, but the apk is not available due to https://github.com/openfoodfacts/smooth-app/issues/2771 (i commented there as well). 

Lastly i kindly got the apk (734) from pierres (thanks again!) in the matrix-channel, still have to try that out. Pierre also mentioned to publicate a new f-droid version with a fixed mikit flavor -> because of that 3.8.1 did not got released on f-droid.

So
- fix f-droid release
- delete wrong database-entries

### Number of products impacted

Since 29.09.2022 - looking at a monthly 35 items that would make 630 items that should frankly be deleted - just in my country (Austria) alone. Its mentioned in that the error was resolved, but the app was never updated.

Right now on World i'm counting on page 1 about 8, page 2 about 4, page 3 about 7, page 4 about 10. Lets take middle with 7 per page. 26489 pages would make about 185423 entries, probably less because i'm sure the problem is not there from the beginning. On the other hand, there are pages with a lot of these.

**Comment by teolemon** [comment]
cc @VaiTon @stephanegigandet any opinions on this ? We haven't changed anything to image upload, so I'm not sure what could be going on .

**Comment by natrius** [comment]
No, its just an old (at least one year?) issue thats solved already. https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/3982 
The problem is:

- Old version in f-droid
- Old version (APK) on the Website

And at least the version in the F-Droid-Store leads to the error. And its not possible to get the most recent apk anywhere. But still, in my opinion the wrong entries do more harm than help and should get deleted.

**Comment by VaiTon** [comment]
Hey @natrius! If we deploy the new flutter app to the F-Droid store replacing the current listing it should not be a problem anymore. Let's wait for https://github.com/openfoodfacts/smooth-app/issues/2771

**Comment by natrius** [comment]
Yeah, thats fine, but in this issue i talk about the old, already existing database entries That do more harm Than good in my opinion.

**Comment by VaiTon** [comment]
So, TODOs:
- [ ] Wait for https://github.com/openfoodfacts/smooth-app/issues/2771
- [ ] Remove the already created products

**Comment by natrius** [comment]
The old app got updated and works now - see https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/4868 I think it would now be proper to remove the faulty entries as its possible to upload correct ones. The app from F-Droid works, the apk on the website is still old, but i will create a separate issue for that :)

**Comment by teolemon** [comment]
I'm going to close this one, the products got cleaned up @natrius
