### ISSUE TITLE
gulp-terser dependencies conflict in npm for tagify and gulp-terser-js / gulp-min

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#7662]
### What
- Country taxonomy is probably not built automatically on .net 
<img width="298" alt="image" src="https://user-images.githubusercontent.com/1689815/200352241-e836d197-b6f4-4833-b6b3-d045f91ef599.png">

**Comment by stephanegigandet** [comment]
https://github.com/gulp-community/gulp-terser-js/issues/28 is still open

**Comment by alexgarel** [comment]
I think it's solved.
