### ISSUE TITLE
Missing units in json

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#769]
Why are the units not always filled in the json? For instance: https://world.openfoodfacts.org/api/v0/product/3560070563166.json

**Comment by stephanegigandet** [comment]
I'm guessing those are the ones coming from Yuka:

February 22, 2017 at 6:21:37 PM CET - kiliweb Selected images (Changed: front_fr) -- Data (Changed: product_name) -- Nutriments (Added: saturated-fat, fiber, proteins, nutrition-score-fr, nutrition-score-uk) (Changed: energy) - (app) - view

the [nutriment] field and [nutriment]_unit is what the user (or in this case the app) sent.

the processed value is [nutriment]_100g, and the unit is always the default unit (g), or for energy, kJ.

**Comment by aleene** [comment]
Ah I did not check the origin. I have som others as well, so I will have a look and confirm (or not).

Anyway OFF shoulc guard the integrity of their database.

**Comment by stephanegigandet** [comment]
I guess the _unit field is more of an internal thing, apps should not use it. Maybe we should remove it from future versions of the API. Internally we want to keep exactly what the user entered, but we should only expose the canonicalized value.

**Comment by aleene** [comment]
It can not be an internal thing. How can I otherwise distinguish between kJ/kcal or g/mg/μg ?

**Comment by aleene** [comment]
I found another example where kiliweb changed the nutriments and where the units are wrong.

**Comment by stephanegigandet** [comment]
You need to use the _100g field (see https://world.openfoodfacts.org/data/data-fields.txt ),  it is always in g. (or kJ for energy)

The other fields are raw values from the user and nor normalized, they should not be used. We have to keep them internally, if we improve the normalization for instance.

**Comment by aleene** [comment]
Thanks, I had a look at the jsons and discovered it as well. Will do that and handle the units differently.
