### ISSUE TITLE
Product Opener crashing at startup on dev server when Producers.pm is loaded in startup_apache2.pl

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#7695]
Caused by this recent commit: https://github.com/openfoodfacts/openfoodfacts-server/commit/8dafcf69bd63c1b0cf2250e32318e72782014194

This happens only on the dev server (which does not use Docker), it seems to be working on Docker.

Commenting out
`#use ProductOpener::Producers qw/:all/;
`
in startup_apache2.pl seems to be the problem.

The weird thing is that I don't see any error message about the crash anywhere, but after we get:

[4622] /srv/off/lib/startup_apache2.pl 151 main {version => 'production'} product opener started

apache stops.

**Comment by stephanegigandet** [comment]
After deleting mostly everything in Producers.pm, it seems that this line causes the crash:

use Minion;

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/201721150-1db503fa-f969-4ced-8020-1bbe38b9e7cb.png)

**Comment by alexgarel** [comment]
Is this working now @stephanegigandet ? (to close issue).
