### ISSUE TITLE
Handle multi-lingual packaging

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#77]
Let a product have multi-lingual values for:
-ingredients
-name

-Let the user now that an ingredient list is available in another language (as well with a link to that language)
-Let him circle the ingredients list in his language in the picture.
-We can then later match ingredients using gamification

**Comment by stephanegigandet** [comment]
Started, will use bug #197 to update on progress.

**Comment by hangy** [comment]
Closing in favour of #197
