### ISSUE TITLE
Extra /cgi/login.pl string at top of login page when user/password is incorrect

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#7705]
![image](https://user-images.githubusercontent.com/8158668/202199674-bda41b47-e24a-4ebd-beb5-2e9a36615aea.png)

**Comment by Nitya-Pasrija** [comment]
Hey, I would love to contribute, can you explain the issue in detail thou?

**Comment by stephanegigandet** [comment]
@Nitya-Pasrija I think this has been fixed already, I'm closing the bug.

**Comment by Nitya-Pasrija** [comment]
Yep, I noticed that too.
