### ISSUE TITLE
Knowledge panels crash on .net env (not .org)

### ISSUE THREAD

**Issue by monsieurtanuki** [openfoodfacts/openfoodfacts-server#7707]
### Describe the bug

Looking for knowledge panels for a product will make the API crash on .net env (looks OK on .org):

> Software error:
Undefined subroutine &ProductOpener::API::initialize_knowledge_panels_options called at /opt/product-opener/lib/ProductOpener/API.pm line 633.
For help, please send mail to the webmaster ([contact@openfoodfacts.net](mailto:contact@openfoodfacts.net)), giving this error message and the time and date of the error.

### To Reproduce

https://world.openfoodfacts.net/api/v0/product/7300400481588.json?lc=fr&cc=fr&fields=knowledge_panels

### Expected behavior

No crash, and results.

### Type of device

REST-API

**Comment by teolemon** [comment]
@stephanegigandet here's feedback on this mornings deployment
