### ISSUE TITLE
/state/brands-to-be-completed/codes doesn't work anymore

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#773]
https://world.openfoodfacts.org/state/brands-to-be-completed/codes

**Comment by hangy** [comment]
> https://world.openfoodfacts.org/state/brands-to-be-completed/codes

This actually just loaded for me, even though it took some time. The resulting HTML was 27.8 MiB, so that's not too great. 😉

**Comment by VaiTon** [comment]
Closing in favour of #920
