### ISSUE TITLE
Impossible to read the full doc

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#7738]
### What
Impossible to read the full doc
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/1689815/203121912-35dba4b8-c4b6-4747-98a0-5c0f2f725afa.png">
### Part of
- #7446

**Comment by alexgarel** [comment]
Did you reproduced it @teolemon ?

**Comment by teolemon** [comment]
nope, we can close I guess.
