### ISSUE TITLE
Create a Knowledge Panel Facets section with high-level explanation and a link to the Knowledge Panel Facets API

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#7746]
### What
- Create a Knowledge Panel Facets section with high-level explanation and a link to the Knowledge Panel Facets API
- https://facets-kp.openfoodfacts.net/docs#/knowledge-panel/
- https://facets-kp.openfoodfacts.org/docs#/knowledge-panel/
### Code pointer
- This gives you an idea of where to insert the HTML code for Facets Knowledge Panels
  - https://github.com/openfoodfacts/openfoodfacts-server/pull/7742/files
- This gives you an idea of what to insert
  - [ ] https://facets-kp.openfoodfacts.net/render-to-html?facet_tag=category&value_tag=beers
  - [ ] We need to inject some of the CSS of the product page to make Knowledge Panels look like knowledge panels
  - @alexgarel and @sumit-158 can provide guidance about it

### Part of
- #7446

**Comment by teolemon** [comment]
cc @sumit-158

**Comment by teolemon** [comment]
It's live on production
### Code pointer
- https://github.com/openfoodfacts/openfoodfacts-server/pull/7742/files

**Comment by alexgarel** [comment]
How to do it:
* create a js file to call the facets knowledge panel API and inject the html in the page 
* include this js in the facet page generated by the server (the js function should be called with parameters either given through the template mechanism or using the page url)
* add some css rules for the html to be rendered correctly
  * you can ask for changes in generated html if needed on facets knowledge panel repository

**Comment by alexgarel** [comment]
@sumit-158 as found the place to put it: https://github.com/openfoodfacts/openfoodfacts-server/blob/main/templates/web/pages/tag/tag.tt.html 
it’s called by display_tag in Display.pm.
