### ISSUE TITLE
Folksonomy Engine UI is not displayed anymore

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#7777]
### Describe the bug

The UI is not displayed anymore because some HTML code has been removed from Product Opener.
Folksonomy Engine UI is appended via Javascript on a `<div>` containing `itemtype='https://schema.org/Product'`.

### To Reproduce

Open https://world.openfoodfacts.org/product/5000119532329/conchiglie-tesco

**Comment by alexgarel** [comment]
It's resolved right @CharlesNepote ?

**Comment by CharlesNepote** [comment]
Yes!
