### ISSUE TITLE
NEW DESIGN: The barcode is not visible in edit mode

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#7786]
### What
- NEW DESIGN: The barcode is not visible in edit mode
- example: https://world-fr.openfoodfacts.org/cgi/product.pl?type=edit&code=07370793

### Part of
- #7295

**Comment by Sakshamgupta90** [comment]
Hi,
Can I work on this issue?

**Comment by alexgarel** [comment]
welcome @Sakshamgupta90, 
Yes you can work on it :-)

**Comment by Sakshamgupta90** [comment]
Hi, I want to know is it look good? or I have to show the barcode inside a box.
<img width="220" alt="Screenshot 2022-12-15 at 11 34 37 PM" src="https://user-images.githubusercontent.com/84325475/207935030-e76c824c-6ad3-41f1-9712-71a592764d85.png">

**Comment by Sakshamgupta90** [comment]
Hi, @alexgarel I have opened the pull request for this issue, looking forward to contribute more :)
