### ISSUE TITLE
Htaccess rule - redirecting /en:product/ in the right language

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#7793]
### Describe the bug

There used to be a rule in the htaccess file that no longer seems to be there. 

When opening a product on the web, the url contains the word `product` in a language specific to the country in the url. The use of generic word for product like `en:product`, makes it much easier to create multilingual links, as one does not have to take into the account all languages for the word product (produkt, prodotto, produit, produto, etc).

### To Reproduce

Try https://nl.openfoodfacts.org/en:product/8716100610125/

### Expected behavior

This example should be mapped to Try https://nl.openfoodfacts.org/product/8716100610125/

### Screenshots

gives an empty screen

### Type of device

Browser

### Browser version

Safari

**Comment by hangy** [comment]
Probably not a .htaccess rule, but previously part of https://github.com/openfoodfacts/openfoodfacts-server/blob/4e8e83d365f8ac93cc69faa0fc6794bc28ae0537/lib/ProductOpener/Display.pm#L891 - IIRC ProductOpener doesn't really use .htaccess at all.

**Comment by stephanegigandet** [comment]
@aleene I don't remember that syntax to work with en:product, but it does work without the en: https://fr.openfoodfacts.org/product/8716100610125/ redirects to https://fr.openfoodfacts.org/produit/8716100610125/zure-matten-aardbeismaak-katja

Maybe that's the feature you are looking for?

**Comment by aleene** [comment]
It used to work, as I implemented it in FoodViewer. However this new solution is good enough for me.
