### ISSUE TITLE
[Bug] Unable to update product packaging from hunger game

### ISSUE THREAD

**Issue by alexfauquette** [openfoodfacts/openfoodfacts-server#7796]
### What

- Unable to update product packaging from hunger game
- Sounds like there is a CORS problem:

I tried to use [experimental hunger game page](https://hunger.openfoodfacts.org/packaging) to update a product packaging ([this product](https://world-fr.openfoodfacts.org/produit/8001420000788/riso-gallo-blond-rice-integrale-veloce)) but it returns CORS issue and the product page is not updated

I reproduced the same request by copy-pasting url/body in postman, and then, it update product information, cf following the modification line:

4 décembre 2022 à 13:32:54 CET - openfoodfacts-contributors - API v3 - voir

Here is the request used:

https://world.openfoodfacts.org/api/v3/product/8001420000788
```json
{
    "product": {
        "fields": "updated",
        "packagings": [
            {
                "shape": {
                    "id": "en:bag"
                },
                "material": {
                    "id": "en:plastic"
                },
                "recycling": {
                    "id": "en:recycle-with-plastics"
                }
            }
        ]
    }
}
```

like 

### To Reproduce

- Go to the hunger game page
- click on button to see the product in another page
- fill the table
- open network debug
- send annnotation

You should see a PATCH request sent returning CORS issue and the product is not updated

### Type of device

REST-API

**Comment by stephanegigandet** [comment]
@alexfauquette The OPTIONS request is sent those headers:

access-control-allow-credentials: true
access-control-allow-origin: https://hunger.openfoodfacts.org

I'm not sure which one it wants though. Maybe access-control-allow-methods? Anything else?

**Comment by alexfauquette** [comment]
Yes, [`Access-Control-Allow-Methods`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Methods) could be the source of the problem.

I was not aware about that but only `GET`, `HEAD`, and `POST` are considered as [simple requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#simple_requests). Others have a [preflight request](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request) and if the server does not allow the method, the browser will nether send the request.

**Comment by teolemon** [comment]
@stephanegigandet any update

**Comment by alexgarel** [comment]
I will look into this.

**Comment by teolemon** [comment]
Thanks @alexgarel
