### ISSUE TITLE
Hide the classic packaging field (packagings) in edit mode

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#7804]
### What
- Hide the classic packaging field (packagings) in edit mode

### Why
- It's replaced by packaging_text and the new structured field

### Part of
- #6374

**Comment by MonalikaPatnaik** [comment]
Hey.. I would like to work on this issue..kindly tell me some pointers to fix it!
Thanks!

**Comment by alexgarel** [comment]
You can look at templates/web/pages/product_edit/product_edit_form_display.tt.html

where you see it uses display_fields_arr to get fields to display.

You can then search where this list is built.
