### ISSUE TITLE
energy-value-in-kcal-does-not-match-value-in-kj: false positive for low values

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#7811]
### Describe the bug

https://wiki.openfoodfacts.org/Data_quality_issues_which_can%27t_be_fixed#When_energy_values_are_low_.281-10_Kcal.29

When energy values are low (1-10 Kcal?), there are often matching issues between the energy in Kcal and KJ. This often because producers are rounding the values.

Eg. https://world.openfoodfacts.org/product/3502110008459: In this example, 1 Kcal (rounded) => 6 KJ. Because 6 / 4.2 = 1.428, the producer is probably rounding 1.42 to 1.

see also:
* https://world-fr.openfoodfacts.org/produit/3564700737194/jus-de-citron-de-sicile-rustica
* https://world-fr.openfoodfacts.org/produit/4056489009412/jus-de-citron-vert-solevita

### Expected behavior

This should be a warning and not an error.

**Comment by alexgarel** [comment]
reported by @aleene, herbal tea: https://world.openfoodfacts.org/product/4056489024330/infusion-rooibos-saveur-citron-gingembre-lord-nelson

**Comment by CharlesNepote** [comment]
As of 2022-12-20, there are [421 products](https://mirabelle.openfoodfacts.org/products?sql=select+%0D%0Aurl%2C+%5Benergy-kj_100g%5D%2C+%5Benergy-kcal_100g%5D%0D%0Afrom+%5Ball%5D%0D%0Awhere+true%0D%0A--and+%28%5Benergy-kj_100g%5D+%3D%3D+2+or+%5Benergy-kj_100g%5D+%3D%3D+3+or+%5Benergy-kj_100g%5D+%3D%3D+5+or+%5Benergy-kj_100g%5D+%3D%3D+6%29%0D%0Aand+%5Benergy-kcal_100g%5D+%3C%3D+2%0D%0Aand+data_quality_errors_tags+like+%22%25energy-value-in-kcal-does-not-match-value-in-kj%25%22%0D%0Aorder+by+%5Benergy-kj_100g%5D+desc+%0D%0Alimit+500) with less than 2 Kcal which provide the error.

There are also many products with a serving size under 2g which are probably concerned but not detected yet because the energy in Kcal is not yet filed.

I made a [spreadsheet to understand the impact of rounding low values](https://docs.google.com/spreadsheets/d/1MaEmHLXVAnfIViJS2IbLwVT4kz5GMuFFVQTDmP06cEc/edit#gid=0). We can see that the issue occurs when Kcal is equal to 2 or below.

The place to change our threshold is there: https://github.com/openfoodfacts/openfoodfacts-server/blob/main/lib/ProductOpener/DataQualityFood.pm#L689

```diff
# check energy in kcal is ~ 4.2 energy in kj
if (
		(
			$product_ref->{nutriments}{"energy-kj_value"}
-			< 3.7 * $product_ref->{nutriments}{"energy-kcal_value"} - 1
+			< 3.7 * $product_ref->{nutriments}{"energy-kcal_value"} - 2
		)
		or ($product_ref->{nutriments}{"energy-kj_value"}
-			> 4.7 * $product_ref->{nutriments}{"energy-kcal_value"} + 1)
+			> 4.7 * $product_ref->{nutriments}{"energy-kcal_value"} + 2)
		)
	{
		push @{$product_ref->{data_quality_errors_tags}}, "en:energy-value-in-kcal-does-not-match-value-in-kj";
	}
```
