### ISSUE TITLE
Product loading is broken on .net

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#7814]
### What
- Product loading is broken on .net
![image](https://user-images.githubusercontent.com/1689815/206467312-c3c9f97f-7da6-4db8-8933-35bcd302c785.png)

**Comment by alexgarel** [comment]
@teolemon isn't it a product that you recently added to org database ? We do not refresh products so frequently at the moment.

**Comment by teolemon** [comment]
we can close, @stephanegigandet told me the likely cause for this
