### ISSUE TITLE
The Windows Phone link is broken

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#782]
```http://www.windowsphone.com/en-us/store/app/openfoodfacts/5d7cf939-cfd9-4ac0-86d7-91b946f4df34```

Not sure about the new URL

**Comment by olicarter** [comment]
@teolemon I've done an extensive Google and can't seem to find it on the Windows Phone app store though I don't have a Windows phone so it may only be the web store that doesn't show it.

Should the link be removed completely or can someone resolve this with Microsoft?

**Comment by teolemon** [comment]
Fixed @olicarter 
The app had been unpublished
