### ISSUE TITLE
Do not compute the nutriscore nutrition grade if there is no category set

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#783]
Beverages have a different scoring formula, so if we don't have a category, we should not compute the Nutriscore.
(e.g. US products from USDA that have nutrition facts but no categories, or some products from some apps)

**Comment by CharlesNepote** [comment]
This issue have been solved isn't it?

The problem now is that **so many products doesn't have Nutri-score computed due to lack of category**... Should we open a P1 priority issue as Open Food Facts growth and Nutriscore growth are highly correlated?

**Comment by stephanegigandet** [comment]
Deployed 2 years ago.
