### ISSUE TITLE
Eco-Score or Éco-Score ?

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#7831]
@stephanegigandet you modified Éco-Score into Eco-Score, and as a result the tests are confused. Does French get to keep the accent ? not ? Should we modify the French test accordingly ? 
#   Failed test at tests/unit/attributes.t line 221.
# 
#     Structures begin differing at:
#          $got->{attribute_groups_fr}[4]{attributes}[0]{name} = 'Eco-Score'
#     $expected->{attribute_groups_fr}[4]{attributes}[0]{name} = '�co-Score'
# 
# {

**Comment by stephanegigandet** [comment]
@teolemon Eco-Score does not have an accent, see https://docs.score-environnemental.com/ "L'Eco-score® est un indicateur représentant l'impact environnemental des produits alimentaires. "

The tests have already been modified, they are waiting to be merged in this PR: https://github.com/openfoodfacts/openfoodfacts-server/pull/6085/

**Comment by teolemon** [comment]
Validated
