### ISSUE TITLE
Add a special label if the ingredient list ends with ,

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#784]
Can we add a label: "Ingredient list probably uncomplete" for all ingredient list ending by a coma ?

**Comment by stephanegigandet** [comment]
Can you list one example in the bug, just for reference?

Instead of a label, I think we could use the debug field for this.
https://world.openfoodfacts.org/debug

**Comment by teolemon** [comment]
- We have list ending with a single character
https://world.openfoodfacts.org/product/0071567993647/49-assorted-flavors-jelly-belly

- Some end with a coma (can't find one right now)
- Some have a different count of ingredients according to language

**Comment by VaiTon** [comment]
Can close as now there are quality [checks for this](https://world.openfoodfacts.org/quality/ingredients-en-ending-comma).
