### ISSUE TITLE
Translation test should fail on missing placeholders

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#7906]
### What
Translation test should fail on missing placeholders
```
# keep %s, it will be replaced by the letter A, B, C, D or E
msgctxt "attribute_nutriscore_grade_title"
msgid "Nutri-Score %s"
msgstr ""
msgstr "영양 점수"
```

### To Reproduce

Visible in Korean translations

### Expected behavior

Test fails, preventing faulty translations from making it to production

**Comment by diivi** [comment]
Where can I find the file for translation tests?
