### ISSUE TITLE
No "Remember me" checkbox in responsive mode

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#7915]
### What
- No "Remember me" checkbox in responsive mode
![image](https://user-images.githubusercontent.com/1689815/209975941-11d35bba-e9d5-4779-b62d-cc4b28fdaafb.png)

**Comment by karthiknadar1204** [comment]
I would like to work on this issue,please assign it to me

**Comment by karthiknadar1204** [comment]
please assign the issue to me,i can fix it
