### ISSUE TITLE
Estimate Ingredient percentages from nutritional data

### ISSUE THREAD

**Issue by john-gom** [openfoodfacts/openfoodfacts-server#7918]
Use CIQUAL to get the the nutrient composition of each ingredient and use this to estimate the original recipe by matching with the nutritional information about the product.

Discussion on potential algorithms here: https://docs.google.com/document/d/1cPEEhl9Ty0feKEel2NxUmscRR6oWZTLJMpTSbLbzB5U/edit?usp=sharing

**Comment by john-gom** [comment]
Issues observed during development:

- Have no CIQUAL codes for ingredients like:
  - [ ] Water
  - [ ] Vitamins (e.g. added B12)
  - [ ] Minerals (e.g. Calcium Carbonate)
  - [ ] Processed raw ingredients, e.g. Pea Protein (Isolate)
- [ ] Nutrient parsing seems to miss data sometimes (e.g. 7394376616709). Can't see source text from OCR

Improvements needed to the algorithm
- [ ] Some ingredients are not specific enough to ever be known (e.g. "Flavouring")
- [ ] Dealing with advertised Ingredient quantities
- [ ] Qualified nutrient levels e.g. less than, "trace" (in CIQUAL or product)

**Comment by john-gom** [comment]
Hi @karthiknadar1204 , the code is now in the recipe-estimator repo on a working branch. There are instructions on running in docker if you want to play. Contact @alexgarel if you get any permission issues. There is a project board in the repo on areas I was hoping to look at...

**Comment by alexgarel** [comment]
See https://github.com/openfoodfacts/recipe-estimator/

**Comment by alexgarel** [comment]
@john-gom can we make the project board public in recipe-estimator ?
