### ISSUE TITLE
Product search / State tag / discrepancies

### ISSUE THREAD

**Issue by monsieurtanuki** [openfoodfacts/openfoodfacts-server#7922]
### Describe the bug

In off-dart we run tests, and one of them frequently fails ("frequently" only because we use random inputs in our tests).
* Test with state tag 1 - [number of products with `states_tags=en:complete`](https://world.openfoodfacts.org/cgi/search.pl?lc=fr&tags_lc=fr&cc=fr&fields=code,states_tags&page=1&page_size=100&states_tags=en:complete&search_terms=&json=1&api_version=3): 6566
* Test with state tag 2 - [number of products with `states_tags=en:to-be-checked`](https://world.openfoodfacts.org/cgi/search.pl?lc=fr&tags_lc=fr&cc=fr&fields=code,states_tags&page=1&page_size=100&states_tags=en:to-be-checked&search_terms=&json=1&api_version=3): 6243
* Test with both state tags - [number of products with `states_tags=en:complete,en:to-be-checked`](https://world.openfoodfacts.org/cgi/search.pl?lc=fr&tags_lc=fr&cc=fr&fields=code,states_tags&page=1&page_size=100&states_tags=en:complete,en:to-be-checked&search_terms=&json=1&api_version=3): 6247

The counts do not seem correct, as we would expect the filter on state tags to be an `AND`.
If it were an `AND`, the "both" count couldn't be greater than "test 1" or than "test 2". And it is.

Same thing would be true for `OR`: the "both" count would be greater than "test 1" and than "test 2". And it is not.

### To Reproduce

Run the same queries - just click on the links and check the `"count"` value in the returned JSON.

### Expected behavior

We expect either an `AND` or an `OR` combo, and therefore a lower (or a greater) value when both conditions are together than with individual state tag tests.

### Type of device

Browser

**Comment by stephanegigandet** [comment]
Hi @monsieurtanuki , search results are cached, and may not be exactly up to date. You can add &no_cache=1 to disable the cache. This is why you see number of results that don't exactly match.
