### ISSUE TITLE
Compute packaging stats for categories

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#7929]
Now that users can enter detailed information for each packaging component (shape, material, weight etc.), we can try to compute packaging statistics for categories. e.g. to determine the most common packaging components of yogurts, the distribution of their weights etc.

Those stats can be used to suggest packaging components when editing products, to show how one product compares to similar products etc.

Which exact stats to compute is yet to be defined. We will probably start with some basic stats, see what we get and how we could extend them.

**Comment by zanovis** [comment]
Awesome. Will users be able to enter this data manually or does the product package need to contain the information?

**Comment by stephanegigandet** [comment]
We now compute basic stats by country / category / shape, that we use for suggestions of shapes and materials.
