### ISSUE TITLE
Write api no_nutriments fails

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#795]
I try to use the `no_nutriments` to indicate that there are no nutriments on the package. 

It is however not accepted by OFF, nothing changes.
In the changes history the edit is seen:
``
April 14, 2017 at 4:54:50 PM CEST - foodviewer - (app) - view
April 14, 2017 at 4:53:40 PM CEST - foodviewer Data (Deleted: no_nutrition_data) - (app) - view
``
PS need to doublecheck how I write.

**Comment by aleene** [comment]
Checked, I write:
`"https://ssl-api.openfoodfacts.org/cgi/product_jqm2.pl?code=3333313202012&user_id=foodviewer&password=yes&lang=fr&no_nutriments"	`

Seems OK to me, but nothing changes on the server.

**Comment by teolemon** [comment]
```<input type="checkbox" id="no_nutrition_data" name="no_nutrition_data">```

**Comment by aleene** [comment]
"no_nutrition_data" does not work.

**Comment by hangy** [comment]
I researched the code a bit. It's `&no_nutrition_data=on` to set the checkbox; `&no_nutrition_data` (just the key; no value) to delete it.

**Comment by aleene** [comment]
Great thanks. Maybe an idea to put this in the API documentation.
