### ISSUE TITLE
Add a crawl delay for search engines

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#7965]
Some search engines and crawling tools are taking into account the `Craw-delay` directive in the [robots.txt](https://github.com/openfoodfacts/openfoodfacts-server/blob/main/html/robots.txt) file: at least Bing, Yahoo!, Yandex. Source: https://www.contentkingapp.com/academy/robotstxt/faq/crawl-delay-10/

Using `Crawl-delay: 0.5` will ask them to make a 0.5s pause between two requests.
It will allow them to make 2 requests per seconds * 60 *60 *24 = 172 800 products per day. It would take ~18 days to index ~3 millions pages, which seam to be reasonable. It could be `1` or `2` instead of `0.5`.

There are only two lines to add on `robots.txt`:
```
User-agent: *
Crawl-Delay: 0.5
```

TODO: analyze how many requests the main search engines are making.

**Comment by Jayabrata18** [comment]
is this issue still open? If yes I want to contribute , plz assign me

**Comment by raphael0202** [comment]
I'm closing this issue, as adding a crawl-delay won't help: we need web crawlers to index web pages fast, given the number of pages to index (see #8751 to have more context about crawler impact on performance).
