### ISSUE TITLE
Add a field to see which 'server' the product is on

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#797]
### What
- Add `"new_server":"off"` to the OFF-json. I use it to detect product type.

### Part of
- #5505 
- #5536 
- #5555

**Comment by stephanegigandet** [comment]
You mean to distinguish between OFF and OBF? Why "new" server?

**Comment by aleene** [comment]
I don't know why it is called new_server, that comes from the opff- and opb-servers jsons.

**Comment by stephanegigandet** [comment]
new_server is something internal, when a product is moved from OFF to OBF or OPFF or the reverse. It will go away, please don't rely on it.

**Comment by stephanegigandet** [comment]
It should have been transient and not included in the json or the database, it's a bug.

**Comment by aleene** [comment]
OK. 
I am just exploring a way to support the three product types within a single app. I need to store the product type for this. I want to rely on info found in the json, so I was looking for a fild that could help me.

**Comment by teolemon** [comment]
Oh you want to try displaying them without having to switch ?

**Comment by aleene** [comment]
Do not know yet. At the moment I support a history, which now contains any product type (and complains that a product doesn not exist). So I need to filter to a specif type. But I could try to support an ALL filter.

**Comment by aleene** [comment]
Still I would like to see from the json-file, which server (product type) it refers to. Maybe add a tag with the original json-link. As I store the jsons from time to time, I can no longer refer to the original http string. And I do not trust the image links for determining the product type, as there is not always an image.

**Comment by teolemon** [comment]
@stephanegigandet closing
