### ISSUE TITLE
Redirect for synonym on facets loose the end of the url

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-server#7979]
### Describe the bug

If you try to reach https://world.openfoodfacts.org/category/en:lemonades/data-quality
you are redirected to https://world.openfoodfacts.org/category/en:lemonade

Redirection is ok because it's a synonym, so we redirect to id. What is wrong is that we loose the second facet in the redirect.

### To Reproduce

1. go to https://world.openfoodfacts.org/category/en:lemonades/data-quality
2. The page you land on is not a data-quality page

### Expected behavior

https://world.openfoodfacts.org/category/en:lemonades/data-quality should redirect to https://world.openfoodfacts.org/category/en:lemonade/data-quality

### Additional context

Causes:
- https://github.com/openfoodfacts/facets-knowledge-panels/issues/85

**Comment by Adarsh-Shetkar** [comment]
@alexgarel Can you assign me this issue

**Comment by DataScience-Mayur** [comment]
I would like to work on this, can you give me some starting points? I am trying open source contribution for the first time.

**Comment by alexgarel** [comment]
Hi @DataScience-Mayur, it happens in [Display.pm line 3095](https://github.com/openfoodfacts/openfoodfacts-server/blob/v2.6.0/lib/ProductOpener/Display.pm#L3095)

**Comment by jnsereko** [comment]
Following this up @yuktea.  Can you kindly assign to me so that i don't violet contribution rules :) 
ref:  https://openfoodfacts.slack.com/archives/C02LDQDDD/p1678431913964239?thread_ts=1678268447.535609&cid=C02LDQDDD

**Comment by yuktea** [comment]
@jnsereko: assigned!

**Comment by jnsereko** [comment]
hey @alexgarel @yuktea @stephanegigandet 

IMHO this goes beyond just a mere redirection, to actually how [request urls are mapped  ](https://github.com/openfoodfacts/openfoodfacts-server/blob/a85a5d34fc240ae8af0b15764651729daeb6e902/lib/ProductOpener/Display.pm#L565-L566)

making a request like `https://world.openfoodfacts.org/category/en:lemonades/data-quality` should generate a url that ends with `data-quality` which is not present in the request-url as early as initialisation from the  QUERY_STRING environment variable `$ENV{QUERY_STRING}`. 

Unless `/data-quality` has to be mapped as  `tagid2` i think i should be looking for this somewhere else.  
```
  'canon_rel_url'=>'/category/en:lemonade',
  'country'=>'en:world',
  'user_preferences'=>1,
  'query_string'=>'category/lemonade',
  'original_query_string'=>'category/lemonade',
  'cc'=>'world',
  'method'=>'GET',
  'lcs'=>[
    'en'
  ],
  'tag_prefix'=>'',
  'page'=>1,
  'tag'=>'en:lemonade',
  'referer'=>undef,
  'tagid'=>'en:lemonade',
  'tagtype'=>'categories',
  'lc'=>'en'
```

**Comment by jnsereko** [comment]
I think `/data-quality` is handled as some sort of facet ie a tag or something like that

**Comment by stephanegigandet** [comment]
@jnsereko : /data-quality should be mapped to $request_ref->{groupby_tagtype}

```
		if (defined $tag_type_from_plural{$lc}{$components[-1]}) {

			$request_ref->{groupby_tagtype} = $tag_type_from_plural{$lc}{pop @components};
			$canon_rel_url_suffix .= "/" . $tag_type_plural{$request_ref->{groupby_tagtype}}{$lc};
			$log->debug("request looks like a list of tags", {groupby => $request_ref->{groupby_tagtype}, lc => $lc})
				if $log->is_debug();
		}
```

Then when we construct the redirect url, we need to make sure it is added at the end.
https://github.com/openfoodfacts/openfoodfacts-server/blob/a85a5d34fc240ae8af0b15764651729daeb6e902/lib/ProductOpener/Routing.pm#L386
