### ISSUE TITLE
Typing PET in the autosuggest for materials is a disappointing and misleading experience

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#7994]
### What
- Typing PET in the autosuggest for materials is a disappointing and misleading experience

### Screenshot
![image](https://user-images.githubusercontent.com/1689815/212692065-27ec84dc-e633-43ca-a0ba-7fac6b08ec5e.png)

![image](https://user-images.githubusercontent.com/1689815/212692043-66b3d14c-572b-49c6-bf2b-84abd361b67f.png)

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/212692235-ae8d66e7-9bfb-45b4-ba95-93e7d9c2efb0.png)
![image](https://user-images.githubusercontent.com/1689815/212692303-671c5cc0-b0ba-469f-b033-6a5f38658daf.png)

**Comment by stephanegigandet** [comment]
Depends on #8002

**Comment by stephanegigandet** [comment]
Fixed by new material suggestions weighted by popularity for the category and/or shape.

![image](https://user-images.githubusercontent.com/8158668/225380784-77bb5a37-7852-4740-8828-22883e04c2f9.png)
