### ISSUE TITLE
Part of the packaging information provided is not taken into account

### ISSUE THREAD

**Issue by raphael0202** [openfoodfacts/openfoodfacts-server#8001]
### Describe the bug

See "To Reproduce"

### To Reproduce

1. Go to product https://fr.openfoodfacts.org/produit/3596710465385/lait-ecreme-bio-auchan
2. Replace "Bouchon de bouteille de vin" by "Bouchon de bouteille"
3. Save
4. The shape is still "Bouchon de bouteille de vin"

### Expected behavior

I expected the update to be applied.

### Type of device

Browser

**Comment by stephanegigandet** [comment]
It's a taxonomy issue, one synonym is missing "de vins":

```
# Note: cork is listed under materials, it cannot be a synonym of wine cork in the shapes taxonomy.
<en:Bottle cap
en:Wine cork, wine bottle cork, wine corks, wine bottle corks
bg:Коркова тапа за вино, Корк за вино
fr:bouchon de bouteille de vin, bouchons de bouteille
```

**Comment by raphael0202** [comment]
Oh indeed! I should have checked that. Thanks!
