### ISSUE TITLE
Compute popularity facets for 2022

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#8007]

**Comment by stephanegigandet** [comment]
We have an issue for the scans of the new app, as it did not send the User-Agent field properly, so it is very hard to find the real scans from the app. If we search API calls with the dart::io User-Agent, most of the data seems to be from bots.

One option is to use the scan events from Matomo. Matomo has an HTTP API (limited to 10k events so we would need multiple calls). Or the easiest might be to make SQL queries directly against the Matomo database: https://matomo.org/faq/how-to/how-do-i-write-sql-queries-to-select-visitors-list-of-pageviews-searches-events-in-the-matomo-database/

**Comment by stephanegigandet** [comment]
Scans 2022 have been populated  (Android legacy + iOS legacy + Smoothie opt-in users that sent scan data to Matomo).
