### ISSUE TITLE
Wrong identification of E470 additive - Sels de sodium/potassium/calcium d'acides gras

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#801]
https://fr.openfoodfacts.org/produit/3229820181738/biscuit-sesame-bio-bjorg

→ Les ingrédients sont listés par ordre d'importance (quantité).
Liste des ingrédients : Farine de blé 46 %, sucre de canne roux non raffiné, farine complète de blé 15 %, graines de sésame 13 %, huile de tournesol oléique 13 %, sel marin non raffiné, poudres à lever : carbonates d'ammonium et de sodium, acide citrique ; extrait de vanille, antioxydant : extraits de romarin.
Substances ou produits provoquant des allergies ou intolérances : Gluten, Graines de sésame

Additifs :
E503 - Carbonates d'ammonium
E330 - Acide citrique
E502 - Carbonates
E470 - Sels de sodium/potassium/calcium d'acides gras

**Comment by stephanegigandet** [comment]
additives: " [ farine-de-ble-46 -> fr:farine-de-ble-46 ] [ farine-de-ble -> fr:farine-de-ble ] [ farine-de -> fr:farine-de ] [ farine -> fr:farine ] [ sucre-de-canne-roux-non-raffine -> fr:sucre-de-canne-roux-non-raffine ] [ sucre-de-canne-roux-non -> fr:sucre-de-canne-roux-non ] [ sucre-de-canne-roux -> fr:sucre-de-canne-roux ] [ sucre-de-canne -> fr:sucre-de-canne ] [ sucre-de -> fr:sucre-de ] [ sucre -> fr:sucre ] [ farine-complete-de-ble-15 -> fr:farine-complete-de-ble-15 ] [ farine-complete-de-ble -> fr:farine-complete-de-ble ] [ farine-complete-de -> fr:farine-complete-de ] [ farine-complete -> fr:farine-complete ] [ farine -> fr:farine ] [ graines-de-sesame-13 -> fr:graines-de-sesame-13 ] [ graines-de-sesame -> fr:graines-de-sesame ] [ graines-de -> fr:graines-de ] [ graines -> fr:graines ] [ huile-de-tournesol-oleique-13 -> fr:huile-de-tournesol-oleique-13 ] [ huile-de-tournesol-oleique -> fr:huile-de-tournesol-oleique ] [ huile-de-tournesol -> fr:huile-de-tournesol ] [ huile-de -> fr:huile-de ] [ huile -> fr:huile ] [ sel-marin-non-raffine -> fr:sel-marin-non-raffine ] [ sel-marin-non -> fr:sel-marin-non ] [ sel-marin -> fr:sel-marin ] [ sel -> fr:sel ] [ poudres-a-lever -> fr:poudres-a-lever ] [ poudres-a -> fr:poudres-a ] [ poudres -> fr:poudres ] [ carbonates-d-ammonium-et-de-sodium -> fr:carbonates-d-ammonium-et-de-sodium ] [ carbonates-d-ammonium-et-de -> fr:carbonates-d-ammonium-et-de ] [ carbonates-d-ammonium-et -> fr:carbonates-d-ammonium-et ] [ carbonates-d-ammonium -> en:e503 -> exists -- ok ] [ acide-citrique -> en:e330 -> exists -- ok ] [ extrait-de-vanille -> fr:extrait-de-vanille ] [ extrait-de -> fr:extrait-de ] [ extrait -> fr:extrait ] [ antioxydant -> fr:antioxydant ] [ extraits-de-romarin -> fr:extraits-de-romarin ] [ extraits-de -> fr:extraits-de ] [ extraits -> fr:extraits ] [ carbonates-d-ammonium -> en:e503 ] [ carbonates-d -> fr:carbonates-d ] [ carbonates -> en:e502 -> exists -- ok ] [ sodium -> en:e470 -> exists -- ok ] ",

**Comment by teolemon** [comment]
```
en:E470, Sodium\, potassium\, calcium and magnesium salts of fatty acids
bg:E470, E470 food additive
cs:E470, E470 food additive
da:E470, E470 food additive
de:E470, E470 food additive
el:E470, E470 food additive
es:E470, E470 food additive
et:E470, E470 food additive
fi:E470, E470 food additive
fr:E470, Sels de sodium/potassium/calcium d'acides gras, Sels de sodium d'acides gras, Sels de potassium d'acides gras, Sels de calcium d'acides gras, Sels d’acides myristique, Sels d’acide oléique avec potassium, Sels d’acide oléique avec sodium, Sels d’acide oléique avec calcium
hu:E470, E470 food additive
it:E470, E470 food additive
lt:E470, E470 food additive
lv:E470, E470 food additive
mt:E470, E470 food additive
nl:E470, Vetzuurzouten
pl:E470, E470 food additive
pt:E470, E470 food additive
ro:E470, E470 food additive
sk:E470, E470 food additive
sl:E470, E470 food additive
sv:E470, E470 food additive
e_number:en:470
```

**Comment by stephanegigandet** [comment]
en:E470, Sodium\, potassium\, calcium and magnesium salts of fatty acids
--> One of the issues, this causes Sodium to be a synonym of E470 and of Potassium...

**Comment by stephanegigandet** [comment]
Second issue: we don't split " poudres à lever : carbonates d'ammonium et de sodium" correctly, it was split in carbonates d'ammonium + sodium (instead of carbonates de sodium)

**Comment by stephanegigandet** [comment]
Fixed the two issues.

Still a minor issue: https://fr.openfoodfacts.org/produit/3229820112046/le-biscuit-de-natty-bio-bjorg
carbonates acides d’ammonium et de sodium -> carbonates de sodium is not detected

**Comment by stephanegigandet** [comment]
Fixed the last case and added tests.
