### ISSUE TITLE
F-Droid download button too large

### ISSUE THREAD

**Issue by M123-dev** [openfoodfacts/openfoodfacts-server#8026]
### Describe the bug

The F-Droid download is way too large compared to the Play Store, App Store

### To Reproduce

https://world.openfoodfacts.org/open-food-facts-mobile-app

### Expected behavior

They should have a similar size

### Screenshots

![grafik](https://user-images.githubusercontent.com/39344769/214094430-6d211ad3-0e19-4821-8e48-b474ceb27195.png)

### Type of device

Browser

### Browser version

Firefox

**Comment by sidharthviz** [comment]
Hey let me help you with the button size. if it's not already fixed

**Comment by sidharthviz** [comment]
> Hey let me help you with the button size. if it's not already fixed, Please assign me to fix this

Hey Alex, I've been trying to fix the issue but i think my mac is too old to handle the data even with Gitpod. Please assign  to someone else. Although thank you for the opportunity.

**Comment by Tushar98644** [comment]
> > Hey let me help you with the button size. if it's not already fixed, Please assign me to fix this
> 
> Hey Alex, I've been trying to fix the issue but i think my mac is too old to handle the data even with Gitpod. Please assign to someone else. Although thank you for the opportunity.

**Comment by Tushar98644** [comment]
@alexgarel i would love to take up the issue ....pls assign me if the issue still needs help

**Comment by teolemon** [comment]
Seems fixed, at least in English. Would need to cross check in openfoodfacts-web
