### ISSUE TITLE
Additive "Colour - Color" detected on 2 products (is actually empty)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#803]
https://world.openfoodfacts.org/additive/colour-color

![image](https://cloud.githubusercontent.com/assets/1689815/25179912/2a5b7aea-250c-11e7-9b69-51c214e7e299.png)
https://world.openfoodfacts.org/additives

**Comment by stephanegigandet** [comment]
Not a problem anymore.
