### ISSUE TITLE
make dev doesn't work on mac

### ISSUE THREAD

**Issue by sgtSeme4ki** [openfoodfacts/openfoodfacts-server#8040]
This is because nproc is used in the Makefile (to set the CPU_COUNT), which isn't a valid macOS-command (at least on a mac m1 afaik).
This can be fixed by an simple if-statement which will set the CPU_COUNT with the mac-command instead of nproc.

**Comment by sgtSeme4ki** [comment]
Im currently working on this

**Comment by alexgarel** [comment]
Thank you @sgtSeme4ki :slightly_smiling_face:
