### ISSUE TITLE
Clipped image

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#8059]
### Describe the bug

The loading of an image results in a clipped and rotated image. Thus I can not see and select a part of the image.

### To Reproduce

Check https://nl.openfoodfacts.org/product/5054563148445

### Expected behavior

See the whole image

### Screenshots

<img width="583" alt="Screenshot 2023-02-01 at 10 02 00" src="https://user-images.githubusercontent.com/1329905/215998608-6ca41a4a-8dbb-42e5-a671-70a6ec59b547.png">

### Type of device

Browser

### Browser version

Safari 16.1

### Number of products impacted

1 first one this happens

**Comment by thestarsahil** [comment]
As I am seeing in the code 
**transform:rotate( )**   // tag is missing 

![Screenshot 2023-02-01 145928](https://user-images.githubusercontent.com/84167034/216006260-ba0f88f1-d66c-435f-a0f2-5c770f41511e.png)

**Comment by stephanegigandet** [comment]
@aleene I don't understand, is that an image you sent? or someone else? It looks the image was sent clipped, this is what we have on the server: https://nl.openfoodfacts.org/images/products/505/456/314/8445/1.jpg

**Comment by thestarsahil** [comment]
@stephanegigandet actually he is trying to say that the image he wants to see it's not in the proper position 
I mention the **tag** already to fix in the HTML File document 
Rotate option is missing

**Comment by alexgarel** [comment]
@aleene I can't reproduce. It seems to me that it was the thumbnail which was wrong (not the right image).

Did you have it again or can we close ?

**Comment by aleene** [comment]
can not reproduce
