### ISSUE TITLE
Hide by default the obsolete products withdrawn from the market

### ISSUE THREAD

**Issue by manon-corneille** [openfoodfacts/openfoodfacts-server#8078]
### Describe the bug

To avoid confusion for the consumers and from the producers, it would be great to **hide by default the products withdrawn from the market**, from the search results. 

These products could still be visible if scanned or requested by barcode. 

This behaviour would be desirable on both public platform and pro platform. 

Issue created following discussion with @stephanegigandet on [Slack](https://openfoodfacts.slack.com/archives/C02LDQDDD/p1675423981129889) 

 

### To Reproduce

-

### Expected behavior

-

### Type of device

Browser

**Comment by alexgarel** [comment]
:+1: for the Proposal 2 (move in a separate collection), it's always better to .

Later, (if needed), in search API we could provide a way to ask for this particular index or both (with [$unionWith](https://www.mongodb.com/docs/manual/reference/operator/aggregation/unionWith/#mongodb-pipeline-pipe.-unionWith)?).

**Comment by stephanegigandet** [comment]
I'm going to implement proposal 2 and create a new products_obsolete collection.
