### ISSUE TITLE
Add logo of the label "Bio Equitable en France" 

### ISSUE THREAD

**Issue by manon-corneille** [openfoodfacts/openfoodfacts-server#8083]
Story: #

Could we add the logo of Label Bio Equitable en France please? :)  
![LOGO_LABEL_BIO_EQUITABLE_EN_FRANCE](https://user-images.githubusercontent.com/104015489/217585311-1f76bff8-ea93-450e-adaf-986ed92d642a.svg)

Cheers

**Comment by alexgarel** [comment]
J'ai fait une PR.
