### ISSUE TITLE
[FOUNDATION] Create discover page (text, pictures, design)

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#81]
In progress: http://world.openfoodfacts.net/discover (off / off)

Missing the Re-uses section.

**Comment by stephanegigandet** [comment]
Discover page done for English.
Translated in French.

Other translations to be done:
http://en.wiki.openfoodfacts.org/Translations_-_Discover_page

**Comment by teolemon** [comment]
Fixed
