### ISSUE TITLE
No image url in the MongoDB dump

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#812]
Either add it or be more pedagogical on the Data page

```
looks like there's a bug inside the mongodb dump. There's no image_url in any of the document. ```

**Comment by JCBoorgo** [comment]
Hello! I would like to bump this issue, as it is still present. I am working with a team on an app using some of OFF's data and it would be awesome to be able to use the Mongo dumps, but not having the image URLs is kind of a hurdle. Is there any way to help? I don't know much about the inner workings of Mongo but I figure it has to be achievable if I dig enough into it. Thank you!

**Comment by gl-pasci** [comment]
Can't find anywhere in the docs but the image URIs seems to have the structure

`https://world.openfoodfacts.org/images/products/000/000/000/0000/{name}.{width}.{?version].jpg`

where the 0s are the product code split by slashes and the rest is extracted from the product images array.

What's the preferred way to use such images? Is hotlinking allowed?

**Comment by Thomas-Heniart** [comment]
Hi, this is issue is still present (January 2023). Is there any plan to solve it?

**Comment by alexgarel** [comment]
Hi @Thomas-Heniart I don't think we want to hardcode images in mongodb, so you must re-construct the url on your side.

But we could document it, at least, maybe here: https://openfoodfacts.github.io/openfoodfacts-server/reference/api/#get-/api/v2/product/-barcode--fields-images

And maybe we could add a js snippet for a mongodb query to transform imgid to image url.

To retrieve the image, you have to split the barcode ([see robotoff split_barcode](https://github.com/openfoodfacts/robotoff/blob/b13d5059b945e407e58c4168a6f91bb23bf4583c/robotoff/off.py#L154)) and use image id (imgid) and add .jpg.

**Comment by raphael0202** [comment]
How to construct image URLs is now documented: https://openfoodfacts.github.io/openfoodfacts-server/api/how-to-download-images/
