### ISSUE TITLE
Starch and polyols seem to be included in sugar

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#8124]
### Describe the bug

When looking at how we display starch and polyols in the product form, they seem included in the sugar:
![image](https://user-images.githubusercontent.com/562352/220044602-19d22d73-39e3-484c-a4bd-8a9c39718dd1.png)

Sugar, starch and polyols should be at the same level, under carbohydrates, isn't it?

We already have a data quality facet: [Nutrition - Sugars plus starch greater than carbohydrates](https://world.openfoodfacts.org/data-quality-error/nutrition-sugars-plus-starch-greater-than-carbohydrates).

Shouldn't we have one: `Nutrition - Sugars plus starch plus polyols greater than carbohydrates`?

### To Reproduce

eg. https://world.openfoodfacts.org/cgi/product.pl?type=edit&code=8410636000077

**Comment by aleene** [comment]
And sugars below carbohydrates. Polyols are not an energy source.

**Comment by CharlesNepote** [comment]
> And sugars below carbohydrates. Polyols are not an energy source.

Do you mean we should have:
```
Carbohydrates*
  - Sugar*
  - Starch
Polyols

* means always displayed in the form. Without * means it is displayed only if a 
   previous users has entered values.
```

or 

```
Carbohydrates*
  - Sugar*
  - Starch
  - Polyols
```

**Comment by aleene** [comment]
The first option. As I understand it a polyol does not provide an energy, so it should not be counted as a carbohydrate.

**Comment by CharlesNepote** [comment]
Generally, [polyols do provide energy](https://en.wikipedia.org/wiki/Sugar_alcohol#Sugar_alcohols_as_food_additives). In the INCO regulation, the formula of the energy (kcal) is:
`((carb - polyols)*4) + (polyols * 2.4) + (proteins * 4) + (fat * 9) + (fiber * 2) + (alcohol * 7)`

But the INCO regulation does not take into account that few polyols -- like erythritols -- provide zero calories.

As derived from sugar, shouldn't polyols be carbohydrates? [This table](https://en.wikipedia.org/wiki/Carbohydrate#Division) suggests polyols are carbohydrates.

So I would tend to choose the second option.
