### ISSUE TITLE
Link for windowsphone is dead

### ISSUE THREAD

**Issue by Cypresslin** [openfoodfacts/openfoodfacts-server#813]
http://www.windowsphone.com/en-us/store/app/openfoodfacts/5d7cf939-cfd9-4ac0-86d7-91b946f4df34

"We are sorry, the page you requested cannot be found. "

**Comment by teolemon** [comment]
@Cypresslin Do you have a Windows Phone device ? Could you find the app in the store ?

**Comment by teolemon** [comment]
@stephanegigandet Do we have the credentials to go see what's going on there ?

**Comment by Cypresslin** [comment]
@teolemon Sorry I don't, was just checking the link to see if I can replace it with a localized one.

**Comment by teolemon** [comment]
@Cypresslin This has been fixed. The app had been unpublished, now it's up again.
