### ISSUE TITLE
The API examples are not working

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#8134]
### What
- The API examples are not working
- https://openfoodfacts.github.io/openfoodfacts-server/reference/api/#get-/api/v2/product/-barcode-
- Click Try
```
Uncaught (in promise) TypeError: Failed to construct 'Request': Request cannot be constructed from a URL that includes credentials: https://off:off@world.openfoodfacts.net/api/v2/product/3017620422003
    at ie.onTryClick (api-request.js:1143:1)
    at ee.handleEvent (rapidoc-min.js:2:14156)
```

**Comment by alexgarel** [comment]
Sorry, wrong issue !

**Comment by raphael0202** [comment]
It works for .org though. It's because JS requests with embedded credentials are blocked by the browser. Maybe set .org server by default would solve this issue easily?

**Comment by alexgarel** [comment]
> Maybe set .org server by default would solve this issue easily?

I'm against it, because people will use it for write requests… without thinking.

**Comment by teolemon** [comment]
I believe this one is fixed.

**Comment by alexgarel** [comment]
Yes, we removed authentication for API on .net.
