### ISSUE TITLE
The includes and their translations have not been deployed for Nova Groups pages

### ISSUE THREAD

**Issue by Sarazine131** [openfoodfacts/openfoodfacts-server#8148]
### Describe the bug

The Nova Group pages seem to not be loading right, regardless of the amount of time I've tried, they aren't loading especially the fresh one, lots of information is missing. 

### To Reproduce

https://fr.openfoodfacts.org/nova
https://world.openfoodfacts.org/nova

### Expected behavior

The pages should fully load and display the calculus methodology

**Comment by teolemon** [comment]
This is because the includes and their translations have not been deployed for Nova Groups pages. I'll try to fix it in openfooodfacts-web

**Comment by teolemon** [comment]
@Sarazine131 this PR should fix it once it's approved and deployed: https://github.com/openfoodfacts/openfoodfacts-web/pull/380

**Comment by Sarazine131** [comment]
Hello @alexgarel, it is okay, we can close :).
