### ISSUE TITLE
Facet knowledge panel: replace data-quality items by data-quality-errors items

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#8158]
### Describe the bug

While facet knowledge panel is a good idea, the data quality information does not make sense and is even counterproductive.
![image](https://user-images.githubusercontent.com/562352/222533598-0e81ed81-94a8-4ea0-a359-92cd6ca80db6.png)

* The proposed 3 issues are not understandable by the majority of the users
  * Even if the user click on `87503 products with Food groups 3 unknown` he will have many products without any idea of what they are. "What is this Food groups 3???"
* The 3 issues (and `data quality` link) often leads to false positive or issues that can't be solved (eg. for products without the image).
* Sometimes the data quality information won't be issues, as said, but only information. "`EcoScore - extended data computed`: is this an issue? Do I have to take care about it? What can I do?"
* The link `data quality` is counterproductive:
  * It lists dozens, say thousands, of so-called "data quality issues" (which are not in the majority)
  * It mixes real data quality issues, that the user could manage, warnings (mostly composed of false positives), and information (`Nutrition value under 0‚1 g salt` ("Is it an issue I must take care of???").
  * It's discouraging to see all these quality problems that we don't understand.
  * The user may think that there are a lot of problems with the data (when in fact there are not that many).

Let's take another "data quality" link example from a "small" contributor:
![image](https://user-images.githubusercontent.com/562352/222540204-b79abb50-7964-4611-b5a8-526fe4d65e35.png)

What information can he get from this list? The majority of these links are just information that he won't understand (look at the three first lines!) or things we won't care about. The real problems that it could fix are at the bottom of this list! (not on this image).

### Expected behavior

A smart thing could be to restrict to `data-quality-issues` which are real issues, without false positives, that the user can really fix.

**Comment by alexgarel** [comment]
@sumit-158 I think this is a fix to be done on facets-knowledge-panels side. 

(use `data-quality-errors` instead of `data-quality` for the URL)

Do you want to take it ?

**Comment by sumit-158** [comment]
@alexgarel  You mean to say use "https://world.openfoodfacts.org/category/en:beers/data-quality-errors.json" instead of just "data-quality" ?

**Comment by sumit-158** [comment]
This Pr Should solve this!

**Comment by alexgarel** [comment]
@sumit-158 merged and tested on staging, works perfectly.

I launch a release.

**Comment by alexgarel** [comment]
hum… wrong prefix in PR did not trigger release please (no release for a refactor).

I had to make a new PR: https://github.com/openfoodfacts/facets-knowledge-panels/pull/101

**Comment by alexgarel** [comment]
Deployed.

**Comment by CharlesNepote** [comment]
Thank you so much @sumit-158 and @alexgarel!
