### ISSUE TITLE
Idea: Create a recycling taxonomy that takes into account location

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#816]
### What

- It seems each country has it's own recycling approach. On packaging we see often different instructions for different countries. We have not yet found a good way to transcribe these instructions into the packaging-field. And the instructions are always the same. 
- Seems a good idea to create a recycling taxonomy. This taxonomy should list all the countries, per country the recycling possibilities and per possibility what can be recycled. The latter should refer to the packaging taxonomy.
- If needed a country can be subdivided in regions or smaller entities.
- The required info can be gathered from the packaging.

### Part of
- #5502

**Comment by teolemon** [comment]
https://en.wiki.openfoodfacts.org/Global_packaging_taxonomy#Recycling_instructions

**Comment by aleene** [comment]
That is more a translation approach, which is also needed.

**Comment by aleene** [comment]
too old
