### ISSUE TITLE
Allow users to be removed while keeping moderation capabilities

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-server#8164]
We want users to be able to remove their accounts without any moderator intervention. This is more inline with GDPR and this avoid loosing time on this.
But right now, we do this manually because we want to insure user did not vandalise products, as with account deletion, we loose the changeset.

To change it, we want to keep a unique userid for the changeset (so that we can visualize changes). This enables us to let people delete their account themselves.

- [ ] change account deletion procedure, so that instead of attributing changes to "openfoodfact-contributors" we attribute them to "anonymous-HASH" where HASH is a random hash (with reasonable collision probability)
- [x] implement an account deletion page accessible to all users (should be accessible from profile page, but a distinct page, with a proper explanation on consequences and a confirmation, beware to only enable a user to remove his own account)

### Part of
- #5809 

Better do this in conjunction with:
- #8270

**Comment by oyenuga17** [comment]
Please i am interested in the issue

**Comment by oyenuga17** [comment]
Please assign me to the issue

**Comment by oyenuga17** [comment]
Please unassign me @alexgarel I am unable to do it

**Comment by john-gom** [comment]
Ability for users to delete their own account is in separate issue #6435
