### ISSUE TITLE
<p> tags are display none in the CSS for Static pages

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#8188]
### What
<p> tags are display none in the CSS for Static pages
I was beginning to doubt my sanity during deployment, when I realized ```< p >``` tags are display none in the CSS for Static pages
![image](https://user-images.githubusercontent.com/1689815/224719645-f5c656ca-0d4b-433d-bcb1-588a39b42d50.png)

#### Happens on the NOVA page
https://world.openfoodfacts.org/nova

#### Does not happen on the Nutri-Score page
https://world.openfoodfacts.org/nutriscore

```
#main_column>h1, #main_column>p, .top-bar-section .has-dropdown.moved>a:after {
    display: none;
}
```

**Comment by alexgarel** [comment]
It was introduced by https://github.com/openfoodfacts/openfoodfacts-server/pull/7703

**Comment by alexgarel** [comment]
It was introduced by new design commit : 7e52e7a8f97

I'm not sure why this rule exists …

**Comment by alexgarel** [comment]
Fixed by https://github.com/openfoodfacts/openfoodfacts-server/pull/8192
