### ISSUE TITLE
Update Facebook group URLs

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#819]
We got more beautiful URLs

 
https://www.facebook.com/groups/openfoodfacts
https://www.facebook.com/groups/openfoodfacts.fr
https://www.facebook.com/groups/openbeautyfacts.fr
https://www.facebook.com/groups/openbeautyfacts

**Comment by muskangarg21** [comment]
@teolemon how do you want this to be applied to the website?
We can give 2 links, one for English other for french on each of the pages in `lang/<cc>/texts/contribute.html`  and `lang/obf/<cc>/texts/contribute.html`by running a script.
Thanks

**Comment by stephanegigandet** [comment]
@muskangarg21 : I'm not sure what this bug refers to. It may have been fixed already, I think it is referring to the links in the footer of each page of the web site.  Can you clarify @teolemon?

**Comment by teolemon** [comment]
This has been fixed @muskangarg21 👍 
Thank for investigating it, I will be closing this issue.
