### ISSUE TITLE
Unlocalized string on the pro platform

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#8194]
### What

- [ ] Unlocalized string on the pro platform
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/blob/eaa18b8627e76de60bc64380bd714fce8417f656/templates/web/pages/product_edit/product_edit_form_display.tt.html#L28

### Part of
- #5521

**Comment by yuktea** [comment]
This should be straightforward. We'll need to assign an `id` (some identifier) for the string and pass the ID through the `lang()` function + add the original string with it's corresponding `id` to the language files. 

added the `good-first-issue` tag 👍

**Comment by jnsereko** [comment]
hey @yuktea 
this is really an awesome issue.  I wish to push a fix for this

**Comment by jnsereko** [comment]
PR:  https://github.com/openfoodfacts/openfoodfacts-server/pull/8203
