### ISSUE TITLE
2 exact same packaging components added through API are conflated into one

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#8197]
In the API (but not in the web site), adding exactly the same packaging components twice does not work, only one is kept.
This is the case also if one component is compatible with another component (e.g. 1 metal can + 1 steel can will result in 1 steel can).

**Comment by oyenuga17** [comment]
Please assign it to me @stephanegigandet  

Please i also have difficulty in joining the slack channel ..

**Comment by oyenuga17** [comment]
@stephanegigandet Alright! thank you for noting that instead of having to struggle with it ..

**Comment by stephanegigandet** [comment]
fixed by https://github.com/openfoodfacts/openfoodfacts-server/pull/8207
