### ISSUE TITLE
[FOUNDATION] Create contribute page (text, pictures, design)

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#82]
Similar to Discover page, lists all the possible ways of contributing to the project.

**Comment by stephanegigandet** [comment]
Draft done for English: http://world.openfoodfacts.info/contribute

Suggestions?

We could add some illustrations / icons, like the Discover page, but we can always do it later.

**Comment by teolemon** [comment]
Fixed
