### ISSUE TITLE
Bring Robotoff and Hunger Games to the Producer Platform

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#8202]
### What
- Bring Robotoff Questions (on-page) and Hunger Games to the Producer Platform private space, so that producers can validate suggestions and export Robotoff assisted edits as protected edits.

### Part of
- #5521 
- https://github.com/openfoodfacts/robotoff/issues/374

**Comment by teolemon** [comment]
- @raphael0202  is tackling part of this in #8319

**Comment by manon-corneille** [comment]
Related to https://github.com/openfoodfacts/openfoodfacts-server/issues/5673

**Comment by manon-corneille** [comment]
Connected to https://github.com/openfoodfacts/openfoodfacts-server/issues/8486 so I close this issue
