### ISSUE TITLE
incron does not exists in Debian Bullseye

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-server#8209]
We currently rely on incron to send images to OCR. See `scripts/process_new_image_off.sh`.

But it is not available in Bullseye.From [this thread](https://github.com/piku/piku/issues/220), we can understand it was removed because of a [core dump issue](https://github.com/ar-/incron/issues/36). 

The piku thread also propose to move to [systemd path](https://www.freedesktop.org/software/systemd/man/systemd.path.html), but we could move to a classical [inotify listener script](https://metacpan.org/pod/Linux::Inotify2).

I think first option is good to explore first, as it might be more robust and easy to setup in prod.

**Comment by alexgarel** [comment]
I did some search and did not find any good alternative: fswatch is cumbersome, inotify-tools does not provide a tool for that use case, inotify-hookable, entr, iwatch or systemd-path do not provide changed file as arguments.

On the other side, writing a script using the [Linux::Inotify2](https://metacpan.org/pod/Linux::Inotify2) is quite straight forward and would have the advantage of not reloading perl interpreter, and all taxonomy, etc. each time. So much more efficient.

But first, I would like to verify with @stephanegigandet if this thing is really needed !

**Comment by stephanegigandet** [comment]
@alexgarel Instead of watching the file system to see if a new image is available, an alternative would be to actively add the image to a queue (e.g. in a minion queue, or a redis list or stream), and then have a separate service call the Google Cloud Vision API.

**Comment by alexgarel** [comment]
Ok, I think for now we can inotify2, because we will have to do that also for sibling projects" so it's easier to just keep same approach.

Later we can go for redis streams.

**Comment by stephanegigandet** [comment]
Sounds good.
