### ISSUE TITLE
Add the logo for the Swedish label "A-market"

### ISSUE THREAD

**Issue by manon-corneille** [openfoodfacts/openfoodfacts-server#8212]
### Describe the bug

Would be great to add the logo for the A-market label :-) 

![Ä-märket 85x90](https://user-images.githubusercontent.com/104015489/225334401-41f373ae-8ba4-4120-8414-2d61bb35b81e.png)

### To Reproduce

.

### Expected behavior

.

### Type of device

Browser

**Comment by benbenben2** [comment]
Previous pull request: https://github.com/openfoodfacts/openfoodfacts-server/pull/7957
