### ISSUE TITLE
Update logo of the label V-label 

### ISSUE THREAD

**Issue by manon-corneille** [openfoodfacts/openfoodfacts-server#8214]
### What

Update the logo of the V-label VEGAN and VEGETARIAN (will be added soon) 

<img src="https://user-images.githubusercontent.com/104015489/225374947-3c18e75a-a8b2-4f4f-8611-2f01b54abcf0.png" height="400px">

### Part of
- #5529

**Comment by manon-corneille** [comment]
And the 2 logos for the vegetarian label : 
* Végétarien → French 
* Vegetarian → English 

![v-label-vegetarian-color-1](https://user-images.githubusercontent.com/104015489/225390048-395ed398-fc35-4aae-814f-ce5e13756c8d.png)
![v-label-vegetarien-color](https://user-images.githubusercontent.com/104015489/225390057-31b02567-dadc-42e8-b8fa-f4dec3e60d9e.png)

**Comment by SmitaTripathi** [comment]
Hello mam @manon-corneille, can I get this issue fixed?

**Comment by thestarsahil** [comment]
> ### What
> Update the logo of the V-label VEGAN and VEGETARIAN (will be added soon)
> 
> <img alt="" height="400px" src="https://user-images.githubusercontent.com/104015489/225374947-3c18e75a-a8b2-4f4f-8611-2f01b54abcf0.png">
> 
> ### Part of
> * [What can I work on ? #5529](https://github.com/openfoodfacts/openfoodfacts-server/issues/5529)

In which section which want to update this logo?

**Comment by SmitaTripathi** [comment]
vegan section sir

**Comment by thestarsahil** [comment]
@SmitaTripathi that's the part I know dear I mean to say in the code section

**Comment by thestarsahil** [comment]
@alexgarel  Done I added the logo in this section 
openfoodfact-server\openfoodfacts-server\html\images\lang\hr\labels

**Comment by thestarsahil** [comment]
I push on main branch sir ✅
