### ISSUE TITLE
Advanced Search CSV export does not work in the Platform for Producers

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#8243]
### What
- Advanced Search CSV export does not work in the Platform for Producers
- Solving it would enable scientific research with scraped data to move forward (they could redownload their uploads with scores, without the problematic of having to import data they (and we) don't own into Open Food Facts.

### Part of
- #5521

**Comment by manon-corneille** [comment]
Tested and it works :)
