### ISSUE TITLE
Foreign language suggestion popups no longer work

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#8257]
### Describe the bug

Foreign language suggestion popups no longer work.

### To Reproduce

For instance go to https://world.openfoodfacts.org/product/5056357904626/mars-aufstrich and start edit mode. Start to fill `nl:Smeerbare` as a category.

Nothing happens.

### Expected behavior

A list of dutch suggestions should appear.

### Type of device

Browser

### Browser version

Safari

**Comment by stephanegigandet** [comment]
@jnsereko is working on this issue

**Comment by aleene** [comment]
seems done
