### ISSUE TITLE
Add the Pro platform in Matomo 

### ISSUE THREAD

**Issue by manon-corneille** [openfoodfacts/openfoodfacts-server#8260]
It would be great to have some analytics about the pro platform in Matomo

**Comment by alexgarel** [comment]
Done now :-)

* added the site in matomo
* edited the `/srv/off-pro/lib/ProductOpener/Config2.pm` section `$google_analytics` variable to add Matomo js snippet.
* restarted the service: `sudo systemctl restart apache2@off-pro`
