### ISSUE TITLE
docs: Edit spellling errors in Read.md files

### ISSUE THREAD

**Issue by oyenuga17** [openfoodfacts/openfoodfacts-server#8264]
#### Correct the spelling mistake in 

 -How-to-learn-Perl.md
-explain-packaging-data.md
-explain-taxonomy-build-cache.md
-how-to-update-agribalyse-ecoscore.md

**Comment by oyenuga17** [comment]
I would love to fix this issue

**Comment by alexgarel** [comment]
Go @oyenuga17 :-)
