### ISSUE TITLE
Sulfates and nitrates are not in the nutrients' list

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#8265]
### Describe the bug

Most (the majority?) of the waters do display sulfates' quantity, and sometimes Nitrates, in the nutrients' table. Eg.
* https://world.openfoodfacts.org/product/8437019482329/aqua-sierra-nevada
* https://world.openfoodfacts.org/product/8413432015009/agua-mineral-natural-agua-de-chovar
* https://world.openfoodfacts.org/product/3245390083173/bidon-5l-eau-de-source-montagne-grand-jury
* ...

### To Reproduce

Edit https://world.openfoodfacts.org/product/8437019482329/aqua-sierra-nevada and try to add `Sulfates`.

### Expected behavior

The display-as-you-type should provide `Sulfates` with `mg` unit (alternative English spelling `sulphate` (UK)).

I guess it should be in the singular form: `Sulfate`, `Nitrate`.

The field should also be exported in the daily CSV exports.

### Type of device

Browser

**Comment by benbenben2** [comment]
See following PR: https://github.com/openfoodfacts/openfoodfacts-server/pull/8323

> The field should also be exported in the daily CSV exports.

Is this related to the nutriments_tables subroutine called in Export.pm and defined in Food.pm?

**Comment by aleene** [comment]
There is a file somewhere where is defined which nutrients are exposed to the user. Have to look it up. These ones are indeed needed for mineral waters.
