### ISSUE TITLE
Add a config file for deep links on mobile apps

### ISSUE THREAD

**Issue by g123k** [openfoodfacts/openfoodfacts-server#8275]
Hi everyone,

On the mobile app, we will implement the deep link feature anytime soon (https://github.com/openfoodfacts/smooth-app/issues/920).

For that, we have to host a file at `https://openfoodfacts.org/.well-known/assetslinks.json` which will look like this:

```
[{
  "relation": ["delegate_permission/common.handle_all_urls"],
  "target": {
    "namespace": "android_app",
    "package_name": "com.mycompany.app1",
    "sha256_cert_fingerprints":
    ["14:6D:E9:83:C5:73:06:50:D8:EE:B9:95:2F:34:FC:64:16:A0:83:42:E6:1D:BE:A8:8A:04:96:B2:3F:CF:44:E5"]
  }
}]
```

Could you please guide me on where I should put this file in the repo?

Thanks :)

**Comment by alexgarel** [comment]
@g123k I think you just have to put it in html/.well-known folder.

Do you agree @stephanegigandet ?

**Comment by stephanegigandet** [comment]
@g123k That's correct, just put it in html/.well-known

**Comment by teolemon** [comment]
Given the potential upside, I'm bumping the priority to P0 @stephanegigandet @alexgarel @g123k
