### ISSUE TITLE
How should we handle obsolete products for robotoff

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-server#8283]
We now put obsolete products in their own collection: 
- see issue: #8078
- and corresponding PR #8277

They are still accessible with a specific parameter or invoking the right collection.

What should we do ?
* add support for obsolete parameter in robotoff ?
* avoid notifying robotoff on obsolete parameters ?

**Comment by raphael0202** [comment]
Are obsolete product can still be updated?
I suggest we don't keep any prediction/insights for obsolete products in Robotoff.

**Comment by stephanegigandet** [comment]
> Can obsolete products still be updated?

Yes.

**Comment by alexgarel** [comment]
@raphael0202 I would keep insight, as we are also an encyclopedia of food, and it may matter having old food completed.

**Comment by raphael0202** [comment]
@alexgarel Then we need a special handling for obsolete products on Robotoff side, as they're not in the "products" collection anymore: when the product is deleted we delete associated insights and predictions.

**Comment by alexgarel** [comment]
@raphael0202 did you solved that ?

**Comment by raphael0202** [comment]
No I didn't. There is already an issue on Robotoff repo, so I'm closing this one.
