### ISSUE TITLE
Bug on staging: can't insert nutrition facts because of image div

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-server#8287]
Editing a product on https://world.openfoodfacts.net, you can't enter nutrition facts.

It seems there is a div above the nutrition table disabling access to the box.

[Kooha-2023-04-05-10-55-02.webm](https://user-images.githubusercontent.com/144788/230032528-f763a793-3368-40ea-92e0-ef8615c245a2.webm)

**Comment by alexgarel** [comment]
Maybe only apply if there is no nutrition images.

**Comment by alexgarel** [comment]
It's linked to power user script...

**Comment by stephanegigandet** [comment]
@alexgarel This div is needed to display the nutrition image next to the table, to make it easy to see the values while typing them.
e.g. it should look like this:
![image](https://user-images.githubusercontent.com/8158668/230596610-f5162858-35d9-4a77-89bb-c35c83d42c49.png)

But the z-index completely hides the image.

**Comment by stephanegigandet** [comment]
Re-closing this bug and opened a new bug for clarity: https://github.com/openfoodfacts/openfoodfacts-server/issues/8292
