### ISSUE TITLE
Consistently getting 504 Gateway timeout error when trying to access categories taxonomy

### ISSUE THREAD

**Issue by prateekshac1** [openfoodfacts/openfoodfacts-server#8289]
### Describe the bug

Calling "https://world.openfoodfacts.org/categories.json" is consistently timing out. I used to be able to access it successfully up to about a month ago.

FYI: I'm accessing it from the US. 

Is there a way to paginate and access this data in chunks? Or any other recommended way to get the category taxonomy?

### To Reproduce

1.   Call "https://world.openfoodfacts.org/categories.json" either from a browser or command line.
2.  Errors out after a min.

### Expected behavior

Expect to see a json response, even if it takes a bit longer.

### Type of device

Browser

**Comment by alexgarel** [comment]
Hi @prateekshac1 I don't know what you are trying to achieve. The url you use is to get statistics on categories. 

In this time frame we are migrating the infrastructure to a new service and our MongoDB is on a temporary instance which is under high pressure.

If what you need is the list of categories you can better get it by using https://static.openfoodfacts.org/data/taxonomies/categories.json

We also have a suggest API if needed: https://openfoodfacts.github.io/openfoodfacts-server/api/ref-v2/#get-/cgi/suggest.pl

**Comment by prateekshac1** [comment]
Hi @alexgarel . I just needed a list of all categories. This static api should work very well i believe. Thank you for your prompt response, and for this excellent initiative.

**Comment by prateekshac1** [comment]
@alexgarel , took a look at both the apis. The static one is useful. But, without the popularity information, it's hard to prioritize the top categories. We have a bit of manual processing that follows, which we want to focus only on the top categories. Is there a rough ETA on when the MongoDB will stabilize? Alternately, is there perhaps a one time data dump of the dynamic categories api that you could share? I don't necessarily care about the exact numbers, just want a rough sense of popularity.
