### ISSUE TITLE
Nutrition photo is not shown next to nutrition table in product edit form

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#8292]
There should be a copy of the nutrition image next to the nutrition table, but a recent fix to https://github.com/openfoodfacts/openfoodfacts-server/issues/8287 made the image invisible.

![image](https://user-images.githubusercontent.com/8158668/230596610-f5162858-35d9-4a77-89bb-c35c83d42c49.png)

**Comment by alexgarel** [comment]
Fixed.
