### ISSUE TITLE
URLs with a product page number return an invalid request error message

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#8304]
From Slack:

Food Facts
  [il y a un jour](https://openfoodfacts.slack.com/archives/C02KVRT2C/p1680895593150679?thread_ts=1680865992.766959&cid=C02KVRT2C)
Is "Error Invalid address" for all kinds of pages a side effect of this update too? The timing is suspicious. Pages like [this](https://world.openfoodfacts.org/store/lidl/2) one, [this](https://world.openfoodfacts.org/brand/danone/3) one or any other stopped working.

**Comment by alexgarel** [comment]
Hot fixed by @stephanegigandet !
