### ISSUE TITLE
Petfood trace elements

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#831]
### What
- I found an ingredient list, where the original molecules of traces are also listed.
![09e7b5c3-1a7a-4460-9ac5-8504f825d3b2](https://user-images.githubusercontent.com/1329905/26847114-2a2ae2ac-4afc-11e7-86d7-cf8e6660fafe.jpg)

- It would be nice if these could be added to the nutrients somehow. Part of the hierarchy?
- Is it possible to the calculations from molecule to trace and viceversa?

### Part of
- #5536

**Comment by teolemon** [comment]
What is the real story here ? Why are they putting this information ?
There must be something fishy.

**Comment by aleene** [comment]
Most dietary minerals are added as compounds. So it is nice to know which compounds to use. The question is more why is it not noted as such in human food. I assume they use the same compound for each mineral, but that is something OPFF can check.

And I noticed that the animal foods I added have all additives. Guess the animal food is not a very complete meal.

**Comment by aleene** [comment]
An example where they do not bother to transform to actual traces:
![img_7480](https://user-images.githubusercontent.com/1329905/27260188-eddbe17e-5425-11e7-94f4-d493eff0a7ea.JPG)

**Comment by aleene** [comment]
This can be added to the nutriments taxonomy.

**Comment by aleene** [comment]
too old
