### ISSUE TITLE
Add a new label "Zero résidu de pesticides" 

### ISSUE THREAD

**Issue by manon-corneille** [openfoodfacts/openfoodfacts-server#8311]
Add a new label zero-residu-de-pesticides please :-) 

Read more about the label: https://www.nouveaux-champs.fr/label-zero-residu-de-pesticides/

Image below: 

![zero-residu-de-pesticides 77x90](https://user-images.githubusercontent.com/104015489/231182126-4418baa1-304d-4e6a-ae34-b2ae5fa00212.png)

**Comment by benbenben2** [comment]
Fixed: https://github.com/openfoodfacts/openfoodfacts-server/pull/8315

**Comment by manon-corneille** [comment]
Amazing, thanks @benbenben2
