### ISSUE TITLE
Add products_obsolete to mongo export and JSONL

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-server#8338]
After the move of obsolete products to their own collection we MUST change mongodb_dump.sh to include a dump of products_obsolete.

**Comment by raphodn** [comment]
This might be done ? After discussion today, there seems to be a https://static.openfoodfacts.org/data/openfoodfacts-products_obsolete.jsonl.gz dump (24k products).

Creating an issue in `openfoodfacts-python` :)

**Comment by alexgarel** [comment]
Yes, this was done in commit c22fc420b91d !
