### ISSUE TITLE
Japanese full width parenthesis not recognised

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#8345]
### Describe the bug

The ）and （ are not recognised as parenthesis

### To Reproduce

https://jp.openfoodfacts.org/cgi/product.pl?type=edit&code=0682335900097

### Expected behavior

Handles it is  normal parentheses.

U+FF08 and U+FF09

### Type of device

Other

**Comment by Naruyoko** [comment]
Another example: https://jp.openfoodfacts.org/%E8%A3%BD%E5%93%81/4901360245567/%E3%82%A2%E3%83%AB%E3%83%95%E3%82%A9%E3%83%BC%E3%83%88%E3%83%9F%E3%83%8B%E3%83%81%E3%83%A7%E3%82%B3%E3%83%AC%E3%83%BC%E3%83%88-bourbon?rev=27

(Also contains unrecognized full width slash "／")

**Comment by benbenben2** [comment]
Interestingly, parenthesis are already found in https://github.com/openfoodfacts/openfoodfacts-server/blob/main/lib/ProductOpener/Ingredients.pm

Using this website: https://www.coderstool.com/unicode-text-converter
（ -> \uff08 -> already found in $obrackets
） -> \uff09 -> already found in $cbrackets
／ -> \uff0f -> not found 

For the slash, in other languages it is not used as a parser as well (for example in Croatia, it is common to have ingredients list of both Croatian and Bosnian together where small language variation would be differentiated by the slash sign (for example, for salt: sol/so). In that case, it needs to be fixed manually after extraction). In your case, in Japanese, are both words that are left and right of the slash, synonyms?

For parenthesis, I suspect that at least 1 of the ingredients - either the ones in parenthesis or the other ones - is unknown, and that leads to all being highlighted. Don't know if we could rule out this suspicion with more examples with parenthesis in Japanese.

**Comment by Naruyoko** [comment]
One of the ingredients is indeed missing from the taxonomy, and the same for other examples I could quickly find from the ingredients list. Does it not split when one or more of the ingredients are unknown?

Slash is just one option for manufacturers to separate ingredients from additives. [Ref. p21 of this pamphlet](https://www.caa.go.jp/policies/policy/food_labeling/information/pamphlets/assets/food_labeling_cms202_230324_02.pdf).

**Comment by hangy** [comment]
As noted by @benbenben2, we have `$obrackets` and `$cbrackets`. However, it's not used consistently, eg: https://github.com/openfoodfacts/openfoodfacts-server/blob/e0f97b6aa369f09358874e7a71581a59461f4156/lib/ProductOpener/Ingredients.pm#L1286

> For the slash, in other languages it is not used as a parser as well (for example in Croatia, it is common to have ingredients list of both Croatian and Bosnian together where small language variation would be differentiated by the slash sign (for example, for salt: sol/so). In that case, it needs to be fixed manually after extraction). In your case, in Japanese, are both words that are left and right of the slash, synonyms?

The other slashes are used by some subs like `normalize_enumeration` and `normalize_allergens_enumeration`, though: https://github.com/openfoodfacts/openfoodfacts-server/blob/e0f97b6aa369f09358874e7a71581a59461f4156/lib/ProductOpener/Ingredients.pm#L3285
Also, the latter doesn't seem to use `$obrackets`/`$cbrackets`: https://github.com/openfoodfacts/openfoodfacts-server/blob/e0f97b6aa369f09358874e7a71581a59461f4156/lib/ProductOpener/Ingredients.pm#L3406

**Comment by benbenben2** [comment]
Thank @hangy for the inputs :+1: 

`For parenthesis, I suspect that at least 1 of the ingredients - either the ones in parenthesis or the other ones - is unknown, and that leads to all being highlighted. Don't know if we could rule out this suspicion with more examples with parenthesis in Japanese.`

For the first example given by Aleene, I tried in dev to replace unknown ingredient in the first しょうゆ（本醸造）by any known ingredient in the taxonomy しょうゆ（たまり）. It remains unknown. 
Also, we can see that the parsing of ingredients in parenthesis is not as expected because 糖類（ぶどう糖果糖液糖, 水あめ, 砂糖）leads to 1/ 糖類（ぶどう糖果糖液糖  2/ 水あめ  and 3/ 砂糖）(it is parsed only by the comma)
**Conclusion:** we can ignore my previous comment about parenthesis.
