### ISSUE TITLE
Move "ingredients" translation to specific strings? 

### ISSUE THREAD

**Issue by hangy** [openfoodfacts/openfoodfacts-server#836]
We have several strings that are about ingredients (`image_ingredients`, `image_ingredients*`, `ingredients*` but also `origins*`)  or contain "ingredients" (for example `product_description` `product_js_extract*_ingredients` or `product_js_upload_image_note`). I think those might need to be moved from `common.pot` to `openbeautyfacts.pot` etc.

The reason is that the English "ingredients" translates differently to German (and probably other languages) based on content. Technically, using the previous "Inhaltsstoffe" translation for Open Food Facts, Open Beauty Facts and Open Pet Food Facts would be OK. However, all food labels in Germany use the more accurate "Zutaten" translation. That's much better for food products, but completely incorrect for all beauty products.

What do you think? Is there a similar situation for other languages?

**Comment by teolemon** [comment]
No problem with that. You just need to add the string to the obf or opff file, and it will override common. No need to delete the original one, AFAIK

**Comment by hangy** [comment]
OK that would be cool. Do you know if Crowdin supports that?

**Comment by teolemon** [comment]
You do the string modifications in the source code, and Crowdin will pick
from there.
