### ISSUE TITLE
Pantothenic acid is sometimes also referred as vitamin B5

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#8388]
### Describe the bug

It should be put as a synonym in the nutrients' taxonomy.

### To Reproduce

Eg. https://world.openfoodfacts.org/cgi/product.pl?type=edit&code=3533630093793

Vitamin B5 is also used in English.

**Comment by aleene** [comment]
Do you mean in english or also other languages?

**Comment by CharlesNepote** [comment]
Yes I would like to have it displayed in the form's list of nutrients in "edit" mode.
Either `Vitamin B5 (pantothenic acid)` or `Pantothenic acid (vitamin B5)`.

**Comment by CharlesNepote** [comment]
Thanks a lot @benbenben2 !
