### ISSUE TITLE
The placement of mono and polyunsaturated fat is wrong

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#8396]
### What

The placement of mono and polyunsaturated fat is wrong

### To Reproduce

https://world.openfoodfacts.org/product/0073210000139/extra-virgin-olive-oil-star

### Expected behavior

Should appear under a heading `Unsaturated fat`

### Screenshots

<img width="572" alt="Screenshot 2023-05-04 at 15 00 33" src="https://user-images.githubusercontent.com/1329905/236212259-2c706230-01d8-4d7c-9797-114cb0aa11b7.png">

**Comment by shahnawazpatel23** [comment]
hey members, i am new to open source and i wanna contribute to this project, it would be very helpful if you allow me to work on this issue and let me know more about this issue

**Comment by shahnawazpatel23** [comment]
please let me know how to fix this issue and what the issue is

**Comment by alexgarel** [comment]
Hi @shahnawazpatel23 and welcome :-)

It's closely related to https://github.com/openfoodfacts/openfoodfacts-server/issues/8395

You might start looking at product_edit_form_display.tt.html, and data_to_display_nutrition_table in Display.pm (yes it could be refactored in smaller chunks !).

**Comment by owais0017** [comment]
i got it. it looks like a simple fix. Can you please assign it to me?

**Comment by alexgarel** [comment]
@owais0017 declaring you are doing it is enough :-)

**Comment by owais0017** [comment]
Thanks. Will resolve it as soon as possible

**Comment by aleene** [comment]
repaired in #9569
