### ISSUE TITLE
[FOUNDATION] Create new index text

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#84]
Text shown at the top of the page on the root of each country (e.g. fr.openfoodfacts.org).

It should be shorter than the current text (too much text, scary). Instead it should link to the Discover and Contribute pages.

**Comment by stephanegigandet** [comment]
Current text, for reference:

Help us to collect information and data (ingredients, nutrition facts etc.) on food products from all around the world. In a few minutes, you can easily add products and contribute to improve food for everyone.

The collected data is then usable and reusable freely:

To help you to make better choices

to decipher labels: which food additives should you avoid?
to compare products and to find better alternatives
to find products that do not contain (or contain less) substances that you want to avoid: fat, salt, additives, allergens etc.

To motivate the industry to offer better products

by grading products and publishing nutritional comparisons.
by checking allegations like "25% less sugar/salt/fat than other products from the same category".

To help research

by combining the data with other data, researchers can find correlations and try to establish the link between some ingredients and affections.

... and for all the other uses we have not thought about! By making this data publicly available for free and for all uses, you are not limited by our imagination, and people from all around the world will find thousand of usage ideas that we would never have thought about.

Got ideas? Share them on the Idea Forum!

**Comment by stephanegigandet** [comment]
In progress.

````
<h1>Open Food Facts</h1>

<div class="row hide-when-logged-in">

	<div class="medium-12 large-6 columns">
	
<h2>Discover</h2>

<p>Open Food Facts is a food products database made by everyone, for everyone.</p>
<p>You can use it to make better food choices, and as it is open data, anyone can re-use it for any purpose.</p>

<p><a href="/discover">Learn more about Open Food Facts</a></p>

	</div>
	
	<div class="medium-12 large-6 columns">

<h2>Contribute</h2>

<p>Open Food Facts is a non-profit project developed by thousands of volunteers from around the world.
You can start contributing by adding a product from your kitchen, and we have lots of
exciting projects you can contribute to in many different ways.</p>

<p><a href="/contribute">Learn more about how you can join us</a></p>

	</div>
</div>

<h2>Last products added:</h2>

<p>&rarr; <a href="/state/to-be-completed">products from the mobile app that need to be completed</a></p>

````

Comments or suggestions?

**Comment by aleksejrs** [comment]
This still hasn't been done at https://ru.openfoodfacts.org/
