### ISSUE TITLE
Bogus url in editor page

### ISSUE THREAD

**Issue by DanieliusAsm** [openfoodfacts/openfoodfacts-server#8421]
### Describe the bug

When I went to a profile/editor page of https://world.openfoodfacts.org/editor/kiliweb or https://world.openfoodfacts.org/editor/foodless I noticed that theres a bogus link like this:

[Products added by Foodless Android App](https://foodless/)

### To Reproduce

- https://world.openfoodfacts.org/editor/kiliweb
- click on [Products added by Yuka](https://kiliweb/)
- the url is **https://kiliweb/**

### Expected behavior

Im not sure whats to be expected here. There used to be:

- Products edited by ...
- Products photographed by ...

### Screenshots

![image](https://github.com/openfoodfacts/openfoodfacts-server/assets/22033222/44f640b5-ae63-47b1-8ba6-f1ae0d276666)

### Type of device

Browser

### Browser version

Chrome

**Comment by teolemon** [comment]
Related to the new deployment. It should link to https://world.openfoodfacts.org/contributor/xyz
