### ISSUE TITLE
504 Gateway Time-out when retrieving the ingredients

### ISSUE THREAD

**Issue by yangar** [openfoodfacts/openfoodfacts-server#8430]
### Describe the bug

https://world.openfoodfacts.org/ingredients.json
Return a 504 Gateway Time-out, i guess pagination should be implemented!

### To Reproduce

Try to load the following url: https://world.openfoodfacts.org/ingredients.json

### Expected behavior

The ingredients list

### Screenshots

![image](https://github.com/openfoodfacts/openfoodfacts-server/assets/5199021/646c7e12-8491-4289-bef9-5567ef8b354a)

### Type of device

REST-API

**Comment by alexgarel** [comment]
@yangar sorry but currently we have the mongodb on a temporary server which is undersized. I'm trying to work to migrate our infrastructure so that we resolve this.

**Comment by alexgarel** [comment]
Thanks to work of @raphael0202 on scrapping bots this should be somewhat available again (server migration still on the work).

**Comment by hangy** [comment]
Looks like this works fine after the server migration.

**Comment by teolemon** [comment]
Thanks @hangy for spotting. Closing as a result
