### ISSUE TITLE
The `Product` schema in OpenAPI does not work with code gen tools

### ISSUE THREAD

**Issue by VaiTon** [openfoodfacts/openfoodfacts-server#8449]
I'm trying to update the nodejs SDK, and I'm trying to use code generation for the OpenAPI schema. The problem is that this file does not produce a valid schema:

https://github.com/openfoodfacts/openfoodfacts-server/blob/7953dbc8f668378239d1bac4bb495e27d7e2a369/docs/api/ref/schemas/product.yaml#L1

### Solution
Remove the initial `Product:` and de-indent everything.

It works with that edit.

**Comment by alexgarel** [comment]
+1 @VaiTon, this was introduced by a contributor, to initially fix the compatibility !

There are some json ref to this file to correct, if you change that.
