### ISSUE TITLE
Manufacturing Place Search API

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#846]
It seems that it is not possible to do this:
http://en.openfoodfacts.org/manufacturing_place/brooklyn.json

**Comment by hangy** [comment]
I don't think any tag is actually linked with the underscore (even if the `<input>` field name differs). https://world.openfoodfacts.org/manufacturing-place/brooklyn.json works

**Comment by aleene** [comment]
Thanks, I missed that typo.
