### ISSUE TITLE
Warning explanation on nutriments is displayed under the nutrition image and not visible

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-server#8477]
### Describe the bug

If a user enters a wrong value for energy, the label explaining the warning on energy is hidden by the nutrition image.

### Expected behavior

The user should be able to see the text.

### Screenshots

![Capture d’écran du 2023-05-30 10-05-25](https://github.com/openfoodfacts/openfoodfacts-server/assets/144788/ced25e87-e00d-4c82-8028-ec37fb06c4d5)

### Browser version

Firefox 113.0.2

### Part of
- #8420

**Comment by alexgarel** [comment]
still there.

**Comment by TCatinaud** [comment]
Hello @alexgarel,
I would like to work on this issue, could you assign it to me please?

**Comment by alexgarel** [comment]
Hi @TCatinaud just signal you are working on it, it's enough.

**Comment by TCatinaud** [comment]
Thanks :)
