### ISSUE TITLE
Make it possible to subscribe to the pro newsletter

### ISSUE THREAD

**Issue by manon-corneille** [openfoodfacts/openfoodfacts-server#8505]
Story: #
Today, When a user creates an account on the Pro platform and ticks “Subscribe to the newsletter”, we do keep the info, but it's not used. 
As we are now publishing a newsletter every couple of months from SendinBlue, it would be good to allow users to subscribe to it. 

### Part of
- #5521 

<img width="886" alt="image" src="https://github.com/openfoodfacts/openfoodfacts-server/assets/104015489/0526f76e-ba17-4e47-8cee-d24921dcd5b8">

**Comment by stephanegigandet** [comment]
We use Brevo (which used to go by the name Sendinblue) to manage newsletters.

Here is the documentation for the Brevo API: https://developers.brevo.com/reference/createcontact

**Comment by teolemon** [comment]
Could this help ?
https://metacpan.org/pod/WebService::SendInBlue

**Comment by Ban3** [comment]
> Could this help ? https://metacpan.org/pod/WebService::SendInBlue

It's for an old version (v2) of the API. Current is v3.

> API v2 Deprecation Notice
>
>On June 25th 2020 Sendinblue's [API v2](https://apidocs.sendinblue.com/) started its official deprecation process. The sunset of the platform will be carried out through the current year and will be completely removed by *December 2022

 It doesn't seem to have any functions for contact/campaign management anyway.

**Comment by stephanegigandet** [comment]
Steps:
- create a free plan on Brevo, and create an API key
- create a contact list on Brevo, and get the list id
- create a Brevo.pm module, with a function add_contact_to_list($list_id, $email, $username, $cc, $lc..) 
- create a brevo.t unit test, to verify it works, and to verify, we also need a function to get the list of contacts, or get one contact info
- then use add_contact_to_list() in user.pl or Users.pm when a user creates an account

**Comment by manon-corneille** [comment]
I close this issue as the discussion moved to : https://github.com/openfoodfacts/openfoodfacts-server/pull/8856
