### ISSUE TITLE
Add the welcome video in the Pro platform  

### ISSUE THREAD

**Issue by manon-corneille** [openfoodfacts/openfoodfacts-server#8526]
**Welcome video link:** https://www.youtube.com/watch?v=7usK67u2pM4

**Where to add it:** https://world.pro.openfoodfacts.org/
Youtube provides auto-translation so we could publish it on all platforms (fr.pro / it.pro / de.pro / es.pro / etc)  

### Part of
- #5521 

**Mockup:** 
<img width="796" alt="image" src="https://github.com/openfoodfacts/openfoodfacts-server/assets/104015489/2d3c856c-9f1a-426b-b8fa-5f0ceb2cca93">

**Comment by stephanegigandet** [comment]
The relevant file is in the openfoodfacts-web repo: https://github.com/openfoodfacts/openfoodfacts-web/blob/main/lang/en/texts/index-pro.html

**Comment by manon-corneille** [comment]
Hey :) 
I don't see the Welcome videos on the home page of the platform. 
Would it be ok to reopen this issue maybe?

cc @MonalikaPatnaik
