### ISSUE TITLE
In dialogues and enumerations you must use an m-dash

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#853]
In dialogues and enumerations you must use an m-dash. - 237 times (only the first ones are displayed) - click to see details
Url:  https://world.openfoodfacts.org/state/to-be-completed
Context: - World
Context: - Saturated fat	1 g	0.6 g	?

Possible replacements:—

**Comment by hangy** [comment]
There are no enumerations on that page. :)

**Comment by teolemon** [comment]
I guess the point of the linter is to replace - by —, but not sure in which cases.
