### ISSUE TITLE
Update the links to the FAQ on the website's main landing page 

### ISSUE THREAD

**Issue by Sarazine131** [openfoodfacts/openfoodfacts-server#8551]
### What
- Hello, an update of the links to the FAQ (Frequently Asked Questions) is needed in each of the following languages: 

**Italian :** for https://it.openfoodfacts.org/ the link is https://support.openfoodfacts.org/help/it-it
**Spanish** : for https://es.openfoodfacts.org/ the link is https://support.openfoodfacts.org/help/es-es 
**German :** for https://de.openfoodfacts.org/ the link is https://support.openfoodfacts.org/help/de-de
**English :** for https://world.openfoodfacts.org/ the link is https://support.openfoodfacts.org/help/en-gb  

Thank you very much :) !

**Comment by vedantmistryy** [comment]
Hello @Sarazine131, I'm new and learning open-source contributing, can i do this issue?
Thank you!

**Comment by alexgarel** [comment]
Hi @vedantmistryy and welcome. Of course feel free to fix the issue ! (just signal you are working on it, as you did). 

You might find the links either in https://github.com/openfoodfacts/openfoodfacts-web or in some template in this project. In the later case, maybe links are in the .po (translation files). I let you dig :-)

**Comment by vedantmistryy** [comment]
@alexgarel @manon-corneille I think this issue has been solved, please check and revert.
![image](https://github.com/openfoodfacts/openfoodfacts-server/assets/106006564/e05c1fc1-2496-4d24-a472-6ff7bfca9d39)

**Comment by Sarazine131** [comment]
Hello, @vedantmistryy :) 
The issue refers to this button on the main page of the public platform, it is at the very bottom of the page.  
The task is to modify the link to the "Frequently asked questions" button from the Open Food Facts website to the support ones (listed above). 
<img width="404" alt="Capture d’écran 2023-06-27 à 10 12 43" src="https://github.com/openfoodfacts/openfoodfacts-server/assets/125381861/57595a35-fa68-4945-a38c-b00f888dbd84">

**Comment by vedantmistryy** [comment]
Hello @Sarazine131
you mean for example an english user taps for "FAQ" button they should redirect to "https://support.openfoodfacts.org/help/en-gb" and same for other respective languages?
Am I correct?

**Comment by Sarazine131** [comment]
Hi @vedantmistryy :). 

Yes, you are correct, this is exactly what I mean.

**Comment by vedantmistryy** [comment]
Okay, I'm trying from last 1 hour, but I can't find the FAQ div in code base, it isn't in index.html either, please help me

**Comment by alexgarel** [comment]
Hi @vedantmistryy, thanks for your efforts.

Look at `site_layout.tt.html`, there is a "#contribute_and_discover_links_block" div, where you can see that the link is indeed a translation string "footer_faq_link".

So, the way to change the FAQ is to go in [crowdin](https://crowdin.com/project/openfoodfacts) and change translation for this string in different languages to point the right resource.

**Comment by vedantmistryy** [comment]
Hello @alexgarel sir, first of all I'm sorry for disturbing you guys again and again but am 2nd year cse student am still learning, I am trying my best but can't succeed, please help I want to learn more and more about in this field.
In en/texts there isn't `site_layout.tt.html` as seen in below ss and it isn't either in [crowdin](https://crowdin.com/project/openfoodfacts).
Please help

![image](https://github.com/openfoodfacts/openfoodfacts-server/assets/106006564/7e623354-8784-4357-b901-06306c09ac0c)

**Comment by alexgarel** [comment]
@vedantmistryy will you do it ?

**Comment by vedantmistryy** [comment]
@alexgarel thank you sir, but i cannot find the links which i need to change for respective language.

**Comment by alexgarel** [comment]
@ivedantmistry did you have look at crowdin ?

**Comment by aadak99** [comment]
Looked into this issue and saw that this issue seems to have been fixed. Just wanting to have someone verify if possible and close if correct.

**Comment by alexgarel** [comment]
Yes, thanks @aadak99 !
