### ISSUE TITLE
Le participe « aperçus » devrait être au singulier.

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#856]
Le participe « aperçus » devrait être au singulier. - 1 time - click to see details
Url:  https://fr.openfoodfacts.org/mission/releveur-d-empreintes
Context: ...mpreintes ! Des informateurs l'auraient aperçus dernièrement dans des magasins bio et d...

**Comment by lan33** [comment]
I will fix this.
