### ISSUE TITLE
Add the PME+ label to the taxonomy

### ISSUE THREAD

**Issue by Sarazine131** [openfoodfacts/openfoodfacts-server#8573]
Hello, would it be possible to add the [PME+](https://www.label-pmeplus.fr/) label to the taxonomy please ? 
![PME+150x150](https://github.com/openfoodfacts/openfoodfacts-server/assets/125381861/abe841bf-eaad-4db5-b0e4-9ff517b82254)

**Comment by teolemon** [comment]
I reckon you have seen this @Sarazine131 : https://support.openfoodfacts.org/help/en-gb/15/55 ?

**Comment by Sarazine131** [comment]
Hello, @teolemon I have but I do not understand the process, I figured out it would be more efficient for someone else to do it :)

**Comment by manon-corneille** [comment]
@teolemon The label PME+ is not in the taxonomy yet. Could you help us with adding the label "pme+" in the taxonomy first? 

And then I've opened this PR to add the logo → https://github.com/openfoodfacts/openfoodfacts-server/pull/8584

Thanks for your help,

**Comment by duhow** [comment]
Since PR is merged, this issue may be closed. 🎉
