### ISSUE TITLE
Allergens autocompletion should use synonyms

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-server#8578]
### Problem
When typing "OE" in the allergen text box in french, you don't get "Œuf" entry although the ["oeuf" variant](https://github.com/openfoodfacts/openfoodfacts-server/blob/main/taxonomies/allergens.txt#LL102C21-L102C21) is present in taxonomy

This is quite cumbersome for on windows œ is not really accessible.

### Proposed solution

All synonyms should be taken into account when you type in allergens.

### Additional context

This field does not use a suggest.pl request. If it was, [it would work](https://world.openfoodfacts.org/cgi/suggest.pl?tagtype=allergens&term=oe&lc=fr&limit=300).

Also this might affect other fields, which would benefit from synonyms.

**Comment by Naruyoko** [comment]
I'm making a prototype that allows the API to return the matched synonym, so the options would be searched by the matched synonym and displayed like `[matched name] ([canonical name])`.
