### ISSUE TITLE
404 Failed to load resource Open http://en.openfoodfacts.org/users from https://world.openfoodfacts.org/who-we-are

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#858]
404 Failed to load resource: the server responded with a status of 404 (Not Found) https://en.openfoodfacts.org/users - 1 time - click to see details
Steps to reproduce
Open https://world.openfoodfacts.org/who-we-are
Open http://en.openfoodfacts.org/users

**Comment by CloCkWeRX** [comment]
Seems to be serving content now...

**Comment by TechShooter** [comment]
Can close this issue, users.html has been deleted https://github.com/openfoodfacts/openfoodfacts-server/commit/a1c4a2391e31fc5ca076aba45a4b693b96981615

**Comment by alexgarel** [comment]
Thank you @TechShooter :-)
