### ISSUE TITLE
[FOUNDATION] Allow more than 2 criteria in search form

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#86]
The search form is complex, and thus scary. This is why I put only 2 criteria (for brands, categories, labels etc.), so that they can fit in only one row on wide screens.

One thing we could do is to add 2 more criteria when the 2nd one is filled by the user. That way advanced users can keep doing complex searches.

**Comment by pijey** [comment]
I started the modification by adding two more criterias when the last text field is modified (on the change event). Is there a limit in terms of numbers of criterias or we can add as many criterias as we want ?

I used the clone() method on a criteria to get the three fields (with the two selects) and then modify the names and ids before appending them to the form.

**Comment by stephanegigandet** [comment]
There's a limit of 2 on the server side, I will remove it so that we can have any number of criterias.

**Comment by pijey** [comment]
Yep I saw the $tags_n variable that is set to 2 by default.

**Comment by stephanegigandet** [comment]
I just checked in the change in search.pl  $tags_n is still used to display the 2 default tags, but as long as tag_[i] is defined, it now checks tag_[i+1]

**Comment by pijey** [comment]
Perfect, I will submit a PR this afternoon

**Comment by hangy** [comment]
I believe this is fixed. The current search page doesn't seem to limit the number of criteria.
