### ISSUE TITLE
The recycling information indicated for mineral water or spring water does not appear

### ISSUE THREAD

**Issue by PommeOrange147** [openfoodfacts/openfoodfacts-server#8616]
### Problem
Hi everyone, I noticed that the recycling information indicated for mineral water or spring water does not appear on the product sheet.
For example, the Cristaline 50 cl (https://fr.openfoodfacts.org/produit/3268840001008/cristaline-eau-de-source), the product sheet indicates "Packaging information missing for this product" while the information are well informed in the background. Is it intentional or is it a bug? I don't know...

### Proposed solution
Even if the Eco-Score is not applicable for the water category, wouldn't it be interesting for the information on packaging and sorting provided by the contributors to appear?

### Additional context
![Screenshot_20230624-215157_Chrome](https://github.com/openfoodfacts/openfoodfacts-server/assets/136658399/d16d4c98-5ce3-4549-a7d5-edab3a73da41)
![Screenshot_20230624-215325_Chrome](https://github.com/openfoodfacts/openfoodfacts-server/assets/136658399/d6ac5d8d-237a-48bc-951a-c4bf47cbe316)

**Comment by stephanegigandet** [comment]
Thanks for the report, it will be fixed by https://github.com/openfoodfacts/openfoodfacts-server/pull/8629
