### ISSUE TITLE
Sentence not translated

### ISSUE THREAD

**Issue by PommeOrange147** [openfoodfacts/openfoodfacts-server#8636]
### Problem
It's a detail but I noticed on the website that there was a sentence in English that was never translated.
It is located in the “your contributions” section and it is the sentence: Products added by…
I tried the German, Italian and even Korean versions of the site but no matter what language you choose, this is the only sentence that is not translated. However the translation is available on Crowdin.

### Proposed solution
Unlock the translation of this sentence

### Additional context
![This sentence is not translated](https://github.com/openfoodfacts/openfoodfacts-server/assets/136658399/4418d1c8-7e23-43db-bf65-e600c9e34f98)

**Comment by alexgarel** [comment]
Thanks for spotting it @PommeOrange147 

I added it to the translations file, should be available for translation soon.
