### ISSUE TITLE
Trouble displaying a table in the Product Opener dev environment setup guide 

### ISSUE THREAD

**Issue by albatrousse** [openfoodfacts/openfoodfacts-server#8651]
Even though in Github [docs/dev/how-to-quick-start-guide.md] the display is correct, but the table is badly displayed when looking directly in the website : https://openfoodfacts.github.io/openfoodfacts-server/dev/how-to-quick-start-guide/#3-optional-review-product-openers-environment under "3. [Optional] Review Product Opener's environment"

**In Github:**

![image](https://github.com/openfoodfacts/openfoodfacts-server/assets/120013023/5ea743a9-26dd-4919-a1f2-b3bfc96043d2)

**Directly in the website:** 

![image](https://github.com/openfoodfacts/openfoodfacts-server/assets/120013023/8cf83a89-e2fa-49f0-9cf8-2346b6ae7269)

**Comment by alexgarel** [comment]
Fixed last week by https://github.com/openfoodfacts/openfoodfacts-server/pull/8657

An empty line was missing.
