### ISSUE TITLE
Remove references to the extra off:off HTTP basic authentication in .net API documentation

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#8675]
Following a suggestion from @teolemon , the extra off:off authorization has been removed for API calls on openfoodfacts.net (preprod environment for testing). We should remove the off:off references in the API documentation (and sample queries).

https://github.com/openfoodfacts/openfoodfacts-server/issues/8582

This should also allow us to make the "Try it" feature of the API doc work: #8134

**Comment by alexgarel** [comment]
@albatrousse this is a good occasion to meet the OpenAPI documentation :-)
