### ISSUE TITLE
Non sold products are not processed

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#8689]
### What
I tried to repair a categorisation of a product that is no longer sold. After editing is still appears under the deleted category

### Steps to reproduce the behavior
See https://world.openfoodfacts.org/product/3227291015170/pommes-de-terre-en-lamelles-a-rissoler-lunor is also found under the category fresh vegetables, but it no longer has that category.

### Expected behavior
The edited product should be processed

### Why
- 

### Number of products impacted
all wrongly categorised old products

**Comment by aleene** [comment]
See also https://world.openfoodfacts.org/category/fresh-vegetables/ingredient/oil-and-fat The product listed should not appear

**Comment by benbenben2** [comment]
@aleene, can you still reproduce it?
First of your link, we cannot see fresh vegetables 👍 

However, it does not appear under fresh-vegetables: 
https://world.openfoodfacts.org/category/fresh-vegetables/ingredient/potato

(
While it does under one of its categories:
https://world.openfoodfacts.org/category/potato-preparations/ingredient/potato
)

**Comment by aleene** [comment]
Maybe there was some other issue. Let's  close this for the moment.
