### ISSUE TITLE
Mistranslation on the producers' platform 

### ISSUE THREAD

**Issue by manon-corneille** [openfoodfacts/openfoodfacts-server#8701]
On the French producers' platform (https://fr.pro.openfoodfacts.org/), the text "Number of products withdrawn from the market since last export" isn't translated. I can see this error on the German producers' platform too, I suspect it might be on all languages.   
 
<img width="1012" alt="image" src="https://github.com/openfoodfacts/openfoodfacts-server/assets/104015489/ef5957bc-7b95-4171-ba38-c9f8387a888b">

**Comment by raphael0202** [comment]
There are some translations available, but the pull request to add it is blocked since May 6th:
https://github.com/openfoodfacts/openfoodfacts-server/pull/8400

**Comment by raphael0202** [comment]
The translation PR was merged, it's not resolved.
