### ISSUE TITLE
Allow language prefix in categories

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#872]
On the web and the api the language prefix is stripped from any categories that are not in the taxonomy.
So if I want to add the category "fr:test" on the english site, the fr: is changed to en:.

**Comment by hangy** [comment]
I can't reproduce this in unit tests or on off.net. https://world.openfoodfacts.net/product/5050083535079 still has my `fr:test` category, as does https://world.openfoodfacts.net/product/3760138011022 with `ru:yoxooaosd`. I edited both on world.off.net.

**Comment by CloCkWeRX** [comment]
I also see it working in production, annecdotally.

**Comment by VaiTon** [comment]
We should test API too

**Comment by aleene** [comment]
Not sure what happened finally
