### ISSUE TITLE
Move texts to Crowdin

### ISSUE THREAD

**Issue by hangy** [openfoodfacts/openfoodfacts-server#875]
In order to profiting from Crowdins translations, we should evaluate moving texts from /lang/$lc/texts/ to .po files.

Implementing this change would require us to update `ProductOpener::Display::display_text` to not depend on the file system structure any more.

**Comment by teolemon** [comment]
We're talking about the Static Pages like discover ?
Breaking them down into phrase level chunks and translating them ?

**Comment by hangy** [comment]
Yes, either break them down or have the complete HTML fragments in .po files, as we do for other HTML fragments. Right now, they have to be translated completely differently from the other UI strings. Moving them to Crowdin could encourage more translations.

**Comment by hangy** [comment]
Actually the same as #692
