### ISSUE TITLE
The classic Open Products Facts gets a 413 HTTP Error

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#8750]
### What
- The classic Open Products Facts gets a 413 HTTP Error
- [413 Payload Too Large - HTTP - MDN Web Docs](https://developer.mozilla.org/fr/docs/Web/HTTP/Status/413)

### Steps to reproduce the behavior

1. Install Open Products Facts classic
2. Add a new product
3. Add a front photo and then an ingredients photo
4. See 413 error as a tooltip

**Comment by alexgarel** [comment]
Might be linked to the move on off2 server. I will check for nginx configuration.

**Comment by alexgarel** [comment]
Here are nginx difference with previous config:

```
$ diff /tmp/nginx-off1.conf /etc/nginx/nginx.conf 
19,20d18
< 	tcp_nodelay on;
< 	keepalive_timeout 65;
34c32
< 	ssl_protocols TLSv1 TLSv1.1 TLSv1.2 ; # Dropping SSLv3, ref: POODLE
---
> 	ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
49d46
< 	gzip_disable "msie6";
56c53
< 	gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript text/csv;
---
> 	# gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
64,65d60
< 
< 	client_max_body_size 20M;
```

I will add it to the single configuration files, I think it's more explicit.

**Comment by alexgarel** [comment]
This should be fixed now, @teolemon can you test it ?

**Comment by teolemon** [comment]
It is! Thank you @alexgarel
