### ISSUE TITLE
"Vitamin PP" is not present in the nutrition facts form

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#8755]
`Vitamin PP` is also called `Vitamin B3` or `Niacin`: https://en.wikipedia.org/wiki/Niacin

Some products only show `Vitamin PP` in their nutrient facts, such as: https://world.openfoodfacts.org/cgi/product.pl?type=edit&code=3175681851849

But Open Food Facts only recognize `Vitamin B3 (Niacin)`. `Vitamin PP` should be added as a synonym or any maner that allows, when typinp `PP` in the field, to display the right vitamin.

Should it be `Vitamin B3 (Niacin / PP)`?

**Comment by aleene** [comment]
Can change it to Vitamin B3/PP (Niacin). In english only?
