### ISSUE TITLE
Warn users that ALDI product pages can be wrong

### ISSUE THREAD

**Issue by TaciteOFF** [openfoodfacts/openfoodfacts-server#876]
Many visitors and contributors, especially outside France, find it odd that their barcode return a totally different product.
It might be worth adding a warning.
Here's my suggestion:

If : Barcode = EAN8 + Stores contains ALDI
Then display :  

Attention: Les supermarchés ALDI référencent parfois plusieurs produits distincts sous un même code-barre. OpenFoodFacts ne peut pas les différencier pour l'instant.
Beware: ALDI supermarkets can use a single barcode for different products. OpenFoodFacts can't distinguish them for now.

**Comment by teolemon** [comment]
#403 ?

**Comment by teolemon** [comment]
fixed @TaciteOFF
