### ISSUE TITLE
Import Nordic products from sebleouf

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#879]

**Comment by aleene** [comment]
It would be interesting to include a bulk import feature into FoodViewer.

**Comment by teolemon** [comment]
oh interesting. Either bulk, or an offline mode. 
https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/407
https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/406
https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/473

**Comment by aleene** [comment]
I'm thinking along these lines. It should be offline as well. Need to think of a nice work flow:
- take an image from a barcode creates a new product, then add extra images until the next barcode, confirm this is a new product and continue.
- with a film roll folder select the first image with a barcode and the app goes through the folder and creates new local products if it finds a barcode.
- at a later stage synchronise with off (and correct any errors)
- and do the usual editing

**Comment by teolemon** [comment]
Fixed by https://world.openfoodfacts.org/contributor/sebleouf/country/sweden
