### ISSUE TITLE
bug: parsing vitamins from ingredients list

### ISSUE THREAD

**Issue by benbenben2** [openfoodfacts/openfoodfacts-server#8794]
When Croatian is main language. 
When there is "vitamins" followed by a list of vitamin in parenthesis - like this:
vitamini (vitamin C, niacin, pantotenska kiselina, vitamin B6, vitamin B2, vitamin B1, folna kiselina, vitamin B12)

some elements of the list are not correctly parsed.

Example
ingredients list contains: 
vitamini (vitamin C, niacin, pantotenska kiselina, vitamin B6, vitamin B2, vitamin B1, folna kiselina, vitamin B12),

Parsed ingredients is: 
vitamins (vitamin v, tam, n C, vitamin n, vitamin ac,vitamin n, pantotenska kiselina, vitamin B6, vitamin B2, vitamins, vitamin B1, folna k, sel, vitamin na, vitamin B12)

some examples: 
https://hr.openfoodfacts.org/product/3850104258961
https://hr.openfoodfacts.org/product/3831061001043
https://hr.openfoodfacts.org/product/3850334110961
https://hr.openfoodfacts.org/product/5900020019530
https://hr.openfoodfacts.org/product/3850354004257/baktiv-smoothie-sa-%C5%BEitaricama-dukat

**Comment by stephanegigandet** [comment]
It's caused by a translation mistake:

in /po/common/hr.po

```
# leave a space before and after, unless there are no spaces between "A and B" in the target language
msgctxt "_and_"
msgid " and "
msgstr "i"

```

**Comment by benbenben2** [comment]
Oh! Super!

Updated in Crowdin. Is it deployed automatically?

**Comment by stephanegigandet** [comment]
It's not deployed automatically, translations are uploaded in a special branch and crowdin makes a PR with them.

I think I will remove that string from the translation and put it in the code instead, as it's too easy to break.
