### ISSUE TITLE
All JS scripts get executed twice due to robotoff-asker

### ISSUE THREAD

**Issue by raphael0202** [openfoodfacts/openfoodfacts-server#8799]
### What
When analyzing XHR queries made on Open Food Facts, I noticed that some XHR queries were performed twice (`/preferences`, `/attribute_groups`). The culprit is robotoff-asker that clones every script and add it inside its HTML node:
```javascript
    const scripts = document.querySelectorAll('script');
    for (let i = 0; i < scripts.length; ++i) {
      const script = scripts[i];
      content.appendChild(script.cloneNode(true));
    }
```

In the #1705 PR, it seems that we cannot use JS and CSS from the main page and need to copy it, but we definitely don't need custom scripts.

I understand why we need CSS, but do we even need these scripts?
poke @hangy

**Comment by hangy** [comment]
> I understand why we need CSS, but do we even need these scripts?

In my mind, we required the scripts for Foundation's responsive layout to work inside the template. The execution might be a bit obscure, but since the script also clones the `script` nodes that run `$(document).foundation({`, it probably makes the template responsive through that.

**Comment by raphael0202** [comment]
Ok, but I guess we don't need the custom scripts then, we can disable loading them.

**Comment by hangy** [comment]
Yep, maybe add some `data-*` attribute to exclude some files?
