### ISSUE TITLE
Define a rate-limit policy

### ISSUE THREAD

**Issue by raphael0202** [openfoodfacts/openfoodfacts-server#8818]
### Problem

From time to time, we ban using iptables bots that crawl our dataset through the API or the website (even though the data can be freely accessible on /data page).
We currently don't have any rate limit policy. Before setting up a rate-limiter, it is necessary to define rate-limits that users should respect, so that we can rate-limit them (once we have a rate-limiting mechanism in place) or block their requests in the meantime.
Our current approach is not fair to users, as we never told them how many requests they can make on our API.

On Open Food Facts, we receive ~3000 requests / min.
With this metric in mind, I suggest the following rate limit: 30 req/min on product page and product API calls (1% of all requests). If our reusers have a higher traffic, they can still set up a cache to avoid hitting our database everytime.

**Comment by CharlesNepote** [comment]
Some thoughts about it.
* Some reusers are sometimes facing pikes (new app, tv show, etc.) and I guess we can try to manage this and not to have too strict rules
* Some reusers are contributing back: at least their API calls to send products should not be taken into account; would it be interesting and possible to give contributors higher rate limits, I guess it's not simple
* More than a rate-limit policy, we should have an "API usage policy" (maybe found a better name)
* Some reusers do not respect the ODBL licence, we should have a very clear statement among them: even if they are providing a user-agent, there is no warranty we don't block them at any time; ODBL licence creates a common ecosystem that benefits to all. This ecosystem is working as long as the common pot and its attribution are respected. People/organisations which are not respecting the ODBL are consuming common resources and penalizes others.
* We should publish at the same time: a clear policy about the API usage and technical guidelines to reuse Open Food Facts data differently depending on the usages (local DB, cache, etc.)

**Comment by CharlesNepote** [comment]
We could have something like this (numbers to be refined).

1. If possible, rate-limit is not activated when resources are ok

2. **product pages** (API and web, view or edit mode): **300 req/min** (5 req/s); rationale: they don't consume too much resources and we don't want to penalize individuals, scanning apps, SEO, etc.

3. **facets and search (API and web)**:
  * People with a user agent we know (or we provide): 30 req/min; 
  * All others (crawlers, unknown apps): 10 req/min

**Comment by stephanegigandet** [comment]
I would suggest to start small and simple. e.g. only 1 rule on GET /api/*/product/ , with something very high like 100 req/min. And we monitor it, to see what is rate limited and how often. (even better, we use the logs to see who/what would have been rate limited in the past month). + another rule on /api/*/search + /cgi/search.pl at 10 req/min

Web facets are much more complex as we have hundreds of different paths for them, we can do that later if needed.

**Comment by raphael0202** [comment]
> If possible, rate-limit is not activated when resources are ok

I would personally enforce rate-limiting at any time, the benefit of rate-limiting is to protect our infrastructure by making the load manageable. And when you reach 150k calls a day (100 req/min), you definitely need a local cache. And you won't reach the limit anyway if you call the API from the user device.

I would like to make it easy for reusers to set-up an up-to-date local cache, by providing webhook or other mechanism to be warned when a product is updated. Indeed only a small fraction of the database is modified each day.

> even better, we use the logs to see who/what would have been rate limited in the past month

I like this approach!

**Comment by alexgarel** [comment]
FYI rate limiting (not yet deployed) on images: https://github.com/openfoodfacts/openfoodfacts-infrastructure/pull/255

**Comment by raphael0202** [comment]
I'm closing this issue, as rate-limit is now implemented.
