### ISSUE TITLE
Delete sentences in the professional account creation form

### ISSUE THREAD

**Issue by manon-corneille** [openfoodfacts/openfoodfacts-server#8824]
When I create an account in the Pro platform, even if I don't enter any value in the field "organisation", the 2 following sentences appear : 
<img width="1160" alt="image" src="https://github.com/openfoodfacts/openfoodfacts-server/assets/104015489/34f6849b-fbb5-49c0-8c44-1a5fa37cb988">

I assume these sentences would be the result of a logical check after the user has entered the name of his/her organisation (?) 

Could someone help fix this, please?

**Comment by teolemon** [comment]
I spotted this today on my own
