### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#885]
You have Algorithm::Dependency::Source::HoA (1.110)
npm WARN deprecated bower@1.8.0: ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD projects. Currently there's no migration path, but please help to create it: https://github.com/bower/bower/issues/2467
openfoodfacts-server@1.0.0 /home/travis/build/openfoodfacts/openfoodfacts-server

**Comment by teolemon** [comment]
└── strip-json-comments@1.0.4 
0.19s$ bower install
bower: command not found
The command "bower install" failed and exited with 127 during .

**Comment by teolemon** [comment]
https://travis-ci.org/openfoodfacts/openfoodfacts-server/builds/271446293?utm_source=slack&utm_medium=notification

**Comment by paperplanes53** [comment]
Still fails with bower: command not found
