### ISSUE TITLE
Understanding JSON taxonomy fields

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#892]
The API allows to inspect how OFF interprets taxonomy based fields. A taxonomy based field consist of one or more tags (one or more words tied together). This information could be used by the user to suggest improvements to taxonomies. I would like to support this in my app, but before that it must be clear what information the API offers.

Any taxonomy based field presents its data in the json in three variants. An example for categories:
```
"categories":"Boissons,Boissons gazeuses,Eaux,Eaux minérales,Eaux gazeuses,Eaux minérales gazeuses,Boissons non sucrées"
"categories_tags":["en:beverages","en:carbonated-drinks","en:waters","en:mineral-waters","en:carbonated-waters","en:carbonated-mineral-waters","en:non-sugared-beverages"]
"categories_hierarchy":["en:beverages", "en:carbonated-drinks", "en:waters", "en:mineral-waters", "en:carbonated-waters", "en:carbonated-mineral-waters", "en:non-sugared-beverages"]
```

These three fields are in this example very similar. I (want to) interpret them as:
- Without postfix (categories): These are the tags as entered by the user. If there is no language prefix, the tags are assumed to be in the main language of the product. If the user wants to add tags in another language than the main product language, he should use a language prefix, like "en:Beverages". In this categories example, OFF probably has added tags that the user did not specify, like "Boissons non sucrées".
- _tags-postfix (categories_tags): This field shows how the OFF interpreted the tags specified by the user. Tags that are recognised are converted to the keys found in the taxonomy. If a tag is not recognised, it will be shown with the language prefix of the main product language. If the main product language is english, then it is unclear whether it is a recognised tag. Why is in this example the tag "en:non-sugared-beverages" in the list?
- _hierarchy-postfix (categories_hierarchy): In the current implementation it is unclear what this field adds. It would be nice if this field shows the 'derived' tags. These could be parents of tags, such as "en:beverages" of calculated tags "en:non-sugared-beverages" (based on other fields, such as ingredient "sugar")

In my app I support the viewing of these different fields. By double tapping you can cycle through them. It would be nice if these fields have actual meaning.

**Comment by stephanegigandet** [comment]
categories_hierarchy is a re-ordering of categories_tags, with the "level" of the entries as the sort key. The level is how deep the category is from one of the roots.

categories is what the user entered last in the form, but what is shown on the form to the user when the page is edited is the content of categories_hierarchy, in the language of the interface.

**Comment by aleene** [comment]
The difference between _hierarchy and _tags seems not very useful, especially when it is not possible to identify the tops of the trees. I like to know how off uses to interpret and extend what has been entered by the user. This can be used to give suggestions to the editors of taxonomies.

**Comment by aleene** [comment]
I will have to incorporate the taxonomies and do my own processing.

**Comment by stephanegigandet** [comment]
The new taxonomy exports may help: https://github.com/openfoodfacts/openfoodfacts-server/issues/1126

**Comment by aleene** [comment]
I will play wiith the json-versions.

**Comment by aleene** [comment]
to \o old
