### ISSUE TITLE
Store Application Identifier (AI) data string in products

### ISSUE THREAD

**Issue by hangy** [openfoodfacts/openfoodfacts-server#8926]
New barcodes like GS1 DataMatrix, GS1 QR Code, and GS1 Digital Link can contain more information than the GTIN (AI (Application Identifier) = 01). For example, they can contain the product weight for variable weight items, and the "best before" date.

## Example

```
(01)3274080005003 # GTIN
(15)230501 # Best before
(3103)000123 # Weight
```
(The string is split into multiple lines for readability. The AI string returned from `libgs1encoders` doesn't contain newlines.)

## Proposal

1. Normalize the barcodes to AI strings using [`GS1::SyntaxEngine::FFI`](https://metacpan.org/pod/GS1::SyntaxEngine::FFI) after a successful run of `scan_barcode`,
1. Store a list of unique AI strings in the product identified by the GTIN, so that they can be analyzed later.

## TBD: API integration

This would only solve product search from images uploaded from the web. (Mobile) apps that use the API need some way to search by the new GS1 barcodes and/or the AI data string.

### Part of

- #8333 

### Depends on

- #9013

**Comment by stephanegigandet** [comment]
In addition, we could just accept AI strings in the API, e.g. /api/v3/product/(01)3274080005003(15)230501(3103)000123 would return the product 3274080005003

**Comment by hangy** [comment]
I think it could be advantageous for the API to accept other types, too. Otherwise. each app/client would have to be able to parse all the GS1 barcode variations, as well.

- /api/v3/product/(01)3274080005003(15)230501(3103)000123
- /api/v3/product/013274080005003152305013103000123
- /api/v3/product/https%3A%2F%2Fid.gs1.org%2F01%2F3274080005003%2F15%2F230501%3F3103%3D000123 (/api/v3/product/https://id.gs1.org/01/3274080005003/15/230501?3103=000123)
- …?
