### ISSUE TITLE
Unexpected empty category besides other categories

### ISSUE THREAD

**Issue by Phyks** [openfoodfacts/openfoodfacts-server#896]
Hi,

https://world.openfoodfacts.org/product/4607025398387/%D0%BA%D0%B5%D1%84%D0%B8%D1%80-%D0%BD%D0%B0-%D0%B6%D0%B8%D0%B2%D0%BE%D0%B9-%D0%B7%D0%B0%D0%BA%D0%B2%D0%B0%D1%81%D0%BA%D0%B5-3-2-%D0%B4%D0%BE%D0%BC%D0%B8%D0%BA-%D0%B2-%D0%B4%D0%B5%D1%80%D0%B5%D0%B2%D0%BD%D0%B5 and https://world.openfoodfacts.org/product/4607025398394/%d0%ba%d0%b5%d1%84%d0%b8%d1%80-%d0%bd%d0%b0-%d0%b6%d0%b8%d0%b2%d0%be%d0%b9-%d0%b7%d0%b0%d0%ba%d0%b2%d0%b0%d1%81%d0%ba%d0%b5-1-%d0%b4%d0%be%d0%bc%d0%b8%d0%ba-%d0%b2-%d0%b4%d0%b5%d1%80%d0%b5%d0%b2%d0%bd%d0%b5 have an empty category as well as many other categories.

This can be seen by the presence of two consecutive commas in the categories list:

> […], Kefir, , Kefir 1 %, […]

as well as in the CSV dump.

When editing the product page, everything seems to be fine https://lut.im/zIpWfPfv95/IjAwYVOkJPheJ8Br.png.

Looking at the CSV dump, it seems this is the only affected products.

**Comment by hangy** [comment]
Product seems to have been fixed.
