### ISSUE TITLE
Translation error on production

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#901]
```DE BY117 EG, FR 62.448.034 CE, 84 R 20, 33 RECOLTANT 522```
https://ch.openfoodfacts.org/produkt/7610011759175/bell

**Comment by hangy** [comment]
https://translate.openfoodfacts.org/translate/openfoodfacts/all/en-de#q=DE+BY117+EG%2C+FR+62.448.034+CE%2C+84+R+20%2C+33+RECOLTANT+522 some translations need to be downvoted, I think.

**Comment by teolemon** [comment]
I removed the faulty translation from suggestions and hotfixed in trunk by removing the translation as well.

**Comment by teolemon** [comment]
Fixed in prod
