### ISSUE TITLE
Bad IU conversion in µg for prepared nutrition data

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#9107]
In the following product, 468 UI is converted into 468,000,000 µg, which leads to a data quality error (Nutrition value over 105 - Vitamin a prepared ): https://world.openfoodfacts.org/product/8717896009292/lait-entier-en-poudre-instantane-nestle?rev=45

![image](https://github.com/openfoodfacts/openfoodfacts-server/assets/562352/a3683f80-ad5e-42bf-b848-7f4abff78a4a)

**Comment by stephanegigandet** [comment]
Happens on prepared nutrition facts, looking into it.
