### ISSUE TITLE
NEW DESIGN : Leaflet map goes above content.

### ISSUE THREAD

**Issue by Valimp** [openfoodfacts/openfoodfacts-server#9118]
### What
Leaflet map goes above content, it's weird when you scroll.
<img width="486" alt="Capture d’écran 2023-10-06 à 09 40 58" src="https://github.com/openfoodfacts/openfoodfacts-server/assets/112864841/fe07c586-54dd-4e73-8668-02966fbb48e1">

### Steps to reproduce the behavior
1. Go to ah product with location
2. Scroll

### Expected behavior
Change z-index of leaflet map to match with the content.

### Screenshot/Mockup/Before-After
<img width="486" alt="Capture d’écran 2023-10-06 à 09 40 58" src="https://github.com/openfoodfacts/openfoodfacts-server/assets/112864841/481de6b9-3da4-456d-a8ed-b425020701c2">

### Part of
- #7295

**Comment by SarthakD15** [comment]
Hey @Valimp, I want to work on this issue can you please assign it to me?

**Comment by teolemon** [comment]
@SarthakD15 assigned

**Comment by SarthakD15** [comment]
Thanks !

**Comment by shamun-khatri** [comment]
Hey, @SarthakD15  are you stll working on this issue?

**Comment by alexgarel** [comment]
@shamun-khatri I think you can take it :-)

**Comment by shamun-khatri** [comment]
Hey, @teolemon while setting up the project locally on Windows I am getting an error on "make dev" that is not mentioned in Guide and till now I have done:

1- Reinstalling docker. 
2- Clean installation of docker by removing every single file associated with docker and then reinstall.
3- every time I redo the process I clone a fresh file by running the given command for cloning.

I am attaching an image of the error.
![error 1](https://github.com/openfoodfacts/openfoodfacts-server/assets/100433320/9085b7a1-3bed-489b-8b5f-5ed0be411e20)
![Screenshot 2023-12-26 155948](https://github.com/openfoodfacts/openfoodfacts-server/assets/100433320/3e6b3808-b08a-49b4-a8ab-9a682d95cab1)

**Comment by shamun-khatri** [comment]
Hi, I used Gitpod to set up the project. I tried to setup in Windows and Linux but it's not happening. Anyway, I opened the first pull request because I fixed this issue please review it.
Thanks.

**Comment by shamun-khatri** [comment]
hi @alexgarel @teolemon please look forward to my pull request for this issue. Thank you.
