### ISSUE TITLE
Querying obsolete products through openfoodfacts-query

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#9134]
It's possible to get lists of obsolete products by adding ?obsolete=1 to URLs. In that case we issue query on the products_obsolete collection.

e.g. to see brands for which we have products marked obsolete: https://world.openfoodfacts.org/brands?obsolete=1

This behavior does not seem to be implemented with the openfoodfacts-query service.

**Comment by john-gom** [comment]
I've raised [PR #9](https://github.com/openfoodfacts/openfoodfacts-query/pull/9) on openfoodfacts-query to handle this. Will raise a separate PR on off-server to supply the obsolete tag when this is in the request.
In the same PR I'll remove the code that falls back to product_tags
