### ISSUE TITLE
Search - Allow to use extended user roles in advanced search

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#915]
### What
- In an advanced search it is possible to search the **editor** and **creator** role. Add the other roles as well.
- Add a contributor role to the advanced search. A contributor is someone who did one or more roles.
- On the advanced search webpage one can search a contributor. In the search url this is interpreted as the creator role. The interface should be adapted as such.

### Part of 
- #5492

**Comment by TaciteOFF** [comment]
Searching by "editors" gives weird result. 

https://fr.openfoodfacts.org/editeur/grumpf : 108 products
https://fr.openfoodfacts.org/cgi/search.pl?action=process&tagtype_0=editors&tag_contains_0=contains&tag_0=grumpf&sort_by=unique_scans_n&page_size=20&axis_x=energy-kj&axis_y=products_n&action=display : 0 products

https://fr.openfoodfacts.org/editeur/tacite : 35 257 products
https://fr.openfoodfacts.org/cgi/search.pl?action=process&tagtype_0=editors&tag_contains_0=contains&tag_0=tacite&sort_by=unique_scans_n&page_size=20&axis_x=energy-kj&axis_y=products_n&action=display : 15 369 products

**Comment by aleene** [comment]
too old
