### ISSUE TITLE
Update the Mobile taglines for the 2023 donation campaign

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#9195]
### What
- Update the Mobile taglines for the 2023 donation campaign
- Ensure that we have UTMs to ensure attribution (eg Smoothie Android, Smoothie iOS, OBF, OPF, OPFF Android)

### Code pointers
tagline:
- html/files/app/tagline/tagline-off-ios.json
- html/files/tagline-off.json
- html/files/tagline.txt
- html/files/tagline-obf.json
- html/files/tagline-opf.json
- html/files/tagline-opff.json
- html/files/tagline-off-ios-v2.json
- html/files/tagline-off-android-v2.json

### PR to duplicate
- https://github.com/openfoodfacts/openfoodfacts-server/pull/7668

### Part of
- #5720

**Comment by aakankshabhende** [comment]
@teolemon I would like to work on this issue. Could you please assign me this?

**Comment by alexgarel** [comment]
@aakankshabhende I think it's better that @teolemon handles it by itself (it's a bit touchy).
