### ISSUE TITLE
[FOUNDATION] Be compliant with Google SEO enhancements using Schema.org

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#92]
* https://developers.google.com/structured-data/site-name (Will display the Site Name, eg "Open Food Facts" in search results)
* https://developers.google.com/structured-data/breadcrumbs (Will display categories and pages in a nice hierarchical breadcrumb)
* https://developers.google.com/structured-data/slsb-overview (Will enable users to perform searches from within Google results page)

**Comment by stephanegigandet** [comment]
Added site name and searches.

**Comment by stephanegigandet** [comment]
https://developers.google.com/structured-data/testing-tool/
