### ISSUE TITLE
Pagination processing software error

### ISSUE THREAD

**Issue by nicolasleger** [openfoodfacts/openfoodfacts-server#921]
1. Go on a products listing page like https://world.openfoodfacts.org/state/quantity-to-be-completed/
2. And choose lasts pages
3. You might get a `Software error`: `Type of argument to keys on reference must be unblessed hashref or arrayref at /home/off/lib/ProductOpener/Display.pm line 7277.`

<img width="1005" alt="screen shot 2017-10-31 at 01 36 51" src="https://user-images.githubusercontent.com/570901/32202298-00e06df6-bddc-11e7-8860-240985204b91.png">

However if you goes after the last page you got no problem like https://world.openfoodfacts.org/state/quantity-to-be-completed/12351

<img width="769" alt="screen shot 2017-10-31 at 01 36 40" src="https://user-images.githubusercontent.com/570901/32202303-0352fbb2-bddc-11e7-8018-e8a962c1021d.png">

**Comment by hangy** [comment]
Apparently, this is unrelated to pagination, and actually not a MongoDB query issue. We have some products that do not have a `languages_codes` property, and the code that tries to add image URLs for other languages does not check that correctly.

```
> db.products.find({"languages_codes": null}).count()
28
```
