### ISSUE TITLE
Migrate from bower to yarn for front assetss

### ISSUE THREAD

**Issue by nicolasleger** [openfoodfacts/openfoodfacts-server#922]
During `npm install` :

`npm WARN deprecated bower@1.8.2: ...psst! Your project can stop working at any moment because its dependencies can change. Prevent this by migrating to Yarn: https://bower.io/blog/2017/how-to-migrate-away-from-bower/`

- https://bower.io/blog/2017/how-to-migrate-away-from-bower/
- https://www.npmjs.com/package/bower-away

- https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn
- https://yarnpkg.com/en/docs/install-ci#travis-tab

**Now use `yarn install` instead of `npm install`.**

**Comment by hangy** [comment]
closed in 11b81e8f78d7ec14cfaf550144eb3be1363a3c1f
