### ISSUE TITLE
Missing variety of avocado (hass)

### ISSUE THREAD

**Issue by bigon** [openfoodfacts/openfoodfacts-server#9233]
### What
When adding "hass avocado" (fr:"avocat hass") as ingredient , the parser doesn't recognize this as a variety of avocado

https://en.wikipedia.org/wiki/Hass_avocado

### Expected behavior
- "hass avocado" (fr:avocat hass) is recognize as a variety of avocado

**Comment by alexgarel** [comment]
I close it, it should work with next release !
