### ISSUE TITLE
Invalid character in the Delete the images button

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#9277]
### What
<img width="550" alt="image" src="https://github.com/openfoodfacts/openfoodfacts-server/assets/1689815/8f4a3e3f-9d43-4a9a-a4a9-709b3255c404">

**Comment by stephanegigandet** [comment]
@TCatinaud: could you take a look? the extra character is caused by the "after" added in https://github.com/openfoodfacts/openfoodfacts-server/pull/9135

**Comment by MonalikaPatnaik** [comment]
can i take this up?

**Comment by alexgarel** [comment]
:+1 @MonalikaPatnaik
