### ISSUE TITLE
404 - ManUp.js/manup.min.js

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#929]
Failed to load resource: the server responded with a status of 404 (Not Found) >> https://static.openfoodfacts.org/bower_components/ManUp.js/manup.min.js

**Comment by hangy** [comment]
`.bowerrc` was missing on the production server, so that Bower restored the files to the wrong directory. I added `.bowerrc` from Git and re-ran `bower install`, which fixed this problem.
