### ISSUE TITLE
Uncaught SyntaxError: Unexpected token { (line 116)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#930]
Uncaught SyntaxError: Unexpected token { (line 116)
https://fr.openfoodfacts.org/cgi/search.pl?action=process&tagtype_0=states&tag_contains_0=contains&tag_0=Complet&tagtype_1=labels&tag_contains_1=contains&tag_1=V%C3%A9g%C3%A9tarien&tagtype_2=categories&tag_contains_2=contains&tag_2=Plats%20pr%C3%A9par%C3%A9s&sort_by=unique_scans_n&page_size=20&axis_x=energy&axis_y=additives_n&series_nutrition_grades=on&graph=1

**Comment by teolemon** [comment]
Fixed by @hangy 
We should ensure bower is running well on new installs.

**Comment by hangy** [comment]
> Fixed by @hangy

What did I do? 😆 

> We should ensure bower is running well on new installs.

One of the best options would be to have a CI/CD pipeline that automatically build and deploys automatically to a dev, test and production environment after an OK of a team member. Unfortunately, I don't know how feasable continuous deployment would be with Perl in general, and the current structure of the project.
