### ISSUE TITLE
Negative value for fruits-vegetables-nuts estimated from ingredients

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#9306]
Eg. https://world.openfoodfacts.org/product/3270160822454/le-petit-marchand-de-glaces-cafe-picard?rev=19

It triggers a data-quality-error.

**Comment by benbenben2** [comment]
Is this same issue?
https://github.com/openfoodfacts/openfoodfacts-server/issues/9105

**Comment by CharlesNepote** [comment]
Yes this is the same issue, sorry for the duplicate. I'm closing this one.
