### ISSUE TITLE
The heart in the donation banner is not aligned

### ISSUE THREAD

**Issue by g123k** [openfoodfacts/openfoodfacts-server#9321]
### What
- Hi everyone,

I just noticed this morning that the heart in the donation banner (after the 'Thank you very much') is not aligned with the text:
<img src="https://github.com/openfoodfacts/openfoodfacts-server/assets/246838/261c4fe3-c61a-4cfa-a2d1-fb70002ac304" height="400px">

This is just a tiny UI issue :)
Since I'm not skilled at CSS and the like, I'd rather avoid making a PR that will break everything.

### Code pointers
https://github.com/openfoodfacts/openfoodfacts-server/blob/7ed793a4fb40955abb64862b6b0fa867f48e6ccb/templates/web/common/includes/donate_banner.tt.html#L16
https://github.com/openfoodfacts/openfoodfacts-server/blob/main/po/common/en.po#L4023
https://github.com/openfoodfacts/openfoodfacts-server/blob/main/po/common/en.po#L5775

### Part of
- #5720

**Comment by Josckar** [comment]
Hi, can I work on this issue?

**Comment by Josckar** [comment]
Actually, it appears the donation popup, at least the one shown in the issue, no longer displays the heart nor displays in the same way anymore. If this is the case, I believe the issue should be closed.

**Comment by alexgarel** [comment]
Thanks @Josckar
