### ISSUE TITLE
Wiki doesn't work for me

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#934]
```
[daaeae7fd28757d4bcd94a01] /index.php?title=User:Tacite&diff=prev&oldid=683 InvalidArgumentException from line 107 of /var/www/obf.wiki.en/extensions/mediawiki-extensions-sessionprovider-productopener-master/AuthProductOpener.body.php: Invalid user name

Backtrace:

#0 /var/www/obf.wiki.en/extensions/mediawiki-extensions-sessionprovider-productopener-master/AuthProductOpener.body.php(65): AuthProductOpener->newSessionForRequest(array, WebRequest)
#1 /var/www/obf.wiki.en/includes/session/SessionManager.php(486): AuthProductOpener->provideSessionInfo(WebRequest)
#2 /var/www/obf.wiki.en/includes/session/SessionManager.php(189): MediaWiki\Session\SessionManager->getSessionInfoForRequest(WebRequest)
#3 /var/www/obf.wiki.en/includes/WebRequest.php(735): MediaWiki\Session\SessionManager->getSessionForRequest(WebRequest)
#4 /var/www/obf.wiki.en/includes/session/SessionManager.php(128): WebRequest->getSession()
#5 /var/www/obf.wiki.en/includes/Setup.php(759): MediaWiki\Session\SessionManager::getGlobalSession()
#6 /var/www/obf.wiki.en/includes/WebStart.php(137): require_once(string)
#7 /var/www/obf.wiki.en/index.php(40): require(string)
#8 {main}

```

**Comment by CharlesNepote** [comment]
@teolemon Can you give the process to reproduce?

Is it the page: https://fr.wiki.openfoodfacts.org/index.php?title=User:Tacite&diff=prev&oldid=683

Works fine for me.

**Comment by teolemon** [comment]
No, not fixed
```
[0992d089ee9aed24c1224a91] /index.php?title=Journ%C3%A9es%20OFF%202019 InvalidArgumentException from line 107 of /var/www/off.wiki.fr/extensions/mediawiki-extensions-sessionprovider-productopener-master/AuthProductOpener.body.php: Invalid user name

Backtrace:

#0 /var/www/off.wiki.fr/extensions/mediawiki-extensions-sessionprovider-productopener-master/AuthProductOpener.body.php(65): AuthProductOpener->newSessionForRequest(array, WebRequest)
#1 /var/www/off.wiki.fr/includes/session/SessionManager.php(486): AuthProductOpener->provideSessionInfo(WebRequest)
#2 /var/www/off.wiki.fr/includes/session/SessionManager.php(189): MediaWiki\Session\SessionManager->getSessionInfoForRequest(WebRequest)
#3 /var/www/off.wiki.fr/includes/WebRequest.php(735): MediaWiki\Session\SessionManager->getSessionForRequest(WebRequest)
#4 /var/www/off.wiki.fr/includes/session/SessionManager.php(128): WebRequest->getSession()
#5 /var/www/off.wiki.fr/includes/Setup.php(759): MediaWiki\Session\SessionManager::getGlobalSession()
#6 /var/www/off.wiki.fr/includes/WebStart.php(137): require_once(string)
#7 /var/www/off.wiki.fr/index.php(40): require(string)
#8 {main}
```
@CharlesNepote Go to any wiki page. This message appears. I'm not signed in on OFF. But I expect to be able to browse at least.

**Comment by VaiTon** [comment]
> /extensions/mediawiki-extensions-sessionprovider-productopener-master
It's the custom login extension that is causing the issue. Maybe when you created your account on OFF the extension was still in development and that means that you don't have an account on the wiki.

**Comment by hangy** [comment]
> @CharlesNepote Go to any wiki page. This message appears. I'm not signed in on OFF. But I expect to be able to browse at least.

I'm not getting that error on the English wiki or the French wiki. It also doesn't matter if I open the wiki in my normal browser window with an existing OFF login or a new incognito window. 😕

> > /extensions/mediawiki-extensions-sessionprovider-productopener-master
> 
> It's the custom login extension that is causing the issue. Maybe when you created your account on OFF the extension was still in development and that means that you don't have an account on the wiki.

https://github.com/hangy/mediawiki-extensions-sessionprovider-productopener if you want to have a look at it.

**Comment by CharlesNepote** [comment]
I'm not getting the error as well. I tried being identified or not, in both regular and private browsing sessions. @teolemon could you give the exact steps to reproduce?
