### ISSUE TITLE
Table sorting and filtering is broken for facets that have a taxonomy

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#935]
Maybe related to issue #873 , and probably because there is an extra column for facets that have a taxonomy like categories and labels.

https://ru.openfoodfacts.org/packaging --> works
https://ru.openfoodfacts.org/labels --> does not work, JS Error:

Uncaught TypeError: Cannot read property 'mData' of undefined
    at HTMLTableCellElement.<anonymous> (datatables.min.js:102)

**Comment by hangy** [comment]
We need to add `{ "searchable": false }` for the 3rd column. It can only be added if the extra column exists, though.
