### ISSUE TITLE
Add a new binary property to some preferences, like allergens

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#9370]
We currently use 4 levels for all food preferences, but some preferences like allergens could have a single binary switch.

We should define a new property in https://world.openfoodfacts.org/api/v0/attribute_groups to indicate which properties should/could be binary.

### Part of
- #8919

**Comment by alexgarel** [comment]
We will add an attribute "binary" that says what are the values corresponding to on / off

eg: `"binary": {"on": "important", "off": "not important"}`.
