### ISSUE TITLE
Contribution count over-reported after server migration

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#9372]
### What
- Contribution count over-reported after server migration
- I get 2,9M contributions :-) 
- Stephane seems to say it's not a classic facet, but he will comment probably tomorrow with more details.
- cc @stephanegigandet @john-gom 
<img width="280" alt="image" src="https://github.com/openfoodfacts/openfoodfacts-server/assets/1689815/4f33c8c2-3356-4bd2-be9e-a57131c825a9">

**Comment by stephanegigandet** [comment]
Probably a bug I made when doing the unlimited facets, I will look into it.
