### ISSUE TITLE
Harmonize handling of JS

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#9374]
### What
- Harmonize handling of JS
```
<script src="https://static.openfoodfacts.org/js/dist/foundation.js" data-base-layout="true"></script> 
<script src="https://static.openfoodfacts.org/js/dist/jquery.cookie.js"></script> 
<script src="https://static.openfoodfacts.org/js/dist/select2.min.js"></script> 
<script src="/js/datatables.min.js"></script> 
<script src="/js/dist/papaparse.js"></script>
```

**Comment by abdessamadchokri** [comment]
I found this issue on https://ovio.org/projects and would love to contribute! [add other relevant info about you]

**Comment by alexgarel** [comment]
Hi @abdessamadchokri, please do :-)

**Comment by sbeesm** [comment]
Hello, I would like to work on this issue. I did some initial analysis, as we need to ensure that all scripts are sourced consistently,
we can update these scripts below (used in a couple of files) to use absolute paths. Please could you suggest if my understanding is correct.

```
<script src="/js/datatables.min.js"></script> 
<script src="/js/dist/papaparse.js"></script>
```

**Comment by hangy** [comment]
IIRC, there's some code that automatically replaces some  `/js/…` URLs, and so on, in the HTML by `$static_subdomain/js/…` somewhere in `Display.pm`, so that the source in the code isn't necessarily what's output to the client

**Comment by sbeesm** [comment]
@alexgarel, @hangy Thanks for pointing this out. I just checked, `Display.pm` creates this variable below:
`$static_subdomain = format_subdomain('static');`  

And `format_subdomain` function is defined in `URL.pm`.

It is being used at multiple places like so: 
`<script src="[% static_subdomain %]/js/dist/select2.min.js"></script>`. 

Similarly, we can update scripts like below to use the `static_subdomain`:
```
<script src="/js/datatables.min.js"></script> 
<script src="/js/dist/papaparse.js"></script>
```

**Comment by mike-lu1** [comment]
hwy @alexgarel could you kindly assign me this issue
