### ISSUE TITLE
Add product_quantity_unit and serving_quantity_unit fields

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#9377]
The "quantity" and "serving_size" fields are free text fields. They are converted to a quantity in g or ml and the result is stored in "product_quantity" and "serving_quantity". We should add new fields that indicate if those normalized _quantity fields are in g or ml.

**Comment by raphodn** [comment]
Would be awesome to have this ! Need in https://github.com/openfoodfacts/open-prices
