### ISSUE TITLE
Prevent crawlers from going to deep in facets

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#938]
I'm thinking to make those links no follows:
- 2nd level drilldown by facets links in the product list resulting of a 1st drilldown by facet

The list of facet values in the 2nd drilldown are already no follow, e.g. in page /packaging/surgele/additives:

<tr><td><a href="/packaging/surgele/additive/e471-mono-and-diglycerides-of-fatty-acids" class="tag well_known" rel="nofollow">E471 - Mono- and diglycerides of fatty acids</a></td>

**Comment by teolemon** [comment]
so brand XXX additive YYY would not be discovered ?

**Comment by stephanegigandet** [comment]
no, those are already nofollow, brand XXX additives should not be crawled either.

we just get too many pages crawled and recrawled for nothing. and those are expensive pages.

**Comment by teolemon** [comment]
fair enough.
