### ISSUE TITLE
[PRODUCT-OPENER] Installation, running startup.pl raises a long integer error

### ISSUE THREAD

**Issue by nazimboudeffa** [openfoodfacts/openfoodfacts-server#94]
After running in cgi folder #perl startup.pl

here what i got, as far as i am a newbee in perl it seems that there is a long integer issue

SiteLang - overrides
cannot retrieve /root/src/product-opener/packager-codes/packager_codes.sto : Long integer size is not compatible at /usr/lib/perl/5.14/Storable.pm line 379, at Blogs/Store.pm line 129
 at Blogs/Food.pm line 2681
Can't use an undefined value as a HASH reference at Blogs/Food.pm line 2682.
Compilation failed in require at Blogs/Tags.pm line 93.
BEGIN failed--compilation aborted at Blogs/Tags.pm line 93.
Compilation failed in require at Blogs/Display.pm line 93.
BEGIN failed--compilation aborted at Blogs/Display.pm line 93.
Compilation failed in require at startup.pl line 56.
BEGIN failed--compilation aborted at startup.pl line 56.
root@debian:~/src/product-opener/cgi#

**Comment by boudeffa** [comment]
As far as i know My VM is a Wheezy running under VMWare
root@debian:~/src/product-opener/cgi# lscpu
Architecture:          i686
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                1
On-line CPU(s) list:   0
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 30
Stepping:              5
CPU MHz:               1729.128
BogoMIPS:              3458.25
Hypervisor vendor:     VMware
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              6144K

**Comment by boudeffa** [comment]
so i ran #update_packager_codes.pl and i got this

SiteLang - overrides
cannot retrieve /root/src/product-opener/taxonomies/test.result.sto : Long integer size is not compatible at /usr/lib/perl/5.14/Storable.pm line 379, at Blogs/Store.pm line 129
 at Blogs/Tags.pm line 1103
cannot retrieve /root/src/product-opener/taxonomies/countries.result.sto : Long integer size is not compatible at /usr/lib/perl/5.14/Storable.pm line 379, at Blogs/Store.pm line 129
 at Blogs/Tags.pm line 1103
cannot retrieve /root/src/product-opener/taxonomies/labels.result.sto : Long integer size is not compatible at /usr/lib/perl/5.14/Storable.pm line 379, at Blogs/Store.pm line 129
 at Blogs/Tags.pm line 1103
cannot retrieve /root/src/product-opener/taxonomies/categories.result.sto : Long integer size is not compatible at /usr/lib/perl/5.14/Storable.pm line 379, at Blogs/Store.pm line 129
 at Blogs/Tags.pm line 1103
cannot retrieve /root/src/product-opener/taxonomies/additives.result.sto : Long integer size is not compatible at /usr/lib/perl/5.14/Storable.pm line 379, at Blogs/Store.pm line 129
 at Blogs/Tags.pm line 1103
Tags.pm - loading geofile villes-geo-france-galichon-20130208.csv
Tags.pm - loading geofile villes-geo-france-complement.csv
Tags.pm - loading tags texts
additives

en - e120 : $VAR1 = undef;

fr - e440 : $VAR1 = undef;

fr - e333 : $VAR1 = undef;

fr - e440i : $VAR1 = undef;

fr - e440i :
cannot retrieve /root/src/product-opener/packager-codes/packager_codes.sto : Long integer size is not compatible at /usr/lib/perl/5.14/Storable.pm line 379, at Blogs/Store.pm line 129
 at Blogs/Food.pm line 2681
Can't use an undefined value as a HASH reference at Blogs/Food.pm line 2682.
Compilation failed in require at update_packager_codes.pl line 9.
BEGIN failed--compilation aborted at update_packager_codes.pl line 9.
root@debian:~/src/product-opener/cgi#

**Comment by boudeffa** [comment]
Then i ran 

root@debian:~/src/product-opener/scripts# perl build_tags_taxonomy.pl
Status: 500
Content-type: text/html

<h1>Software error:</h1>
<pre>Can't locate Blogs/Config.pm in @INC (@INC contains: /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at build_tags_taxonomy.pl line 8.
BEGIN failed--compilation aborted at build_tags_taxonomy.pl line 8.
</pre>
<p>
For help, please send mail to this site's webmaster, giving this error message
and the time and date of the error.

</p>
[Mon May  4 06:37:25 2015] build_tags_taxonomy.pl: Can't locate Blogs/Config.pm in @INC (@INC contains: /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at build_tags_taxonomy.pl line 8.
[Mon May  4 06:37:25 2015] build_tags_taxonomy.pl: BEGIN failed--compilation aborted at build_tags_taxonomy.pl line 8.
root@debian:~/src/product-opener/scripts#

**Comment by stephanegigandet** [comment]
Discussion regarding the "long integer" issue: http://comments.gmane.org/gmane.comp.lang.perl.pdl.devel/5644

**Comment by stephanegigandet** [comment]
Can you try to replace the packager_codes.sto file with this one?

http://world.openfoodfacts.org/files/packager_codes.sto.gz

It was saved with Storable::nstore instead of Storable::store. nstore saves file in network byte order instead of native byte order.

But OFF is also using Little Endian machines, so I'm not sure if it helps. The issue seems to be about the long type being a different number of bytes. The .sto file is different with store and nstore on my machine, so maybe the nstore version work.

**Comment by stephanegigandet** [comment]
For this error:

Can't locate Blogs/Config.pm

You can create a symbolic link "Blogs" in your scripts directory that points to the cgi directory.

**Comment by boudeffa** [comment]
Is the actual running server 32 bits or 64 bits ?

**Comment by boudeffa** [comment]
Now i got the same error with another file, the first error is gone by replacing the file as mentionned :+1: 

root@debian:~/src/product-opener/packager-codes# ls
FR-merge.csv  geocode_addresses.sto  geocode-uk.json  openlylocal-com-councils-all.json  packager_codes.sto  UK-merge.csv  uk_packager_codes_fsa_rating_ids.csv
root@debian:~/src/product-opener/packager-codes# mv packager_codes.sto packager_codes-old.sto
root@debian:~/src/product-opener/packager-codes# mv ~/downloads/packager_codes.sto .
root@debian:~/src/product-opener/packager-codes# ls
FR-merge.csv  geocode_addresses.sto  geocode-uk.json  openlylocal-com-councils-all.json  packager_codes-old.sto  packager_codes.sto  UK-merge.csv  uk_packager_codes_fsa_rating_ids.csv
root@debian:~/src/product-opener/packager-codes# cd ..
root@debian:~/src/product-opener# cd cgi/
root@debian:~/src/product-opener/cgi# ./startup.pl
./startup.pl: line 25: use: command not found
./startup.pl: line 27: syntax error near unexpected token `('
./startup.pl: line 27: `use Carp ();'
root@debian:~/src/product-opener/cgi# perl startup.pl
get_urlid : bonjour
..........
..........
SiteLang - overrides
cannot retrieve /root/src/product-opener/packager-codes/geocode_addresses.sto : Long integer size is not compatible at /usr/lib/perl/5.14/Storable.pm line 379, at Blogs/Store.pm line 129
 at Blogs/Food.pm line 2686
Can't use an undefined value as a HASH reference at Blogs/Food.pm line 2687.
Compilation failed in require at Blogs/Tags.pm line 93.
BEGIN failed--compilation aborted at Blogs/Tags.pm line 93.
Compilation failed in require at Blogs/Display.pm line 93.
BEGIN failed--compilation aborted at Blogs/Display.pm line 93.
Compilation failed in require at startup.pl line 56.
BEGIN failed--compilation aborted at startup.pl line 56.
root@debian:~/src/product-opener/cgi#

**Comment by Topheur** [comment]
I have the same error. Did you find a solution ? Thanks ;)

**Comment by boudeffa** [comment]
i thought it was fixed by someone that had installed productopener last week or 15 days
seems it's one about linux distro and a nameserver

**Comment by elbeho** [comment]
Storable is known to fail when the file is stored with one architecture (64bit) and restored in another (32bit).
On a side note: I recently installed my own instance (for test and dev purpose) of product-opener without facing this problem. I installed it on a 64-bit architecture.
IMHO let's forget 32bit architecture for the server.

**Comment by don1ruill** [comment]
thank you for reporting, yes, 32bit on a 64 bit machine doesn't work for productopener, i have tried 64 bits and it works
but i haven't yet an instance of the server

**Comment by Topheur** [comment]
Ok it's work for me for this issue thanks but I have another issue : when i try to launch apache 8001, i have a Perl error => Cannot load mod_perl.so into server, undefined symbol modperl_handler_name. Someone has the same problem ? Thanks

**Comment by stephanegigandet** [comment]
Well you need to install Apache with mod_perl. 
Instructions here: http://en.wiki.openfoodfacts.org/Product_Opener_installation_on_Debian_/_Ubuntu#Rebuild_Apache_2.2_and_mod_perl

**Comment by hangy** [comment]
This is an environment/infrastructure issue with the Storable module. I'm closing this, because it's nothing we can fix right now, except than moving away from Storable.
