### ISSUE TITLE
Unicode issues at the graph page

### ISSUE THREAD

**Issue by aleksejrs** [openfoodfacts/openfoodfacts-server#941]
https://world-ru.openfoodfacts.org/cgi/search.pl?action=process&tagtype_0=categories&tag_contains_0=contains&tag_0=en%3ACondensed%20milks&sort_by=unique_scans_n&page_size=20&axis_x=proteins&axis_y=carbohydrates&graph=1

Russian product names are displayed in broken Unicode, and links to products (with Russian for "product") are broken.

**Comment by hangy** [comment]
Apparently something in https://github.com/openfoodfacts/openfoodfacts-server/blob/483dba98960aa529cb2bfb3f3efb488640af885a/lib/ProductOpener/Display.pm#L3326 does not mix well. Generally, `encode_json` works well with UTF-8 (ie. in https://github.com/openfoodfacts/openfoodfacts-server/blob/80089c5c194ecbb9d12fe5d8b233900f06179439/cgi/product_multilingual.pl#L155), but something in there messes up the encoding. We should probably aim to phase out manual string concatenation for the Highcharts data object, but the first step is to see what's wrong here. FWIW, not a translation issue.
