### ISSUE TITLE
`page_count` is wrongly equivalent to `page_size`

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#9449]
Example: https://world.openfoodfacts.org/cgi/search.pl?action=process&json=1&nocache=1&tagtype_0=labels&tag_contains_0=contains&tag_0=en:Fabriqu%C3%A9%20en%20France&fields=code,labels&page_size=200

![image](https://github.com/openfoodfacts/openfoodfacts-server/assets/562352/8ff16559-9462-4022-b321-ade07d8966c8)

**Comment by benbenben2** [comment]
https://world.openfoodfacts.org/cgi/search.pl?action=process&json=1&nocache=1&tagtype_0=labels&tag_contains_0=contains&tag_0=en:Fabriqu%C3%A9%20en%20France&fields=code,labels&page_size=200&page=2


page_size: how many results per page
page_count: how many results in current page

**Comment by stephanegigandet** [comment]
@CharlesNepote It is working as expected, page_count is the number of results you have for the requested page.

If you request page 2 for instance: https://world.openfoodfacts.org/cgi/search.pl?action=process&json=1&nocache=1&tagtype_0=labels&tag_contains_0=contains&tag_0=en:Fabriqu%C3%A9%20en%20France&fields=code,labels&page_size=200&page=2

You get this:
count: 212,
page: 2,
page_count: 12,
page_size: 200,
