### ISSUE TITLE
Software error at https://world.openfoodfacts.org/category/bg:%D0%BA%D0%B0%D1%80%D1%82%D0%BE%D1%84%D0%B5%D0%BD%D0%B8-%D0%BD%D0%BE%D0%B0%D0%B7%D0%B5%D1%82%D0%B8

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#9465]
### What
I get

```Software error:
Wide character at /srv/off/lib/ProductOpener/Display.pm line 4618.
For help, please send mail to the webmaster ([contact@openfoodfacts.org](mailto:contact@openfoodfacts.org)), giving this error message and the time and date of the error.
``` 
on this page: https://world.openfoodfacts.org/category/bg:%D0%BA%D0%B0%D1%80%D1%82%D0%BE%D1%84%D0%B5%D0%BD%D0%B8-%D0%BD%D0%BE%D0%B0%D0%B7%D0%B5%D1%82%D0%B8 . I arrived on that link by clicking fr:pommes noisettes on this product: https://world.openfoodfacts.org/product/7610827778476/pommes-noisettes-31-07-24-coop

**Comment by stephanegigandet** [comment]
Fixed
