### ISSUE TITLE
Test that translated URLs are indeed URLs

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#949]

**Comment by hangy** [comment]
Shouldn't that be reviewed in crowdin?

**Comment by hangy** [comment]
> Ideally a consensus and proofreading is done by several people on Crowdin, and multilingual users thoroughly review the Pull request on GitHub, before it gets merged :-D

🤣 

I really don't know what I'm supposed to test here. Are you talking about the issues mentioned in #931?

**Comment by teolemon** [comment]
yup. A small regex to ensure it's lowercase, and starts with a / and no BLANKSPACE

**Comment by teolemon** [comment]
https://www.regexpal.com/96861

**Comment by hangy** [comment]
Sure, we can enforce the leading slash, but I'm not sure the other requirements are what's the problem in #931. Upper case letters and blanks can be fine in URLs, as long as the server maps it to something. In our case, the entries were translated to a page that doesn't exist in the lang/$lc/texts directory. Maybe we should try to check for that explicitly? (Even though I don't fully understand the way that `$texts{$textid}` is built.)
