### ISSUE TITLE
After signing-in, redirect users to the page they were on

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#95]
From Vince:

Let's remove the silly little page saying "hello <nick>" after you sign in. It really feels like a placeholder (maybe it is one). Redirecting to the index (or even better in some cases the product page the user was on) would make more sense.

**Comment by vince** [comment]
@stephanegigandet I think you're summoning the wrong developer. This project doesn't seem like anything I've contributed to although it does look interesting!

**Comment by stephanegigandet** [comment]
@vince: sorry about that, I got mixed up with the usernames we have on Slack.

**Comment by stephanegigandet** [comment]
There is some related code in session.pl already:

	my $next_action = param('next_action');
	my $url;
	
	if (defined $next_action) {
		if ($next_action eq 'product_add') {
			$url = "/cgi/product.pl?type=add&code=" . param('code');
		}
		elsif ($next_action eq 'product_edit') {
			$url = "/cgi/product.pl?type=edit&code=" . param('code');
		}
	}
	
	if (defined $url) {
		
		print STDERR "session.pl - redirection to $url\n";
	
		my $r = shift;
  
        $r->err_headers_out->add('Set-Cookie' => $cookie);
		$r->headers_out->set(Location =>"$url");
		$r->status(301);
		return 301;	
	}

**Comment by hangy** [comment]
Fixed with f792d2200411c26f5b045e5beca6e2389f093339
