### ISSUE TITLE
how can i complete successfully, I don't know how to complie the program.

### ISSUE THREAD

**Issue by yuanranyr** [openfoodfacts/openfoodfacts-server#9504]
process "/bin/sh -c cpanm --notest --quiet --skip-satisfied --local-lib /tmp/local/ \"Apache::Bootstrap\" &&     cpanm $CPANMOPTS --notest --quiet --skip-satisfied --local-lib /tmp/local/ --installdeps .     || ( for f in /root/.cpanm/work/*/build.log;do echo $f\"= start =============\";cat $f; echo $f\"= end =============\"; done; false )" did not complete successfully: exit code: 1
make: *** [build] Error 17

**Comment by benbenben2** [comment]
Hi @yuanranyr 
I would suggest asking on Slack. It will be easier.
Did you install docker? Which command did you try to run?

**Comment by alexgarel** [comment]
@yuanranyr it happened (in India) that some ISP where blocking cpanm !
Sometimes, it's just transiant problems on cpanm side.
It's hard to debug it for you.
