### ISSUE TITLE
For moderators, Show the presence of a CIQUAL/Agribalyse match in the panel for ingredient analysis

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#9534]
### Problem
- Make it easy to spot holes in Agribalyse/CIQUAL coverage, and easier to look for proxies, without overwhelming all users

### Proposed solution
- For moderators, Show the presence of a CIQUAL/Agribalyse match in the panel for ingredient analysis

### Part of
- #6499

**Comment by himanshisrestha** [comment]
I would love to work on this

**Comment by himanshisrestha** [comment]
@teolemon and @stephanegigandet How can I navigate to the ingredient analysis panel from my local machine

**Comment by himanshisrestha** [comment]
Also, ciqual_proxy_food_code and ciqual_food_code both to be displayed which ever is applicable for the particular ingredient?

**Comment by stephanegigandet** [comment]
> @teolemon and @stephanegigandet How can I navigate to the ingredient analysis panel from my local machine

Just view any product page, and in the ingredients section, click on "Details of the ingredients analysis"

![image](https://github.com/openfoodfacts/openfoodfacts-server/assets/8158668/3e0ec872-067a-430d-bcf4-6801b69c2959)
