### ISSUE TITLE
"Matière grasse végétale de palme" not detected

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#954]
"Matière grasse végétale de palme" n'est pas détecté par notre détecteur d'huile de palme.
Exemple : https://fr.openfoodfacts.org/produit/3560071013028/crunchy-chocolat-noir-intense-carrefour
69 produits qui ont de l'huile de palme et qui ne sont peut être pas détectés : https://fr.openfoodfacts.org/ingredient/matiere-grasse-vegetale-de-palme

**Comment by teolemon** [comment]
https://en.wiki.openfoodfacts.org/Global_palm_oil_taxonomy

**Comment by aleene** [comment]
Is the same as #522

**Comment by teolemon** [comment]
This is fixed.
