### ISSUE TITLE
 it is possible to create a product with nutrition facts, but with no_nutrition_facts=on

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#962]
I discovered that it is possible to create a product with nutrition facts, but with no_nutrition_facts=on.

There is a consistency issue here. A product with the no_facts checked cannot have nutrition facts and viceversa.

**Comment by hangy** [comment]
Removing API label. It's actually possible from the UI as well.

**Comment by hangy** [comment]
- [ ] If "Nutrition facts are not specified on the product" is checked, the UI should probably clear and disable `#serving_size` and `input.nutriment_value` (and enable those fields if unchecked)
- [ ] API should either throw an error (breaking change), clear/ignore the nutrition fields, or unset `no_nutrition_data` if values are present.
