### ISSUE TITLE
PNG files transparent background is transformed to black background if it's selected as front

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-server#9621]
On producer platform, this image: https://www.arcadie.fr/boutique/img.php?id_produit=459
was transformed to https://images.pro.openfoodfacts.org/images/products/org-arcadie/341/796/004/3973/front_fr.8.400.jpg with a black baground, it's ugly !

Not that the image by itself has a white and black background  !https://images.pro.openfoodfacts.org/images/products/org-arcadie/341/796/004/3973/2.jpg, it's the front selection which have a black background.

**Comment by alexgarel** [comment]
Things might happend in import.pm, nearby the `process_image_upload` call.

It would be important to cut this code and put those processing in specific functions… so that we can test them.

**Comment by stephanegigandet** [comment]
This happens because we remove transparency with white only if the file extension is .png. Here it's a png but without an extension. I will fix it.
