### ISSUE TITLE
The 0-100 salt warning does not take  into account that values are in mg and µg

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#9622]
### What
When entering a value for salt, I got a warning that the value must lie between something (0 and 100?). This warning does not seem to take into account that values in mg and µg.

### Steps to reproduce the behavior
 Happened on https://world.openfoodfacts.org/product/7501791654647/dolce-biscotti-world-table

### Expected behavior
No warning

### Additional context
<img width="609" alt="Screenshot 2024-01-06 at 09 14 16" src="https://github.com/openfoodfacts/openfoodfacts-server/assets/1329905/8633bd4b-415a-411d-8f1a-bf598dcdef54">

### Type of device

- Browser:Safari

**Comment by hangy** [comment]
mg values and other units are processed, correctly, in general ![image](https://github.com/openfoodfacts/openfoodfacts-server/assets/87124/9d0666b5-1de0-479d-98cf-e0999df5078a) however, there seems to be an issue if the unit is changed after the warning is initially shown, ie. ![image](https://github.com/openfoodfacts/openfoodfacts-server/assets/87124/8c73be0a-05bb-4928-b433-7ec0299ecd62)

Probably related to https://github.com/openfoodfacts/openfoodfacts-server/blob/7d295d10fcc8939cccfd093810cb0edb8a3c9449/templates/web/pages/product_edit/product_edit_form_display.tt.js#L44-L49 - maybe `check_nutrient` needs to be run when the unit is changed

**Comment by himanshi-154** [comment]
I will start to work on it today!

**Comment by komalverma04** [comment]
@himanshi-154 are you working on it?

**Comment by himanshi-154** [comment]
@komalverma04 Yes!

**Comment by nicholasyfu1** [comment]
Anyone still working on this? If not I can start

**Comment by benbenben2** [comment]
Solved by https://github.com/openfoodfacts/openfoodfacts-server/pull/8464
