### ISSUE TITLE
The carbon footprint KP is unexpectedly empty sometimes

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#9654]
I've finally found the issue and it's because of the carbon footprint KP.
[On the website](https://fr.openfoodfacts.org/produit/3760296730100/biere-deck-donohue), it's empty:
<img width="1275" alt="Screenshot 2024-01-15 at 08 31 12" src="https://github.com/openfoodfacts/smooth-app/assets/246838/2a9904f5-210e-4cb5-b7b6-f26c7707f4ac">

And I have a fix for the app to have the same thing:
<img width="362" alt="Screenshot 2024-01-15 at 08 31 08" src="https://github.com/openfoodfacts/smooth-app/assets/246838/fd474cd8-9bad-4689-9f09-7e8e3613a688">

But is-it the real fix that we want? (what's the goal of an empty KP)

Cc @teolemon / @stephanegigandet

_Originally posted by @g123k in https://github.com/openfoodfacts/smooth-app/issues/4948#issuecomment-1891466199_

**Comment by stephanegigandet** [comment]
json_debug_url: "https://static.openfoodfacts.org/srv/off/html/files/debug/knowledge_panels//carbon_footprint.3760296730100.json",
json_error: ", or } expected while parsing object/hash, at character offset 810 (before "coeur de march\x{c3}...") at /srv/off/lib/ProductOpener/KnowledgePanels.pm line 352.
",
