### ISSUE TITLE
Add a message to dissuade people from creating a Pro account with a personal email address

### ISSUE THREAD

**Issue by manon-corneille** [openfoodfacts/openfoodfacts-server#9658]
In the Pro account creation form (https://world.pro.openfoodfacts.org/cgi/user.pl), it would helpful to had this sentence on top of the field "Email", in red maybe so that it's visible.

"🚨 Please note that your Pro account will only be valid if you use your **professional e-mail address**. 
Our moderation team checks that the domain name is consistent with the organisation you which to join."

**Comment by teolemon** [comment]
I'm putting a P1 given how much strain it's putting on the permanent team.

**Comment by manon-corneille** [comment]
Hi folks, Charlotte noticed that the sentence had been added in French but wasn't translated into other languages. Example below on es.pro.openfoodfacts.org :-) 

![Uploading image.png…]()
