### ISSUE TITLE
Add a short explainer of the Nutri-Score in panel

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#9659]
### Add a short explainer
![image](https://github.com/openfoodfacts/openfoodfacts-server/assets/1689815/32667dd6-716b-441e-bac2-2a27edbbd439)

```
Le Nutri-Score est un logo sur la qualité nutritionnelle globale des produits. Le score de A à E est calculé en fonction des nutriments et aliments à favoriser (fibres, protéines, fruits et légumes, légumes secs…) et des nutriments à limiter (calories, acides gras saturés, sucres, sel). Le score est calculé à partir des données du tableau de la déclaration nutritionnelle qui figure au dos des emballages et des données de composition (fibres, fruits et légumes, légumes secs).
L’affichage de ce logo est recommandé par les pouvoirs publics sans obligation pour les entreprises. 
```

### Add a section header for computation details
```Détails du calcul du Nutri-Score :```

**Comment by deveshidwivedi** [comment]
Hi @teolemon! Do we want the explainer like the given format (red color for the description, green for the link) and position (positioned below all Nutri-score details)?

**Comment by teolemon** [comment]
We have fixed this in the revamped Nutri-Score panel
