### ISSUE TITLE
Add /org/[organisation name] facet directly in URL on the producers platform

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#9685]
Today we have an hidden facet on the producers platform for the organization name. It would be much better to make that facet directly visible in the URL (like other facets).

This would allow:
- org admins to easily access different organizations
- producers to have access to several organizations (e.g. for sub brands)
- sharing URLs that specify the organization

**Comment by TheSussex** [comment]
Do you mean to make the URL look like this: @stephanegigandet

`https://world.pro.openfoodfacts.org/cgi/user.pl?type=edit&userid=successabidemi&orgid=successventures`

**Comment by TheSussex** [comment]
Oh interesting. I’ll start working on it then. Thanks for the clarification.
