### ISSUE TITLE
The "Recently modified" view is broken on the home page

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#9686]
### What
- The "Recently modified" view is broken on the home page
- It has been like that for 2 to 3 days at least
- The same products are at the top. I have disabled custom ranking. I have refreshed my browser.

**Comment by stephanegigandet** [comment]
last_modified_t is a string for some products currently shown at the top, probably due to some recent changes

last_modified_by: "feat",
last_modified_t: "1704911712",
last_updated_t: 1705598678,
