### ISSUE TITLE
Broken translation in the footer

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#9687]
### What
- Broken translation in the footer (the empty and small button)

![image](https://github.com/openfoodfacts/openfoodfacts-server/assets/1689815/4ec77e4a-fdd6-411e-a455-7e1e5c849abb)

**Comment by teolemon** [comment]
I think @MonalikaPatnaik fixed it.

**Comment by MonalikaPatnaik** [comment]
Yes @teolemon it's been fixed now
