### ISSUE TITLE
Review hard-coded French code in empty parentid check

### ISSUE THREAD

**Issue by hangy** [openfoodfacts/openfoodfacts-server#970]
Is the hard-coded 'fr:' in this condition correct?

https://github.com/openfoodfacts/openfoodfacts-server/blob/4fff25949a0209c9112ba9beabdbb83d42ea268b/lib/ProductOpener/Tags.pm#L1447-L1450

**Comment by teolemon** [comment]
@hangy there's French harcoded stuff in Palm detection and missions as well

**Comment by hangy** [comment]
Yup, but this is specific to this if condition. No need to mix that. I think we have several issues about different hard coded strings. 😄
