### ISSUE TITLE
Investigate switching to `DOCUMENT_TEXT_DETECTION` on Google Cloud Vision for OCR

### ISSUE THREAD

**Issue by raphael0202** [openfoodfacts/openfoodfacts-server#9723]
We currently use `TEXT_DETECTION` annotation feature to extract text from images. [According to Google Cloud Vision documentation](https://cloud.google.com/vision/docs/ocr), there is another mode, `DOCUMENT_TEXT_DETECTION`, that's more optimized for dense texts and documents. This mode could possibly be better for our use case, i.e extracting text from product packaging images.

I investigated whether the switch is beneficial by:

- downloading the most 200 images uploaded on Open Food Facts
- using Google Cloud Vision API to extract text using the two aforementioned modes
- compared the results: only the text for each page/block/paragraph was compared, not the bounding boxes or language scores

Results:
- 142 OCR results were identical between the two modes (71%)
- 52 OCR results were different (27%)
- 4 OCR results were empty

Among the 52 OCR different results between the two mode, there is no clear winner:

- Some spaces are introduced/removed between modes, with no real implication (ex: before a ',' or '/')
- It looks like in `DOCUMENT_TEXT_DETECTION` there is som
e additional spellcheck going on as accents are added even if there were not present in the original text
- Sometimes the `DOCUMENT_TEXT_DETECTION` mode improves slightly the results, sometimes it's worse.

For reference, below are the two files to compare: `current.txt` is `TEXT_DETECTION`, `new.txt` is `DOCUMENT_TEXT_DETECTION`.

[current.txt](https://github.com/openfoodfacts/openfoodfacts-server/files/14109957/current.txt)
[new.txt](https://github.com/openfoodfacts/openfoodfacts-server/files/14109958/new.txt)

**Comment by alexgarel** [comment]
Thanks for studying this !

**Comment by raphael0202** [comment]
It had been on my TODO list for almost a year :smile:
