### ISSUE TITLE
How to get limited records?

### ISSUE THREAD

**Issue by Pereradilon9** [openfoodfacts/openfoodfacts-server#9727]
What parameter to use for get limited records because at a single I'm getting lot of results and I want to limit it to like 40,50.

**Comment by Pereradilon9** [comment]
Can this be done?

**Comment by alexgarel** [comment]
Hi @Pereradilon9, sorry for the late reply. 

As issue tracker is not for questions, can you come on [slack](https://slack.openfoodfacts.org/) to ask your question ? (#api channel). 

Please give us more information (which API, etc.) and verify if the answer is not already [in the documentation](https://openfoodfacts.github.io/openfoodfacts-server/api/) ! (see also [how to ask](https://stackoverflow.com/help/how-to-ask))



Thank you !
