### ISSUE TITLE
Feature request: add data-quality-error: insoluble/soluble fiber greater than total fiber

### ISSUE THREAD

**Issue by jayaddison** [openfoodfacts/openfoodfacts-server#9729]
### Problem
The `Fiber` nutritional field can have two sub-nutrient fields, `Soluble fiber` and `Insoluble fiber`.  These do not appear by default during product editing, but can be added manually by the editor.

It should be an error for the total of those values to be greater than the `Fiber` value.

### Proposed solution
Add a `data-quality-error` to detect this scenario and highlight it as a potential problem for data quality.

This could be similar to the existing [`Fructose plus glucose plus maltose plus lactose plus sucrose greater than sugars`](https://world.openfoodfacts.org/data-quality-error/en:nutrition-fructose-plus-glucose-plus-maltose-plus-lactose-plus-sucrose-greater-than-sugars) rule.

### Additional context
An example product where this could be detected is: https://world.openfoodfacts.org/product/0027331032050/spinach-wrap (this may be an error on the printed nutritional label)

### Code pointers
The similar sugars-total-validation rule mentioned previously is implemented here: https://github.com/openfoodfacts/openfoodfacts-server/blob/dc04d189c6010f9bc06b62d025056ddb7abc4ccd/lib/ProductOpener/DataQualityFood.pm#L1266-L1294

...and in the data quality taxonomy here: https://github.com/openfoodfacts/openfoodfacts-server/blob/main/taxonomies/data_quality.txt#L57-L58

### Number of products impacted
Unknown - I expect a relatively small number; in my experience so far, these subnutrient fields are not included on nutrition labels frequently.

### Time per product
Unknown.

### Mockups
N/A

### Part of
N/A

**Comment by Payne680** [comment]
Am  currently working on this issue @stephanegigandet

**Comment by jayaddison** [comment]
Thank you @Payne680!  That is working in today's v2.30.0 release - I added a missing nutrient to the product, and the problem with the fiber values is displayed:

![image](https://github.com/openfoodfacts/openfoodfacts-server/assets/55152140/0461353f-c2d9-4ccc-82b4-a47453b2e52b)

**Comment by Payne680** [comment]
You are welcome @jayaddison
