### ISSUE TITLE
Display app_name and app_uuid in edit history

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#9731]
From Slack:

David Pryor
  [il y a 12 heures](https://openfoodfacts.slack.com/archives/C032PK9D8/p1706816215626299?thread_ts=1706725921.871549&cid=C032PK9D8)
[@stephane](https://openfoodfacts.slack.com/team/U02KVRT1W)

https://world.openfoodfacts.org/product/01782877499/jack-links-beef-jerky-35g-teriyaki-jack-link-s
I submitted with my personal account and a uuid of
WjU4TEtJa1B2T2hWdWZNNzhnL3YyZUJvNXE2TUIxR05LK2crSVE9PQ

--

The uuid was saved in changes.sto but is not displayed.

**Comment by deveshidwivedi** [comment]
Hi! I wish to work on this. I understand that the objective that the app_name and app_uuid should be displayed when editing a product, but where will we fetch these from? And what is app_name here, is it similar to product name? 
Thank you!

**Comment by stephanegigandet** [comment]
@deveshidwivedi here is more details about the issue:

- When you edit a product, at the bottom of the page, we display the list of changes to that product. e.g.
![image](https://github.com/openfoodfacts/openfoodfacts-server/assets/8158668/c6da179a-66d1-406c-91aa-9d44e4599867)

- This list is built from the changes.sto file that all products have. In it we may record a uuid sent by apps.

- Currently when we have both a userid and a uuid, we display only the userid. This issue is to display both.

Related code is in lib/ProductOpener/Display.pm : sub display_product_history ($request_ref, $code, $product_ref) {

**Comment by anaritadauane** [comment]
Hi @deveshidwivedi, 

are you working on this issue?

**Comment by deveshidwivedi** [comment]
Yes @anaritadauane thanks for asking
