### ISSUE TITLE
Have a way of differentiating between data from manufacturers and data from consumers

### ISSUE THREAD

**Issue by manon-corneille** [openfoodfacts/openfoodfacts-server#9740]
When data is sent by a food manufacturer, it would be useful to flag it, like in the mock-up below. 

Several benefits to making it visible: 

- Make it identifiable by consumers -> higher level of trust 
- Identifiable by the producer -> easier to know what need to be updated or not (and what data is protected)
- Better for the reuser, who can decide to download “certified data only”

Note: this feature has been requested by a handful of producers and reusers. 

<img width="595" alt="image" src="https://github.com/openfoodfacts/openfoodfacts-server/assets/104015489/98cb8381-a44e-4cd2-a5cb-f941ccee4265">

**Comment by himanshisrestha** [comment]
How can I start working on this?
