### ISSUE TITLE
Add an event file to log events per product

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-server#9756]
For each products we currently have a changes.sto file that stores the changes events for a product.

I propose to add a events.sto to add other events like:
* scan (anonymously)
* (latter on) fields checks by users

This is an easy way to start to log those events in a robust and consistent way with a minimal effort and without affecting the product schema anymore.

I thinks it's better to keep this separated from changes.sto, because of the nature of the data (change product, does not change product).

A very simple API can get events for a specific product. 
Scan events can be consecutive to a get on a product with a specific code.
We will add more APIs to record events (like fields checks) later on.

Events should also be reported to the (to be activated) redis stream as [we plan to integrate them in openfoodfacts-query](https://github.com/openfoodfacts/openfoodfacts-query/issues/33)

**Comment by alexgarel** [comment]
I would also consider storing events as a json instead of a sto (I recently added a fast json parsing library), but it should keep a lock on the file as store does.

One possible drawback is that we will add more writes to the filesystem.

**Comment by stephanegigandet** [comment]
To me the whole point of openfoodfacts-events was to store scans (and other product activities like edits) specifically in a database (there's a whole discussion about that here: https://github.com/openfoodfacts/openfoodfacts-server/issues/1501 ).

I don't think storing scans in files is a good idea, unless it is just something temporary while openfoodfacts-events is deployed...).

**Comment by alexgarel** [comment]
I agree this is a bad idea !

Maybe we just have to store scans (and events) in their own database.

Either openfoodfacts-query handles that (but becomes more than a cache for this part), either we repurpose openfoodfacts-events for that only, and do not use it for change events, and openfoodfacts-query will aggregate all events types.

**Comment by alexgarel** [comment]
We spoke together at weekly meeting --> we will use openfoodfacts-query to store them.
