### ISSUE TITLE
Read API status code

### ISSUE THREAD

**Issue by hangy** [openfoodfacts/openfoodfacts-server#976]
Reported by @pilu on Slack:

> READ APis are always returning a 200 status code, even when the product is not found. is there a plan to upgrade the api to support the right HTTP statuses?

**Comment by naerion89** [comment]
+1

**Comment by hangy** [comment]
I actually implemented this a few weeks ago, but for some reason, Perl or Apache just sent another (server generated) 404 page to the browser, even though I printed JSON output to the response. 😕
