### ISSUE TITLE
[FOUNDATION] Add license Link header to product images?

### ISSUE THREAD

**Issue by hangy** [openfoodfacts/openfoodfacts-server#98]
Right now, images searches seem to have no idea about the image license of OFF images. (No images show when I used Google Image Search with site:openfoodfacts.org and selected a CC license.)

It might be interesting to link the CC license in the images' [HTTP header](http://www.otsukare.info/2011/07/12/using-http-link-header-for-cc-licenses) (in addition to microformats), so that bots can categorize them correctly.

**Comment by teolemon** [comment]
http://googlewebmastercentral.blogspot.fr/2009/08/specifying-images-license-using-rdfa.html

**Comment by stephanegigandet** [comment]
Added in proxy httpd.conf:

<Location "/images/products" >
Header set Link "<http://creativecommons.org/licenses/by-sa/3.0/>; rel='license'; title='CC-BY-SA 3.0'"
</Location>


wget -S http://fr.openfoodfacts.org/images/products/325/039/000/1065/front.8.400.jpg
--2015-05-08 18:16:20--  http://fr.openfoodfacts.org/images/products/325/039/000/1065/front.8.400.jpg
Résolution de fr.openfoodfacts.org... 188.165.39.31
Connexion vers fr.openfoodfacts.org|188.165.39.31|:80...connecté.
requête HTTP transmise, en attente de la réponse...
  HTTP/1.1 200 OK
  Date: Fri, 08 May 2015 16:16:20 GMT
  Server: Apache/2.2.23 (Unix)
  Last-Modified: Mon, 03 Nov 2014 15:53:47 GMT
  ETag: "5247ce7-ce54-506f65a1b18c0"
  Accept-Ranges: bytes
  Content-Length: 52820
  Cache-Control: max-age=864000
  Expires: Mon, 18 May 2015 16:16:20 GMT
  Link: <http://creativecommons.org/licenses/by-sa/3.0/>; rel='license'; title='CC-BY-SA 3.0'
  Keep-Alive: timeout=5, max=100
  Connection: Keep-Alive
  Content-Type: image/jpeg

**Comment by stephanegigandet** [comment]
Also added some microformats (on .net and .info right now)

````
<div id="drop_front" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog" about="http://static.openfoodfacts.net/images/products/848/001/707/0739/front.7.full.jpg" >
<h2 id="modalTitle">Produit</h2>
<img src="http://static.openfoodfacts.net/images/products/848/001/707/0739/front.7.full.jpg" alt="Oeufs de Lompe Noir  - Produit" />
<a class="close-reveal-modal" aria-label="Close" rel="licence" href="http://creativecommons.org/licenses/by-sa/3.0/">&#215;</a>
</div>
