### ISSUE TITLE
Pro accounts with missing organisation

### ISSUE THREAD

**Issue by manon-corneille** [openfoodfacts/openfoodfacts-server#9819]
I’m surprised to see a lot of new accounts recently with no org. I’ve tried to reproduce the bug by creating a new account with no org but I get the message: error_missing_org

Also, we don't see the org_name either

![Image](https://github.com/openfoodfacts/openfoodfacts-server/assets/104015489/52a29811-688c-423d-b54b-1d7f71448796)

**Comment by alexgarel** [comment]
This seems to be users without any org trying to export products to the public database from the producer platform (and they haven't created products, even in their private space).

**Comment by himanshi-154** [comment]
@alexgarel may I know more details on how I can actually solve this issue?
