### ISSUE TITLE
data restored from mongodb dumb throwing bson error on _id field

### ISSUE THREAD

**Issue by Safvan-tsy** [openfoodfacts/openfoodfacts-server#9847]
Downloaded MongoDB dump from https://world.openfoodfacts.org/data

Im using the below command to take the data to my db
mongorestore -h localhost:27017 -d db-name /off/dump/products/

products folder has these two files : products.bson  and products.metadata.json
After restore the value of _id is not coming as type of mongodb Objectid . its a string  eg: _id: "0000000000"

I want the _id to be type of mongodb ObjectId

**Comment by stephanegigandet** [comment]
@Safvan-tsy We use a string (the barcode) for the _id field.

See https://www.mongodb.com/docs/manual/core/document/

"The field name _id is reserved for use as a primary key; its value must be unique in the collection, is immutable, and may be of any type other than an array."
