### ISSUE TITLE
Open Beauty Facts logo broken in production

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#9849]
### What
- Open Beauty Facts logo broken in production
<img width="562" alt="image" src="https://github.com/openfoodfacts/openfoodfacts-server/assets/1689815/3c91da72-842a-447e-98d9-55283a91a94c">

**Comment by alexgarel** [comment]
`site-specific` symlink was missing in `po/` folder

I added it and relaunched the `build_lang.pl`

Then `sudo systemctl restart apache2`
