### ISSUE TITLE
bug: missing assets on presskit page - openfoodfacts-web not exposed !

### ISSUE THREAD

**Issue by Valimp** [openfoodfacts/openfoodfacts-server#9859]
### What
Missing lot of assets on presskit page

### Steps to reproduce the behavior:
1. Go to : [Presskit page](https://world.openfoodfacts.org/presskit)
2. Scroll down
3. See some assets missing

### Expected behavior
These assets simply don't exist

### Screenshots
<img width="1470" alt="Capture d’écran 2024-03-01 à 14 16 10" src="https://github.com/openfoodfacts/hunger-games/assets/112864841/c06b28f4-5416-405b-ac4a-a116a6c1e342">
<img width="1341" alt="Capture d’écran 2024-03-01 à 14 16 25" src="https://github.com/openfoodfacts/hunger-games/assets/112864841/dd9986c0-04a6-4999-95b1-4de7875d4414">

I made a list of missing images and svg :

https://world.openfoodfacts.org/images/eco-score-logos/ecoscore-b.svg
--
https://static.openfoodfacts.org/images/misc/mobileapp/new_openfoodfacts_app_en_light_3_screenshots.png
https://world.openfoodfacts.org/images/logos/logo-variants/MONO_CMJN_VERTICAL_WHITE_BG_OFF.svg
https://world.openfoodfacts.org/images/eco-score-logos/ecoscore-bw-a.svghttps://world.openfoodfacts.org/images/eco-score-logos/ecoscore-bw-b.svghttps://world.openfoodfacts.org/images/eco-score-logos/ecoscore-bw-c.svghttps://world.openfoodfacts.org/images/eco-score-logos/ecoscore-bw-d.svghttps://world.openfoodfacts.org/images/eco-score-logos/ecoscore-bw-e.svg
https://world.openfoodfacts.org/illustrations/un-sdg-logos/EN_SDG_Goals_03.pnghttps://world.openfoodfacts.org/illustrations/un-sdg-logos/EN_SDG_Goals_12.pnghttps://world.openfoodfacts.org/illustrations/un-sdg-logos/EN_SDG_Goals_13.pnghttps://world.openfoodfacts.org/illustrations/un-sdg-logos/EN_SDG_Goals_14.pnghttps://world.openfoodfacts.org/illustrations/un-sdg-logos/EN_SDG_Goals_15.pnghttps://world.openfoodfacts.org/illustrations/un-sdg-logos/EN_SDG_Goals_17.png
https://world.openfoodfacts.org/images/misc/nutriscore/nutriscore-white-d.svg
https://world.openfoodfacts.org/cop26/podcast/podcast-thumbnail-en.jpghttps://world.openfoodfacts.org/cop26/podcast/podcast-thumbnail-fr.jpgAll podcast icons

https://world.openfoodfacts.org/images/eco-score-logos/ecoscore-b.svg
https://static.openfoodfacts.org/images/misc/mobileapp/new_openfoodfacts_app_en_light_3_screenshots.png
https://world.openfoodfacts.org/images/logos/logo-variants/MONO_CMJN_VERTICAL_WHITE_BG_OFF.svg
https://world.openfoodfacts.org/images/eco-score-logos/ecoscore-bw-a.svg
[https://world.openfoodfacts.org/images/eco-score-logos/ecoscore-bw-b.svg](https://world.openfoodfacts.org/images/eco-score-logos/ecoscore-bw-a.svg)
[https://world.openfoodfacts.org/images/eco-score-logos/ecoscore-bw-c.svg](https://world.openfoodfacts.org/images/eco-score-logos/ecoscore-bw-a.svg)
[https://world.openfoodfacts.org/images/eco-score-logos/ecoscore-bw-d.svg](https://world.openfoodfacts.org/images/eco-score-logos/ecoscore-bw-a.svg)
[https://world.openfoodfacts.org/images/eco-score-logos/ecoscore-bw-e.svg](https://world.openfoodfacts.org/images/eco-score-logos/ecoscore-bw-a.svg)
https://world.openfoodfacts.org/illustrations/un-sdg-logos/EN_SDG_Goals_03.png
[https://world.openfoodfacts.org/illustrations/un-sdg-logos/EN_SDG_Goals_12.png](https://world.openfoodfacts.org/illustrations/un-sdg-logos/EN_SDG_Goals_03.png)
[https://world.openfoodfacts.org/illustrations/un-sdg-logos/EN_SDG_Goals_13.png](https://world.openfoodfacts.org/illustrations/un-sdg-logos/EN_SDG_Goals_03.png)
[https://world.openfoodfacts.org/illustrations/un-sdg-logos/EN_SDG_Goals_14.png](https://world.openfoodfacts.org/illustrations/un-sdg-logos/EN_SDG_Goals_03.png)
[https://world.openfoodfacts.org/illustrations/un-sdg-logos/EN_SDG_Goals_15.png](https://world.openfoodfacts.org/illustrations/un-sdg-logos/EN_SDG_Goals_03.png)
[https://world.openfoodfacts.org/illustrations/un-sdg-logos/EN_SDG_Goals_17.png](https://world.openfoodfacts.org/illustrations/un-sdg-logos/EN_SDG_Goals_03.png)
https://world.openfoodfacts.org/images/misc/nutriscore/nutriscore-white-d.svg
https://world.openfoodfacts.org/cop26/podcast/podcast-thumbnail-en.jpg
https://world.openfoodfacts.org/cop26/podcast/podcast-thumbnail-fr.jpg
All podcast icons

**Comment by alexfauquette** [comment]
>  you can move the issue to another repo

Done :+1:

**Comment by alexgarel** [comment]
The problem is much more important than though: all of openfoodfacts-web/html is not exposed yet !

I will handle this.

**Comment by alexgarel** [comment]
This was done in #9865
