### ISSUE TITLE
Improve the style of the header and cells of the import spreadsheet template on the producers platform

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#9873]
This issue is part of #9872 , please see the parent issue for context and guidance on how to work on this issue.

 The current import template (generated by https://world.pro.openfoodfacts.org/cgi/generate_sample_import_file.pl ) looks like this:

![image](https://github.com/openfoodfacts/openfoodfacts-server/assets/8158668/2385ba48-baac-4f7c-afb5-f338ebe44ea8)

And we want to make it look like the template proposal: https://docs.google.com/spreadsheets/d/148PWIsSfDRsj8gLJ7cHbQtdapIEscUwX/edit#gid=1221199414 :

![image](https://github.com/openfoodfacts/openfoodfacts-server/assets/8158668/8bc253fb-770f-40ff-8810-575c7f7c0ca8)

Specifically we need:
- blue background, padding and centering for header cells
- italic for the description and example lines (will be added by #9874 )

To test your changes in a local dev environment once you have followed the quick start guide https://github.com/openfoodfacts/openfoodfacts-server/blob/main/docs/dev/how-to-quick-start-guide.md , you can click on http://world.openfoodfacts.localhost/cgi/generate_sample_import_file.pl to generate the spreadsheet template.

**Comment by ayushichoudhary-19** [comment]
@stephanegigandet I am an Outreachy Applicant and would love to work on this issue! Please assign it to me.

**Comment by ayushichoudhary-19** [comment]
I am working on this issue.

**Comment by anaritadauane** [comment]
Hi, I'm interested in this issue. 
What about column B and C? Should they be replaced with the 'Product Name' column?

**Comment by stephanegigandet** [comment]
@anaritadauane : columns B and C are optional columns, in one version of the spreadsheet template they won't be generated (see this bug: https://github.com/openfoodfacts/openfoodfacts-server/issues/9876 )

**Comment by anaritadauane** [comment]
I have fixed the errors

**Comment by TheSussex** [comment]
Hi @anaritadauane, are you currently working on this?

I would like to pick it up if you're not.

**Comment by anaritadauane** [comment]
> @anaritadauane : columns B and C are optional columns, in one version of the spreadsheet template they won't be generated (see this bug: #9876 )

Thank you @stephanegigandet

**Comment by anaritadauane** [comment]
> Hi @anaritadauane, are you currently working on this?
> 
> I would like to pick it up if you're not.

Hey @TheSussex, 

I'm working on this issue.

**Comment by stephanegigandet** [comment]
This issue has been completed :)
