### ISSUE TITLE
Generate an import spreadsheet template with mandatory fields only on the producers platform

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#9876]
This issue is part of #9872 , please see the parent issue for context and guidance on how to work on this issue.

In the import template generated by https://world.pro.openfoodfacts.org/cgi/generate_sample_import_file.pl , add a parameter ?fields=mandatory to output only mandatory fields.

**Comment by ayushichoudhary-19** [comment]
@stephanegigandet I would love to work on this issue, please assign it to me!

**Comment by ayushichoudhary-19** [comment]
I have started working on this issue.

**Comment by TheSussex** [comment]
Hi @ayushichoudhary-19 , are you currently working on this?
