### ISSUE TITLE
Add the list of all categories in the taxonomy to the import spreadsheet template on the producers platform

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#9877]
This issue is part of #9872 , please see the parent issue for context and guidance on how to work on this issue.

In the import template generated by https://world.pro.openfoodfacts.org/cgi/generate_sample_import_file.pl add a sheet with the list of all entries in the categories taxonomy, translated in the local language, and sorted alphabetically.

See the template proposal: https://docs.google.com/spreadsheets/d/148PWIsSfDRsj8gLJ7cHbQtdapIEscUwX/edit#gid=1221199414 :

**Comment by kemsguy7** [comment]
Kindly assign this issue to me

**Comment by TheSussex** [comment]
I have started working on this.

**Comment by TheSussex** [comment]
I finally got it to work!
