### ISSUE TITLE
Add a description line to the import spreadsheet template on the producers platform

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#9879]
This issue is part of https://github.com/openfoodfacts/openfoodfacts-server/issues/9872 , please see the parent issue for context and guidance on how to work on this issue.

We want to add 2 lines to the import template (generated by https://world.pro.openfoodfacts.org/cgi/generate_sample_import_file.pl ):

- a description line that should contain what we currently have in the comments in the header line (and then we can remove the comments)
- an example line

This issue is about adding the description line.

We also need add one first column that just contains "description" and "example" for those 2 lines, and nothing for the the other rows.

See the template proposal: https://docs.google.com/spreadsheets/d/148PWIsSfDRsj8gLJ7cHbQtdapIEscUwX/edit#gid=1221199414 :

We will need to change the importing so that rows that contain something in the first column are skipped.

**Comment by deeksha81** [comment]
hey im interested in solving this issue

**Comment by sangwan-smriti** [comment]
hey, im interested in solving this issue.
