### ISSUE TITLE
[FOUNDATION] Incorrect lang code for country specific subdomains

### ISSUE THREAD

**Issue by hangy** [openfoodfacts/openfoodfacts-server#99]
Excerpt from http://us-es.openfoodfacts.org/

    <html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://www.facebook.com/2008/fbml"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:food="http://data.lirmm.fr/ontologies/food#" xmlns:gr="http://purl.org/goodrelations/v1#">
    <head>
    <title>Open Food Facts - Estados Unidos</title>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <meta name="language" content="es-ES" />

First off, OFF uses an [undefined](http://stackoverflow.com/a/4417940/11963) HTML meta tag

    <meta name="language" content="es-ES" />

The language information should probably be moved to the `<html>` tag, or at least the correct `http-equiv="content-language"` tag should be used instead. Also, the language code is incorrect. Since the us-es subdomain shows products from the USA in Spanish, the correct code in the HTML document should be `es-US`.

**Comment by stephanegigandet** [comment]
Fixed in the new foundation version, we now have something like:
````
<!doctype html>
<html class="no-js" lang="es">
  <head>

**Comment by hangy** [comment]
Agreed, but the `lang` attribute of the `html` element could be more specific (ie. `es-US` in my first example), and the undefined `<meta name="language" content="es-ES" />` is still there.

**Comment by stephanegigandet** [comment]
I removed the meta language, and updated .net and .info, I had forgotten to restart them.

Regarding es-US, I'm a bit unsure. Will clients fall back to es if there isn't a specific es-US locale supported by the system / the browser?

In practice OFF currently does not support language variants. UK and US, MX and ES, PT and BR have the same translations.

**Comment by hangy** [comment]
If the region code should be used for varying translations only, then I agree. I was thinking that while those pages use the same translations, they do list different products (filtered to the specific country) on the (search engine discoverable) index page. But I'll admit that I have no idea, if changing this would actually change anything for users or search engines. :wink:
