### ISSUE TITLE
Return user information in auth.pl if sent with a specific parameter (eg. ?info=json) 

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-server#9910]
We need to know some information like:

* is a user a moderator
* what is it's preferred language

for services like open-prices / nutripatrol / hungergames

It should be quite easy to add this functionality to auth.pl so that if there is a ?info=json parameter, we would return a json with useful information (maybe avoid revealing email for now)

**Comment by hangy** [comment]
What's the timeframe? We want to move a lot of this data to Keycloak (#1596), so that it could be available as user claims. If we add it to `auth.pl` now (it's really not an auth feature, but a user profile feature, but I digress, we'd have to proxy the request it to Keycloak afterwards.

**Comment by alexfauquette** [comment]
> NutriPatrol needs it to be deployed

If it's blocking, you still have the option of hard coding a list of username as nutripatrol moderator
