### ISSUE TITLE
Missing image

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#9913]
### What
An image link is broken

### Steps to reproduce the behavior
https://nl.openfoodfacts.org (at the bottom

### Screenshot/Mockup/Before-After
<img width="1178" alt="Screenshot 2024-03-14 at 09 10 03" src="https://github.com/openfoodfacts/openfoodfacts-server/assets/1329905/d30824fb-5380-4379-a0b6-20dd18734947">

**Comment by stephanegigandet** [comment]
[Reported as working on Slack by Himanshi Sharma](https://openfoodfacts.slack.com/archives/C02LDQDDD/p1710759553009779), so closing. Also this icon will go away soon, the Microsoft App Store doesn't exist anymore. (I removed it in a [draft PR](https://github.com/openfoodfacts/openfoodfacts-server/pull/9888) already)
