### ISSUE TITLE
Add support for the SignalConso experiment

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#9928]
### Problem
- Add support for the SignalConso experiment
- We got the URLs to create a knowledge panels with a button, as well as their target mockups (we also have our own)
- You can see it in production: https://signal.conso.gouv.fr/fr/alimentaire-codebarres/faire-un-signalement?gtin=3017620422003
- The URL is always the same: https://signal.conso.gouv.fr/fr/alimentaire-codebarres/faire-un-signalement?gtin=LE_CODE_BARRES_ICI
- This URL is made especially for you. It cannot be discovered by browsing the site.
- "It is now up to you to build this link on your product sheets, if possible following the model that I suggested" https://excalidraw.com/#json=JVKcZOSmxXzWiZnRSAvcO,7wdyPlzRZT2fTjaeMqkuVQ

### Part of
- #Product page

**Comment by stephanegigandet** [comment]
@teolemon Can you add the details in the bug, or link to related docs?

**Comment by teolemon** [comment]
done @stephanegigandet

**Comment by stephanegigandet** [comment]
Done in https://github.com/openfoodfacts/openfoodfacts-server/pull/10106
