### ISSUE TITLE
Add `isInTaxonomy` boolean flag in ingredient parsing result

### ISSUE THREAD

**Issue by alexfauquette** [openfoodfacts/openfoodfacts-server#9930]
### Problem

The API does not provide a clean way to know if an ingredient is already in the taxonomy or not.

We can guess from the fact that an ingredient get a `ciqual_proxy_food_code` or `vegetarian` attribute that it's in the taxonomy, but there is no way to know when an ingredient is not in the taxonomy.

### Proposed solution

Adding `isInTaxonomy` for all ingredients at the same time the server is looking for `ciqual_proxy_food_code`

### Additional context

Would be useful for [hunger game ingredients](https://hunger.openfoodfacts.org/ingredients). And I think robotoff also needs it and for now is using a workaround

### Code pointers

No idea where it is

### Part of
- #5523

**Comment by himanshisrestha** [comment]
I'm interested in this issue and would like to resolve this.

**Comment by stephanegigandet** [comment]
Related code is in lib/ProductOpener/Ingredients.pm
in the parse_ingredients_text_service() function (it's a huge one).

At the end we should add a boolean field "is_in_taxonomy", using the exists_taxonomy_tag function, near this code:

```
			if (not $skip_ingredient) {

				my %ingredient = (
					id => get_taxonomyid($ingredients_lc, $ingredient_id),
					text => $ingredient
				);
```

Note that a lot of tests will need to be updated after that, so you will need to run "make update_tests_results", and possibly change manually some tests results in *.t files

**Comment by stephanegigandet** [comment]
Note that Perl doesn't have Boolean type, so instead we should return 1 for true, and 0 for false.

**Comment by himanshisrestha** [comment]
I'm understanding the function refered to. Thank you for the references
