### ISSUE TITLE
Rename "username" and "user name" to "public user id"

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#9942]
### What
- In the forms for users to sign in, create an accound, and edit parameters, we ask for / display the user id, but the field name is "username" or "user name", which is confusing (some users think they should enter their actual name). It would be clearer to name that field "user id".
### Code pointers
Needed:
in po/common/common.pot and po/common/en.po:
- change all the stringids that contain username / user_name to contain user_id instead
- change those string values to use "user id" instead of "username" or "user name".

**Comment by himanshi-154** [comment]
I will work on this issue!!

**Comment by stephanegigandet** [comment]
@himanshi-154 Please wait for [the discussion on Slack,](https://openfoodfacts.slack.com/archives/C02LDQDDD/p1710759977464589) just to make sure everyone agrees it is a good thing.

**Comment by himanshi-154** [comment]
Sure @stephanegigandet, I will keep myself updated on the discussion!!

**Comment by TheSussex** [comment]
I already worked on a fix for this on Friday after I raised the issue @himanshi-154 , was just waiting for A response and go-ahead from @stephanegigandet so I can make a PR.

**Comment by john-gom** [comment]
Not sure we should do this now as Keycloak supersedes it

**Comment by TheSussex** [comment]
Oh I see, I'll follow the discussion on slack to know the final consensus. Thank you.

**Comment by CharlesNepote** [comment]
I have renamed the title of this issue, because I think it's very important to let people understand, during account creation, that the user id is public. Many people ask us to change their username (user id) because they didn't understand that it will be public.

See #5338
