### ISSUE TITLE
Convert the view link into a "View this revision" button

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#9943]
### Problem
- Convert the view link into a "View this revision" button

### Screenshot
![image](https://github.com/openfoodfacts/openfoodfacts-server/assets/1689815/0ed43721-b707-4d79-bf88-8b47d435ea63)

### Part of
- #5612

**Comment by himanshi-154** [comment]
Okay I will start working on it!

**Comment by anaritadauane** [comment]
If you are not working on this @himanshi-154, can I start working on it?

**Comment by stephanegigandet** [comment]
This is the product history that is displayed at the bottom of the product edit page, and for admins and moderators at the bottom of the product page as well.

**Comment by himanshisrestha** [comment]
@himanshi-154 Please confirm have you completed you PR on this .. Else I'll do it

**Comment by himanshisrestha** [comment]
As there is no feedback, I'm starting to work on this issue
